== Chapter II. Charges Against Friends

The sudden rise and rapid growth of the new Society caused, as might be expected,
much excitement in many parts of England.
The Friends and their principles were often misunderstood,
and many false charges were made against them,
which filled the popular mind with rage and prejudice.
Of this the early records of our Society furnish many illustrations.
The priests of that day were among the foremost of those who thus slandered Friends,
and it is not surprising that it should have been so,
for the doctrines of Friends as to the ground and nature of Gospel ministry and their
contention that the system of tithes had no proper place in the Christian dispensation,
struck at their business.
When at Wakefield in 1652,
George Fox said the priest of that church raised many wicked slanders upon him, as:

[.embedded-content-document]
--

That I carried bottles about with me, and made people drink of my bottles,
which made them follow me.
And, that I rid upon a great black horse,
and was seen in one county upon my black horse in one hour,
and in the same hour in another county three score miles off.
With these lies he fed his people,
to make them think evil of the Truth which I had declared among them.
But by those lies he preached many of his hearers away from him; for I travelled on foot,
and had no horse at that time; and that the people generally knew.

--

Such slanderous reports would seem childish and useless at the present day,
but at that time there still existed among the people
of England a wide-spread belief in witchcraft,
to which this priest maliciously appealed.
Many hundreds of people were put to death as witches,
indeed the last of these murders in England occurred more
than sixty years after the date of which we are speaking.
So infatuated with this superstition were the people,
that one Hopkins made a regular business of going about the country and
freeing the different neighborhoods of witches for a stated fee.
Many were the innocent victims that were put to death through his means.
One of his methods of determining their guilt was to throw them into a pond of water.
If they floated it was regarded as a proof that they were
witches--but if they sank they were supposed to be innocent.

Rutty in his history of Friends in Ireland,
mentions that Thomas Wight attended a Friends`' Meeting near Bandon, out of curiosity,
but "`Finding that the people sat silent for a long time, he began to be very uneasy,
and to think within himself, that as he had heard the Quakers were witches,
he might be bewitched if he should stay any longer.`"
Elizabeth Bathurst, in [.book-title]#Truth Vindicated#,
has some remarks which explain Thomas Wight`'s uneasiness.
She says:

[.embedded-content-document]
--

Some not knowing the way of the Spirit in themselves,
and yet seeing the evident change which has been wrought upon others by virtue of the
powerful operation of this spiritual principle or power of God in their consciences,
they have hereupon confidently affirmed the same to be effected
by the art of witchcraft and diabolical enchantment;
which affirmation, though false,
yet may it truly be said to be fixed as a scarecrow or ghostly apparition,
to frighten people from so much as looking towards this religion...
They have enviously cast upon the professors of it,
as the means whereby they convert and turn people to it;
alleging it as a matter of wonder that any should be so strangely altered both in countenance,
carriage and communication, and that on a sudden too (as some have been observed to be),
unless it were by the power of sorcery, or some satanical possession.
And hence have they mocked at and derided that godly fear and holy trembling,
that has been made to appear in some when the terrors
of the Almighty took hold of them by reason of sin,
as though this were occasioned through some frenzy humor,
being the product of natural weakness and defect,
or else produced by the invincible force of magic art,
which the creature can no ways resist.
So that this has been a main argument why people should not adventure
themselves so much as to go into a Quaker meeting for fear of the great
danger (that some suppose there is) of being charmed into that religion;
which fear has so much affrighted the hearts of some,
that notwithstanding there are good desires in them
after satisfaction in matters of religion,
and they have freely confessed even in my hearing:
"`That this seems to be the way to attain the same; yet they never were,
nor do they dare to come among this people, namely, the Quakers,
for fear of being forcibly possessed with the belief of their principles.`"

--

A belief in demoniacal possession had come down from the earliest ages,
and had been fanned into a new intensity at the close of the middle ages by the
physical calamities and moral scepticisms which threw their gloom over the world.
But it was not till the chaos and turmoil of the Reformation
put its strain on the spiritual imagination of men,
that the belief deepened into a general panic.
The panic was common to both Catholics and Protestants; it was in Catholic countries,
indeed,
that the persecution of supposed witches was carried on longest and most ruthlessly.
Among Protestant countries, England was the last to catch the general terror;
but it was not till the close of Queen Elizabeth`'s
reign that it became a marked feature of the time.

To men like the Puritans, says Green, in his [.book-title]#History of the English People#,
who looked on the world about them and the soul within them as
battle-fields for a never-ceasing contest between God and the devil,
it was natural enough to ascribe every evil that happened to many,
either in soul or body, to the invisible agency of the spirit of ill.
A share of his supernatural energies was the bait by which
he was held to lure the wicked to their own destruction;
and women, above all,
were believed to barter their souls for the possession of
power which lifted them above the weakness of their sex.

A bull issued by Pope Innocent VIII, in 1484, and several by succeeding popes,
tended to increase the agitation of the public mind on this subject.
A writer in _Chambers`' Encyclopedia_, thus describes the result:
"`A panic fear of witchcraft took possession of society.
If anyone felt an unaccountable illness, or a peculiar pain in any part of his body,
or suffered any misfortune in his family or affairs; or,
if a storm arose and committed any damage by sea or land; or,
if any cattle died suddenly; or, in short, if any event,
circumstance or thing occurred out of the ordinary routine
of daily experience--the cause of it was witchcraft.
To be accused was to be doomed: for it rarely happened that proof was lacking.
If the accused did not at once confess,
they were ordered to be shaved and closely examined
for the discovery of the devil`'s marks;
and if any strange mark was discovered,
there remained no longer any doubt of the party`'s guilt.
Failing in this kind of evidence, torture was applied.
A large proportion of the accused witches, in order to avoid these preliminary horrors,
confessed and were forthwith led to execution.
Others seemed to confess voluntarily,
being probably either insane persons or feeble-minded beings,
whose reason had been distorted by brooding over the popular witchcraft code.`"

In Germany, and other parts of Europe,
the prosecutions were carried to a frightful extent.
In Geneva five hundred persons were burnt in three
months--1515-1516. In the district of Como,
one thousand were burnt in 1524, and one hundred per annum for several years afterwards.
The mania was later in spreading in England and Scotland,
but during the era of the Long Parliament, which sat from 1640 to 1653,
three thousand persons were put to death as witches.
Even the good and enlightened Sir Matthew Hale, in 1664,
tried and condemned two women for bewitching children.
The last of these murders in England was in 1716.
In Scotland, the whole number of victims has been estimated at four thousand.
Both there and in New England the clergy were the prime movers--but the force
of this wild delusion spent itself towards the end of the seventeenth century.
But a belief in it long lingered among the more ignorant classes, and still exists.

Another false charge brought against our early Friends was that of blasphemy--a
crime which by the laws of England at that time was punishable with death--and
efforts were made to inflict this penalty upon George Fox and others.
The spiritual views of religion which they held,
and their rejection of outward ordinances and forms, and of all priestcraft,
enraged many and led them in some cases to become false accusers.
George Fox thus relates his trial on this charge,
which took place at the sessions of Court at Lancaster:

[.embedded-content-document]
--

There appeared against me about forty priests.
These had chosen one Marshal, a priest of Lancaster, to be their orator;
and had provided one young priest and two priests`' sons to bear witness against me,
who had sworn beforehand that I had spoken blasphemy.
When the justices were set,
they heard all that the priests and their witnesses could say and charge against me,
their orator Marshal sitting by and explaining their sayings for them:
but the witnesses were so confounded that they discovered themselves to be false witnesses.

There were then in court several who had been at that meeting,
wherein the witnesses swore I spoke those blasphemous
words which the priests accused me of;
and these, being men of integrity and reputation in the country,
did declare and affirm in court,
That the oath which the witnesses had taken against me was altogether false;
and that no such words as they had sworn against me were spoken by me at that meeting.
Indeed, most of the serious men of that side of the country, then at the sessions,
had been at that meeting, and had heard me both at that and other meetings also.
This was taken notice of by colonel West, who being a justice of the peace,
was then upon the bench, and said:
"`That he never saw so many people and good faces together in all his life.`"
Then turning himself to me, he said in the open sessions: "`George,
if you have anything to say to the people, you may freely declare it.`"
I was moved of the Lord to speak; and as soon as I began, priest Marshal,
the orator for the rest of the priests, went his way.
That which I was moved to declare was this:
"`That the Holy Scriptures were given forth by the spirit of God;
and all people must first come to the spirit of God in themselves,
by which they might know God and Christ, of whom the prophets and apostles learned:
and by the same spirit know the Holy Scriptures;
for as the spirit of God was in them that gave forth the Scriptures,
so that same spirit must be in all them that come to understand the Scriptures.
By which spirit they might have fellowship with the Father, with the Son,
with the Scriptures, and with one another:
and without this spirit they can know neither God, Christ, nor the Scriptures,
nor have a right fellowship one with another.`"

I had no sooner spoken those words, but about half a dozen priests that stood behind me,
burst into a passion.
One of them, whose name was Jackus,
among other things that he spoke against the Truth said:
"`The spirit and the letter were inseparable.`"
I replied: "`Then everyone that has the letter has the spirit,
and they might buy the spirit with the letter of the Scriptures.`"
This plain discovery of darkness in the priest,
moved judge Fell and colonel West to reprove them openly, and tell them:
"`That according to that position,
they might carry the Spirit in their pockets as they did the Scriptures.`"
Upon this the priests being confounded and put to silence,
rushed out in a rage against the justices,
because they could not have their bloody ends upon me.
The justices, seeing the witnesses did not agree,
and finding that all their evidences were not sufficient
in law to make good their charge against me,
discharged me.

Thus I was cleared in open sessions of those lying accusations
which the malicious priests had laid to my charge;
and multitudes of people praised God that day.
It was a day of everlasting salvation to hundreds of people: for the Lord Jesus Christ,
the way to the Father, the free Teacher, was exalted and set up,
his everlasting Gospel was preached,
and the word of eternal life was declared over the
heads of the priests and all such lucrative preachers.

--

The trial of George Fox for alleged blasphemy was by no means a solitary case.
It is recorded of Anne Audland, afterwards Anne Camm,
that she was indefatigable in promulgating the glad tidings of life and salvation.
The success which attended her labors so provoked her persecutors,
that they threatened she should be burnt,
and she was brought to trial on a charge of blasphemy.
In speaking to a priest of Banbury, she had observed:
"`That true words might be false in the mouths of some who quote
them;`" and quoting in proof and explanation of her meaning,
the language of the prophet Jeremiah: "`Though they say the Lord lives,
surely they swear falsely.`"
From these expressions her enemies manufactured the charge of denying that God lived.
During the course of the trial she conducted herself
with so much prudence and innocent firmness,
and gave such judicious answers to the questions propounded to her,
that the judge was evidently inclined to her acquittal.
Some of the justices who had been active in committing her,
finding their designs were likely to be frustrated,
stepped down from the bench among the jury,
in order to influence their minds against her.
Some of the officers of the court protested against
their arbitrary and unrighteous proceedings.
She was honorably acquitted, but the judge,
willing to appease the disappointed rage of her enemies,
demanded bond for her good behavior; which, as an innocent woman of good repute,
she declined giving, and he remanded her to prison.
Here she was thrust into a filthy dungeon several steps below the ground,
on one side of which ran the common sewer, emitting a horrible stench,
and giving admission to frogs and vermin, which infested her apartment.
It was also destitute of any convenience for making a fire to warm the inmates,
or dry up the noxious vapors which exhaled from its filthy and disgusting contents.

Among the truths of which our early Friends were convinced,
perhaps no one exposed them to more severe sufferings from malicious men,
than their faithful adherence to the teaching of Christ,
that oaths are forbidden to the Christian.
At an earlier period in English history,
when the conflict between popery and protestantism was still recent or, it may be said,
still unsettled in England, acts had been passed inflicting severe penalties,
extending to the loss of property and imprisonment for life,
on those who refused to take certain oaths, avowing allegiance to the king of England,
and rejecting the claims of the pope to the government of the church in that country.
In a community where everyone admitted the propriety of binding themselves by oaths,
those who refused these oaths were considered to be disloyal to the government.
These obligations were never designed to be applied to a loyal and innocent people,
who were willing to be bound by their substance,
but who believed that the command "`Swear not at all,`" was obligatory upon them.
It was therefore a malicious and hateful perversion of justice of which
the enemies of Friends were guilty in so wresting these statutes as to
make them apply to those against whom there was no shadow of pretense
that they were deficient in loyalty to the king,
or were not free from attachment to popery.
The history of our Society abounds in instances where, without any show of reason,
these oaths were administered to Friends, simply as traps to ensnare them.
The account which George Fox gives of his trial at Lancaster in 1664,
shows in an interesting manner the efforts of the judges to ensnare him,
and his own intrepidity and the clearness of his intellect.

[.small-break]
'''

In 1663,
a warrant to arrest George Fox had been given by
some evil-disposed justices in the north of England,
the pretence for which was that he had sent forth a paper cautioning
the people against joining in any treasonable plots.
Hence it was inferred that he must have some knowledge of such a movement.
When he was brought before the justices,
one George Middleton (who was reported to be a papist) said to him:
"`You are a rebel and a traitor.`"
George says:

[.embedded-content-document]
--

I asked him whom he spoke to, or whom did he call a rebel.
He was so full of envy that for a while he could not speak.
But at last he said, he spoke it to me.
With that I struck my hand on the table,
and told him I had suffered more than twenty such as he, or than any that were there,
for I had been cast into Derby prison for six months together,
and had suffered much because I would not take up
arms against the king before Worcester fight.
I had been sent up a prisoner out of my own county by colonel Hacker to Oliver Cromwell,
as a plotter to bring in king Charles, in the year 1654,
and I had nothing but love and good-will to the king,
and desired the eternal good and welfare of him and all his subjects.
"`Did you ever hear the like?`"--said Middleton.
Indeed, said I, you may hear it again, if you will, for you talk of the king,
a company of you.
But where were you in Oliver`'s days, and what did you do then for him?
I have more love to the king for his eternal good and welfare than any of you have.

--

Finding no other excuse for sending him to prison, they tendered the oath to him,
which he would not take.
In 1664, he was again brought before the court.
When George Fox was asked in court whether he would take the oath or not, he replied:

[.embedded-content-document]
--

"`You have given me a book to kiss and to swear on,
and this book which you have given me to kiss, says:
'`Kiss the Son,`' and the Son says in this book, '`Swear not at all:`' and so says, also,
the apostle James 1 say as the book says, yet you imprison me.
How come you do not imprison the book for saying so?
How comes it that the book is at liberty among you which bids me not to swear,
and yet you imprison me for doing as the book bids me?`"
I was speaking this to them,
and held up the Bible open in my hand to show them the place where Christ forbade swearing.
They plucked the book out of my hand, and the judge said: "`No,
but we will imprison George Fox.`"
Yet this got abroad over all the country as a by-word:
"`That they gave me a book to swear on that commanded me
not to swear at all,`" and that the Bible was at liberty,
and I in prison for doing as the Bible said.

--

The account of this trial, as given in [.book-title]#George Fox`'s Journal#, illustrates several points:
The feeling of malice that actuated the court,
its disregard of the legal rights of the prisoner,
the fearlessness with which George Fox exposed their wrong proceedings,
the clear-headedness which enabled him, in measure, to confound his persecutors,
and the plain exposition of the Scriptural ground for refusing to swear.

In the account of Friends in Wales, it is stated that the magistrates in Montgomeryshire,
being excited to enmity against Friends because so many were convinced of their principles,
had most of those who had newly joined with them brought before them,
that they might tender them the oath of allegiance.
They knew they could not, in conscience, take it,
and thus the way was opened to send them to prison.

In the Sixth Month of 1662,
five women were committed to close confinement at
Haverford-West for refusing to take the oath of allegiance.

At Shrewsbury, where many Friends were confined,
several of their brethren from distant places were drawn, in Christian love,
to visit them.
The soldiers of the guard apprehended these as they came, and took them before the mayor,
who, understanding his business fully by this time,
would immediately tender them the oath,
and commit them to the company of those they had been sympathizing with.
Some so served had come to bring provisions to the prisoners.

William Penn, in his account of the rise of the Society of Friends,
points out one of their characteristics,
which had much to do with the severe sufferings to which they were exposed.
He says:

[.embedded-content-document]
--

They refuse to pay tithes or a maintenance to a national ministry,
and that for two reasons: The one is, that they believe all compelled maintenance,
even to Gospel ministers, to be unlawful,
because expressly contrary to Christ`'s command, who said: "`Freely you have received,
freely give;`" at least, that the maintenance of Gospel ministers should be free,
and not forced; the other reason of their refusal is,
because these ministers are not Gospel ones,
in that the Holy Spirit is not their foundation, but human arts and parts,
so that it is not a matter of humor or sullenness; but pure conscience toward God,
that they cannot help to support national ministers where they dwell,
which are but too much and too visibly become ways of worldly advantage and preferment.

--

The testimonies held by our early Friends to a free Gospel ministry,
caused them much suffering.
It operated in two ways: First,
by bringing them into collision with the laws then in force for
the collection of tithes and other so-called church dues;
and, secondly, by making enemies of the great body of the priesthood,
whose calling and maintenance were thus called in question,
and who became some of the most bitter and inveterate of persecutors,
and were active in stirring up others to beat and imprison the Quakers.
The words of Micah, the ancient prophet, were verified:
"`He that puts not into their mouths, they even prepare war against him.`"
The maliciousness and cruelty of many of the priests were altogether
at variance with the Divine love which ought to rule in the hearts
of those who professed to be ministers of the loving Jesus.

A writer in the _Westminster and Foreign Review_ points out the connection
between the doctrines of Friends and the persecutions they experienced:

[.embedded-content-document]
--

George Fox repudiated priesthood and priestcraft,
and dared to deny the right of a human mediator between God and man.
He acknowledged but one mediator;
one whose services were not to be doled out in pittances apportioned to the coin returned.
It, therefore, is not remarkable that the priesthood,
of whatever denomination +++[+++seeing their craft was in danger],
should rise as one man against the Quaker,
and denounce him from the pulpit and the press as an atheist and a traitor;
an enemy alike to religion and to law.
Such was the case; and when we remember how subtle, how ramified,
how extended is that power and influence which he attacked,
we cannot wonder that the Quaker was hunted from place to place like a beast--was torn
from his home and family--was thrown into the most filthy dungeons--was flogged,
maimed, crippled and murdered merely on a false charge of irreligion and disaffection,
originating entirely in the vengeance of a priesthood whose offices he declined,
and with whose emoluments the spread of such opinions must of necessity interfere.

The license for marriage, the marriage form,
and the interference of the priests in completing it--the churching of women--the sprinkling
of infants--the administration of the sacrament--the ceremony of confirmation--the funeral
service the consecration of churches and churchyards--all forms of prayers and written
sermons--all were of no avail with the Quaker.
This was accounted atheism and high treason in the eyes of the clergy,
and all those over whom this influence extended.
The boldness with which Fox preached these doctrines is shown in his own Journal.
_The Journal of George Fox_, says Sir James Macintosh,
"`is one of the most extraordinary and instructive documents in the world,
and no man of competent judgment can peruse it without revering the virtue of the writer.`"
Here we are presented with the origin of the Quaker
tenet against a paid clergy of any description;
and from the doctrines of their founder, as agreeing with the New Testament,
the Quakers conceive themselves called upon to protest
openly against such a ministration of the Gospel,
as being contrary to the spiritual injunctions of Christ and the practice of the apostles,
and the early Christian church.
Hence they refuse to pay all tithes or church demands,
patiently submitting to the legal penalties attached to such refusals,
and to the rapacity of their enemies, who, in the early periods of the Society,
carried their plunder to so great an excess as not only to involve many in total ruin,
but also subject them to long and cruel imprisonments,
which in many cases of particular hardship, terminated in death.
The number who perished in this way throughout the kingdom
amounted to three hundred and sixty-nine persons.

--

Somewhere about the year 1781,
a number of Friends were summoned before a Justice of the Peace at the
suit of the Vicar of Carlton for not having paid their small tithes.
The amount that could be claimed of each annually, according to law, was small,
but the demand made before the magistrate appeared to him exorbitant,
and he advised the priest to make a more moderate claim.
This he refused to do--and although the Friends could
not have paid the smallest fraction of the claim,
yet the refusal of the prosecutor to abate anything, clearly showed his covetous spirit.
He then commenced an exchequer process, throwing it into the Bishop`'s Court.

After many years`' delay he obtained a decree for the amount of his claim, and the costs,
and for not paying the sum thus awarded, Joseph Brown, John Wormall, John Stansfield,
Henry Wormall, Henry King, John Wilkinson, William Hartley and James Walton,
were torn from the bosom of their families, and thrown into York Castle.
These men were none of them in affluent circumstances, some were quite poor,
and there was not one whose family was not dependent for its support on his industry.
Being now debarred from profitable employment,
several of the prisoners had no means of preventing their families
from becoming dependent upon the charity of their friends.
Joseph Brown was a minister, and although affected with a pulmonary complaint, he had,
by persevering industry, maintained a wife and family of ten children by his business,
which was not a remunerative one, being that of a constructor of dry stone fences.
Beside this he tilled a very small portion of land.

The Friends continued in prison about two years, when,
through the representations made of the case to the king, and others in authority,
a clause was inserted in an act of Parliament by
which magistrates were empowered to release them.
The prison doors were opened for all the Friends except John Wilkinson--who
had by death been previously set free from the wrath of the persecutor.
Distraints were made on the property of the survivors
to meet the unjust claims of the vicar.

On one occasion,
George Fox was at a meeting when the preacher took for his text the passage: "`Ho,
everyone that thirsts, come to the waters; and he that has no money, come, buy and eat;
yes, come, buy wine and milk, without money and without price.`"
After he had finished his discourse, George exclaimed: "`Come down, you deceiver!
Do you bid people come freely, and to take of the water of life freely,
and yet you take three hundred pounds a year of them?
Should you not blush with shame!
Did not Christ say to his ministers whom He sent to preach: '`Freely you have received,
freely give?`'`"

The practice of true friends has ever been in accordance with this principle.
Samuel Bownas, in his Memoirs, says:

[.embedded-content-document]
--

I visited Leicestershire pretty generally, and a woman of some account,
whose name was Jemima Mountney, was convinced, and was with me at sundry meetings,
and was exceedingly tender and loving, being thoroughly reached and satisfied.
When we parted she was so open-hearted that I was called aside by her,
and after having said something to me about her inward condition,
she offered me some pieces of gold, which I told her I dared not touch.
She very courteously, and with a becoming genteel mien,
told me she was both able and willing,
and as she had no other way that she could show her gratitude
for that spiritual good she had received from my ministry,
she could do no less, beseeching that I would receive it,
as the true token of her love and respect.
In answer, I said it was what I never had done; nor could I now do it;
but all the reward I desired and expected was, that she might carefully,
with a sincere heart, endeavor that her obedience did keep pace with her knowledge,
the hearing of which would rejoice my soul.
We parted in great love and tenderness.

--

[.offset]
Samuel Bownas makes this further remark on the subject of the ministry:

[.embedded-content-document]
--

All who have received their ministry from the Lord Jesus, are bound,
by his command to his apostles, to give it forth freely.
If persons study their preaching to get a living by it,
they will be likely to expect to be paid for it;
but do we not suppose if all Christians were brought to wait upon God in reverent silence,
for ability to worship Him in spirit and in truth,
that He would select his ministers for the work who would preach freely as their duty,
and that the Redeemer`'s cause, the reign of the Prince of Peace,
would be more effectually spread in the world?

--

Gough, in his history of the people called Quakers,
mentions several cases which show the hard-heartedness of some of the priests,
and their injustice in taking more than the law entitled them to.
Leonard Cole, for refusing to pay tithes, was sent to prison,
and while there the priest made a seizure of his corn and cattle
to the value of nearly one hundred pounds for one year`'s tithe,
for which the former occupier of the same farm paid but six pounds.

For fifty pounds demanded, were taken from John Pollard, of Steeple, corn, etc.,
to the value of three hundred and twenty-two pounds.

John Bishop, in the Isle of Wight,
a poor laboring man who had a large family dependent on his labor,
was imprisoned in Winchester jail for tithes twenty weeks.

William Vincent, for a demand of only four pence for tithes,
was imprisoned in Northampton jail about a year.

Margaret Parke, a poor widow, having three children,
was imprisoned twenty-seven months for tithes of cow and
hay less than thirteen shillings four pence in value.
This poor woman`'s sufferings were grievous,
being closely confined among murderers and thieves,
where her friends were not admitted to see her.

It was the practice of Friends to preserve an account
of the sufferings they underwent on Truth`'s account,
and the annual epistles of London Yearly Meeting for many years,
state the amounts taken from its members on account of tithes, etc.,
as well as the number in prison.
The pecuniary distraints varied from three to upwards of five thousand pounds,
and the number of prisoners was often over one hundred.
In the year 1829 the meeting was able to report for the first time that there was no
Friend in prison on "`Truth`'s account,`" "`On which occasion,`" says the epistle,
"`we cannot but commemorate the goodness of our God in this his merciful dispensation,
so different from the lot of our fathers.`"

[.offset]
Of the enmity felt by the clergy towards our early Friends, Robert Barclay remarks:

[.embedded-content-document]
--

God having shown us this corrupt and antichristian ministry, and called us out from it,
and gathered us into his own power and life, to be a separate people,
so that we dare not join with nor hear these antichristian hirelings,
neither yet put into their mouths or feed them; oh!--what malice,
envy and fury has this raised in their hearts against us!
That though we get none of their wares, neither will buy them,
as knowing them to be naught, yet will they force us to give them money; and,
because we cannot for conscience`' sake do it,
our sufferings upon that account have been unutterable.
These avaricious hirelings have come to that degree of malice and rage,
that several poor laboring men have been carried hundreds of miles from their own dwellings,
and shut up in prison, some two, some three, yes, some seven years together,
for the value of one pound sterling and less.
I know myself a poor widow, that for the tithes of her geese,
which amounted not to five shillings,
was about four years kept in prison thirty miles from her house.
Indeed, hundreds have hereby spilled their innocent blood,
by dying in the filthy noisome holes and prisons.
And some of the priests have been so enraged,
that goods thus ravished could not satisfy them,
but they must also satisfy their fury by beating,
knocking and wounding with their hands innocent men and women for
refusing (for conscience`' sake) to put into their mouths.

--

The Journals of Friends who lived in those days,
abound with statements of the sufferings by loss of property and
imprisonments to which they were subjected for their faithfulness
in refusing to pay preachers who had not ministered unto them,
and who had no equitable claim upon them,
and whose forced maintenance was a violation of the
principles laid down by Christ and his apostles.

The word "`Tithes`" means a tenth part.
Among the Jews it was given to the tribe of Levi,
as a substitute for their share of the land,
when the land of Canaan was divided among the tribes of Israel.
There was no similar provision among the early Christians.
Indeed, in the earlier period of the Christian church,
there was no separate order of clergy,
but in their meetings everyone was at liberty to exercise
the gift of ministry as the Lord called them to the service.
It soon became common to raise a church fund,
and Tertullian shows the purposes to which it was applied--"`In relieving the poor,
and upon children destitute of parents,
and in the maintenance of aged and feeble persons, and of men wrecked by sea,
and of such as have been condemned to metallic mines, or have been cast into prison,
professing the Christian faith.`"
In the distribution of these funds, no doubt,
the ministers in need would share as well as the other members,
not because they were ministers, but because they were poor or in distress.

These funds were derived from voluntary contributions,
and were under the care of the deacons--the bishops having nothing to do with them,
until the Council of Antioch, in the year 340,
ordained that the bishops might distribute them,
but that they should take no part of them to themselves,
or for the use of the priests who lived with them, unless necessity required it.
With the progress of declension in the church,
the payment of all ministers was gradually introduced
between the fourth and eighth centuries;
and the proportion of the funds devoted to its original
object--the relief of the poor--was lessened.
In the year 1200,
Pope Innocent III ordained that everyone should pay tithes to those
who administered to him spiritual things in his own parish:
and thus the fund of the poor was converted almost
wholly into a fund for the maintenance of the church.

By an act passed in the reign of Henry VIII, of England,
the right of the clergy to tithes was confirmed,
and the priests could claim a legal title to them.
Friends refused to obey this law, because, if tithes were due to anybody,
they were due to the poor.
Secondly, because they had been originally free-will offerings,
and now by violence had been changed into dues to be collected by force.
It was clear, from the instructions of Jesus to his disciples,
that ministers of the Gospel were not authorized to demand a maintenance from others;
and that any constrained payment of these demands would amount
to an acknowledgment of the right of the civil magistrate to interfere
in matters which lay solely between God and man.
Thirdly, the tithes were claimed by the act of Henry VIII as being due by Divine right,
as were the Levitical tithes.
To this Friends objected that the Levitical priesthood and
all its belongings ceased with the coming of Christ;
and therefore they would be acquiescing in a false principle,
if they paid tithes founded upon it.

The objection to the payment of tithes by Friends being a matter of conscience,
and founded on a religious principle,
they suffered great hardships rather than sacrifice their peace of mind by paying them.
One of the most outrageous of these cases was that of a poor widow and her son,
who were imprisoned eleven months on a verdict for one penny for tithe-wool.
Under a feeling of the avaricious spirit which prevailed
in many of the ministers of the established church,
George Fox says:

[.embedded-content-document]
--

The black, earthly spirit of the priests wounded my life;
and when I heard the bell toll to call people together to the steeple-house,
it struck at my life; for it was like a market-bell to gather people together,
that the priest might set forth his wares for sale.
Oh, the vast sums of money that are got by the trade they make of selling the Scriptures,
and by their preaching, from the highest bishop to the lowest priest!
What one trade else in the world is comparable to it?--notwithstanding
the Scriptures were given forth freely,
Christ commanded his ministers to preach freely,
and the prophets and apostles denounced judgment
against all covetous hirelings and diviners for money.

--

It was not only in the collection of tithes and similar
charges that Friends suffered by the hands of the priests,
but these were great instruments in stirring up the civil magistrates to persecute them.
Not only so, but in collecting the tithes which they claimed,
many of them maliciously resorted to forms of legal proceedings which
involved their victims in great expenses and often tedious imprisonments,
when at the time there were easy methods of distraining the amount.
To procure relief from this grievance a petition was presented to Parliament in 1736,
praying that prosecutions for tithes might be restrained
so as to follow only the less oppressive methods.
In this petition it was stated that above eight hundred
pounds had been taken from ten persons,
when the original demand did not collectively amount to more than fifteen pounds;
and that nearly three hundred had been committed to prison on such prosecutions,
of whom several had died prisoners.
Notwithstanding the reasonable nature of this petition,
it was strenuously opposed by the clergy, and through their influence defeated.

Among the sects which arose in England during the
religious excitements of the seventeenth century,
were the Ranters, who appeared about the year 1640.
William Penn says of them:

[.embedded-content-document]
--

They interpreted Christ`'s fulfilling of the law for us to be a discharging
of us from any obligation and duty the law required of us,
instead of the condemnation of the law for sins past, upon faith and repentance;
and that now it was no sin to do that which, before,
it was a sin to commit--the slavish fear of the law being taken off by Christ;
and all things good that man did,
if he did but do them with the mind and persuasion that it was so;
insomuch that several fell into gross and corrupt practices--pretending,
in excuse thereof, that they could, without evil,
commit the same act which was sin in another to do.
This was to make sin superabound by the aboundings of grace,
and to turn from the grace of God into licentiousness.
As if Christ came not to save us from our sins, but in our sins; not to take away sin,
but that we might sin more freely, at his cost and with less danger to ourselves.
I say, this ensnared several,
and brought them to an utter and lamentable loss as to their eternal state,
and they grew very troublesome to the better sort of people,
and furnished the looser with an occasion to profane.

--

These Ranters, William Penn says,
"`Were the reverse to the Quakers (for they feared and quaked at nothing,
but made a mock at fearing of God, and at sin, and at hell),
who pretended that love made fear needless,
and that nothing was sin but to them that thought it so,
and that none should be damned at last;
whose extravagant practices exactly corresponded with their evil principles.
Yet,`" he adds, "`some ignorantly, and too many maliciously,
involved us and ours with them,
and many of their exorbitances were thereby placed to our account,
though without the least reason, truth or justice.`"

Friends often came into contact with these wild people.
In 1649, George Fox visited some of them who were in prison at Coventry.
They began to "`Rant, vapor and blaspheme.
At which,`" he says, "`my soul was greatly grieved.`"
After showing them that the Scripture texts they adduced
in support of their pretensions made nothing for their purpose,
he reproved them for their blasphemous expressions, and went away.

In 1651, his Journal states,
he visited a people at Cleveland that had tasted of the power of God,
but were then shattered to pieces and turned Ranters.
His message unto them from the Lord was "`That they should all come together again,
and wait to feel the Lord`'s power and spirit in themselves, to gather them to Christ,
that they might be taught of Him.`"
He adds: "`Most of the people were convinced, and received God`'s everlasting Truth,
and continue a meeting to this day, sitting under the teaching of the Lord Jesus Christ,
their Saviour.`"

In 1654, he met with many Ranters "`In the Peak country.`"
He reproved them for swearing.
"`The word of life was fully and richly preached, and many were convinced that day.`"

At Reading, some of the Ranters entered into dispute,
and contended that God made the devil.
This was in accordance with the doctrine,
which a temperate writer of that time says they hold--that
"`There is but one spirit in the world,
and those names of good spirit and bad spirit are mere scarecrows.`"
In reply, George Fox tells them that God made all things good,
and that Satan became a devil by going out of the Truth.

The Ranters sometimes came into Friends`' meetings, and made much disturbance,
"`Singing and dancing in a rude manner.`"
When William Edmundson was visiting the meetings in New Jersey, he says:
"`One Edward Tarff came into the meeting, with his face blacked,
and said it was his justification and sanctification; also sung and danced,
and came to me, where I was sitting, waiting on the Lord, and called me old,
rotten priest, saying I had lost the power of God.
But the Lord`'s power filled my heart,
and his word was powerful and sharp in my heart and tongue.
I told him he was mad.
I looked on him in the authority of the Lord`'s power,
and told him I challenged him and his god that sent him, to look me in the face one hour,
or half an hour.
But he was smitten, and could not look me in the face, but went out.
The Lord`'s power and sense of it was over the meeting, in which I stood up,
showing them how the Ranters went from it,
and were bewitched by a transformed spirit into strong delusions.`"

When Thomas Story was travelling in Connecticut,
he found reproach had been thrown upon the Society of Friends on account
of the "`Wild and unaccountable behaviour`" of some of the Ranters,
whom the people of that colony confounded with Friends.
Thomas told the people that the Ranters "`Held absurd and blasphemous opinions,
and frequently came into our meetings, and rant, sing and dance, and act like madmen,
throwing dust into the faces of our ministers when preaching.
Though they are called Quakers, and have meetings of their own, as we have,
yet they have no discipline or order among them, but deny all that as carnal and formal,
leaving everyone to do as he pleases, without any reproof, restraint,
or account to the Society in anything, how inconsistent soever with civility,
morality and religion, and are in mere anarchy.`"

In another part of his Journal, Thomas Story mentions attending a meeting at Westbury,
Long Island, where a marriage was solemnized.
To this meeting some of the Ranters came.
"`During the greatest part of the time they were pretty still, save only an old man,
who sometimes hooted like an owl, and made a ridiculous noise, as their manner is.
The marriage being solemnized, he stood up and bore his testimony, as he called it,
against our set forms.`"

In 1737, John Griffith was travelling into East New Jersey,
and had a meeting near Black`'s River.
He says: "`None of our Society were thereabouts, but there were some Ranters,
who had taken upon them the name of Quakers,
to the great scandal of Friends in that remote place.
They came to the meeting, being mostly women.
Their impatient,
restless spirits would not permit them to let us hold our meeting quietly;
yet they did not seem inclinable to contend, but rather to flatter and applaud us.
But we were not free to receive their testimony,
any more than Paul and Silas could that of the maid who was possessed with an evil spirit,
but rebuked them openly, and publicly declared our disunity with them,
desiring the people not to look upon them as belonging
to the Society of the people called Quakers,
as we could assure the meeting it was not so.
I thought the chief service we had at that place was to testify against those wild,
frantic people.`"

[.embedded-content-document]
--

It was not only in Great Britain that Friends suffered
for the non-payment of tithes at the priests`' demands.
In Virginia, in 1724,
Robert Jordan was summoned to appear before the general
court for non-payment of priest`'s wages.
He says:

At my first appearance, the fierceness of the dragon was felt,
and his dark power seemed great and terrible,
even as though he would have swallowed me quick,
and Truth`'s adversaries seemed to rejoice,
for I was made to stand like a fool for them to glory over me,
finding it safest for me and the cause, to say little at that time.
The indictment being found, seemed very strange to me,
who had not been accustomed to such work.
However, I composed and stayed my mind in stillness on the Lord,
with earnest breathings to Him for Divine aid in this his cause.
As I was not conscious of having done any evil therein,
I was greatly desirous that I might not give way one jot of my testimony, through fear,
even of death itself.
I thought I felt the bitterness of it strike at my natural life,
and saw plainly that antichrist is as bloodthirsty as ever, only he lacks power.

Now the day for final judgment in the case came.
The council were very long in the council-chamber, before they sat in judgment,
when I was brought +++[+++before them]
the third time.
They demanded what I had further to say, for they were about to pass sentence upon me.
I desired liberty to make my defence, having much to say,
and speak my sense upon my paper,
for the commissary or chief priest had perverted my meaning.
This, governor Drisdale seemed willing to, but it is likely the priest,
apprehending what I might say would not make for their interest, overswayed him,
and it was denied.
Howbeit, I told them I remembered to have read a proviso of an act of Parliament, saying,
no man should be punished for any offense against the act,
unless he were prosecuted within three months after the fact committed; but this, said I,
was about seven months after.

Some of the court being especially resolved on severity to make me submit,
they proceeded to sentence, of a year`'s imprisonment,
or bond with security for good behaviour, etc.
With a composed mind, and an audible voice, I said: "`This is a hard sentence;
I pray God forgive my adversaries!`"
This affected several standers-by with tears.
One in particular, a judge, and a man of note, was much affected,
and made himself acquainted and conversed with me, more than once.
He appears a well-convinced and tender man,
and has since gladly received meetings into his house, and, as he has since then told me,
has laid down his commission.

So now, I was settled in prison, but in the debtor`'s jail,
and although a close prisoner, had pretty good air.
But this seemed too easy to force me to comply +++[+++with my adversaries`' wishes,]
wherefore in a few days I was removed into the common
side where condemned persons are kept.
The jailer, who, it is likely, was taught his lesson, came to me, and said:
"`The bill is found against you!`"
I meekly replied: "`If they have power to take away my life, I shall not refuse.`"
Here I was kept night and day without seeing anybody,
save the negro who tended the prison, +++[+++who came]
once a day to bring a little water.
+++[+++The place was]
very nauseous, and so dark I could not see to read at noonday,
without creeping close to the little holes in the door.

After a while some Friends, with paying dear, would come to me.
The infectious air soon +++[+++made me sick,]
and had not the Lord been pleased to help me by an invincible hand,
I had there lost my life.
The governor was acquainted with my condition, and, I believe,
used his endeavors for my liberty.
My wife, with others came to see me, and brought me some necessaries,
with a design to stay and minister to me.
But being close pent in that infectious place,
I thought it was enough to endanger the life of one, +++[+++so discouraged her staying.]
My wife went away that day, we being made willing to part, and leave all to the Lord.
Herein the craft of my adversaries was turned into foolishness,
as well as in the close of the whole scene.
They expected she might have influenced me to comply +++[+++with their terms,]
and in order to render it terrible to her, we, with the other Friends,
were locked and barred in as close as usual.
The jailer asked if they had brought any tools in their wallets,
which I am well assured he did not expect.

The commissary omitted not to visit me, more than once, under a show of friendship,
to ensnare me; and I was very wary of him.
I had written to the Governor to acquaint him with my condition, and now wrote again.
So after about three weeks`' confinement I was discharged, without any acknowledgment.
This brought me into acquaintance and ready admittance to the governor, who said,
I was a meek man, and that we loved the king, etc.
Thus I returned home with praises and thanksgivings, in my heart to the Lord,
who had caused his Truth to triumph over the strongest efforts of man,
and the powers of the earth.

--
