== Chapter III. Worldliness

It is worthy of notice how large a proportion of the professors
of Christianity practically disregard the Scripture exhortation:
"`Be not conformed to the world, but be transformed in the spirit of your minds.`"
It remains to be sorrowfully true that the world lies in wickedness,
and that many of its practices are not consistent
with the purity inculcated by the religion of Christ.
George Fox says, in his Journal:

[.embedded-content-document]
--

When the Lord sent me into the world, He forbade me to put off my hat unto any,
high or low, and I was required to "`thee and thou`" all men and women,
without any respect to rich or poor, great or small.
And as I travelled up and down,
I was not to bid people "`Good morning`" or "`Good evening;`" neither might I bow,
or scrape with my leg, to anyone.
This made the sects and professors rage.

Oh, the rage that was in the priests, magistrates, professors and people of all sorts,
and especially in priests and professors;
for though "`thou,`" to a single person was according
to their accidence and grammar rules,
and according to the Bible, yet they could not bear to hear it.
And because I could not put off my hat to them, it set them all into a rage.
But the Lord showed me it was an honor below, which He would lay in the dust and stain;
an honor which proud flesh looked for,
but sought not the honor which comes from God only; that it was an honor invented by man,
in the fall and in the alienation from God, who were offended if it was not given them,
yet would be looked upon as saints, church members and great Christians.
But Christ says: "`How can you believe who receive honor one of another,
and seek not the honor that comes from God only?`"
"`And I,`" says Christ, "`receive not honor of men.`"
Showing that men have an honor which they will receive and give,
but Christ will have none of it.
This is the honor which Christ will not receive, and which must be laid in the dust.
Oh, the scorn, heat and fury that arose!
Oh, the blows, punching,
beatings and imprisonments that we underwent for not putting off our hats to men.
For that soon tried all men`'s patience and sobriety, what it was.
The bad language and evil usage we received on this account is hard to be expressed,
besides the danger we were sometimes in of losing our lives for this matter,
and that by the great professors of Christianity.
And though it was but a small thing in the eye of man,
yet a wonderful confusion it brought among all professors and priests.

--

[.offset]
William Penn, in speaking of Friends, says:

[.embedded-content-document]
--

Not to respect persons was another of their doctrines and practices,
for which they were often buffeted and abused.
They affirmed it to be sinful to give flattering titles,
or to use vain gestures and compliments of respect;
though to virtue and authority they ever made a difference,
but after their plain and homely manner.
They also used the plain language of "`Thou`" and "`Thee`" to a single person,
whatever was his degree among men.

--

Robert Barclay, in his Apology, Proposition XV, unfolds, to some extent,
the grounds of the objections felt by Friends to titles of honor and vain compliments:
First,
because these titles are no part of that obedience which is due to magistrates or superiors,
which consists in obeying their just and lawful commands; secondly,
such titles are not used in Scripture; and thirdly,
they often lay on those who use them a necessity to lie,
because he who is styled "`Your Excellency`" may have nothing of excellency in him;
or "`Your Grace`" may appear to be an enemy to grace,
and he who is called "`Your Honor`" may be known to be base and ignoble; lastly,
these titles are part of that honor which comes from below,
which is to be rejected by Chistians.

Such absurd compliments as "`Your humble servant,`" etc.,
are so notoriously false and hollow,
that "`To use lying is now come to be accounted civility.`"

Kneeling,
bowing and uncovering the head is the outward signification of our adoration towards God,
and therefore it is not lawful to give it unto man.

When George Fox was travelling in the southwestern part of England,
one major Ceely put off his hat to him, and said: "`How do you do, Mr. Fox?
Your servant, sir.`"
George replied to him: "`Major Ceely, take heed of hypocrisy and of a rotten heart;
for when came I to be your master, and you my servant?`"

In 1656,
seven Friends in Wales were arrested and committed to prison till the next court session,
five months off.
When the court session came, they were brought before the court,
and no breach of law was proven against them.
Yet, taking occasion of their coming before him with their hats on, the judge,
on pretence of its being a contempt of court, fined them and recommitted them to prison,
where they remained for three months longer.

In Cheshire there was a hole hewed out of a rock,
into which prisoners were sometimes forced, by way of torture.
It was called "`Little Ease.`"
A Friend,
who complained to the mayor against a drunken fellow who had grossly abused him,
was sent to "`Little Ease`" for not putting off his hat when he made the complaint,
and the drunkard went unpunished.

When George Fox was travelling in Cornwall,
he was arrested and committed to prison by major Ceely.
When the court session came on, no breach of law could be proven against him.
The judge, instead of releasing him,
fined the prisoners twenty marks apiece for not putting off their hats.

When William Penn became convinced of the principles held by Friends,
he saw that the so-called "`Hat honor`" paid to men was
inconsistent with the high standard of practical Christianity,
and was turned out of his home by his father for
his refusal to conform to the usual custom.

On one occasion, when George Fox and his friends were taken into court,
they stood with their hats on, and the Journal narrates that:

[.embedded-content-document]
--

Judge Glyn, a Welshman, then chief justice of England, said to the jailer:
"`What be these you have brought here into the court?`"
"`Prisoners, my lord,`" said he.
"`Why do you not put off your hats?`"--said the judge to us.
We said nothing.
"`Put off your hats,`" said the judge again.
Still we said nothing.
Then said the judge: "`The court commands you to put off your hats.`"
Then I spoke and said: "`Where did ever any magistrate, king or judge,
from Moses to Daniel, command any to put off their hats,
when they came before them in their courts,
either among the Jews (the people of God) or among the heathen?
And if the law of England does command any such thing,
show me that law either written or printed.`"
The judge grew very angry, and said: "`I do not carry my law books on my back.`"
"`But,`" said I, "`tell me where it is printed in any statute book, that I may read it.`"
Then said the judge: "`Take him away, prevaricator!
I will flog him.`"
So they took us away, and put us among the thieves.
Presently after he called to the jailer: "`Bring them up again!
Come,`" said he, "`where had they hats from Moses to Daniel?
Come, answer me; I have you fast now!`"
I replied,
"`You may read in third of Daniel that the three children were
cast into the fiery furnace by Nebuchadnezzar`'s command,
with their coats, their hose and their hats on.`"
This plain instance stopped him; so that, not having anything else to the point,
he cried again: "`Take them away, jailer!`"

--

In the early history of Pennsylvania there is an incident recorded,
which shows the carefulness of Friends to maintain their testimony on this point,
and also the jealousy with which they guarded against any infringement on their liberties.

In the year 1725,
John Kinsey was employed to plead in a case before the court of chancery in Pennsylvania.
When he undertook to speak, having his hat on his head,
he was interrupted by the governor of the province, William Keith,
who was president of the court, and directed to remove his hat.
He declined obedience, saying that he could not do it, for conscience`' sake.
The governor, notwithstanding this reply, directed the hat to be taken from his head,
and then allowed the cause to proceed.
At the Monthly Meeting of Philadelphia, held Second Month 30th of that year,
the subject claimed the serious attention of the members,
and the representatives to the Quarterly Meeting were directed,
after giving in to that body an account of the state of their members,
"`To signify the great uneasiness Friends are under
at the governor`'s not permitting our Friend,
John Kinsey, Jr.,
to plead in the last court of chancery until his hat was first taken off by an officer,
which this meeting apprehends to be an infringement
on the religious liberties of our community,
and desires advice and assistance of the Quarterly Meeting therein.`"

At the next meeting, the representatives report "`That the Quarterly Meeting,
upon hearing and fully considering the case of John Kinsey in the court of chancery,
had appointed ten Friends to wait on the governor with an address,
showing the infringement made, as Friends conceive,
on their religious liberty secured to them by law and charter,
and requesting the governor that he would consider it as such,
and for the future be pleased to direct that all such impositions might be avoided.`"

[.embedded-content-document.letter]
--

[.letter-heading]
The Humble Address of the People Called Quakers,
by Appointment of their Quarterly Meeting Held Second of Third Month, 1725,
for the City and County of Philadelphia.

[.salutation]
May it please the Governor.

Having maturely considered the inconveniences and hardships,
which we are apprehensive all those of our community
may be laid under who shall be required,
or obliged to attend the respective courts of judicature, in this province,
if they may not be admitted without first having
their hats taken off from their heads by an officer;
as we understand was the case of our Friend John Kinsey,
when the Governor was pleased to command his hat to be so taken off,
before he could be permitted to speak in a cause depending at the last Court of Chancery,
after he had declared that he could not, for conscience,
comply with the Governor`'s order to himself to the same purpose; which,
being altogether new and unprecedented in this province,
was the more surprising to the spectators, and as we conceive,
however slight some may account it,
has a tendency to the subversion of our religious liberty.

We, therefore, crave leave to represent to the Governor, That this province,
with the powers of government, was granted by King Charles II to our late Proprietor,
who, at the time of the said grant,
was well known to dissent from the national way of worship, in several points,
and particularly in that part of outward behavior of refusing to pay unto man the honor,
that he, with all others of the same profession,
believed to be due only to the Supreme Being,
in which they on all occasions have supported their testimony,
so far as to be frequently subjected to the insults of such as required that homage.

That the principal part of those, who accompanied our said Proprietor,
in the first settlement of this colony, with others of the same profession,
who have since retired into it, justly conceived, that by virtue of the said powers,
granted to our Proprietor,
they should have a free and unquestioned right to the exercise of their religious principles,
and their persuasion, in the aforementioned point, and all others,
by which they were distinguished from those of other professions;
and it seems not unreasonable to conceive an indulgence intended by the Crown,
in graciously leaving the modelling of government to him and them, in such manner,
as may best suit their circumstances,
which appears to have been an early care in the first Legislators, by several acts,
as that for liberty of conscience,
and more particularly by a law of this province passed
in the thirteenth year of King William,
chapter 92, now in force; it is provided that "`In all courts,
all persons of all persuasions may freely appear in their own way,
and according to their own manner, and there personally plead their own cause, or,
if unable,
by their friends;`" which provision appears to be directly intended
to guard against all exceptions to any persons appearing in their
own way as our Friend did at the aforesaid court.

Now though no people can be more ready or willing, in all things essential,
to pay all due regard to superiors, and to honor the courts of justice,
and those who administer it, yet,
in such points as interfere with our conscientious persuasions,
we have openly and firmly borne our testimony in
all countries and places where our lots have fallen.

We must, therefore, crave leave to hope, from the reasons here humbly offered,
that the Governor, when he has fully considered them, will be of opinion with us,
that we may justly and modestly claim it, as a right,
that we and our Friends should at all times be excused in this government,
from any compliances against our conscientious persuasions,
and humbly request that he would, for the future, account it as such to us.

[.signed-section-closing]
Your assured well-wishing friends,

[.signed-section-closing]
Signed by appointment of the said meeting.

[.signed-section-signature]
Richard Hill, Richard Hayes, Morris Morris, Anthony Morris, Evan Evans, John Goodson,
Rowland Ellis, Rees Thomas, Samuel Preston, William Hudson

--

The entry on the record of the court of chancery made by order of the governor,
on receiving the above address, follows:

[.embedded-content-document]
--

On consideration had of the humble address, presented to the Governor,
this day read in open Court, from the Quarterly Meeting of the people called Quakers,
for the city and county of Philadelphia, it is ordered,
that the said address be filed with the Register,
and that it be made a standing rule of the Court of Chancery for the Province of Pennsylvania,
in all time to come, that any practitioner of the law, or other officer,
or person whatsoever professing himself to be one of the people called Quakers,
may and shall be admitted, if they think fit, to speak, or otherwise officiate,
and apply themselves decently unto the said court,
without being obliged to observe the usual ceremony of uncovering their heads,
by having their hats taken off,
and such privilege hereby ordered and granted to the people called Quakers,
shall at no time hereafter be understood, or interpreted,
as any contempt or neglect of the said court,
but shall be taken only as an act of conscientious liberty,
of right appertaining to the religious persuasion of the said people,
and agreeable to their practice in all the civil affairs of life.

--

The use of the plural pronoun,
"`you,`" in speaking to a single person was one of those
corruptions which our Society was forced to abandon.
Robert Barclay in his Apology quotes from another author,
the following account of the introduction of this foolish practice:

In course of time, when the Roman commonwealth grew into an empire,
the courtiers began to magnify the emperor, using the word "`you,`" yes,
and dignifying him with more remarkable titles,
concerning which matter we read in the epistles of
Symmachus to the emperors Theodosius and Valentinianus,
where he uses these forms of speaking, _vestra Aeternitas_, your Eternity; _vestra Numen_,
your Godhead; _vestra Serenitas_, your serenity.
So that the word "`you`" in the plural number,
together with the other titles and appellations of honor,
seem to have taken their rise from monarchical governments;
which afterwards by degrees came to be accorded to private persons.

[.offset]
He quotes also from one of the French Academicians:

[.embedded-content-document]
--

The use of the word "`you,`" when one person is spoken to was only
introduced by the base flatterers of men of latter ages,
to whom it seemed good to use the plural number to one person,
that he may imagine himself alone to be equal to many others in dignity and worth.

--

At the time of the rise of our Society, it was the custom to say "`you`" to a superior,
but "`thee`" and "`thou`" to a servant or inferior.
George Fox says: "`When the Lord sent me into the world,
I was required to '`thee`' and '`thou`' all men and
women without any respect to rich or poor,
great or small.`"

In 1665, George Fox, then incarcerated in Scarborough Castle,
and the subject of much interest there, being visited by many people of rank and station,
thus speaks:

[.embedded-content-document]
--

There came to me another time the widow of old lord Fairfax,
and with her a great company, one of whom was a priest.
The priest asked me why we said "`thee`" and "`thou`" to people?--for
he counted us but fools and idiots for speaking so.
I asked him whether those who translated the Scriptures so,
and made the grammar and accidence, were fools and idiots,
seeing they translated the Scriptures so, "`thou`" to one, and "`you`" to more than one,
and left it so to us?
If they were fools and idiots, why had not he, and such as he,
who looked upon themselves as wise men,
and could not bear "`thee`" and "`thou`" to a singular, altered the grammar, accidence,
and Bible, and put the plural instead of the singular?
But if they were wise men who so translated the Bible,
and made the grammar and accidence so,
I wished him to consider whether they were not fools and idiots themselves,
that did not speak as their grammar and Bible taught them; but were offended with us,
and called us fools and idiots for speaking so.

--

It was fully in accord with the Scripture injunction
against adorning the person with splendid attire,
that the Society of Friends has always borne a testimony
in favor of a plain and simple manner of dressing.
At the time it arose there was an amazing amount of folly in fashionable dress.
Man submitted to be painted, gilded, feathered, and decked with ribbons, laces, ruffles,
wings,
swords and ornaments with bunches of gay ribbons attached to different parts of the body.
Yet the dress of religious people was plain and simple,
and when the Society of Friends first became a united people,
they made no alteration in their dress on account of their new religion.
But as the Society increased,
and many were incorporated into it as the children of members,
there arose a necessity for caution on this head.
In 1654 George Fox issued an epistle in which he counsels his friends:
"`Do not wear apparel to gratify the proud mind.`"
And three years later, he says:
"`Keep out of the vain fashions of the world in your apparel,
and run not after every new fashion that the world sets up.`"

[.offset]
That eminent minister, John Fothergill, records:

[.embedded-content-document]
--

When I was about twelve or thirteen years old, which was after my mother`'s decease,
a strong inclination took place in me to have a coat made with
some more resemblance of the mode or fashion of the time,
than in the plain manner, which I had, with other Friends, used,
and prevailed on my father to grant it;
but I was made uneasy in it almost at the first wearing it, and the more so in using it,
feeling the certain reproofs of the spirit of Truth, for leaning to,
and joining with the vain and restless flesh-pleasing spirit of the world,
and turning from the steady plainness of the unchangeable Truth.
I was indisputably satisfied,
that the enemy of all good worked in the earthly
affections of those wherein he could get place,
to draw out the mind at times, of the youth especially,
after the corruptions of the depraved world, in its changeable and vain fashions,
in dress and clothing, in order to lead into the broad way,
and by degrees into the wide world, one step making way for another.
On the other hand, I was in measure then, and have been since more immovably assured,
that the light of the Gospel day, the spirit of Truth,
does appear against and reprove the very conception of such vain desires and inclinations,
and would lead and preserve out of them, if people did but attend thereto,
and labor honestly to bear the cross of Christ in this respect.

--

[.offset]
John Woolman records in his Journal that:

[.embedded-content-document]
--

At our Yearly Meeting in Philadelphia, on the twenty-fifth day of the Ninth Month, 1764,
John Smith, of Marlborough, aged upwards of eighty years, a faithful minister,
stood up in our Meeting of Ministers and Elders,
and appearing to be under a great exercise of spirit,
informed Friends in substance as follows:
"`That he had been a member of the Society upwards of sixty years,
and well remembered that, in those early times, Friends were a plain,
lowly-minded people, and that there was much tenderness and contrition in their meetings.
That, at twenty years from that time, the Society increasing in wealth,
and in some degree conforming to the fashions of the world,
true humility was less apparent,
and their meetings in general not so lively and edifying.
That, at the end of forty years, many of them were grown very rich.
That wearing fine,
costly garments became customary with them and their sons and their daughters,
and many of the Society made a specious appearance in the world,
which marks of outward wealth and greatness appeared
on some in our Meeting of Ministers and Elders.
And, as these things became more prevalent,
so the powerful overshadowings of the Holy Spirit were less manifest in the Society.
That there had been a continued increase of these ways of life, even until now,
and that the weakness which had overspread the Society
and the barrenness manifest among us,
is matter of much sorrow.`"

--

John Banks, one of the early ministers in the Society of Friends,
in a testimony to the Truth, which he gave forth about the year 1671, says:

[.embedded-content-document]
--

The practice of the world is to change from fashion to fashion, in pride of apparel,
foods and drinks, to see who can exceed each other in pride and high-mindedness.

The practice of those who truly fear the Lord,
is to be plain and decent in their apparel, not giving to change,
as they of the world are,
nor to wear anything but what becomes the Truth and
may tend to adorn the Gospel of our Lord Jesus Christ.

--

Joseph Pike, who had been preciously visited by the spirit of the Lord when quite young,
says that, when at fourteen or fifteen years of age,
he was more allured by the pleasures and vanities of the world.
Among other things, he says:

[.embedded-content-document]
--

I was inclined to take pleasure in fine apparel and the likes, as I could get them,
of which I remember a particular instance.
Having got a pretty fine, new coat, the spirit of pride arose in me,
and passing along the street (I remember the place), I thought myself, as the saying is,
"`somebody,`" but amidst these vain and foolish thoughts,
I was in an instant struck as with an arrow from the Lord,
and it swiftly passed through my mind after this manner: "`Poor wretch!
Was not Jesus Christ, the Lord of heaven and earth, meek and low of heart,
and his appearance lowly on earth?
He was not proud and high.
Will you, poor worm, be high and proud of yourself or clothes?`"
These thoughts so wounded my spirit that I went home very sorrowful and dejected.

--

That the spirit of Truth does condemn the desire for gay and fine clothing,
has been the experience of many.
William Jackson, an honored minister of the Gospel, who lived in Chester County,
Pennsylvania, in a conversation with a friend, related the following incident:

[.embedded-content-document]
--

He said his parents were religious Friends,
much concerned to bring up their children in the
Christian plainness which Truth leads into.
As he grew towards manhood, he found the cross in regard to dress, irksome to him,
and desired more liberty in some things, which his parents were not easy to grant him.
On coming of age, he thought as he was now his own master, he would judge for himself,
and at a certain time he started to walk to a tailor`'s, who lived at some distance,
to get a coat made in a different manner from the one he had been used to wear.
He did not design to make much deviation,
but thought he might gratify his inclinations a little.
As he walked on the way during the stillness of the night,
the witness for God arose in his heart, and brought him under very serious feelings.
His mind became distressed;
he reasoned that it was but a little change he proposed to make;
it was too small a thing to be so uneasy about, and could not make much difference.
But the further he went, the more his uneasiness increased,
and at length he was so afflicted in mind, that he returned home, and went to bed,
where he passed a tossing night.
Nature pleaded hard for a little self-indulgence,
and the inward monitor followed him so closely with conviction,
that for some days he had little rest.
At length Truth prevailed,
and so fully was his mind humbled and made to bow under its crucifying power, that,
said he: "`I took the cloth to the tailor,
and told him to make me a coat just like my father`'s,
which was much plainer than I had ever worn; and as I had occasion for new clothing,
I had the rest made to suit it, and I have never made any change since,
nor had any desire to do so.`"

--

[.offset]
The testimony of Birmingham Monthly Meeting, Pennsylvania,
respecting the late James Emlen, says:

[.embedded-content-document]
--

A few weeks previous to his decease,
in conversing with a friend relative to one period of his life,
he said (in substance) he was a gay and fashionable young man,
but having been brought under the powerful hand of his Heavenly Father,
one of the first things in which he was required to take up the cross,
was in relation to the arrangement of his hair,
which he had been accustomed to wear in the fashionable mode of that time.
This sacrifice, he said, although it may seem, and is a very little thing,
was much against his inclination, but he yielded,
and experienced the reward of a peaceful mind.
Another requisition of duty which he found enjoined upon him,
was the use to a single person of the pronoun "`Thou.`"
He remarked that this was a great trial to him, but the peace which followed,
amply compensated for the sacrifice.
He was sensible, he said, that the work of religion was going on in his heart,
before he made any change in his personal appearance or in his mode of language.

--

In the year 1683, Friends at Norwich, Eng+++.+++,
were under severe sufferings on account of their faithfulness to
religious duty in the attendance of their meetings for Divine worship.
Sixty-three persons, both men and women, were in close imprisonment;
ten of them in a low dungeon far under ground, and others in the hole among felons.
The proceedings in this case were believed to be illegal,
and the statement of the circumstances having been prepared,
George Whitehead and Gilbert Latey were appointed to deliver it to the king,
on whom they had waited before on similar occasions.
The king was then at Hampton Court, where his council was about to meet,
and there the two Friends repaired.
They met the king surrounded by his nobles, as they were proceeding through the park,
and found an opportunity to lay the case before him,
and received his promise that it should be investigated.
Charles treated them kindly and courteously, and entered into conversation with them.
He asked them why they said "`thou`" and "`thee.`"
To which Gilbert Latey made answer:

[.embedded-content-document]
--

The same reason as the apostle Paul, when speaking to king Agrippa, he says,
I think myself happy, king Agrippa, that I shall answer for myself before thee,
especially because I know thou art expert in all customs, etc.
Also, king Agrippa, believest thou the prophets?
And, would to God not only thou, but also all that hear me this day,
were both almost and altogether such as I am, except these bonds!

Upon this the king made a little pause,
and seemed to question whether these passages were truly translated, yet said,
the translators might have translated "`you`" as well as "`thou,`" from the Greek;
upon which George answered: "`Then the translators were as simple as we Quakers.`"
The king replied: "`But you will not pull off your hats,
and what have you to say for that?`"
To which Gilbert answered: "`If to any mortal,
then to the king in the first place;`" but it is a matter of conscience,
and "`we only do it when we approach the Lord in prayer.`"

--

After some further conversation, in which part of the nobles took a share,
the Friends withdrew,
but not until George Whitehead again entreated the
king to remember the poor sufferers at Norwich,
which he promised to do.
This application to the king had its desired effect.
At the next court session which came on soon after,
the prisoners were all set at liberty, and no fees were demanded of them.

When Ruth Anna Rutter (afterwards Lindley) was a young woman,
before she became a member of the Society of Friends,
she was under deep religious conviction,
and felt it required of her to become plain in her attire;
at the same time she was distressed with the fear of running too fast.
She says:

[.embedded-content-document]
--

One day, being retired, I threw myself on the bed,
and taking up the Bible that lay by the side of it,
(scarce knowing what I did,) opened upon this passage: "`Put off your ornaments,
that I may know what to do with you.`"
I also had a dream which still further confirmed
me--I thought I was at the point of death,
and there seemed no help for me; and being in great agony I covenanted with the Almighty,
that if he would spare me a little longer, there was nothing which was required of me,
but what I would give up to, through his grace assisting me,
and that the remainder of my days should be dedicated to his service.
Immediately after I made this covenant I thought I saw myself recovered,
and in a plain garment very neat and simple.

Shortly after this I attended a general meeting at Uwchlan;
having made preparation thereto as secretly as I could.
I took the trimmings off one of my plainest silk gowns and cut off the trail.
I had a black bonnet made without much trimming,
which I wore instead of my hat and feathers.
There was a considerable number of young girls in company, going to the meeting,
and I endeavored to appear cheerful;
but my heart was secretly engaged in cries to the Lord that
I might hear something that would be confirming to me;
for I was then wavering whether or not I should join the Methodists.
We accordingly went to meeting,
and soon after I sat down a deep exercise covered my mind,
and after some time dear William Savery got up and spoke
so exactly to my state that my heart was much broken,
and my spirit contrited within me.
We lodged that night at a house where William Savery also was, who, with some others,
marking our appearance to be in the gay line of life,
wondered a little at our being there upon such an occasion;
but upon our telling them it was from a desire of attending that general meeting,
they in a pleasant way expressed their approbation, and spoke encouragingly to us.

After my return from this meeting,
the weight and necessity of my putting on a plain dress seemed to increase,
and one evening, most of the family having gone from home,
I sent to the shop for some plain gauze, and by twilight, with a darning needle,
made a little round eared cap.
Next morning I rose early,
but did not leave my chamber until most of the family had breakfasted;
being upon my knees, and earnestly petitioning to be rightly directed,
after which I went downstairs.
My father, mother, and a little nephew, were sitting at the table,
and as I entered the room my father viewed me (in a manner that
somewhat affected me) with silent astonishment at the alteration;
however I was favored to keep in a degree of quiet,
although it was indeed a deep trial to be thus exposed
to the observation of my connections and acquaintances.
But my dear sisters and brothers continuing to treat
me with their customary affection and respect,
my heart was, I trust, made measurably thankful.

As I labored under a heavy affliction from an inflammation in my eyes,
occasioned by a cold taken some time before I changed my dress,
which proceeded from my not taking necessary care when I left off my cushion,
and my health appearing to decline from the great exercise of mind I was under,
my parents sent me to the Yellow Springs, in Chester County, where I spent four weeks.
It happened to be in the time of their harvest frolics,
and being persuaded by some company who were there for their health,
I went to see them dance.
But oh, the distress of mind which I felt when entering the dancing room,
I cannot describe!
It seemed as if I were in a fire, and could not stay many minutes,
but walked into the balcony;
and shortly after left the company and retired to my chamber,
where I gave vent to many tears, and earnestly besought forgiveness for what I had done;
after which I felt a little quiet.

--

When Thomas Story came under religious conviction,
and was constrained to decline many things he had before practiced, he says:

[.embedded-content-document]
--

Some of my friends got together in a tavern, and my father with them,
intending to have me among them to drink a hearty glass,
and try in their way whether they could raise my spirits into a
more sociable temper and bring me off from such thoughts.

While they were contriving this scheme, I was retired alone into my chamber,
and favored with a sense of the good and soul-nourishing presence of the Lord;
but after some time a concern came upon me,
which gave me to expect something was in agitation concerning me,
and soon after an attorney-at-law, of my acquaintance, came from the company to me,
and mentioned certain gentlemen who desired to see me at the tavern.
I was not hasty to go, looking for the countenance of the Lord therein,
neither did I refuse;
but my father and some others being impatient to have me among them, came likewise to me.
I arose from my seat when they came in,
but did not move my hat to them as they did to me, upon which my father fell a weeping,
and said I did not use to behave so to him.
I entreated him not to resent it as a fault,
though I now thought fit to decline that ceremony,
it was not in disobedience nor disrespect to him or them,
for I honored him as much as ever, and desired he would please to think so,
notwithstanding the exterior alteration.
Most of the rest kept up another air, hoping to bring me into the same at the tavern,
but I through grace, saw their intents and was aware;
and I had now freedom in my mind to go among them.
When we came there, the company all arose from their seats, and seeming generally glad,
put on airs of pleasantness.
In seating themselves again,
they placed me in the midst of them and then they put the glass round,
and to relish it the more, they began a health to king William.
But the secret presence of the Lord being with me, though hidden from them,
it affected them all in a way they did not expect, for scarcely had two of them drank,
till their countenances changed and all were silenced.

The glass, nevertheless, went forward till it came to me,
and then I told them I wished both them and the king well,
and if I could drink to the health of any, I should more especially to the king`'s,
but should drink no health any more, and so refused it.
The glass never went round; for several of them fell to weeping, and were much broken,
and all of them were silenced for a time.
When this was over, some of them said they believed I intended well in what I did,
and that every man must be left to proceed in the
way which he thinks right in the sight of God;
and so we parted in solid friendship.
It was the secret grace of God which wrought this, and to Him, the Lord alone,
did I impute it.
The company dispersing,
I returned to my chamber in Divine peace and true tranquillity of mind,
with which I was favored for many days.

--

It is recorded of Gilbert Latey that,
having enlisted himself under the banner of the Lord,
made profession of his blessed Truth and taken up the cross, despising the shame,
bearing scorn and reproach,
it pleased the Lord to bring a trial upon him like the cutting off the right hand,
or pulling out the right eye.
For being still in great business in the world,
and concerned with persons of considerable rank,
who would have their apparel set off with much cost and superfluities of lace and ribbons,
he came under a conscientious concern not to meddle therewith,
nor permit his servants to put it on, which made some say he was mad.
Upon his refusing to be concerned in this superfluous part, the great people left him,
and his trade decayed so, that having a great many servants (assistants),
he was forced to part with them, not knowing but he,
who lately had such a great business and so many servants,
might now himself be a servant to some of the trade, and work at day labor for his bread.
This was a close trial, but he patiently waited the Lord`'s season.
Though despised even of his own mother`'s children, and as it were,
banished from his father`'s house,
yet he chose to leave all rather than to lose his peace with the Lord.
And He who never forsakes those who trust in Him, was his support,
bore up his spirit through all his exercises,
and enabled him to be resigned and contented in his will.

It is related of a bishop of London,
that being in need of some article connected with house furniture,
he sent to the house of a Friend in the city for patterns of the article he wanted.
When the bishop`'s message reached the Friend`'s shop, the Friend was absent,
but a young and consistent Friend in his employ went
to the palace with the desired patterns.

After having shown them to the bishop, he was desired to leave them until next morning,
when, after the approval of a pattern,
a message should be forwarded to the house for a party to return and take the order.

When the young man reached the warehouse he found his employer there,
who queried of him "`Where he had been,`" and on being informed, remarked very sharply,
that he supposed he should lose the order, from the young`'s man`'s stiffness,
and requested to be informed when the bishop`'s messenger arrived.

The following morning the bishop sent down, according to promise, and the Friend,
having been acquainted, away he started.
On being introduced to the bishop, the Friend made a profound bow,
and accosted the bishop in a manner quite inconsistent with his profession.

The bishop, perceiving this,
asked him "`If he was the person who called upon him yesterday?`"
To which the Friend replied: "`No; he had left the young man at home,
as he preferred calling personally.`"
The bishop told him that he should prefer seeing
the person who had previously called upon him,
and added to the following effect: "`Let me give you a few words of advice,
never to be ashamed of consistently carrying out your profession, for,
however much others may differ from you in religious opinion,
they always admire the conduct of those who consistently carry out the views they hold.`"

The Friend who transcribed the foregoing incident, Fifth Month 19th, 1850,
had the account from the young man himself.

[.offset]
Charles Marshall records:

[.embedded-content-document]
--

The visit of God`'s holy and ever-blessed day was eminent; and in his fear and dread,
we received the Gospel with a ready mind, and with broken hearts,
and gave up to follow the Lord fully,
casting off the weights and the sin that easily besets,
and departed from the evil ways and vanities of this world;
stripping off all needless apparel, and forsaking superfluities in foods and drinks;
walking in the plain, self-denying path, having the fear and dread of God in our souls,
whom we were afraid of offending in word or deed.
Our words were few and savory, our apparel and houses plain,
being stripped of superfluities, our countenances grave, and deportment weighty,
among those we had to do with.
Indeed, we were a plain, brokenhearted, contrite-spirited people;
our souls being in an inexpressible travail,
to do all things well-pleasing in the sight of God.
Our concern, night and day, was to obtain, through Jesus Christ,
the great work of salvation, and thereby,
an assurance of the everlasting rest and Sabbath of our God.

--

The Journal of Thomas Chalkley contains the following narrative of his
care to observe the testimonies of our Society as to plainness:

[.embedded-content-document]
--

Thinking it convenient to send our little children to school,
and not having a schoolmaster of our Society near us,
we concluded to put our son and daughter under the care of Nathaniel Walton,
to whom I thought it my duty to write a few lines about the salutations
and language I would have them trained up in,
which were as follows:

[.signed-section-context-open]
Frankfort, thirtieth of Fifth Month, 1727.

[.salutation]
Loving friend, Nathaniel Walton:

I hope thou wilt excuse the freedom I take with thee
in writing this on account of my children,
in these particulars, namely: Respecting the compliment of the hat and courtesying,
the practice thereof being against my professed principle: First,
because I find nothing like it in the Bible; but, as I think, the contrary.
Thou knowest the passage of the three children of God,
who stood covered before a mighty monarch; and Mordecai,
who could not bow to great Haman; Second, I believe those practices derived from vain,
proud man.
And as to language,
I desire my children may not be permitted to use the plural language to a single person,
but I pray thee to learn them to say "`Thee`" and
"`Thou,`" and "`Thy,`" and to speak properly,
many using it improperly; and the rather, I desire it,
because it is all along used in the Divine, inspired, holy writings.
I know it is generally objected that the end of speech is to be understood.
It is understood better in and according to the language of God,
Christ and the Holy Spirit, in the Bible, and the language of kings, and all people,
as we read it in the Holy Scriptures.
Why, then, should we be ashamed of it, or shun it,
and bring in and uphold a custom contrary to it?
The same care I would have thee take about the names of the days and months,
which are derived from the names of the gods of the heathen,
and are not found in the Bible.

--

When Joseph Pike, of Cork, Ireland, was engaged in business,
many opportunities of enriching himself by speculative enterprises were offered to him.
But everything of this character he steadily declined, being unwilling to burden himself,
or set an ill example for others to follow.
On one occasion, a proposal was made to him to purchase a large quantity of tobacco,
when there was a likelihood of making a great profit, and no apparent danger of losing.
But, on considering the subject, he felt it to be his duty to decline it,
that the way of Truth might not, through his agency, be evilly spoken of.
Another person, who had not the same scruples, or did not obey them,
availed himself of the opportunity, by which he made several thousand pounds.
In relation to his own conduct on this occasion, Joseph Pike says: "`I never repented it,
for if it were to do again,
and I was sure of getting the same profit which the other did, I would still decline it,
for the same reasons.`"
And upon this subject he adds these weighty remarks,
which are worthy the consideration of all who are tempted to engage in hazardous enterprises,
or to embark in any business of a character to overcharge and burden the mind.
"`But notwithstanding,`" he says,
"`I have often declined the prosecution of prospects
that carried a fair appearance of profit,
yet I will not, and dare not, say, that they would have answered accordingly;
for the Lord having blessed me in moderate dealing,
he might have turned his hand against me, and frustrated my expectation,
if I had overcharged myself with business,
to the hinderance of that little service I had to do for him.
And I can say, in the sincerity of my heart, that I never inclined or strove to be rich,
or to make my children great or high in the world,
seeing the ill effects of it in others.`"

Indeed, it may truly be said of Joseph Pike, that he was a man "`fearing God,
and hating covetousness.`"
Against this evil, which often increases in old age, he bore a strong testimony,
and in the latter years of his life, he makes these remarks in reference to it: "`Oh,
this spirit of covetousness!
Where it prevails how it darkens and clouds the understanding,
and eats out all that is good!
The zeal of the Lord burns in my soul against it,
and I believe there are few greater evils in the sight of the Lord than this,
though there are few evils that have more cloaks and coverings than this has.`"

The late John Barclay, of Croydon, Eng+++.+++, although brought up in a fashionable manner,
believed it his duty to live plainly and simply.
On the twenty-fourth of Twelfth Month, 1836, he wrote to a young friend:

[.embedded-content-document]
--

Picture to yourself any set of people raised up to a deep sense of religion,
and carrying out their watchfulness and self-denial to all branches of their conduct,
and endeavoring to follow that exhortation:
"`Be holy in all your conduct,`" and whatsoever you "`do in word or deed,
do all to the glory of God,`" etc.,
Would they not soon come to be distinguished from other people,
who follow the course of this world,
or who secretly yearn after their own hearts`' lusts,
and comfort themselves with trying to think there
is nothing in this and the other little thing,
and that religion does not consist in these things?
Would they not soon find themselves to be a peculiar people; their outward appearance,
their manners,
their very gestures restrained and regulated after a mode
totally contrary to the generality of those around them?
According to that striking passage in one of the Apocryphal writings,
setting forth the language of the ungodly respecting the righteous,
so will it be respecting such a people or person as I have described:
"`He is not for our turn, he is clean contrary to our doings;
he was made to reprove our thoughts; he is grievous unto us even to behold;
for his life is not like other men`'s, his ways are of another fashion.`"

Indeed, it has never been any wonder with me, that a people gathered,
settled and preserved, as I have hinted at--or as Friends were,
when they found themselves estranged from the world at large, and eccentric,
through the process of following their convictions of duty,
should value this their privilege, and these outward badges,
which tend to keep up this desirable distinction and separation from the world`'s spirit.
But they never set up a rule as to dress, or any particular color, cut or fashion,
on the same footing as the livery of the monks, or religious orders of the Papists, etc.;
they only left off their ornaments and such things as were a burden to them,
as unnecessary and unsimple;
it was the ever changeable tide of fashion which did the rest, and, in time,
caused their dissimilarity and strangeness to appear.
But as to the base assertion that George Fox and
the early Friends would have changed with the times,
it is a conjecture which has its origin in the mere
caprice and inclination of those who say so;
and the contrary may be as flatly and broadly asserted upon far stronger grounds,
even upon the actual facts of the whole tenor of their dissent,
as exhibited in their lives, and especially in their writings.
The common consent spoken of,
is the very conformity they objected to--a consent of worldly men,
upon worldly principles, not the consent of men redeemed from the earth.
On the other hand,
all that have ever rightly given up to make a plain
appearance and to speak the plain language,
etc., have done it on the very same ground,
and not merely because George Fox and others did it.
They, the truly convinced, have continued to feel on the subject as he did;
and though the instances are rare, as the mercy is great and the work marvellous,
and no light and superficial one, such instances are yet from time to time occurring.
They are the result of cleansing the inside of the cup,
that the outside may become clean also.

My case is, I trust, one of these, and perhaps rather an unusual one,
for I was brought up, as you know, in the entire disuse of,
and I even cherished a real contempt for such singularities;
until I came to see that there was "`No peace to the wicked,`" and that "`great
peace have all they who love`" "`the law of the spirit of life in Christ Jesus.`"
Then as I yielded my mind to be in all things led and guided thereby,
nothing offended me but evil, nothing seemed too hard to give up unto,
nor anything to be slighted as insignificant,
which in any wise contributed to this heavenly peace and
progress in what was esteemed so supremely excellent.

--

The Journal of Thomas Chalkley alludes to the dealings
of the Lord with him when in very childhood,
recurring to the various exercises and trials which
he underwent when but eight or ten years of age,
on account of his plain manner of dressing,
being thus known as a "`Quaker,`" and that often on his way to and from school,
he was stoned and beaten,
"`Several telling me it was no more sin to kill me than it was to kill a dog.`"

[.offset]
Thomas Chalkley relates the following:

[.embedded-content-document]
--

One time I remember being among some men, one of whom I had reproved,
and he told the rest of it,
and turned to me and said "`That I was no Christian,`"
and asked me "`When I said the Lord`'s prayer?`"
I asked him if he said it.
He replied "`Yes.`"
I then asked him, how he could call God, Father,
and be so wicked as to swear and take God`'s name in vain,
which I had heard him often do?
And I told him what Christ said to the Jews: "`You are of your father, the devil,
because his works you do;`" and that those that did
the devil`'s work could not truly call God,
Father, according to Christ`'s doctrines.
Being convicted in their consciences that what I said was true, they were all silent,
and wondered that I, being so young, should speak in such a manner.
In which, I remember, I had great peace and good satisfaction.
And from thenceforth these men let me alone.

--

[.offset]
His Journal goes on to say:

[.embedded-content-document]
--

Notwithstanding I hated to hear wicked words, I loved play exceedingly,
being persuaded that there was no harm in it, if we used no bad words.
One time I was at play at a neighbor`'s house with the children,
and in the midst of my sport I was reached with strong conviction,
insomuch that I could not forbear weeping.
The children`'s mother, observing that I wept, said: "`Why do you weep?`"
I told her I could not tell, except it was because I was a naughty boy.
"`Oh,`" said she, "`don`'t believe him, for that`'s the devil tells you so,
for you are the best boy in all our street.`"
But I knew I was told the truth by conviction, and that she was mistaken,
for I plainly understood by clear conviction and by the Holy Scriptures,
which I had been trained up in the reading of, that I was too vain and careless;
for I loved music, dancing and playing at cards, and too much delighted therein,
and was followed with the judgments of God therefor in the secret of my soul.
What I did in those sports and games, I always took care to do out of sight,
and without the knowledge of my tender parents,
for I was afraid of their reproofs and corrections, the which I was sure to have,
if they had any intelligence of it.

--

He mentions at one time being at his uncle`'s, where he had gone on a visit,
taking with him a pack of cards which he had purchased,
but on his way he attended a meeting,
in which the minister declared against the evil of gaming, particularly of cards.
He says:

[.embedded-content-document]
--

From this meeting at Wanstead I went to the house of my relations,
where the parson of the next parish lodged that night,
who used to play cards with them sometimes.
The time drawing near that we were to go to our games, my uncle called to the doctor,
as he styled him, to me and to my cousin, to come and take a game of cards;
at which motion I had strong convictions upon me not to do it, as being evil,
and I secretly cried to the Lord to keep me faithful to him, and lifting up my eyes,
I saw a Bible lying in the window, at the sight of which I was glad.
I took it and sat down, and read to myself,
greatly rejoicing that I was kept out of the snare.
Then my uncle called again, and said: "`Come, doctor, you and I, my wife and daughter,
will have a game of cards, for I see my cousin is better disposed.`"
Then he looked upon me, and said he was better disposed also.

--

[.offset]
He goes on to say:

[.embedded-content-document]
--

So their sport, for that time, was spoiled, and mine, in that practice, forever,
for I never, as I remember, played with them more, but as soon as I came home,
offered my new and untouched pack of cards to the fire.
I am certain the use of them is of evil consequence,
and draws away the mind from heaven and heavenly things.

--

[.offset]
Mary Alexander states:

[.embedded-content-document]
--

At this time, while young,
I was favored to receive much comfort in reading the Holy Scriptures,
which I often took up when alone, to my consolation and encouragement.
Then deeply did I lament,
that any of my precious time had been spent in perusing
publications of an unprofitable tendency;
such as plays and romances;
and I was made sensible that nothing I had ever been in the practice
of had so much alienated my mind from the love and fear of God,
or led me so far from the simplicity of the pure Truth as books of this kind.
How often did I wish I could warn the whole world of their pernicious effects,
and especially the young people in our Society.
Penning this remark,
brings to my remembrance how in an instant I was entirely weaned
from ever desiring again to look into a book of this description.
It was by a few words expressed by a beloved friend when
I was about reading to her one night after we got up stairs,
and were retiring to bed.
She queried with me, and I believe under Divine influence, "`Dear Mary,
is such a subject likely to profit us upon our pillows?`"
The question so forcibly struck my mind,
that I very willingly laid down the volume and to the best of my remembrance,
I never more read a page in that, or anything of the like kind.
I have often thought those few words were indeed,
"`Like apples of gold in pictures of silver.`"

--

[.offset]
A writer in _The British Friend_, says:

[.embedded-content-document]
--

The plain language of Friends, like their plain dresses,
has been of much use in preserving them from the follies and temptations of the world.
The character of Friends as a society is well known,
and it is also well known that they regard as wrong a great
many actions that people generally look upon as harmless;
and so it happens that the mere fact of a person being known,
as a Friend often prevents him from being tempted to do things
which otherwise he would be expected and asked to do.
In the same way, a man who is known to be a member of a total abstinence society,
will seldom be pressed to drink intoxicating liquor.

The use of the pronouns "`thee`" and "`thou`" in ordinary speech,
is a peculiarity of Friends, but it is not peculiar to them alone, although,
perhaps few people, if any, have like the Friends,
looked upon it as springing from religious principle,
and therefore have not attached so much importance to it.
But, probably few people are aware that all members of the Hungarian
Parliament must address one another as "`thou.`"
This rule was promulgated by Francis Deak,
who looked upon it as the only way of abolishing caste prejudices in Hungary.
One of the Hungarian noblemen got into serious trouble through writing a letter
to a colleague in which he addressed him as "`you`" instead of "`thou.`"

In Hungary, and I believe in most countries in Europe, if not in them all,
"`thee`" and "`thou`" are used only in addressing people of a lower worldly rank,
or familiar friends.
This used to be the custom in Great Britain also, and is to some extent even yet,
especially in remote country districts.
The Highlanders, in speaking Gaelic, make the same distinction,
and so do our far-away Shetland countrymen in speaking English.

At the trial of Sir Walter Raleigh,
the lawyer who conducted the prosecution against
him "`thou`'ed`" him in a very bitter speech,
saying in the course of it: "`I '`thou`' thee, thou traitor.`"

--

Thomas Elwood joined Friends in his youth, very much against the will of his father,
who persecuted him sorely for adopting the Quakers`' unfashionable and impolite peculiarities,
such as refusing to take off his hat in his father`'s presence,
and addressing him as "`thou.`"
Poor Ellwood had all his hats torn off his head by his enraged parent,
and was obliged to go about bareheaded; and after his hats were all gone,
and it became impossible for him to offend more in that way,
he was hardly a bit better off,
for he could not speak to his father without offending him:

[.embedded-content-document]
--

I dared not, +++[+++writes Thomas,]
say "`you`" to him, but "`thou`" or "`thee,`" as the occasion required,
and then would he be sure to fall on me with his fists.
At one of these times, I remember, when he had beaten me in that manner, he commanded me,
as he commonly did at such times, to go to my chamber, which I did,
and he followed me to the bottom of the stairs.
Being come there, he gave me a parting blow, and, in a very angry tone, said: "`Sirrah,
if ever I hear you say '`thou`' or '`thee`' to me again,
I`'ll strike your teeth down your throat!`"
I was greatly grieved to hear him say so.
And feeling a word rise in my heart unto him, I turned again and calmly said unto him:
"`Would it not be just if God should serve thee so
when thou sayest '`Thou`' or '`Thee`' to Him?`"
Though his hand was up, I saw it sink, and his countenance fall,
and he turned away and left me standing there.

--

[.offset]
Samuel Neale, when a young man,
accompanied Garratt Van Hassan on a religious visit in Ireland.
He says:

[.embedded-content-document]
--

On our return we called at Christianstown, and stayed a few nights there,
where I met with a remarkable occurrence:
I had been used in former times to walk out with my gun and dog;
it was a retired way of amusing myself, in which I thought there was no harm;
and reasoning after this manner, though I was very thoughtful about leading a new life,
yet I now went out as formerly.
I remember I shot a brace of woodcocks, and on my return home it rained,
and I went to shelter myself by a stack of corn;
when it struck my mind as an impropriety thus to waste my time in this way of amusement,
so I returned rather heavy-hearted.
Dear Garratt and I lodged together; and the next morning he asked me if I was awake,
I told him I was; "`I have something to say to you,`" said he; I bid him say on.
"`It has been,`" said he, "`as if an angel had spoken to me,
to bid you put away your gun;
I believe it is proper that you should put away that amusement.`"
To this purport he spoke; and that same night I dreamed that it was said to me,
intelligibly in my sleep, that if I would be a son of righteousness,
I must put away my gun, and such amusements; it made a deep impression on my mind,
and I concluded to give up everything of the kind,
and take up my daily cross and follow the leadings of the Lamb,
who takes away the sins of the world.

--

John Thorp, the day before his peaceful close,
related to his family the following circumstance, which occurred in his youth.
He said:

[.embedded-content-document]
--

When a boy, about fourteen years of age, my attachment to music was such,
that when walking in the lanes and fields on an evening,
I frequently gratified myself by singing aloud; and indulged therein,
even after my mind became uneasy with the practice, until,
in one of my solitary evening walks, and when in the act of singing, I heard, as it were,
a voice distinctly say: "`If you will discontinue that gratification,
you shall be made partaker of a much more perfect harmony.`"

--

Such was the powerful and convincing effect of this solemn and awful communication, that,
he added, he never afterwards indulged in the practice.

He also mentioned the case of another, who, prior to joining the Society of Friends,
had been a great singer, of whom John Richardson remarked:
"`He was the greatest singer in that part of the country where he resided,
and sung then the songs of Babylon by the muddy waters thereof;
but having drunk deep of the brooks of Shiloh,
which run softly into the newly converted soul,
he could sing and rejoice in the Lord Jesus Christ.`"

When John Churchman and John Browning were travelling in Talbot County, Md.,
an elderly man asked them if they saw some posts standing, pointing to them, and added,
the first meeting George Fox had on this side of
Chesapeake Bay was held in a tobacco-house there,
which was then new, the posts that were standing were made of walnut;
at which J. B. rode to them, and sat on his horse very still and quiet;
then returning again with more speed than he went,
J+++.+++ C. asking him what he saw among those old posts, he answered:

[.embedded-content-document]
--

I would not have missed of what I saw for five pounds;
for I saw the root and grounds of idolatry.
Before I went,
I thought perhaps I might have felt some secret virtue
in the place where George Fox had stood and preached,
whom I believe to be a good man; but while I stood there, I was secretly informed,
that if George Fox was a good man, he was in heaven, and not there,
and virtue is not to be communicated by dead things, whether posts, earth,
or curious pictures, but by the power of God, who is the Fountain of living virtue.

--

A lesson which, if rightly learned,
would wean from the worship of images and adoration of relics.

The winter after,
John Churchman being out on a religious visit with two Friends in Maryland,
attended Sassafras Meeting, of which John Browning was a member,
but had then been deceased about a month.
He +++[+++J. C.]
called to see the widow and children,
and she gave him in substance the following account of J. B.:

[.embedded-content-document]
--

"`My husband was not long sick, but said he believed he should not recover,
and charged me to endeavor that his children should be brought up in the way of Truth,
which Friends profess, and if they incline to have trades,
to put them apprentice to real Friends,
not barely nominal ones (which she said she was willing to do,
though she had never yet joined to Friends),
and desired she would not trust her own judgment,
and named some Friends with whom she should advise in choosing masters.
Then said, when I am dead, bury me by my father and mother,
in the graveyard belonging to our family;
and you know that I put a large gravestone at my father`'s grave,
and there is one ready for my mother`'s grave, which I did not put there,
because I began to think they were more for grandeur than service.
I sent for them from England (not at the request of my father), they are mine,
and now I have a full testimony against such formal tokens of respect;
therefore when I am buried, before the company leave the grave,
inform them what my will is,
and desire their help to take the gravestone from my father`'s grave,
and carry it out of the yard, that it may be brought home,
and lay one in one hearth and the other in the other hearth of this new house,
and they will be of real service there (he had built a new brick house,
and the hearth not fully laid), which she promised him to observe,
and told me she had complied therewith.
He remained sensible to near the last, and departed in a quiet, resigned state of mind.`"

How weak are the arguments of such who make profession with us,
and plead for those grand marks of memorial, or other tokens of distinction,
set up at or on the graves of their deceased relations, and how soon would they subside,
did they but live so near the pure truth as to feel the mind thereof,
as I fully believe this our friend did,
knowing that the name of the righteous will not perish,
but be had in everlasting remembrance, because their portion is life forevermore.

--

Bishop Nicholson, with a company of priests, called at John Roberts`',
who invited him to come into his house; but the bishop declined,
yet said he would drink with him.
After directing beer to be brought, John returned to the coach-side.
A kinsman of the bishop pertly asked the Friend,
"`Is your house free to entertain such men as we are?`"
John Roberts replied: "`I entertain honest men, and sometimes others.`"
The man remarked to the bishop: "`My Lord, John`'s friends are the honest men,
and we are the others.`"
To which John rejoined: "`That is not fair, for you to put your construction on my words;
you should have given me leave to do that.`"
Squire Masters came out of his coach, and standing by the bishop`'s coach-side,
said in a diverting humor to John Roberts:
"`My lord and these gentlemen have been to see your burying-ground,
and we think you keep it very decent.`"
John had given this piece of ground to Friends for that purpose.
He answered: "`Yes; though we are against pride, we think it commendable to be decent.`"
The chancellor then said:
"`But there is one thing among you which I did not expect to see;
I think it looks a little superstitious.
I mean those gravestones which are placed at the head and feet of your graves.`"
John Roberts: "`That I confess is what I cannot much plead for,
but it was permitted to gratify some who had their relatives interred there.
We, notwithstanding, propose to have them taken up before long,
and converted to some better use.
But I desire you to take notice, we had it from among you,
and I have observed in many things wherein we have taken you for our pattern,
you have led us wrong, and therefore we are now resolved, with the help of God,
not to follow you one step further.`"

Such was the high Christian character which Friends held,
that putting gravestones to mark the place of interment of the body of anyone,
struck this professor in the church as inconsistent with their religious principles
and their testimony against superstitious treatment of the dead.
John Roberts`' confession, that they could not consistently plead for it,
and that they proposed to remove them, showed that faithful ones had had their scruples,
and they had determined to come to a stop, and to follow their neighbors no longer.

Wherever the members of our Society lose the conscientious scruples
which they have once felt to support its principles undeviatingly,
we shall see one innovation after another creeping in among them,
and numbers and influence in the Society steadily-paving the way for these
deviations to be openly advocated and finally pleaded for,
as no departure from what the Christian churches generally consider as proper,
or unimportant.
In this way we may be in heart, and in many things, mixed again among the people,
our strength being devoured by them, and, like Ephraim, know it not.
A Christian grows in the Divine life by little and little, and if he gets off the watch,
he may fall away by little and little,
until his religion is no more than a shell without the kernel or substance.
Yet the worldly wise may own and flatter him, as he advocates their views,
and maintains something of an honorable standing among men.
Such uphold one another, and take their ease in the example and authority of numbers,
but where is their obedience and their love to the pure Truth?

Instances are on record, too,
of the punishment of early Friends by the magistracy for enclosing their burial grounds,
among which may be narrated that of Edward Vivers,
who in 1665 was taken from his business by order
of the lord lieutenant of the county of Oxford,
and kept in confinement two years and seven months.
Perhaps there is nothing more difficult to contend with
than prejudices which are the fruits of early teaching,
and the results of priestly influence;
and it is easy to understand how the enclosure of ground for the
purpose of sepulture became a cause of offence to those who,
apart from the sacerdotal question,
had come to look upon such enclosures as something sacred,
and appertaining alone to what was termed the "`church.`"

Having, however,
taken their stand upon the broad principle of the freeness of the Gospel,
and the consequent liberty in all things pertaining to it,
our early Friends persisted in the course they had entered upon.
Francis Howgill, one of the most explicit writers among them at that day,
and from his early associations and pursuits,
one of the best informed on ecclesiastical matters, remarks,
in reference to burial-grounds and burial yards:
"`Abraham was the first that we read of that made any place of burial in Hebron,
which he bought of Ephron the Hittite for thirty shekels of silver,
and there was he and his wife buried, and this was no parish yard,
neither did he have any priest or clerk that we read of to receive wages and fees, etc.,
for ringing a bell and reading or saying a service over the body.`"
And in reference to the origin of that piece of absurdity called consecration of graveyards,
he informs us that "`Urbanus, the seventeenth bishop of Rome,
was the individual who first ordained churchyards to be hallowed;`" and quoting Gaudensius,
reminds us "`that of old time they did bury their dead in their own ground,
which custom was taken away by pope Innocent III,
who prohibited that any should cause themselves to be buried in unconsecrated ground.`"
And according to the testimony of another writer, Hospinius,
"`The custom of being buried in order near the church,
at last became so superstitious that they judged it needful even for their salvation.`"

We cannot wonder that early Friends, having adopted a purer Christianity,
forsook the practices which, having their root in popery,
had thus spread through the length and breadth of the land,
and had obtained such hold on the minds of the people.
With them the question of sepulture became one of simple truth,
and by their course of action they restored the solemnity
of that most eventful period of our humanity,
the passage to the silent grave.
With Francis Howgill they considered that "`churchyards`"
in which to bury their dead in its origin was superstitious,
and all the ringing and singing, and the reading before and over the body,
as idolatrous and superstitious, and therefore to be avoided.
Thus they became prepared to adopt the counsel of George Fox: "`That all Friends,
who are not already provided, should speedily procure convenient burying places,
that thereby a testimony may stand against the superstitious
idolizing of those places called holy ground.`"

We see, then, that what we are now pleased to call one of our peculiarities,
was in reality in the eyes of early Friends a Christian testimony.
Let us be careful that in the change of expression we do not sacrifice anything of principle.

Having come to the conclusion that the Society ought to free itself from all
participation in the superstition which clung to the then modes of sepulture,
it was not surprising to find that resort was had to the interment in private grounds,
and that many families, more especially in rural districts,
set apart small detached plots on their own estates as family burial places.
Hence we find scattered up and down where Friends are now very much extinct as a body,
small detached graveyards, some under the care of the Society,
and some that have long since passed into other hands, but which latter,
from reverence to the dead, are still kept enclosed and unoccupied.
However this mode of sepulture might suit a nomad state,
it was a salutary regulation on the part of the Society to direct that Friends should
have well ordered burial-grounds under the care of the body for the purposes of sepulture;
and it was almost a natural consequence that with this regulation they
would discard all the ceremonies and pomp that prevailed in the world.
Hence we find it recorded by their historian "`That
in the burial of the dead they mind decency,
and endeavor to avoid all pomp; and the wearing of mourning is not approved by them,
for they think that the mourning which is lawful may be
shown sufficiently to the world by a modest and grave deportment.`"

This severe simplicity, which extended itself to the very grave`'s mouth,
in the absence of everything like ornament on the receptacle of the corpse,
was indeed a great offence to the customs of the age.
It called forth much animadversion from the world,
and caused no small amount of suffering to those who adopted
it--numerous individuals were committed to prison,
great persecutions were endured, and much pecuniary loss borne,
for the simple act of attending the mortal remains
of their friends and relatives to the grave.
So sweeping at times were the raids upon the mourners and attenders at funerals,
that instances are recorded where large bodies of
Friends were swept away at once to prison.
In Somersetshire in 1675, thirty-two persons were fined for being at a funeral,
and had cows, corn and other goods taken from them for penalties,
amounting to upwards of eighty-two pounds.

So offensive to the public mind was the mode of sepulture adopted by Friends,
that it became a proverb of reproach "`That the newly-risen
Society buried its members like dogs.`"
This accusation was not likely to lessen the sufferings of Friends,
and accordingly we find George Fox, ever equal to an emergency,
issuing an address from the press,
under the title of [.book-title]#Encouragement to All to Trust in the Lord#.
In this document he remarks:

[.embedded-content-document]
--

You see what entertainment the Lord of glory had when He came into the world--a manger,
instead of a cradle;
and when He went out of the world the Scripture does
not say that He had so much as a coffin.
Joseph of Arimathea wrapped his body in linen, and laid it in a sepulchre in a garden.

And all you that say we bury like dogs,
because that we have not superstitious and needless things
upon our coffins and a white and black cloth with escutcheons,
and do not go in black, and hang scarfs upon our hats,
and white scarfs over our shoulders, and gold rings,
and have sprigs of rosemary in our hands,
and ring bells--how dare you say that we bury our people like dogs,
because we cannot bury them with the pomps and glory of the world?
Whereas you do not read that Christ, the Prince of Life, our Lord and Saviour,
had any of these things, neither when He came into the world,
nor when He went out of the world;
and refused the pomp and glory of it when the devil tempted Him with it.

Therefore,
follow not the pomps and glory of this world at your children`'s coming into the world,
nor bring them up in the pomp and glory of the world in the times while they live,
nor use them at going forth out of the world; but follow Christ Jesus,
who is not of the world, who is your Redeemer, your Saviour, your Way,
your Truth and Life, your Bishop, your Shepherd, your Priest,
your Prophet--and let Him rule in your hearts by faith,
who will give you life abundantly, who is from above and not from below.
That you may be built upon Him, the living rock, and the foundation of God stands sure.
Amen, amen, says my soul.

--

The testimony of William Edmundson as to the concern that rested on the minds of early
Friends to be preserved from the inroads of any worldly spirit is instructive.
He says:

[.embedded-content-document]
--

At the first, when the Lord called and gathered us to be a people,
and opened the eyes of our understandings, then we saw the exceeding sinfulness of sin,
and the wickedness that was in the world;
and a perfect abhorrence was fixed in our hearts against all the wicked, unjust, vain,
ungodly, unlawful part of the world in all respects.
And we saw the goodly and most glorious lawful things of the world,
were abused and misused--and that many snares and temptations lay in them,
with troubles and dangers of various kinds, which we felt the load of,
and that we could not carry them, and run the race the Lord had set before us,
so cheerfully as to win the prize of our salvation.
Wherefore our care was to cast off this great load and burden; that is,
great and gainful ways of getting riches, and to lessen our concerns therein;
that we might be ready to answer Christ Jesus, our Captain,
who had called us to follow Him in a spiritual warfare
under the discipline of his daily cross and self-denial.
Then the things of this world were of small value with us, so that we might win Christ,
and the goodliest things thereof were not near us, so that we might be near the Lord;
for the Lord`'s Truth outbalanced all the world, even the most glorious part of it.

--
