== Chapter IV. Convincement

The early members of our Society felt themselves to be servants of the Lord Jesus,
and to the extension of his grace and good spirit they looked
for any good fruits from their labors in his cause.
For, as William Penn expresses it: "`Without this secret, Divine power,
there is no quickening and regenerating of dead souls.
The bent and stress of their ministry was conversion to God, regeneration and holiness;
not schemes of doctrine and verbal creeds, or new forms of worship.`"
They were not satisfied that men should accept the truth of the doctrine they preached,
merely from a conviction of the intellect;
but they earnestly pressed the necessity of their
being thereby changed in heart and life.

[.offset]
Robert Barclay in his Apology interestingly relates his own experience.
He says:

[.embedded-content-document]
--

It was not by strength of argument, or by a particular disquisition of each doctrine,
and convincement of my understanding thereby,
I came to receive and bear witness of the Truth,
but by being secretly reached by this life;
for when I came into the silent assemblies of God`'s people,
I felt a secret power among them which touched my heart, and as I gave way unto it,
I found the evil weakening in me, and the good raised up,
and so I became thus knit and united unto them,
hungering more and more after the increase of this power
and life whereby I might feel myself perfectly redeemed.
And indeed this is the surest way to become a Christian,
to whom afterwards the knowledge and understanding of principles will not be lacking,
but will grow up so much as is needful, as the natural fruit of this good root,
and such a knowledge will not be barren nor unfruitful.
After this manner we desire therefore all that come among us to be proselyted,
knowing that though thousands should be convinced
in their understanding of all the truths we maintain,
yet if they were not sensible of this inward life,
and their souls not changed from unrighteousness to righteousness,
they could add nothing to us.
For this is that cement whereby we are joined, as to the Lord, so to one another.
Indeed, if such should come among us,
and from that understanding and convincement they have of the Truth,
speak ever so true things and utter them forth with ever so much excellency of speech,
if this life were lacking, it would not edify us at all,
but be as sounding brass or a tinkling cymbal.

--

In the records of our Society there are preserved many interesting narratives
of the work of Divine grace in effecting convincement and conversion.
One of these is the account left of her experiences by Jane Fenn, afterwards Jane Hoskins.
It contains so much of spiritual instruction and is so full of life,
that an outline of it may profitably be inserted here.

She was a native of England,
and brought up as an Episcopalian--coming under the operations of Divine grace,
she felt that it was the Lord`'s will that she should go to Pennsylvania.
She was quite young, and her father being opposed to her removal,
she found no way of carrying out her concern except by persuading one,
Robert Davis who was himself going over the sea, to pay her passage,
with a promise that she would repay him out of her future earnings.
After her arrival in Philadelphia,
Robert insisted that she should bind herself as a servant for four
years to a person that was an utter stranger to her;
and on her refusal, had recourse to law, and by process laid her under confinement.

This was a trying experience for a poor young creature among strangers.
But, she says, the Lord heard her cries, raised up friends, and provided for her.

[.embedded-content-document]
--

The principals of four families living at Plymouth who had several children,
agreed to purchase a sober young woman, as a school mistress,
to instruct them in reading, etc.
On applying to their friends in town, I was recommended for that service.
When we saw each other, I perceived it my place to go with them.
Wherefore on their paying Davis twelve pounds, currency,
being the whole of his demand against me, I bound myself to them, by indenture,
for the term of three years, and went cheerfully with them to Plymouth.

I have since thought, how wonderful it was,
that though various scenes and trials attended me,
yet I was enabled to perform the service they had for me.
The children learned very fast; which afforded comfort to me,
and satisfaction to their parents.
My love to them was great, and theirs equally so to me;
so that all my commands were obeyed with pleasure.
And afterwards, when we met, we could tell one another of it,
with sincere regard and affection.
They proved sober, religious men and women.

I served my time out faithfully, and never had cause to repent.
The people with whom I lived, were those called Quakers.
As I had not been among any of that denomination before, I had a desire, in my mind,
to become acquainted with their principles and manner of worship.
Having liberty, I was ever ready to go to their meetings, though at first, only as a spy.
But after I had been some time among them,
and took notice of their way and manner of performing Divine worship to God,
I was ready to conclude, and say in my mind, surely these are his people.
A brave, living people, they really were; there being then many worthies among them, who,
I believe, are now in the fruition of "`Joy unspeakable,
and full of glory,`" the earnest of which they, through mercy, then at times partook of,
to the satisfaction of their hungry and thirsty souls.
The solid, weighty, and tender frame of spirit,
which some of them were many times favored with, in meetings,
brought serious considerations over my mind, with this query:
"`Why is it not so with me?`"--and I said in my heart:
"`These people are certainly better than I am;
notwithstanding I have made a great deal more to do about religion than they.`"

As I pondered on these things, that saying of the apostle,
"`Neither circumcision nor uncircumcision avails anything,
but a new creature in Christ Jesus,`" was often brought to my mind.
I saw this work must begin in the heart, and be carried on by a Divine power.
This I was soon convinced of, and therefore could wait with patience, though in silence.
But yet the whole work was not completed; it went on gradually, step by step,
which demonstrates the parental care of our Heavenly Father,
carrying the lambs in his arms, lest they should be weary and faint.
Who can but admire his goodness and celebrate his praise.
His wisdom and power are great.
Oh!--that all would but dwell under his peaceable government, and learn of Him,
who is pure and holy.
Through the operation of Divine Goodness,
great love was begotten in my heart to these people;
and if at any time Friends were concerned to speak against any evil habit of the mind,
I did not put it from me, but was willing to take my part,
and have sometimes thought it all belonged to me.

As I continued in this humble frame, and was diligent in attending meeting when I could,
Infinite Goodness was graciously pleased to favor me with
a fresh and large visitation of his heavenly love,
and often tendered my spirit, and begot strong desires after true and saving knowledge,
and that the way of life and salvation might be clearly demonstrated;
and blessed be his eternal name, He heard my cries, and was pleased to send his servants,
both male and female, filled with life and power,
who sounded forth the Gospel in Divine authority,
declaring the way to the Father through the door of Christ,
and opening the principles of these people,
by turning our minds inward to the pure gift and manifestation of the Spirit.

--

This doctrine agreeing with what she had been in some measure convinced of,
she was made willing to join heartily with it.
She passed through many exercises in the great work of regeneration.
One time, when sitting in a meeting, a call arose in her mind:
"`I have chosen you a vessel from your youth to serve me,
and to preach the Gospel of salvation to many people; and if you will be faithful,
I will be with you unto the end of time, and make you an heir of my kingdom.`"
Like many others,
she shrank exceedingly from entering on the office of a minister of the Gospel,
and thereby brought upon herself for a time much spiritual darkness and distress of mind.
She was favored at length with a renewed visitation of Divine mercy,
under which she was strengthened to submit to the Lord`'s requirings.
Yet after this she continued to have many temptations,
and suffered much from the buffetings of Satan.
At one time, when sitting alone in the woods, she says:

[.embedded-content-document]
--

[.offset]
A cry arose in my heart thus:

If I die it shall be at your footstool, O Lord!
For your lovingkindness has been great to me, from my youth to this day.
Then, falling on my knees,
I prayed that He would be graciously pleased to enlighten my understanding in
such a manner that I might clearly see wherein I had offended so merciful a Father;
for I thought I had offended Him, because I was permitted to be so tempted.
His word then became as a fire in my breast,
and the answer I received was to this effect: "`Be encouraged.
You are permitted to pass through these trying dispensations,
not only on your own account, but for the sake of others, to whom, when qualified,
I will, in my own time, send you.
Be faithful, and I will be with you to the end of time.`"

At this intimation I was tendered and filled with gratitude to his Divine Majesty,
who alone can deliver his children out of all their afflictions.
And my soul, at this time, under a sweet sense of his goodness,
bows with awful reverence and with praises to his holy name, and says,
Who is like unto our God?

There were many incidents occurred during the time of my being among these Friends,
to whom I was indebted for payment of my passage, which, for brevity`'s sake, I omit.
When the time for which I engaged to them was expired +++[+++autumn of 1715],
I served them a quarter of a year longer,
in consideration of the tender regard they had shown to me,
when it was in their power to have conducted otherwise--and also
for granting me the liberty of going to week-day meetings--which
additional service they accepted from me with reluctance.
We loved one another much; and being unwilling to part,
I stayed with them till the spring following +++[+++1716], and then,
in much love and tenderness, we parted.

--

When she had fulfilled her contract, she found a concern to move over Schuylkill,
which she did, and stayed some time at Haverford.
Her narrative continues:

[.embedded-content-document]
--

One First-day, after I had sat some time in Haverford Meeting, David Lloyd, from Chester,
with his wife and several other Friends, came into the meeting.
As soon as they were seated it was as though it had been spoken to me,
"`These are the people with whom you must go and settle.`"
They being strangers to me, and appearing as persons of distinction, I said in my heart,
Lord, how can such a one as I get acquaintance with people
who appear so much above the common rank?
The word was in my soul, "`Be still; I will make way for you in their hearts.
They shall seek you.`"
I knew not what to think of this, and was afraid it might be a temptation of Satan;
yet rested content in the thought that the Lord, who never yet had failed,
was all-sufficient to provide for me.
At that instant a great stillness came over me,
and I felt the love of my heavenly Father to affect me in a very uncommon manner.
I afterwards understood that David Lloyd and his wife fixed their eyes upon me,
feeling a near sympathy with me--such as they had never known toward a stranger before,
and said in their hearts: "`This young woman is, or will be, a preacher.`"
They were both tendered,
and it was fixed in their minds that they were to take me under their care,
and nurse me for the Lord`'s service,
with a promise that his blessing should attend them.
This I had from their own mouths, after I came to live with them.

After the meeting, I was passing away as usual, for fear of being taken notice of,
but was stopped by a Friend, who asked me to go home with her,
saying the Chester Friends were to dine there.
I excused myself as well as I could.
Then those Friends came to me, and spoke kindly,
which affected me in such a manner that they let me go,
but told some Friends there how they felt towards me,
and how it opened to them in the meeting.
They left their love to me, and said they intended to visit me soon,
with proposals for my living with them;
for according to what each of them felt in themselves,
they were to become instruments of good to me.

Soon after this, I became acquainted with Elizabeth Levis, a Friend, of Springfield.
The way and manner of which was thus: I had not appeared in public for a great while,
nor felt any motions that way.
I was very low in my mind, and having got into a dark state, had again almost lost hope,
and thought it impossible but that I should fall
a sacrifice to the temptations of the grand enemy,
who still followed me.
However, it happened that Elizabeth Levis came to visit Haverford Meeting,
where I then was.
After some time of silence, she stood up, and speaking in the authority of Truth,
so effectually laid open my present state,
that I could heartily subscribe to the truth of her testimony.
The power that attended her ministry reached the witness of God in my heart.
A zeal was begotten in me for the honor of the good cause,
and I was filled with love to the instrument through whom I had been thus favored.
Hope was again renewed in me, that, by virtue of the word preached,
the Lord would still continue his customary favors to me,
and preserve me from the snares of the wicked one.

After meeting, Elizabeth took kind notice of me, and said, "`I came here today,
through the cross--the Lord knows for what end!
It may be for your sake.`"
I was so overcome that I could not speak, but wept much,
and esteemed it as a blessing that she had taken notice of me.
I went home, rejoicing in spirit, because I had met with Divine refreshment,
of which I was in much need.

As it had pleased the Almighty to visit me in a wonderful manner,
by the renewing of his pure love, I made covenant,
that if He would be with me in the way I should go, He should be my God.

My mind was still engaged about Chester, with strong desires to be with Friends there,
but how to accomplish it I knew not.
Yet I knew the promises of God were yes, and amen; and in this I confided.
However, a good opportunity soon offered.
I was just finishing some work, which I had taken to do for a Friend; and on my saying:
"`When this is done, I know not where to get more,`" one, not of our Society,
being in company, said to me: "`Fear not; God will always provide for you,
because you fear his great name.`"
I made no reply.
But, in a few minutes, somebody knocked at the door.
I, being next to it, opened it, when I saw a man of a good appearance,
sitting on horseback.
He asked whether there was any young woman there that needed a place,
for he wanted a maid--one that was sober.
We desired him to alight, and inquired of him from where he came.
He and his family belonged to Chester Meeting, and he lived not far from the town.
It immediately occurred to my mind,
it may be this is a providential thing to bring me to that people.
I will give him expectation of my going with him next week, if he will come for me;
but concluded to hire only for a month, to see how I liked his wife, etc.
I communicated my mind to him.
He accepted the offer, and asked what wages I required.
I answered, as usual, what they thought I deserved.
So we parted.
His name was Benjamin Head, a worthy, honest man.
He called at a Friend`'s house just by, and told of his success,
and when he was to fetch me.
They told him I was a preacher, and they were unwilling to part with me.
But he had my word, and came according to our agreement.
I was prepared to attend his call, and so went with him.

I found his family consisted only of himself, his wife and daughter,
with one man and maid-servant.
His wife, being apprised of my character, received me with love and affection,
which lasted, not only while we lived together,
but to the conclusion of her time in this life.
Indeed, it would have been high ingratitude in me,
if I had not returned their kindness in the best manner I could,
for I had not been there three weeks before I was seized with a violent fever,
which reduced me so low that my life was despaired of.
They got the best advice that could be had--sparing neither cost nor labor,
in hopes of restoring my health.
Though the distemper was violent on my body, yet I was favored with quietude of mind,
and was entirely resigned to the Divine will, whether to live or die.

It is a great blessing that attends those who fear God,
that his Holy Spirit accompanies their souls when upon a bed of languishing.
The Psalmist experienced this in his day; and so will all the righteous now,
as well as then.

This illness held me near three months,
in all which time this Friend Head and her daughter, a sober young woman, attended me,
night and day, very carefully.
Several of Chester Friends and others also visited me, and offered their services,
in ministering things suitable for my disorder, as well as otherwise,
so that I lacked nothing that was proper for me.
Some friends were for removing me; but that was impossible.
Besides, the Friend with whom I was, declared against any such motion,
and I was opposed to it myself, under this consideration,
that if it pleased Providence to raise me, it would be my duty to stay,
and make such retaliation as might be in my power.

Thus, the time was prolonged six or seven months, instead of one.
So that we, poor, short-sighted mortals, may propose many things to ourselves,
but Providence can disappoint; and all for our good, if we patiently submit, and indeed,
it is our interest, as well as duty, so to do.
Grace Lloyd, perceiving that Friend Head was unwilling to part with me,
forbore speaking anything of her mind to me, until after I had got out to meeting;
which I did as soon as I was able.

My first going to meeting was on a First-day.
The meeting was large, by reason that John Danson, a Friend from Great Britain, was there.
+++[+++Twelfth Month, 1718.]
I sat about the middle of the house, under much exercise of spirit,
insomuch that the Friend was sensible of it, though at that distance.
And although I did not appear in testimony, yet I was not hidden.
I don`'t remember anything remarkable that attended the meeting.
John Danson was silent; and as soon as it broke up, he spoke to David Lloyd, saying:
"`Stop that young woman who sat in such a place.
I have something to say to her from the Lord.`"
He spoke so loud that I heard him, and trembling, was going away.
But Grace Lloyd desired me to stay, and kindly told me I must go home with her.
I excused myself, but it did not avail.
She would not be denied--I must go.
I therefore asked leave of Friend Head, which she readily gave me,
and left a horse for me to ride home.

When we came to David Lloyd`'s, there was a great company of Friends;
but not thinking myself worthy, I would not thrust in among them,
intending to go among the servants.
But this was not permitted, for, as I was entering the parlor,
I heard the English Friend say: "`Where is the young woman--I want her company.`"
I came in, and was seated next to him.
He took hold of my hand, fixed his eyes upon me, and after a little silence,
spoke to me in such a manner, by way of encouragement,
as I have not freedom here to relate.
Only so much I may say, he proved a true prophet to me, as I afterwards experienced,
respecting the work the Lord was preparing me for, and about to employ me in.
But I, like Nicodemus, was ready to say: How can this be?
Will the Almighty engage such a poor, unworthy creature in so great a work of his?
He knows I am in no way sufficient for the task.
But the Divine word was:
"`Trust in my all-sufficient power--that shall properly qualify you for every service.
What I require of you is, to be faithful,
and you shall see greater things than have yet been made manifest.`"

I felt Infinite Goodness near.
My soul bowed in awful reverence to the Divine Majesty of heaven and earth,
and in the secret of my heart I said: "`Lord,
I will submit to every dispensation which you allot.`"
The Friends present were mightily broken,
and were made partakers together of the virtue of light and life,
which caused gladness of heart, so that little food satisfied some of us.

After dinner, the Friend spoke to David Lloyd and his wife, saying:
"`Take this young woman; make her your adopted child,
and give her liberty to go wherever Truth leads.`"
They told him that was their intention, and when I was free to come,
their house should be my home for the future.
He replied: "`Do as you say, and the blessing of God will attend you on her behalf.`"
Grace Lloyd then took me into another apartment,
and told me how she and her husband were drawn in love to me, the first time they saw me,
at Haverford (as has been related), and if I would come and live with them,
they intended to do well for me.

I admired at the ordering of Providence, in thus providing for me, a poor,
destitute orphan, separated from all my natural friends, in a strange land,
and having no certain habitation here, in mutability.
Oh, that all would fear and serve the living God, whose goodness endures forever!
It was his own work, and He shall have the praise.
We parted, in tears, under the holy influence of Divine love, and I,
with a sense of his wonderful kindness to me, went home, rejoicing in spirit,
and praising the Almighty.

I entered into David Lloyd`'s family as an upper servant,
such as in England are called housekeepers, having the keys, plate, linen, etc.,
delivered unto me.
They had a great family, and everything passed through my hands.
As they had reposed such a trust in me,
it brought a weighty concern on my mind that I might
conduct aright and discharge my duty faithfully,
both to my principles and their servants; and, being sensible of my own weakness,
I many times, when others were asleep, poured out my prayers to God,
and asked wisdom of Him who gives liberally and upbraids not.

I was often afraid, lest,
through my misconduct I should bring dishonor to the pure Truth I made profession of;
for I now began to speak frequently in meetings, and many eyes were upon me.
I was become like a city on a hill, which could not be hidden.
Christ, our Lord, speaking of this situation, says:
"`Let your light so shine before men that they may see your good works,
and glorify your Father who is in heaven.`"
This text was often revived in my memory,
and under this dispensation I was led through a painful, anxious travail of soul.
I considered I had been tried in low circumstances, though I never lacked necessaries,
but was always provided for.
And having met with kind treatment from all sorts of people,
I was blessed with contentment in the station allotted me.
Now I was to be proved with greater plenty and favored
with the company of valuable Friends,
who often frequented our house, and though I was but in the station of a servant,
yet I was much noticed by them,
for when they came I was always allowed to be in the room with them.
This was a great obligation conferred on me--but it did not elevate
my mind--it made me more humble and assiduous in my business.
Another favor conferred on me was that I always dined with master and mistress,
which was of advantage, for many times their conversation was profitable.

Thus, as I kept my eye steady to the Almighty, He gave me favor among Friends,
and with both my said benefactors.
They were kind and affectionate, like tender parents, watching over me for good;
often telling me to mind the dictates of Truth,
and if at any time I found a concern to visit any meetings, to be sure to go;
and they were very careful to provide suitably for me in every respect.
This was engaging, and my love to them increased daily.
I judged it my duty to make their interest my own, as if I was their child;
and can in truth say I never willfully disobliged either of them, nor left their service,
to serve myself, in any shape.
I went nowhere without their leave, not so much as to buy some trifles I wanted.
And when a religious concern came over my mind to visit the churches of Christ,
they were the first I made acquainted therewith.

--

There is to the writer something very instructive and touching
in the manner in which the Lord cared for his servant,
and brought her into such a position outwardly that she was able
to perform the different services He required of her.
And I do not doubt that her kind friends, David and Grace Lloyd,
felt the reward of peace for their care over her.

She travelled much as a minister, having gone on one occasion to Bermuda; on another,
to Great Britain, besides several journeys in America.

George Whitehead, who was an eminent minister among our early Friends,
was brought up among the Episcopalians.
The Lord was graciously pleased to visit him in early life
and to awaken desires after a true amendment of life.
While still young in years, he heard of a people called Quakers,
who trembled at the word of God,
and observing how they were reviled and reproached by loose and wicked people,
occasioned his further inquiry.

About this period,
in attending one of the meetings of the newly-risen Society of the Quakers,
he was much affected by perceiving how greatly the spirits of most
of those who were there assembled seemed broken and contrited,
more especially in the case of a young woman, who, on quitting the meeting,
he observed to sit down upon the ground, "`With her face towards the earth,
as if,`" he says, "`she regarded nobody present, but, moaning bitterly, cried out,
'`Lord, make me clean!
O Lord, make me clean!`'--which,`" he adds,
"`did far more tenderly and deeply affect my heart than what I had heard spoken,
and more than all the preaching that ever I had heard from man or men,
and was a certain testimony to me (the spirit of the Lord evidencing to my spirit),
that it was a real work of his power upon her heart,
which also operated upon the hearts of others, causing both trembling,
sorrow and contrition, in order to bring them to true repentance and amendment of life.`"

[.embedded-content-document]
--

Some time after I was fully convinced, +++[+++says he,]
and my mind turned to the light,
and I was persuaded and resolved to persevere among Friends,
before I heard our dear Friend, George Fox.
The first time I heard him minister was at an evening meeting at Sunny Bank.
I was then very low, serious and intent in my mind, willing to see and taste for myself,
for my own inward satisfaction;
and I saw and felt that his testimony was weighty and deep;
and that it proceeded from life and experience, and did bespeak Divine revelation,
and tended to bring to an inward feeling and sense of the life and power of Christ,
and the sanctifying operation thereof in the heart.
His speech was not with affected eloquence or oratory, or human wisdom,
but in the simplicity of the Gospel, to turn the mind to the light and life of Christ;
and the Lord abundantly blessed his ministry to many.

As to the progress which by Divine assistance I came to
experience in the work of the Lord Jesus Christ in me,
after I came to be resolved and settled in my mind and conscience,
to join in communion with the said people, and to frequent their assemblies as aforesaid,
the Lord by his light and grace of his Holy Spirit, having fully persuaded me,
that without being converted as well as convinced, and without being regenerated,
sanctified, and born again, I could not enter into his kingdom, nor be an heir thereof,
and that the godly sorrow unto true repentance, and a real amendment of life,
must be wrought by his grace and good spirit in me; and,
that without holiness none can see God.

Upon these and such serious Christian considerations,
I was persuaded by the grace of God to give up in obedience to follow Christ Jesus;
to believe in and obey his light given me, and to wait therein diligently,
to receive power from Him to become a true child of God;
for as many as truly receive Christ the Son of God,
He gives them power to become sons of God.

--

[.offset]
Samuel Bownas was born in Westmoreland about the year 1676--

[.embedded-content-document]
--

Persecution being still hot,
many Friends were in prison at Appleby for attending that meeting,
whom my dear mother went to visit, taking me along with her,
and we had a meeting with the prisoners,
several Friends from other places being likewise there by appointment.
I observed, though very young, how tender and broken they were;
and I was very inquisitive of my mother, why they cried so much, and you too, said I,
why did you?
She told me that I could not understand the reason of it then,
but when I grew up more to man`'s state I might.

To return to my apprenticeship: I had a very kind loving master and mistress,
but had little consideration about religion, nor any taste thereof.
On First-days I frequented meetings, and the greater part of my time I slept,
but took no account of preaching, nor received any other benefit, than that being there,
kept me out of bad company, which indeed is a very great service to youth.
I took much liberty in discourse, and was taken notice of, as a witty,
sensible young man: but often on my bed, I reflected on my way of life with sorrow,
yet frequently fell into the same way again.
I never was given to swearing, nor to any very gross vice, but what I gave way to most,
was jesting, and turns of wit to provoke mirth, which gave me often after it was over,
a heavy heart.

Thus I went on for nearly three years; but one First-day, being at meeting,
a young woman, named Anne Wilson, was there and preached.
She was very zealous, and I fixed my eye upon her; she, with a great zeal,
pointed her finger at me, uttering these words with much power: "`A traditional Quaker,
you come to meeting as you went from it the last time, and go from it as you came to it,
but are no better for your coming; what will you do in the end?`"
This was so suited to my condition, that, like Saul, I was smitten to the ground,
but turning my thoughts inward, in secret I cried, Lord, what shall I do to help it?
And a voice as it were, spoke in my heart, saying, Look unto me, and I will help you;
and I found much comfort, which made me shed abundance of tears.
Then I remembered what my mother told me some years before,
that when I grew up more to man`'s state,
I should know the reason of that tenderness and weeping, which I now did to purpose.

I went home with a heavy heart, and could neither eat nor sleep, as I used to do,
but my work never succeeded better in my hands than it did at this time,
nor was my mind ever less in it.
My conduct, as well as countenance, was much altered,
so that several in the family were fearful that I should fall into a kind of melancholy;
but I longed for the meeting day, and thought it a very long week.
When the time of meeting came, my mind was soon fixed and stayed upon God,
and I found an uncommon enjoyment that gave me great satisfaction,
my understanding being opened, and all the faculties of my mind so quick,
that I seemed another man.
Divine and spiritual sweetness abiding with me night and day, for some time,
I began to see and understand the Scriptures,
and the nature of preaching the doctrine of the Gospel in the power and spirit,
plainly seeing a difference between a preacher of the letter and of the spirit, which,
till then, I was wholly ignorant of, not having before that,
the least degree that I could perceive of Divine understanding.
But upon looking back and considering what I had heard such and such Friends preach,
which, at that time I did not understand, I now understood it clearly,
which was a plain demonstration to me, that all saving knowledge is from Divine light,
which we cannot comprehend, until we are assisted so to do by a visitation from heaven.

--

[.offset]
Thomas Thompson says:

[.embedded-content-document]
--

It came to pass about the Sixth or Seventh Month, of the year 1652,
we heard of a people raised up at or about Malton, who were called Quakers,
which was the first time I heard of that name being given to any people.
They were by most persons spoken against,
but when I strictly inquired what they had to lay to their charge,
that might give cause for such aspersions as were thrown out upon them,
I met with none that could justly accuse them of any crime.
They said they were fantastical and conceited, and burnt their lace and ribbons,
and other superfluous things, which they used formerly to wear,
and that they fell into strange fits of quaking and trembling.
But these reports increased my desire to see, and be acquainted with some of them;
and in the Eighth Month, of the aforesaid year,
I heard that the Quakers were come to Bridlington,
whereat I greatly rejoiced in my spirit,
hoping I should get some opportunity to see them.
This was that faithful laborer and minister of the Gospel, William Dewsbury,
who then was ordered into these parts; and on Fifth-day following,
I heard they were come to Frodingham.
Being on my master`'s work at Brigham, I could not go in the day,
but determined to go in the night,
and would gladly have some of my acquaintance to go with me;
but the night being very dark, none would go, so I went alone.

Coming into the room where William was, I found him writing,
and the rest of his company sitting in silence, seeming to be much retired in mind,
and fixed towards God.
Their countenances being grave and solid, preached unto me,
and confirmed what I had before believed, that they were the people of the Lord.
After a little while, William ceased writing, and many of the town`'s people coming in,
he began, in the power and wisdom of God, to declare the Truth.
And oh!--how was my soul refreshed, and the witness of God reached in my heart!
I cannot express it with pen.
I had never heard nor felt the like before;
for he spoke as one having authority and not as the scribes;
so that if all the world had said, "`no,`" I could have given my testimony,
that it was the everlasting truth of God.

--

Thomas Wight, of the city of Cork, was born in the year 1640.
His father, Rice Wight, was minister of the town of Bandon,
a zealous man in the duties of his office, and of a more tender conscience,
and devoted in that respect, than the generality of the priests,
and very strict in the education of his children,
according to the manner of the church of England.
His son, Thomas, served a hard apprenticeship with a clothier in Bandon,
and while in his service, hearing of a Quakers`' meeting to be held in the neighborhood,
he went to it out of curiosity.
Finding that Friends sat silent for a long time, he grew very uneasy, and began to think,
that as he heard the Quakers were witches,
he might become bewitched if he should stay much longer in the meeting.
However, he waited a short time, until Francis Howgill,
then on a religious visit in these parts, stood up, and uttered these words:
"`Before the eye can see, it must be opened; before the ear can hear,
it must be unstopped; and before the heart can understand, it must be illuminated.`"
As Francis opened these three sentences to the congregation, with great clearness,
and energy, his ministry made a deep impression on Thomas`'s mind,
and he was in great measure convinced of the truth of the doctrine
preached by this distinguished servant of the Lord Jesus.
But the prejudices of education,
and the reproach cast upon him by his relations for going to the Quakers,
very much wore off the impressions received at that meeting.
Some time after Edward Burrough came into these parts,
to visit Friends and others in the work of the Gospel,
under whose powerful preaching the state of his soul was so effectually reached,
accompanied with such evidence of Truth, that he, as well as many others,
was no longer able to withstand it, and he now resolved, through Divine assistance,
to be faithful, according to the light received,
through the difficulties that might attend him.

Samuel Crisp, who was a clergyman in the church of England about the year 1700,
was under conviction for his transgressions,
and earnestly seeking for reconciliation with God.
He felt that he must leave the church of England,
but knew not what body of men he should join.
He was altogether unacquainted with Friends,
except that he knew the Quakers were everywhere spoken against,
so that he wondered "`with what face they could call themselves Christians.`"
Being in London, he says:

[.embedded-content-document]
--

As I had occasion to be one day at a bookseller`'s shop,
I happened to cast my eye on Barclay`'s works, and,
having heard that he was a man of great account among the Quakers,
I had a mind to see what their principles were,
and what defence they could make for themselves.
For sure, thought I, these people are not so silly and ridiculous,
nor maintainers of such horrid opinions, as the author of __The Snake__^
footnote:[This book, [.book-title]#The Snake in the Grace#,
was published anonymously in the year 1696 by a man who was employed by
the clergy to render Friends and their principles odious to the world.
His misrepresentations were disproved,
and his crafty imposture manifested by Joseph Wyeth and George Whitehead in a book,
entitled, [.book-title]#A Switch for the Snake#.]
and some others would make us believe.
I took Barclay home with me, and I read him through in a week`'s time,
save a little treatise at the end, which, finding to be very philosophical, I omitted.
But, however, I soon read enough to convince me of my own blindness and ignorance,
in the things of God.
There I found a light to break in upon my mind,
which did mightily refresh and comfort me in that poor,
low and humbled state in which I then was.
For, indeed, I was then, and had been, for a considerable time before,
very hungry and thirsty after righteousness, and, therefore,
I received the Truth with all readiness of mind.
It was like balm to my soul, and as showers of rain to the thirsty earth,
which is parched with heat and drought.

This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the Scriptures so clearly to me, that, without standing to cavil, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God;
and weeping for joy that I had found so great a treasure, I often thanked Him,
with tears in my eyes, for so kind a visitation of his love,
that He was graciously pleased to look towards me, when my soul cried after Him.
So, though before I was in great doubt and trouble of mind,
not knowing which way to determine myself,
yet now the sun breaking out so powerfully upon me, the clouds were scattered.
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.
So I left the communion of the church of England, and went to Grace-church Street meeting.

--

David Ferris was a native of Connecticut, and brought up as a Presbyterian.
He was early in life favored with religious convictions;
but through unwatchfulness and unfaithfulness,
fell into a state of great mental distress.
He says:

[.embedded-content-document]
--

On a certain day, in this season of despair and deep distress,
I concluded to leave my native land, and go into some foreign country,
to spend the residue of my days; where I purposed to remain unknown,
and that none of my relations or acquaintances should know what was become of me.
Being, in my own apprehension, a poor, lost, reprobate creature,
I was not willing to remain at home, to be a disgrace to my relations and country people.
This was a day of the deepest affliction and distress that I had known.
Towards evening, as I followed the plough, my attention was arrested, as it were,
by a still, small voice, saying: "`The blood of Jesus Christ, his Son,
cleanses from all sin.`"
But I put it by, saying in my heart: "`It is too late;
there has been a day wherein I might have been cleansed; but alas!
I have let it pass over my head forever.`"

Some time after this (perhaps half an hour),
while I was musing on what land I should flee to,
the same words passed through my mind again, with more authority than before,
and commanded my attention rather more closely than they had done;
but I again put them by, concluding I had lost all right to apply them to myself.
So I resumed the consideration of my flight for a foreign land.
In the meantime my sorrow and anxiety of mind increased,
so that I was not well able to support it, or go on with my business.
But while I was still musing, the same words, unsought for and unexpectedly,
passed through my mind with greater power and authority than any time before:
"`The blood of Jesus Christ, his Son, cleanses us from all sin.`"
At the sound of them my soul leaped for joy.
I felt that a door of hope was opened, and said in my heart: "`If all sin, why not mine?`"
Then a living hope sprang in my soul.
I saw the arms of mercy open to receive me,
and the way cleared before me as a road through a thicket.
I was now filled with joy unspeakable;
thanksgiving and living praise to my Redeemer arose in my heart
for the experience of so great and marvellous a deliverance.
That my feet should be plucked out of the mire, and set upon a rock; that I,
who had no hope just before,
should now be favored with a well-grounded assurance of pardon and acceptance,
was a mercy never to be forgotten.

From this time I sought for Divine assistance, and in infinite kindness,
a hand of help was extended for my restoration and the healing of my backslidings.
Then I was enabled to sing upon the banks of deliverance,
and praise the name of Him who lives forever.
The Holy Spirit, that blessed teacher, whom I had formerly been favored with,
but had forsaken, was now restored, as a leader and teacher,
to direct and instruct me in the way to peace and rest.
From this time, my mind, after such great favor,
was humbled and made subject to the cross of Christ,
and heartily willing to take it up daily, and follow Him, my kind leader,
in the narrow way of self-denial.
And as I was obedient, He led me to forsake my vain course of life,
and all those youthful delights and sensual pleasures
which were displeasing to my dear Lord and Master,
who, in wonderful mercy, had lifted me out of the dungeon,
and heard my prayers in a time of deep affliction.
He now became my director in all things, showing me clearly what my duties were,
and enabling me to perform them in an acceptable manner.

As I waited upon the Lord for instruction, my understanding was gradually enlightened,
so as to perceive many errors in my former creed,
and to discover the Truth in opposition to the doctrines of my education.
That which stood most in my way, and appeared to be a grievous hardship to mankind,
as well as a great dishonor to a just and righteous God,
was their doctrine of unconditional election and reprobation, which would,
according to their apprehension of it,
shut out the chief part of mankind from all hope of mercy,
as they believed they were the Lord`'s only people,
and that but few of others were within the pale of election.
Yet I believe there were some among them who had a more extensive charity.
I was much concerned on this subject, and being earnestly desirous to discover the Truth,
it pleased the Lord to open my understanding,
clearly to perceive the error of this doctrine; and I was enabled to believe that Christ,
who "`gave himself a ransom for all,`" would "`have all men to be saved,
and come to a knowledge of the Truth.`"

I had before this period heard of a people called Quakers,
but was unacquainted with any of them.
As I had never seen any of their writings I knew not what doctrines they held,
but ascribe all my knowledge in Divine things to
the inward manifestation of grace and truth,
the teaching of the Holy Spirit.
It was Christ, the light of the world, the life of men, who opened to me the Scriptures,
and gave me a discerning of their meaning;
and as I was faithful and obedient to the pointings of Truth,
I was favored with further and clearer discoveries thereof.

I continued at the college until near the time for taking my degrees,
and being convinced of the errors of my education relating
to the doctrines we held and the worship we performed,
I apprehended it was time to consider what was best for me to do;
and being favored to see that a qualification or commission
derived from man was not sufficient for the Gospel ministry,
I concluded not to take their degrees nor depend upon their authority.

--

About three weeks after leaving college, he says:

[.embedded-content-document]
--

I went to a Yearly Meeting of the people called Quakers, on Long Island,
in order to discover whether they were a living people or not,
for a living people I wished to find.
I had thought for several years before that there ought to be such a people,
a people who had life in them, and abounded in love to each other,
as did the primitive Christians; a people who knew they had passed from death unto life,
by their love to the brethren.

Here I gathered strength, and was more confirmed that I was right in leaving the college;
for I found a living, humble people, full of love and good works,
such a one as I had never seen before.
I rejoiced to find that which I had been seeking,
and soon owned them to be of the Lord`'s people, and of the true church of Christ,
according to his own description of it when he says:
"`By this shall all men know that you are my disciples, if you love one another.`"

At the meeting before mentioned, there were several eminent ministers from Europe,
both male and female.
I there heard women preach the Gospel, in the Divine authority of Truth,
far exceeding all the learned rabbis I had known.
This was not so strange to me as it might have been to others, for I had seen before,
by the direct manifestation of grace and truth,
that women as well as men might be clothed with Gospel power;
and that daughters as well as sons, under the Gospel dispensation,
were to have the Spirit poured upon them that they might prophesy;
and though I had never before heard a woman preach,
yet I now rejoiced to see the prophecy fulfilled.

--

David Ferris now felt that he must separate himself
from the people among whom he had been educated,
and he embraced the views which distinguished the Society of Friends.
He met with many close trials of his faith and patience.
For a time his father was much displeased at the change
which was manifest in his conduct and deportment;
but becoming convinced of his son`'s sincerity, he was at length reconciled to him.

The reader may have noticed in the preceding accounts that there
was some variety in the mode in which the Lord dealt with his children
in bringing them into submission to his holy will.
In some cases, the Divine visitation seemed to come suddenly,
and with overpowering force;
in others there was a more gradual unfolding of the Divine will,
and a submission was felt--one thing was opened to the understanding after another.
But in every case it was needful that the Lord`'s will should be obeyed,
as without this there could be no growth in grace, or any establishment on Christ Jesus,
the Rock on which the church is founded.

It is related of Edward Andrews,
a person who became an eminent instrument in the
hand of God in gathering many to the fold of rest,
that what seemed to be the turning point in his life was a comparatively simple incident,
from which one would scarcely have expected such important results to follow.
The account given of him says:

[.embedded-content-document]
--

His residence was at that time in the Jerseys, near the seashore,
among a wild sort of people, Indians and others, vain and loose in their conduct,
fond of frolicking, music and dancing; among these he acted the part of a fiddler.
In this situation, as he was one day working in his field,
he came across a part of a human body, which he had seen before, which, as he now saw it,
lying on the ground, a thought struck him,
that it was not right to allow a part of his fellow creature
to be thus thrown up and down in the open field;
but that he ought to do with it as he would desire to be done by in the like condition;
after some reasoning of this sort, he decently buried it and returned to his work again,
with an answer of peace in his mind.

From that time he grew pensive.
The pure witness of Truth rose in him,
by which he was made sensible he had spent many years in vanity,
that it was high time for him to turn unto the Lord,
and a desire was begot in him to experience an inward acquaintance
with God and be favored with power from Him,
to forsake his vanity and loose living, the iniquity of which was then opened to him;
and he found a call in his mind to destroy that fiddle,
which had been so much an instrument to lead himself and others,
to the misspending their precious time; this he concluded to do, when he went home;
but delaying to perform this resolution,
as he lay in his bed he felt the fire of God`'s wrath kindled on account of his disobedience,
which induced him, the next day, to break the fiddle in pieces, which, when done,
his heart rejoiced, and he felt a strength of hope rising in him,
that God would give him farther power over all his vanities.
A sense was also given him,
that if he was faithful to what the Lord would require of him,
he should be made an instrument in God`'s hand, to gather a people to his praise,
from those very loose people among whom he resided; which seemed strange to him.
But as his heart became daily more and more exercised towards God,
and in giving him thanks for his mercies, a lively concern and desire came upon him,
that sinners might be brought, as he had been, to a sight of the error of their ways.
He then found it to be his duty to speak to those same people,
whom he had led on in folly and vanity, and to direct them to the service of God.

This he at first found to be hard work;
but being charged by the Spirit to be faithful to what was required of him;
and made sensible that if he was so, God would be with him, but that if he refused,
he should be left to himself, and fall into a worse condition than he was in before,
he was enabled to speak to them, though in great fear,
and the Lord caused his admonition to be well received by his neighbors.
And on the next day of worship, instead of spending their time in rioting and excess,
as they were used to do, some of them sat with him to read the Scriptures,
and confer together upon the things which related to eternity,
in which his understanding was opened to see that
the right worship of God was to be performed in silence,
unless when moved by the Spirit to appear in vocal service,
under which prospect he found himself moved to kneel down and pray; and sometime after,
to exhort his companions, which was accompanied with so much energy and power,
that the people were much affected.

--

[.offset]
Stephen Crisp says of the early visitation of Divine Grace to his soul:

[.embedded-content-document]
--

As early as I can remember,
the Lord made me to understand that which consented not to any evil,
but stood in my soul as a witness against all evil; and manifested that I should not lie,
nor steal, or be stubborn or disobedient,
but should behave myself in meekness and quietness, and set Truth before me,
as that which was better than falsehood.
This witness ministered peace and boldness to me in my childhood,
when I hearkened to the counsel of it.
But there was a contrary nature and seed in me that was of this evil world,
as most of all suiting the carnal mind,
and an eye began to open in me that saw what was acceptable with man,
rather than what was well pleasing to God.

About seven or eight years old, when judgment overtook me for evil,
I would yield that it was so,
and therefore thought that I must do something to please God again;
and hereupon I learned to pray, and to weep in secret,
and to covenant with God for more watchfulness, and I thought for a season,
I was unburdened from my weight.
Yet this best state was accompanied with many questionings,
whether my evils were blotted out, especially when I was again led into evil thoughts,
words or actions.
For the +++[+++Divine]
witness cried even then, to have my whole mind given up to the Lord;
that I should serve him, but I knew not that it was from God.
I knew that I lacked power to answer the requirings
of that in me which witnesses against evil,
and this I lamented day and night.
When I was about ten years old, I sought the power of God with great earnestness,
with strong cries and tears; and if I had had the whole world, I would have given it,
to have known how to obtain power over my corruptions.

--

The autobiography of Richard Davies shows the gradual manner in which it sometimes
pleases the Lord to unfold the mysteries of his kingdom to his children.
When he was an apprentice to a man named Evan Jones,
"`A poor man in lowly habit,`" a Quaker,
called at the house and fell into conversation on religious subjects with his master.
Evan`'s wife, finding him unable for the task he had undertaken,
slipped into the shop where Richard Davies was at work, and addressing him, said:
"`Why do you not go out to help your master?--there
is a Quaker at the door that has put him to silence.`"
Richard seizing hold of his Bible,
hastened to the door as a dutiful servant to help his master in a tight place.
The subject under consideration when Richard reached the scene of action,
was the use of the singular number to a single person.
Richard took up the debate,
and although admitting that the Almighty used the singular number in speaking to Adam,
and that it was also the language of Scripture, he declared that was not enough,
for we must have a command for it;
and turning to the poor man in a very peremptory manner,
he demanded what command he had to speak "`Thee`" and "`Thou.`"
The poor man promptly answered in the language of Scripture,
"`Hold fast the form of sound words, which you have heard of me.`"
The Friend`'s readiness in quoting Scripture,
and his willingness to read in the Bible at Richard`'s request,
was a convincing proof that the report that the Quakers denied the Scriptures,
and would not read them, was false.

Richard found that he was not a match for the poor man,
and the poor man saw that what he had said, had reached the witness for God in the youth.
He quit disputing, and exhorted Richard to take heed to the light,
that shining in his heart, did make manifest his vain thoughts,
and reprove him in secret for every idle word and action.
He told him that this light "`was the true light which gives light to every man
that comes into the world,`" and that in that light he would see more light,
and that would open the Scriptures to him,
and that he would receive a measure of the Spirit that gave them forth.
It was "`the more sure word of prophecy, unto which he did well if he took heed,
as unto a light that shines in a dark place, until the day dawn,
and the day-star arise in your hearts.`"
He spoke also of the inward work, and the operation of God`'s Holy Spirit upon the soul;
recommending to the "`Grace of God, that brings salvation, teaching us,
that denying ungodliness and worldly lusts, we should live soberly,
righteously and godly in this present world.`"

Richard adds: "`And so he departed from our house,
and I set him a little along on his way.
Now when I came back from him, the consideration of his words took fast hold on me,
that I could not go from under them;
and the more I waited in that light that he recommended me to, the more my former peace,
and that in which I formerly took comfort, was broken; and herein I came to see,
that our former building could not stand,
for we built upon that which the apostle called '`wood, hay,
and stubble.`' Here I came to a loss of all my former knowledge;
and my former performances proved but a sandy foundation.
Then I did, with much humility and poverty of spirit, beg of Almighty God,
that I might build upon that Rock, that the true church of Christ was built upon,
that the gates of hell might not prevail against me.`"

Richard was now in the school of Christ,
and although he had many spiritual trials and difficulties to encounter,
he grew in grace and knowledge,
and in his silent waitings upon God was often much broken and tendered.
He was afraid of being deceived;
and having read that Satan was "`transformed into an angel
of light,`" he desired to be watchful and circumspect.
He wished for a little more outward information,
and he desired of the Lord that he might see the poor man once again.
He says that "`It pleased God that he came again that way,
and I desired of my master and mistress to give him lodging,
and that he might be with me, to which they consented.`"
Richard then queried of him about the Quakers`' way of worship, and the ordinances,
so called, of bread and wine, and baptism, and their judgment of the Scriptures.
He received satisfaction on these points,
and in the morning the poor man again passed on his way.

Gradually the various doctrines held by the Society of Friends,
and the peculiarities into which they had been led, were unfolded to Richard Davies,
and he was brought into conformity thereto.
His mistress now began to show much hard feeling towards him,
and at one time under the temptation of Satan, she was determined to take his life.
Richard felt himself freely given up to die, but the Lord checked her wicked feelings,
and she was afterwards more moderate towards him.
In her last sickness the remembrance of her harsh
conduct to him came so heavily upon her,
that she told her husband "`She thought she should
not die until she had asked Richard to forgive her.`"
He freely gave the forgiveness she craved, and she ended her days in peace.

The simple account which our late honored Friend, Christopher Healy,
gave of his own early experience,
furnishes an interesting description of the manner in which
Divine grace operated on his mind in quite early life.
It is as follows:

[.embedded-content-document]
--

I very well remember, though I was then quite a child,
the day my father brought [.book-title]#Sewell`'s History# home with him.
If I was but a little fellow, yet I was quite a good reader,
and my father set me to read the book to him, while he sat upon his bench making shoes,
for he was by trade a shoemaker.
I recollect distinctly, as though it was but yesterday,
how much I was affected in reading some parts of that book,
especially where it told of the constancy which so many of those poor people,
both young and old, showed under suffering and cruel persecution.
I often had to stop reading, for I could not go on for weeping, and my sister Hannah,
who was older than I,
would take the book and read till I was composed enough to go on again.
My childish sympathies were indeed very much stirred up on account of these poor,
innocent sufferers of whom we read;
and I thought that if there ever were any really good people in the world,
these surely were some of them.
And I said in my heart, if the Lord should ever make me a Quaker,
like He did the people of whom we read,
and give me his testimonies to bear for the Truth,
that I also would be willing to suffer for his sake,
and that I would rather lay down my life and die for Him,
than draw back and give up my religion because of persecution.
And I now gratefully remember that the Lord did, in his own appointed time,
visit my soul, and reveal his dear Son in me;
and as I was made willing to bear his yoke and become obedient
to the word of Life that He gave me from season to season,
as I was able to bear them, one after another of his precious doctrines to believe,
and more and more of his noble testimonies to uphold and declare before the people,
for his great name`'s sake.

And now I feel bound in gratitude to say,
that He has graciously enabled me to continue faithful to Him, my good Lord and Master,
for nearly sixty years.
It will be sixty years this coming summer since I first attended a Friends`' meeting.
My brother John and I thought we would like to go to a Quaker meeting,
and as the nearest one to us, we heard, was at Hopkinton, Rhode Island,
we concluded one First-day morning that we would go to it.
I was not then quite fifteen years old.

So, after our very long walk, we went into the meeting;
and when I saw Friends sitting around me in solemn silence, I was much struck with it,
and with the very great difference there was between what I now saw,
and all that I had ever before seen in religious meetings.
In every meeting that I previously had been at, there had been no silence,
no waiting on the Lord,
and no preparation for the solemn duty of worshipping Almighty God,
but they went right away to singing, or praying, or preaching; and when they were done,
they hurried off without ceremony and without taking any time for solemn reflection,
that they might profit by what they had heard.
But here all was changed.
And when I looked over the meeting, and saw many people sitting quietly around me,
I asked myself this question;
"`What are these people doing?`"--for they have not yet heard preaching,
or any good advice for them to be thinking about.
And I said: "`Can this be worship?
Are these people really worshipping their Heavenly Father?`"
I looked very attentively at the Friends in the gallery,
and when I saw the solid gravity with which they sat,
and especially after I had observed that tears were trickling down some of their cheeks,
although there had not been a word spoken, I said in my heart:
"`Surely these people have something in them which I know nothing about.`"
And I felt an earnest desire in my heart to know what that something was,
and where they got it from, and how it was to be obtained; that, if it were possible,
I might get some too,
and come to know what it was that made the tears run down their faces,
without any of the common means having been employed to produce such effects.

Thus the Lord began to open my spiritual eyes,
by first kindling holy desires in my heart to know and understand the mysteries of godliness.
And blessed be his holy name, He not only raised these desires in my heart,
but by the inshining of his Holy Spirit,
He gave me an understanding of one mystery after another, as I was able to receive it,
until I was brought,
through Divine grace and by the revelation of his light and love and power in my soul,
to set my seal to all the doctrines and testimonies which He raised up
Friends in the beginning to uphold before the nations of the earth.
No doubt the reading of [.book-title]#Sewell`'s History# and other now forgotten incidents, prepared,
in a measure, my heart for the reception of their truth,
but on this day I was first made sensible of a true convincement,
and saw the dawn of the true Gospel day arise in my soul.
And thus those principles and doctrines of life and salvation
began to be recognized by me--and blessed be my Stay and
Holy Helper who has preserved me from departing from them,
from that day to the present time.

After meeting, Friends showed great kindness to us poor lads,
and we had many invitations to dinner.
We went home with one which would not take us out of our way,
and this Friend was indeed truly kind to us.
He told us that he would be glad to see us at meeting
when we should feel inclined to come,
and pressed us to make his house our home when we did come.
His truly friendly conduct to us made a deep and lasting impression on my mind.

--

When Christopher Healy was between thirteen and fourteen years of age,
he attended a school in New England, taught by a Presbyterian master,
who heard them every Seventh-day morning say their catechism.
This had for some time been very irksome to the lad,
the secret witness testifying against it.
In looking at the answer that fell to his lot in the lesson one day, he found that,
to the question: "`What are the decrees of God?`"--he must reply,
"`That God`'s decrees are the wise, free and holy acts of the counsel of his will,
whereby from all eternity He has, for his own glory,
unchangeably foreordained whatsoever comes to pass in time,`" etc.
This doctrine of predestination in subversion of man`'s free agency,
was what his Bible had not taught him, and he found that he must decline these lessons;
but how to break his determination to the master was the question; yet,
as his peace consisted in it, he made the request.
In surprise,
the teacher desired to know why he wished to be excused from saying his catechism,
which he looked upon as next to the Bible, if not equally sacred.
The straitened boy could only reply that he did not feel easy to learn it.
"`But,`" said the master, "`I cannot excuse you unless you give me a reason.`"
At length Christopher had fairly to tell him he could
not learn his catechism because it was not true.`"
"`Not true!`"--said the astonished master, who, although he set great store by the lad,
seemed almost horror-struck at his declaration.
However, finding him firm,
he told him that if he would make his word good by proving the catechism to be false,
he would excuse him hereafter from these lessons,
and after school that day was appointed for the proof.

A time of deep trial, the little fellow had till the hour came,
to which nearly all his school fellows stayed.
But Christopher, though so young, had read his Bible with care,
and had a retentive memory,
and the good Remembrancer brought to his recollection this passage of the prophet Jeremiah,
where, speaking in the name of the Most High, it is said:
"`They have built the high places of Tophet, which is in the valley of the son of Hinnom,
to burn their sons and their daughters in the fire; which I commanded them not,
neither came it into my heart.`"
Showing that these things were not pre-ordained of God, but were of man`'s own wickedness.
The astonished schoolmaster could only say he "`did not
think there had been anything like it in the Bible.`"
However, he released the lad from saying his catechism any more.

Twenty-five years afterwards,
when Christopher had been recommended as a minister
of the Society of Friends about seven months,
a concern came upon his mind to visit the scenes of his childhood,
and having procured the requisite credentials from his Monthly Meeting,
he came to this very spot, and appointed a meeting,
to which his old schoolmaster and former schoolfellows were invited and came.
In this meeting he was led to relate this anecdote, saying:
"`And you are my witnesses,`" as he appealed to them,
and detailed some of the dealings of the Lord with him in drawing him towards Friends,
and opening one by one their testimonies to his understanding.
His old master seemed rejoiced to see him, and clung to him with affection,
and his schoolfellows received him with open arms.

In her early life, Mildred Ratcliff was a zealous Baptist.
Her father and a number of her near connections were ministers among them,
and she was warmly united to that people.
When quite young she was married to Harrison Ratcliff,
who had been brought up among Friends.
They resided near Lynchburg, Virginia,
and Mildred sometimes accompanied her husband to a meeting
of Friends in the neighborhood of their residence.
She had once before their marriage been at such a meeting,
but appears to have derived no satisfaction therefrom.
She says of Friends:

[.embedded-content-document]
--

Going sometimes with my husband to their silent meetings, I sat among them,
wondering at such a manner of holding a religious meeting,
it being to me as lost time--time that I might have improved at my own meeting.
Truly, a silent meeting was all foolishness to me.

At that time I had not read a page in a Friends`' book that I remember.
But after this, my mind being prepared, I picked up John Woolman`'s Journal,
and said in my heart,
I will look in this book to see if there is any sense in anything a Quaker can write.
Before I had read many pages my spirit was broken and my heart
contrited under a sense that the lack of sense was in me,
and not in the Quakers.
I was blinded with tears, and had to shut the book.
Yet, from time to time, and little by little, being anxious to see the contents,
I read it as secretly as possible.
Truly I had not got half through,
before I thought I saw the beauty of holiness shine in his remarks
brighter than I ever saw the sun shine in the clearest day.
What he said on the subject of oppression answered to the
exercise through which I had passed on the same subject,
as face answers to face in a glass.

Although now in a good degree convinced of the principles Friends profess,
yet there was something in me that felt abhorrence
at the idea of ever being called a Quaker,
notwithstanding the fervent desire of my soul, day and night,
to become a humble follower of the Lord Jesus Christ,
in whom I did believe according to the Scriptures.
I continued going to the Baptists`' meeting and Friends`' by turns, until,
when I would go to the +++[+++Baptists`']
meetinghouse door, it seemed to me I felt a hand, though invisible,
clap me on the right shoulder, and with it I heard the language in secret,
yet plain and intelligible: "`You have no business here.`"
I did not know what to make of it.
Though startled; I went in and took my seat.
But my peace was broken, so I could not enjoy the meeting.

I went to the Baptist meeting again and again, and as often as I did so,
felt the same invisible hand, and heard the same language.
My poor mind was all in confusion.
I had a great life in singing, but I had no pleasure in it in those meetings.
I had not then felt any concern about singing or compliments not being right.
Such was the state of my mind I did not know what to do.
My distress increased so when I went to the Baptist meeting that I gave it up,
and went to no meeting for a time.
On First-day I would read Friends`' books.
My peace sometimes was great while at home reading,
notwithstanding my stubborn determination not to be called a Quaker.
Oh, the matchless mercy, the longsuffering of the Good Shepherd,
who laid down his life for the sheep,
was marvellously manifested in waiting for a poor nothing like me.

--

About four years after her marriage, Mildred became a member among Friends,
and as she was strengthened to persevere in a Christian course,
desiring above everything else to love and serve her God,
and to know the salvation of her soul wrought out,
she became prepared to advocate publicly the Lord`'s cause.

The following account was received from Isaac Pickerill,
an eminent Friend of Reading in Berkshire:
at the time of the occasion he lived in the borough.

[.embedded-content-document]
--

I was informed, +++[+++said he,]
of an ancient woman Friend living in Long Lane,
who had let in some discouragement that as she was little known,
Friends would not permit her body to be interred in their burial ground, which,
when I heard of, I went with a Friend or two to pay her a visit.
On coming to the door, a little girl ran out and said: "`Grandmother,
here is some of your friends asking for you.`"
On which she rose up and met us and said:
"`And is it some of my dear friends come to see me?
The Lord preserve them and me to the end!`"
Having sat down and conversed with her about the subject of her uneasiness,
we assured her that her request would be granted,
and added that if she needed any assistance for her support
she should have every accommodation in their power to procure,
which tended to revive her, and she cheerfully said: "`Now, friends,
I will tell you how I was convinced.
I was a young lass, at that time in Dorsetshire, when George Fox came into that country,
and he having appointed a meeting, to which the people generally flocked,
I went among the rest, and in going along the road, this query rose in my mind:
'`What is it that condemns me when I do evil, and justifies me when I do well?
What is it?`' In this state I went to the meeting, which was large.
George Fox rose with these words: '`Who are you who queries in your mind,
What is it that condemns me when I do evil, and justifies me when I do well?
What is it?
I will tell you.
Lo! He that formed the mountains, and created the winds,
and declares unto man what are his thoughts, that makes the morning darkness,
and treads upon the high places of the earth; the Lord, the Lord of hosts in his name.
It is He by his Spirit that condemns you for evil, and justifies when you do well.
Keep under its dictates,
and He will be your preserver to the end.`'`" To which she added: "`It was truth,
the very truth, and I have never departed from it.`"

--

Thomas Story, in his Journal,
thus gives his views of the manner in which the conversion
of the Indian races to Christianity would be effected:

[.embedded-content-document]
--

As to the conversion of the Indians of all, or any nation and nations, to the Truth,
I believe the Lord will call them, after the power of antichrist is overthrown;
but it seems to me, that learning, or the historical part of religion,
or their own language (which is very barren of pertinent words),
will not be much instrumental in it; but the Word of life,
whose Divine and life-giving intellectual speech is more certainly known in the mind,
will tender their hearts, in a silent state and retirement,
by means of some instruments that the Lord will raise up and qualify for that purpose;
who shall not confound them with a long fruitless history of needless things.
But when the Lord shall send forth his word, the light of the Gentiles,
the quickening spirit of Jesus, into and upon any of them in holy silence, or in prayer,
their minds shall be directed to the Spirit himself,
as the present object of their faith, obedience and love,
and author of their present joy and salvation; and so,
believing in the Light they shall become children of that light and day of God,
and heirs of eternal life in Him.
And then the histories in the Bible, the prophecies of the prophets of God,
and the fulfilling of them; the evangelical account of the conception, birth, life,
doctrine, miracles, death, resurrection, ascension, glorification, mediation,
intercession, and judgment of Him, who is the substance of all,
and that true light which gives light to every man that comes into the world,
will be the more clearly received by the Indians,
when the Almighty shall think fit to acquaint them therewith.

--

[.offset]
Thomas Story,
writes thus beautifully of the blessings attending on a true submission to God:

[.embedded-content-document]
--

I called unto God out of the great deep; He put on tender mercies,
and had compassion on me, because his love was infinite, and his power without measure.
He called for my life and I offered it at his footstool;
but He gave it me as a prey with unspeakable addition.
He called for my will, and I resigned it at his call;
but He returned me his own in token of his love.
He called for the world, and I laid it at his feet, with the crowns thereof;
I withheld them not at the beckoning of his hand.
But mark the benefit of exchange, for He gave me, instead of earth,
a kingdom of eternal peace; and in lieu of the crowns of vanity, a crown of glory.

--

Rebecca Travers was a gentlewoman,
who was thought of account in that day of religious excitement and high profession.
She had received a good, religiously guarded education,
and was a zealous professor among the Baptists.
The many reports that had reached her of the Quakers in the north,
had prejudiced her strongly against them.
She looked upon them as worthless, uncivil fanatics,
who were very uncomely in their appearance, their manners and carriage;
with whom those who stood fair in church or State
could wish to have little or nothing to do.

James Nayler having come to London in 1655,
preached with so much eloquence that many of the higher rank flocked to hear him,
and some of the Baptist pastors challenged him to dispute with them.
A time and place was agreed on and there was no little interest excited among very many.
Rebecca Travers having been invited by one of her
friends to accompany her to hear this dispute,
consented to go,
fully prepared--as she afterwards said--to witness the defeat of
the rustic Quaker by the learned ministers of her own Society.
But greatly was she surprised and confounded,
when the "`countryman,`" rising on a platform opposite to the ministers,
after they had spoken,
poured out such a stream of Scriptural argument as overturned all the
objections that had been brought forward against the principles of Friends,
and showed that those principles were based on the immutable foundation of Truth.
Two of the Baptist ministers said they were sick, and went away,
while the other failed to show how the texts he quoted sanctioned the opinions he advanced.

Though mortified at the result of the dispute,
Rebecca was curious to hear James Nayler preach,
and the next First-day went to the Bull-and-Mouth meeting,
where he spoke so convincingly, that she remarked: "`She could not but declare,
that if she had lived in the apostles`' days,
she could not have heard Truth more plainly,
nor in greater power and demonstration of the Spirit, than she had that day.`"
From that time she became a constant attender at the meetings of Friends;
but still she found it a hard matter fully to act
up to the doctrines she knew to be true.
There were many things to be given up hard to part with,
and her former habits of religious profession prompted
to seek for that knowledge in Divine things,
which could be obtained by the natural understanding alone.

Some time after, having been invited to dine in company with James Nayler,
a person present who was a high professor, put many curious questions to him.
James answered him with wisdom, but with great caution;
but not so as to gratify the strong desire she felt
to hear him discourse of these sacred mysteries.
Presently James Nayler, reaching across the table,
took her by the hand and addressing her, said: "`Feed not on knowledge;
it is as truly forbidden to you, as ever it was to Eve: it is good to look upon;
but not to feed on; for who feeds on knowledge, dies to the innocent life.`"
This was spoken with power, and carried conviction to her soul.
She gave up her own willing, and searching into hidden mysteries,
became emptied of her self-knowledge, and taking up the daily cross, she found that,
as a babe in Christ,
all that was necessary for her to know of those things hidden from the wise and prudent,
was revealed to her by the spirit of her Father in heaven.
She became an acceptable minister in the Society;
suffered much for witnessing to the Truth, and died beloved, in a good old age.

[.offset]
John Conran of Ireland, gives the following account of his religious experience:

[.embedded-content-document]
--

I was born in the city of Dublin, in the year 1739;
my parents professing with the church of England, I was bred in that profession,
and had the advantage of a pretty liberal education under a clergyman of that way.
After I had acquired some acquaintance with the classics, before I was twelve years old,
I was placed under the care of Abraham Shackleton, of Ballitore,
where I acquired further improvement in my former studies,
as well as an acquaintance with such learning as was necessary to qualify me for business.

I was placed apprentice in Lisburn, in the county of Antrim, to learn the linen trade;
in that situation I had more liberty than hitherto I had experienced.
My intimate acquaintance was with young men, about my own age;
and having a pretty good share of money given to me by my relations,
it led me into amusements to which youth are incident.
I kept a horse, and was very fond of hunting; I attended balls and assemblies,
to which I was much addicted: and this led to a desire after fine clothes,
which I indulged to an expensive degree; I was also fond of music,
and had a strong propensity to singing and whistling, which the love of music leads to.
I may say with Solomon,
I gave my heart to know pleasure in most shapes which the sons of men are given to--not,
as the wise man said, to know what it was good for;
that knowledge was reserved by the good Shepherd for a future day,
when I was made to see in that light which is superior to the written word,
that these things lead to the chambers of death;
for the lovers of (worldly) pleasure are not, nor can be, lovers of God,
as there is no concord between Christ and belial.

I continued pretty much in these practices and habits
till I was about twenty-four years of age,
when I felt my mind oftentimes brought into serious reflections,
and that disposition gradually wore away which led me into gay company,
and at the same time out from hearing the Divine voice,
which was a still small voice in the secret of my heart; and to the surprise of many,
some of whom were otherwise valuable members of the community,
I left the assemblies which were termed innocent amusements.
I had lodgings in town, and kept very much at home;
my former companions used to come and tempt me to go with them,
but I refused with such a countenance bespeaking a degree of solidity as surprised them;
and I heard it reported I was taking leave of my senses,
which occasioned others to come and look at me to see if it were so.

I had been in the practice of going occasionally
to the meetings of Friends for years past,
but as my spirit became exercised after more durable riches than I had already obtained,
I attended them more frequently, yet cannot say I felt myself much benefited thereby;
for although I knew the people called Quakers made profession
of a more spiritual religion than other people in this land,
I was not then capable of forming a just judgment of that which
I had only heard of by the hearing of the outward ear;
my spiritual eye had not been then anointed,
by which only I could see the wonders of the new creation of God, in,
and through his dear Son, Christ Jesus.
The time was not yet come that the Lord would enter into his temple,
and the earth would be moved at his Divine presence,
who indeed is the Lord of the whole earth, and worthy, worthy to be feared,
honored and obeyed!

While I was in this seeking frame of mind I attended a Province meeting held in Lurgan.
In the first sitting a Friend spoke upon this portion of Scripture: "`Behold,
I stand at the door and knock: If any man hear my voice and open the door,
I will come in to him, and sup with him and he with me.`"
I did not find this testimony produced any good effect in me,
for I was built up in a good opinion of the religious profession of my education,
and I did not see much in the lives and conduct of many among the Quakers,
to induce me to give them much preference to many among my fellow-professors: moreover,
I did not comprehend the nature or use of silent meetings.

There was a Friend there from Pennsylvania, Robert Willis,
I think he was silent in that sitting.
Upon Friends gathering into the meeting for discipline, I went in,
not knowing the impropriety of it;
and though there were door-keepers they let me pass on,
as they observed a solidity in my countenance.
In the pause of silence, Robert Willis spoke, what it was I could not tell,
my mind being gathered into inward silence;
but such a power broke in upon me that I was greatly broken into tears,
and my whole body was shaken in an extraordinary manner,
attended by feeling the Divine Life to arise within me;
and though it brought a spirit of judgment with it, yet it left a healing virtue,
so that I thought then I would not be ashamed to
confess to the Truth in the public streets,
let the shame be ever so great.
The cross then was nothing to me when compared with
the treasure which was hidden in my heart;
I was then determined to sell all,
so that I could gain this pearl I had been searching for so long.

Oh, I remember that day, how I did rejoice!
A new song was put into my mouth, even praises to my God!
This I call, as to myself, the beginning of the new creation of God, in Christ Jesus.
The Gospel in the days of the first messengers was termed by the worldly-wise and prudent,
foolishness--an eminent publisher of it was told much learning had made him mad;
their lives, indeed, were counted as madness,
because the life they then lived was in Christ Jesus,
while the lives of those who condemned them were after the flesh,
fulfilling the lusts thereof.
At the same time I fear there are many who make profession with me of those things,
who are not able to comprehend them,
for we have not anything that is good but what is given to us of God;
and if we are not concerned to ask wisdom from Him we shall not receive it,
for the promise remains to be to those who ask; some among us do ask, but they ask amiss,
asking that from the form which it cannot give.
But I write these things for the wayfaring man and woman who may be travelling Zionward,
and can read me in their own experience, to encourage them to hold on their way,
and to let no discouragements they may meet with in their wilderness travel,
cause them to look back to Egypt,
for it is only those who hold out to the end that will be saved.

I was now very much reduced to silence, and my spirit oftentimes inward,
waiting and looking after Him whom my soul loved.
I thought,
having found Him of whom Moses and the prophets did write--whose
blessed day Abraham saw in the vision of life,
and was glad,
and whose blood of sprinkling speaks better things than that of
Abel--that now the Egyptian bondage of sin was at an end;
which perhaps was the case with Israel formerly,
when Moses brought the message to them from the God of their fathers,
commanding Pharaoh to let Israel go and worship their God.
But spiritual Pharaoh was not to be so easily prevailed against as I thought.
When he found I was for moving from under his government,
and making for the promised land,
submitting myself day after day to the guidance of the cloud by day,
and the bright flame by night, I was closely pursued by him, his horsemen and chariots,
as if they were determined I should not escape from them.
The power that was permitted them to try me was great,
so much so that I thought there was no other power so great,
not having as yet experienced the coming of Him who was stronger than they,
clothed with the power of his Father, to spoil the strong man of his goods,
turn them out and take possession for himself.
This is the work of regeneration--this is the Gospel of glad tidings (the power of God),
preaching and teaching liberty to the captive,
and the opening of the prison doors to them who had
been bound by the chains of darkness and of sin.
This is not the work of a day or of a year--perhaps
it may be that of the greatest part of our lives.
The command of our Lord and Master must be remembered in every stage of our journey,
to "`watch and pray.`"

--

The narratives of their convincement and early religious life given in the autobiographies
of the members of our religious Society are full of deep instruction.
They all speak of the reproofs for sin,
of the Divine inspeaking Word--the remorse and contrition that follow--the
sense of forgiveness through the atoning sacrifice of Christ--the sweet
consolations of obedience and well-doing--the being led on from knowledge
to knowledge in the path of duty--the conquest over pride,
vanity, sensuality and selfishness.

One of the most interesting of these narratives is that left us by the first John Fothergill.
He was born at Wensleysdale, in Yorkshire, in 1676, of pious, exemplary parents,
members of our religious Society.

[.embedded-content-document]
--

When I was between six and seven years old, as near as I can recollect,
being at some little play with another boy, through the force of a sudden temptation,
I swore an oath, which, notwithstanding it was to a truth,
yet such secret convictions of the evil of so doing in the sight of the Almighty God,
so affected my mind with sorrow and remorse, as made a lasting impression on my judgment,
and also imprinted that warning and fear in my heart in this respect,
that I never did the like since on any occasion.

Another thing I am inclined to mention is,
that when I was about twelve or thirteen years old, which was after my mother`'s decease,
a strong inclination took place in me to have a coat made with some more resemblance
of the mode or fashion of the time than in the plain manner which I had,
with other Friends, used, and I prevailed on my father to grant it.
But I was made uneasy in it almost at the first wearing it, and the more so in using it,
feeling the certain reproofs of the Spirit of Truth,
for leaning to and joining with the vain and restless flesh-pleasing spirit of the world,
and turning from the steady plainness of the unchangeable Truth.
I was indisputably satisfied that the enemy of all good worked
in the earthly affections of those wherein he could get place,
to draw out the mind at times, of the youth especially,
after the unsteady corruptions of the depraved world,
in its changeable and vain fashions in dress and clothing,
in order to lead into the broad way, and by degrees into the wide world,
one step making way for another.
On the other hand, I was in a measure then,
and have been since more immovably assured that the light of the Gospel day,
the Spirit of Truth,
does appear against and reprove the very conceptions of such vain desires and inclinations,
and would lead and preserve out of them,
if people did but attend thereto and labor honestly
to bear the cross of Christ in this respect.

I think this year, Thomas Wilson and James Dickenson came into the country,
and some time afterwards to visit the meeting of Friends at Crosswicks.
I happened to be at the meeting before they came in.
The sight of them struck me.
The heavenly frame of mind which their countenances manifested,
and the awe they seemed to sit under, brought a stillness over my mind,
and I was as ground prepared to receive the seed.
James stood up in the authority of the Gospel,
and in it he was led to unravel me and all my works from top to bottom,
so that I looked on myself like a man dissected or pulled to pieces--all my religion,
as well as all my sins, were set forth in such a light that I thought myself undone.
After he sat down, Thomas stood up and brought me together again,
I mean what was to be raised, bone to his bone,
with the sinews and strength that would constitute a Christian.
I almost thought myself new born, the old man destroyed and the new man made up,
concluding I should never be bad again, that my sins were forgiven,
and I should have nothing to do but to do good.
I thought I had gotten my lot in the good land,
and might sit now under my own vine and fig-tree, and nothing more should make me afraid.

Poor creature!
I had only a sight.
I did not yet think what powerful adversaries I had to war with.
This has been the miserable case of many.
They have sat down under a convincement, and in a form of religion,
some depending on former experience or former openings, some on their education,
some on a bare belief and historical knowledge of the Scriptures and principle of Truth.

--

[.offset]
Thomas Story, in his memoirs, relates the following remarkable visitation of Divine grace:

[.embedded-content-document]
--

My mind being truly earnest with God,
thirsting unto death for the knowledge of the way of life,
He was pleased to hear the voice of my necessity, for I needed present salvation,
and the Lord knew my case could not admit of further delay.
Being moved by his own free mercy and goodness,
even in the same love in which He sent his Son, the beloved, into the world,
to seek and save the lost; on the first day of the Second Month,
in the evening of the year, according to the common account 1689,
being alone in my chamber, the Lord broke in upon me unexpectedly,
quick as lightning from the heavens, and as a righteous, all-powerful,
all-knowing and self-condemning Judge, before whom my soul, as in the deepest agony,
trembled, was confounded and amazed,
and filled with such awful dread as no words can reach or declare.
My mind seemed plunged into utter darkness,
and eternal condemnation appeared to enclose me on every side,
as in the centre of the horrible pit, never to see redemption there,
or the face of Him in mercy, whom I had sought with all my soul.

But in the midst of this confusion and amazement, where no thought could be formed,
or any idea retained, save eternal death possessing my whole man,
a voice was formed and uttered in me: "`Your will, O God, be done;
if this be your act alone, and not my own, I yield my soul to you.`"
In conceiving these words, from the word of life, I quickly found relief;
there was all-healing virtue in them, and the effect was so swift and powerful, that,
even in a moment, all my fears vanished, as if they had never been,
and my mind became calm and still, and simple as a little child,
the day of the Lord dawned, and the sun of righteousness arose in me,
with Divine healing and restoring virtue in his countenance,
and He became the centre of my mind.

--

It was some time after this remarkable experience,
before Thomas Story met with the Society of Friends.

[.embedded-content-document]
--

The occasion of it was some concerns that I had in the west parts of Cumberland,
when lodging at an inn kept by one of that profession, on a Seventh-day night;
and inquiring of him concerning some points of their religion,
I perceived no material difference between his sentiments and mine,
in the particulars then asked after;
and he also perceived I was nearer them than he or perhaps any other had thought;
for I had formerly opposed the same man in some things,
which gave him occasion to inform me of their meeting, to be held next day,
at a country village called Broughton.

As I had been desirous to be rightly informed concerning that people,
and to see them as in truth they were, I was pleased with the opportunity,
and the next morning the Friend and I set forward toward the meeting.
He being zealous to have me further informed and convinced of the truth of their way,
spoke of many things as we rode along, and with a good intent,
but my mind being composed, and its attention directed towards God,
who knew I only wanted to see the Truth, and not to be deceived,
I could not take any distinct notice of what the Friend said; which he perceiving,
after some time desisted, and said no more.
And then we rode some miles together in profound silence,
in which my mind enjoyed a gentle rest and consolation from the Divine and holy presence.

When we came to the meeting, being a little late, it was full gathered,
and I went among the throng of the people on the benches;
and sat still among them in that inward condition and mental retirement;
and although one of their ministers, a stranger,
began to speak to some points held by them,
and declaim against some things held by others and denied by them,
particularly predestination as asserted by the Presbyterians;
yet I took not much notice of it.
I did not doubt but, like all other sects, they might have something to say,
both for their own and against the opinion of others,
yet my concern was rather to know whether they were a people gathered
under a sense of the enjoyment of the presence of God in their meetings;
or, in other words,
whether they worshipped the true and living God in the life and nature of Christ,
the Son of God, the true and only Saviour.
And the Lord answered my desire according to the integrity of my heart.

Not long after I had sat down among them,
that heavenly and watery cloud overshadowing my mind,
broke into a sweet abounding shower of celestial rain,
and the greatest part of the meeting was broken together,
dissolved and comforted in the Divine presence of the true, heavenly Lord;
which was several times repeated before the meeting ended.
In the same way, by the same Divine power, I had been often favored before when alone,
and when no eye but that of heaven beheld, or any knew but the Lord himself,
who in infinite mercy had been pleased to bestow so great a favor.
And as many small springs and streams descending into a proper place,
and forming a river, becomes more deep and weighty, even so,
thus meeting with a people gathered of the living God into
a sense of the enjoyment of his Divine and living presence,
through Jesus Christ, the Son of God and Saviour of the world,
I felt an increase of the joy of salvation of God;
and the more by how much I now perceived I had been
under the like mistake as the prophet of God of old,
but now was otherwise informed by a sure evidence and token,
by the witness of the Divine Truth, in which no living soul can err or be deceived,
being self-evident and undeniable in all those who truly know Him.

Our joy was mutual and full, though in many tears,
as in cases of the deepest and most unfeigned love;
for the Friends there being generally sensible I was affected and tendered with them,
by the influence of the Divine Truth they knew and made profession of,
did conclude I had been at that time, and not before,
convinced and come to the knowledge of the way of Truth among them;
and their joy was as of heaven at the return of a penitent,
and mine as the joy of salvation from God in view of the
work of the Lord so far carried on in the earth,
when I had thought, not long before,
there had scarcely been any true and living faith or knowledge of God in the world.

--

Christopher Story, who resided in the North of England,
attended a meeting appointed by Thomas Carleton and Thos.
Langhorn.
He says:

[.embedded-content-document]
--

Thomas Carleton, a man of a sweet countenance,
spoke concerning the Spirit of Truth being come, that convinces the world of sin,
and that this, if taken heed unto, would lead out of all sin;
of which words I was heartily glad; for I said in myself,
"`I have felt that from a child, which condemned me for sin,
and if this be sufficient to lead out of sin, it is what I have long wanted.`"

Being invited, the Friends went home with me.
In a few hours, it being in the winter, and the nights about the longest,
many neighbors came to hear and see, and the house being pretty well filled,
Thomas Carleton and Thomas Langhorn advised me to speak to the people to sit down,
and we would have a meeting; I did so, and we had a meeting.
Afterwards several of us went to an upper room, and having written some queries,
came down.
When the Friends perceived what we aimed at, Thomas Carleton called for a Bible,
and did not so much argue with us, as endeavor to let us see what the Scripture said,
putting us gently by, for we were much for arguing; we parted pretty well satisfied.
Next morning the Friends going to Carlisle, Christopher Taylor and I went with them,
and we asked many things, which they answered to our satisfaction.
After we parted on our return home, we said one to another,
"`If there be saints on earth, these men are two of them!`"

--

Isaac Penington, in describing his spiritual progress,
mentions some of the exercises and trials he passed through, and goes on to say:

[.embedded-content-document]
--

At last, after all my distresses, wanderings, and sore travails,
I met with some writings of this people called Quakers,
which I cast a slight eye upon and disdained, as falling very short of that wisdom,
light, life and power, which I had been longing for and searching after; I had likewise,
some time after this, opportunity of meeting with some of them,
and several of them were by the Lord moved (I know it to be so since), to come to me:
as I remember at the very first they reached to the life of God in me;
which life answered their voice, and caused a great love in me to spring to them;
but still in my reasonings with them, and disputes alone, in my mind, concerning them,
I was very far off from acknowledging them, as so knowing the Lord,
or so appearing in his life and power as my condition needed, and as my soul waited for.
Indeed, the more I conversed with them,
the more I seemed in my understanding and reason to get over them,
and to trample them under my feet, as a poor, weak, silly, contemptible generation;
who had some smatterings of Truth in them, and some honest desires towards God,
but very far off from the clear and full understanding of his way and will.
And this was the effect almost of every discourse with them, they still reached my heart,
and I felt them in the secrets of my soul,
which caused the love in me always to continue, yes, sometimes to increase towards them;
but daily my understanding got more and more over them,
and therein I daily more and more despised them.

After a long time I was invited to hear one of them (as I had been often,
they in tender love pitying me, and feeling my lack of that which they possessed),
and there was an answer in my heart, and I went in fear and trembling,
with desires to the Most High, who was over all, and knew all,
that I might not receive anything for Truth, which was not of him,
nor withstand anything which was of him,
but might bow before the appearance of the Lord my God, and none other: and indeed,
when I came, I felt the presence and power of the Most High among them;
and words of truth, from the Spirit of Truth, reaching to my heart and conscience,
opening my state as in the presence of the Lord.
Indeed, I did not only feel words and demonstrations from without,
but I felt the dead quickened, the seed raised, insomuch as my heart,
in the certainty of light and clearness of true sense, said: "`This is He, this is He,
there is no other; this is He whom I have waited for and sought after from my childhood,
who was always near me, and had often begotten life in my heart,
but I knew him not distinctly, nor how to receive him, or dwell with him.`"
And then in this sense in the melting and breakings of my spirit,
was I given up to the Lord, to become his,
both in waiting for the further revealings of his seed in me,
and to serve him in the life and power of his seed.

--

Christopher Taylor is said to have received a classical
education intended to fit him for the priestly office;
but he afterwards became a religious teacher among the Puritans.
While thus employed,
he appears to have been tried with doubts as to whether he had
received a true call and qualification for the ministry.
Meeting with a book by Isaac Penington, in which he quoted the Scripture passage:
"`Who is this that darkens counsel by words without knowledge,`"
he was deeply affected by the weighty remarks made upon it,
and clearly perceived that no man can ever be a minister of Christ,
except the great work of regeneration be first wrought in his own heart.
He saw that the ministry of the Gospel was a spiritual ministry,
declared in the motion and evidence of the Spirit; otherwise,
it would be but darkening of counsel by words without knowledge.

In 1652 he became a minister among Friends, and preached the Gospel freely,
travelling much to call the people to Christ.
In 1654 he was imprisoned for his testimony at Appleby, Westmoreland,
where he continued for nearly two years, subjected to inhuman usage.
In 1661, he was arrested in a religious meeting and committed to Aylesbury Jail.
Some time after his liberation,
he appears to have changed his place of abode to Waltham Abbey, Essex,
where he superintended a boarding school for Friends`' children of both sexes,
which deservedly obtained a high reputation in the Society.
His instructions and influence, combined with those of his wife and assistants,
were eminently blessed to the young persons under their care.
In the narrative published by Christopher Taylor, in 1679, entitled:
_A Testimony to the Lord`'s Power and Blessed Appearance Among Children,_
he gives an account of an extraordinary visitation
of heavenly love to the pupils in the school.
In this account he says:

[.embedded-content-document]
--

Sitting, toward evening, with the family and children, in all about fifty,
the Lord`'s sweet, tender, heart-breaking power, was with us in a shower of love,
mercy and gentleness, which caused abundance of tears and great gladness,
like to the love of a most tender father, in forgiveness and submission,
especially to such who had been most stubborn;
and the mild and gentle were under the sense of the same power,
in pure love and sweet tenderness.
The whole meeting was, I may truly say, so filled with Divine comfort,
that the heavenly flame drowned all sorrow at that time,
and conquered all sense of terror and judgment,
nothing but love and mercy appearing and overcoming all,
that it was wonderful to behold the great gravity and sense of the children in the exercise.
And now I may say, that there is not one,
who has been of the worst temper and disposition,
but in pleading with them about their condition,
has been broken into a sensible acknowledgment with weeping eyes,
so far has the blessed power of the living God appeared in this place;
a day much longed for, glory to the Lord forever;
and certainly the living God will bestow more of his blessings upon us,
by still pouring forth of his heavenly spirit and his glory, as we are tender before Him.

--

[.offset]
Henry Hull, in the [.book-title]#Memoirs of his Life#, relates the following incident:

[.embedded-content-document]
--

On one occasion, as I was walking over a hill covered with trees,
I saw a large one that had been struck by lightning.
I sat down under it in silent meditation on the power of the electric fluid,
thinking it but a common accident from natural causes,
and that it was well I was not there at the time the tree was struck.
As I thus sat, all my thoughts were stayed and brought into subjection,
and an awful silence prevailing in my soul, a language intelligible to my mind,
proclaimed within me, "`You see how awfully powerful the lightning is--thus,
as in the twinkling of an eye, I could deprive you of your existence.`"
I was struck with amazement, and as I walked home, pondered what I had heard;
and believing it was the voice of the Almighty,
I felt a degree of reverence spring in my heart, as also of gladness,
in thinking I was not wholly cast off.
I was led to contemplate my past religious experience,
and was strengthened to forsake my foolish consultations with flesh and blood;
and feeling myself to be a poor creature,
I resolved to seek afresh the favor of Him who is infinite in power and goodness.

--

Among those in the North of England who joined with Friends, was Aaron Atkinson,
who was of believing parents convinced almost with the first,
and of good repute in the country.
His father lived but a few years after his convincement;
yet bore a good testimony for the time.
His wife was left with six small children, and not much outward substance;
yet she was not cast down under her exercise; for the Lord made hard things easy,
so that she remained bright and cheerful.
"`After some time she sickened, and I went to see her;
I found her in a heavenly frame of spirit, resigned to die.
She was not anxious for her children,
but fully believed the Lord would take care for them.
In a few days she sweetly finished her course;
and her children were mostly provided for by her friends and relations.
In their young days they proved generally vain and careless for a time;
yet remembering the faith which was in their mother, I expected to see their restoration,
which in due time came to pass.`"

When Aaron was young and carried a linen pack on his back,
being at a kinsman`'s at Sikeside,
he went to an evening meeting at Christopher Taylor`'s, and in the time of prayer,
the Lord being supplicated that, as He had been pleased to visit the fathers,
He would visit the children, graciously answered that supplication,
and reached Aaron by his power, that he was as one slain at once and freely giving up,
went out in the faith and greatly prevailed.
His master, W. Alexander, a Presbyterian, hearing of it,
was at a stand what to do with him, yet concluding we were an honest people,
he would try him further.
After some time his master was convinced also, and they lived together in much love,
and honored Truth in their trading, being at a word with people.
Though they lived in Scotland,
they saw they were not to trade in goods that were prohibited, as many did,
neither were they free to sell such striped or gaudy
cloth as was not seemly for Friends to wear.

As their acquaintance was great,
and their integrity well known in the country by being preachers of righteousness,
where they were concerned among men, so the Lord raised them up,
and gave them living testimonies publicly to bear
in the power and demonstration of the Spirit.
Aaron was first concerned in a powerful manner,
to the reaching of the hearts and consciences of very many.
Then William came forth, and many people who knew them had a desire to hear them.
Meetings were kept at fresh places up and down the country,
and those who were not Friends would come three or four miles to them frequently,
so that in time our meetinghouse became too small,
and others would send to us to have meetings on their ground.
There was great openness in the country.
All Aaron Atkinson`'s brothers then living, and his sister joined Friends.

Of a remarkable visitation of Divine love to the members of the Society of Friends
about Plymouth and North Wales for a few years previous to 1720,
Jane Hoskins writes:

[.embedded-content-document]
--

Many of the youth were reached,
and by the effectual operation of Divine and heavenly life,
brought into true submission to the cross of Christ, several were called to the ministry,
and engaged to speak in the authority of the Gospel, which is now the same as formerly,
the power of God unto salvation, unto all who receive it with meekness,
and truly believe in and patiently wait for the inward
and spiritual appearance of Christ our holy Redeemer.

--

[.offset]
On one occasion Christopher Story remarks:

[.embedded-content-document]
--

Some years after our convincement,
being met at the house of C. Taylor to wait upon the Lord,
his power and presence in a wonderful manner overshadowed us in our sitting together;
and there was much brokenness and tenderness on the spirits of Friends,
which spread over the whole meeting, except three or four persons who sat dry,
and they proved not well.
I, being near the door, saw many in the room filled,
before the power of the Lord reached me.
Yet the Lord, in his free love and mercy,
was pleased to give me such a share among my brethren,
that my heart is always glad when I remember that season of God`'s love,
though now upwards of twenty years ago.

--

[.offset]
A writer in _The British Friend_ speaks of a family visit
paid to his father`'s house by the late John Finch Marsh:

[.embedded-content-document]
--

He was then a saintly-looking elderly man,
evidently weighted with a load of real humility and a deep
sense of the sacredness and responsibility of his calling.
After he had addressed my father and mother, a pause ensued.
Believing that he had been really sent by his Divine Master,
and being at that time specially depressed by a feeling almost of hopelessness
as to realizing the state to which I so earnestly aspired,
I put up a silent prayer that he might be commissioned to help me.
Immediately he turned towards me and told me that
although I was a perfect stranger to him,
a feeling of strong and loving encouragement arose in his mind for me.
He bade me be patient and trustful and faithful;
and then he assured me that I should be brought out into a large place,
and find freedom and strength beyond what I could at that time imagine.
When the opportunity was over he was very affectionate to me,
and we were both deeply touched with a sense of the lovingkindness of the Lord,
and of his special condescension and guidance on that occasion.

--

The following interesting incidents in the life of
George Withy were related by our friend,
Thomas Evans, a short time before his death:

[.embedded-content-document]
--

George Withy was the son of an ale-house keeper in Bristol, who was a dissipated man,
but his wife was a religious woman and much concerned for the welfare of her children.
Thomas Carrington, a minister of the Society of Friends, from Pennsylvania,
while on a religious visit to England,
felt a concern to visit the ale-house keepers of Bristol.

Among others was the father of George Withy;
the latter being at that time about thirteen years of age,
was engaged in carrying round the ale to his father`'s customers,
and having a remarkably sweet voice, he was often asked to sing.
The exposure to which he was subjected was cause of great concern to his pious mother,
which she had expressed to Thomas Carrington.
Before the interview closed, George Withy came in.
T+++.+++ C. looked attentively at him for awhile--then placing his hand on his head,
remarked to his mother--you need feel no concern for the lad,
for he will be met in a narrow place,
he will become convinced of the principles of the Society of which I am a member,
and will have to visit my native land in the love of the Gospel.

George, mentally resolved he would never become a Quaker, nor ever become a minister,
and he would certainly never visit America.
In the course of time he had an alarming attack of sickness, during which,
he was waited upon by his anxious mother, whose exercises on his account were very great.
He was indeed met in a narrow place, and became convinced of the principles of Friends,
and while relating this circumstance to Thomas Evans, he said, When I left my sick room,
I appeared in the garb you now see me in.

He was received into membership about the twenty-second year of his age,
and first appeared as a minister in his twenty-fifth year.
He became interested in a young woman, a member,
whose family objected to the marriage on account of his humble position in life.
But their attachment having such a foundation as to induce the
belief that it would be right to take that important step,
the objection was finally removed.
They settled several miles from Bristol,
and were in the practice of regularly attending the meeting twice in the week,
and having no conveyance were obliged to walk, which they continued to do,
until they had six children old enough to walk with them,
never omitting a meeting except in case of sickness,
and always taking the children with them.

His memorial states, he removed in the year 1805,
to reside within the compass of Frenchay meeting.
Some years after this, feeling a religious concern to visit America,
which he had long been resisting,
reasoning that he could not leave his dependent family and aged mother,
who was then about eighty-seven years old,
he was brought to a state of submission by a remarkable circumstance.
As he was lying on his bed one afternoon with closed eyes,
under a feeling of deep distress on account of this prospect,
it appeared to him that two men entered the room, each carrying a stool,
such as are used at funerals, and set them at the foot of his bed,
they then left the room, and returned,
bringing in a coffin which they placed on the stools; observing a plate on the lid,
he read--George Withy, died Seventh Month 13th, 1822, aged fifty-nine years.
This increased his distress--when he heard in his mental ear, the language,
"`If you will be faithful and yield to my requiring,
your family shall be cared for in your absence,
and I will add fifteen years to your life,
and you shall return to close your mother`'s eyes in death.`"

--

The visit to America was performed in 1821-2, and while in this country,
George Withy frequently had Thomas Evans for his travelling companion.
One day George Withy seemed thoughtful,
and was evidently passing through religious exercise.
He informed Thomas Evans that this was the day that he had seen
on the plate on the coffin should be the date of his death.
He feared that he had not been sufficiently faithful, and that his death, therefore,
would really occur.
This, however, did not prove to be the case.
Exactly fifteen years from that time George Withy died.
They visited Washington during the sessions of Congress, and George Withy,
wishing to hold a public meeting, Thomas Evans consulted some of the prominent men,
who encouraged it, and proposed to have it announced by hand-bills,
which were accordingly posted in different parts of the city.

On their way to attend the meeting,
the Friends observed a large number of vehicles collected
in the neighborhood of the Capitol,
the sight of which almost overwhelmed George Withy,
who remarked to his companion that he feared he had made a mistake.
The latter encouraged him to believe that this was not so.
On arriving at the door of the House of Representatives,
so large a crowd had assembled that way had to be made through
it for them to reach the seats it was intended they should occupy.

On a stand before them were a Bible and a glass of water, which, at their request,
were removed.
On seeing such a large concourse of people, George Withy`'s heart almost failed him,
and again he was reassured by his companion.

After sitting some time in silence, George Withy arose with the text:
"`For you see your calling, brethren; how that not many wise men after the flesh,
not many mighty, not many noble are called;
but God has chosen the foolish things of the world to confound the wise;
and God has chosen the weak things of the world to confound the things which are mighty;
and base things of the world and things which are despised, has God chosen; yes,
and things which are not, to bring to naught things that are;
That no flesh should glory in his presence.`"
Upon this he enlarged in a remarkable manner,
the audience being much impressed and affected.
Old men with white hair, and women dressed as dowagers,
were equally broken under his baptizing ministry, the tears streaming down their faces,
so that, to use the language of Thomas Evans,
"`The floor was literally strewed with tears,
and it was one of the most remarkable meetings I had ever attended.`"

After the meeting, the people crowded up to speak to him,
expressing their satisfaction and approval of the sentiments delivered.
As he was descending the steps of the Capitol, a Presbyterian minister embraced him,
saying: "`Dear brother, you have preached the Gospel this day.`"

Upon returning to his native land,
he found the promise verified--his family had been cared for,
and his mother was still living.
She deceased soon after, being about ninety years of age.
George Withy died the thirteenth of Seventh Month, 1837.

It is remarkable how circumstances of no uncommon kind,
and apparently in the usual course of events,
are at times made the means by Divine Providence to change
the character of men and their entire future life,
and it may be to lay the foundation of the work of their salvation,
and of promoting that of many others.
Claude Gay was a native of France, born in the City of Lyons, about the year 1706,
and was educated in the church of Rome,
of which he continued a zealous member until near the thirty-sixth year of his age, when,
coming to Morlaix on account of business,
he was brought under a religious exercise of mind.
During this time, seeing a copy of the New Testament in a room where he was,
he took it up, and observing it had been licensed by two popes,
concluded he might lawfully read it.
On opening the book, the first words he read were these: "`God that made the world,
and all things therein, seeing He is Lord of heaven and earth,
dwells not in temples made with hands, neither is He worshipped with men`'s hands,`" etc.
On the perusal of this passage, he was convinced, in his judgment,
of the errors of the Romish doctrine of transubstantiation, in which,
as he told a friend,
the papists believe that the consecrated wafer is changed into the body, blood,
soul and Divinity of Christ, which now appeared to him to be false,
and the adoration of the host, so called, idolatrous,
and of course contrary to the doctrines of the Gospel.

At the solicitation of a person,
who persuaded him not to forsake the public worship at once,
he went to one of the smallest mass houses in that town,
and placed himself at the greatest distance from the priest.
He did not keep kneeling steadily as was customary,
but first on one knee and then on the other, with great restlessness,
until the priest elevated the host, that the congregation, seeing it,
might prostrate themselves as usual before it.
This query strongly impressed his mind: "`Will you also prostrate yourself?`"
Being deeply affected with the convicting power of the Holy Spirit,
he could continue there no longer, but putting on his hat, with fear and trembling,
he arose and hastily left the place;
and confessed to his former adviser he felt great condemnation
for conforming that day against his conscience,
and that, being clearly convinced of the errors of the doctrine of that church,
he ought to forsake them.
He finally left the Romish communion, and went to live at Jersey,
in order to be among protestants.
Here he met with [.book-title]#Robert Barclay`'s Apology#.
He was, on perusing it, convinced of the truth of the doctrines contained in it,
and embraced the religious principles of Friends.
