== Chapter V. Divine Worship

The Society of Friends has ever embraced the truth declared by
our Saviour when He told the woman of Samaria at Jacob`'s well:
"`The hour comes,
and now is when the true worshippers shall worship the Father in spirit and in truth;
for the Father seeks such to worship Him.`"
Their members are exhorted to be diligent in assembling
together for the purpose of public worship,
and "`When assembled, the great work of one and all ought to be to wait upon God,
and retiring out of their own thoughts and imaginations, to feel the Lord`'s presence,
and know a gathering into his name, indeed, when He is in the midst,
according to his promise.`"
Robert Barclay testifies that:

[.embedded-content-document]
--

As everyone is thus gathered and so met together inwardly in their spirits,
as well as outwardly in their persons,
that the secret power and virtue of life is known to refresh the soul,
and the pure motions and breathings of God`'s spirit are felt to arise; from which,
as words of declaration, prayers and praise arise,
the acceptable worship is known which edifies the Church and is well-pleasing to God.
Yes, and though there be not a word spoken, yet is the true spiritual worship performed.
In fact, it may, and has often, fallen out among us,
that several meetings have passed without one word;
and yet our souls have been greatly edified and refreshed,
and our hearts wonderfully overcome with the secret sense of God`'s power and spirit.

--

Robert Barclay mentions, as one of the excellencies of this worship,
that it can neither be stopped nor interrupted by the malice of men or devils.

[.embedded-content-document]
--

For when the magistrates, stirred up by the malice and envy of our opposers,
have used all means possible (yet in vain) to deter us from meeting together, and that,
openly and publicly, in our own hired houses for that purpose, both death, banishment,
imprisonment, finings, beatings, whippings and such other devilish inventions,
have proved ineffectual to terrify us from our holy assemblies.
And we having, I say, thus oftentimes purchased our liberty to meet by deep sufferings,
our opposers have then taken another way,
by turning in upon us the worst and wickedest people, yes, the very offscourings of men,
who, by all manner of inhuman, beastly and brutish barbarism, have sought to provoke us,
weary us and molest us, but in vain.
It would be almost incredible to declare what things of this kind my eyes have seen,
and I myself, with others, have shared of, in suffering!
They have often beaten us and cast water and dirt upon us; then they have danced, leaped,
sung and spoken all manner of profane and ungodly words,
offered violence and shameful behavior to grave women and virgins, and much more;
and all this while we have been seriously and silently
sitting together and waiting upon the Lord.
But the Lord, knowing our sufferings and reproaches for his testimony`'s sake,
has caused his power and glory more to abound among us,
and has mightily refreshed us by the sense of his love, which has filled our souls.

--

This spiritual refreshment was a great encouragement to Friends
to persevere in publicly holding their meetings for worship,
and their faithfulness in the performance of this duty was very remarkable.
There was probably no other one testimony that exposed
them to so much and long-continued persecution.
Of this their records and biographies are full.

It was no uncommon thing when Friends were imprisoned,
to preach through the grates of their cells to the people, either passing,
or who would gather around to hear them.
In 1677, Patrick Livingston, George Gray and Andrew Jaffray,
confined in the tolbooth at Aberdeen, were frequently engaged in this way,
especially on market days.
The magistrates,
much offended that they should thus proclaim their principles and attract others to them,
separated them from their friends, and shut them up in a high,
close room on the top of the prison, called the iron-house,
where they had neither air nor light, but through a long hole in the wall,
having a double grate of iron on the outside and another within.
Here those worthy men were kept in the heat of summer,
where the filthiness of the place and the great impurity of the air so closely pent up,
bred worms and other vermin, which swarmed about their beds and their food,
endangering their health and their lives.
But through the supporting power of Him whom they served,
and for whose cause they suffered, they were kept cheerful, and enabled to proclaim,
with strong and elevated voices, the glorious truths of the Gospel,
through the long hole in the wall,
so as to be distinctly heard over the street by the people, who frequently got together,
and attentively listened to their voices whose faces they could not see.
It was generally remarked that, during their greatest sufferings,
they found the favor of God attending them,
not only causing their spirits to be cheerful,
praising the Lord in their most grievous afflictions,
but also preserving their bodies in health and strength,
beyond all human probability or expectation.
The malice of their adversaries became subservient to spreading
the doctrines of Truth which they were called to uphold,
their imprisonment, though designed to destroy their service,
being the means of many blessed opportunities for this purpose.

[.offset]
Hugh Roberts says of his mother:

[.embedded-content-document]
--

My mother was a religious woman since I can remember, which is about forty years.
She kept good order in her family and among her servants,
being a widow some years before, and so continued all the rest of her days.
She walked then among the Presbyterians, and had a great zeal for God,
and was much esteemed by these people.
In the year 1662, she was convinced of Friends`' principles,
though there were none of that persuasion then in the part of Britain +++[+++Penllyn]
where she lived.
Friends hearing of her convincement, came from far to visit her.
Many of her neighbors were also convinced of the principles she held,
and a meeting was set up at her house;
on which account she was summoned before the bishop`'s court,
where she held a great deal of discourse with him.
Soon afterwards a mighty persecution arose, which she bore with great courage.
The informers took from her for a fine of fifteen shillings, for holding two meetings,
four oxen that were valued at fifteen pounds.
She was cast into prison various times, often had irons put upon her,
and was once kept in a dungeon with murderers for several days and nights.
But none of these things alarmed or disheartened her, or weakened her testimony.
She had great confidence in the Lord, and loved his Truth and people.
We were five children, and were convinced of God`'s blessed Truth,
and that mostly by our mother`'s faithfulness thereunto,
for surely she was a good example unto us.

--

Giles Barnardiston was one of the early Friends who had received a university education,
and was designed to be a minister;
but feeling unwilling to enter on that sacred office without a sense of Divine requiring,
he joined in membership with the people of God called Quakers,
who were then exposed to much suffering from the persecution of those in power.

At Colchester many of them were taken from their meeting and committed to prison,
and the seats and windows of the house were broken up.
Being kept out of their house,
Friends collected in the street regularly on First and Fourth-days,
sometimes in cold and rain, and there held their meetings for the worship of God.
On the sixth-day of the Tenth Month, 1662, a troop of horse,
armed with swords and pistols, rode furiously among them,
beating with drawn swords old and young, male and female,
by which many were very much injured.
They returned the following week, having provided themselves with clubs,
and with these knocked down many, some of whom lay for a time as dead;
and many were so disabled that they could not take off their clothes,
nor feed themselves for several days.
These outrages were repeated for several weeks,
in which time a number of aged persons were disabled.
One man was so beaten that he lost much blood, and his wife,
fearing the troopers would kill him,
threw herself upon him to defend him from their blows, many of which she received.
Her father was knocked down and survived the blow but a few days.
Among these valiant sufferers for the Truth was Giles Barnardiston.

In the year 1669, Giles removed to Clare in Suffolk,
and with his brethren there was subjected to a course of persecution.
So many warrants of distress were issued that it was thought all
the estates of the members there were too little to satisfy them.
After taking all the goods out of one Friend`'s house, and the wood from his yard,
a neighbor desired the officers to leave a few old hoop-poles to boil milk for the children,
but they refused.
From another they took the team of horses from his plow;
and when they had made a spoil of a weaver`'s goods,
they broke his loom in pieces with the work in it,
which was his only means to get bread for himself, a sick wife and young child.

Friends could not forsake the assembling of themselves together,
but manifested their love and allegiance to their Lord and Master
by publicly offering that worship which is due to Him.

After all this spoiling of goods,
the Friends were kept out of their meetinghouse six months together in winter,
when they met in the open street as constantly as before, and underwent much abuse.
Two watchmen with halberts pushed them up and down the streets,
frequently striking and threatening to kill them.
One of the watchmen falling sick,
was relieved by some of those whom he had been engaged in abusing.
Their charity and Christian kindness in rendering good for evil,
so wrought upon his comrade,
that he refused to continue his outrageous treatment any longer,
and one day meeting a Friend whom he had abused, he said:
"`I desire you to forgive me--the blessing of God is among you.`"
Although they employed another to continue the same course,
the patience and mildness of Friends overpowered him,
and he finally took his seat on the threshold of
the meetinghouse during the time of their worship.

In 1670, the British Parliament passed an act against seditious conventicles,
designed to prevent Friends from holding their religious meetings, subjecting them,
where five persons or more were present, to a fine of five shillings each,
and twenty pounds for a preacher,
which the company were liable to pay if the preacher had not the property to be distrained,
or did not reside in the place.
Persecution followed the passing of the act to a very severe degree.
Many Friends were beaten with swords and pikes and muskets,
so that their blood ran to the ground;
and the informers were so eager in hunting their prey,
that they reported meetings where there were none.
At Droitwich, John Cartwright came to a Friend`'s house,
and sitting down to supper prayed before they ate, which was heard by an informer,
the room being next to the street.
He thereupon went immediately and informed that there was a meeting in that house,
and obtained a warrant to distrain the goods,
and when he came riding with them in the evening,
he fell from his horse and broke his neck,
thereby getting his death instead of the prey which he hunted after.

Neale, in his _History of the Puritans_,
bears full testimony to the zeal and faithfulness of Friends under these trying circumstances.
He says:

[.embedded-content-document]
--

The behavior of the Quakers was very extraordinary,
and had something in it that looked like the spirit of martyrdom.
They met at the same place and hour as in times of liberty;
and when the officers came to seize them, not one of them would stir;
they went all together to prison; they stayed there till they were dismissed,
for they would not petition to be set at liberty, nor pay the fines set upon them,
nor so much as the prison fees.
When they were discharged, they went to their meetinghouse again as before;
and when the doors were shut by order,
they assembled in great numbers in the street before the doors; saying,
they would not be ashamed,
nor afraid to own their meeting together in a peaceable manner to worship God;
but in imitation of the prophet Daniel, they would do it the more publicly,
because they were forbid.
Some called this obstinacy, others firmness; but by it they carried their point,
the government being weary of contending against so much resolution.

--

There were few places in which the spirit of persecution seemed more prevalent,
or where it longer continued than at Bristol.
A citizen of Bristol, writing to his friend in London,
under date of nineteenth of Fourth Month, 1682, says:

[.embedded-content-document]
--

Yesterday the Quakers`' meeting was again disturbed by our new sir John and his men.
The constables came not with him,
they by agreement having placed themselves in the meeting-room,
and had for their company several fiddlers, a drummer with a drum, also a flag and arms.
For this company food and liquor were provided, to carry on the designed revel and riot.
Just as the sheriff came, the doors of the meetinghouse were thrown open,
and the fiddlers began to play.
The sheriff smiling, asked what was the meaning of this.
One of his brother informers answered, they meant to be merry and came there to dance.
They attempted to lay hold of several young women to hale them in,
+++[+++having probably met outside the house], who,
fearful of being abused by so vile a company, held fast by the ancient women;
upon which two of the girls, with the women who sheltered them,
were committed by the sheriff to Bridewell, and with them two more for reproving them.
The manner of the Quaker women`'s reproof was thus: "`Well, sheriff Knight,
I see that though we cannot be permitted to serve God, these shall, to serve the devil.
Our peaceable meetings you seek to make riots,
and here you yourselves are rioting and revelling to a great excess.
Oh, these doings are a shame to Bristol,
which was once reputed a sober and well-governed city.
Now it is altered, for the profane, the drunkards, revellers, etc., are countenanced,
but those that fear God, are made a prey of;
surely God will visit heavily with his judgments for these crying sins.`"

--

Great havoc was made on Friends`' goods and stock
and furniture for their religious meetings,
even when held in silence.
When their persecutors enter a shop, though there is abundance of goods in view,
yet they break open chests, counters, etc., and from there take their money.
If no money is found, they take shop or household goods,
and of them generally double the value.
If any speak to them in reproof for their unjust proceedings,
they threaten them with a prison.
All this has to be endured by innocent men and women from wicked, cruel persons,
who rob and abuse them at their will.

At one time, several of these notorious informers, as they are often called,
came to one of the meetings, took out seven men and sent them to Newgate,
and then nailed up the doors upon fourteen men and eighty-seven women,
and kept them there nearly six hours.
While these were locked up, the afternoon meeting began at the other meetinghouse,
which those who attended were not permitted to enter,
but were obliged to meet in an open court,
where Tilly and his accomplices fastened them in
till between four and five o`'clock in the evening.
The sheriff came to their next meeting, and commanded the king`'s peace to be kept;
a serious woman present answered: "`We do keep the king`'s peace,
and we came here to keep our peace with the King of kings.`"
Upon this, he sent her and three more to Newgate.
Several youth under sixteen years old, were put in the stocks, which was contrary to law.
On the seventh of the month termed July, the meeting consisting chiefly of children,
was dispersed.
It was remarkable to see the gravity and manly courage with which some of the boys conducted,
keeping close to their religious meetings in the absence of their parents,
and undergoing, on that account, many abuses with patience.
There were then about one hundred and sixty in jail.
On the twenty-third, eight boys were put in the stocks two hours and a half.
On the thirtieth, in the afternoon, about fifty-five were at the meeting,
when Helliar beat many of them in a cruel manner
over their heads with a twisted whalebone stick;
few of them escaping without some marks of his fury on their heads, necks or faces.

On the third of the next month, Tilly, another informer,
beat many of the children with a small faggot stick, but they bore it patiently.
Others were beaten on the eleventh, and several sent to Bridewell.
Helliar beat Joseph Kippon, a young lad, about the head, till he was ready to swoon,
and sent eleven boys and four girls to Bridewell,
till a friend engaged for their appearance next day before the deputy mayor,
who endeavored by persuasions and threats to make them promise to come no more to meetings,
but in that respect the children were unmovable.
Wherefore they were again sent to prison, Helliar to terrify them,
// lint-disable invalid-characters
charging the keeper to provide a new cat-o’-nine-tails against next morning,
and he urged the justices next day to have them corrected,
but could not effect his cruel design.
The boys and girls were mostly from ten to twelve years old.
In this year there were confined in the two jails one hundred and thirty-six Friends,
very much crowded, and some of them were thrust into a dark dungeon,
where they were obliged to burn a candle constantly.

The fearlessness and constancy of those men and women,
in persisting in the discharge of what they believed to be their religious duty,
leads us to believe that they were favored with the
presence and support of their Lord and Saviour,
giving them the knowledge of his will,
and enabling them to endure hardship as good soldiers of Jesus Christ.
The innocent boldness and fortitude of children and the young people,
in following the example of their parents and older friends,
by keeping up their meetings for the public worship of God in the face of cruel persecution,
shows the sense they had of the importance of this religious duty,
and the obligation they felt to perform it, whatever might be the consequences,
even while debarred of the company of their fathers and mothers,
who were locked up in filthy dungeons.
It would be well for our young Friends to make themselves
acquainted with the history of the rise of their Society,
the doctrines and testimonies which their forefathers held,
and their firmness in maintaining them.
Follow them as they followed Christ, and He will make you pillars in his church,
and reward you with the white stone and the new name upon it.

In the year 1683,
one hundred and ninety-one Friends in Bristol were returned into the exchequer
on the statute of twenty pounds per month for absence from the national worship,
and their fines within that period amounted to sixteen thousand,
four hundred and forty pounds, or about eighty thousand dollars.

The prisoners in Newgate drew up an account of the outrages committed by the keeper,
and his bad language to them.
In the account they say:
"`At length it pleased the Lord to visit this keeper with his judgments,
which were dreadful, that he could not eat, nor sleep, but very little.
By day he would strive against it, and by drinking and keeping vain company,
endeavored to get ease for his troubled conscience,
and while the effect of the liquor was upon him in the daytime,
he would seem as if nothing was amiss.
At night he was in agony; then he would desire us to pray for him,
and wish that he had never seen the inside of the jail, saying it had undone him.
He desired several of us to forgive what he had done; to which we replied,
he should ask forgiveness of God, for we did forgive him.
Doctors were sent for, and he was bled; but he told them no medicine would do him good,
his distemper was another thing, and no man could do him good; his day was over,
and there was no hope of mercy from God for him.
Seeing him in this woeful condition, our hearts did pity him,
and desired if the will of the Lord was so, he might find a place of repentance.
Some of us had opportunities to speak with him,
and found that he had his senses and understanding well,
and we used such arguments as in Christian tenderness we thought best,
to persuade him out of his hardness and unbelief.
One of us said to him, we hoped his day was not over,
because he had a sense of his condition.
To which he answered: I thank you for your good hope, but I have no faith to believe;
and further said, Faith is the gift of God; so nothing would enter him,
but that his day was over, and there was no mercy for him.
In this miserable state he continued until the last of the Ninth Month,
and in the morning ended this miserable life.`"
They say: "`This is not made public, the Lord knows,
out of any revenge to the persons concerned, but as a warning to all.
Neither is it of any self-boasting,
as though by our own ability we had undergone all the cruelties inflicted on us;
but to Him that lives forevermore, do we ascribe the glory; by his power alone,
we have been supported.
And if this example of God`'s judgments on this man shall stop any from their evil courses,
we have our end.`"

The case of this poor man, as contrasted with the feelings of his prisoners,
furnishes a striking illustration of the fact that man`'s happiness
depends far more on the feelings of the mind than on outward surroundings.
There are many evidences that our early Friends often
enjoyed great comfort in the midst of their trials.

[.offset]
Joseph Besse says:

[.embedded-content-document]
--

It was a received observation among this people,
that during the time of their deepest suffering at Aberdeen,
they found the favor of God attending them, and his hand of providence preserving them,
so that not only their spirits were continued cheerful,
praising the Lord in the midst of their most grievous afflictions,
but also their bodies kept in health and strength, under the most unhealthy confinement,
beyond all human probability or expectation.
And even the malice of their adversaries became, against their own wills,
subservient to the spreading the doctrine of Truth, which they were called to bear,
and even their close imprisonment, on purpose to prevent their preaching,
was made a means of many blessed opportunities,
to promote what was the aim and design of their adversaries therein to hinder.
During this persecution,
their appointed meetings in that town were not only constantly held at the usual times,
but greatly increased in the number of persons attending them; for the women,
whose husbands were frequently shut up in prison, failed not, with their children,
to assemble themselves together for the worship of God at the stated time and place.
Which constancy of theirs, with the accession of other persons out of the country,
and the returning of the prisoners as soon and as often as any of them were released,
so far disappointed the persecuting magistrates,
that they were not able to prevent the holding of
any one of the public assemblies of this people,
during the whole course of this persecution.

Moreover, the sufferers, to their exceedingly great consolation,
did especially remark that, to encourage them to be faithful and constant,
the power and influence of the spirit of God was
in a more than ordinary manner manifest among them,
insomuch that their prison-house was turned into a house of prayer and praise,
and the aboundings of the love of God did enlarge their hearts,
and enable them to utter and sound forth his Truth
to the reaching and convincing of many souls,
and even to the amazement of their enemies;
until at length the hands of their persecutors became weakened,
some of them being removed by sudden death in an exemplary manner, and the priests,
George Meldrum, John Menzies and William Mitchell,
one of them by death and the other two by law,
deprived of their power and silenced from preaching; the lord of Hudda,
who had threatened by his own authority to pull down their meetinghouse,
turned out of his office of chancellorship; and James Sharp, the Bishop of St. Andrews,
so called, whom the magistrates of Aberdeen made use of as their principal instrument,
by his power in council, to crush the Quakers and suppress their meetings,
inhumanly and barbarously murdered by some wicked Presbyterians,
who waylaid him as he passed by in his six-horse coach, and assassinated him,
calling him an apostate, a betrayer and a persecutor.

This remarkable concurrence of so many unusual and extraordinary
events which befell the principal instruments of their sufferings,
was observed and acknowledged by those who in Christian
constancy and patience under oppression,
quietly expected the Lord`'s appointed time for their deliverance,
as manifest tokens of his displeasure revealed against their opposers,
and gradually tending to restrain the remainder of
men`'s wrath against the innocent sufferers,
and in due season to obtain their relief, which was shortly after effected.

--

Robert Widders was one who suffered much on account of his religious principles.
Thomas Camm says of him:

[.embedded-content-document]
--

I never saw him in the least dejected nor concerned, when his cattle,
corn and household goods were by wholesale swept away.
But he was one that knew well for what he suffered,
who enjoyed the sweetness of an eternal reward, in heavenly treasure a hundred-fold here,
together with the evidence of a crown in eternity.
Thus, Robert Widders had learned to be just as cheerful and content in the absence,
as in the abounding of those outward things with which he had been largely endowed,
and could, like upright Job, bless God who gave, and who permitted them to be taken away.
Frequently, when conversing respecting other Friend`'s trials, he would say:
"`It is well with all those that suffer for the cause of Truth; they are blessed,
they enjoy peace.
There is nothing that has come, but there has been need for it, and a service in it;
for all our sufferings work together for our good and the glory of God;
and the remainder of wrath will be restrained.`"
During the illness which immediately preceded his death,
he was resigned to the will of God, and dwelt on the Lord`'s mercies to his church,
saying, in the language of the prophet: "`The Lord shall comfort Zion;
He will comfort all her waste places; He will make her wilderness like Eden,
and her desert as the garden of the Lord; joy and gladness shall be found therein,
thanksgiving and the voice of melody.`"

--

A large number of Friends being confined in Newgate, in Bristol,
felt their minds drawn to address an epistle to their
brethren at their approaching Yearly Meeting in London,
from which the following is taken, dated seventeenth of the Third Month, 1684:

[.embedded-content-document]
--

The time being near when Friends may be together,
we thought it might not be unwelcome to you to hear from us.
The Friends who have been long prisoners at Bridewell,
the keeper removed here on the second of this month,
so that the number in this jail is above one hundred, crowded in dark, damp,
dungeon-like holes,
many in a place called "`Paul`'s,`" where never any
before were put to lodge that we heard of.
These things cry aloud, but many hearts are hard, and those who might remedy,
will not regard, but impute it wholly to our fault.
We mention these things to inform how we are, rather than to complain.
Indeed, God has been so good to us, and still is so,
that it does outbalance all these light afflictions.
He has given health, and preserved it in several appearances of very great danger,
which mercy is even to a wonder.
He has given comfort, content, unity, peace and love among us greatly,
and by his fatherly care, has so provided always for us, that we have had no lack.
For all which mercies we desire you with us to praise the Lord,
and to pray unto Him for us here, that God would forever keep us in faithfulness to Him,
that we may become even as monuments of his mercy, that He who alone is worthy,
who is all, and does all, may have all the honor, praise and renown, now, henceforth,
and forevermore.

Within this week we are pulled and haled out, and not permitted to meet together,
the keeper saying he has orders for it from his masters,
and so we are thrust and locked in several places in heaps.
But in this is our rejoicing, that they cannot keep God from us,
by whose power we are kept in patience to suffer these things
from the hands of men to whom we never did any harm,
to whom God grant repentance before his anger breaks forth in an overflowing scourge,
and there be no remedy.
Blessed be God, we are well,
and our love is to all our dear friends in the holy Truth of God, whose lives,
liberty and peace, we pray God preserve.
In your approaches to the throne of grace, forget us not;
that is the greatest good we can do one another, who have none in heaven but the Lord,
nor desire any on earth but Him only.

--

These Friends were kept prisoners in Bristol another year,
and when the Yearly Meeting in London was drawing on,
they again addressed them in the Fourth Month, 1685:

[.embedded-content-document]
--

[.salutation]
Dear friends and brethren.

This being the season wherein you may be glad to hear from one another
as fellow-members of that living body of which Christ Jesus is Head,
we thought you might hear from us, who, though still in bonds,
are yet in good satisfaction,
knowing that affliction is that which all the righteous in all
ages ever passed through on their way to God`'s heavenly kingdom.

--

Elizabeth Stirredge, with some other Friends, were taken from their meetinghouse,
after their persecutors had put faggots at the door, and threatened to burn it,
and then committed to Ilchester Jail.
It was a most dismal place, where they had nothing to sit or lie upon, but the damp,
cold ground.
In this comfortless condition, some of their Friends, prisoners in an adjoining room,
put through the grates four dust or chaff pillows, two blankets, and a little straw,
whereon they laid down, like a flock of sheep in a pen.
It was in a very cold winter, but most of them took their rest sweetly.
When they laid down, Elizabeth Stirredge says, this consideration came into her heart:
"`Lord, you know for what we are exposed to this hardship;
it is because we cannot betray our testimony, nor wrong our conscience,
nor deal treacherously with our souls.
Lord, be our comfort in this needful time;
for it is your presence makes hard things easy, and bitter things sweet;
and you have sweetened the waters of a bitter cup.
Oh, you, Physician of value, who can strengthen both soul and body,
be with us this night, and all the nights and days that we have to live in this world.`"
Her heart was then filled with the Lord`'s mercy and comfortable presence,
insomuch that she could have sung aloud of his goodness,
and blessings bestowed upon them, but looking over her fellow-prisoners,
and seeing them asleep, she forebore.

Many people came to the prison door in the morning,
to see how many of them were dead from their hard fare;
some said they were sure that she was dead,
for she looked as if she would not live until the morning.
Finding them all well, they confessed and said: "`Surely we were the people of God,
if there were any.`"
It being First-day, they had a meeting in the prison, to which many Friends came,
and the presence of the Lord was with them,
and filled their hearts with joy and gladness.
Elizabeth Stirredge says: "`I was constrained to praise the Lord, and magnify his power,
and to testify in the hearing of many,
that we were so far from repenting of our coming there,
that we had great cause to give glory,
honor and praises to the Lord God of heaven and earth,
because He had found us worthy to suffer for his name and Truth.
His presence was with us, and sanctified our afflictions,
and made the prison like a palace to us;
and we would not change our state for all the glory of the world,
if it were offered unto us.`"

Some years previous to this imprisonment, when persecution was severe,
and they were turned out of their meetinghouse,
many who became weary with standing in the street, consulted about meeting in private,
and told those who could not conform to their proposal,
that if they would come and meet with John Story and some others in private,
they might sit together in quietness, and wait upon the Lord,
and enjoy the benefit of meeting, which would be better than standing in the street,
to be hurried and thronged together, and had hardly any time to wait upon the Lord.
But Elizabeth Stirredge and others, could not join this human policy to escape suffering,
but believed it to be their duty to support their testimony for the Truth,
in the face of their bitter enemies; and John Story and his adherents parted from them,
and left them, as it were in the open field to endure reproach.
Their persecutors said: "`Here are the fools, the wise men are gone.
They have more wit than to meet so near the justice`'s house,
to aggravate him and ruin themselves;
do you think to stand against all the powers of the earth?
A company of silly fools!`"
If any should say, was this a discouragement to you, Elizabeth Stirredge answers: "`No;
our fear and zeal towards God was increased;
and I can say to the praise and honor of his everlasting name,
my cries and supplications ascended night and day unto Him,
for strength to stand in my lot and testimony,
and that I might be able to hold out to the end.
And forever blessed be the Lord, He strengthened my weakness,
and made the weak as strong as David, and afforded his living presence among us,
to our great comfort.`"

When George Whitehead was imprisoned at Bury, St. Edmonds in 1655,
the jailer treated him and his friends with great cruelty,
because they would not buy beer of him.

Yet, in the midst of these atrocities,
the spirits of the sufferers were exalted by the sustaining power of God,
and enabled to soar above that region in which the
persecution of men or devils had power to operate.
On one occasion, George Whitehead, with three more Friends, were put into a dungeon,
four yards under ground, by this inhuman jailer and his turnkey,
because they would not desist from crying against the wickedness that surrounded them.
He describes the place by saying:

[.embedded-content-document]
--

It was very dark, and but a little space at the bottom,
and in the midst thereof an iron grate, with bars above a foot distant from each other,
and under the same, a pit or hole, we knew not how deep;
but being warned thereof by a woman that saw us put down, and pitied us,
we kept near the sides of the dungeon, that we might not fall into the said pit,
and there we were detained near four hours, singing praises to the Lord our God,
in the sweet enjoyment, and living sense of his glorious presence,
being nothing terrified nor dismayed at their cruelties;
but cheerfully resigned in the will of the Lord,
to suffer for his name and Truth`'s sake.

--

"`I am still truly humbled and thankful,`" says George Whitehead,
when many years afterwards he reverted to these fiery trials:
"`I am still truly humbled and thankful to the Lord our God,
in remembrance of his great kindness to us,
how wonderfully he supported and comforted us through and over all these our tribulations,
strait confinement and ill usage, and preserved us in bodily health.`"
And speaking of the painfulness of the circumstances which attended their imprisonment,
in regard to the filth and abominations of the place in which they were kept, yet,
says he: "`The Lord by his power so sanctified the confinement to me,
that I had great peace, comfort and sweet solace;
and was sometimes transported and wrapt up in spirit, as if in a pleasant field,
having the fragrant scent and sweet smell of flowers, and things growing therein.`"

He says that the happiness enjoyed by him and his companions, surprised the prisoners.
Speaking of the merciful support and consolations of God,
"`in the comfortable enjoyment of his glorious Divine power and presence,`" he remarks,
"`Several of us have often been made to sing aloud in praise to his glorious name; yes,
his high praises have been in our mouths,
oftentimes to the great amazement and astonishment of the
malefactors shut up in the same ward with us.
When walking therein, our hearts have been lifted up in living praises to the Lord,
often for several hours together, with voices of melody.
O, the sweet presence and power of the Lord our God; how precious to be enjoyed,
in prisons and dungeons!
O, my soul, still bless the Lord, and forever praise his excellent name, for the true,
inward sense and experience you have often, and long had, and still have,
of his Divine power, and unspeakable goodness!
Glory and dominion be to our God,
and to the Lamb that sits upon the throne forever and ever!`"

William Leddra, the day before he was executed in New England,
wrote to his friends a letter, in which he says:
"`The sweet influences of the morning star,
like a flood distilling into my innocent habitation,
has so filled me with the joy of the Lord in the beauty of holiness,
that my spirit is as if it did not inhabit a tabernacle of clay,
but is wholly swallowed up in the bosom of eternity, from which it had its being.`"

Well might he exclaim, under such a glorious experience:
"`What can the wrath and spirit of man, that lusts to envy;
aggravated by the heat and strength of the king of the locusts,
which came out of the pit,
do unto one that is hidden in the secret places of the Almighty?--or unto
them that are gathered under the healing wings of the Prince of Peace?--under
whose armor of light they shall be able to stand in the day of trial.`"

A similar feeling animated the fathers in the church who were concerned
to advise and comfort their younger Friends when under trial.
Thomas Ellwood was carried a prisoner to Oxford,
and there he received a loving epistle from his dear friend Isaac Penington,
who thus saluted him:

[.embedded-content-document.letter]
--

Great has been the Lord`'s goodness to you,
in calling you out of that path of vanity and death,
wherein you were running towards destruction,
to give you a living name and an inheritance of life among his people;
which certainly will be the end of your faith in Him, and obedience to Him.
And let it not be a light thing in your eyes,
that He now accounts you worthy to suffer among his choice lambs,
that he might make your crown weightier, and your inheritance the fuller.
O, that that eye and heart may be kept open in you, which know the value of these things!
And that you may be kept close to the feeling of the life,
that you may be fresh in your spirit in the midst of your sufferings,
and may reap the benefit of them; finding that pared off thereby,
which hinders the bubblings of the everlasting spring,
and makes unfit for the breaking forth and enjoyment of the pure power!
This is the brief salutation of my dear love to you,
which desires your strength and settlement in the power,
and the utter weakening of you as to self.
My dear love is to you.

--

So also George Fox in a letter addressed to Friends in Ireland,
who had been under great sufferings,
tells them that "`the Lord is able to preserve and keep you,
and to save to the uttermost, and none can hurt so much as a hair of your heads,
except He permit it to try you, for he upholds all things in heaven and earth.`"

Edward Burrough also issued a letter of encouragement
to those who were imprisoned or otherwise persecuted,
in which he says:

[.embedded-content-document]
--

It is true the gates of hell at this time seem to be open against us,
and we are a people like to be swallowed up of our enemies,
and floods of wickedness seem to overflow,
and the waves of the great sea seem to be void of mercy,
and the hope of our adversaries is to extinguish us from being a people,
and to destroy us from the face of the earth;
and the hands of our persecutors are highly exalted at this day,
as though all that we have done for the Lord,
by our labors and travels should now be made of none effect.

Well, dear brethren, though it be thus, yet our God can deliver us,
and confound our adversaries; and we can appeal unto our God,
and can spread our cause before Him;
and He knows that our sufferings and our afflictions are altogether unjust, and unequal,
and unrighteous, and that our persecutors do afflict us out of their envy,
and without any just cause administered unto them by us; our God knows it,
angels and saints know it, that we are at this day a persecuted people,
for religion`'s sake; and this our present affliction is not any just punishment,
either from the justice of God, or the justice of men.

--

Their confidence in the Divine power to deliver them and confound their adversaries,
was not misplaced.
Although judges and magistrates, bishops and clergy,
exerted themselves to root out the Quakers; and numbers of unprincipled, lying informers,
were encouraged to make a prey of the Quakers; yet,
by their constancy in acting and suffering,
they wearied out the most determined hostility;
till at length even their bitterest enemies became tired of their own fruitless efforts
to repress them and to counteract the dissemination of their religious tenets.
And notwithstanding the iron hand of tyranny and persecution was
long stretched forth against this people with relentless severity,
they bore its inflictions with a meekness,
patience and fortitude which nothing could subdue;
their hearts being so powerfully influenced by the love of God,
that they were made willing to part with all things, even with life itself,
for his name`'s sake.

Not only did the Quakers weary out opposition,
but their Christian conduct and patience under suffering,
not infrequently led to the conversion of soldiers, constables, jailers,
and even of informers, who were the instruments of carrying the cruel laws into effect.
Their exemplary conduct in private life also won over many
to the consideration and adoption of their principles;
so that during the whole reign of Charles II, in which, with a few intervals,
a heavy persecution prevailed, the numbers of the Quakers increased greatly.

Christopher Story,
after relating the efforts that were made in the part of England where he resided,
for about three years, to break up our meetings,
impoverish our families and imprison our bodies, adds:
"`And yet I can say all things wrought together for good to them that loved God;
for in this time of persecution we lost but one man, and several were added,
and we had glorious meetings.`"

In a hot time of persecution,
Francis Howgill gave forth a paper for the encouragement of his friends,
in which he declared what it had pleased God to reveal
to him when his spirit was waiting on the Lord:
"`Though the powers of darkness and hell combine against this people,
and the jaws of death open its mouth, yet I will deliver them and lead them through all;
I will confound their enemies; I will take their enemies;
I will hurl them here and there, as stones hurled in a sling.`"

The predictions of the prophet Isaiah seem to have
been fulfilled in the experience of our early Friends:
"`The Lord God will help me; therefore shall I not be confounded;
therefore have I set my face like a flint, and I know that I shall not be ashamed.`"

The prediction of Francis Howgill that the Lord would confound the enemies of his people,
was often fulfilled in particular cases, as well as in a general way.
One colonel Robinson, a severe persecutor, sent to a neighboring justice,
desiring that he would go with him "`fanatic-hunting`"
(meaning the disturbing of Quaker meetings).
On the day he intended to go, he went into a field where his bull was kept,
and having formerly accustomed himself to play with the animal,
he began to fence at him with his staff, as he used to do.
But the bull ran at him fiercely, struck his horn into his thigh,
and threw him over his back.
When he came to the ground, the bull continued to gore him,
and the men were forced to bring mastiff dogs to beat him off.
Robinson was taken up and carried home,
but was so grievously wounded that he died soon after.
It was a sad circumstance that he should be cut off while harboring
such a malicious intent as that of persecuting his sober neighbors.

Francis Howgill died in prison, where he spent much time, for his faithfulness to his God.
During his sickness he was often heard to say that he was content to die,
that he was ready,
and that he praised God for the sweet enjoyments and refreshments
he had received in his prison-house beds.

Some Friends who were imprisoned at Montrose, in Scotland,
addressed a remonstrance to the magistrates, in which they say: "`As for us,
we are well contented to stay here, until the due time of our deliverance come,
and our expectations (be it known to you) are neither from the hills nor from the mountains,
but from God alone.
Our case is committed to Him who judges righteously!
We are, as regards our testimony, and for its sake, well contented, well pleased,
well satisfied to be here; our bonds are not grievous to us;
glory to the Lord forever!--who has not been, who is not lacking toward us.`"

It is recorded by that able minister of Christ Jesus, John Burnyeat, who died in 1691,
that the Lord`'s condescending goodness and mercy was very great to Friends,
and to the meetings of Friends in that day; which would be so no less to us,
were we as inward and diligent in seeking after Him and his life-giving presence,
whose hand is not shortened, nor his mercy withdrawn, but who is the same yesterday,
today and forever.
John Burnyeat writes:

[.embedded-content-document]
--

O, the joy,
the pleasure and the great delight that our hearts were
overcome with many times in our reverent and holy assemblies!
How were our hearts melted as wax, and our souls poured out as water before the Lord,
and our spirits as oil, frankincense and myrrh,
offered up unto the Lord as sweet incense,
when not a word outwardly in our assemblies has been uttered!
Then did the Lord delight to come down into his garden
and walk in the midst of the bed of spices;
and he caused the north wind to awake, and the south wind to blow upon his garden,
and the pleasant showers to descend for the refreshing of his tender plants,
that they might grow more and more.

--

[.offset]
George Whitehead records in his Memoirs:

[.embedded-content-document]
--

I remember in those days,
Friends in the west part of Cumberland kept their meetings outdoors,
at a place on the common called Pardsay Cragg,
not then having convenient house room to contain the meetings.
It was very cold, stormy, snowy, and sleety weather,
at one of the meetings which I had there on the said Cragg;
but as there are several sides of it, where sheep may shelter from the wind and storm,
so Friends commonly took the same advantage to meet on the calmest side.
And truly several good and blessed meetings I had at the said Pardsay Cragg, outdoors,
both in the winter and summer times, and some within doors,
since our friends got a meetinghouse built there.

Likewise our friends of Strickland and Shapp, and that side of Westmoreland,
kept their meetings for some years on the common, both winter and summer,
until they got a meetinghouse built at Great Strickland.
Our friends in those northern counties were greatly
enabled to bear the cold and all sorts of weather,
when they had their meetings on the commons and mountainous places,
for several years at first.
It rained most of the time at some meetings, and we have been very much wet;
yet I do not remember that ever I got any hurt thereby,
the Lord so preserved and defended us by his power; blessed be his name,
who enabled me and many others to stand and to bear various kinds of storms and winds.

--

Much of the suffering inflicted on Friends in their early days,
had been on old acts made for the suppression of popery and other purposes,
which were most unjustly and cruelly wrested from their original intent,
and used to persecute a harmless people,
who had become obnoxious to the intolerant spirit of the age.
The parliament which had assembled under the authority of Charles
II seemed to be animated with a furious zeal for episcopacy,
in which political feeling had probably a greater share than any regard for religion.
An act was passed inflicting penalties on those who attended any meetings for worship
other than those held in conformity to the usages of the established church of England,
and for the third conviction under it the punishment of banishment
for seven years to the American provinces was the penalty attached.
The proceedings under this act show in a remarkable manner
how the Lord`'s protecting care was extended to his people,
and how vain are the efforts of wicked men to thwart his will.

Other dissenters generally succumbed to the violence of the party now in power,
and either gave up their meetings altogether,
or resorted to subterfuges to escape detection and conviction,
or fully conformed to the forms required by law.
But it was not so with Friends,
who stood boldly forth in the avowal and practice of their religion,
and braved all that the wrath of man could accomplish,
to maintain a conscience void of offence toward God and man.

In the Eighth Month of 1664, eight Friends were tried at Hertford, before judge Bridgman,
under this act.
The witnesses gave in evidence that they found these persons at
certain times and places assembled (this being the third time),
above five together, under color and pretence of religion,
but admitted that they neither heard them speak any words,
nor saw them do anything at their meetings but sit still.

The grand jury,
supposing that no law could be intended to punish
men for simply meeting together and sitting still,
nothing being said, or apparently done, returned the bill ignoramus.
But in those days,
it appeared to be the intent of the judges--who held
their appointment direct from the crown,
and were liable to be dismissed at its pleasure--to
carry out the wishes of the party in power,
rather than to administer justice,
and hence judge Bridgman angrily reprimanded the jury for their course:
"`My masters (said he) what do you mean to do?
Will you make a nose of wax of the law, and allow the law to be baffled?
Those who think to deceive the law, the law will deceive them.
Why do you not find the bill?`"
In our day and country, no judge would dare address a grand jury thus,
for not finding a true bill against those whom they believed to be guilty of no crime;
but the claims of justice and equity were but little regarded then,
especially when dealing with the hated Quakers.
The jury, acting under the dictation of the court again took up the case,
and to the gratification of the judge, found a true bill.

Four of the prisoners were then arraigned at the bar, who pleaded "`Not guilty,`" saying,
"`they had not transgressed any just law,`" upon which the judge replied:
"`But you have transgressed this law (having the act in
his hand) and you have already been twice convicted.
If you be now again found guilty, I must pass sentence of transportation upon you;
but if you will promise to go no more to any such meetings,
I will acquit you for what is past:
what say you?--this favor you may receive before the jury be charged with you.
Will you promise to meet no more?`"
The four answered with one accord, "`We can make no such promise.`"

The jury being sworn, the former evidence was repeated before them,
and the judge gave them his charge, in which he told them:
"`You are not to expect a plain punctual evidence against
them for anything they said or did at their meeting,
for dumb men may speak to one another, so as they may understand each other by signs:
and they themselves say that the worship of God is inward in the spirit,
and that they can discern spirits, and know one another in spirit.
So that if you find or believe in your heart that they were
in the meeting under color of religion in their way,
though they sat still only, it was an unlawful meeting;
and their use and practice not according to the liturgy of the church of England;
for it allows and commands when people meet together in the church,
that Divine service shall be read,`" etc.
Under such instructions the jury were not long in bringing in a verdict of guilty.

The names of the four prisoners being called the judge asked them,
"`What can you say for yourselves that judgment of transportation should not pass,
or be given against you?`"
They replied: "`We are innocent, and have transgressed no just law;
if we must have that sentence, we give up our bodies freely into the hands of the Lord;
the will of the Lord be done.`"
"`Have you nothing more to say?`"--said the judge.
"`Nothing but that we are innocent, we have wronged no man,`" replied the prisoners.
"`Then hearken to your sentence,`" said the judge.
"`You shall be transported beyond the seas, to the island of Barbados,
there to remain seven years.`"

In [.book-title]#Besse`'s Sufferings of Friends#, it is stated that the jailer at Hertford, acting,
it seems, under the order of the sheriff,
made a contract with a master of a vessel to carry seven Friends, who were prisoners,
to the West Indies.
Various difficulties occurred previous to their being delivered on board the vessel;
and when at length they were brought to the ship,
the master gave them permission under his hand to go ashore,
and to return again when he should require them.

[.embedded-content-document]
--

On the first of October, +++[+++Eighth Month--the month in which the above letter is dated],
the master sent for them to come on board, which they did;
and the ship sailed down the river as far as the Red-house near Deptford;
when a sudden turn of the wind drove her back to Limehouse,
where the prisoners were again set ashore.
On the sixth, the ship again weighed anchor with wind and tide fair;
yet could not the seamen, with their utmost application, make this ship sail,
but they were obliged to anchor again about a stone`'s
cast from the place they lay at before;
so that some of the mariners were amazed, and said, "`We shall never get out of England,
while these men are on board!`"
So they set them ashore the third time.
On the eighth, they sailed again, and went down to Greenwich;
when a sudden storm obliged them to cast anchor again to secure the ship,
and the prisoners were sent on shore the fourth time.
On the tenth, they were ordered on board the fifth time, and sailed again;
when the ship was with much ado kept from running aground: they +++[+++however]
set the prisoners ashore again at Blackwall, and she went down the same tide to Gravesend.
The prisoners followed, and by the master`'s order some tarried there,
and others came back to London, till the twenty-eighth;
when they were ordered aboard a sixth time, and the ship sailed that night to Leigh Road,
where they cast anchor; but before morning the wind turned strong against them,
so that they lay there two days and three nights.
On the thirty-first, they sailed to the North Foreland,
and cast anchor again till the next day.
At night the master set them ashore, and directed them to Deal,
where he met them altogether; and before several witnesses declared,
that though they had followed the ship so long, yet he was resolved not to carry them,
and gave them a certificate in writing as follows:

"`Whereas, there were seven men, called Quakers, brought on board my ship,
called the _Anne_, of London, by William Edmonds, jailer of Hertford, namely: Nich.
Lucas, Henry Feast, Henry Marshall, Francis Pryor, John Blendall,
Jeremiah Herne and Samuel Traherne,
all of which have continued waiting upon my ship from London to Deal,
from the 14th day of September last till this day;
and I seeing Providence has much crossed me hitherto,
whereby I perceive that the hand of the Lord is against me,
that I dare not proceed on my voyage to carry them, they being innocent persons,
and no crime signified against them worthy of banishment;
and that there is a law in force that no Englishman shall
be carried out of his native country against his will;
and also my men refuse to go the voyage, if I carry them,
which will be much to my hindrance, men being very scarce by reason of the long press.
For these reasons, therefore, and many more, I will not carry them.
These are, therefore, to certify any person or persons that shall question them:
that they did not make an escape, but I put them on shore again to go where they please.
All this is certified under my hand, this tenth of November, 1664.`"

[.signed-section-closing]
+++[+++Witnessed by four persons].

[.signed-section-signature]
Thomas May

Being thus set at liberty, they returned to London, and then to their own homes;
and they sent a letter to the king and council, stating the circumstance,
and accompanied it with a copy of the ship-master`'s certificate.
This letter being read at the council board produced an order; which,
after setting forth the fact of their having been put on board the aforesaid ship,
pursuant to their sentence of transportation,
and having been by the master set ashore at the Downs,
"`Leaving them at liberty to go where they please;
and it appearing to be matter of contrivance and design between
the said master and the persons before mentioned;`" it was ordered
that the high sheriff do again apprehend and secure them,
"`until means of transporting them can be made by some shipping bound unto those parts.`"

By this order they were again committed to prison, and remained there seven years,
until discharged by the king`'s proclamation.^
footnote:[[.book-title]#Besse`'s Sufferings#, Vol.
I+++.+++ p. 246-248.]

--

[.offset]
A letter from Ellis Hookes, who acted as a recording clerk for Friends, to Margaret Fell,
says:

[.embedded-content-document]
--

At Hicks`'s Hall, four women were sentenced to eleven months`' imprisonment or £40 fine,
having husbands;
about twelve or thirteen men and women were sentenced
to be transported to any of the foreign plantations:
and at the Old Bailey about forty-six Friends were called,
and sixteen of them would not answer them (not guilty) according to their form,
and so yesterday were sentenced by the recorder; those that had husbands,
to Bridewell for twelve months or £20 fine, and the men were sentenced to Barbados,
and the women-maids to Jamaica.
About sixteen last Seventh-day pleaded, and were tried by a jury,
which jury were twice sent out, not agreeing in their verdict:
the judges (Hide and Keeling) talked much to them; but at last they could not agree,
six of them standing very much for Friends.
Some of them pleaded notably on the behalf of Friends, and said,
they did not deny but that they were guilty of meeting at the Bull and Mouth;
but they said, they were not guilty of the fact charged against them, namely:
that it was a seditious meeting; and one of the jury said:
the witnesses were not competent persons (being common
drunkards) to swear against honest men.
So the judges were very angry with them,
and bound them in £100 bond a-piece to answer it at the king`'s bench bar.
The four jailers at Newgate were all the witnesses that came in against Friends, +++[+++also]
one of the marshal`'s men.

--

At one time in 1665 there remained in Newgate prison more than
one hundred and twenty persons under sentence of transportation,
whom the sheriffs knew not how to get rid of; for the masters of ships,
persuaded of the men`'s innocence, generally refused to carry them,
and the increasing pestilence confirmed them in their refusal,
it being esteemed by them and many others as a judgment
on the nation for its persecuting laws.
To remedy this,
an order was made that no merchant-man should go
down the river without a pass from the admiral,
and this would be given to no master going to the West Indies,
but on condition of his engaging to carry some Quakers.
Remonstrances were vain.
At length the sheriff found a man named Fudge,
who agreed to carry the prisoners to Jamaica, and in pursuance thereof,
fifty-five were taken out of Newgate, put in a barge,
and carried down the river to his ship, lying a little below Greenwich.
When they came to the ship`'s side, the master being absent,
the seamen refused to assist in forcing them on board,
and the prisoners were unwilling to be active in their own transportation.
The turnkey and officers used high words to the seamen,
insisting that the prisoners were the king`'s goods,
and that they ought to be assisted in putting them on board.
The commander of the soldiers called to the seamen to assist, but few of them regarded.
Then the soldiers in the barge laid hold on the prisoners, dragging some,
kicking and punching others, heaving many by the legs and arms,
and in this manner got them all on board in about an hour`'s time,
being thirty-seven men and eighteen women.

On board, the men were all thronged together between decks,
where they could not stand upright.
The master of the ship being in the meantime arrested for debt, and cast into prison,
the ship was detained so long in the river,
that it was about seven months before they reached the Land`'s End;
and in the intermediate time, the pestilence breaking out in the ship,
carried off twenty-seven of the prisoners.
At last, another master being procured, the vessel sailed from Plymouth,
and was the next day taken by a Dutch privateer off the Land`'s End,
and carried to Haven in North Holland.
When the commissioners of admiralty there understood that
they would not be exchanged as prisoners of war,
they set them at liberty, and gave them a passport and certificate:
"`That they had not made their escape, but were sent back by them.`"
From Haven they made their way to Amsterdam,
where they met with a kind reception from their friends,
who provided them with lodging and clothes,
their own having been mostly taken from them by the privateer`'s crew.
From hence they all returned to England, except one, who being a foreigner,
stayed in Holland.
By these means the exiles were delivered,
and the design of the persecutors was frustrated by the ordering hand of Divine Providence.

Friends were not deficient in showing the authorities the evil of their actions,
and in informing them of the evils that would come
upon those who were guilty of such cruelties.
The plain and fearless manner in which they plead with their rulers is
well shown in an address by William Bayley (one of their preachers),
to the king and parliament.
He tells them that to persecute and afflict an innocent and harmless people,
was not the end for which the Lord permitted them to occupy the seat of
government--that they had committed their cause to the Lord,
and that no weapon formed against them should ever prosper.
He tells them that the innocent blood of the sufferers shall be required at their hands,
and reminds them of the saying of Christ,
that it were better a millstone be hanged about a
man`'s neck and he drowned in the depth of the sea,
than that he should offend one of the little ones that believe in Him.
In parts of his appeal he speaks with the authority
of one of the ancient prophets of Israel:
"`Thus says the Lord God, that made heaven and earth,
Let my innocent people alone and touch them not any more as you have done;
for they are mine, and I have called them, and chosen them and redeemed them.
I will preserve them and deliver them.
I will rebuke kings and rulers for their sakes.`"

After Charles the Second had ascended the throne,
from which his father had been driven by his exasperated subjects,
and made to pay the penalty of death for his assumption of unlawful power,
he seemed disposed partially to fulfill the promise made by him at Breda,
of "`liberty of conscience.`"
Richard Hubberthorn, having obtained an interview with him, Charles said to him:
"`None should molest Friends,
so long as they lived peaceably,`" promising this on the word of a king,
and telling him Friends might make use of his promise;
and upon the intercession of several Friends,
but more especially at the solicitation of Margaret Fell,
he set at liberty about seven hundred Friends, who had long been suffering in prison,
under various frivolous charges,
during the protectorship of Oliver Cromwell and his son Richard.

The parliament,
freed for a short time in some measure from the malevolent instigations of the clergy,
also manifested a disposition to listen to the voice of truth and justice,
and admitted some of the despised Quakers to appear in the house of lords,
and set forth the reasons why they could not frequent the places of the national worship,
pay tithes to the priests, nor take an oath.
They were heard with attention and moderation,
and the work of securing their rights advanced so far that an order was
drawn up for permitting the Society the free exercise of their worship,
and only needed the royal signature to make it a law.
This was in the year 1660, seventeen years after George Fox had been first sent forth,
and there was a reasonable ground to believe that the cruel sufferings to which
Friends had been subjected since he first began to promulgate their faith,
would be materially mitigated, if not altogether stopped.

King Charles, though a dissolute, was a kind-hearted man, and some of the royalists,
knowing that several of the predictions of the Quakers
concerning the downfall of the commonwealth,
and the miserable end of their persecutors under it, had been strikingly fulfilled,
entertained so strong a feeling of respect for their religious character,
as to have addressed to them several queries, as to the king`'s right to the crown,
and their sense as to his reign and government being blessed, and established.
These queries had been answered by Edward Burrough, who, among other things,
sought to impress the court and men in power with a conviction,
that the reign and government would be blessed or not,
according as it avoided the evil courses that had brought
the reign of Charles`' father to a bloody end,
and destroyed the commonwealth, especially persecuting for conscience`' sake.
This, with the unexceptionable lives and patient endurance of Friends,
had undoubtedly made not a little impression,
and all dissenters waited in expectation of an act securing liberty of conscience.

During this interval of repose, the meetings of Friends increased greatly,
many resorting to them in search of the Truth, and some out of curiosity,
and great convincements took place, so that the number of members was largely increased.
George Fox says: "`The everlasting power of the Lord was over all, and his blessed truth,
life and light shined over the nation,
and great and glorious meetings we had and very quiet; and many flocked unto the Truth.`"

But the time for a permanent release from persecution had not yet arrived,
and a pretext was soon found for commencing it with increased rigor and cruelty.
Among the many restless and dissatisfied people, who were then living in Great Britain,
were a few zealots,
who professed to believe that the time had come to
establish the reign of Jesus on the earth,
and who were, therefore,
opposed to the settlement of Charles on the throne of his ancestors.
The millennial kingdom they proposed to set up was styled by them a Fifth-monarchy,
which was to be under the absolute control of the Prince of Peace, but which,
absurdly enough, they declared themselves authorized to inaugurate by force of arms.
Accordingly, having made preparation for an insurrection in London, about sixty of them,
completely armed, and headed by a man of the name of Venner, a wine cooper,
sallied forth into the streets, in the night of a First-day, and proclaiming King Jesus,
strove to incite the people to rebellion, and to drive out the king and his officers.
The whole city was quickly in an uproar.
The drums were beaten, and the cry "`arm, arm,`" resounded in every quarter.
Being attacked by the trained bands, the deluded insurgents took possession of a house,
and defended themselves in it, until the greater part of them were killed.
The few survivors being seized, were tried, condemned and executed.
Sewell, in his short allusion to the insurrection, says:
"`The trained bands appeared in arms, and all was in an uproar,
and both the mob and soldiers committed great insolencies for several days.`"

The wild attempt of the Fifth-monarchy men produced
great disturbance throughout the nation,
affording a pretext for the rude and cruel soldiery to commit
violence on the persons of whoever they chose to assault,
so that for some time it was dangerous for any,
not connected with the court and its party, to go abroad.
When the insurrectionists were about to be executed,
they voluntarily cleared Friends of any participation in their councils,
leaving it as their dying testimony,
that they had no connection with or knowledge of their plot.
Nevertheless, they fell under great suffering on account of it,
being abused by the soldiers and populace, their houses forced open and ransacked,
their meetings broken up, and they dragged out of them, as well as out of their houses,
and shut up in jails, until several thousands of them were crowded into prison.

Taking advantage of the alarm and tumult excited by the insurrection,
those who hated Friends,
and those who cherished a desire to retaliate on the Presbyterians and Independents
for the violence and loss they had formerly suffered at their hands,
and who likewise were determined to put down all dissent from the established church,
procured the issuing of an order in council against the meetings of +++[+++those deemed]
sectaries, in great numbers, or at unusual times;
and subsequently a proclamation came forth, "`Forbidding Anabaptists, Quakers,
and Fifth-monarchy men to assemble or meet together, under pretence of worshipping God,
except in some parochial church or chapel,
or in private houses by persons therein inhabiting.`"
All meetings in any other place, were declared to be unlawful and riotous.

In order to escape the charge of disregarding the promise made by the king when at Breda,
by which he bound himself and his government, that "`No man should be disquieted,
or called in question,
for differences of opinion in matters of religion,`" it was pretended
that all non-conformists were dangerous from their political opinions,
and the laws made in former reigns for the suppression of Jesuits and of popery,
were revived and made use of to harass and distress them.
It was also required that all persons should, at the option of any magistrate or judge,
be obliged to take the oath of allegiance.

From the storm thus raised, most dissenters shrunk,
discontinuing their meetings in most cases,
and resorting to various subterfuges to screen the
few they held from the operation of the law.

Friends, however, could make no compromise,
nor shrink from the performance of a duty so imperative as they considered
the assembling for the purpose of Divine worship to be.
They knew themselves to be innocent of any treasonable or sinister designs,
and felt that they were called on by the King of kings to show their allegiance to Him,
by obeying his law written in the heart,
however the commandments of men might stand in opposition to them,
or cruel men tax their cunning and malice to inflict suffering on them therefor.
As, therefore, they dared not withdraw from the attendance of their meetings,
nor yet take any oath,
they thought it right to put forth a declaration against all plots and insurrections,
clearing themselves of the charges brought against them,
and setting forth the great persecution to which
they were subjected on account of their religion.
George Fox and Richard Hubberthorn,
having drawn up a document on behalf of their fellow-members, sent it to the press.
It was there seized by some in power,
who wished to deprive them of all opportunity for vindicating the hated Quakers.
They were not, however, to be deterred from their purpose by this arbitrary act,
but quickly preparing another copy, they succeeded in getting it printed;
and having sent a copy to the king, they speedily had it distributed over the country.
It was styled __A Declaration From the Harmless, Innocent People of God Called Quakers,
Against all Sedition, Plotters and Fighters in the World,
for Removing the Ground of Jealousy and Suspicion
From Both Magistrates and People in the Kingdom,
Concerning Wars and Fightings.__
But this availed little or nothing in staying the rage of their enemies.
Besse states:

[.embedded-content-document]
--

Few or no counties escaped this general persecution;
but in consequence of the proclamation,
the Quakers (so called) were everywhere taken up in crowds,
violently haled by soldiers or peace officers before the justices,
who generally tendered them the oath of allegiance (which
they knew they had a religious scruple against taking),
and, upon their conscientious refusal,
committed them to prison by fifty or sixty at a time.
In Bristol, near one hundred and ninety were imprisoned.
Soldiers kept guard at the several prisons night and day,
with orders to admit nobody to them.
Their servants were denied access; what they brought was narrowly searched,
and themselves rudely treated.
In Lancaster were two hundred and seventy prisoners; in Wesmoreland,
one hundred and sixteen; in West Riding of Yorkshire,
the number committed to prison was no less than two hundred and twenty-nine,
for refusing to swear; being taken, many of them from their religious meetings,
some on the highways, others from their houses and lawful employments,
and some out of their beds.

--

[.offset]
In the course of a religious visit in America John Richardson came to Nantucket.
He says:

[.embedded-content-document]
--

We then inquired for Nathaniel Starbuck, who, we understood,
was in some degree convinced of the Truth, and having directions to his house,
we went there.
I told him we made bold to come to his house, and if he was free to receive us,
we should stay a little with him, but if not, we should go elsewhere;
for we heard he was a seeking religious man, and such chiefly we were come to visit:
he said we were very welcome.
By this time came in his mother, Mary Starbuck,
whom the islanders esteemed as a judge among them,
for little of importance was done there without her, as I understood.

At the first sight of her it sprang in my heart:
"`To this woman is the everlasting love of God.`"
I looked upon her as a woman that bore some sway in the island, and so I said,
and that truly: "`We are come in the love of God to visit you,
if you are willing to let us have some meetings among you.`"

The meeting being agreed on, and care taken as to the appointment of it, we parted,
and I laid down to try if I could get any sleep; but sleep vanished from me,
and I got up and walked to and fro in the woods, until the meeting was mostly gathered.
I was under a very great load in my spirit, the occasion of which was hidden from me,
but I saw it my place to go to meeting, the order of which was such,
in all the parts thereof, that I had not seen the like before;
the large and bright rubbed room was set with suitable seats or chairs,
the glass windows taken out of the frames, and many chairs placed outside,
very conveniently, so that I did not see anything lacking, according to the place,
but something to stand on, for I was not free to set my feet upon the fine cane chair,
lest I should break it.

I am the more particular in this exact and exemplary order than in some other things,
for the seats both within and outdoors were so placed,
that the faces of the people were towards where the public Friends sat, and when so set,
they do not look or gaze in our faces, as some I think are too apt to do,
which in my thoughts bespeaks an unconcerned mind.
The meeting being thus gathered, and set down in this orderly manner,
although there were but very few bearing our name in it,
it was not long before the mighty power of the Lord began to work,
and in it my companion did appear in testimony in the forepart thereof.

I sat a considerable time in the meeting before I could see my way clear to say anything,
until the Lord`'s heavenly power raised me,
and set me upon my feet as if one had lifted me up;
and what I had first in commission to speak, was in the words of Christ to Nicodemus,
namely: "`Except a man be born again,
he cannot see the kingdom of God;`" with these words, Indeed,
the natural and unregenerate man cannot so much as
see the heavenly and spiritual kingdom of Christ,
which stands not only in power but also in righteousness,
joy and peace in the Holy Spirit.
I told them that to be born again, was not to be done unperceivably,
no more than the natural birth could be brought forth without trouble;
and to pretend to be in Christ and not to be new creatures is preposterous;
and to pretend to be new creatures,
and yet not to be able to render any account how it was performed, was unreasonable;
it could not be, as I urged before, without our knowledge; for to be born again,
signified to be quickened and raised into a spiritual and new life,
by which the body of the sins of the flesh is mortified,
and we come to live a self-denying life.
Those who are crucified with Christ, are crucified to their sins,
that as He died for sin, we might die to sin:
in this state we live not after the flesh although we live, as the apostle said,
in the flesh; but the life which these live, is through faith in the Son of God:
and to have all this, and much more wrought in us, and we know nothing of it,
is unaccountable.

As I was thus opened, and delivering these things, with much more than I can remember,
the woman +++[+++Mary Starbuck]
I felt, for most of an hour together, fought and strove against the testimony,
sometimes looking up in my face with a pale, and then with a more ruddy complexion;
but the strength of the Truth increased and the Lord`'s
mighty power began to shake the people within and outdoors;
but she who was looked upon as a Deborah by these people,
was reluctant to lose her outside religion, or the appearance thereof.
When she could no longer contain, she submitted to the power of Truth,
and the doctrines thereof, and lifted up her voice and wept.
Oh!--then the universal cry and brokenness of heart and tears were wonderful!
From this time I do not remember one word that I spoke in testimony,
it was enough that I could keep upon the true bottom,
and not be carried away with the stream above my measure.

I might add much more concerning this day`'s work,
but I intend not to say anything to the praise of the creature,
but to the renown of the mighty name of the Lord of Hosts,
and let all flesh lie as in the dust forever.
While I continued speaking in this state, as before mentioned,
and thus swallowed up in the internal presence of Christ,
where there was no lack of power, wisdom or utterance,
I spoke but a sentence and stopped, and so on for some time.

As extreme heats often end in extreme cold, and as great heights frequently centre,
as to man in this capacity, in great depths, and great plenty in great poverty,
which I have often seen to be good, in order to keep the creature low,
in fear and in a dependence upon the Lord,
I soon fell into such a condition that I was likely to die away.
When it was so, I, with my companion, made a motion to break up the meeting,
but could not for some time, for they sat weeping universally; then I told the meeting,
especially such as were near me, that if I should faint away,
I would not have them to be surprised at it,
for I was much concerned lest that should hurt these tender people;
my life was not dear to me in comparison of the worth
of the souls of the children of men.
But all this did not break up the meeting.

After some time, Mary Starbuck stood up, and held out her hand and spoke tremblingly,
and said: "`All that ever we have been building, and all that ever we have done,
is pulled down this day: and this is the everlasting Truth,`" or very nearly these words.
Then she arose, and I observed that she, and as many as could well be seen,
were wet with tears from their faces to the foreskirts of their garments,
and the floor was as though there had been a shower of rain upon it; but Mary,
that worthy woman, said to me,
when a little come to consider the poor state that I was in: "`Dear child,
what shall I do for you?`"
I said, "`A little would do for me.
If you can get me something to drink that is not strong, but rather warm,
it may do well.`"
So she did, and I went unto her son`'s, where my clothes were,
that I might change my clothes, for I felt sweat in my shoes as I walked.

--

[.old-style]
=== On Silent Worship / By B. Barton

[verse]
____
"`Thou worshippest at the temple`'s inner shrine,
God being with thee when thou know`'st it not.`"

Though glorious, O God! must thy temple have been
On the day of its first dedication,
When the cherubim`'s wings widely waving were seen,
On high o`'er the Ark`'s holy station,

When even the chosen of Levi, though skill`'d
To minister, standing before Thee,
Retired from the cloud which the temple then filled
And thy glory made Israel adore Thee,

Though awfully grand was thy Majesty then,
Yet the worship thy Gospel discloses,
Less splendid in pomp, to the visions of men,
Far surpasses the ritual of Moses.

And by whom was that ritual ever repealed?
But by Him unto whom it was given,
To enter that oracle where is revealed
Not the cloud--but the brightness of Heaven.

Who, having once entered hath shown us the way,
Oh, God! how to worship before Thee,
Not in shadowy forms of that earlier day,
But in spirit and truth to adore Thee.

This, this, is the worship the Saviour made known,
When she of Samaria found Him
By the Patriarch`'s well, sitting weary, alone;
With the stillness of evening around Him.

How sublime, yet how simple the worship He taught,
To her who enquired by the fountain,
"`If Jehovah at Solomon`'s shrine should be sought,
Or adored at Samaria`'s mountain?`"

Woman, believe me, the hour is near,
When He, if ye rightly would hail Him,
Will neither be worshipped exclusively here,
Nor yet at the altar of Salem.

For God is a spirit, and they who aright
Would perform the pure worship He loveth,
In the heart`'s holy temple will seek with delight
That spirit the Father approveth.

And many that prophecy`'s truth will declare
Whose bosoms have livingly known it,
Whom God hath instructed to worship Him there
And convinced that his mercy will own it.

The temple that Solomon built to his name,
Now lives but in history`'s story.
Extinguished, long since its altar`'s bright flame,
And vanished each glimpse of its glory.

But the Christian made wise by a wisdom Divine,
Though all human fabrics may falter,
Still finds in his heart a far holier shrine,
When the fire burns unquenched on the altar.
____

[.old-style]
=== The Quaker Meeting--1688 / By John G. Whittier

[verse]
____
Fair First-day mornings, steeped in summer calm,
Warm, tender, restful, sweet with woodland balm,
Came to him like some mother-hallowed psalm

To the tired grinder at the noisy wheel
Of labor, winding off from memory`'s reel
A golden thread of music. With no peal

Of bells to call them to the house of praise,
The scattered settlers through green forest ways,
Walked meetingward. In reverent amaze

The Indian trapper saw them from the dim
Shade of the alders, on the rivulet`'s rim,
Seek the Great Spirit`'s house to talk with Him.

There, through the gathered stillness, multiplied
And made intense by sympathy, outside
The sparrows sang, and the gold-robin cried

A-swing upon his elm. A faint perfume
Breathed through the open windows of the room,
From locust trees heavy with clustered bloom.

Thither, perchance, sore-tried confessors came,
Whose fervor, jail nor pillory could tame--
Proud of the cropped ears meant to be their shame.

Men who had eaten slavery`'s bitter bread
In Indian isles; pale women, who had bled
Under the hangman`'s lash, and bravely said

God`'s message through their prison`'s iron bars;
And gray old soldier-converts, seamed with scars
From every stricken field of England`'s wars.

Lowly before the Unseen Presence knelt
Each waiting heart, till haply, some one felt
On his moved lips the seal of silence melt.

Or, without spoken words, low breathings stole
Of a Diviner life from soul to soul,
Baptizing in one tender thought the whole.

When shaken hands announced the meeting o`'er,
The friendly group still lingered near the door,
Greeting, inquiring, sharing all the store

Of weekly tidings. Meanwhile youth and maid
Down the green vistas of the woodland strayed,
Whispered and smiled, and oft their feet delayed.

And solemn meeting, summer sky and wood,
Old, kindly faces, youth and maidenhood,
Seemed, like God`'s new creation, very good.

And, greeting all with quiet smile and word,
Pastorius went his way. The unscared bird
Sang at his side; scarcely the squirrel stirred

At his hushed footstep on the mossy sod;
And wheresoe`'er the good man looked or trod,
He felt the peace of Nature and of God.
____
