== Chapter VI. Courage

The courage manifested by our early Friends and their
fearlessness when the cause of Christ was concerned,
was a very striking characteristic, and of which their annals furnish many illustrations.

When George Fox was travelling in Scotland,
he was brought before the Council of Edinburgh,
who ordered him to depart from that nation within a week.
He, however, travelled over almost all Scotland.
Returning at length to Leith,
the innkeeper told him that the council had issued a warrant to apprehend him,
because he had not left the country after the seven days were expired.
Some others told him the same, to whom he said:
"`What do you tell me of their warrants against me?
If there were a cartload of them, I do not heed them,
for the Lord`'s power is over them all.`"
He went from there to Edinburgh, and continued some time longer in Scotland,
laboring in the Gospel, and no man offered to lay hands on him.

Once a company of Irishmen came to the Pall Mall, when George Fox was there;
but the meeting was already broken up, and he, being gone up into a chamber,
heard one of those rude persons, who was a colonel, say he would kill all the Quakers,
whereupon George Fox came down and told him: "`The Lord said, '`An eye for an eye,
and a tooth for a tooth,`' but you threaten to kill all the Quakers,
though they have done you no hurt.
But,`" said he, further, "`Here is Gospel for you; here`'s my hair, here`'s my cheek,
and here`'s my shoulder,`" turning it to him.
This so surprised the colonel, that he and his companions stood amazed, and said:
"`If this be your principle, as you say, we never saw the like in our lives.`"
To which George Fox said: "`What I am in words, I am the same in life.`"
Then the colonel carried himself lovingly.

George Fox mentions in his Journal, that when at Baldeck, in Hertfordshire,
he went to visit a sick woman, and on his return to the inn,
he "`found two desperate fellows fighting so furiously
that none dared come near to part them.
But I was moved in the Lord`'s power to go to them; and when I had loosed their hands,
I held one of them by the one hand, and the other by the other,
showed them the evil of their doings, and reconciled them one to the other;
and they were so loving and thankful to me that people admired at it.`"

In 1654, Francis Howgill wrote to the Protector, Oliver Cromwell, in a bold,
plain manner,
which showed that he feared not man when he spoke in the service of his Lord.
In this letter he says:

Thus says the Lord, I chose you out of all the nations,
when you were little in your own eyes,
and threw down the mountains and the powers of the earth before you,
which had established wickedness by a law,
and I cut them down and broke the yokes and bonds of the oppressor,
and made them stoop before you; but thus says the Lord,
Now your heart is not upright before me, but you take counsel, but not of me;
and my name is not feared; but your own wisdom you establish;
therefore this is the word of the Lord to you, whether you will hear or forbear:
If you take not away all those laws which are made concerning religion
whereby the people which are dear in my eyes are oppressed,
you shall not be established.

There is no reason for believing that Cromwell himself was in favor of persecution.
In his speech to parliament in 1654 he said: "`Liberty of conscience is a natural right,
and he that would have it ought to give it.`"

During the war between parliament and the king,
Oliver Cromwell had raised a regiment of a thousand men,
who were all professors of religion.
No blasphemy, drinking, disorder or impiety were permitted in their ranks.
"`Not a man swears but he pays his twelve pence.`"
These were the famous Ironsides, of whom their leader said at the close of the war:
"`Truly, they were never beaten at all.`"
They went into battle singing Psalms,
and many among them were accustomed to deliver religious exhortations to their fellows.
Many of these men belonged to the Independent party,
which had for some years been growing in numbers in England.
They advocated full religious freedom,
and the right of each congregation to appoint its own officers,
and to govern itself in religious matters.
In this and on some points of doctrine they held many views which
approached those afterwards held by the Society of Friends--indeed,
from their ranks came many of the early converts to Quakerism.

The late Robert Barclay in his [.book-title]#Inner Life of the Religious Societies of the Commonwealth#,
calls attention to these points of resemblance,
and suggests that George Fox derived from the Independents, Mennonites,
and General Baptists, many of his doctrinal views, and his system of church polity.
But the clear statements which Fox records in his Journal of the manner
in which the truths of religion were gradually opened to his mind,
proves that this suggestion does not rest on a solid foundation,
as is clearly shown by the late Dr. Charles Evans,
in his review of Robert Barclay`'s work, [.book-title]#An Examen#, etc.
There appears to have been among these people in those early
days a good degree of simple obedience to Christ,
and of real religious feeling.
Isaac Penington, who at one time was in fellowship with them, bears witness to this,
and he mourns over the decay in the "`savor of life`" among them,
and the substitution for it of "`head-knowledge,`" and of "`prayers,
reading of the Scriptures, and preachings, and duties,
and ordinances,`" and he tells them,
"`You must come out of your knowledge into the feeling of an inward principle of life,
if ever you be restored to the true unity with God,
and to the true enjoyment of Him again.`"

Many of the soldiers in the parliamentary army were Independents,
and sympathized with them.
But in the parliament the Presbyterian influence was predominant,
and religious liberty was not in accordance with their traditions.
They still held to the views which had long prevailed in Europe,
and had been the generally accepted doctrine "`That every realm through its rulers,
had the sole right of determining what should be the form of religion within its borders.`"
But the army, victorious over Charles and his adherents,
had no disposition to submit to intolerant restraints,
and finally ejected the members of parliament,
and Cromwell became the ruler of the nation, with the title of Protector.
This, Green calls the beginning of the struggle "`Between the principle
of religious conformity and the principle of religious liberty.`"

The sufferings of Friends during the protectorate of Cromwell, who died in 1658,
did not proceed so much from the government, as from the ill-will of the clergy,
to whom they refused to pay tithes,
believing that they were a part of the Mosaic dispensation,
abrogated by the coming of Christ, and that under the Gospel,
the ministry should be freely exercised.
Many were imprisoned for refusing to contribute to the maintenance
of priests whose preaching they did not attend,
and who, in consequence, had no just claims upon them.
They suffered not only in this way,
but were often beaten and abused by the mobs whom
the priests stirred up against them as heretics;
and they were frequently brought to trial or condemned as
blasphemers through the influence of the same adversaries.
Thus the clergy of that day showed that they were like the prophets of whom Micah spoke:
"`He that puts not into their mouths, they even prepare war against him.`"
Other causes of the dislike and persecutions extended
to the Quakers were their refusal to take oaths,
their peculiarities of language, and their disuse of the customary titles of society.

One of the false accusations brought against some
of the early members of our Society was,
that they were Jesuits in disguise.
In the contests of the reign of Elizabeth,
religion and politics had become closely interwoven in the public mind.
The rivalry of Mary, queen of Scotland, who made claim to the English throne,
and the political situation of England, as to the designs of Philip of Spain,
in the previous century,
had gradually brought queen Elizabeth of England to be considered
as one of the principal defenders of the Protestant cause,
although she herself was governed by political, far more than by religious feeling.
The action of the Pope of Rome in sending over large
numbers of disguised Jesuits to England,
to further his projects had awakened alarm,
and led to the passage of severe laws against such emissaries.
The attempts of Philip of Spain to eject Elizabeth from her throne
and to make the religion of the government Roman Catholic,
roused the energies of the people in opposition, and made patriotism favor Protestantism.
The public excitement was promoted by the cruelties of the Inquisition,
the massacre of St. Bartholomew in France, and later on,
by the atrocities connected with an Irish uprising in 1641,
when thousands of English people perished in a few days.
Green says of it: "`Tales of horror and outrage,
such as maddened our own England when they reached us from Cawnpore,
came day after day over the Irish Channel.`"

The period in which Cromwell held the reins of power was a very unsettled one,
and judging from the ordinary political views,
it was only by the exercise of great care and prudence
that he was able to maintain his authority.
He relied on the army to support him,
so that the government was really a military despotism.
The army were largely Independents,
and with the power in their hands would not submit to ecclesiastical oppression.
In the parliament the Presbyterian influence was predominant, and that people,
at that time, wished everyone to be made to submit to their views of church government.
Add to this, that a large body of people were dissatisfied,
that the constitutional government of Great Britain
had been superseded by one of military force,
and we may form some conception of the thorny and
rugged path which the Protector had to tread.

We believe Cromwell himself would gladly have relieved Friends of their sufferings,
but he feared to openly espouse their cause,
lest he might further offend some of those opposed to them.
Edward Burrough wrote to him,
plainly setting before him the wrongs inflicted in his name on the innocent,
and warning him that it was in the Lord`'s power to humble him,
as He had his enemies before him,
and that the blood of those who had died in prison for conscience`'
sake would one day be reckoned in account against him.

It was the belief of some of our early Friends that,
if Oliver Cromwell had had faith enough in the Lord to do what he knew to be right,
in repressing persecution, and to trust to Divine protection,
that the Lord`'s blessing would more eminently have rested upon him,
and they mourned over him as one who had injured himself by listening
to the advice of those who secretly desired his downfall.

William Penn says of George Fox: "`As he was unwearied,
so he was undaunted in his services for God and his people.
He was no more to be moved to fear than to wrath.`"
Of this there are many instances recorded.
In 1649, he went to visit a sick man, and after he came down from his chamber,
a servant came with a naked rapier in his hand, and threatened to stab him, but he,
looking steadfastly on the man, said: "`Alas for you, poor creature!
What will you do with your carnal weapon?
It is no more to me than a straw!`"

At the time of the court session at Lancaster in 1652,
some of his enemies had persuaded the presiding judge to issue a warrant for his arrest.
George Fox, coming to Lancaster, heard of a warrant to be given out,
and judged it best to show himself openly.
So he went to the chambers of judge Fell and colonel West;
and as soon as he went in they smiled, and the colonel said: "`What!
Are you come into the dragon`'s mouth?`"
But with his usual intrepidity, he stayed in town until the judge had departed,
and walked up and down there, without being meddled with.

Our early Friends felt themselves to be the servants of the King immortal,
who was able to preserve them in every danger.
This conviction was the secret of their courage.
They did not fear what man could do unto them while they
were faithfully carrying out the mission entrusted to them.
This was shown, not only in their readiness to endure persecution,
but in their plainness in rebuking evil.
George Fox wrote a letter of reproof to justice Sawrey, in which he tells him:
"`You were the first stirrer up of strikers, stoners, persecutors stockers;
mockers and imprisoners in the North; and of revilers, slanderers,
railers and false accusers and scandal-raisers.
This was your work, and this you stirred up.
But God has shortened your days, and limited you, and set your bounds,
and broken your jaws, and brought your deeds to light.
You shall have your reward according to your works.
You can not escape.
The Lord`'s righteous judgment will find you out,
and the witness of God in your conscience shall answer it.`"

It is related of Robert Widders, one of the early ministers among Friends,
that when he was brought before a justice of the peace,
who made a warrant to send him to Carlisle Jail,
the justice asked him by what authority or power he came to seduce and bewitch the people?
Robert answered: "`I came not to seduce and bewitch people,
but I came in that power which shall make you and all the
powers of the earth bend and bow down before it,
namely, the mighty power of God.`"
The justice was so impressed that he took the warrant from the hand of the constable,
and allowed Robert to go away.

The undaunted boldness with which our early Friends
maintained their testimony to the Truth,
was due not so much to any natural fearlessness of character,
as to the sustaining power of the Lord and the confiding
trust in Him with which He favored his people.

After the death of Oliver Cromwell, as persecution still continued,
Edward Burrough wrote the following lines to his son Richard,
who succeeded him as Protector:

To the Protector and His Council

The Lord God will shortly make you know that we are his people,
though we be accounted as sheep for the slaughter,
yet our King of righteousness will break you to pieces,
if you harden your hearts and repent not.
And though that love will not draw you,
neither the gentle leadings from God have any place in you,
yet judgments shall awaken you,
and his heavy hand of indignation shall lie upon your conscience,
and you will be scattered and distracted to pieces.

It was but a few months after the delivery of this letter,
when Richard laid down the government.

The experience of Barbara Blaugdon, of Bristol,
shows how the Lord supported his servants, and raised them above the fear of suffering,
enabling them to rejoice in tribulation.
At one time she went to Great Torrington, and spoke to the people in the steeple-house.
The next day she was sent for by the town authorities, and committed to prison at Exeter.
After the court sessions were over, the sheriff came to the jail with a beadle,
who took her into a room, where he whipped her till blood ran down her back,
and she never startled at a blow,
but sang aloud and was made to rejoice that she was
counted worthy to suffer for the name of the Lord,
which made the beadle say: "`Do you sing?
I will make you cry by and by;`" and with this he laid on so hard that one Ann Speed,
seeing this, began to weep.
But Barbara was strengthened by an uncommon and more than human power,
so that she afterwards declared if she had been whipped to death,
in the state she then was, she should not have been terrified or dismayed.
And the sheriff, seeing that all the wrath of man could not move her,
bid the fellow leave off striking, and then Ann Speed was permitted to dress her stripes.
The next day she was turned out, and the beadle followed her two miles out of town;
but as soon as he left her she returned back,
and went into prison to see her friends that were prisoners there,
and having visited them, she went home to Bristol.

Gilbert Latey, of London, was one of our early Friends,
who was well known to many of the higher classes in that city,
and greatly esteemed by them.
About the year 1671, having occasion in the way of his trade to wait on the lady Sawkell,
her husband, sir William Sawkell came into the room,
who then had a command under the earl of Oxford, in his regiment of horse;
sir William asked him what meeting he went to, to which he answered:
"`Sometimes to one meeting and sometimes to another.`"
"`The reason,`" said sir William, "`why I ask is,
because I have had orders to go and break up your meeting at Hammersmith,
which I have deferred executing, and now I have a fresh command laid on me,
and cannot avoid it,
but must go there--Sunday next--and therefore I speak in kindness to you,
if you were at any time to go there, that you refrain coming that day;
for I receive my command from so high a hand that I dare not omit executing thereof.`"

Upon this discourse it was immediately laid on Gilbert that he must be at Hammersmith
at the same time sir William had desired he would avoid coming,
and accordingly he told him so before they parted.
Accordingly he went to that meeting,
and in the Lord`'s authority spoke to those who were assembled.
While he was preaching, the troopers came, and Gilbert asked: "`Who commanded them?`"
They replied, "`Sir William Sawkell.`"
Then said Gilbert: "`Let your officer know I am here,
and my name is Gilbert Latey,`" which, when sir William heard, he came in trembling,
and at last said: "`Latey,
did I not tell you I was commanded to be here today?`"--to which Gilbert replied:
"`You did, but did I not also tell you, I was commanded by a greater than you are,
to be here also?`"
Upon this, said sir William: "`Go, get you gone about your business,
and I will take care concerning the rest here met;`" upon which Gilbert said:
"`If you have any respect for me, then discharge all the rest,
and let me be your prisoner.`"
So after some time, the Friends were set at liberty, and Gilbert taken and fined.

Among the varied forms of suffering which our early
Friends endured for conscience`' sake,
one of the most common was imprisonment.
From the numerous accounts of their experiences in the jails of that period,
we find that these places of confinement were often in a very neglected and bad condition,
and that the comfort of the prisoners depended largely on
the character of the jailer to whose care they were committed.
The jails were often private property,
and the safe custody of the inmates was almost the only point insisted upon.
There appears to have been very little, if any,
proper arrangement for the feeding of the prisoners,
who depended largely on their own means or the benevolence
of visitors to supply their needs.
The sale of provisions and the rent of rooms to his
prisoners were the sources of the income of the jailer;
of course, such loose arrangements exposed the inmates to great abuses,
when the jailer happened to be an unprincipled or evilly disposed man.

At Appleby, Friends endured cruelties,
which no Christian government at this day would allow
to be inflicted upon the most abandoned criminals;
and all for the harmless performance of the duty of worshipping their Almighty Creator.
The stench from the felons`' dungeon below them,
and the impracticability of keeping their own cell clean,
rendered the air very impure and offensive,
particularly when the grate and out-door were closed,
which was often done by the cruel jailer,
to keep their friends from supplying them with food and water.
Having no fire, they suffered with cold in the winter,
and for lack of proper ventilation, with the heat of summer,
at times as if they would be smothered; and with many other privations and hardships,
which drew Friends who were at liberty, to visit them.
John Spooner gives this account of the abuses he met with in one of his visits of sympathy.

One day the jailer came down to the jail in the afternoon,
to let out one of the felons to beg in the town, who, it seems,
knowing some of us to be on the stairs, hastily pulled to him the outer door,
and locked it.
About two hours after, he came to let the prisoners into the jail again,
and when the door was open, I came down, thinking to go peaceably away;
and then he asked me what I had to do there; I said I came to see my friends.
Then he locked me in, and fell in a rage,
and beat me bloodily with the keys about my head and face,
and bruised me till blood came forth at my mouth, until the string broke.
He broke my head and jolted me several times against the wall; and when he had done so,
I bid him see how he had bloodied me.
He answered, Rogue, I shall blood you.
Then he gathered up the keys, and struck me again with the keys, and jolted me to and fro.
I would have gone my way, but he thrust me violently back, locked the door,
and kept me there until after nine o`'clock at night.
Afterwards he boasted how he did beat me till the keys flew about my ears,
and he intended to go down again; and said what he had done was but earnest,
and he would give me more.
His wife privately hearing him say so, and the intent of his further cruelty,
followed him; and when he had opened the door, he called on me, and I came down,
and he took me by the throat, and bringing a cudgel with him,
fell desperately to beating me with it.
Then his wife stepped in, and got fast hold of him, and so I went forth;
and he fell beating his wife in much cruelty and rage;
and two men of the town seeing him, they came to help her, and to entreat or hold him;
and he locked them all within the jail-door,
and kept them till almost four o`'clock in the morning.

The Journal of Richard Davies,
after describing the committing to prison of some Friends in Wales, says:

We found the temper of the jailer to be very cruel.
He threatened us with a great deal of hardship, if we did not eat of his food,
drink of his drink, and lie on his beds, and give him what he demanded.
We told him we were the king`'s prisoners, and demanded a free prison,
and straw to lie upon; but he in a rage denied us that, and put us into a little room,
where there was scarce place for us to lie down.
When night came, sleep came upon us, we being weary by travelling so many miles on foot,
but we were made willing and able to suffer all things;
so that night we lay upon the boards, and it was pleasant unto us, being warm weather,
and about the time of hay-harvest.
The next morning we were very fresh and well,
praising God for his mercies and goodness to us.
When the jailer came to us, and asked "`How we liked our lodging,
and how we slept?`"--we told him, we slept in peace of conscience and quietness of mind,
for we suffered for conscience`' sake towards God,
and dared not break the command of Christ and the apostle,
who commanded us not to swear at all.
For our supposed transgression was not only for meeting together,
but for refusing the oath of allegiance and supremacy.
The jailer being a very passionate, inconsiderate man,
would go out in the morning from his own house, and not come back till night,
and then return so drunken, that he could hardly speak or stand.
The next night when we went to lie down,
the room was so little we could not all lie at once.
The next morning we complained to the jailer,
that there was not enough of room for us all to lie down,
and desired him to let us have a little straw, but it would not be granted us.

By this time the Friends of the town had liberty to come and visit us,
and to bring us in some provision;
and when the door was opened for us to go into another room,
there being a bedstead with cords in that room, William Gibson and I lay upon the cords,
and the next morning we found that the print of the cords was not only in our clothes,
but in our skin also,
so that it had been easier for us to have lain upon the boards as we did before.
By this time, having well observed the jailer`'s humor and temper,
I began to be uneasy in myself to let him alone;
so I watched him in the morning upon his first rising,
when he came to the court before our prison door,
and began to discourse with him about the prisoners that lay in such hardship.
I told him they were honest men, and most of them masters of families,
and had good beds to lie upon at home,
but now they were content for Christ`'s and the Gospel`'s sake, to suffer that hardship.
I desired him to let them have liberty to go to their Friends in town at night,
and to come there in the morning;
and if he would not be pleased to grant them a little straw,
then to let them go lie in their own beds; which he surlily denied,
calling them a company of rogues and knaves, and such like terms.
He asked me, what made me plead for them?
I told him, they were my friends.
He answered, "`Why your friends?
You are no Quaker, are you?`"
I said, "`I am called a Quaker.`"
He answered, "`You do not look like a Quaker;`" and he looked at me in my face,
and on my hands and body.
I desired him not to disgrace me so, as to tell me I was no Quaker.
Then he asked where I lived: I told him, when I was at home I lived at Welchpool,
and my family was there, "`But,`" said he, "`where are you now?`"
I asked him, whether he did not know I was a prisoner there with my friends;
and he asked me, whether I did lie upon the boards with them; I told him I did.
He said he was sorry for it; but went away in anger, being much discontented in himself.

I did not see him till next morning, at which time I went to him again,
and discoursed friendly with him; he said he inquired about me in town,
and I might take the liberty of the town.
I acknowledged his kindness; but told him it would be no comfort to me,
to have the liberty of the town, and leave my friends and brethren there.
He said then I might stay there with them.
So I did not see him till the next morning, and then I went to him again.
He was so cross and ill-conditioned, he would not allow any other Friend to speak to him.
William Gibson did so judge him for his wickedness,
that he kept him close in a room by himself.
After five nights lying on the boards, I prevailed with him,
that Friends might have the liberty of the town in the night,
and be there in the morning.
So the next day he began to be more friendly to us.

After some days, I desired our friend John Millington,
to come with me to the jailer`'s house,
to see whether we could have leave to go home till the next court session;
but it was not then granted; but he told me, if I pleased I might go home till then.
I told him he might as freely let them go as me, for most of them lived in the county,
and I lived out of the county; but no more could we have that time of him.
I was uneasy in myself, seeing I had got a place in him, to let him alone,
and pressed for my Friends`' further liberty.
A little time afterwards, by serious arguments, as it was harvest time,
and hard for their wives or some of their families
to come with weekly necessaries for them,
I, with my friend John Millington, prevailed with him to let them go,
and he took our words for our appearance at the next court session.

Through the goodness of God, we all returned together to Shrewsbury, to our prison,
before the court session, and found a great alteration in the jailer;
he was low and mournful.
He had lost a prisoner, a malefactor, and was to be tried for his life for his escape.
He was very loving and kind to us, and let Friends go themselves to Bridgenorth,
fourteen miles, where the court sessions were then held;
and he desired me to stay with him in his affliction, and not be much from him.
He said his life was at stake, and if God and the judge would show him any mercy,
it was upon our Friends`' account, and not for any deserts that were in himself,
for he confessed he had been too severe to us; but notwithstanding, said he,
you are merciful men, and can forgive wrongs and injuries.

When we came to Bridgenorth, we were put in a large,
spacious room in the House of Correction, to be there in the day time,
that we might be all together, and ready when called for;
but we had liberty of going in and out for lodging and what necessaries we needed;
no keeper being over us, but what we set ourselves to look to the door,
and that too many Friends might not be out at once,
and these were not to stay out too long.
We saw it was convenient that Friends should go out by two and two, to walk the streets;
for it was a strange thing to people to hear of Quakers.
Once it fell to my lot to be at the door, though the door was always open,
that such as would,
might come and see us--with several of whom we had reasonings and disputes about the
way of Truth and righteousness--there came one who appeared something like a gentleman,
and asked me whether he might see the Quakers; I desired him to walk up along with me,
and he should see them.
When I had brought him up to the room where Friends were walking,
I told him these were they.
He answered, these be Christians like ourselves, but where are the Quakers?
I told him these were they that were called Quakers.
He asked me whether I was one of them; I told him I was one so called.
I had an opportunity to declare to him the way of Truth,
and that the name of Quaker was given to us in scorn and derision;
and he departed very friendly.

Some people were so blind and dark in these days,
that they looked upon us to be some strange creatures, and not like other men and women.
They would gather about us in the town,
and we had good opportunities to speak of the things of God to them.
But I was pretty much with the jailer, waiting when his trial would be; and when it came,
I went with him and stood somewhat near him, which he was very glad of.
The jury cleared him, being not found guilty of a willful escape;
which was gladness to him and satisfaction to us.
And when the court session was near at an end,
the judge returned us to one justice Holland, except William Gibson,
to whom the judge put it whether he would go home if he were discharged;
but he could not make the judge such a promise as he required,
so he was committed to prison; but we were freely and friendly discharged,
having had good service in that town, and the Lord was with us, and brought us safe home,
to the comfort of our families and ourselves;
and we have cause to bless and praise the name of the Lord forever,
for all his mercies and goodness to us all along,
in the time of our afflictions and persecutions.
We could say, surely God is good to Israel,
and to all them that draw near unto Him with an upright heart.

The Journal of Richard Davies throws considerable light
upon the powers and duties of the jailers at that period.
After mentioning that several friends in Montgomeryshire had been put in prison,
he says that one of the magistrates,
a "`Lord Herbert,`" sent private instructions to the jailer to let them have more liberty.

The jailer had an empty house at the end of the town, and there he let Friends go,
which was a sweet, convenient place near the fields, without any keeper over them,
and they had the liberty of the town, and to go where they pleased,
except to their own houses.

So Charles Lloyd took a house in town for him and his family to live in,
and we kept our meetings in that house of the jailer`'s aforesaid for several years.
Most of Friends by this time being under premunire,
many Friends came from several places to visit them
and those that were convinced towards Machynlleth.
William Evans and several others of that end of the county,
who were formerly Independents,
were sent here to prison upon the same account--refusing
to take the oath of allegiance and supremacy.
Peter Price, also, a worthy man of Radnorshire, was sent to this prison.
He had been in commission of the peace in Oliver`'s days; he,
with several others with him,
were committed by the justices of this county to the House of Correction in Welchpool,
for three months, as vagrants, because they came out of their own county, Radnorshire,
adjoining to this county of Montgomeryshire.
They remained prisoners three months, but they had the liberty of the town,
and to go to the meetings with the rest of the prisoners.
Other Friends that lived in and about the town, met with them in prison,
and considerable meetings we had in that house.

When John Banks was paying a religious visit in Ireland,
as he was waiting on the Lord at Dublin, a great weight came upon his spirit,
with an opening that on the next First-day he must
have a meeting at a point some miles to the southward,
of which he did not know the name.
He told William Edmundson of his exercise, who mentioned Wicklow,
and he felt that that was the place he was to go to.
So on Seventh-day he went, in company with two friends,
and gave notice of his intention to hold a meeting.
Soon after the company were gathered, and before John had spoken,
a guard of musketeers came and took him before the governor of the town,
where they found the priest, who exclaimed: "`This is the deceiver,
this is the deluder who has come from England to delude people here:
I hope you will do justice and execute the law.`"
The room was large, and many people crowded in.
After a time, John turned to the crowd and said:

"`Your minister has charged me, without proof, that I am a deceiver and deluder.
Did you ever see my face before, or did you ever hear me speak before now?
Which of you, or whom, have I deceived or deluded?`"
Some more words I spoke,
to manifest to the people that their minister was no minister of Christ,
according to the Scriptures.

All this time the governor was silent,
and I declaring God`'s everlasting Truth to the people.
At last the priest`'s wife said to the governor: "`I pray you, sir,
let him not preach here; commit him to jail.`"

This the governor did, on the ground that he had broken the law against conventicles.
John replied, that they only met in an honorable manner, in silence,
waiting upon the Lord.
But the governor directed the jailer, who was present, to take charge of him.
When they came forth from the house, the jailer said: "`Come after me.`"
He took them into a large room beyond his own dwelling,
and the people came in and filled that room, the jailer`'s and part of a third.
John Banks adds:

In a little time my mouth was opened in the demonstration of the power and spirit of God,
and I preached the way of peace and salvation to the people, in and by Jesus Christ,
his Son,
by believing in his pure light and walking answerable to the teachings of his grace,
and the reproofs of his Holy Spirit,
by which they might receive power to become the sons of God.

It was a blessed day for the Lord and his Truth, for his heavenly power broke in on many,
and several were convinced, and received the Truth in the love of it,
and many made confession thereunto,
and told the priest they were satisfied by what they had heard me speak,
that I was no such man as he said I was,
and that we were not the people he had persuaded them to believe.

The next morning the priest went to the sheriff to tell him what a numerous
meeting the jailer had permitted to be in the county jail,
and said: "`I entreat you, sir, to take some course in time, or else, I fear,
all the town of Wicklow will be Quakers.`"
The sheriff replied: "`If the jailer or any other permit the like again,
come and inform me, and I shall take a course with them.`"
When the news came to the jailer, who was a man of a pretty noble spirit,
"`What!`"--said he, "`have I been a jailer eight years,
and know not what belongs to my place?
So that I have my prisoners when there is occasion for them, I`'ll set my doors open,
and they shall go and come who will.`"
Accordingly he did so during the three days John Banks was there, who says that,
except when he was in bed,
there was scarcely an hour without some persons coming to see him,
and discourse with him about the principles of religion,
"`so that I was sorry for nothing but that I had no longer time there;
the Truth having prevailed so much upon the people,
and begotten true love to it in so little time.
Everlasting praises unto the Lord alone, whose the work is,
and by his own power He is the carrier on and manager of it.`"

On Third-day morning John Banks was brought before the governor, who,
in great moderation, reasoned with him for about an hour,
about their manner of meeting and the worship of God,
and what they believed concerning Christ and of honor to men in authority;
all which was cleared to his satisfaction.
He confessed to the truth of what was said,
expressed his belief that John Banks was an honest man, and set him at liberty.

Ambrose Rigge, when travelling on a religious visit, was arrested at Melcombe Regis,
and cast into a dismal underground dungeon,
where he was confined many days without a fire, having only a stone to sit upon.
Through an opening in the top of his cell he could see the people in the street,
and ever zealously concerned to spread the knowledge of the Truth, he preached the word,
from the bottom of his dreary abode, to the tendering of many hearts.
He was afterwards committed to the county jail at Dorchester for three months,
in which time an infectious disease swept away most of the prisoners.
He had, however, excellent religious service during this confinement,
and was a kind attendant on his fellow-prisoner for conscience`' sake, Humphrey Smith,
who was brought near to the grave by the prevailing sickness.
Joseph Coal and William Bayley, both ministers in the Society of Friends,
were likewise inmates of the same prison on a similar account.

In 1658, attempting to visit the Friends, prisoners in Southampton Jail,
he was seized by a constable and his assistants,
who treated him with great cruelty and barbarous violence.
By order of the mayor he was then severely whipped, and cast, maimed and faint,
into a cart; and thus conveyed, amid frost and snow, to a distance of twenty miles;
treatment through which, he says: "`The Lord carried me with cheerfulness, content,
and without the least murmuring.`"
In 1662, he was apprehended at a religious meeting, and was lodged in Horsham Jail.
At the assize he refused to take an oath, and was sentenced to premunire, namely:
"`The loss of his lands and tenements during life, and of his goods and chattels forever;
to be placed out of the king`'s protection,
and to be imprisoned during the royal pleasure.`"
The jailer also was strictly enjoined to keep him a close prisoner.
During this confinement, which lasted upwards of ten years,
he was subjected to much unworthy treatment at the hand of a professed minister of religion,
named Letchford, who,
having incensed the magistrates against the prisoner when on his trial,
continued to instigate them to add afflictions to his bonds.
Ambrose Rigge was, in consequence,
transferred to the "`Low Jail,`" and there confined among the felons.
The keeper of this prison, filled with the same spirit of hatred and enmity,
on one occasion, in the depth of winter,
placed him in the "`upper ward,`" but deprived him of his bed,
forcing him (while the snow was often deep upon the
ground) to lie upon the bare floor for weeks together.
So rigorous was his imprisonment at that period that his friends
found great difficulty in having food and water conveyed to him.

In 1672, chiefly through the exertions of George Whitehead, the king, Charles II,
was induced to grant letters-patent under the great seal,
for the liberation of the whole of the Friends prisoners throughout England,
and Ambrose Rigge, as well as many others, was set at liberty.
In reference to his sufferings, he remarks:
"`I have been made able and willing to bear all for
the testimony of Jesus and word of God,
not counting my life dear unto me, that I might finish my testimony with joy,
being counted worthy, not only to believe, but also to suffer for that doctrine,
faith and practice,
for which the ancient Christians suffered the loss of their liberties,
and many of them their lives.

At one time, when Richard Davies was a prisoner, although not strictly confined,
a concern came upon him to visit some counties in England and Wales,
but he was a prisoner, and though left much at liberty by his keeper,
he would not go without consent.
Most travelling Friends were at that time prisoners,
and the sense of duty was urgent on Richard to visit
the stripped meetings in Gospel love.
He says:

I followed my good Guide, that showed me what to do.
I went to the jailer and told him I had an occasion to go out a little while,
and I could not go without acquainting him of it, because I was his prisoner.
He said, "`I warrant you will go to preach somewhere or other,
and then you will be taken to prison; and what shall I do then?`"
I told him that if I was taken prisoner, I would send to him where I was,
and he might send for me if he pleased.
So he bid me have a care of myself.
