== Chapter VII. Friends as Advocates of Liberty

In his biography of William Penn,
William Hepworth Dixon speaks of the famous trial of Penn and Mead,
as one which had an important bearing in the promotion of civil liberty in Great Britain:

The great question agitating the country at that time was
liberty of conscience--with its consequence--free worship.
The church of England was alarmed.
The duke of York, the presumptive heir to the throne, was an avowed Catholic.
The king himself was suspected of a leaning towards the ritual followed by his wife,
his brother, his brother`'s wife... Some of the courtiers had recently apostatised;
and many others were suspected of only waiting a more favorable moment to declare
themselves converts to the creed which alone found active sympathy at Whitehall.
But, if Popery threatened from above, Puritanism was no less formidable below.
The country was known to swarm with the disbanded soldiers of Cromwell-men
as hostile to the establishment as to the monarchy.
Sects were daily multiplying in number.
And now in the midst of all these causes of dismay,
the power with which parliament had armed the church in its own defence,
six years before, was about to expire.
This power was given (May 16th,
1664) by the conventicle act--granted as an experiment for three years,
and afterwards renewed for a second term--which act declared
it seditious and unlawful for more than five persons,
exclusive of the family,
to meet together for religious worship according to any other than the national ritual;
and every person above the age of sixteen attending
meetings of the character described was liable,
for the first offence, to be fined five pounds or imprisoned during three months;
for the second offence, to be fined ten pounds or imprisoned six months;
for the third offence,
to be fined a hundred pounds or transported beyond the seas for seven years;
and for every additional offence, an additional hundred pounds fine was inflicted.

This monstrous enactment had fallen with the heaviest weight on Quakers.
Other denominations of dissenters,
finding their excuses in the spirit which prevailed against their doctrines,
evaded these penalties either by a pretended conformity
or by secret adherence to their own rules.
The followers of George Fox alone braved the law openly--continuing
to worship in public as before--and submitting to the fines,
degradations, and imprisonments which the law awarded;
resolved to tire out persecution by the patient spirit in
which they endured affliction for consciences`' sake.

William Penn soon became a victim of this enactment.
The Quakers, as usual,
taking no notice of the attempt of parliament to interfere with their modes of worship,
went on the fourteenth of August to their meetinghouse in Grace-church Street.
They found it closed and the doors guarded by a company of soldiers.
Unable to enter the building,
the members loitered about until there was a considerable crowd,
when William Penn took off his hat and began to address them.
Seeing this movement, the constables came forward and arrested him,
together with captain William Mead,
an old soldier of the commonwealth and now a draper in the city.
Penn demanded to be shown their authority for this act,
and the officers at once produced a warrant prepared beforehand,
and signed by the lord mayor sir Samuel Starling.
The whole of the little drama had been previously arranged by the civic powers;
and Penn and Mead were instantly taken from the place of meeting to undergo examination.
Knowing that admiral Penn was on his deathbed,
the petty officers of the city gave a loose rein to their native insolence.
When the prisoner refused to doff his hat,
the lord mayor threatened to carry him to Bridewell and have him
well whipped--though he was the son of a commonwealth admiral!
On being reminded that the law was against such a course of proceeding,
he ordered them to be sent to the "`Black Dog,`" a wretched jail in Newgate Market,
to await their trial at the Old Baily.
From this place of durance he wrote to his father in the most affectionate terms; and,
while glorying in his sufferings for a great principle,
expressed his deep regret at being dragged away from home at such a time.

On the first of September, 1670,
the two prisoners were placed in the dock to answer the charges brought against them.
Everything considered, the character of the men, the interests at issue,
the course of the proceedings and the final results--this is perhaps
the most important trial that ever took place in England.
Penn stood before his judges in this celebrated scene,
not so much as a Quaker pleading for the rights of conscience--as the Englishman
contending for the ancient and imprescriptible liberties of his race.
The special law on which he was arraigned, he knew very well that he had violated,
and intended again and again to violate.
His religious friends took the same view of the case:
they acknowledged the conventicle act to be in force
according to the mere forms of jurisprudence;
but they contended that it was in direct contradiction to the Divine laws,
and therefore not binding.
Better versed in his country`'s history, Penn disputed its legality.
He held it to be in equal hostility to the Bible and the Great Charter.
This therefore was the point to be brought to an issue--Does
an edict possess the virtue and force of law,
even when passed by crown and parliament,
which abolishes any one of the fundamental rights
secured to the nation by the ancient constitution?
A most important point in itself;
and dear to England were the interests which hung on the result.

The trial itself was an instructive exhibition of arbitrary proceedings on the part
of the courts and of courageous defense of their right on the parts of the prisoners.
William Penn said:
"`We confess ourselves to be so far from recanting or declining
to vindicate the assembling of ourselves to preach,
pray or worship the eternal, holy, just God, that we declare to all the world,
that we do believe it to be our indispensable duty,
to meet incessantly upon so good an account;
nor shall all the powers on earth be able to divert us from
reverencing and adoring the God who made us.`"
The sheriff, Richard Brown, said: "`You are not here for worshipping God,
but for breaking the law.`"
William Penn replied: "`I affirm I have broken no law,
nor am I guilty of the indictment that is laid to my charge.`"
Then he asked upon what law his indictment was grounded.
The recorder answered on the common law and refused to give any more definite answer.
William Penn in reply,
quoted from [.book-title]#Coke`'s Institute# that common law is common right--the great charter privileges;
and he further stated that if they denied him the oyer (hearing)
of the law which they suggested he had broken,
they would evidence to the whole world their resolution to sacrifice
the privileges of Englishmen to their sinister and arbitrary designs.

This so annoyed the court, that they ordered him to be removed to the bail-dock.
But this was not effected before the prisoner had exclaimed:
"`Must I therefore be taken away because I plead for the fundamental laws of England?`"
And, addressing the jury, he said: "`However, this I leave upon your consciences,
who are of the jury, and my sole judges, that if these ancient fundamental laws,
which relate to liberty and property,
and are not limited to particular persuasions in matters of religion,
must not be indispensably maintained and observed,
who can say he has right to the coat upon his back?
The Lord of heaven and earth will be judge between us in this matter.`"
The hearing of this emphatical speech was so troublesome to the recorder, that he cried:
"`Be silent there.`"
At which William Penn returned:
"`I am not to be silent in a cause wherein I am so much concerned, and, not only myself,
but many ten thousand families besides.`"

After William Mead had been also sent to the bail dock,
the recorder charged the jury in the absence of the prisoners,
which they protested against as arbitrary and illegal.
The jury having retired to agree upon a verdict; upon their return,
reported that William Penn was guilty of speaking in Grace-church Street,
but they sturdily refused to make the addition which the court requested,
"`to an unlawful assembly.`"
The court threatened the jury that they should be locked up without food, drink,
fire and tobacco, until they rendered a verdict that the court would accept.
Penn said: "`The agreement of twelve men is a verdict in law,
and such a one being given by the jury, I require the clerk of the peace to record it.
And if the jury bring in another verdict contrary to this,
I affirm that they are perjured men in law.`"
And looking on the jury, he said: "`You are Englishmen, mind your privilege;
give not away your right.`"
To which one of them returned, "`Nor will we ever do it.`"
The jury were locked up for another day,
when they rendered a clear verdict of not guilty as to both defendants.

Finding the jury impracticable, the court fined them forty marks a man,
and imprisonment in Newgate till the fines be paid.

Prisoner and jurors alike, refused to pay the fines--the first as a matter of conscience,
the second, because, under the influence of Edward Bushel,
they were induced to dispute the power of the court to inflict a fine for such
a contempt as the one they stood charged with--and were all removed to Newgate.

Dixon remarks:
Up to this period the usage of the courts with regard to verdicts
had never been reduced to a legal and positive form:
from the days of the Tudors it had been the occasional practice of the
bench to inflict fines on contumacious and inconvenient juries;
for centuries it had remained an unsettled question of law whether the jury had,
or had not,
a right so far to exercise its own discretion as to bring
in a verdict contrary to the sense of the court.
This great point was now to be decided.
Bushel and his fellow-jurors, at Penn`'s suggestion,
brought an action against sir Samuel Starling and sir John Howell,
the lord mayor and the recorder of London, for unjust imprisonment.
On the fifth of September they were committed to Newgate; counsel was engaged,
and application was immediately made to the Court of Common Pleas,
but it was not until the ninth of November that a writ of _habeas corpus_ was issued
to the Governor of the jail to bring up the person of Edward Bushel.
Newdegate, Size, Waller and Broome appeared as counsel for the prisoners;
Leroy and Maynard for the king--that is, for Starling and Howell, the king`'s justices.

Freeman has preserved the heads of this famous appeal.
The defence was taken on the ground that the jury had brought
in a verdict contrary to the laws of England,
to manifest evidence, and to the direction of the court.
Newdegate urged against this defence,--that,
so far as the laws of England were concerned,
the defence was bad--inasmuch as the question of
law cannot occur until the facts are proved;
here the facts were not proved to the satisfaction of the men who
were called upon by the constitution to investigate them;
consequently, the laws not being invoked, they could not be violated.
The second point of the defence Broome met by showing that it is the special
function of the jury to judge of the value of the evidence submitted to it,
and that in the eye of the law that body is presumed to be a more
competent judge of whether evidence is good or bad than the court.
This argument also met the last point of the defence;
the bench might be deceived in its opinion--the jury being agreed among themselves,
are presumed to be infallible.
The bench, therefore,
though at liberty to offer suggestions to the jurymen for their consideration,
may not lawfully coerce them; or, as Newdegate expressed it,
the judges may try "`to open the eyes of the jurors, but not to lead them by the nose.`"

The Court of Common Pleas adopted these views.
Sir John Vaughan summed up the argument on both sides,
and gave a learned exposition of the question as a piece of historical law,
ending with a verdict for Edward Bushel on behalf of himself and his fellow-prisoners.
They were consequently ordered to be set at liberty in open court.
Ten of the other eleven judges agreed in the verdict
given by sir John Vaughan--Chief Baron Turner,
merely abstained from giving an opinion on the point,
as he had not been present in the court to hear the arguments of counsel.
The verdict may therefore be considered as the unanimous expression of the twelve judges.
The course adopted by the lord mayor and recorder was condemned
by the highest legal tribunal in the land.
Bushel and his fellows left Newgate as conquerors.

The importance of this extraordinary trial can hardly be over-estimated,
either as a piece of history shedding light on the opinions held
in high places in the age immediately succeeding a time in which,
even by the confession of men otherwise adverse to it,
justice had been incorruptibly administered;
or as a stand taken once for all upon the ancient liberties of England
against the encroachments of an apostate king and a licentious court.
It established a truth which William Penn never ceased to inculcate--that
unjust laws are powerless weapons when used against an upright people.
It proved that in England at least the ruling power of the moment,
even when agreed in all its branches, is not omnipotent; that there still remained,
and ever must remain, a grand check to unjust government in the public conscience.
What is the use of a severe law,
if the nation repudiates it--if juries refuse to convict under it?
It becomes at once a dead letter, a thing which nobody will own,
a statute really at large.
We at the present day can more distinctly realize
the service rendered to posterity--to liberty,
by the noble defence offered at these trials, than could contemporaries.
We have seen the results of the stand then made--results
which there is good reason to believe Penn for one foresaw.
It may be said without exaggeration that these trials
gave a new meaning--infused a new life,
into the institution of the jury.
The result proved there was a power in the state superior to the parliament in its palace
at Westminster and the king in his palace at Whitehall combined--that sense of justice
which informs the brain and nerves the heart of the English people.
Driven from the court, the legislative assembly, and the bench of justice,
the spirit of Puritan Democracy found an impregnable citadel in the jury-room.

After the failure of the court to convict William Penn and William Mead,
through the courage of the jury,
the lieutenant of the tower was determined that William Penn should be made to suffer,
and so kept watch on his movements.
Accordingly he was arrested for preaching at Wheeler
Street meeting and taken to the tower,
and brought before sir John Robinson, the lieutenant of the tower, and others.
Here he was told that he was to be tried for a breach of what was called the Oxford Act.
To this William Penn replied that this act could not concern him,
for the preamble of the act shows that it was designed for those in orders,
and that he had never been.

John Robinson.--Will you swear?
Will you take the oath that the act requires of you?

W+++.+++ P.--That is not to the purpose.

J+++.+++ R.--Will you take it or no?

W+++.+++ P.--Why need I take an oath not to do that which is my faith not to do,
so far as concerns the king?

Lieutenant Price.--Then swear it.

W+++.+++ P.--The oath in that respect is already answered to all intents and purpose;
for if I can`'t fight against any man (much less against the king),
what need I take an oath not to do it?
Should I swear not to do what is already against my conscience to do?

J+++.+++ R.--You won`'t take the oath, then?

W+++.+++ P.--What if I refuse the oath,
not because of the matter contained in it (which
only can criminate in the sense of the act),
but of scrupling any oath?
Shall I therefore be committed to prison?
`'Twas all about fighting the oath and act were designed, and not taking of oath.
Therefore the denying to swear, where there is a denial to fight or plot,
is no equitable ground for commitment.

J+++.+++ R.--Do you refuse to swear?

W+++.+++ P.--Yes, and that upon better grounds than those for which you would have me swear.

J+++.+++ R.--I am sorry you should put me upon this severity.
It is no pleasant work to me.

W+++.+++ P.--These are but words.
It is manifest that this is a prepense malice;
you have several times laid the meetings for me, and this day particularly.

J+++.+++ R.--No, I profess I could not tell you would be there.

W+++.+++ P.--Your own corporal told me, that you had intelligence at the tower,
that I would be at Wheeler Street today, almost as soon as I knew it myself.
It is disingenuous and partial.
I never gave you occasion for such unkindness.

J+++.+++ R.--I knew no such thing: but if I had, I confess I should have sent for you.

W+++.+++ P.--That might have been spared: I do heartily believe it.

J+++.+++ R.--I vow, Mr. Penn, I am sorry for you; you are an ingenious gentleman,
all the world must allow you, and does allow you that; and you have a plentiful estate;
why should you render yourself unhappy by associating with such a simple people?

W+++.+++ P.--I confess I have made it my choice,
to relinquish the company of those that are ingeniously wicked,
to converse with those that are more honestly simple.

J+++.+++ R.--I wish you wiser.

W+++.+++ P.--And I wish you better.

J+++.+++ R.--You have been as bad as other folks.

W+++.+++ P.--When and where?
I charge you to tell the company to my face.

J+++.+++ R.--Abroad, and at home too.

Sir John Sheldon, as is supposed.--No, sir John, that`'s too much,
or words to that purpose.

W+++.+++ P.--I make this bold challenge to all men, women and children upon earth,
justly to accuse me with ever having seen me drunk, heard me swear, utter a curse,
or speak one obscene word (much less that I have made it my practice).
I speak this to God`'s glory,
that has ever preserved me from the power of those pollutions,
and that from a child begot a hatred in me towards them.
But there is nothing more common,
than that when men are of a more severe life than ordinary,
for loose persons to comfort themselves with the conceit,
that they were once as they are;
and if there was no collateral or oblique line of the compass, or globe,
men may be said to come from to the Arctic Pole,
but directly and immediately from the Antarctic.
Your words shall be your burden, and I trample your slander under my feet.

J+++.+++ R.--Well, Mr. Penn, I have no ill-will towards you: your father was my friend,
and I have a great deal of kindness for you.

W+++.+++ P.--But you have an ill way of expressing it.
You are grown too high to consider the plea of those you call your forefathers,
for liberty of conscience against the papists, Cranmer, Latimer, Ridley, Bradford, etc.
`'Twas then plea good enough, My conscience won`'t let me go to mass,
and my conscience wills that I should have an English testament;
but that single plea for separation, then reasonable, is now by you,
that pretend to succeed them, adjudged unreasonable and factious: I say,
since the only cause of the first revolt from Rome
was a dissatisfaction in point of conscience,
you cannot reasonably persecute others who have right to the same plea,
and allow that to be warrantable.

J+++.+++ R.--But you do nothing but stir up the people to sedition,
and there was one of your friends that told me, that you preached sedition,
and meddled with the government.

W+++.+++ P.--We have the unhappiness to be misrepresented,
and I am not the least concerned therein.
Bring me the man that will dare to justify this accusation to my face,
and if I am not able to make it appear, that it is both my practice, and all my friends,
to instill principles of peace and moderation,
and only to war against spiritual wickedness,
that all men may be brought to fear God and work righteousness,
I shall contentedly undergo the severest punishment all your laws can expose me to.
And as for the king, I make this offer, that if any living can make appear,
directly or indirectly, from the time I have been called a Quaker,
(since from that point you date me seditious) I have
contrived or acted anything injurious to his person,
or the English government, I shall submit my person to your utmost cruelties,
and esteem them all but a due recompense.
`'Tis hard that I, being innocent, should be reputed guilty, but the will of God be done:
I accept of bad report as well as good.

J+++.+++ R.--Well, I must send you to Newgate for six months,
and when they are expired you will come out.

W+++.+++ P.--Is that all?
You well know a larger imprisonment has not daunted me.
I accept it at the hand of the Lord, and am content to suffer his will.
Alas!--you mistake your interest: You`'ll miss your aim:
This is not the way to obtain your ends.

J+++.+++ R.--You bring yourself into trouble: you will be heading parties,
and drawing people after you.

W+++.+++ P.--You mistake: there is no such way as this to render men remarkable:
you are angry that I am considerable, and yet you take the very way to make me so,
by making this bustle and stir about one peaceable person.

J+++.+++ R.--I wish your adhering to these things do not convert you to something at last.

W+++.+++ P.--I would have you and all men to know,
that I scorn that religion which is not worth suffering for,
and able to sustain them that are afflicted for it.
Mine is; and whatever may be my lot for my constant profession of it,
I am not at all concerned about it, but resigned to answer the will of God,
by the loss of goods, liberty, and life itself: When you have all, you can have no more,
and then perhaps you will be contented,
and by that you will be better informed of our innocency.
Your religion persecutes, and mine forgives:
and I desire my God to forgive you all that are concerned in my commitment,
and I leave you all in perfect charity, wishing you everlasting salvation.

J+++.+++ R.--Send a corporal with a file of musquetiers along with him.

W+++.+++ P.--No, no, send your lackey: I know the way to Newgate.

His court order was made out and he imprisoned.

The preceding chapters have contained many illustrations of the effects
of the persecuting spirit to which our early Friends were exposed.
Their faithfulness in remonstrating with their persecutors,
and in publishing to the world the cruel treatment which they received, had, we believe,
a great effect in opening the eyes of the people to the wickedness of persecution,
and in preparing the way for the advance of both religious and civil liberty.

A number of Friends were confined in Ilchester Jail for going to their religious meetings.
When they were brought to trial, a jury chosen from among their neighbors was rejected,
and another which the court thought more fit for its purpose, substituted in its place.
The clerk read an indictment, that they were found or taken at an unlawful assembly,
with force of arms, in contempt of the king and his laws, crown and dignity,
to the terror of the people, etc.
The clerk said to the jury, "`Gentlemen, you have heard the indictment;
if you find them guilty, you find for the king.`"
To cast an odium upon these harmless people,
a bishop who sat upon the bench with the judge, stood up and said,
"`That the first Quaker that ever was in England
was hanged for being concerned in the Popish plot.`"
Elizabeth Stirredge, with her characteristic boldness, replied,
that "`The first who was called a Quaker was now alive.`"
It was well known that Friends were as decidedly opposed to Popery
as they were to the impositions of the church of England.
This pretended Christian bishop, being enraged because he was contradicted,
held up his hand towards them, and bid them, "`Have a care what they said,
for those who had estates among them, it would cost them their estates,
and they that had not should lie in prison until they perished.`"
This savored much of the Popish inquisition.

She says: "`Such was their rage and wickedness against us,
that it was very grievous to hear them,
but a secret cry many times ran through my heart unto the Lord, '`Lord,
work for your name`'s sake, and confound their wisdom and rage,
and bring down their proud and wicked spirits,
and bring to nought their mischievous contrivance that they
have been contriving against your innocent people,
as they have been making themselves merry, and drinking wine to the full,
and feeding themselves with the fatness of the earth, as Dives did;
yet none of these things will give them satisfaction but the destruction of a poor,
despised people.
O Lord, make your power known this day,
and that which will make most for your honor and
the prosperity of your blessed Truth bring to pass;
that it may be known there is a God in heaven who
can rule the hearts of the children of men,
and whom all men ought to fear,
honor and obey.`'`" The Lord was pleased to hear the prayers of his children,
and to answer their request in the days of their affliction.
The jury, whom they thought fit for their work, were out long,
and when they came into court with their verdict, the foreman could not readily speak,
but looked much like a dead man.
The bishop, in an angry mood, asked him whether they were guilty or not guilty.
He answered, "`Guilty of not going to church, but not of a riot.`"
"`Of not going to church?`"--said the bishop: "`that is not the matter in hand;
guilty of a riot, you mean.`"
Then the rest of the jury said: "`No, my lord, guilty of not going to church,
but not of a riot.`"
"`You mean of an unlawful assembly, then?`"
"`Yes,`" said the foreman.
"`Why, that is a riot in law,`" said the bishop.

Elizabeth Stirredge fearlessly answered: "`We are no rioters.`"
Then the crier of the court shook his white rod over her head, and said, "`Be silent.`"
She said, "`No, we may not be silent; we are a sober people,
and live a good life and conduct; we do unto all men as we would be done by.
I never wronged man, woman nor child, and I know none that has anything against us,
unless for the answer of a good conscience.
Here are our neighbors who can testify for us.`"
The crier continued shaking his rod over her head, crying, "`Hush, and be silent.`"
But one of the judges, a sober, ancient man, said, "`Let the woman speak for herself;
she speaks truth and reason; let more of them speak.
You are many against them, and if they may not be permitted to speak for themselves,
it is very hard.`"
This stopped the rage of the bishop and judge,
and they directed the keeper to take them away, to be brought when called for.
The court went to their dinner, and Friends with the keeper.

"`No sooner were they gone, than a concern came upon me,`" says Elizabeth Stirredge,
"`to follow them; I could neither eat nor drink,
but was pressed in my spirit to go after them.`"
When she came, they were sitting down to dinner, with music playing,
and not seeing a fit opportunity, she retired, and came in as they were rising,
with a great dread and awe over her spirit.
One of them came to her and said: "`Good woman, whom would you speak with?`"
She answered, "`The judge of the sessions.`"
He said, "`I am the judge; if you have anything to say, I am ready to hear you.`"
But not being the man who sat on the bench that day, she said,
"`You are not the man I am going to.`"
Then he turned to the judge; and said, "`This woman has something to say to you.`"
Then one of them, laying his hand on her shoulder, said,
"`Let this good woman have what she will to say, we will hear her.`"
Going near to the bishop and judge, who sat at the upper end of the table, she said,
"`Forasmuch as you are all here who sat in judgment against us this day,
I have a concern upon my spirit in vindication of our innocency.
We are well known among our neighbors to be a sober and an honest people,
who live a good life and conduct; we do no wrong to any;
we can do good to them that hate us, and pray for them that despitefully use us.
I know of none who has anything against us, but concerning the law of our God.
Notwithstanding all this, we are numbered among transgressors,
and have been turned into the common jail, among felons,
our trades and families are liable to be ruined,
and all these things shall not befall us but you shall understand thereof.
I am here this day to testify to the truth of it,
for which the just and righteous God will one day plead.
As sure as the day gives its light, and the covenant of day and night cannot be broken,
there is not a man here, nor any that draw breath,
that shall escape the tribunal seat of God`'s divine justice;
everyone shall receive a just recompense of reward for the deeds done in their lifetime,
whether they be good or evil.`"

She says of this time: "`I can truly say the dread of the Lord was upon me,
insomuch that they were smitten and had not a word to say.`"
But in going downstairs a young man said:
"`I thought it would be so when this woman came in.
I thought she would preach when the Spirit moved her;
but why would you permit her,`" said he to the landlord, "`to disturb your guests?`"
Then he said: "`Get downstairs, or I will throw you down.`"
But nothing daunted, she turned in again, saying,
"`'`What wrong have I done to anyone here?--if I
could have kept my conscience clear in staying away,
I had not been here this day; but whether you will hear or forbear,
I shall be clear in the day of account of all your blood.`'
So I left them and had great peace with the Lord.`"
On the following morning they were called into court,
but they saw the bishop there no more, and the judge was very moderate.
He directed the keeper to bring up the Quakers, and calling some by name said,
"`You who stand here indicted, the court fines you five shillings apiece.`"
He said nothing about payment, broke up the court, and they went their way.
The keeper also left Friends, to their great admiration, and above eighty prisoners,
who were before them that day, were liberated.
After dinner, the cryer came in among them, and said: "`Neighbors and friends,
I am glad for your release; you are the people of God; men would ruin you,
but God will not allow them so to do.`"
He then asked: "`where is the woman?`"
E+++.+++ Stirredge said: "`Here am I.`" He added: "`The Lord bless you; I pray you, forgive me,
for I intended no harm, nor would do anything against you;
though I shook my rod over your head, I did it in no evil towards you; so I hope,
my honest neighbors and friends, you will forgive me.`"
They answered, "`Yes, freely,`" and desired his well being forever.
He went his way in much love, praying God to bless them,
and the Friends returned to their respective habitations,
with the peace of the Lord in their bosoms, and she adds:
"`Everlasting praises be given unto the Lord our God forevermore.`"

In the year 1670 Elizabeth Stirredge felt it required
of her to give a warning to king Charles II,
as follows:

"`This is unto you, O king;
hear what the Lord has committed into my charge concerning you.
As you have been the cause of making man desolate, so will the Lord lay you desolate;
and as many as have been the cause of persecuting
and shedding the blood of my dear children,
in the day when I call all to account, I will plead with them, says the Lord.
Therefore hear and fear the Lord God of heaven and earth,
for of his righteous judgments all shall be made partakers,
from the king that sits upon the throne to the beggar upon the dunghill.`"

This testimony I delivered into his hands, with these words: "`Hear, O king,
and fear the Lord God of heaven and earth.`"
I can truly say that the dread of the Most High God was upon me, which made me tremble,
and great agony was over my spirit, insomuch that paleness came into his face,
and with a mournful voice, he said: "`I thank you, good woman.`"
My soul knows and magnifies the name and power of the Lord my God,
for keeping me faithful to his testimony, and giving me strength to do his will.
So the Lord blessed my going forth, his presence was with me in my journey,
preserved my family well, and my coming home was with joy and peace in my bosom.

Another exercise through which this faithful servant passed, is thus narrated:

The officers came and demanded money for the king for our meeting together.
My husband answered them: "`If I owed the king any, I would surely pay him;
but seeing I owe him no money, I will pay him none.`"
They asked leave to distrain his goods; to which he said:
"`If you will take my goods by force I cannot hinder you,
but I will not give you leave to take them,
neither will I be accessory to your taking them.`"
The officers seeing our innocency, for we were in our shop at our lawful calling,
with our hands to our labor, and our children with us,
the constable leaned his head down upon his hand, with a heavy heart and said:
"`It is against my conscience to take their goods from them.`"
Then I said: "`John, have a care of wronging your conscience;
for what could the Lord do more for you than to place his good Spirit in your heart,
to teach you what you should do, and what you should leave undone:`" He said:
"`I know not what to do in this matter; if paying the money once would do, I would do it,
but it will not end so; it will be thus while you keep going to meeting;
for the rulers have made such laws, that never was the like in any age.`"
I said: "`John, when you have wronged your conscience,
and brought a burden upon your spirit, it is not the rulers who can remove it from you.
If you should go to the rulers and say,
I have done that which was against my conscience to do, they may say,
as the rulers did to Judas, What is that to us, you see to that.`"

The officers who were with him came and pulled down our goods;
and the power of the Lord smote them insomuch that
paleness was in their faces and their lips quivered,
and their hands did so shake, that they could not hold it long.
Then they would force a poor man to take them, but he refused until they forced him,
and laid them upon his arms and shoulders.
He trembled very much, though we had nothing further to say to them, after they came in,
but could rejoice that the Lord had found us worthy
to suffer for his blessed truth and testimony.
A little time after,
they had a meeting to appraise the goods taken from us and other Friends;
where there met together seven men called justices, and the officers and sheriffs,
bailiff and more of their confederates, a great room full of them.
I was at work in our shop,
and seeing the constable carrying some of the goods to be appraised,
it immediately came into my heart to go after them,
not knowing one word I should have to say;
which made me a little consider for what I should go,
but it more and more lasted with me to go.

When I came within the doors, I sat down like one that was a fool,
and had not one word to say, as near as I can count the time,
for half or three-quarters of an hour.
But when I came in they were greatly disquieted in
their minds and hurried in their business.
They said they could do nothing while I was with them,
the justices calling one to another to cause me to be taken away many times, saying,
"`We shall not do any business this day, but spend our time in vain,
if this woman sit here.`"
They often tempted me to speak what I had to say, and be gone;
but could not prevail with me.
Then they called to the man of the house to take me away,
solemnly protesting never to come to his house again, if he would not take me away.
But the man had not power to touch me, but full of trouble said, "`Sir,
I cannot lay hands on her, for she is my honest neighbor!`"--and he turning towards me,
said, "`Pray, neighbor Stirredge, if you have anything to say, speak,
that you may be gone.`"
One of the justices in great rage and fury,
solemnly protested he would never sit with them any more, if they did not take me away;
oftentimes wondering at their folly for letting me alone.
Then he opened the back door and went out, as though he would be gone,
but in a little time came in again saying, "`What!
Is she here yet?
I wonder at your folly!`"
Then the power of the Lord fell upon me, and filled my heart with a warning to them;
telling them "`That it was in vain to be found striving against the Lord and his people,
their work would not prosper;
for the great God of heaven and earth would be too strong for them.`"
Therefore I warned them to repent, and amend their lives before it be too late;
"`for the Lord will smite you unaware, and in an hour not expected by you;
therefore remember that the Lord has afforded you a day of warning,
before destruction comes upon you.`"
This and much more ran through me at that time.
In a few weeks, as they were making merry at a feast, two of them died on a sudden,
after dinner, and the rest very hardly escaped.
This was about the year 1674.

When persecution was active in Aberdeen, in 1676,
John Skein addressed a letter from the prison to the provost,
remonstrating with him for imprisoning Friends; in which he says:

I warn you, that you "`Seek not to cover this and such like rigorous practices,
lest you add to your iniquity.`"
No excuse will stand you instead in the day of the Lord; and the power and influence,
by which you proceed as you do, shall not cover you from the hand of that God,
who has said concerning his people: "`He that touches you, touches the apple of my eye.`"
Wherefore let not the self-seeking clergy, nor their emissaries,
sew pillows under the arm-holes, as the false prophets did of old to those in authority,
by telling you, that we are not the people of God; for know assuredly, that it is,
and has been, the word of the Lord to me, with others of my brethren,
since we came in here, that as there is no variableness nor shadow of changing in him,
so he shall be the same to us,
as he has been to our brethren and sisters in the time of their
sufferings under the persecuting anti-christian spirit in England,
Ireland and New England too, where some suffered martyrdom for his name`'s sake.
As we continue faithful in owning Him before men, so He shall own us,
not only before our very persecutors, but also in the great and terrible day of the Lord,
before his Father and his angels.

Wherefore I beseech you in God`'s holy fear,
to take heed to your proceedings against an innocent people,
and let not the enemy within, nor his instruments without,
drive you farther on in this path, wherein you are walking,
lest you be found a fighter against God.
So repent, and be warned from the Lord; despise it not,
though it come through a weak instrument.
Receive this as you please; but this I can say,
I have wrote this in true love and respect both to your soul and body,
as likewise in obedience to the Lord.
What I have written shall stand as a witness against you in the day of account,
and I shall be clear of your blood.
But it is the earnest prayer of my soul to the God of Power, that he may so second it,
as it may produce such fruits as are most acceptable to God,
and refreshing to his people.
I rest as formerly, however esteemed by you,

Your true and faithful friend,

John Skein

The trial of John Crook furnishes another illustration of the despotic
character of those who professed to administer justice;
and of the firmness with which Friends maintained their legal rights--John Crook,
who was a man of good family and education,
and had held the office of magistrate for some time,
having been dragged out of meeting and kept in prison for several weeks without trial,
was brought to the sessions at the Old Bailey, when,
there being no legal indictment upon which he could be tried,
the oath of allegiance was tendered him by the court,
in order to entrap and recommit him to prison.
Being well acquainted with the law,
he requested that prior to his being required to take the oath,
his accuser should first appear,
and the cause why he had been so long deprived of his liberty, should be investigated;
but the court refused to take any notice of his imprisonment, saying,
it was no matter to them how a man was brought before them, finding him there,
they had the right to tender the oath to him,
and he must either take it or suffer the penalty for refusing.
The prisoner denied the legality of their proceeding, inasmuch as he was there on trial,
and if there was nothing found against him he should be discharged,
after which the law would justify their requiring him to swear.
But they refused to give any heed to his plea, one of the judges saying:
"`You are here required to take the oath by the court,
and I will inform you what the penalty will be in case you refuse.
For your first denial shall be recorded,
and then it shall be tendered to you again at the end of the sessions,
and upon a second refusal, you run a premunire,
which is the forfeiture of all your estate, if you have any,
and imprisonment during life.`"
Upon John Crook replying that he stood for justice and the law, etc.,
the judges cried out: "`Take him away,`" which as the officers were about to do,
he addressed the court:
"`Mind the fear of the Lord God that you may come
to the knowledge of his will and do justice;
and take heed of oppressing the innocent,
for the Lord God of heaven and earth will assuredly plead their cause.
For my part I desire not the hurt of one of the hairs of your heads;
but let God`'s wisdom guide you.`"

On being brought before the court the next day,
an indictment against him for refusing to take the oath was read,
and he was called on to plead guilty or not guilty.
He requested to know first, who were his accusers.
This the court refused to take any notice of,
and endeavored to affright him by telling him that
if he did not plead he would run in a premunire,
whereby "`You lose the benefit of the law, and expose yourself, body and estate,
to great hazard, and whatever violence is offered to your person or estate,
you are out of the king`'s protection.`"

John Crook.--I desire, in meekness and humility, to say, I shall not:
I dare not betray the honesty of my cause, and the honest ones of this nation,
whose liberty I stand for as well as my own, as I have cause to think I shall,
if I plead to the present indictment, before I see the face of my accusers.

Finding the court would pay no regard to his exposition of the law,
which prohibited the oath of allegiance to be tendered to a prisoner until he
had been rightfully tried for the offence for which he had been committed,
and that they were bent on subjecting him to the severe penalty,
they had repeatedly recited in his hearing, John Crook enquired,
whether if he took it today he could be called on to take it again, tomorrow,
or the next day, and so on as often as they chose.

Judge.--When you have once sworn,
you may not be put upon it again except you minister occasion again on your part.

J+++.+++ C.--Is this the judgment of the court, that the oath once taken by me is sufficient,
and ought not to be tendered to me a second time
without new matter ministered on my part?

Judge.--Yes, you making it appear that you have once taken it.

J+++.+++ C.--Is this the judgment of the whole court?

The whole court standing up.
"`Yes: it is the judgment of the court.`"

J+++.+++ C.--&hellip;I am the man that have taken it once,
being a freeman of the city of London,
when I was made free; witness the records in Guild Hall, which I can produce,
and no new matter appearing you ought not, by your own judgment,
to tender it to me a second time.`"

Notwithstanding their united judgment just before delivered,
the judges refused to be bound by it, saying they would not be thus entrapped.

J+++.+++ C.--Will you not stand to your own judgment?
Did you not say, even now, that if I had once taken the oath,
it ought not to be tendered to me a second time except I ministered new matter,
that I had not kept it.
No such matter appearing, you ought not to tender it to me a second time,
by your own confession, much less indict me for a refusal.

He, with others, was remanded to jail.
When brought before the court again, the same arbitrary course was pursued,
and whenever John Crook attempted to speak in his own and his fellow-sufferer`'s defence,
the court ordered the hangman to stop their mouths,
which he did repeatedly with a gag and a piece of dirty cloth.
The judge sentenced them to forfeit all real estate during life;
and all personal estate forever, to be out of the king`'s protection,
and to be imprisoned during his pleasure.

J+++.+++ C.--But we are still under God`'s protection.

They were all sent to prison.

The experience of Samuel Bownas furnished another illustration of the
manner in which Friends were made instrumental in promoting civil liberty.
When in America, on a religious visit, in 1702, he was arrested on Long Island,
charged with speaking against the church of England in one of his sermons.
When the case came up for trial, the grand jury ignored the bill,
at which the judge was very angry, and demanded of the jury their reasons.
One of them, named James Clement, a bold man, well skilled in the law, answered:
"`We are sworn to keep the queen`'s secrets, our fellow`'s and our own,
and for that reason we declare no reasons.`"

Judge.--Now Mr. Wise Man speaks, but I tell you you are not so sworn,
and I could find in my heart to lay you by the heels, and a fine upon your brethren.

Clement replied, he might if he pleased, but when it was done,
it should be exposed with as much expedition as the case would admit in Westminster Hall.
"`For,`" adds he, "`juries, neither grand nor petty,
are to be menaced with threats of stocks or fines, but they are to act freely,
according to the best of their judgments, on the evidence before them.`"

Finding he could not bow the jury to his wishes,
the judge ordered Samuel Bownas to be kept in prison,
and threatened to send him to London chained to the deck of a man-of-war.
This greatly depressed Samuel`'s spirits, but an honest old man,
who had formerly been chief justice, came to visit him,
and taking him affectionately in his arms, said: "`Dear Samuel,
the Lord has made use of you as an instrument,
to put a stop to our arbitrary courts of justice,
which have met with great encouragement since his
lordship (lord Cornbury) came here as governor.
But there never has been so successful a stand made against it as at this time.
Fear not, they can no more send you to England than they can me.
The eyes of the country are now opened,
and they will never be able to get a jury to answer their end.`"

The old justice, as if he had been sent by Divine commission,
raised Samuel Bownas`' drooping spirits by his discourse, renewed his faith,
and as he said so it proved; they could not get a second jury to find a bill against him,
but they returned it, ignoramus, as the first.

While Samuel Bownas`' case was before the court, the hardhearted judge was taken ill,
and it was deferred in hope of his recovery,
as he was considered the most fit to take vengeance on the Quakers and Samuel Bownas;
yet he never was permitted to carry out his evil design,
but died some months before Samuel was released.
Our friend remained some time on the island;
and found that his long imprisonment had stirred up the people,
so that they flocked to the meetings which he held through the country generally,
in which he was renewedly anointed and strengthened to publish
abroad the glad tidings of salvation through our Lord Jesus Christ.

The more fully we understand the prevailing spirit
of the times in which the Society of Friends arose,
the conditions of social and political life that then existed,
and especially the contracted limits of civil and religious liberty;
the more highly do we value the bold and conscientious stand in defense
of the rights of man taken by those undaunted advocates of the Truth,
our primitive Friends.
Under the heavenly power with which they were clothed,
they were as a brazen wall against all oppression; and by their unyielding,
yet meek and inoffensive firmness in suffering, they finally overcame all opposition,
and largely contributed to secure to the English
race the degree of freedom which they enjoy,
and which we believe exceeds that possessed by any other of the nations of Europe.

The life of Robert Pike, one of the early Massachusetts Puritans,
and contemporary with the Friends who were put to
death by the intolerant government there,
throws light on this subject.
The author of the book says, in speaking of those times:

"`The civil authority was offensively dictatorial in its commands.
No individual outside of the ruling power had any
rights with which government could not meddle.`"
// lint-disable no-undefined
"`What we now call the rights of man were not only undefined and unrecognized,
but almost unknown.`"
"`The peremptory character of even Massachusetts`'
semi-popular government admits of no question;
and to face its hostility was an act of temerity in which few engaged,
and from which very few of those who did undertake it, emerged unscathed.`"
"`It was a period of history, both at home and abroad,
when the average citizen or subject could secure immunity only by a discreet,
quiet and complete obedience.`"
"`The liberty of speech, and the liberty of criticism and opposition,
were the precise things that were denied.
The man who contended for either had to do it in the spirit of a martyr,
and risk a martyr`'s doom.`"

In illustration of this despotic spirit,
the book relates the proceedings against this Robert Pike,
ending in a fine and disfranchisement,
because he had condemned a law passed by the general court,
which prohibited anyone from preaching to the people on a First-day of
the week who was not a regularly ordained minister of the Puritan church.
When a subsequent petition was presented to them for a repeal of this sentence,
they considered this an unwarrantable and insulting liberty,
and appointed commissioners to deal with the petitioners.
Robert Pike paid his fine, and in a few years had his right of citizenship restored.
There is no doubt his condemnation of an unrighteous
law was useful in opening the eyes of others;
though in paying the fine he did not fully carry out his
testimony as would have been done by a consistent Friend.
These proceedings occurred about the year 1653.

The treatment of the early members of our Society clearly evinces
the despotic spirit of the magistrates above referred to,
and shows how little regard was paid even to the forms of law,
when the will of the officer was contravened by the sufferers.
In 1655,
near the same time that Robert Pike had his controversy with the Massachusetts magistrates,
some Friends were brought into suffering at Barberry, in Oxfordshire, Eng+++.+++,
for their religious principles;
and they promptly published to the world the history of their case,
in a small pamphlet or book, entitled,
The Saints`' Testimony Finishing Through Sufferings, printed by Giles Calvert,
at the Black Spread-Eagle in 1655.
It clearly exposes the illegal and unjust treatment on false
accusations meted out to Anne Audland and others,
compares the proceedings with Scripture records to show their inherent unrighteousness,
and lays the burden of their iniquities plainly on the heads of the transgressors;
sparing none for their station or influence, but faithfully warning them to repent,
lest the righteous judgments of the Lord should overtake them,
and appealing to their own conscience as evidence of the truth of the statements made,
and of the wickedness of their course.
The old volume of pamphlets in which this is contained,
has within its binding more than thirty documents,
nearly all of which refer to similar cases,
and which were printed at different times between the years 1653 and 1656.
And this collection is a very small part of the fruits of that unwearied
perseverance in spreading the Truth among the people by pen and press,
as well as by word of mouth,
which made our early Friends such efficient instruments
not only in promoting vital religion in the world,
but also in educating the communities in which they lived
up to a fuller appreciation of the rights of man.

It is not surprising that such plain dealing should offend despotic magistrates,
who were unused to having their acts openly criticised,
and who expected humble submission to their dictates, whether right or wrong.
And we can readily believe that they were not pleased when told,
that they had violated the law of God as to respect of persons,
and reminded that He who judges righteously would
give unto every one of them according to their deeds,
because they fined and committed a Friend to prison
for coming into their presence with his hat on,
while at the same time they invited two priests who were present,
to retain those coverings.
Anne Audland in her "`Warning`" to the people of Barberry who were found "`falsely
accusing and imprisoning the servants of the Lord Jesus,`" thus pleads with "`Magistrates,
people and priest:`" "`If they shall depart into utter darkness
that visit not Christ`'s little ones in prison,
how shall those escape that cast them into prison?
The burdensome stone which you have taken upon you, will grind you to pieces;
to the light in all your consciences do I speak, which will witness for God,
and against all unrighteousness, in the day of the Lord,
when his righteous judgments shall be revealed from
heaven against all unrighteousness of men.`"

As Richard Farnsworth was passing quietly along the street of the aforesaid Barberry,
on his way to a meeting, a justice of the peace met him,
and ordered him to be sent to jail without just provocation or the breach of any law.
When brought up to be examined the next day, no charge could be found against him,
and he was told he might go out of the town if he would pay the sergeant his fees.
Richard refused to do so, and was remanded to prison, "`Because,`" as the account states,
"`he could not be a friend to deceit,
and acknowledge a false imprisonment and pay fees for the same,
being taken out of the highway or street, as he was passing quietly on,
and sent to prison; and to color over their deceit,
they have added several lies in a court order,
and here he is kept in prison for standing faithful to the Lord,
and cannot have any fellowship with the unfruitful works of darkness,
but rather reprove them.`"

Such faithful witnesses, whom no fear of man could intimidate,
and no suffering prevent from upholding the standard of Truth and righteousness
which they believed the Lord himself had given them to bear aloft,
were exceedingly annoying to their persecutors;
for they hesitated not to rebuke their evil deeds,
and to throw the burden of the responsibility on
those who were violating the laws of God or man;
and that, both in private and in public; to the offenders themselves,
and to the world at large.

In the year 1654, Miles Halhead came to Berwick, in Northumberland,
and went to the mayor of that town, and spoke to him in his shop thus: "`Friend,
hear what the servant of the Lord has to say unto you.
Give over persecuting the Lord`'s servants,
whom He does send in love to this town of Berwick,
to show you the way that leads to life eternal.
I charge you, O man, touch not the Lord`'s anointed, nor do his prophets any harm,
lest you procure the anger of the living, eternal God against you.`"
This bold language so offended the mayor, that he sent Miles to prison,
where he was about ten weeks, and then was brought to the sessions, where a bill,
drawn up against him, was read in open court, but he denied the contents thereof,
yet said: "`But what I said to the mayor of this town I will not deny.`"
And then he related the aforesaid words he spoke to the mayor.
Whereupon the recorder says: "`Sirs, as I understand by his own words,
if he cannot prove the mayor of the town a persecutor,
in my judgment he has wronged him.`"
To this Miles answered: "`If the mayor of this town of Berwick dare say,
in the presence of the Lord, whose presence is here, that he is no persecutor,
but the persecuting nature is slain in him,
I will be willing to abide the judgment of the court.`"
Then the clerk of the court said: "`Mr. Mayor,
if you will say that you are no persecutor, but the persecuting nature is slain in you,
he is willing to abide the judgment of the court.`"
To this the mayor answered, "`I know not what to do: I would I had never seen him;
I pray you let him go, and let us be no more troubled with him.`"
Then Miles said,
That he would prove this mayor of Berwick the greatest persecutor in town or country.

"`I was once +++[+++thus he went on]
committed to prison in this town before,
by some of the justices that are now in this court; but you, O man,
have exceeded them all; you have committed me,
and kept me in close confinement for about ten weeks, for speaking to your own person,
in your own shop.
Now, I make my appeal to the recorder of this town of Berwick,
as I am a free-born Englishman, whether my imprisonment be legal,
according to the law of this nation, or not?`"
Then the recorder of the town stood up and said:
"`It is not very legal for any minister of the law to imprison any man in his own cause.`"
Then the court cried, "`Take him away.`"
The chief priest of the town then stood,
and desired the court that he might ask Miles one question.
To this Miles said: "`The Lord knows your heart, O man,
and at this present has revealed your thoughts to his servant;
and therefore now I know your heart, also, you high priest,
and the question you would ask me; and if you will promise me, before the court,
that if I tell you the question you would ask me, you will deal plainly with me,
I will not only tell you your query, but I will answer it.`"
Then the priest said he would.
Then Miles proceeded: "`Your question is this,
You would know whether I own that Christ that died at Jerusalem or not?`"
To this the priest, wondering, said: "`Truly that is the question.`"
Then Miles said, "`According to my promise, I will answer it before this court;
in the presence of the Lord God of heaven,
I own no other Christ than Him that died at Jerusalem,
and made a good confession before Pontius Pilate,
to be the light and way that leads fallen man out of sin and evil, up to God eternal,
blessed forevermore.`"
More questions were not asked him, but the jailer was commanded to take him away.
Yet, within a short time the court gave order to release him.

The early ministers in the Society of Friends often encountered much exposure and hardship
in their efforts to fulfill the commissions entrusted to them by their Divine Master.
Some of the early settlers in North Carolina were
men and women who had sought refuge in the wilderness,
from the persecutions to which they were exposed in New England and Virginia.

The first record of a visit to them by any of the ministers of the Society of Friends,
was in the early part of the year 1672.
George Fox and several others, came to this country from England,
by the way of the West Indies, and landed at the Patuxent River in Maryland.
Some of the party went northward, and William Edmundson went to Virginia.
After some service there, he felt it laid upon him to go to Carolina,
and his record of his journey there shows the hardships which the Gospel messengers
to newly settled sections of the country had to encounter in those days.
He says:

Two Friends accompanied me, it being all wilderness,
and no English inhabitants or pathways, but some marked trees to guide people.
The first day`'s journey we did pretty well, and lay that night in the woods,
as we often used to do in those parts.
The next day, being wet weather, we were sorely foiled in swamps and rivers,
and one of the two who were with me for a guide was at a
stand to know which way the place lay we were to go to.
I, perceiving he was at a loss, turned my mind to the Lord, and as He led me,
I led the way.
So we travelled in many difficulties until about sunset,
then they told me they could travel no farther, for they both fainted,
being weak-spirited men.
I bid them stay there, and kindle a fire, and I would ride a little farther,
for I saw a bright horizon appear through the woods,
which travellers take as a mark of some plantation.
I rode on to it, and found it was only tall timber trees without underwood.
But I perceived a small path,
which I followed until it was very dark and rained violently;
then I alighted and set my back to a tree until the rain abated.
It being dark and the woods thick, I walked all night between two trees,
and though very weary, I dared not lie down on the ground,
for my clothes were wet to my skin.
I had eaten little or nothing that day, neither had I anything to refresh me but the Lord.
In the morning I returned to seek my two companions,
and found them lying by a great fire of wood.
I told them how I had fared,
and he that should have been the guide would have persuaded
me that we were gone past the place where we intended,
but my mind drew to the path which I had found the night before.
So I led the way, and that path brought us to the place where we intended, namely:
Henry Phillip`'s house by Albemarle River.

He and his wife had been convinced of the Truth in New England, and came here to live,
and not having seen a Friend for seven years before, they wept for joy to see us.
It being on a First-day morning when we got there,
although I was weary and faint and my clothes wet,
I desired them to send to the people there-away to
come to a meeting about the middle of the day,
and I would lie down upon a bed, and if I slept too long that they should awake me.
Now, about the hour appointed, many people came, but they had little or no religion,
for they came and sat down in the meeting, smoking their pipes.
In a little time the Lord`'s testimony arose in the authority of his power,
and their hearts being reached by it,
several of them were tendered and received the testimony.
After meeting they desired me to stay with them, and let them have more meetings.

One Tems, a justice of the peace, and his wife were at the meeting,
who received the Truth with gladness,
and desired to have the next meeting at their house, about three miles off,
on the other side of the water; so we had a meeting there the next day,
and a blessed time it was, for several were tendered with a sense of the power of God,
received the Truth, and abode in it.

I could stay no longer with them at that time,
for I had appointed a men`'s meeting in Virginia, to be on the Fifth-day of that week,
things being much out of order among them.
I therefore took my leave of them in the love of God,
and began my journey on Third-day morning, with my two fellow travellers.
I had ridden but a few miles before I was seized
with grievous pain and a weakness in my bowels,
occasioned by the great cold I got with those hardships in coming there.
I rode in great pain that day, and at night lay in the wilderness.
Soon after we alighted off our horses, my two fellow travellers,
who should have helped me, fell sick and fainted.
So I was forced to rise, kindle a fire and fodder the horses.
After some time they recovered from their fainting fit.
The Lord was merciful, and bore up my spirit that night,
and the next day we got to Virginia to the men`'s meeting,
and the Lord`'s power was with us,
and Friends received Truth`'s discipline in the love of it,
as formerly they had received the doctrine of Truth,
for which they were great sufferers in the spoiling of their goods,
the governor being a very peevish man, and much set against Truth and Friends.

George Fox also visited this little flock,
and preached the Gospel among the surrounding people in the same year, 1672.
After leaving Pagan`'s Creek, in Virginia, he says:

Our way to Carolina grew worse, being much of it plashy,
and pretty full of great bogs and swamps, so that we were commonly wet to the knees,
and lay abroad at nights in the woods by a fire,
saving one of the nights we got to a poorhouse at Sommertown, and lay by the fire.
The woman of the house had a sense of God upon her.
The report of our travel had reached there,
and drawn some that lived beyond Sommertown to that house,
in expectation to have seen and heard us; but they missed us.
Next day, the twenty-first of the Ninth Month,
having travelled hard through the woods and over many bogs and swamps,
we reached Bonner`'s Creek; there we lay that night by the fireside,
the woman lending us a mat to lie on.

This was the first house we came to in Carolina.
Here we left our horses, over-wearied with travel.
From hence we went down the creek in a canoe to Macocomocock River,
and came to Hugh Smith`'s,
where people of other professions came to see us (no Friends inhabiting
that part of the country) and many of them received us gladly.
Among others, came Nathanial Batts, who had been governor of Roan-oak.
He went by the name of Captain Batts, and had been a rude, desperate man.
He asked me about a woman in Cumberland, who, he said, he was told,
had been healed by our prayers and laying on of hands,
after she had been long sick and given over by the physicians.
He desired to know the certainty of it.
I told him we did not glory in such things,
but many such things had been done by the power of Christ.

Not far from hence we had a meeting among the people, and they were taken with the Truth;
blessed be the Lord!
Then passing down the river Maratick in a canoe, we went down the bay Connie-oak,
to a captain`'s, who was loving to us, and lent us his boat,
for we were much wetted in the canoe, the water flashing in upon us.
With this boat we went to the governor`'s; but the water in some places was so shallow,
that the boat, being loaden, could not swim; so that we put off our shoes and stockings,
and waded through the water a pretty way.
The governor, with his wife, received us lovingly;
but a doctor there would needs dispute with us.
And truly his opposing us was of good service,
giving occasion for the opening of many things to
the people concerning the Light and Spirit of God,
which he denied to be in everyone; and affirmed it was not in the Indians.
Whereupon I called an Indian to us, and asked him, "`Whether or no, when he did lie,
or do wrong to anyone, there was not something in him, that did reprove him for it?`"
He said: "`There was such a thing in him that did so reprove him;
and he was ashamed when he had done wrong, or spoken wrong.`"
So we shamed the doctor before the governor and people;
insomuch that the poor man ran out so far,
that at length he would not own the Scriptures.
We tarried at the governor`'s that night;
and next morning he very courteously walked with
us himself about two miles through the woods,
to a place where he had sent our boat about to meet us.
Taking leave of him, we entered our boat, and went about thirty miles to Joseph Scot`'s,
one of the representatives of the country.
There we had a sound, precious meeting; the people were tender,
and much desired after meetings.
Wherefore at a house about four miles further, we had another meeting;
to which the governor`'s secretary came, who was chief secretary of the province,
and had been formerly convinced.

I went from this place among the Indians, and spoke to them by an interpreter,
showing them, "`That God made all things in six days, and made but one woman for one man;
and that God did drown the old world because of their wickedness.`"
Afterwards I spoke to them concerning Christ, showing them that "`He died for all men;
for their sins, as well as for others; and had enlightened them as well as others;
and that if they did that which was evil He would burn them;
but if they did well they should not be burned.`"
There was among them their young king and others of their chief men,
who seemed to receive kindly what I said to them.

Having visited the north part of Carolina,
and made a little entrance for Truth upon the people there,
we began to return again towards Virginia, having several meetings in our way,
wherein we had good service for the Lord, the people being generally tender and open;
blessed be the Lord!
We lay one night at the secretary`'s, to which we had much ado to get;
for the water being shallow, we could not bring our boat to shore.
But the secretary`'s wife, seeing our strait, came herself in a canoe,
her husband being from home, and brought us to land.
By next morning our boat was sunk, and full of water; but we got her up, mended her,
and went away in her that day about twenty-four miles, the water being rough,
and the winds high; but the great power of God was seen,
in carrying us safe in that rotten boat.
In our return we had a very precious meeting at Hugh Smith`'s;
praised be the Lord forever!
The people were very tender, and very good service we had among them.
There was at this meeting an Indian captain, who was very loving;
and acknowledged it to be truth that was spoken.
There was also one of the Indian priests, whom they called a Pauwaw,
who sat soberly among the people.
The ninth of the Tenth Month we got back to Bonner`'s Creek,
where we had left our horses; having spent about eighteen days in the north of Carolina.

In his Memoirs, Joseph Hoag, records his experience in attending his religious meetings.
He says:

We found it our duty, when at home, to be faithful in attending our meetings,
so that the two first years we used to walk over four miles, twice a week, spring,
summer and fall.
In winter I used my oxen for a team, taking all our family with us.
Starting about sun-rise, we could get to meeting seasonably, and home about sunset.
When I got able to buy and keep a horse for your mother to ride, I felt rich.
Oh!
Dear children, I want, if any or all of you should arrive at easy circumstances,
that you remember from where you have risen,
and always let a thankful and humble mind be your inner garment,
that the blessing of the dew of heaven may rest upon you.

A love of the attendance of meetings has been a characteristic of all true Quakers.
Samuel Smith mentions his visiting Dorothy Owen, in North Wales,
a young women noted for her excellent gift in the ministry.
He says: "`She had been several times to the Yearly Meeting at London,
more than two hundred miles on foot,
and to Quarterly Meetings frequently from twenty to fifty miles.`"
Our late dear Friend, that honest minister of the Gospel, Ellen McCarty, of Elkland,
Lycoming County, Pennsylvania, often walked to the next settlement to attend meeting,
a distance of five miles, carrying a babe with her.
On one occasion in winter,
she remained all night in the neighborhood of the meetinghouse,
and in the morning found that snow had fallen to a considerable depth.
She had two of her little boys with her, who assisted her in turns with the babe,
until the infant became fretful, and would cry whenever either of the brothers took it,
and the difficulty of walking through the snow with such a weight in her arms,
made the journey very toilsome to her, and she had frequently to sit down,
overcome with fatigue.
Harassed in body and tried in mind,
she declared aloud she would not go to the meeting again.
She reached home safely, and things passed on during the week as usual,
but on the next Seventh-day she found a weight of darkness,
and an uncommon depression upon her spirits.
On feeling this, she sat down in quiet, anxiously seeking the cause.
Her mind was soon illuminated clearly to discern the truth,
and she perceived a hand pointing to the meetinghouse,
while she remembered the hasty resolution she had formed in her own impatient will.
She saw her error,
took fresh courage to encounter the difficulties and trials of her situation,
and the next day contentedly trudged with her usual load the five miles to attend
her meeting and seek for spiritual strength to sustain her own soul.
She was careful hence forward to be diligent in the performance of this,
as well as her other duties, and in consequence thereof grew in the root of Life,
became an able minister of the Gospel, and was made useful in the household of faith.

"`Be faithful unto death, and I will give you a crown of life`" Rev. 2:10.
