== Chapter VIII. Communion With God

The whole tendency of the teaching and practice of
our early Friends was towards communion with God.
When they met for Divine worship they endeavored to draw near unto Him in feeling,
and waited to feel the movings of his Spirit.
And this was a marked characteristic of their every day life.
Hence they knew more of the workings of his power upon them,
and were more abundantly favored with the revelations of his will,
than is the common experience of those who are less spiritually minded.
The records of their lives present very many remarkable
and interesting illustrations of this;
and show that the spirit of prophecy has not ceased to visit mankind.

In the Journal of the life of that worthy Friend, William Edmundson,
is contained an account of a visit paid by him to the town of Londonderry,
and the remarkable testimony which he delivered to its inhabitants,
under the constraining power of the Spirit of the Lord.
The narrative reminds one of the warnings uttered in ancient
days by the prophets of Israel to a backsliding people.

[.embedded-content-document]
--

Another time I was moved of the Lord to go from my own house to Londonderry,
to warn them to repent, or the Lord would bring a scourge over them.
So in obedience to the Lord I went,
and when I came there it happened to be a day of humiliation, as they called it,
being at the time the plague was in London.
They were gone to their worship at the cathedral, and I was moved of the Lord to go there.
When I came to the door, the man who used to ring the bells met me,
and took me by the hand, and led me near the pulpit, where the bishop was preaching.
He thought he had got a Presbyterian convert, and did not take off my hat,
until he saw the people gaze at me, observing which, he took my hat off and laid it by.
I stood there until the bishop had done preaching; the peoples`' eyes were on me,
and I spoke what the Lord gave me to say, warning them to repent,
or the Lord would bring a scourge over them, and scale their walls without a ladder.
The bishop called to the mayor and officers to take me away,
but the dread of the Lord`'s power was over them; they all sat still,
and did not molest me.
When I had delivered the Lord`'s message, I went towards the door,
where the man who led me in met me, and took me by the hand,
having my hat in his other hand; he led me to the door, put my hat on my head,
and bid God speed me well.

I went to my lodging, which was a public-house, kept by John Gibson,
who with his wife were convinced of the Truth.
There I was moved to write a paper to the bishop and magistrates,
and the next day I went to the bishop`'s house with it, he living in the city.
I knocked at the door,
and the man who led me in and out of the worship house the day before, opened the door,
and made his defense, that he did me no harm at the church.
I told him he did well and asked him for the bishop.
He said he was gone to dinner, and a great many gentlemen with him;
for there was a great meeting of them;
and he told me it would be better to come when they had dined.

I went back to my lodging, and in a little time came again, and they having then dined,
I sent my paper to them, and they sent a priest to call me up.
As I was going up the stairs, the word of the Lord said unto me,
I will make you as a wall of brass.
There were the bishop, the governor, the mayor, several justices,
priests and others in a great dining room; the bishop sat with his hat on,
and the rest all stood bare-headed.
When I came into the room, the bishop rose up from his seat, put off his hat,
and met me with several low bows; but I was as a wall of brass,
and stood in the power of the Lord, that was with me, which smote him.
Then he sat down, and told me that what I said at their worship the day before was true,
and he preached the same, and pointed to two of the priests, saying,
they preached the same, therefore there was no need of me.
I told him, the more preachers of Truth the better, and there was need enough;
and he being a bishop, ought to encourage me.
He said he must know what I came to the city for, and who sent me,
and he bid the mayor examine me.
So the mayor came from among the rest, and asked me where I dwelt?
I told him in the Queen`'s County.
He asked what trade I was?
I told him, a ploughman.
He asked my business there and who sent me?
I told him the Lord Jesus Christ sent me, to warn them to repent,
or He would lash them with his judgments.
As I declared this, the Lord`'s power reached him, and he could not refrain from tears,
being a tender-spirited man; so he went back behind the rest.

The bishop seeing this, was amazed,
and bid two of his waiting men take me into the buttery, and make me eat and drink.
They took me by the arms down the stairs, and bid me go into the buttery to eat and drink.
I told them I would not eat or drink there; but they urged me, saying,
I heard their lord command them to make me eat and drink.
I asked them if they were Christians at that house.
They said yes; then, said I, let your yes be yes; and your no be no,
for that is Christ`'s command.
I said, I will not eat or drink here, and you take no notice of it,
being accustomed to break your "`yes`" and "`no`". They stood silent and let me go,
for the Lord`'s power astonished and was over them all.

I went to my lodging, and was moved of the Lord to write a paper,
and put it on the gates of the city,
and to declare the Lord`'s message through the streets.
Accordingly I wrote a paper that evening,
and in the morning went first to the mayor and told him the message I had to the city.
He said the bishop had chid him the day before, because he did not send me to prison;
but he did not intend to do it, so long as the law would bear him harmless,
and wished he had me living by him,
and then I should soon have another to help to suppress wickedness.
I went from the mayor, and beginning near Water-gate,
sounded the Lord`'s message through the streets; it was dreadful to the people,
and several ran as if before naked swords.
As I came near the main guard, a soldier being at the door mocked,
but in the dread of the Lord`'s power I looked in at the guard-house door, and cried,
Soldiers, all repent!
The soldiers on the guard were smitten as men affrighted,
for the power of the Lord was mighty, in which I performed this service;
and when I had done, I put a paper on the gates, as the Lord moved me.
Being clear, I left the city, and visited Friends`' meetings in the north,
and they admired the Lord`'s goodness that carried
me through that service without a prison.

--

The city of Londonderry was one of the Protestant strongholds in Ireland;
and during the civil war which was waged in that country
after the coming to England of William of Orange,
and the expulsion of James 2, it declared in favor of William and Mary,
and was besieged by the forces of James.
This was in 1689, twenty-four years after William Edmundson,
under a consciousness of approaching danger, had called its inhabitants to repentance.
The account of the siege which follows, is condensed from [.book-title]#Macaulay`'s History#:

[.embedded-content-document]
--

After ineffectual attempts to persuade the inhabitants to surrender,
the besieging force began to batter the town.
It was soon on fire in several places.
Roofs and upper stories of houses fell in and crushed the inmates.
During a short time the garrison,
many of whom had never before seen the effect of a cannonade,
seemed to be discomposed by the crash of chimneys,
and by the heaps of ruins mingled with disfigured corpses.
But familiarity with danger soon produced its natural effect,
and the spirits of the people revived.
Two months passed away, marked with much hard fighting.
There had been sallies and skirmishes with various success;
but on the whole the advantage had been with the garrison.
But before the hope of reducing the town by main force was relinquished,
it was determined to make a great effort.
The point selected for assault was an outwork called Windmill Hill,
which was not far from the southern gate.
Religious stimulants were employed to animate the courage of the forlorn hope.
Many volunteers bound themselves by oath to make
their way into the works or to perish in the attempt.
Captain Butler, son of the lord Mountgarret,
undertook to lead the sworn men to the attack.
On the walls the colonists were drawn up in three ranks.
The office of those who were behind was to load the muskets of those who were in front.
The Irish came on boldly and with a fearful uproar,
but after long and hard fighting were driven back.
The women of Londonderry were seen amidst the thickest fire
serving out water and ammunition to their husbands and brothers.
In one place, where the wall was only seven feet high,
Butler and some of his sworn men succeeded in reaching the top;
but they were all killed or made prisoners.
At length, after four hundred of the Irish had fallen,
their chiefs ordered a retreat to be sounded.

Nothing was left but to try the effect of hunger.
It was known that the stock of food in the city was but slender.
Every avenue for the introduction of provisions was carefully guarded.
A heavy boom was stretched across the river to prevent the access of vessels.

--

Many of the inhabitants died of famine and disease before relief came.
Half a pound of tallow and three-quarters of a pound of salted
hide were the rations dealt out to each fighting man.
A fleet of vessels from England loaded with supplies arrived on the coast,
but for some time did not venture to ascend the Foyle.

Amid such distress,
it is not to be doubted that the prophetic admonitions of
William Edmundson must often have been brought to mind.
This is indicated by his own remark at the conclusion of the account of his visit:
"`The people of Londonderry afterwards remembered these warnings,
and spoke of them in their great distress in the last siege,
when thousands died for lack of bread, and through other miseries,
the Lord having scaled their walls without a ladder,
yet allowed not their enemies to get the city with force of arms, or scaling-ladders.
And thus the warning before given them was fulfilled.`"

The foresight granted to William Edmundson, on his visit to Londonderry,
was not a solitary instance.
Many of our early Friends were favored at times with a sense or sight of coming events.
George Fox having gone to Hampton Court to lay before Oliver
Cromwell the sufferings of Friends from unjust persecutions,
met him as he rode at the head of his life guards, and says:
"`I saw and felt a waft of death go forth against him,
and when I came to him he looked like a dead man.`"
In a few days Oliver died, and soon after, Charles the Second came to the throne.
George Fox says: "`I had a sight and sense of the king`'s return a good while before,
and so had some others.
I wrote to Oliver several times, and let him know,
that while he was persecuting God`'s people,
they whom he accounted his enemies were preparing to come upon him.`"
Thomas Aldam and Anthony Pearson were moved to go through all the jails in England,
and to get copies of Friends`' commitments under the jailers`' hands,
that they might lay the weight of their sufferings upon Oliver Cromwell.
And when he refused to give order for the releasing of them,
Thomas Aldam was moved to take his cap off his head, and rend it in pieces before him,
and to say to him.
"`So shall your government be rent from you and your house.`"

In 1653, George Fox relates: "`Being one day at Swarthmore Hall,
when judge Fell and justice Benson were talking of the news,
and of the parliament then sitting (called the long parliament),
I was moved to tell them: Within two weeks the parliament should be broken up,
and the speaker plucked out of his chair.
And within two weeks justice Benson told judge Fell
that now he saw George was a true prophet,
for Oliver had broken up the parliament.`"

William Edmundson gives a lively narrative of how he was led of the Lord,
as a horse with a bridle, to perform a service for his Divine Master.
He says:

[.embedded-content-document]
--

About this time there were two women Friends from London, Anne Gould and Julian Westwood,
who came to Dublin and travelled to Londonderry, having some drawings to that place.
After some service for the Lord there, they travelled to Colerain,
so through the Scotch country to a place called Clough, all on foot, in winter time,
wading rivers and dirty, miry ways.
Anne Gould, being a tender woman, was much spent, and stayed at Clough,
the enemy persuading her that God had forsaken her,
and that she was there to be destroyed, so that she fell into despair;
but I knew nothing of them.

At this time my brother and I were at a fair in Antrim; being late there,
we proposed to lodge that night at Glenavy, six miles on our way homeward.
Before we got to Glenavy I was under a great exercise of spirit,
and the word of the Lord came unto me that my shop was in danger to be robbed that night.
I told my brother of it, so we concluded to travel home:
and went about a mile beyond Glenavy; but my spirit was still under a great exercise,
the word of the Lord moving me to turn back towards Clough.
I was brought under a great exercise, between these two motions,
to travel back and my service unknown; and my shop, on the other hand,
in danger to be robbed, which brought me into a great strait, for fear of a wrong spirit.
I cried to the Lord in much tenderness of spirit, and his word answered me,
that which drew me back should preserve my shop, so we went back to Glenavy,
and lodged there.
That night I slept little, because of many doubts about the concerns; on the other hand,
I dared not disobey, for I knew the terrors of God for disobedience.

The next morning my brother went home, but I rode back to Antrim.
Towards evening I came to Clough, and took up my lodging at an inn.
When I came into the house I found Anne Gould in despair, and Julian Westwood with her,
but when they knew who I was and heard my name (for they had heard of me before),
the poor, disconsolate woman revived for joy and gladness, and got up,
for she was in bed, overwhelmed under trouble of mind.
I saw then that my service of coming there was for her sake.
When we came to discourse of matters,
I told her how I was brought there by the good hand of God,
led as a horse by the bridle to the place where they were;
they therefore greatly rejoiced and praised God:
the tender woman was helped over her trouble,
and she saw it was a trial of great temptations she had laid under.

They had a mind to go to Carrickfergus,
to my house and to Dublin to take shipping for England,
but neither of them would undertake to ride single,
therefore I was forced the next day to carry them behind me,
first one and then the other.
When we came in very foul way, I set them both on horseback,
and waded myself through dirt and mire in my boots,
holding them both on horseback with my hands.
We came to Conyers that night and lodged there.
The next day I got them to Carrickfergus, and there leaving them, rode home,
and sent my brother and two horses to bring them to my house.

When I came home, I inquired about my shop, whether it had been in danger of robbing.
They told me the night I was under that exercise about it,
the shop window was broken down and fell with such
violence on the counter that it awakened our people,
and the thieves were affrighted and ran away.
So I was confirmed it was the word of the Lord that said "`that which drew me back should
preserve my shop,`" and I was greatly strengthened in the word of life,
to obey the Lord in what He required of me.
When these two women had stayed some time at my house, and visited Friends,
my brother sent them on horseback to Dublin, so they went for England.

--

In 1672, William Edmundson returned to Ireland from a visit in America.
While he was at sea on that voyage, he says: "`As I lay retired in my cabin,
a heavenly vision came over my senses, and in it appeared two very poor,
ill-favored cows, which arose under my plough-beam, as I was holding my plough.
Whereupon I sat up in my cabin and considered the matter.
Then the word of the Lord came to me and said, '`The two cows are two years;
for these shall be two very dear years,
and inasmuch as the cows arose under the ploughshare,
they shall fall on corn and cattle.`' This came to pass in a very little while:
in the time of great plenty, contrary to men`'s reason, cattle died abundantly,
and the price of corn rose to an astounding height,
so that many were famished for lack of bread,
and several families who had lived plentifully were forced to go a begging,
their corn being spent and cattle dead.
Several families who were ashamed to beg,
shipped themselves for servants to the West Indies to get food.`"

When George Fox was at Gainsborough in 1652,
a man charged him with having said that he was Christ.
He says this "`put the people into such a rage,
that they had much to do to keep their hands off me.
I was moved of the Lord to stand up upon the table, in the eternal power of God,
and tell the people, '`That Christ was in them, except they were reprobates;
and that it was Christ, the eternal power of God,
that spoke in me at that time unto them;
not that I was Christ.`' I called the accuser Judas,
and was moved to tell him that Judas`' end should be his.
The Lord`'s power came over all, and quieted the minds of the people,
and they departed in peace.
But this Judas shortly after hanged himself.`"

When Martha Routh was in America on a religious visit in 1795,
and was travelling in the interior of Virginia, she became very sick,
through the oppressive heat of the weather, and the exposure to which she was subjected.
If she had been at home,
she would have thought it right to remain quietly at home in her chamber.
But she went to meeting, where she sat a long time in silent exercise.
When it appeared nearly time to close the meeting, she was led into a line of labor,
in which she says: "`I felt healing virtue, both of body and mind.`"

The experience of the servants of the Lord confirms the testimony of the prophet Joel:
"`I will pour out my spirit upon all flesh;
and your sons and your daughters shall prophesy, your old men shall dream dreams,
and your young men shall see visions.`"
The apostle Peter declared that the wonderful pouring forth of the spirit,
which was witnessed at Jerusalem on the day of Pentecost,
was the fulfilment of this prophecy;
but it was by no means limited to that remarkable event; but from that day to this,
every generation has partaken of the blessing predicted by Joel,
and has been favored with the precious visitations of the spirit of God,
reproving for evil, and pointing out to the obedient mind,
the way in which we should walk to obtain the Divine favor.
These visitations are no part of our natural faculties,
but come directly from the Source of every good and perfect gift.
It was through their enlightening power that the prophets of old were
enabled to foretell future events and to perform wonderful miracles.
Under the same Divine influence,
Peter and John were enabled to heal the imperfect
man--not by any power or holiness of their own.
For, when they were examined by the rulers of the people, Peter,
filled with the Holy Spirit, declared: "`Be it known unto you all,
and to all the people of Israel, that by the name of Jesus Christ of Nazareth,
whom you crucified, whom God raised from the dead, even by Him,
does this man stand here before you whole.`"

It seems to us a mistaken notion to suppose that everything
miraculous has been withdrawn from the church;
for so numerous are the cases in which the Lord`'s
servants are preserved from threatened dangers,
which their own wisdom could not have avoided; or led in paths that they have not seen,
to the accomplishment of the Divine purposes;
or experience their petitions to the Almighty graciously answered;
that there are probably few if any persons of religious
experience who have not known such in their own lives.
We regard these favors as among the common mercies of the Lord,
restricted to no denomination of people,
but bestowed more abundantly on those who are most fervent in spirit.
Among the early members of our Society were many
who lived in close communion with their Creator,
and the records of their lives contain many remarkable incidents.
In the [.book-title]#Journal of George Fox# he mentions attending a meeting at Worminghurst in Sussex,
England, when James Claypole, of London,
was suddenly taken very ill with a violent fit of stone.
"`When I heard it,`" says George Fox:

[.embedded-content-document]
--

I was much exercised in spirit for him, and after I had spoken a few words to him,
to turn his mind inward, I was moved to lay my hand upon him,
and prayed the Lord to rebuke his infirmity.
As I laid my hand on him, the Lord`'s power went through him,
and by faith in that power he had speedy ease, so that he quickly fell into a sleep.
The next day he was so well, that he rode five and twenty miles with me in a coach,
though he used formerly (as he said) to be sometimes two weeks,
sometimes a month with one of these fits of the stone.
But the Lord was entreated for him and by his power soon gave him ease at this time;
blessed and praised be his holy name therefore.

--

In the year 1652, when George Fox was at Ulverstone, he was taken out of the town,
at the instigation of a persecuting justice;
and when the officers in charge had come to the common,
they "`Gave me some blows over my back with their willow rods,
and thrust me among the rude multitude; who having furnished themselves with stones,
hedge-stakes, holm or holly bushes, fell upon me, and beat me on my head,
arms and shoulders, till they had deprived me of sense;
so that I fell down upon the wet common.
When I recovered again, and saw myself lying in a watery common,
and the people standing about me, I lay still a little while,
and the power of the Lord sprang through me, and the eternal refreshings revived me;
so that I stood up again in the strengthening power of the eternal God,
and stretching out my arms among them, I said, with a loud voice, '`Strike again,
here are my arms, my head, and my cheeks.`' There was in the company a mason,
a professor +++[+++of religion], but a rude fellow,
who with his walking rulestaff gave me a blow with
all his might just over the back of my hand,
as it was stretched out; with which blow my hand was so bruised, and my arm so benumbed,
that I could not draw it to me again; so that some of the people cried,
'`He has spoiled his hand from ever having the use of it any more.`' But I looked
at it in the love of God (for I was in the love of God to all that persecuted
me) and after a while the Lord`'s power sprang through me again,
and through my hand and arm,
so that in a moment I recovered strength in my hand and arm in the sight of them all.`"

George Fox says, in 1653 he was at a meeting where Richard Myer was,
who had been long lame of one of his arms.
"`I was moved of the Lord to say unto him among all the people,
'`Stand up upon your legs,`' for he was sitting down; and he stood up,
and stretched out his arm that had been lame a long time and said,
'`Be it known unto you, all people,
that this day am I healed!`' He soon after came to Swarthmore meeting,
and then declared how the Lord had healed him.`"

In 1675 as George Fox was travelling north to Swarthmore from London,
at Cassel "`A woman brought her daughter for me to see how well she was;
putting me in mind, that when I was there before,
she had brought her to me much troubled with the king`'s evil +++[+++scrofula],
and had then desired me to pray for her.
Which I did, and she mended upon it.
Praised be the Lord.`"

In 1649, he says:
"`At Mansfield Woodhouse there was a distracted woman under a doctor`'s hand.
He was about to let her blood, she being first bound, and many people about her,
holding her by violence; but he could get no blood from her.
I desired them to unbind her and let her alone.
So they did unbind her,
and I was moved to speak to her and in the name of
the Lord to bid her be quiet and still;
and she was so.
The Lord`'s power settled her mind and she mended.`"
He adds:
"`Many great and wonderful things were wrought by the heavenly power in those days;
for the Lord made bare his omnipotent arm,
and manifested his power to the astonishment of many;
by the healing virtue whereof many have been delivered from great infirmities,
and the devils were made subject through his name;
of which particular instances might be given beyond
what this unbelieving age is able to receive or bear.
Let the honor and praise of all his works be ascribed to the Lord alone.`"

"`At Twycross in Leicestershire there was a great man that
had long lain sick and was given over by the physicians.
Some friends in the town desired me to visit him.
I went up to him in his chamber, and spoke the word of life to him,
and was moved to pray by him; and the Lord was entreated and restored him to health.`"

At Baldock, in Hertfordshire,
he found a woman who was very ill and was moved of the Lord to speak to her,
and He raised her up again, to the astonishment of the town and country.

When in America on a religious visit in 1672, George Fox was at a meeting in Maryland;
he says:
"`After the meeting a woman came to me whose husband was one of
the judges of that county and a member of the Assembly there.
She told me her husband was sick, not likely to live,
and desired me to go home with her to see him.
It was three miles to her house, and I being just come now out of the meeting,
it was hard for me then to go; yet considering the service, I got a horse, went with her,
visited her husband, and spoke what the Lord gave me to him.
The man was much refreshed, and finely raised up by the power of the Lord;
and afterwards came to our meetings.`"

The expression already quoted from George Fox,
that the Lord`'s power "`sprang through me`", by which he was physically revived,
is similar to the language of Thomas Story,
who had been from home on a journey in the cause of Christ,
and had taken cold so that he was hoarse; so that he says:
"`I spoke with difficulty when I went into the house;
yet through a very sensible operation of the Divine truth and the healing virtue thereof,
under which I sat in silence for about half an hour, I was perfectly healed,
by which I was forever confirmed in the belief of
the miracles of Christ recorded in the Holy Scripture.`"

Many of our early Friends lived in such close communion with the Lord
that they were favored with an insight into the feelings of others,
and a degree of Divine light and power that was little less than miraculous.

Among these was Miles Halhead.
He is mentioned among the zealous preachers who went forth about the year 1652,
in company with John Audland, Edward Burrough and others.
He was the first of the Friends who was imprisoned in Kendal.

[.embedded-content-document]
--

Once he went to Swarthmore to visit his friends and to assist at their meeting;
by the way, he met the wife of the justice, Thomas Preston,
and because he passed by her quietly, without the ordinary way of greeting,
she grew so offended, that she commanded her man to go back and beat him; which he did.
At which Miles being kindled with zeal, said to her: "`O you Jezebel!
You proud Jezebel!
Can you not permit and allow the servant of the Lord to pass by you quietly?`"
She then held forth her hands, as if she would have struck him, and spit in his face,
saying: "`I scorn to fall down at your words.`"
This made Miles say again: "`You proud Jezebel,
you that harden your heart and brazen your face against the Lord and his servant,
the Lord will plead with you in his own time, and set in order before you,
the things that you have done this day to his servant.`"
And so he parted with her and went to Swarthmore.

About three months after this, he felt himself moved to go and speak to her;
and when he came to Houlker Hall, he asked for Thomas Preston`'s wife;
she then coming to the door, and Miles not knowing her,
asked her if she was the woman of the house, to which she said, "`No,
but if you would speak with Mrs.
Preston, I will entreat her to come to you.`"
Then she went in, and coming back with another woman, said:
"`Here is Mistress Preston;`" but then it was manifested
to him that she herself was the woman.
It is true, as has been said, some time before he had seen her on the way,
and spoken to her; but it may be, she was then in so different a dress,
that by reason thereof he did not know her; yet firmly believing that it was she,
he said, "`Woman, how dare you lie before the Lord and his servant?
You are the woman I came to speak to.`"
And she being silent, not speaking a word, he proceeded, "`Woman,
hear what the Lord`'s servant has to say unto you; O woman,
harden not your heart against the Lord; for if you do,
He will cut you off in his sore displeasure; therefore take warning in time,
and fear the Lord God of heaven and earth, that you may end your days in peace.`"
Having said this, he went away, and she, despite her pride, did him no harm,
having been withheld without knowing by what.

About three years after she had made her man beat Miles,
it happened that as he was riding from Swarthmore, near to Houlker Hall,
he met with a person who said to him: "`Friend, I have something to say unto you,
which has lain upon me this long time.
I am the man that, about three years ago, at the command of my mistress,
did beat you very sore; for which I have been very much troubled,
more than for anything that ever I did in all my life; for truly, night and day,
it has been often in my heart, that I did not well in beating an innocent man,
that never did me any hurt or harm.
I pray you forgive me, and desire the Lord to forgive me,
that I may be at peace and quiet in my mind.`"
To this Miles answered: "`Truly friend, from that time to this day,
I never had anything in my heart against you, nor your mistress, but love.
The Lord forgive you both; I desire that it may never be laid to your charge;
for you knew not what you did.`"

Travelling once in Yorkshire, he came to Skipton, where declaring the word of Truth,
he was so sorely abused and beaten, that he was laid for dead; nevertheless,
by the Lord`'s power, he was healed of all his bruises,
and within three hours he was healthy and sound again,
to the astonishment of those that had so abused him,
and to the convincing of many that beheld him.

Then he went to Bradford, Leeds and Halifax,
where he also declared the doctrine of Truth among the people;
but not without meeting with great persecution.

From there he came to Doncaster, and there went on a First-day of the week,
to a steeple-house, where, after the worship was done, he spoke to the priest and people;
but they, instead of hearkening to what he said, fell upon him in a great rage,
and drove him out of the town; and he being sorely bruised, they left him for dead.
But before his going from home, he had been firmly persuaded,
that the Lord would preserve him in all dangers;
and it happened so to him according to his belief, for he got up again,
and went to a Friend`'s house, where he laid himself down upon a bed.
But not long after, he felt a very strong motion to go to a certain chapel,
and there to declare the word of the Lord; forthwith he felt also an inward assurance,
that if he gave up to do so, the Lord would heal him from his bruises.
Then he rose, as well as he could, and came downstairs with great difficulty,
by taking hold of the walls for a stay, and going out, he began to mend by degrees;
and coming at length into the chapel, he spoke as he was moved;
and when he had cleared himself, he went back to the house from which he came,
and the Lord made him sound of all his bruises.

From there he went to York, and there spoke to the lord mayor,
and other rulers of that city, and passing through Yorkshire,
he went into several steeple-houses, to exhort the people;
and though he met with great hardships, yet he was supported by an invisible hand.
So being clear of that country, he returned to his house at Mountjoy, in Underbarrow,
in the county of Westmoreland.

But his going thus often from home, was an exceedingly great cross to his wife,
who in the first year of his change, not being of his persuasion,
was much troubled in her mind, and would often say from discontent:
"`Would to God I had married a drunkard, then I might have found him at the ale-house;
but now I cannot tell where to find my husband.`"
But after the space of a year it pleased the Lord to visit her.
She had a little son of about five years of age, which child she loved extraordinarily,
insomuch that she thought it was her only delight and comfort;
but it happened that this darling died, and sometime after,
she spoke thus to her husband: "`Truly, husband, I have something to tell you:
one night being in bed, mourning and lamenting with tears in my eyes,
I heard a voice saying, '`Why are you so discontented concerning your husband?
I have called and chosen him to my work; my right hand shall uphold him.
Therefore be content and pleased, that he serve me,
and I will bless you and your children for his sake,
and all things shall prosper that you shall take in hand.
But if you will not be content, but grudge and murmur,
and repine against me and my servant, whom I have chosen to do my work,
I will bring a greater cross upon you.`' These words
being fresh in my mind both night and day,
I often said within myself, What cross can this be,
that would be greater than the absence of my husband?
But for all this I could not be content: all the joy I had, or could find,
was in our little boy, who would often, when he saw me weeping and mourning,
take me about my neck and say: My dear mother, pray be content,
for my father will come home in a little time.
This child would often comfort me in this manner; but for all that I could not be content.
Not long after it pleased the Lord to take from me this my only son, my chiefest joy.
Then the voice which I had heard came into my mind,
and I perceiving that this was the cross which the Lord would bring upon me,
smote upon my breast, and said within myself,
that I was the very cause why the Lord had taken away my little son.
A great fear then seizing upon me, I said, O Lord, my God!
Give me power to be content to give up my husband freely to do your will, lest O Lord,
you take away from me all my children.
From that time I never dared oppose you, my husband, any more in the work of the Lord,
for fear that his judgments might also fall upon me and my children.`"
This served not a little to strengthen and encourage Miles.

Some time after, walking in his garden,
he felt a motion to go to Stanley chapel in Lancashire.
Now though he might expect to meet with rude entertainment there,
yet he consulted not with flesh and blood, but went to the aforesaid chapel.
Being come, he was not permitted to enter; but the door was violently turned against him.
Then he walked in the yard till the worship was done,
and the people that came out fell upon him with great rage,
and one captain William Rawlinson took hold of his arms and shoulders,
and calling another man to take him by the feet and legs, they threw him over the wall;
by which fall he was exceedingly bruised, so that he had much to do to get home.
By the way it was inwardly said to him that he must
be content with what was befallen him that day,
and that if he was faithful in what the Lord required of him then,
He would heal him again.
Being come home, he waited upon the Lord to know his will.
In this resignedness, within six days, he was moved to go to Windermore steeple-house,
and it was, as it were said unto him: "`Fear not the face of man,
but speak the word of the Lord freely;
then you shall be made sound again of all your bruises.`"
So he went to the said steeple-house,
and having spoken the word of the Lord to the priest and people,
without receiving any abuse, was healed that day of his sore bruises.

--

During the last war in which this country was engaged with England,
Rebecca Scarlett had an appointed meeting in Pittsburg,
at which many of the principal inhabitants were present,
and in which she was led in a remarkable manner to sympathize with,
and to offer consolation to, some deeply exercised persons present.
After meeting,
a very interesting woman of middle age pressed Rebecca
and her companions to take dinner with her,
assuring her that she could not take any denial.
They finally concluded to go home with her,
and after dinner their hostess sought an opportunity for unburdening
her mind of the sorrows which had long oppressed her.
She told Rebecca that her husband was an officer in the United States army,
and that he was engaged in the active services and dangers of that dreadful employment,
and added, that to crown her unhappiness,
her only son had been drafted and marched off to be exposed
to like dangers in the same unchristian occupation.
She said she had no expectation, and scarcely dared to hope,
that she would ever see either of them again,
and the thought that those so dear to her would probably
lose their lives while thus engaged,
was more than she could bear; and she added:
"`Under your ministry this morning I was for the first time a little comforted,
and I could not be satisfied without telling you so, under my own roof.`"
After they had sat together awhile in solemn silence, Rebecca said:

[.embedded-content-document]
--

We are on the eve of a great change: this war is nearly at an end,
and peace will soon visit our country,
and I hope you will not be too much discouraged on your own account,
or on behalf of those so dear to you,
for I believe that I am authorized to assure you that your
husband`'s life will be spared to your solicitude;
and that he will be safely restored to you.
And as for your son, grieve no more for him on this account,
for he will not even see a battle-field, and will soon return to his home and to you.

--

The woman seemed deeply affected,
and it was evident that a great struggle was taking place in her heart,
and that she scarcely dared to open the door to hope.
At last she said: "`Oh can I--Oh, dare I believe all this?
May I, indeed, once more hope that the Lord will have so much mercy on me and on them,
which are so dear to me, as to restore us to each other?`"
Rebecca repeated her conviction that it would be even so,
and they parted in much unity of feeling; the woman asking her address, and adding,
that if her husband and son were indeed restored to her,
then she would certainly write and inform her of it.

After Rebecca`'s return home she was deeply tried on account of the foregoing circumstance;
for the tempter got in and charged her with speaking without authority,
insinuating that it was only her sympathy with the poor,
distressed woman that had led her to stamp her wishes with the authority of prophecy.
Our dear Friend was indeed sadly buffeted and sorely tried,
thinking what a stumbling-block she would become to that
poor woman and to others who might hear of it,
and that it would certainly bring reproach upon the religious Society of Friends,
and upon Truth itself.
Rebecca mentioned that in one of the many sorrowful
meetings which she attended after her return,
she was more than usually cast down on this account,
for she felt as if she had cast away the shield of faith, and that hope too was dead,
and that she never would be able to hold up her head again.
But when she got home from meeting that day,
she found a letter from that grateful woman awaiting her return,
fully confirming every word which Rebecca had uttered, doubtless under Divine authority.

John Richardson relates some instances in which the Holy Spirit manifested to
him in a striking manner the condition of some with whom he came in contact.
He says:

[.embedded-content-document]
--

During my stay in one of the Jerseys, a great weight, more than usual,
seized upon my spirit, as I sat in a meeting, and under a sense of the same,
my cries ascended unto the Lord, the Fountain of all tender mercies,
that He would please to show me what was the cause of that
great power of darkness which did so oppress my spirit.
And it pleased the Lord to show me,
that a man there had been guilty of some gross wickedness.
And when it clearly appeared to be required of me to express it publicly,
it became a very great exercise to me,
and I had some reasonings before I gave up to make it public
to that large meeting of Friends and other people.
I labored under it till towards the conclusion of the meeting,
but finding my peace concerned very nearly in the matter,
I stood up in the gallery and said:
"`Under a sense of some gross wickedness committed by some person not far from me,
has my spirit been borne down, which wickedness will, in a short time break forth,
to the dishonor of Truth and the grief of Friends.`"
A great man who sat in the gallery by me, started up,
and seated himself upon the rail of the gallery, with his eyes fixed on me,
and in the Lord`'s dread, I fastened my eyes on him, and said:
"`We have a common maxim in old England, '`Touch a galled horse`'s back,
and he will kick,`' and I am of the opinion he that kicks is not clear.`"
He got down as fast as he could out of my way,
for he not only prevented me from the view of the meeting by sitting there,
but his uncleanness stood much in the way of my service.

After the meeting,
I found there was a great jealousy in the minds of
Friends that something was wrong with the man,
but I was, till then, altogether a stranger to their thoughts,
and to the state of the man,
yet I advised Friends should have a watchful eye over him and his family,
for I told Friends my spirit was easy in what I delivered,
and I believed the evil would not be concealed.
On my return, I heard his wickedness had been made manifest, which he did not deny.

--

John Banks was a worthy minister of the Society of Friends,
which he joined in the year 1654.
His friends have left this testimony of him:
that "`He labored night and day for the gathering of people to
God,`" and that "`he was an incessant laborer in the Lord`'s work,
both in body and mind.`"
In a journal of his life, which he left behind him, is the following narrative:

[.embedded-content-document]
--

About this time +++[+++1676]
a pain struck into my shoulder, and gradually fell down into my arm and hand,
so that I was wholly deprived of the use of it; the pain increased both day and night.
For three months I could neither put my clothes on or off,
and my arm and hand began to wither, so that I applied to some physicians,
but could get no cure by any of them.
At last, as I was asleep upon my bed, in the night time,
I saw in a vision that I was with dear George Fox, and I thought I said to him, "`George,
my faith is such, that if you see your way to lay your hand upon my shoulder,
my arm and hand shall be whole throughout.`"
This remained with me two days and nights, that the thing was a true vision,
and that I must go to George Fox, until at last, through much exercise of mind,
as a great trial of my faith, I was made willing to go to him,
he being then at Swarthmore in Lancashire,
when there was a meeting of Friends on the First-day of the week.
Sometime after the meeting, I called him aside into the hall,
and gave him a relation of my dream, showing him my arm and hand; and in a little time,
we walking together silently, he turned about and looked upon me,
and lifting up his hand, laid it upon my shoulder, saying,
"`The Lord strengthen you both within and without.`"
I went to Thomas Lower`'s of Marsh Grange, that night: and when I was set down to supper,
immediately before I was aware, my hand was lifted up to do its office,
which it could not do for a long time before.
This struck me with great admiration,
and my heart was broken into tenderness before the Lord; and the next day I went home,
with my hand and arm restored to its former use and strength without any pain.
The next time that George Fox and I met, he said, "`John, you mended;`" I answered,
"`Yes, very well in a little time.`"

"`Well,`" said he,
"`give God the glory;`" to whom I was and still am bound in duty so to do,
for that and all other his mercies and favors.
He has all power in his own hand,
and can thereby bring to pass whatsoever seems good in his eyes; who, by the same,
prepares instruments and makes use of them as pleases Him,
who is alone worthy of all praise, honor and glory, both now and forevermore.

--

William Dewsbury was another of those remarkable men,
who in the seventeenth century were raised up in
England to proclaim the everlasting Gospel.
Bold and unflinching in his testimony,
he suffered patiently the persecutions which he encountered,
and spent many years in different imprisonments on a religious account.
During his last illness, about a week before his death,
a few friends being in his chamber, he thus addressed them:

[.embedded-content-document]
--

My God has put it into my heart to bear a testimony in his name and blessed Truth.
I can never forget the day of his great power and blessed appearance,
when He first sent me to preach his everlasting Gospel,
and to proclaim the day of the Lord to the people.
And he confirmed the same by signs and wonders;
and particularly by a lame woman who went on crutches, where I with my dear brethren,
George Fox and Richard Farnsworth, were cast;
and as I cried mightily unto the Lord in secret,
that He would eminently manifest himself at this time among us,
and give witness of his power and presence with us, Richard Farnsworth,
in the name of the Lord, took her by the hand, and George Fox after,
spoke to her in the power of God, and bid her stand up and she did,
and immediately walked straight, having no need of crutches any more.
Therefore, Friends, be faithful, and trust in the Lord your God; for this I can say,
I never since played the coward; but joyfully entered prisons as palaces,
telling my enemies to hold me there as long as they could.
And in the prison house I sang praises to my God,
and esteemed the bolts and locks put upon me as jewels;
and in the name of the eternal God I always got the victory.
For they could keep me no longer than the determined time of my God.

--

Many Christians of the present day suffer loss,
from lack of sufficient faith to enjoy some of the
privileges partaken of by the saints of old,
promised in the Holy Scriptures, and experienced in measure by some of modern times.
The sceptical atmosphere in which we live, with its blinding mists,
appears to affect them in degree, and prevent them from seeing with clearness,
and receiving some of the blessings which are bestowed
upon others who have more simple-minded faith.

The efficacy of prayer to procure both spiritual and temporal blessings,
the indwelling of the spirit of Christ, and its sensible operations on the heart,
the gift of prophecy and of healing the sick,
and the extension of Divine power in a manner out of the ordinary course of nature,
are all realities confirmed by the records of the past,
and which we have Scripture authority for expecting
to find in the experience of the present day.

Thomas Story was an intimate friend of William Penn,
and held several important offices under him.
He was a member of the council of state,
master of the rolls and commissioner of property for Pennsylvania.
He had received a classical education, and possessed an unusually clear and logical mind;
and having early in life yielded his heart to the operations of Divine grace,
he possessed both the intellectual and spiritual qualities
which give value to his testimony on religious matters.
He left behind an autobiography in which are recorded the following interesting circumstances.

In 1715, when paying a religious visit in Holland,
he met with a Mennonist named Talken Corsten, living at Mackow, in Friezland,
who gave him the following narrative:

[.embedded-content-document]
--

That some years ago, our friend, Sarah Collier, being in those parts,
desired a meeting with them +++[+++the Mennonists]
in their meetinghouse, which they refused her;
but he himself had a secret desire of a meeting, having never been at one,
and accordingly gave her the liberty of his house, where a meeting was held accordingly,
and many were there and well satisfied.
After the meeting, Sarah Collier, having a mind to see his wife,
who then lay ill of a disease which had been upon her for about twelve or thirteen years,
was conducted into the chamber where she lay;
and after some time Sarah was concerned to pray by his wife,
and for her help and deliverance from her malady and great exercise of it;
and to his great admiration,
and also his wife`'s and all who had opportunity to observe it,
his wife recovered presently upon it, and has been well ever since.

--

In 1717, when in the north of England, he was very unwell,
and suffered much pain at a meeting at Solport, on the twentieth of the Ninth Month.
After the meeting he went to the house of John Irwin, where, he says:

[.embedded-content-document]
--

I was ill most of that night,
but towards the morning the Lord encouraged me with a little help,
which proved very effectual.
It was by the operation of his power in my heart,
by which all the pains for that time were overcome and quieted,
and then I had ease and rest all that day.

--

About two months after that, he attended a meeting at Sunderland,
appointed for James Dickinson, a minister of the Gospel.
At this, he says:

[.embedded-content-document]
--

I was much renewed in my strength, both of body and mind;
for though I had been ill all night and had little rest, by reason of a great cough,
and pain in my stomach,
and so much indisposed in the morning after I arose that I could
not go to meeting till about half an hour after the time;
yet, within a few minutes after I was there,
I found my heart bound up and surrounded with the girdle of Truth,
so close and fast that the healing virtue thereof overpowered every other power in me,
both of body and mind, so that I had no present sense at all of any ailing.

--

In 1698, on a voyage from England to America,
the ship in which he sailed encountered a violent storm, so that,
as his narrative relates:

[.embedded-content-document]
--

All the yards were brought down on the gunnels, and the helm lashed and made fast,
and the ship let drive before the wind.
And we being met together in the great cabin and steerage to wait upon the Lord,
as at other times, He was pleased to appear in the needful time;
for the tempest increased, with thunder and lightning and rain, to that degree,
that few there, if any, had ever seen the like.

And in waiting upon the Lord, I became concerned in prayer;
and being in a mighty agony and wrestling in spirit with the Lord,
I received hope that we should not perish; and having concluded for that time,
and my concern returning, I prayed again; and then some stout hearts were broken:
and the Lord`'s power was glorified, and we greatly comforted.
For I prayed unto the Lord, who is God of the seas as well as of the earth,
and of the winds, the Creator of all things visible and invisible,
that He would be pleased to send forth his word, and command the winds as of old;
and that if there was any opposing spirit that stood in our way to hinder our progress,
the Lord would please to drive him away.
And then I was easy, having fully overcome;
and my companion and some others were also greatly tendered;
and as soon as I arose I took the Friends by the hands, and some others also,
and in full assurance, told them the worst was over for that time;
and the words were scarcely out of my mouth and I set down in the cabin,
till the storm abated and the weather became moderate for some time after,
and we had no more great storms after it to that degree.

--

In 1698, when in Ireland, at the castle of Shannigary,
which was on the estate of William Penn,
he met with "`a gentlewoman of good sense and character,`"
who gave him the following relation:

[.embedded-content-document]
--

That she, being in the City of Cork when it was invested by king William`'s army,
and having a little daughter of hers with her, they were sitting together on a squab;
and being much concerned in mind about the danger and circumstances they were under,
she was seized with a sudden fear and a strong impulse to arise from that seat,
which she did in a precipitant manner, and hasted to another part of the room,
and then was in the like concern for her child,
to whom she called with uncommon earnestness to come to her, which she did.
Immediately after which came a cannon-ball and struck the seat all in pieces,
and drove the parts of it about the room, without any hurt to either of them.

From this relation I took occasion to reason with her thus:
That Intelligence which gave her notice, by fear, of the danger they were in,
must be a spiritual being,
having access to her mind (which is likewise of a
spiritual nature) when in that state of humiliation,
under those circumstances; and must also be a good and beneficent Intelligence,
willing to preserve them;
and furnished also with knowledge and foresight more than human.
"`He must have known that such a piece would be fired
at that time and that the ball would hit that seat,
and infallibly destroy you both, if not prevented in due time by a suitable admonition,
which he suggested by the passion fear (the passions being useful
when duly subjected) and by that means saved your lives.
And seeing that the passions of the mind can be wrought upon for our good by an invisible,
beneficent Intelligence in the mind, in a state of humiliation and stillness,
without any exterior medium,
is it not reasonable to conclude that an evil intelligence may
have access likewise to the mind in a state of unwatchfulness,
when the passions are moving and the imagination
at liberty to form ideas destructive to the mind,
being thereby depraved and wounded?
And when so, is it not likewise reasonable to think that the Almighty himself,
who is the most pure, merciful and beneficent Spirit, knowing all events and things,
does sometimes, at his pleasure, visit the minds of mankind, through Christ,
as through or under a veil,
so as to communicate of his goodness and virtue to a humble and silent mind,
to heal and instruct him in things pleasing to himself and proper
for the conduct of man in his pilgrimage through this present world,
and lead him to the next in safety?`"

--

[.offset]
Oliver Sansom, a Friend, of England, says in his memoir:

[.embedded-content-document]
--

"`On the twenty-fifth of this Tenth Month, 1665, as I lay in bed in the morning early,
I heard, as it were, an audible voice, which said unto me:
'`Take no care for your business,
for you must go to prison for three months.`' Thereupon I presently arose,
and related to my family what I had so plainly heard;
and we all thought that if I went to prison it would be for not paying the priest,
he having so often threatened me.
So I let it pass for the present, being given up in my mind to suffer,
if the will of the Lord were so.

"`Three days after, a ministering Friend came to my house to visit me, and I desired him,
if it stood with his freedom, to have a meeting there that evening,
because several of my neighbors had told me that
if ever there should be a meeting at my house,
and they had notice of it, they would come to it.
The Friend consenting, I sent my servants, both man and maid,
to acquaint all my neighbors therewith,
both in that town and also in a village which was near,
and I bid them deliver their message thus,
that if they had any desire to hear the Truth declared,
they might come to my house at such an hour that evening.
There was not one family, besides the priest`'s, but was invited.
For I thought the priest would prove a troublesome guest;
and therefore neither he nor any of his family were invited.
But most of my neighbors came, especially the men, and the room was full,
and the Friend declared the Truth for near the space
of an hour to the great satisfaction of the people.`"

The priest during this time was at his home, with his family and some others,
amusing himself with playing cards, but hearing of the meeting,
he came with his company to break it up,
and the next morning made complaint of the meeting having been held to William James,
a justice of the peace.
Fines of twelve pence each were imposed on those who were proved to have been present.
When they came to Oliver, he says: "`Because I could not promise, as the others did,
that I would go no more to meetings,
and to confess myself guilty as an offender in that which,
in the sight of God and all just men, was no offence, they fined me five pounds,
or to endure three months`' imprisonment,
as for the first offence (as they called it) upon the act for banishment.
And I, not consenting to pay the fine,
was committed prisoner to the county jail at Reading for three months.

"`Now did I call to mind and thankfully acknowledge the goodness of the Lord unto me,
in fore-showing me of this three months`' imprisonment by that
voice which I had heard as I lay in bed three days before.`"

--
