== Chapter X. Doctrinal

William Penn says of the ministry of Friends in the beginning:
"`The bent and stress of their ministry was conversion to God, regeneration,
and holiness; not schemes of doctrine and verbal creeds, or mere forms of worship.`"
But although their ministry was eminently practical in its character,
yet it rested on a substratum of doctrine to which they firmly held,
as many of their early records clearly show.

John Burnyeat, of Cumberland, England,
was convinced of the Gospel truths which George Fox preached in 1653.
His travels in the ministry were extensive, embracing a service of many years.
He endured much hardship, suffering, and imprisonment, in England and in Ireland.
He also went over much of the settled districts of the United States,
and had meetings with the Indians and in Barbados.
In his autobiography he informs us, he--

Had made a high profession of imputative righteousness;
that though I lived in the act of sin, the guilt of it should not be charged upon me,
but imputed to Christ, and his righteousness imputed to me.
I found it otherwise when I was turned unto the Light,
which did manifest all reproved things.
Then I came to see that the guilt remained while the body of death remained,
and through its power was led into the act of sin.
Then I saw there was a need of a Saviour to save from sin,
as well as the blood of a sacrificed Christ to blot out sin,
and of faith in his name for the remission of sins past.
Then began the warfare of true striving to enter the kingdom.
Paul`'s state was seen; the will was present, but power was lacking many times to do.
Then was the cry: "`O,
wretched man that I am!--who shall deliver me from the body of this death,`"
and free me from the prevailing power of the law which remained in my members,
warring against the law of my mind, which brought me into captivity to the law of sin?
All my conceit in my notional faith, and my pretence and hopes of justification thereby,
were overthrown.
All that I had built for several years, after acquaintance with the Lord,
and the knowledge of Him, and peace with Him, was seen to be but a Babel tower,
which God brought confusion upon,
and that which never could be perfected to reach to heaven,
being out of the faith of his covenant.
All my works were confounded by the visitations of God, in his love,
and by the springing of the day from on high which discovered things as they were.
The Lord brought confusion upon them.

I was amazed, and fear beset me on every side,
and I began sometimes to fear I was undone forever,
for something had entered into my heart that had turned the fruitful field into a wilderness.
The day of God discovered all to be desolation and dryness.
My soul was brought into deep lamentation--sorrow such as had never before been my experience.
My notion and talk of my imputation of the righteousness of Christ being but my own,
which by his spirit I had no seal for, I saw clearly was but like Adam`'s fig-leaf apron,
in which he could not abide the coming of his God.
O, the horror that overtook me!
O, the poverty and need that my soul saw itself in by Divine light,
to which my eye was now turned!
The spring of this light manifested all things.
The load and burden of many, with myself, became grievous in that day.
We began to mourn after a Saviour.
We looked for a deliverer.
We cried for a helper and a healer.
The day of the Lord had overtaken us.
The fire and sword which Christ brings upon the earth, through burning and judgment,
was begun, by which the filth of our defilement was to be taken away.

=== A Sermon Preached by Francis Camfield, at Grace-Church-Street, Fifth Month 14th, 1693

My Friends:

You have often heard by the servants of the Lord, that have given testimony to Jesus,
the only and alone Saviour, you have often heard the report, and the report is true,
that there is no name under heaven by which any man can be saved, but the name of Jesus;
and you have oftentimes read also in the Holy Scripture,
of this Jesus the only and alone Saviour.
All the holy prophets gave testimony that He should come; and when He was come,
all the holy apostles and ministers of our Lord and Saviour Jesus Christ,
gave testimony that He was come, and they were made able ministers of the New Testament,
and their great business was (as instruments in the hand
of the great God) to turn men from darkness to light,
and from the power of Satan to the power of God,
that they might receive forgiveness of sins,
and an inheritance among them that are sanctified;
you know the Scripture speaks plentifully after this manner.
I hope there are none here, but have believed the testimonies that have been given,
but the great thing is, for everyone to come to a consideration of this;
since you have believed the report, everyone`'s concern now, is to examine themselves,
whether or no, they are really turned from darkness to the heavenly light.
None come to be turned from darkness to light,
but as they come to know repentance from dead works,
and faith towards our Lord Jesus Christ.
And as everyone comes to know this, they come to know what it is to lay a good foundation.
This was the foundation the primitive Christians laid,
as you may remember the exhortation of the Apostle in the Epistle to the Hebrews,
"`Therefore leaving the principles of the doctrine of Christ,
let us go on unto perfection,
not laying again the foundation of repentance from dead works,
and of faith towards God.`"

Thus you see he presses them to go on to perfection,
that is the business of every one of you that believe in the name of Jesus,
that you keep walking on in the holy way.
We that are come to know this holy way,
through the riches of the love and grace of the great God to us,
it is our main business to walk in this holy way;
they that know anything of true Christianity, know this to be their great concern,
to walk in this holy way that leads to everlasting life.
Christ is the way, the truth, and the life; and everyone that comes into this way,
and walks in it, they are going on towards perfection.
And they are putting off the old man; they feel in themselves a power at work,
that crucifies the old man with his deeds, then they go on in the name of the Lord.
This power does work,
till everyone in their own particular comes to be crucified with Christ.
It was the primitive Christian`'s experience, what the apostle says of himself:
"`I am crucified with Christ, nevertheless I live, yet not I, but Christ lives in me,
and the life which I now live in the flesh, I live by the faith of the Son of God,
who loved me and gave himself for me.`"

Great is the mystery of godliness; you that are engaged in the Christian warfare,
and that live the Christian life,
and are making war in righteousness against the devil the enemy of your souls,
you know that great is this mystery of godliness.
This mystery is opened among the disciples of Jesus, among the holy offspring of God,
who are begotten again through the Word of eternal life; who, as the holy apostle says,
are begotten of his own will through the word of Truth,
that they should be a kind of first fruits of his creatures.
We to whom God has graciously manifested himself, in the blessed Son of his love,
our Lord and Saviour Christ Jesus, how ought we to walk as becomes the Gospel?
O that the serious and weighty consideration of this, might rest upon every one of us;
that we ought to have our conduct as becomes the Gospel of Christ,
and be going on to perfection.
You know what the apostle speaks: "`Not as though I had already attained,
either were already perfect, but I follow after,
if that I may apprehend that for which also I am apprehended of Jesus Christ.`"
This I am sure every true Christian man and woman will do, as the same apostle did,
who says:
"`I press towards the mark of the prize of the high calling of God in Christ Jesus.`"
And as everyone comes to grow up in the life of righteousness,
they will come to know an increase of faith, they will grow up in faith,
and in that hope which has been as an anchor to their souls,
in the day of their deep exercise, and they will remain steadfast and unmovable,
as they walk in the holy way.
And so everyone as they keep humble and bowed before the God of heaven,
will know his teachings more and more, and have a sensible feeling of it in themselves,
every one in their own particular.

And certainly,
it is all our business to be waiting for the fulfilling
of those many great and precious promises,
which are recorded in the Holy Scripture, which were enjoyed by the primitive Christians,
in the ages that are past and gone;
and in succeeding times shall be likewise enjoyed by all true Christian people,
as they come to be followers of Jesus.
As we have begun well, let us go on towards perfection,
not laying again (as I said before) the foundation of repentance from dead works,
and faith towards God and the Lord Jesus Christ;
for whoever expects salvation by Christ the only Saviour, must be going on to perfection,
they must begin at the work of regeneration, and experience in themselves a new birth,
for if we be not born again, we shall die in our sins;
you know that our Saviour has left this upon record,
and it remains the same truth to this day.

And therefore, how ought everyone that makes mention of the name of the great God,
and of our Lord and Saviour Jesus Christ;
how ought every such a one to be weighty and considerate, and examine themselves,
whether they are come to know repentance from dead works,
whether they have turned from the evil of their doings.
Some are ready to say, I would gladly turn from the evil of my doings,
but I find I am beset with the devil, the enemy of my soul.
Well, if you believe in the light, wherewith Christ Jesus has enlightened you,
then cry to Him, and He will give you power to withstand the enemy of your soul.

[.asterism]
'''

Robert Barclay says: "`Seeing no man knows the Father but the Son,
and he to whom the Son reveals Him,
and seeing the revelation of the Son is in and by the Spirit,
therefore the testimony of the Spirit is that alone
by which the true knowledge of God has been,
is, and can be only revealed.`"
"`From these revelations of the spirit of God have
proceeded the Scriptures of Truth;`" "`nevertheless,
because they are only a declaration of the Fountain, and not the Fountain itself,
therefore they are not to be esteemed the principal ground of all truth and knowledge,
nor yet the adequate primary rule of faith and manners.`"
"`If by the Spirit only we can come to the true knowledge of God,
if by the Spirit we are led into all truth, and so be taught of all things;
then the Spirit and not the Scriptures,
is the foundation and ground of all truth and knowledge,
and the primary rule of faith and manners.`"
"`As, then,
teachers are not to go before the teaching of God himself under the new covenant,
but to follow after it,
neither are they to rob us of that great privilege
which Christ has purchased unto us by his blood;
so neither is the Scripture to go before the teaching of the Spirit,
or to rob us of it.`"

William Penn, speaking of "`the word of light and life`" preached by George Fox, says:

For as it reached the conscience and broke the heart,
and brought many to a sense and search, so what people had been vainly seeking without,
with much pains and cost, they by this ministry found within;
where it was they truly needed what they sought for, namely:
The right way to peace with God.
For they were directed to the light of Jesus Christ within them,
as the seed and leaven of the kingdom of God; near all, because in all,
and God`'s talent to all.
A faithful and true witness and just monitor in every bosom.
The gift and grace of God to life and salvation that appears to all, though few regard it.

Then in regard to the ministry of the early Friends generally:

And as their testimony was to the principle of God in man,
the precious pearl and leaven of the kingdom,
as the only blessed means appointed of God to quicken, convince and sanctify man;
so they opened to them what it was in itself, and what it was given to them for;
how they might know it from their own spirit,
and that of the subtle appearance of the evil one,
and what it would do for all those whose minds are turned off from
the vanity of the world and its lifeless ways and teachers,
and adhere to this blessed light in themselves;
which discovers and condemns sin in all its appearances,
and shows how to overcome it if minded and obeyed in its holy manifestations and convictions;
giving power to such to avoid and resist those things that do not please God,
and to grow strong in love, faith and good works; that so man,
whom sin has made as a wilderness overrun with briars and thorns,
might become as the garden of God, cultivated by his Divine power,
and replenished with the most virtuous and beautiful
plants of God`'s own right-hand planting,
to his eternal praise.

William Penn, alluding to their ministers, declares:

They were changed men themselves before they went about to change others.
Their hearts were rent, as well as their garments changed,
and they knew the power and the work of God upon them.
This was seen by the great alteration it made,
and their stricter course of life and more godly
conduct that immediately followed upon it.
They went not forth nor preached in their own time and will, but in the will of God,
and spoke not their own studied matter, but as they were opened and moved of his Spirit,
with which they were well acquainted in their own conversion.

The fruits of the ministry of such gifted men and women were soon apparent.
Springing from a Divine source,
the word preached appealed directly to the light of Christ--the
witness for God--in the hearts of the hearers,
which begat faith there in the truth of the doctrine preached,
and thousands "`were turned from their lifeless professions and
the evil of their ways to a knowledge of God and a holy life.`"

Recognizing the exclusive headship of Christ in the church and sovereign authority,
as Lord and Master of all his disciples, Friends were careful,
when gathered into a society, to acknowledge their own brotherhood;
and to admit of no privileged order among them, like clergy and laity.
Believing that Christ alone can dispense the gifts
to be used for the edification of the body,
accompany them with the power necessary for their right occupation,
and the knowledge when and where they shall be employed in his service,
they discarded all training for the ministry,
all studied preparation for preaching or prayer,
and admitted that the gift therefor was freely bestowed upon both men and women,
prepared by the Head of the Church himself for the service.
They also believed that this Divine qualification and appointment were required,
not only for the work of the ministry,
but likewise for the right exercise of the gift and duties of elders and overseers,
and indeed, that every vessel used in the Church should be "`sanctified,
and fit for the Master`'s use,
and prepared unto every good work;`" and that these good works could be engaged in aright,
only as the spirit of Christ in the heart of such instruments prompted and guided therein.

Holding these views, in accordance with their testimony "`to the principle +++[+++or spirit]
of God in man, the precious pearl and leaven of the kingdom,
as the only blessed means appointed of God, to quicken,
convince and sanctify man,`" they were convinced
that when assembled for the purpose of Divine worship,
as Robert Barclay declares:

The great work of one and all ought to be to wait upon God,
and returning out of their own thoughts and imaginations,
to feel the Lord`'s presence and know a gathering into his Name indeed,
where He is in the midst, according to his promise.
And as everyone is thus gathered and so met together inwardly in their spirits,
as well as outwardly in their persons,
there the secret power and virtue of life is known to refresh the soul,
and the pure motions and breathings of God`'s spirit are felt to arise; from which,
as words of declaration, prayers or praises arise,
the acceptable worship is known which edifies the church and is well-pleasing to God.
And no man here limits the spirit of God,
nor brings forth his own conned and gathered stuff,
but everyone puts that forth which the Lord puts into their hearts, and it is uttered,
not in man`'s will and wisdom,
but in the evidence and demonstration of the Spirit and power.
All other worship than this worship,
which man sets about in his own will and at his own appointment,
which he can both begin and end at his pleasure, do or leave undone as himself sees fit,
whether they be a prescribed form, as a liturgy, etc.,
or prayers conceived extempore by the natural strength and faculty of the mind,
are but superstition, will-worship and abominable idolatry in the sight of God.

But while they felt themselves in duty bound to hold up this pure and
spiritual worship as being that which is "`answerable to the testimony
of Christ and his apostles,`" yet they were not so devoid of charity as
to deny that the prayers and praises of sincere and upright-hearted worshippers,
who had not seen the deadness of the forms and ceremonies with which they were connected,
were acceptable to Him who looks at the heart and its intent;
nevertheless "`They could not approve of their way in general,
nor not go on to uphold that spiritual worship which the Lord is calling all to,
and so to testify against whatsoever stands in the way of it.`"

Those who depend on the labors of learned men for their knowledge of the Truth,
will find their faith a very variable one.
We know that some who have not understood the ground
on which Robert Barclay and our early Friends stood,
have not scrupled to declare,
that if they could have read the labors of commentators for the last two centuries,
they would have changed their opinions.
Such an assertion only goes to show that he who makes it,
has not come to such a settlement in the Truth as to have the witness in himself.
When Augustine was made really acquainted with the work of regeneration, he could say:
"`I sought you my God!--in the heavens,--in the earth--and
in the creatures--but there I found you not.
But I no sooner sought you in my own heart than I found you.`"
Such is the testimony of the spiritual in all ages.
The Lord Jesus Christ, who once took upon him the form of a man,
and died on Mount Calvary,
offering up himself a propitiatory sacrifice for the sins of the
whole world--has at all times been with his church and his people,
as a light, as a teacher, as a purifier from evil, manifested within them.
With Him for our sufficiency--with Him for our defence--with Him for our guide and instructor,
though thankful for all the outward aid He may furnish us in the heavenly journey,
we shall not trust or depend upon man.
Our sufficiency is in the Lord alone.
The Catholics may depend upon the absolution of men, and the merits of the saints,
for pardon.
According to the poetical fancies so prevalent in their religion,
they imagine the ransomed ones, as cognizant of all events taking place on the earth,
and as watching over and occupying themselves with our mistakes
and repentings and ready to hear and to plead for pardon to the
throne of grace for all who call upon them in their extremities.
With such a belief, praying to the saints is the natural consequence,
especially when in addition to this they also believe,
that those who by a remarkably circumspect life have got to heaven,
have a store of superabundant merit above that which
was necessary to procure their own salvation,
which they can spare to help make up the deficiencies of their worshippers.
Protestants may depend upon their clergy and upon outward form and outward profession.
It is enough for us to know that we have an ever-present
Redeemer who hears the cry of those who truly seek Him,
and will help their infirmities.
His holy eye ever sees us, and oh,
far greater should be our fear of doing wrong in his presence,
who is our immaculate Judge, than if our actions were open to the sight of all men,
with all the ransomed host who dwell in light.

If we humbly wait on Him,
He will instruct us in the way in which we should go--He will wash us in the
laver of regeneration--He will perfect his own work in us to his own glory,
and our everlasting peace.
We shall learn, that though we were perfect in obedience,
we can claim no merit--we are only doing our duty,--and
whether travelling on earth in faithful dedication of heart,
or rejoicing in heaven in the fulness of blessedness,
we shall have no storehouse of our own good works to point to.
"`Not by works of righteousness which we have done but by his mercy He saves us,
by the washing of regeneration and the renewing of the Holy Spirit.`"

=== Passages From the Writings of Thomas Story, Who Died 1742

As the nature and virtue of the Divine essential Truth increased in my mind,
it wrought in me daily a great conformity to itself, by its own power;
reducing my mind to a solid quietude and silence,
as a state most fit for attending to the speech of the Divine word.

The washing of the feet signifies the cleansing of the ways;
and those who are washed in the laver of regeneration will walk in clean
paths and bring forth fruit according to the nature of the tree of life;
such will walk in faith, love, obedience, peace, holiness, mercy and truth.
Will you wash my feet, O Lord!--with the washing of regeneration;
that I may tread the paths of life before your face.

// lint-disable modernize-words 'Come you ...'
Come you ragged ones, come sit down before the King; for He is meek and lowly,
and loves the humble.
Though you be naked, He will clothe you with righteousness; though you be hungry,
He will feed you with the bread of eternal life.
Fear not, you of low degree, for with our God there is no respect of persons.
Fear not, O you little ones; for He showed you his lovingkindness of old;
and with Him there is no shadow of turning.
I was silent before the Lord as a child not yet weaned.
He put words in my mouth, and I sang forth his praise with an audible voice.
I called unto my God out of the great deep; He put on tender mercies,
and had compassion on me, because his love was infinite, and his power without measure.
He called for my life, and I offered it at his footstool; but He gave it me as a prey,
with unspeakable addition.
He called for my will, and I resigned it at his call;
but He returned me his own in token of love.
He called for the world, and I laid it at his feet, with the crowns thereof;
I withheld them not at the beckoning of his hand.
But mark the benefit of exchange!
For he gave me instead of earth, a kingdom of eternal peace;
and in lieu of the crowns of vanity, a crown of glory.
I said: "`What am I, that I should receive such honor?`"
But He removed the mountains out of my way, and by his secret workings pressed me forward.

I followed the voice of the Shepherd, who gave me food according to my strength,
and found all things even as He had said of old, and a name by which I shall be saved.

I will call for perseverance in the ways of life; for the hidden manna,
day by day received.

My Comforter also taught me to pray in knowledge as in faith; I begged him,
and He gave me all.
He gave me power to do wonders also; to keep his commandments, through his Holy Spirit;
and to walk in the paths of righteousness with joyful songs.
I will call upon Him in the days of temptation; and when I am in the shadow of death,
the Lord shall be my strength.

Watch,
O you disciples of the Lamb of God!--lest you be found sleeping when your Lord comes,
and be thereby unfitted to enter into his rest and glory.
Watch and pray lest you enter into the temptation of self-confidence.

[.asterism]
'''

Samuel Scott, who died in 1789, wrote:

Grievous visions have been before me,
of a final separation from the beatific vision of the Lamb,
who dwells in the midst of the throne;
but let the Judge of all the earth deal with me as He may see fit;
I have only to lay my hand upon my mouth, for He is righteous altogether.
In respect to my fellow-men, unrighteousness has not been in my heart,
nor iniquity in my hands: I have sought no increase of the unrighteous mammon,
but have been rather desirous that many might be partakers of the benefit:
bulky and ostentatious donations have been declined,
rather from the persuasion of humility than avarice; verily,
these righteousnesses have their reward;
but in respect to a final acceptation with the Supreme Being,
they ought only to be esteemed as filthy rags;
our dependence ought only to be on "`the blood of the everlasting covenant`"
and interior operations of the Spirit that works in us,
both to will and to do, according to his own good pleasure.

As I was walking in the evening,
agreeably with what was expressed in the conference of yesterday,
in a degree of the immediate feeling, the language of our worthy friend Isaac Penington,
was inwardly uttered: "`None but Christ,`" none but Christ, can my soul say,
from a sense of my continual need of Him.
Not only as He was a propitiation without me, but as a light within me:
"`for in Him was life, and the life is the light of men.`"
And not only by the report of what He has done for them, without them,
but by his direct presence and saving help,
are the souls of the desolate and distressed led, at seasons, to trust in Him,
who for their sanctification, "`suffered outside the gate.`"

=== Thomas Ellwood`'s Account of that Eminent and Honorable Servant of the Lord,George Fox

This holy man was raised up by God, in an extraordinary manner,
for an extraordinary work, even to awaken the sleeping world,
by proclaiming the mighty day of the Lord to the nations and publishing
again the everlasting Gospel to the inhabitants of the earth,
after the long and dismal night of apostasy and darkness.
For this work the Lord began to prepare him,
by many and various trials and exercises from his very childhood;
and having fitted and furnished him for it, He called him into it very young;
and made him instrumental by the effectual working of the Holy Spirit,
through his ministry to call many others into the same work,
and to turn many thousands from darkness to the light of Christ,
and from the power of Satan unto God.

I knew him not until the year 1660; from that time to the time of his death (1690),
I knew him well, communed with him often, observed him much, loved him dearly,
and honored him truly; and upon good experience can say,
he was indeed a heavenly-minded man, zealous for the name of the Lord,
and preferred the honor of God before all things.

He was valiant for the Truth, bold in asserting it, patient in suffering for it,
unwearied in laboring in it, steady in his testimony to it, immovable as a rock.
He was deep in Divine knowledge, clear in opening heavenly mysteries,
plain and powerful in preaching, fervent in prayer.
He was richly endued with heavenly wisdom, quick in discerning, sound in judgment,
able and ready in giving, discreet in keeping counsel; a lover of righteousness,
an encourager of virtue, justice, temperance, meekness, purity, modesty, humility,
charity and self-denial in all, both by word and example.
He was graceful in countenance, manly in person, grave in gesture, courteous in conduct,
weighty in communication, instructive in discourse,
free from affectation in speech or carriage.
A severe reprover of hard and obstinate sinners,
a mild and gentle admonisher of such as were tender, and sensible of their failings.
Not apt to resent personal wrongs; easy to forgive injuries;
but zealously earnest where the honor of God, the prosperity,
truth and peace of the church were concerned.
He was very tender,
compassionate and merciful to all that were under any sort of affliction;
full of brotherly love, full of fatherly care;
for indeed the care of the churches of Christ was daily upon him,
the prosperity and peace whereof he studiously sought.

Beloved he was of God; beloved of God`'s people,
and which was not the least part of his honor, the common butt of all apostates`' envy;
whose good, notwithstanding, he earnestly sought.

Mod: Beloved he was of God; beloved of God`'s people,
and what was not the least part of his honor,
he was the common recipient of all apostates`' envy;
whose good he notwithstanding earnestly sought.

He lived to see the desire of his soul,
the spreading of that blessed principle of Divine light,
through many of the European nations,
and not a few of the American islands and provinces,
and the gathering of many thousands into an establishment therein;
of which the Lord vouchsafed him the honor to be the first effectual publisher,
in this latter age of the world.
And having fought a good fight, finished his course, and kept the faith,
his righteous soul,
freed from the earthly tabernacle in which he had led an exemplary life of holiness,
was translated into those heavenly mansions where Christ our Lord,
went to prepare a place for his own.

=== Extract from the Life of Daniel Wheeler

In looking back at the marvellous manner in which I was sustained through all this conflict,
and again restored as one brought back from the dead,
I cannot avoid adverting to that period of my illness,
when my mind felt so reconciled to the prospect of death, as before mentioned;
and I now fully believe from what I have since been mercifully favored to experience,
that so far from being in any degree prepared for such an awful event,
a deceptive feeling must have been superinduced by the state
of torpor and insensibility in which I then was,
and which totally benumbed any better feeling and desires as to the future.
To this may be added a predominating fear of having to endure
more of those sufferings of which I had had no small share;
which, the probability of being again restored to health,
seemed to banish every hope of escaping.

Truly awful is the thought which this view of my then lost condition occasions,
when I contemplate the woe and misery which must have been my eternal portion,
if unutterable mercy and long-suffering had been withdrawn,
and if the soul had been required of one who had witnessed
no repentance towards God the Judge of all,
except what, at times, the fear of punishment had extorted;
and who was a stranger to that saving faith in the Lord Jesus Christ,
as the "`Lamb of God that takes away the sin of the world;`" without which,
his precious blood would have been shed in vain for me.
I should thus have died in my sins, which, unrepented of,
would have followed after to judgment in terrible array against my guilty soul;
and yet when my end was apparently so near and inevitable,
if such questions as are frequently proposed on the like occasions, had been put to me,
I have little doubt but satisfactory answers would have been returned,
as to my belief and hope in the essential truths of the Gospel.
But alas!--this would have been from hearsay and traditional report,
and not from any heartfelt saving knowledge of my own;
for it is now plain to my understanding,
that no man can have saving faith in Jesus Christ, who is unacquainted with,
and does not walk in the light of that Divine Spirit,
which is so justly styled the spirit of faith.

It is through this alone that the death and sufferings of Christ,
and his whole sacrifice for sin, are availing, and truly applied to all those who,
through faith, lay hold of him,
the true Light and Saviour of them that believe in his inward and spiritual appearance.
These can say to others from sensible and blessed experience:
"`Behold the Lamb of God that takes away the sins of the
world;`" they have received the atonement by Him,
and they reap the glorious fruit and benefit of his death and suffering for sin,
by the sacrifice of himself, and of his resurrection and ascension;
in that He ever lives to make intercession for those
who are thus willing to come unto God by him.
A man may yield an assent to all the great and solemn truths of christianity;
the miraculous birth, holy life, cruel sufferings, ignominious death,
and glorious resurrection and ascension of our blessed Redeemer;
he may believe in the abstract,
in his inward and spiritual appearance in the hearts of mankind by his Holy Spirit;
and yet he may fall short of the prize immortal,
unless he comes to witness the saving operation of the Holy Spirit in his own heart,
and to know thereby, through faith in it,
a purifying preparation for the kingdom of righteousness, peace and joy,
in the Holy Spirit.
How can I sufficiently appreciate or declare the extent of the endless
mercy which allowed me not to perish in the midst of my sins,
when so many were swept away by the same pestilential disorder.

+++[+++The above alludes to when he was in the British army,
when the average number of deaths was twenty-seven a day and night.]

After having mentioned the facts connected with my sickness and recovery,
it seems only due, however feeble on my part the effort,
to endeavor to commemorate such gracious dealings with humble gratitude and reverence;
earnestly desiring that no motive whatever will be
allowed to prevail with me for making the attempt,
but that of promoting the glory and honor of the great name;
that others may know and fear,
and believe in the all-sufficiency of that Power which has "`showed me the path
of life,`" and which alone can bless for their instruction what has been written,
to press the necessity of contending for that saving faith,
"`once delivered to the saints.`"
Without it all religious profession is a dream, a shadow, and a doubt;
but with it a glorious reality; yes, "`The substance of things hoped for,
the evidence of things not seen,`" even the salvation of the soul,
through Christ Jesus our Lord.
Amen!

[.asterism]
'''

William Savery says:

Now I struggled to break myself of my fondness for company,
seeing the snare there was in it;
being apt to relate adventures and tales to provoke mirth,
and often for their embellishment to strain beyond the truth.
I was much concerned to watch over myself in this particular,
which is both dishonorable and sinful,
yet a vice that I have observed to be very prevalent among the youth of both sexes.
Even in companies that are termed polite, or well bred,
the discourse is often so strained, that few sentences or narratives if examined,
would be found to be strictly true.
Some fondly imagine that there is but little harm in telling untruths,
unless they be seriously told; not considering our holy profession,
and who it was that said: "`Let your yes be yes, and your no, no,
for whatsoever is more than this, comes of evil.`"
Oh the folly of this way of spending our precious time!
How watchful, how careful ought we to be of our words and actions,
always remembering that the holy eye of an all-seeing God
pervades the most secret chambers we can retire to,
and his ear is ever open to hear both the evil and the good.
Insomuch that one formerly said,
there is not a thought in the heart nor a word on the tongue but He knows it altogether.
Yes, and many of the present day have known when the terrors
of the Lord have overtaken them for sin,
and they have had to taste of the spirit of judgment and
burning--that every secret thing has been brought to light,
and the hidden works of darkness have been made manifest;
and that even for idle words they have had to render an account.

Stephen Crisp remarks:

It is no man`'s riches nor greatness in this world;
it is no man`'s eloquence and natural wisdom that
makes him fit for government in the Church of Christ;
unless he, with all his endowments, be seasoned with the heavenly salt,
and his spirit subjected, and his gifts pass through the fire of God`'s altar,
a sacrifice to his praise and honor; that so self be crucified and baptized into death,
and the gifts made use of in the power of the resurrection of the life of Jesus in him.
And when this great work is wrought in a man,
then all his gifts and qualifications are sanctified,
and they are made use of for the good of the body, which is the church,
and are as ornaments and jewels,
which serve for the joy and comfort of all who are partakers of
the same Divine fellowship of life in Christ Jesus our Lord.

Did the apostle John, that gave testimony of Christ as the light of the world,
oppose his appearance in that body that was prepared for Him of the Father,
to do his will in?
No, no more than the apostle Paul,
who preached his spiritual appearance and manifestation, opposed his bodily appearance,
and being manifest in the flesh, when he says,
the grace of God which brings salvation has appeared to all men, teaching us,
that denying ungodliness and worldly lusts, we should live soberly,
righteously and godly in this present world.
No more do we deny or oppose Christ`'s bodily appearance,
who died outside the gates of Jerusalem;
though we are misunderstood and misrepresented by many in this generation.
The Lord in mercy by his heavenly power remove this misunderstanding,
and take away this veil from the hearts of the children of men,
and so bring them to a sense and knowledge of the spiritual appearance of Christ Jesus,
and the blessed end of his coming in that blessed body wherein He suffered,
and tasted death for every man;
not that any man might live in sin because He died a sacrifice for sin.
He did not die for sin that men should live in sin, but that they might die to sin,
and live to God;
so likewise we do not preach anything opposite to
Christ`'s appearance in that blessed body,
who was God manifest in the flesh, for therein He wrought salvation for us;
He is the captain of our salvation, and was made perfect through sufferings;
He is the first begotten of the dead, the prince of the kings of the earth,
that has loved us, and cleanses us from our sins in his own blood.

These views of the spiritual nature of all acceptable worship were by no means supposed
to release any from the obligation to assemble themselves together for its performance;
which Friends practised diligently and faithfully.
Nor did they imagine that mere silence, any more than words only, was worship.
They knew and inculcated that, when assembled with one accord in one place,
it was the duty and privilege of each to retire to the Divine gift,
and feel it to qualify to offer unto the Lord whatever He prepared and called for.
Being thus gathered in the name of Christ, He was in their midst;
and the only preaching that could convict, convert, comfort, confirm or edify,
was called for by Him at the time,
and delivered in the demonstration of his Spirit and power;
and under the same heavenly call and influence,
acceptable outward or vocal prayer or praise was engaged in.
This worship of God was considered by many of the high professors in that day,
too simple and contemptible, because, as Robert Barclay says,
man "`finds no room there for his inventions and imaginations,
and has not the opportunity to gratify his outward and carnal senses;
so that this form being observed, is not likely to be long kept pure without the power,
for it is of itself so naked without it,
that it has nothing in it to invite and tempt men to dote upon it,
further than it is accompanied with the power.`"

In each succeeding generation since the days of Fox, Penn and Barclay,
the Lord has raised up sons and daughters, who,
submitting to the government of his Holy Spirit in the secret of their souls,
have been taught by Him,
and led by Him to embrace the faith of their forefathers in religious profession,
and who,
feeling the doctrines and testimonies which the Society had heretofore inculcated,
to be precious, have maintained them themselves,
and encouraged their fellow-members in the support of them;
while with holy zeal they guarded and warned the flock against
the delusions of false teachers and the inroads of error.
And throughout the two hundred years of the Society`'s existence,
we believe it has been abundantly demonstrated,
that its most availing care for the preservation and religious growth of its own members,
and the most effectual impression for good made by it upon other religious denominations,
have been consequences of the unflinching support and practical
illustration given by its consistent and devoted members,
under the Divine guidance and blessing,
to the doctrines and testimonies it promulgated at the beginning.
Herein, as a church, and as a human agency, has been its safety and its strength,
and that strength has waned,
and the influence of the Society for good to itself and to others diminished,
just in proportion as its first principles were disregarded,
and the rigidity of its self-denying faith compromised.

While George Fox was detained at Worcester,
waiting for his trial at the approaching court session,
he was visited by various persons at the Friend`'s house
where the judges had given him permission to stay,
some of whom endeavored to draw him into argument on points of doctrine.
At one time a common-prayer priest came with others, and asked him,
"`If he was grown up to perfection.`"

I told him, says George, that "`what I was, I was by the grace of God.`"
He replied: "`It was a modest and civil answer.`"
Then he urged the words of John: "`If we say we have no sin, we deceive ourselves,
and the truth is not in us,`" and asked: "`What did I say to that?`"
I said, with the same apostle: "`If we say that we have not sinned, we make Him a liar,
and his word is not in us`"--who came to destroy and to take away sin.
So there is a time for people to see that they have sinned;
and there is a time for them to confess their sin, and to forsake it,
and to know the blood of Christ to cleanse from all sin.
Then the priest was asked: "`Whether Adam was not perfect before he fell,
and whether all God`'s works were not perfect.`"
The priest said: "`There might be a perfection as Adam had, and a falling from it.`"
But I told him: "`There is a perfection in Christ above Adam, and beyond falling;
and that it was the work of the ministers of Christ
to present every man perfect in Christ;
therefore they that denied perfection,
denied the work of the ministry and the gifts which
Christ gave for the perfecting of the saints.`"
The priest said: "`We must always be striving.`"
I answered: "`It was a sad and comfortless sort of striving,
to strive with a belief that we should never overcome.`"
I told him also, that "`Paul, who cried out of the body of death, did also thank God,
who gave him the victory through our Lord Jesus Christ.`"
So there was a time of crying out for need of victory,
and a time of praising God for the victory.
And Paul said: "`There is now no condemnation to them that are in Christ Jesus.`"
The priest said: "`Job was not perfect.`"
I told him: "`God said Job was a perfect man, and that he did shun evil;
and the devil was forced to confess that '`God has set a
hedge about him;`' which was not an outward hedge,
but the invisible heavenly power.`"
The priest said: "`Job said He charges his angels with folly,
and the heavens are not clean in his sight.`"
I told him, "`That was his mistake; it was not Job who said so, but Eliphaz,
who contended against Job.`"
"`Well, but,`" said the priest, "`what say you to that scripture,
The justest man that is, sins seven times a day?`"
"`Why, truly,`" said I,
"`I say there is no such scripture;`" and with that the priest`'s mouth was stopped.

In the last sermon that minister of Christ, William Dewsbury, preached,
are the following weighty expressions:
"`Do not make the way to heaven easier on your minds
and imaginations than indeed it is.`"
"`All shuffling people that would have salvation by Christ,
and will not let Him exercise his heavenly power--his princely,
glorious power--to baptize them into his death,
it is they that come short of salvation.`"
"`I was made a Christian through a day of vengeance and burning as an oven,
and the haughtiness and pride of man in me was brought low.`"
