== Chapter XIII. War

The Society of Friends, at their very rise,
saw the inconsistency of wars and fightings with
the loving spirit of the Gospel of Christ.
When George Fox was a prisoner at Derby, in 1650,
he was brought before the commissioners,
who wished to make him captain over some soldiers, who had recently been enlisted.
They asked him, if he would not take up arms for the commonwealth against Charles Stewart.
But he answered that according to James`' doctrine, wars arose from the lusts,
and that he lived in the virtue of that life and
power that took away the occasion of all wars.
As he refused to join the army he was sent back to prison.
After some months`' further confinement an effort was made to press him for a soldier,
but he steadily refused.

The records of the Society furnish many instances of the firmness
with which Friends refused to perform military services.
One of the most interesting of these is the case of Richard Seller:

Richard Seller was a fisherman of Kilnsea, on the coast of Yorkshire,
who had been convinced of the truth of the Gospel, as held by the Society of Friends.
During the war between the English and Dutch, about the year 1665,
he was pressed at Scarborough into the king`'s service,
and forcibly conveyed on board the flag ship _Royal Prince_,
commanded by admiral sir Edward Spragg, and having on board nearly one thousand men.
Being commanded to go to work at the capstan, he declined,
and told them that not being free to do the king`'s work,
he would not live at his charge for food.
Upon this the boatswain`'s mate beat him severely;
and he was ordered on the quarter deck,
where the captain asking him the reason of his refusing to fight,
or partake of the ship`'s provisions, he replied that he was afraid of offending God,
and dared not fight with carnal weapons;
whereupon the captain also fell upon him with his cane,
knocking him down three or four times on the deck,
and beating him very severely as long as he had strength to do it.
One Thomas Horner coming up, who had had some acquaintance with Richard,
entreated the captain "`to be merciful,
for he knew him to be an honest and good man;`" but the captain in his fury exclaimed,
"`He is a Quaker--I will beat his brains out!`"--and falling upon him again,
beat him until he became exhausted, and then called another person to help him.
After this they tied ropes to his wrist,
and reeving the ropes through two blocks in the mizen-shrouds, hoisted him aloft,
and fastened the ropes, so that he hung there by his wrists for some time,
a butt for the vulgar jests of this wicked crew.

Then they let fly the ropes, and he fell upon the deck.
The captain called to the boatswain`'s mate, to "`take the Quakerly dog away,
and put him to the capstan, and make him work, and beat him, and spare him not.`"
This man performed his officer`'s command thoroughly, beating Richard unmercifully,
tying his hands to the capstan,
and making the men thus haul him around with them by main force.
But the fastenings of his hands coming loose by some means which no one could explain,
the conscience of this guilty man appears to have been aroused;
he thought it was done by an invisible hand,
and his mind was so strongly affected by the circumstance,
that he "`promised before God and man, that he would never beat or cause to be beaten,
either Quaker or any other man that refused for conscience`' sake to act for the king,
and if he should, he wished he might lose his right hand.`"

This man`'s turn came now to suffer.
He was called up before the admiral, for refusing any longer to beat Richard Seller,
and being desired to answer for himself, he said, "`I have beaten him very sore,
and I seized his arms to the capstan`'s bars, and forced them to heave him about,
and beat him--and in three or four times of the capstan`'s going about,
the seizings were loosed, and he came and sat down by me.
Then I called the men from the capstan and had them sworn,
whether they had loosed him or not,
but they all denied that they either loosed him or knew by what means he was loosed;
neither could the seizings ever be found.
Therefore I did and do believe that it was an invisible power that set him at liberty,
and I did promise before God and the company, that I would never beat a Quaker again,
nor any man else for conscience`' sake.`"
At this the admiral told him, he must lose his cane (the insignia of his office);
which he willingly yielded.
He added, that "`he must also lose his place,`" which also he was willing to do.
He then told him "`he must lose his right hand;`" when he held it out, and said,
"`take it from me if you please.`"
So they took his cane from him, and displaced him,
but did not fulfill the other barbarous threat.

Richard was given in charge by the admiral to seven men,
who were commanded to beat him wherever they met with him, for seven days and nights,
and to make him work; the first of which they did till they were weary,
and desired to be excused.
Another man then undertook it, and beat him occasionally for a day and a night,
when he also desired to be excused.
The admiral having him stripped, and examining his body, could find no bruises,
at which he grew angry with the men for not beating him enough;
but Captain Fowler replied to him,
"`I have beaten him myself as much as would have killed an ox.`"
The jester,
(a silly man often in those days retained about the persons
of the nobility to make merriment by his fooleries),
who had instigated them to the hoisting punishment,
said "`He had him hung a great while by the arms
up aloft in the shrouds,`" and the men declared,
"`They also had beaten him very sore, but they might as well have beaten the mainmast.`"
The admiral, however, was inexorable, Richard was laid in irons,
and the ship`'s company by proclamation prohibited, on pain of similar punishment,
from providing him with food.
So he lay in irons day and night for nearly two weeks, and would probably have famished,
but that two Friends of Bridlington had, early after his seizure,
sent him a supply of provisions.
As it was, he grew very ill with a fever.

After some days, the remainder of his food being taken away,
the carpenter`'s mate secretly provided him with some refreshment,
telling him that he had of his own, independent of the ship`'s provisions,
and that before he came on board he was strictly charged by his wife and mother,
"`That if any Quaker came on board,
he should be kind to them;`" he added that he had
also lately received a letter from them,
wherein they repeated their charge, "`to remember his promise, and be kind to Quakers,
if any were on board.`"
This man, however, was soon sent away from the vessel on some occasion,
and Richard remained without sustenance for three days and nights.

After suffering in this way for a considerable time, the admiral called a council of war,
composed of the officers of that and other ships,
to decide on the final punishment to which Richard Seller should be condemned.
Being so lame with the irons that he could not stand,
he was set on a bulkhead to hear his sentence.
The judge or president who was governor of Dover Castle, was a papist,
and when they were much divided in sentiment, to what death to subject their prisoner,
this man proposed that he "`Should be put in a barrel
or cask driven full of nails with their points inwards,
and so rolled to death.`"
But the council of war thinking this too horrible a punishment,
agreed that he should be hung.
The poor innocent prisoner meanwhile was lifting up his heart to the God of his life,
who left him not in his extremity, but raised his mind above all earthly things,
endued him with sudden strength, and enabled him to declare to the assembly,
that "`The hearts of kings themselves were in the hand of the Lord,
and so were theirs and his; that he valued not what they could do to this his body,
for he was at peace with God and with all mankind, even with them, his adversaries;
that he could never die in a better condition,
for the Lord had satisfied him that his sins were forgiven,
and he was glad in his mercy that He had made him willing to suffer for his name`'s sake,
that he was heartily glad and did really rejoice with a seal to the same in his heart.`"

His accusers and judges could not bear this, and most of them slunk away.
A man came and laid his hand on Richard`'s shoulder, saying,
"`where are all your accusers?`"
And looking round he found them gone.
The admiral, however, being still there, he showed him his terrible sores,
produced by the irons on his limbs; and an old soldier coming up, put off his cap,
and kneeling down on his bared knees before the commander,
with the obsequious etiquette of the navy, begged his pardon three times,
and having got liberty to speak, thus addressed him: "`Noble Sir Edward,
you know that I have served his majesty under you many years,
both in this nation and other nations by sea, and you were always a merciful man;
therefore do I entreat you in all kindness, to be merciful to this poor man,
who is condemned to die tomorrow, and only for denying your order,
for fear of offending God, and for conscience`' sake; and we have but one man on board,
out of nine hundred and fifty, which does refuse for conscience`' sake;
and shall we take his life away?
No, God forbid.
For he has already declared, that if we take his life,
there shall appear a judgment on some on board within eight and forty hours;
and to me it has appeared; therefore I am forced to come upon quarter-deck before you,
and my spirit is one with his.
And therefore I desire you in all kindness, when you take his life,
to give me the liberty to go off;
for I shall not be willing to serve his majesty any longer on board ship.
So I do entreat you once more, to be merciful to this poor man.`"

The chief gunner also, who had been formerly a captain, came in the same humble manner,
and begged for Richard`'s life.
The admiral, however, persisted, and desired him to go down,
and spend the day in taking leave of his acquaintances on board.
That night, one of the men kindly offered him the use of his hammock,
and he obtained the luxury which had long been denied him,
while he lay continually in irons, of a good night`'s rest.

About eight o`'clock the next morning, the captains of the other ships,
who had joined in the council of war, having come on board,
and a rope being fastened on the mizzen yard arm, with a boy ready to turn him off,
Richard was brought out to be executed.
Coming to the spot, the commander asked the council how their judgment stood?
And most of them consenting, he turned to the prisoner, and desired him freely to speak,
if he had anything to say before his execution.
He replied that he had little at present to say.
Then came a man who bid him go forward to be hung;
and he stepping on the gunnel to go towards the rope, the commander bid him stop there,
if he had anything to say.
At this juncture,
when perhaps the hearts of some were softening at the fate
which seemed impending over this innocent sufferer,
the person who had acted as judge on the trial,
incautiously showed his bigotry by the remark, "`Sir Edward is a merciful man,
that puts that heretic to no worse death than hanging:`"
The word "`heretic`" struck the ear of the admiral,
who professed himself a protestant;
and scorning to be made a tool to execute the vengeance of a papist,
he turned quickly about, and asked him what he had said.
"`I say,`" replied he, "`that you are a merciful man,
that puts him to no worse death than hanging.`"
"`But,`" said the commander,
"`what is that other word that you said?--'`that heretic.`' I say,
he is more a Christian than yourself; for I do believe that you would hang me,
if it were in your power.`"
And turning to his prisoner, he said: "`Come down again;
I will not hurt a hair of your head, for I cannot make one hair grow.`"
He immediately caused it to be proclaimed three times over,
that if any credible man on board would give evidence
that Richard had done anything deserving of death,
he should have it; but no one appearing,
he proclaimed "`That the Quaker was as free a man as any on board.`"
So the men, who filled the shrouds, tops and decks, heaved up their hats,
and loudly cried: "`God bless sir Edward; he is a merciful man.`"

And thus did the Almighty Caretaker of his lowly, dependent children,
defeat the evil intentions of those who sought the life
of this faithful sufferer for the cause of a pure conscience,
and for his testimony to the peaceful nature of true Christianity.
Great was the peace with which his soul was filled on this memorable day.
Much kindness was shown to him by all on board,
but he declared that the "`great kindness of the Lord exceeded all.`"

Being thus preserved from death,
he was soon after made instrumental to the saving
of the ship and the lives of many on board.
It appears that he was visited by a remarkable dream or vision,
in which it was shown him that the vessel would be
engaged with the Dutch on a certain sand-bank,
and in imminent danger of running aground, and so becoming a prey to the enemy.
And though it was death, by the rules of the navy,
for anyone to say anything calculated to discourage the crew in time of battle,
yet he was not easy without mentioning the circumstance to one or two of the officers;
and when afterwards they were engaged in battle, he, from the shrouds,
pointed out to the pilot the very sand-bank which had been
marvellously manifested to him several days before,
when he and the rest were entirely unacquainted with such a shoal.
The vessel was immediately turned about,
in spite of the commander`'s orders to the contrary, who knew nothing of the danger;
and they were thus suddenly rescued from running aground through
the instrumentality of this despised and abused man.
During the engagement he was employed in attending to the poor wounded and dying men;
and again saved the ship from danger by pointing out a fire-ship
rapidly approaching them through the smoke,
filled with combustibles,
in order to set them on fire by the collision which would soon have taken place.

About a week after this they were again engaged with the Dutch,
and Richard was as before employed in carrying down and attending to the wounded men.
This day they lost about two hundred of their ship`'s company.
In describing this day`'s work he says: "`The lieutenant meeting me,
asked me if I had received any wound.
I told him none.
He asked how I came to be so bloody.
Then I told him,
'`It was with carrying down wounded men.`' So he took me in his arms and kissed me;
and this was the same lieutenant that persecuted me so with irons at the first.`"

Soon after this, the vessel arriving near Chatham, the admiral came up to Richard,
and laying his hand on his head, said: "`You have done well, and very well,
too,`" and gave him liberty to go ashore.
Richard requested from him a certificate to show that he had not run away.
The admiral, knowing he was a fisherman, and likely, from his occupation,
to be exposed again to be pressed on board some ship of war, said:
"`You shall have one to keep you clear at home,
and also in your fishing;`" and having it made out, he signed it and gave it to Richard,
wishing him well, and desiring to hear from him if he got well home.
His pay was offered him, but he refused it, and told them he had money of his own,
which he hoped would serve him till he reached his home.

Such is the remarkable narrative of the sufferings of this faithful man,
who rather than violate his conscience by being instrumental
to destroy other men`'s lives,
endured with patience many sore trials,
"`loving not his life unto the death,`" but was freely
resigned to martyrdom for his testimony against war,
and was preserved from it at the last extremity by a memorable interposition
of Him who can change the hearts and purposes of men at his will.
And thus was he enabled to triumph over the malice of his enemies, who,
conscious at length of his innocence and virtue, became his friends and favorers.

The narrative of Thomas Lurting is, perhaps, equally instructive:

He was for some time boatswain`'s mate on board a British man-of-war,
and during the period of his being thus employed,
experienced many remarkable preservations from death,
which appear to have made a deep impression on his mind,
as being evidently the fruits of Divine protection,
and affected him with feelings of gratitude and tenderness.

About the year 1654 there was, among the soldiers in the ship in which he then served,
a young man who had been at a meeting of the Quakers in Scotland, and was,
in some degree, convinced of their principles.
Through the instrumentality of this young man,
two of the ship`'s company were seriously impressed,
and often met together in silence for the purpose of Divine worship,
which attracting attention, others were induced to come and see them,
by which means their number increased.
The peculiarity of their demeanor in declining the customary compliments of the world,
and refusing to repair to the ordinary worship on board the ship,
occasioned them much unfriendly treatment from their associates,
in which Thomas Lurting joined with furious zeal,
and being encouraged by the captain and priest,
often beat and abused them when religiously met together.
This conduct, however, was far from affording him peace of mind,
and his former deliverances being fresh in his remembrance, he soon desisted, and,
being now brought under condemnation for his sins, he was,
through various inward exercises,
and after much struggling against so humiliating an alternative,
constrained to acknowledge the truth of that which he had so recently despised,
and from a sense of religious duty joined in connection
with those seriously-disposed people.

This change subjected him, among the rest, to much suffering, and,
having received the name of Quakers, they were, in common with that people,
made the objects of scorn and derision.
In this the captain was exceedingly active and bitter,
and even after the men in the ship refused any longer to molest them,
would procure men from other ships for that purpose.
Some time after, a sickness prevailed on board the ship,
by which above forty lives were destroyed in a short time.
This visitation so affected the captain that from
that time his disposition towards them was changed,
and instead of an enemy, he became, apparently, their friend;
often sending Thomas part of his own provisions, and became so well pleased with him,
that when anything was to be done, he would often say to Thomas:
"`Take your friends and do such and such a thing;`"
for though they had received the name of Quakers,
yet they had not had any communication with that people,
and had not yet seen the impropriety of war, and, when sent upon any such expedition,
commonly succeeded beyond expectation.
Although, with others, they annoyed their enemies,
yet they would take none of the plunder.
In many desperate engagements in which others were often killed or wounded,
they received no hurt,
though they behaved themselves so valiantly that the captain
would say "`that he cared not if all his men were Quakers,
for they were the hardiest men in the ship.`"

But this time of liberty Thomas looked upon as the forerunner of further trouble,
for he saw that what was done in pretended friendship was but to serve their own ends,
and therefore he expected a time of trial, which soon arrived,
in which their faithfulness was to be proved.

Their ship having been ordered to go to Barcelona,
the station assigned her was to lie against a castle and batter it,
and one corner of the castle firing into the ship,
Thomas Lurting was for beating down that part; he, as well as his friends,
having fought till now with as much courage as any.
Accordingly,
he (being stripped to the waist) went into the forecastle and levelled the guns,
but said: "`Fire not till I go out and see where the shot lights,
that we may level higher or lower;`" but as he came out of the door,
suddenly the thought ran through him: "`What if now you kill a man?`"
This struck him as a thunderbolt,
and He who can turn the hearts of men at his pleasure
so completely changed his in a moment that,
although just before bent upon destroying his enemies, he now felt no disposition for it,
though it were to gain the whole world; and, immediately putting on his clothes,
he walked on the deck as though he had not seen a gun fired.

At night they removed out of reach of the castle`'s shot,
and Thomas took occasion to speak with two of his friends,
inquiring their judgment in regard to war; they said but little in answer, only,
that if the Lord sent them well home, they would never engage in it again.
To which he returned, that if he was faithful to the Divine witness within him,
and the action was renewed again on the morrow,
with the Lord`'s assistance he should bear his testimony against it,
for he clearly saw that, as they had been such great actors in fighting,
they must now bear their testimony against it, and abide the issue.
Some time after, one of Thomas`'s friends went to the captain, desiring to be cleared,
and the captain asking for what reason,
he answered "`that he could fight no longer;`" to which the captain replied:
"`He that refuses to fight in time of engagement, I will put my sword through him.`"
Then,`" said the other, "`you will be a manslayer,
and guilty of shedding blood;`" for which the captain
beat him severely with his fist and cane,
and he who had before professed to be their friend now became their open enemy.

In the course of a short time, being about the year 1655,
they were ordered to go a-cruising, and discovered, one morning,
a ship bearing down upon them, which they supposed to be a Spanish man-of-war;
when orders were given to clear the ship for battle, Thomas,
being sensible that a time of trial was now come,
earnestly desired of the Lord that he might be endued with strength for the occasion;
and being met with his friends, he told them that things looked dark and cloudy,
yet his hopes were that the Lord would deliver all such as were of his faith; adding:
"`The captain puts great confidence in you,
therefore let us be careful that we give no just occasion for offence.
Let us meet in the most public place on deck, in full view of the captain,
that he may not say that we deceived him in not telling him we would not fight.`"
Being thus met upon deck, in a little time, the lieutenant said to one of them:
"`Go down to your quarters;`" to which he replied:
"`I can fight no longer;`" upon which the lieutenant went to the captain, and,
making the worst of it, said: "`Yonder the Quakers are all together,
and I do not know but they will mutiny, and one says he cannot fight.`"
The captain, having asked his name, came to him, threw his hat overboard,
and beating him with his cane, dragged him to his quarters, and having got his sword,
came in an angry, threatening manner towards them, when Thomas stepping forward,
with his eyes fixed upon him with great seriousness,
the captain`'s countenance turned pale, and he called his man to take away his sword.
The ship they had seen proving to be a Genoese, their friend,
the captain sent in the priest in the evening to excuse his anger.
Thus this storm was overcome, and Thomas finally got safe home.

Now, leaving men-of-war, he went to sea in a merchant vessel,
out of which he was several times pressed into the king`'s service,
and for bearing a faithful testimony to the peaceable nature of Christ`'s kingdom,
suffered much.
Once he fasted five days, taking only, at times, a draught of water,
believing that if he had eaten of their provisions
it would have gone the harder with him,
as he scrupled to do even ship-work,
not being satisfied to render any assistance to those whose business it was to fight.

Having premised thus much, we have now to observe how,
without violating his pacific principles, he re-took a ship from pirates.
This circumstance, while it exemplifies the care of Divine Providence over his servants,
may serve for an answer to those who are often inquiring how the doctrines of the Gospel
are to be maintained when its disciples are invaded or attacked by wicked men.

The vessel in which he was mate (the master being likewise a Friend,
or Quaker) was sailing in the Mediterranean, and, passing near the island of Majorca,
was chased by an Algerine pirate, from which they endeavored to escape by sailing, but,
carrying too much sail, some of their rigging gave way,
and the Turks were thus enabled to overtake them.
They commanded the master to go on board, who accordingly, with four of his men,
went in his boat, leaving the mate with three men and a boy on board his vessel.
As soon as they came to the pirate,
thirteen or fourteen of the Turks went in the boat to the English ship,
leaving the master and four men behind.
This brought the mate into much anxiety,
particularly as the men who were left with him were rather unruly.
In this strait he was, however, made to believe that he would not go to Algiers,
and having had great experience of the Lord`'s mercies,
he had learned to trust in Him almost against hope.
This inward assurance divested him of all fear,
and going to the ship`'s side to see the Turks come in,
he received them as though they were his friends, showed them all parts of the ship,
and what she was laden with, saying to the men that were with him:
"`Be not afraid--for all this we shall not go to Algiers.`"
He then desired them, as they had been willing to obey him,
to be as willing now to obey the Turks, to which they agreed,
and soon perceived that by so doing they gained their confidence, and they,
seeing the diligence of the English seamen, became careless,
and having taken a small part of the lading, some went again to their own ship,
leaving eight of their number behind.
Upon this the mate said that if the master and four men were now on board,
he should not fear if there were twice as many Turks.

He thus encouraged the seamen, who, not being of his persuasion,
would have been ready to kill the Turks, if an opportunity had offered.
Meanwhile, it was the mate`'s earnest prayer,
that the Turks might be induced to send their captain and men back,
and his desire was answered, for soon after, they were permitted to come on board.

Then all fear of going to Algiers was taken away, and he said to the men,
some of whom blamed his behavior, "`I now believe I shall not go to Algiers;
and if you will be ruled by me, I will act for your delivery as well as my own.`"
At this time, however, he saw no way for it, although he spoke thus boldly,
the Turks being all armed, and themselves without arms.
Upon his saying to them, shortly after, when they were all together, except the master:
"`What if we should overcome the Turks and go to Majorca?`"
Says one, "`I will kill one or two;`" "`and I,`" said another,
"`will cut as many of their throats as you will have me.`"
But of this the mate entirely disapproved, not intending to injure one of them,
and told the men, that if he knew they would touch a Turk in that way,
he would tell the Turks himself, "`but,`" said he, "`if you will be ruled by me,
I will act for you, if not I will be still.`"
They, seeing that he would not allow them to have their own way,
agreed to do as he would have them.

He then directed them, that if the Turks bid them do anything,
to do it without hesitation, and with as much diligence and quickness as possible;
"`for,`" said he, "`that pleases them, and will induce them to let us be together.`"
To this, the men all agreed.
Upon informing the master of his intentions, he remarked,
that if they were to attempt to revolt and should fail and be overcome,
they might as well be burnt alive, and indeed, the mate knew that in such an event,
they would be punished with great cruelty.
The master was fearful, that in order to gain their ends, blood might be spilled,
and therefore hesitated to consent to the proposal;
but the mate assuring him that he was resolved not to spill a drop of blood,
and that he would rather go to Algiers, than one Turk should be killed,
induced the master to consent that he should do as he pleased.

Meanwhile, the weather became stormy, so that they lost sight of the Turkish man-of-war,
which was what the mate desired, and the Turks,
seeing the diligence of the English sailors, grew careless about them.
A few nights afterwards, the captain of the Turks and one of his companions,
having gone to sleep in the cabin with the master,
the mate persuaded one to lie in his cabin, and another in another,
and it raining very much, he at last persuaded them all to lie down,
and when they were all asleep he got their arms into his possession; this done,
he said to his men, "`Now we have the Turks at our command,`" warning them,
at the same time, that if they attempted to injure them, he would be against them.
So carefully did he guard his prisoners against violence and injury.

They then steered for Majorca, keeping the Turks below deck; and having a strong gale,
were in sight of it by morning.
The Turks, when they found the situation they were in, and that,
instead of their own country, they were in sight of Majorca, were completely surprised;
but, so far were they from attempting to resist, their spirits sunk,
and they begged they might not be sold.
This, the mate assured them, should not be done, and,
in order to avoid any difficulty with the Spaniards, he contrived a place to hide them,
that they might not be found.
Arriving in port, the master having attended to his business on shore,
returned without taking license, fearing the Spaniards might come on board,
and take away their prisoners.
At night, the captain of another English ship which was lying there, came on board,
and was told, under a promise of secrecy, what had occurred.
Upon hearing it,
he wished very much to have two or three of the Turks to take with him to England;
which being denied him, and finding he could not prevail on the master or his mate,
he told them they were fools for not selling the Turks,
who were each worth two or three hundred pieces of eight +++[+++dollars]. But they told him,
that if he would give many thousands, he should not have one of them,
for they hoped to send them to their own country.
The mate said, he would not sell them for the whole island.
This man going ashore, broke his promise, and told the Spaniards of the circumstance,
who threatening to take the Turks,
the captain was under the necessity of calling upon
them to assist in getting the vessel out to sea,
thus hazarding their own lives and liberty, from kindness to their prisoners.

They allowed the Turks to have their liberty for four or five days,
until they made an attempt to revolt,
which the mate prevented without injury to any of them,
though he once was under the necessity of laying hold of one;
and indeed he was so kind to them,
that some of his men said he took more care of the Turks than of them,
to which he answered that they were strangers, and they must treat them well.

They continued hovering for several days, being unwilling to put into any port in Spain,
but at length concluded to steer for the Barbary coast, which they reached in a few days.
The next consideration was how the Turks should be landed.
After several suggestions, the mate, who had been the agent thus far,
concluded to take the ship`'s boat and put them ashore.
This proposal, attended as the undertaking manifestly was, with much risk,
drew tears from both the master and the mate, but the latter, taking courage said,
that he believed the Lord would preserve him,
for he had nothing but good will in venturing his life,
and that he had not the least fear, but that all would be well.
The master having consented, the mate called up the Turks,
and going with two men and a boy into the boat, took them all in, loose and unbound,
but in order to prevent a sudden rising,
he placed their captain in the stern of the boat, then one in his lap,
and one on each side, and one in each of their laps, and so on,
till they were all seated.
He himself sat in the bow of the boat, and with a boat-hook in his hand,
having next him one of the sailors, and the other two rowing, one of them having an adze,
and the other a cooper`'s heading-knife,
which were the only arms they had except those belonging to the Turks.

Thus the boat sailed for the shore: but as they came near it,
one of the sailors becoming alarmed, cried out, there were Turks in the bushes;
and the pirates perceiving their fright, took advantage of it, and all rose up at once.
The situation of the English sailors was at that instant truly appalling; but the mate,
preserving his presence of mind, and perceiving that the alarm was unfounded,
turned the boathook in his hand,
and gave the Algerine captain a proof that he was still subject to his orders,
by striking him a pretty severe blow, and bidding him sit down, which he did instantly,
and the rest followed his example.
When the boat had arrived so near the shore that the Turks could easily wade,
he ordered them to get out, having first supplied them with sufficient provisions,
till they could reach a neighboring town.

The Turks would have persuaded the mate and his men to accompany them,
promising to treat them with wine, etc.
But although he trusted in Divine Providence,
and felt but little fear that they would ill-treat them,
yet he prudently declined their invitation, remembering the Scripture command:
"`You shall not tempt the Lord your God.`"
Being unwilling to retain anything belonging to them,
they then put the boat in nearer the shore, and threw them all their arms.
The Turks then waved their caps, and so joyfully took their last farewell.

Upon the arrival of the vessel at London, the king,
with the duke of York and several lords, being at Greenwich,
they were told that a Quaker`'s ship was coming up
the river which had been taken by pirates,
and redeemed without fighting; upon which the king came in his barge alongside,
and holding the entering rope in his hand, was told the case as it had occurred.
When he heard that they had allowed the Turks to go free, he said to the master:
"`You have done like a fool, for you might have had good gain by them,`" and to the mate:
"`You should have brought them to me.`"
To which Thomas Lurting answered:
"`I thought it better for them to be in their own country.`"
At which the king and his company smiled, thinking the master had done foolishly,
but he and his mate were of another mind,
and they made it appear that they did practically approve the command of our Saviour:
"`Love your enemies, and do good to them that hate you.`"

That wise man and noble Christian, Edward Burrough, in an epistle to Friends in 1660,
thus unfolds the position of the true Christian as respects war:

As for all confusions, and distractions, and rumors of wars, what are they to us?
What have we to do with them?
Wherein are we concerned in these things?
Is not our kingdom of another world, even that of peace and righteousness?
Has not the Lord called us, and chosen us into the possession of that inheritance,
wherein strife and enmity dwell not?
Yes, He has broken down that part in us that is related thereunto,
and being dead in that nature of strife, bloodshed, and wars,
how can we live in strife and contention in the world,
or have fellowship with any therein.
Our kingdom is inward, and our weapons are spiritual,
and our victory and peace are not of this world.
Our war is against souls`' enemies, and against the powers of darkness,
even by the sword of the spirit, which God has given us, and called us to war therewith,
to convert people from sin and death,
and from the very occasion of wars and contentions about the things that are earthly.
This is our calling and work at this day;
and these things all the children of the Lord are to mind,
and to keep over the spirit of this world in all people, which all this enmity,
strife and confusion that is up among men, lodges in, and arises out of it.
These things are the fruits of the spirit of this evil and sinful world,
and the fruits of the spirit of God are of another nature,
even peace and meekness towards all, and not enmity towards any.
In this spirit let us live and walk, admonishing all hereunto,
and praying for our enemies, and not hating them, but doing good for evil,
and not rendering evil for evil; but being meek and humble,
merciful and patient towards all.

When John Richardson visited the Island of Barbados in the year 1702,
he had an interview with the governor, when the following conversation occurred:

"`I want to know the reasons why you as a people
do not assist the king and country with men and arms,
for their and your own defence and safety, against all that may attempt your hurt.`"
I replied, "`The most convincing reasons I have to offer to the governor are:
we have neither precept nor example from Christ or his apostles,
to use the sword to hurt one another with.`"
"`No!`"--said he, "`what then means that saying of our Saviour,
when He bade him that had no sword, sell his cloak or coat and buy one?`"
I replied, "`one of his disciples answered and said, '`Lord here are two;`' Christ said,
'`it is enough.`' Now how two swords can be enough to answer for a general precept,
I leave the governor and all these men to judge.`"
So after a little pause he said, "`In case you were assaulted by robbers,
that would break your house and take what they could get from you; or upon the highway,
and would take your purse or horse, what would you do in that case?`"
I replied, "`I could not directly answer what I should do in such a case,
because through the Lord`'s mercy I was never yet so assaulted;
but it appears most likely, that I should endeavor to keep my house from being broken up,
and yet be tender of men`'s lives; and as to the other assault,
inasmuch as it is well known I do not provide any outward weapon for my own defence,
neither sword, pistol, nor any such like weapon,
therefore I must rely upon the Lord for protection and help,
who is able to rescue me out of the hands of all such ungodly men; or if He does not,
I must endeavor to bear what the Lord allows such to do to me.`"
The governor said, "`You say well,
for inasmuch as you have not provided anything for your own defence,
you have nothing to fly to but the Lord;
you say very well;`" and said he hoped what he had offered had not given any offence.
I replied, it was so far from that, we were glad he was so free with us.

In the support of their testimony against war, Friends in Pennsylvania, New Jersey, etc.,
were brought under much concern near the middle of the eighteenth
century by the outbreak of hostilities with the Indians and French,
and the growth of a military spirit among the people who then far outnumbered our members.
The minutes of the Meeting for Sufferings in 1757,
contain the following remarkable statement:

There are some yet living in this country, who are witnesses,
that so long as the people lived in the fear of God, walked in humility before Him,
and kept his holy laws and commandments, it went well with them and with their children;
the land rejoiced, the blessing of the Most High was known, and his powerful,
protecting providence, remarkably conspicuous; for though we had no outward barrier,
the sword was not permitted to enter within our borders,
but the salvation of the Lord was a defence round about; but now blood has been spilt,
and the land is polluted therewith, and the sound of war is heard.

A few years after these troubles had passed away,
the attempt of the British government to impose a tax on the colonies,
awakened a strong feeling of resistance,
which eventually brought about the war of the Revolution,
and necessarily caused much anxious solicitude for the preservation
of our members in the peaceable spirit of the Gospel.
In 1769 the Meeting for Sufferings of Philadelphia,
issued an epistle of advice and caution:
"`To our Friends and brethren in these and the adjacent provinces,`"
earnestly exhorting them "`to guard against promoting or joining
in any measure proposed for the support of our civil liberties,
which on mature consideration, may appear not to be dictated by the wisdom from above,
which is pure, peaceable and gentle.`"

As the unsettlement and political stir continued and increased,
the Meeting for Sufferings in 1774, extended a fresh caution to our members,
to keep as much as possible from mixing with the people in their human policy and contrivance,
and to forbear meeting in their public consultations.
"`It being a season in which it is abundantly needful to seek best wisdom to guide and
to preserve in safety and consistency of conduct with our religious profession and principles.`"

The continued efforts of Friends to preserve their members from
being drawn into any violation of their peaceable principles,
naturally brought upon them much ill-will and censure
from those who were fanning the flames of war.
The odium thus excited led to much unjust, illegal,
and harsh treatment of individual Friends in many places;
and in Philadelphia caused the banishment from their
homes of a considerable number of prominent Friends.

The war of the Revolution had been going on about two years, when,
in the Eighth Month of 1777,
a large portion of the British army stationed at
New York was embarked on board the fleet,
and proceeding along the coast, entered Chesapeake Bay,
and finally was landed near its head, within the State of Maryland;
from there they marched northward,
and after defeating the American forces at the battle of Brandywine,
entered and held possession of the city of Philadelphia.

Immediately upon the receipt of intelligence that the British
army had landed at the head of Chesapeake Bay,
Congress,
anticipating their march through Pennsylvania with the intention of occupying its capital,
passed a resolution recommending the executive officers of the States of Delaware
and Pennsylvania to cause all persons within those States notoriously disaffected,
to be forthwith disarmed and secured,
until such time as they might be released without injury to the common cause;
and also recommending that the Supreme Executive Council of the State of Pennsylvania
cause search to be made in the houses of the citizens of Philadelphia who had
not manifested their attachment to the American cause,
for swords, fire-arms, bayonets, etc.

As it was known by all that Friends never armed themselves
or used any warlike weapons in self-defence,
it is apparent that upon any fair construction,
this resolution was not applicable to them.
But the community was in a ferment,
and the fears of the people excited by the prospect
of being speedily visited by a hostile army;
and there were not lacking those who gladly embraced the occasion to call
into action the popular suspicion of and partisan hatred against Friends.
To increase these passions, Congress, at this juncture,
received a dispatch from general Sullivan, containing a paper,
said to have been found among some baggage captured on Staten Island,
which paper purported to have been prepared in and by a Yearly Meeting of Friends,
held at Spanktown, near Rahway, N. J., on the nineteenth of the Eighth Month, 1777.
It professed to give information respecting the position of the army under general Washington,
and the detachment under command of general Sullivan,
and was otherwise so worded as to create an impression or belief
that Friends were engaged in obtaining information for,
and transmitting it to, the British, and thus betraying the cause of their country.

Who the author of this clumsy forgery was has never been discovered,
but it seems marvellous how anyone with common sense could have been imposed upon by it.
It was incredible that a Society would be engaged in a proceeding which,
if proved upon them, would subject its members to capital punishment,
and so date and certify the evidence of their guilt,
that if their dispatch should happen to fall into the hands of those they were betraying,
there could be no difficulty in identifying the authors.
Beside this,
the date of the paper and that of some of the occurrences
it mentioned showed it to be a forgery.
It was dated the nineteenth of the Eighth Month,
and yet it gave information of the landing of the British army in Maryland,
which did not take place until the twenty-second,
the news of it not reaching Philadelphia until the twenty-third,
and could not have arrived at Spanktown before the twenty-fourth or twenty-fifth.
It, however, served the purpose no doubt intended by its wicked author.

Between the first and the fourth of the Ninth Month,
seventeen members of our religious Society--men of unimpeachable character,
and exemplary in all the relations of life--were
suddenly taken into custody by a military force,
at their own homes or places of business,
and without knowing the offence with which they were charged,
without a hearing before any tribunal, they were placed in strict confinement,
with a guard set over them.
It was decided to send these persons to Winchester, Va.

The prisoners felt it to be their duty to present a remonstrance
to the council against the course pursued towards them,
in which they claim the rights of freemen,
point out the gross infraction of law and equity in the several acts committed upon them,
and appeal to the humanity and sense of justice in the members,
to induce them to grant them a hearing,
and allow them to defend themselves from whatever charges might be brought against them.
Their remonstrance concludes as follows: "`But if,
regardless of every sacred obligation by which men are bound to each other in society,
and of that Constitution by which you profess to govern,
which you have so loudly magnified for the free spirit it breathes,
you are still determined to proceed,
let our appeal then be to the righteous Judge of all the earth,
for the integrity of our hearts and the unparalleled tyranny of your measures.`"

They were continued in exile nearly eight months,
and their plain and earnest statements of the injustice
of so treating men against whom no crime was charged,
and who had been taken from their homes on mere suspicion of what they might do,
must have been very galling to those who represented themselves as contending for liberty.
Two of their number died in exile, the others were restored to their families and homes.

During the period of the Revolutionary war,
Friends were not only exposed to suffering from exile and imprisonment,
but by military distraints and in other ways, lost greatly in property.
Henry Hull, in his Memoirs, says:
"`They were stripped of nearly all their personal property.`"
This confirms the statement sent up to Philadelphia Meeting for Sufferings in 1779,
that the amount of property taken from Friends in five of the quarters (the other
three not reporting) was nine thousand five hundred and fifty-one pounds,
eighteen shillings and four pence.

That the sufferings which Friends in America faithfully endured,
were not without producing their legitimate fruits,
is indicated in an epistle received from London Yearly Meeting in 1779, which says:
"`We think we perceive in your account the evident traces
of Divine regard and mercy to the churches among you.
The zeal with which many Friends from distant places and through many dangers,
attend your solemnities.
The love and harmony that prevails among you,
the sacred unction that is apparent in the conduct of your affairs,
evidently betoken that the refining Hand has not been at work in vain.`"

Amid the popular excitement that prevailed,
it is not a matter of surprise that some of our members
deserted our testimony against war.
Wishing to retain other peculiarities of the Society,
they organized a body called "`The Free Quakers,`" and applied to the Monthly
Meetings in Philadelphia to appropriate one of the meetinghouses for their use.
This request being refused,
they presented a petition for the same object to the legislature of Pennsylvania.
In this they state that many of them had been disowned for
bearing arms and otherwise participating in the late struggle,
and they ask leave to bring in a bill which shall recognize
their right to a share in the property of the Society,
notwithstanding their disownment.

Friends, in reply to this petition,
assert the right of every religious society to determine the requirements of membership,
and to separate from their communion those who refuse to comply therewith.
This effort to procure legislative aid having failed,
the Free Quakers erected a meetinghouse at the corner of Fifth and Arch Sts+++.+++, Phila+++.+++,
by public subscription.
The number of their members gradually dwindled,
and for many years the house was used by the Apprentices`' Library Company.

Timothy Davis, a minister among Friends at Dartmouth, Massachusetts,
separated from the Society on the same ground as the Free Quakers,
but he afterwards made an acknowledgment, condemning his conduct,
and was reinstated in membership.

The situation of John Clibborn in the time of the civil wars in Ireland,
in the reign of James 2, was peculiarly perilous, being only a few miles from Athlone,
where the Irish army had established one of their principal garrisons,
from which issued parties which distressed the country.

John Clibborn and his friends continued for some time, at great hazard,
to keep up the meeting at his house, where, succoring many,
and endued with Christian patience and courage,
he remained till he was dragged in the night, by the hair of his head,
from that house which had afforded an asylum to the distressed,
but which was now the spoil of the plunderer and of the flames.
His life was attempted three times by those bloodthirsty men, who, at length,
desperate in their wickedness, laid his head on a block, and, raising the hatchet,
prepared to strike the fatal blow.
He requested a little time.
His request was granted.
The pious man knelt down, and in the words of the martyr Stephen,
prayed that this sin might not be laid to their charge.
With a prospect of a better world before him, he prayed not for his own life.
Just then another party arrived, and inquiring,
"`Who have you got there?`"--were answered, "`Clibborn.`"
"`Clibborn,`" re-echoed they; "`a hair of his head shall not be touched.`"
Thus escaping with his life, though stripped almost naked,
he wrapped a blanket about him,
and presenting himself before the commanding officer at Athlone,
informed him of the treatment he had met with.
The officer desired John to point out the men who had committed this outrage,
and they should be hanged before his hall door.
This he refused to do, declaring that, owing them no ill-will,
he desired not to do them the smallest injury, and that all he wanted was,
that his neighbors and himself might be allowed to live unmolested.

This good man saw tranquillity restored to the land,
and thankfully enjoyed that blessing which those
who have witnessed its interruption can best appreciate.
He was diligent in attention to religious duties, preserved in unity with his Friends,
and in love to all mankind to the end of his long life, which closed in 1705,
at his house at Moate Grenoge.

War is a dreadful and wicked business, wholly at variance with the meek,
lowly and loving spirit of the unresisting Lamb of God;
and the closer his disciples walk with Him, doing his will,
the further are they removed from those cruel lusts and passions in which it is conducted.

Those who have entirely renounced it,
and faithfully upheld the non-resisting peace principles of the Gospel,
have often experienced remarkable preservation in imminent danger,
and had cause to admire the gracious interference of Divine Providence in their behalf.
The Irish rebellion, in 1798, furnished many memorable instances of this kind,
and illustrated forcibly the benefits of a steady adherence
to the principles of Friends in times of great danger.
A manuscript account, drawn up by Joseph Haughton, of Ferns, in Leinster,
relates scenes of which he was an eye-witness.

The writer says:

Having often meditated on the merciful preservation which I,
with others of the Society of Friends,
experienced during the awful commotions that prevailed in this land,
in and about the year 1798,
I have been desirous that they may not pass away as matters of only common occurrence.
I write this memorial that succeeding generations may see how much
"`better it is to trust in the Lord than to put confidence in princes;`"
and that to keep faithful to the Truth,
as revealed to us,
is a far more sure defence than all the efforts human policy can make or procure.

In the year 1795, the Quarterly Meeting of Leinster Province,
and afterwards the Yearly Meeting of Ireland,
were concerned that all Friends who had guns in their houses for domestic purposes,
or any other weapons, might destroy them,
in order to prevent their being taken and used for the injury of any of our fellow creatures,
it being then a frequent practice for parties of men to assail houses in search of arms.
In unison with this concern, our Monthly Meeting for the county of Wexford,
appointed a committee to go from family to family among its members,
and endeavor to prevail on them to comply with the concern of the Society.
I was with this committee, feeling my mind nearly interested in the engagement;
but seeing the necessity of first clearing my own hands,
I took a fowling-piece I had in my possession,
and broke it up in the street opposite my house,
which was matter of wonder among my neighbors.

It was a time of serious thoughtfulness,
and in many families the committee had little more to do than to communicate their business;
for the concern of the superior meetings had made its way in most minds, who,
being convinced of its propriety, had destroyed all such instruments,
and others gave full expectation of having it speedily done.
There were a few who could not be prevailed upon to make this sacrifice,
but the conduct of most of them, in other respects,
was such as to occasion their disownment.

A short time after, the government ordered all arms to be given up to the magistrates,
and it was then a very comfortable reflection that, in general,
Friends were found clear of having any such thing in their possession.
Some of the neighboring magistrates, with the clergyman, came to my house, and,
I being from home,
expostulated with my wife on the supposed impropriety of my destroying my gun,
instead of delivering it to the government for the purpose
of defending the royalists against the fomenters of rebellion,
and for the preservation of myself and family;
to which the clergyman voluntarily replied that "`he
believed I put my trust in a higher power.`"
This man was afterward murdered at Enniscorthy, on the day that town was burned,
and his body, with those of many others, exposed in the streets,
until some Friends were emboldened to go and bury them.
One of the above magistrates, named Turner, was also murdered,
and his house burned over him.

The state of things becoming more alarming, a part of the militia was stationed in Ferns.
The earl of Mount Norris came to me and desired I would give up part of my house,
then used as a store, for a guard-house for the soldiers.
The requisition was sudden, and I was put to a stand, considering what to answer.
Although I might have refused him on account of its being used as a store,
yet I knew this inconvenience might be obviated,
and therefore declined offering so poor a reason for refusal.
Considering this an opportunity afforded me to lift up the standard of peace,
and of bearing my testimony against war,
I told him the apartment was occupied as a store,
but that the purpose he wanted it for was such as I could not unite with,
having a conscientious scruple against war and everything connected therewith.

He grew very angry,
and desired the soldiers to afford me no protection in case any disturbance should arise;
to which I replied that "`I hoped I would neither
apply for nor trust to any military protection.`"
He went away greatly displeased, marking me out as a disaffected person;
so that I did not know how soon a prison might be my lot,
especially as one of the militia, who was quartered at my house,
propagated such false reports of me with respect to political matters,
that it increased the peril of my situation.
I was well compensated, however, for this little act of faithfulness,
by the incomes of peace,
which filled my heart to that degree that I was made
willing to suffer the hardships of a prison,
if this should be allotted me.

Some months after this,
the militia began to act with great vigor against such as
were suspected to be United Irishmen (or rebels),
burning their houses and stacks of corn, and fastening pitched caps on their heads.
They were preparing to burn a house of this description in our village.
I felt much pity for the man`'s wife and children,
who would thereby be deprived of a habitation;
and I undertook to intercede for them with the commanding officer.
I remarked to him that I did not come to meddle between him and the suspected person;
but, pitying his poor wife and children,
thought it would be hard to bereave them of a shelter and the means of subsistence,
when he had the man fully in his power; that if he was guilty,
probably they were innocent of his crime.
The officer got very warm in his temper, and charged the Quakers with meddling in cases,
while they would give no assistance to government.
A little time after this, when the rebel party got dominion here,
I rendered this officer some services,
and had the satisfaction of believing that his prejudices were removed,
from the grateful acknowledgments and thanks he expressed for my friendship.

About this time the military were preparing to hang some
suspected persons for not delivering up their weapons,
and to fasten pitched caps on the heads of others.
I was fearful of being applied to for ropes, which I kept for sale,
but which I could not be easy to sell for that purpose,
and yet a refusal might involve me in danger.
Martial law being proclaimed, I was at a loss to know what to do;
but when some of the military came to buy, I refused to sell ropes,
and also linen +++[+++probably to make the pitched caps],
intended to torment and destroy my fellow creatures.
They took them by force, offering me payment, which I refused to accept.
This was but a day or two before the general rising of the United Irishmen in this county,
and was, I believe, through the direction of Divine Providence,
made instrumental to the preservation of myself and family.

The next day a melancholy silence prevailed.
I inquired of a person if anything more than usual was in prospect.
I was told the country people were collecting in large bodies.
A cloud of darkness overspread my mind in such an awful
manner that it is not possible to describe it.
Like Egyptian darkness, it could be felt, and the feeling was exceedingly grievous.
At midnight all was alarm.
Guards were placed in different parts of the town,
and the Protestants were in continual terror.

I got my family to bed, but we could not rest,
yet endeavored after a state of quietude and retirement of mind,
not knowing how soon our lives might be taken by the hands of violent men.

Early in the morning, being in much anxiety as to the event, a person,
whom I supposed to be one of the United Irishmen, came in and said:
"`Let who will be killed, the Quakers will be spared.`"
I considered this like the intimation given to Gideon, in the camp of the Midianites,
while listening to the soldier`'s dream,
and which tended to dispel his fears and fix his confidence.
I felt encouraged to hope our lives might be spared.
The scenes that morning were exceedingly awful.
The houses and stacks of grain were in flames in every direction around us,
some set on fire by the yeomanry, and some by their enemies; so that, between the two,
total devastation seemed at hand.
The Protestant inhabitants were running into the towns and villages for safety;
the military guards all under arms; and, in every direction,
persons flying for protection,
escaping wounded from the hands of murderers in the country,
and bringing news that others were slain.
Property was then of little account; everyone`'s care was to escape with life.

Being informed that some of the fugitive Protestants
were much in need of something to eat,
I got food prepared and sent to invite such to partake, but none came.
In the evening the military left and marched to Enniscorthy,
and with them the Protestants, and all who came in for safety,
as well as those who lived in our village.
We knew not of their going away until the place seemed almost depopulated;
and we were favored to have a little time of peaceful quiet from the alarms of war.

We remained in doubtful suspense of what would follow until next morning,
when the town and neighborhood were filled with an undisciplined and ungovernable crowd,
consisting of many thousands of the United Irish (the rebels),
following the army to Enniscorthy, and demolishing the houses of the Loyalists,
Orangemen, etc., for the inhabitants of them had fled.

My house was soon filled with them; when, to our astonishment and humble admiration,
instead of the massacre we dreaded, we were met with marks of friendship.
They declared that they intended us no injury, but would fight for us;
adding that they required nothing from us but some provisions.
They appeared in extreme need,
and the food which had been prepared for those they
called enemies was now ready for them.

Having eaten the food offered them, they proceeded on their road to Enniscorthy, where,
in a little time after,
we could see the columns of smoke arising from the burning houses, six miles distant.
In the evening some of them returned with tidings that Enniscorthy was in their hands,
and their camp fixed on Vinegar Hill, over the town.

Next day, a man with a malicious countenance came to me, with a long spit in his hand,
and threatened to kill me for some offence which he said I had done him.
"`I have killed Turner,`" said he, "`and burned him in his own house,
and now I will rack you as I please.`"
+++[+++This Turner was probably the magistrate mentioned in the preceding part of the narrative,
who came to J. Haughton`'s about his destroying his gun]. I endeavored
to convince him of his mistake +++[+++in supposing he had offended him],
and being joined by the persuasions of a neighbor,
he was with difficulty prevailed upon to be quiet, and at length we parted in friendship.

Most of the horses being taken from Friends of our Particular Meeting,
we had generally to walk to our meetings; and the first time we did so,
some of us met a man who was very terrible,
having killed one of my neighbors a day or two before; but he was very friendly to us,
and offered to have us carried to the meeting.
We acknowledged his civility, but did not accept his offer,
pursuing our journey on foot six miles.

Parties of these people would often meet us going to or coming from meeting,
and sometimes would be very inquisitive where we came from, and where we were going;
but none of them offered us any molestation, except at one time,
when several Friends were passing through Camolin, a neighboring village,
on their way to meeting,
having a horse belonging to one Friend and a carriage belonging to another;
and a large number of the United Irishmen being in the street conversing about us,
one of them said it was the last time we should ever go that way; and,
after we had passed them a gun was fired, apparently to frighten us.
The horse took fright and broke the harness, which we endeavored to set right,
and went to our meeting place.
Before the next time for our going to meeting there,
the power of those people was overthrown.

The day after the battle of Enniscorthy, several of the poor, distressed Protestants,
mostly women, returned homeward.
Two female servants of the bishop of Ferns,
and a woman whose husband was killed the day before, with her children,
came to my door as persons that had no dwelling-place.
They stood looking about in all the eloquence of silent distress.
My house was small, but my heart and my house were both open to the afflicted;
and we endeavored to keep the house open for as many as we could accommodate,
notwithstanding the severe threatenings we met with from the then ruling party.
Such of the United Irishmen as stayed in the town,
would come at night to my house to lodge with their wives and families,
as many as we could take; supposing they might be more safe than in their own homes,
and this was also the case at the houses of other Friends.

The laws were now suspended,
and the rule was for every man to act according to his own will.
I recoil at the prospect of the wickedness of man, unrestrained by law or religion!
Well indeed did Young say;

Heaven from all eyes conceals, but from his own
That hideous sight, a naked human heart.

And it is so in great mercy--but now, for a little space,
the bosom became as it were transparent,
and the depravity of the heart seemed fully displayed in action.
I forbear to mention many scenes witnessed which I wish to be buried in oblivion,
and that are not so properly connected with the intent of these lines.

Previous to the breaking out of the rebellion,
the military had destroyed the habitation of a neighboring farmer, who with his family,
sought refuge at the house of Joseph Wright, a Friend near Ferns.
Joseph provided them one of his outhouses to live in,
until they could better their condition; but when their party +++[+++the rebels]
got the ascendancy, these persons took possession of his dwelling,
and showed their determination to turn out him and his family;
the short duration of the rebel control prevented
them from carrying out this ungrateful intention.

Friends`' houses appeared to be marked out as places for entertainment,
and were almost always full, day and night,
so that it was wonderful their provisions held out to the end.
Friends, and also some of the oppressed party,
would sometimes convey provisions to one another privately;
and the United Irishmen would occasionally offer us of their stock;
but knowing it to be plunder, or, as they called it, the spoils of war,
we always declined accepting any of it.
Our refusal was generally considered as an offence,
and it went hardly with them that they could not, in any degree,
get us to unite with them.

When the usual time for holding our Monthly Meeting at Enniscorthy came round,
I went there in company with William and Martha Wright, who were on horseback.
We got on without much interruption until we reached about half way;
when their horses were taken from them by some of
the patrol from the camp at Vinegar Hill.
We walked into Enniscorthy, not knowing where to go except to the meetinghouse.
There we met with several Friends of the town, some from Cooladine Particular Meeting,
but none from Ross, as that town was in a state of siege; nor from Forrest,
which was near Scullabogue barn, where so many persons were burned alive.

During our meeting for worship we were a good deal interrupted
by persons walking about and making a noise in an adjoining gallery,
who after a while went away.
It appeared that they came with an evil intent, which they were not permitted to fulfill.
I observed they had broken a large hole in the ceiling,
which we were afterwards told was for the purpose
of more readily setting it on fire and burning it,
but that some of their own party stopped them from carrying out their design.
After the meeting for worship was over,
our attention was turned to the transaction of the business of the Monthly Meeting,
but as only a part of the members could assemble, it was adjourned.

Afterward we had the opportunity of sympathizing with our friends in their distress.
Oh, what a humbling scene it was!
Some had to pass by their own homes, lately the abodes of peace and comfort; now,
partly destroyed by fire, some wholly so, and all plundered to desolation.
We repaired to the house of Thomas and Nathaniel Thompson, a new building,
till then unoccupied, their own particular homes,
together with a large timber-yard adjoining, having all been burned to the ground.
Here we had an opportunity of hearing each other`'s narratives of distress,
and condoling with the afflicted.
A Protestant clergyman of sober moral character, with his wife,
lodged in the house of Joseph Thompson.
When he saw the danger in consequence of the approach of the rebel army,
he requested that the clothing of a Quaker might be given him,
expecting in this disguise to find preservation, or at least to make his escape.
He was told that it would be of no avail to him,
and he then hid himself in the Friend`'s garden by the river side,
where the insurgents found and murdered him.

A woman, living within a few doors of Joseph and Martha Thompson, came to their house,
and, while making great professions of friendship and sympathy,
plundered the house and shop before their faces,
having brought horses and carriages to take their goods away with her.
In order to compel the family to leave, she set the house on fire; which,
when the owners saw, they withdrew, and went to Thomas Thompson`'s at Cooladine,
being assisted in removing by an old and faithful servant,
and by others also of the United Irishmen, who offered to help them on their way.

Thomas Thompson, the elder, and his son,
remained at Enniscorthy in the new house afore-mentioned; and it fell to their lot,
in conjunction with another Friend, Thomas Mason, to bury the dead bodies,
which were lying promiscuously and offensively about the streets, some torn by the swine.

Samuel Woodcock, Jacob Martin, and John Hancock, of Ulster Province,
being in the neighborhood of Enniscorthy,
were all made prisoners and taken to the rebel camp on Vinegar Hill.
Here they underwent a sort of trial, but no charge being brought against them,
they were set at liberty; which was indeed a mark of Divine protection,
for many other persons against whom nothing was alleged were put to death.

Previous to this, Samuel Woodcock was made prisoner at his own house,
by a number of pikemen, and taken to the house of a popish priest,
with whom he was intimately acquainted.
The priest told him he must become a Roman Catholic and be christened,
for that no other profession of religion was now to be allowed.
Samuel was much surprised,
and told him he had a better opinion of him than to suppose he
would make men profess what was contrary to their consciences.
The priest said there was no alternative but to turn Roman Catholic or to be put to death.
Samuel replied that by so doing they would only be making hypocrites of such as complied;
and for his part he would rather suffer death than violate his conscience; adding,
that if any crime was laid to his charge, he was willing to be tried for it;
but on that ground he was not afraid to look any of them in the face.

The priest, who had made every preparation for baptizing him according to their mode,
seemed much disappointed at Samuel`'s constancy,
and brought him out to the pikemen to be taken to Vinegar Hill.
Samuel expostulated with him and them together,
saying again that if anything worthy of death was
laid to his charge he was willing to undergo a trial.
Although the pikemen were much displeased that he would not become a papist,
yet they acknowledged the justness of his proposal,
and he was taken to the rebel camp as before stated.
After their remarkable liberation,
the three Friends returned to their families at Clonmel,
where they were joyfully and thankfully received by their relatives and friends; who,
when parting from them, feared they should never meet again.

During the Revolutionary war,
the inhabitants of Nantucket were placed in a very trying position.
The revolted colonies had no fleet to protect them; and,
if they declined to obey the order of Congress,
might be refused permission to trade with the main land,
on which they were dependent for food and fire-wood.
Many of the inhabitants were Friends, who could not, consistently with their principles,
take any part in military operations.

William Rotch, who was a prominent citizen of the island,
has left an interesting account of their experiences during that trying period.
He says:

When the Revolutionary war broke out in 1775,
I saw clearly that the only line of conduct to be pursued by us,
the inhabitants of the island of Nantucket, was to take no part in the contest,
and to endeavor to give no occasion of offence to either of the contending parties.

A great portion of the inhabitants were of the denomination of Friends,
and a large number of the considerate of other societies united in the opinion,
that our safety was to be found in a state of neutrality, as far as it could be obtained,
although we had no doubt that suffering would be our lot,
and which we afterwards experienced from both parties.
Our situation was rendered more difficult by having among
us a few restless spirits who had nothing to lose,
and who were often thwarting our pacific plan and subjecting us to dangers,
not caring what confusion they brought upon us, if they could gain something.
My own troubles began soon after the war broke out.
In 1764 I had taken the goods of a merchant in Boston, deceased, and insolvent,
who was deeply indebted to me.
Among these were a number of muskets, some with, others without bayonets.
The Straits of Belle Isle opened a new field for the whale fishery.
There wild fowl were abundant, and our muskets met with a ready sale,
but whenever guns with bayonets were chosen I invariably
took that instrument of war from them.
The purchaser would insist on having it, but I as strenuously resisted,
and I laid them all by.
Many years afterwards I removed to another store,
having much rubbish in the one I had left.
Among the rubbish were those bayonets, neglected and forgotten, until the war commenced,
when to my surprise they were brought into view by
an application for them by a person from the continent.

The time had now come to support our testimony against war, or forever abandon it,
as this very instrument was a severe test.
I would not hesitate, and therefore promptly denied the applicant.
My reason for not furnishing the bayonets was demanded, to which I readily answered:
"`As this instrument is purposely made and used for the destruction of mankind;
and I cannot put into one man`'s hand to destroy another +++[+++with]
that which I cannot use myself in the same way, I refuse to comply with your demands.`"
The person left me much dissatisfied.
Others came and received the same denial.
It made a great noise in the country, and my life was threatened.
I would gladly have beaten them into "`pruning hooks.`"
As it was, I took an early opportunity of throwing them into the sea.

A short time after,
he was called before a committee appointed by the court then held at Watertown,
near Boston, and questioned among other things, respecting these bayonets,
to whom he gave a candid account of his proceedings.
He adds:

I passed through no small trial on account of my bayonets,
and the clamor long continued against me.

From the year 1775 to the end of the war, we were in continual perplexities.
Our vessels were captured by the English; and our small vessels and boats,
sent to the continent for provisions, denied, and sent back empty,
under pretence that we supplied the British, which was without the least foundation.
Prohibitory laws were often made in consequence of these reports, unfounded as they were.
By this inhuman conduct we were sometimes in danger of being starved.
One of these laws was founded on information from governor Trumbull of Connecticut,
who had been imposed upon respecting our conduct in supplying the British.
I wrote to the governor on the subject, and clearly laid our distress before him,
at the same time that I assured him that nothing of that kind had taken place.
He was convinced of his error,
and was ever after very kind in assisting us within his jurisdiction.
But there were so many petty officers, as committees of safety, inspection, etc.,
in all parts, that we were sorely tried and afflicted.
It was about the year 1778, when the current was very strong against us at Nantucket.
The vessels we sent after provisions were sent back empty,
and great suffering for lack of food was likely to take place; +++[+++so]
that the people (not Friends) who thought we ought to have joined in the war,
began to chide and murmur against me.

The difficulty to which the Friends of Nantucket
were subjected in procuring the necessaries of life,
on account of the faithful maintenance of their testimony against war,
is further shown by the following extracts from letters of William Rotch,
to his friends John and James Pemberton, of Philadelphia:

Eleventh Month 24th, 1775.--The article of flour we are almost entirely destitute of,
but are now sending to different parts for, which, if we are denied,
will be exceedingly pinching to us.
What we send for, is only for the use of the inhabitants, and not for trade,
but the continent is so much against us,
that I fear it will be withheld from us&hellip; But after we have discharged our duty,
in endeavoring to get the necessaries of life, if they are denied us,
I hope we shall submit to that just Hand that permits the nation to afflict us,
knowing and acknowledging that the same Hand has also been long-suffering towards us.

Second Month 22nd,
1776.--Notwithstanding the detention of our two vessels at Baltimore for flour,
which are yet absent, we obtained sufficient for a little time forward of this:
the resolve of our court, on the ninth of Twelfth Month,
suspending a further supply from us,
not spreading through the Provinces in time to cut us off;
which providential favor ought ever to be remembered with gratitude by us.
It is a time of great exercise to many, in the prospect of approaching calamities;
but we have great cause to trust in that Arm of strength that has hitherto sustained us,
and has not given us up to the rage of those that are seeking occasion against us.
The resolve, before mentioned, is now taken off for the present,
and I hope we shall be able to get provisions necessary for the ensuing summer,
for which we are now sending vessels.
We have several times had very gloomy prospects,
and came near to being in great need of bread,
but have hitherto been wonderfully favored with some opening to obtain it,
before the pinching time came.
But to be so dependent on the will of men in these things,
especially in a country abounding therewith, is a trial to faith and patience;
and I heartily wish it may have a proper effect upon us,
and convince us where our sole dependence ought to be.
Was that the case, we need not fear what the rage of man could do;
whose limits would be "`thus far shall you come,
but no further;`" but unless those favors that we so often witness operate rightly in us,
what can we expect but to be delivered into the hands of such.
While I am thinking of our own difficulties,
I cannot but sympathize with Friends in your parts, who, as you express,
I believe will not be without their trials; indeed,
it is likely that Friends in all places will be brought under deep sufferings,
and a great separation be made between the chaff and the wheat.

While the resolution of the people of Nantucket to maintain a non-resistant
and neutral attitude thus exposed them to sufferings from the Americans,
they were also frequently despoiled by marauding parties of the British,
and that class of Americans called "`refugees,`" who had joined them.
In 1778, seven armed vessels, and transports with troops, visited Nantucket,
and plundered the inhabitants of much property.
Shortly after their departure,
information was received that another formidable
expedition was being fitted out against them.
The town was convened to consult upon the measures to be taken in this emergency,
which resulted in the appointment of a committee, consisting of Dr. Benjamin Tucker,
Samuel Starbuck and William Rotch, to proceed to Newport, and from there, if necessary,
to New York, to represent their case to the commanders of the British forces,
whose headquarters were then in that city.
The feeling at Newport against the people of Nantucket was, at that time,
so strong that the deputation was, at first, not permitted to land,
and ordered to depart.
This, however, they declined to do,
preferring rather to suffer imprisonment and the loss of their vessel,
than to miss the opportunity of using their influence to stop the progress of the expedition.
They finally were allowed to go on shore,
and succeeded in obtaining an interview with several of the British officers.
In reference to this visit to general Prescott, then in command, William Rotch remarks,
in his autobiographical account:

I got on shore in the afternoon, and found that I must wait on general Prescott.
Knowing his brittle temper, and it being in the afternoon,
I almost dreaded to appear in his presence.
However, let my treatment be what it would, I desired this meeting over,
and accordingly went.
I was introduced by one of his aids.
He received me very cordially, and said: "`Mr. Rotch, will you have some dinner?
I can give you good bread, though the rebels say we have none.`"
I thanked him, saying we had dined.
"`Well,`" said he, "`will you have a glass of wine?`"
I answered: "`I have no objection, if you can put up with my plain way.`"
My glass was filled with his own and those of the officers at the table.
As a stranger introduced, they all drank to me before I put the glass to my lips.
I then observed: "`General, as I mentioned before, if you could put up with my plain way,
I was willing to take wine with you; but as we, as a Society, disuse these ceremonies,
and I have always found it best to keep to my profession,
let me be in what company I may,
therefore I hope my not making a like return will not be accepted as a mark of disrespect,
for I assure you it is not the case.`"
His answer was: "`Oh, no; if a Quaker will but be a Quaker, it is all I want of him; but,
he is no Quaker`" (naming one of our profession,
and I was sorry for the cause of this remark).

The interviews with general Prescott and others in authority at Newport,
resulted in obtaining permission for the committee to visit New York,
in order to lay before the commander-in-chief a statement of their condition,
with a promise that the proposed expedition to Nantucket
would be deferred until the result of this visit was known.
William Rotch and his companions then proceeded to New York,
and applied to commodore Collier, of the navy, and general Clinton, of the army;
the latter of whom intimated that he would direct
those in his department not to molest them.
William Rotch states:

In representing our case to sir George Collier,
he readily gave us an order forbidding any British
armed vessel to take anything out of our harbor.
This was a great relief.
I then laid before him the state of our captured seamen;
that all the exchanges of prisoners were partial;
that as "`we`" made no prisoners we had none to exchange,
consequently ours remained in prison-ships until they mostly died.
On his understanding the reasonableness of our request,
he ordered that all our men should be released who were not taken
in armed vessels (for such we had no right to apply),
and promised that it should not be so in future, so long as he held the command.

While thus exposed to robbery on land,
these islanders were also in danger of losing a great portion of
their property by privateers and other armed vessels at sea.
As the fishery was their chief resource,
it became necessary to solicit permits to protect
the vessels from capture by British cruisers.
Such permits, to the number of about fifteen, were granted by admiral Arbuthnot,
who had succeeded admiral Collier, upon the application of Timothy Folger, of Nantucket,
and the immunity thus granted proved very valuable.
The possession of such permits, however,
rendered the vessels carrying them liable to seizure by the Americans,
and great care was accordingly exercised to avoid them.

In 1780, Arbuthnot was succeeded by admiral Digby,
and a fresh application against the predatory visits of the British, became necessary.
A committee of three, of whom William Rotch was one,
was appointed to go to New York on this errand.
He was at this time recovering from severe illness, and wished to decline this journey,
but the others refused to go, unless he would accompany them.

This, +++[+++he says,]
brought a great strait upon my mind.
To go, I thought, I could not, and to omit it seemed almost inevitable destruction.
Atl ast I consented, under great apprehension that I should not live to return.
We accordingly set sail, and when we were off Rhode Island,
I was obliged to have them go to the east side of the island, and lie there several days,
for my pain was so great that I could not bear the motion of the vessel;
but we got safely to New York in a few days after it abated.

On making application for protection against three
British cruisers then in the harbor of Nantucket,
and some permits for the fishery,
they found that reports had been circulated to their disadvantage,
and the officer to whom they applied for assistance,
had been led to believe that they had betrayed the confidence placed in them,
by giving the permits to a greater number of vessels than was originally intended.
William Rotch, however, was able to satisfy him that this report was incorrect, stating

"`These permits were put into my hands; I delivered them, taking receipts for each,
to be returned to me at the end of the voyage,
and an obligation that no transfer should be made or copies given.
I received back all the permits, except two, before I left home, and should, probably,
have received those two on the day I sailed.
Now, if any duplicity has been practised, I am the person who is accountable,
and I am now here to take the punishment such duplicity demands.`"
He immediately became placid, and said: "`You deserve favor.
I am now going to the admiral.
You may go there in an hour.`"
We attended punctually.
He introduced us to the admiral, and informed him that his predecessor,
admiral Arbuthnot,
granted the people of Nantucket a few permits for the fishery last year, adding:
"`I can assure your excellency they have made no bad use of them.`"
Thus, after a storm came a pleasant calm.
We obtained an order, as heretofore, respecting property in our harbor,
and twenty-four permits for the fishery; and I returned home much improved in health.
It was necessary to conceal the documents from the American cruisers;
but such was the difficulty of distinguishing them,
that two were presented to American armed vessels,
who immediately took the vessels as prizes.

The difficulty they experienced from the Americans,
finally made it necessary to obtain permits from both the contending parties,
and in order to procure them from Congress, then sitting at Philadelphia,
William Rotch and Samuel Starbuck were sent to that city in the
winter of 1782-3. After several interviews with prominent members,
in which the value of the whale fishery to this country was urged,
and some of the prejudices which had been entertained
towards the people of Nantucket appeared to be removed,
a memorial representing their condition, was presented to that body.
This resulted in the grant of thirty-five permits for carrying on the fishery.
The privileges thus obtained were, however, no longer required.
News that a provisional treaty of peace with Great Britain had been signed,
was soon after received, and protection of this kind became unnecessary.

Some time after their return home from their visit to New York, about the year 1781,
the peaceful community in Nantucket was again threatened with a hostile invasion.
William Rotch says:

We were now brought into the most imminent danger, which no human effort could check,
much less prevent.
Nothing short of the interposition of Divine Providence preserved us from apparent ruin.
Several sloops of war and a number of transports, intended paying us a destructive visit.
They were in sight of us, in the daytime, three days, near Cape Poge (Martha`'s Vineyard).
They got under weigh three mornings successively,
and sailed for the island with a fair wind, which each morning came round against them,
and the tide, too, came round against them, which obliged them to +++[+++go to]
their anchorage, still in view of us.
Before they could make the fourth attempt,
orders came for their return to New York for some other expedition.
Thus we were mercifully preserved for that time,
after more fearful apprehensions than any we had before witnessed.
Messengers were arriving, one after another, and twice I was called up in the night,
with the disagreeable information that they were at hand.
A solemn time it was, indeed,
and can never be obliterated from my memory while life and reason are vouchsafed.

The following account of preservation from great
personal danger is given in his own words:

I was, with two men and two women Friends, captured in going to our Quarterly Meeting,
at Sandwich +++[+++Massachusetts], by a British privateer from New York.
They had just before taken a cedar boat and ordered us to depart in it immediately,
having first plundered us of what money we possessed,
but they took neither baggage nor provisions from us.
The vessel was mine, and I pleaded earnestly for her,
and sometimes nearly obtained a majority to give her to us;
but another can of grog would be stirred up by those
who would not consent to release her,
and this never failed to gain several on their side.

They repeatedly ordered us to begone, but we refused, still pleading for our vessel,
until the captain called to the prize-master to know why he did not send us away.
He replied: "`They will not go.`"
He then sent a furious fellow to drive us away.
Samuel Starbuck and I were standing together.
He approached us with an uplifted cutlass and a violent countenance, saying:
"`Begone into your boat, or I`'ll cut your heads off.`"
I looked him earnestly in the face, eye to eye, and, with a pretty stern accent, said:
"`I am not afraid of your cutting my head off.
We are prisoners; treat us as such, but do not talk of cutting our heads off.`"
He dropped his arm, and seemed struck at my boldness.
There were now two vessels coming rapidly in pursuit, and we thought it time to be off.
They soon retook our vessel, and pursued the privateer and took her,
but her men left her in their boats, and got on shore in the Vineyard.
Our vessel being taken, I recovered her by paying salvage,
as did a young man most of his money, who had two hundred dollars taken from him.

The preliminary treaty of peace between Great Britain and the United States,
was signed Eleventh Month 30th, 1782, and in the Ninth Month, 1783,
a definitive treaty was concluded,
which established the relations between the two countries.
The alteration in commercial affairs resulting from the separation from Great Britain,
proved destructive, for a time,
to the successful pursuit of the whale fishery at Nantucket;
and as this was then the chief occupation of its people, its prosperity declined,
and it became necessary for at least a portion of its inhabitants, to remove.
Samuel Starbuck and others, went to Nova Scotia,
where they were assisted by a grant of fifteen hundred pounds from the government,
in erecting buildings, etc., near Halifax, for the purpose of carrying on the fishery;
while William Rotch concluded to proceed to England,
in order to ascertain whether sufficient encouragement could
be obtained for the prosecution of the business from there.
He remarks:

The happy return of peace was now enjoyed in the United States, but poor Nantucket,
whose distresses did not end with the war, though rejoiced at the event,
still seemed doomed, for a time, to ruin.
Separated from Great Britain, the only market of consequence for sperm oil,
we were brought under the foreign tax of eighteen pounds sterling per ton,
a duty laid upon aliens to encourage British subjects.
Such we then were, and this duty had its full effect upon us.
Sperm oil was sold at Nantucket after the peace, for seventeen pounds sterling per ton,
which before we were separated, was worth thirty pounds sterling.
Twenty-five pounds was necessary to cover expenses,
and leave a very moderate profit to the owners.
Thus a loss of nearly eight pounds sterling per ton attended the business.
We continued for years at a certain loss,
in hopes that some favorable turn might take place, but no prospect appearing,
and the loss I had sustained by the Revolutionary war had so reduced my property,
that I found it necessary to seek some new expedient to prevent the loss of all.
I found no probable alternative, but to proceed to England,
and endeavor to pursue the fishery from there.
I accordingly took passage in my ship _Maria_, accompanied by my son Benjamin,
and sailed from Nantucket on the fourth of Seventh Month, 1785.
We had a fine passage of twenty-three days.

Our first journey was to the west of England,
in which we had the valuable company of my friend James Phillips.
We visited the coast from Southampton to Falmouth,
in search of a good place for the whale fishery,
if we should conclude to form our establishment in the island.
We found several ports suitable to the purpose, but none that we preferred to Falmouth.
In that large harbor, there are several smaller that would do well for the business.
I had very favorable offers of several places, but I was only on a discovery,
and did not wish to entangle myself.
After viewing the coast, and spending some days in Plymouth, we took a circuitous route,
and returned to London.

My next object was to know what encouragement we could obtain from the British Government.
My friend, Robert Barclay, perceiving what my business was, spoke to Harry Beaufoy,
a member of parliament, who introduced me to the Chancellor of the Exchequer,
the great William Pitt, then about twenty-seven years of age.
He received me politely and heard me patiently.
I laid before him our ruinous situation, saying: "`When the war commenced,
we declared against taking any part in it, and strenuously adhered to this determination,
thus placing ourselves as a neutral island.
Nevertheless, you have taken from us about two hundred sail of vessels,
valued at two hundred thousand pounds sterling, unjustly and illegally.
Had the war been founded on a general declaration against America,
we should have been included, but it was predicated on a rebellion; consequently,
none could have been included in it, but such as were in arms,
or those that were aiding such.
We have done neither.
As a proof of our being without the reach of your declaration;
you sent commissioners to restore peace to America, in which any province, county,
or town, that should make submission and receive pardon,
should be reinstated in its former situation.
As we had not offended, we had no submission to make or pardon to ask,
and certainly it is very hard if we do not stand
on better ground than those who have offended;
consequently, we remained a part of your dominions until separated by the peace.`"
This last sentence I pressed very closely, whenever I could with propriety introduce it,
knowing it was a material point.

After I had done he paused some time, and then answered: "`Undoubtedly you are right, sir.
Now, what can be done for you?`"
I told him,
that in the present situation of things the principal
part of our inhabitants must leave the island.
Some would go into the country.
"`A part,`" continued I, "`wish to continue the whale fishery,
wherever it can be pursued to advantage.
Therefore, my chief business is, to lay our distressed situation before this nation,
and to ascertain if the fishery is an object worth giving such encouragement to,
for a removal to England, as the subject deserves.`"
Thus our conversation ended, and I withdrew with my friend, Harry Beaufoy.

The negotiations with the English Government received little attention from that body,
and finally, William Rotch concluded to address the French Government,
who acceded to his proposals,
and granted him free enjoyment of their religion and freedom from all military requisitions.
This opened the way for the establishment of their fishery at Dunkirk.
It proved so profitable, that in 1793,
no less than forty ships sailed from Dunkirk to pursue
the whale fishery in distant quarters of the globe.

In 1791, William Rotch and his son, attended the National Assembly,
the governing body of the French nation,
to petition for certain privileges and exemptions.
These were that they might conform to their principle, that forbid them to take up arms;
that the register which Friends make,
should be sufficient to legalize their marriages and births,
and authenticate their deaths; and that they might be exempted from all oaths.

William Rotch remarks in reference to the presentation of the Address.
"`The object of our petition was of little consequence compared with the opportunity
we now had of somewhat spreading a knowledge of our principles;--above all,
that of the inward light or spirit of God in every
man as a primary rule of faith and practice.`"

We met with a number of serious persons who were in a great
measure convinced of the rectitude of our faith,
and they gathered about us at our hotel, one evening after another,
one inviting others to come,
until those social meetings in our apartments became exceedingly interesting.
The conversation almost wholly turned on religious subjects,
and they always appeared well satisfied with the hours thus spent.
It was then a turbulent time in Paris, and much more so afterwards.
Several of these valuable persons fell in the reign of terror,
and others are beyond my knowledge; but the remembrance of those evenings,
and the feeling of Divine influence that attended them, will, I believe, never pass away.

In the period of war which soon followed,
Friends at Dunkirk were several times exposed to great danger from their refusal
to illuminate their houses on account of victories gained by the French armies.
But on their informing the magistrates, that as they could take no part in war,
they could not join in rejoicing for victory, measures were taken for their protection.

The breaking out of war between England and France led to
the withdrawal of a part of this colony of Friends,
but meetings appear to have been kept up by those that remained at Dunkirk,
for several years.

=== Joesph Hoag on War and Fighting

+++[+++In the year 1812, while Joseph Hoag was travelling in Tennessee, he says:]

We stopped on our way at Knoxville, to take breakfast;
the Indians having made an invasion on the frontiers of the white inhabitants,
it was a time of great alarm while I was there.
Being taken into the room where the general was with his officers,
the sergeants made their returns to the general,
that they had warned every man that the law required to do military duty,
Quakers and all, and there had not one Quaker appeared on the ground.
In the meantime the general looked sharply at me, as I was walking the room, and said:
"`Well, we have lost a number of our frontier inhabitants, and some of our soldiers,
and a people who would not defend the frontier inhabitants
when the savages were destroying and scalping them,
could not be considered friends to their country, and should have no favor from him.`"
He then said: "`How do you like this doctrine, stranger?`"
I said: "`It is no doctrine for me; I have little or no opinion of it.`"
He asked: "`Why?`"
I said: "`The people with whom I commune, who are sound in their principles,
are all King`'s men, and are remarkably attached to their King,
and our King told Pontius Pilate that his kingdom was not of this world, for if it was,
then would his servants fight, that He should not be delivered to the Jews;
that his kingdom was not from hence, and that his kingdom was our kingdom;
that He had nothing to fight for in this world, neither have we;
and you warriors are fighting for riches, honor, and glory of this world,
and when you have got them, you cannot stay with them.
We choose to lay up our riches, and have our treasures where the rust cannot mar them,
nor thieves nor warriors get them from us.`"

The general sat down, but soon rose with these words:
"`I am not going to give up the argument so;
I see by the look in your eye that you are no coward; you are a soldier,
and if an Indian was to come into your house to kill your wife and children,
you would fight.`"
I answered: "`As for cowardice, I ever despised it,
but,`" pointing towards the guns standing in the house with bayonets on them, "`General,
it would take twelve such men as you are--and then you would
not do it--to make me take hold of a gun or pistol,
to take the life of a fellow creature,`" and looked him full in the face.
He said: "`I see you do not deny the sword.`"
I replied: "`No, I profess to be a swordsman,
that is the weapon I go into the field with--a spiritual sword
that never was beaten in the field nor foiled in battle.`"
He turned and sat down, but not long, and said: "`I will bring you to the point.
If an Indian was to come into your house with his knife and tomahawk,
and you knew he would kill you, your wife and children,
and you knew you could kill him and save all your lives, you would kill him;
if you did not you would be guilty of the death of the whole.`"
I thought it time to come to look for a close,
and proposed a standard to bring the argument to, that should decide it, but he declined.
I asked him if he professed to be a Christian, a Jew, or a Mahometan?
He remained silent awhile.
I then added, if he were a Jew, he was not prepared to fight;
his men were not circumcised, he had not burnt a sin offering, nor a peace offering.
He exclaimed: "`I profess to be a Christian, I am not a Jew or a Turk.`"
I asked him if he believed Jesus Christ was the author of the Christian dispensation.
He said: "`Yes.`"
I asked him if he believed Him sufficiently equal to the work as God himself,
as he received all the works of God to do.
He said: "`He did.`"
then told him I would keep him to the Christian platform or creed,
laid down by Jesus Christ;
and that he would not deny that a Christian was fit to live or die.
I then told him I would give the subject a fair statement, and he might judge.

I proceeded thus: "`I shall state, that myself and wife are true Christians,
and our children are in the minority,
and you know it is natural for children to believe what their parents teach them,
and therefore we are all true Christians as far as
our several capacities enabled us to be;
and now the question lies here;
which is most like the precepts and example of our King--the
author of the Christian religion--to lay down our lives,
and all go to heaven together; or kill that wicked Indian and send him to hell;
for he must be in as wicked a state as he can be,
to kill a family that would not hurt him.
General, it is a serious thing to send wicked folks to hell;
they have no chance to come back and mend their ways;
and you do not know but that if that wicked Indian was spared,
he might feel remorse enough to make him repent, so as to find forgiveness,
and go to heaven.
I really believe I should feel much better to see him come there,
than to send him to hell; and that is not all, general; when I killed that wicked Indian,
and sent him to hell, I imbrued my hands in human blood; before they were clean,
but now they are stained deep in the crimson gore;
can you make yourself believe that I stand as good a chance to get to heaven,
as to die when my hands were clean, and I innocent of human blood?

"`And besides, our King who was Lord of all,
had disciples and many women who looked up to Him for protection,
as much as a wife to a husband, or children to their father.
Did He, when the wicked Jews came out with staves to take Him,
cut off those wicked creatures, and send them to hell,
when He could have the command of twelve legions of angels?
He did not act without reason; He knew if He cut them off they would go to hell;
and He knew if He laid down his life, He was going to heaven;
and neither you nor I know but some of the poor creatures repented of their conduct,
and found forgiveness and are now in heaven, glorifying his name for sparing them.
Now general, was He guilty of suicide?
You will answer; He came into the world for this purpose;
I reply that we are brought into the world to obey his commands,
and to follow his example, and do likewise if called on; and general,
we find He had one soldier among his followers who drew
his sword and fought like a valiant for his Lord.
But what then said his Lord?--did He say, you are a good fellow,
I will promote you for this?--or, did He not say, put up your sword into its sheath,
for they that use the sword shall perish with the sword.
General, you will do well to remember that saying; it is the word of a King.`"

The general made no answer, but sat and hung his head for some time,
one of the company at length replied: "`Well stranger, if all the world was of your mind,
I would turn and follow after.`"
I replied: "`So then you have a mind to be the last man in the world to be good;
I have a mind to be one of the first, and set the rest the example.`"
This made the general smile.
He got up and went out at the door,
and ordered his officers to let me go where I pleased, and not to interfere;
then turned and came in.
I was then walking the floor, and after a little discourse, the general said:
"`Well stranger, there are a great many of your sort of people in this State.`"
I answered: "`Yes, and I hope you find them an honest, industrious, peaceable people;
good inhabitants to populate and clear up a new country, and make it valuable.`"
He said: "`Yes, they are an industrious, harmless people.`"
We were both on our feet; I turned, and looked him full in the face,
and spoke with some emphasis: "`General, can you say that an honest, industrious people,
who will harm nobody, are enemies to their country?`"
He paused awhile, and said: "`No, and they shall have my protection,
and you have the word of a general for it.`"
I then felt easy that all was done that could be done.
I had the same man`'s word who had said:
"`No favor should be shown the Quakers,`" now pledge his honor to protect them.

[.asterism]
'''

In a short sketch of the life of John Bringhurst, of Philadelphia,
who deceased in the year 1750, there is embraced a copy of a testimony of disownment,
prepared by a committee of which he was a member,
issued against a Friend who had joined in fitting out a vessel of war.
It is an interesting illustration of the care observed by Friends of that
day to preserve the members in consistency with their profession:

Whereas, +++_______+++, of this city, merchant, has many years made profession among us,
the people called Quakers, and by his conduct,
for some time after his residence in this city,
gave us cause to hope that he had received the principles
of Truth in true love and sincerity,
and would, by obedience thereto,
be induced to maintain the Christian testimony we esteem it our duty to bear
against the many corruptions which prevailed among the professors of Christianity
during the apostasy from the primitive purity of the church of Christ.
But with concern we have observed in him a gradual declension from the humility
and circumspection incumbent on every member of our religious Society;
and that, as he has attained to worldly honors and preferments,
his regard to the unity of his friends has decreased, so that he has,
on several occasions, given us cause to treat with him;
which we have done in brotherly love,
but without the satisfaction of finding our care and regard had the desired
effect of bringing him to a nearer union and fellowship with us.
He has lately so far deviated from our known principles and discipline,
as to join with others in a contribution to the fitting out a ship of war.
For this he has been dealt with by several Friends,
who were concerned to show him the inconsistency
of his conduct with the profession he makes,
and to advise him to an acknowledgment of his error.
But, both by word and writing, persisting in a vindication of his conduct, and having,
by other instances,
manifested a determination to contradict this part of our Christian testimony,
we think it our duty,
to prevent others under our religious profession from being misled by his example,
and lest any should think we approve his conduct, to declare that we disown him,
the said +++_______+++, to be a member of our religious Society,
until he becomes sensible of his errors, and, being willing to acknowledge them,
is desirous of being restored to the unity of his friends.

=== Hugh Davids--Soldier and Quaker

At the period of the American Revolution,
Hugh Davids was a member of Philadelphia Monthly
Meeting of Friends for the Northern District.
He favored the royalist cause, and when the British occupied Philadelphia,
manifested a disposition to enter the military service on that side.
Against this he was repeatedly cautioned and warned by Friends,
but he finally accepted a commission in the British army,
and when the king`'s troops evacuated the city, in 1778, he went with them.
For his deviation from our religious and well-known peaceable principles,
he was disowned on the thirtieth of the Sixth Month of that year.

Thirteen years afterwards, Hugh Davids attended the Monthly Meeting,
and offered a paper condemning his course in joining in arms with
one of the contending parties in the then late war,
and expressing his great concern and anxiety for what he had done.
His offering was received with much love and tenderness by Friends,
and a committee was appointed to visit him.

The following month the committee reported that the
case was one of more than usual weight,
and that they believed his offering proceeded from a just sense of his deviations,
and a sincere desire for future preservation in the
strait and narrow way which leads to peace.
The meeting fully united in accepting the acknowledgment,
and records that it was not doubted that,
as he was preserved in steady attention to the manifestation of the Divine will,
his peace would be increased.

It also appears that he had filed with the king`'s counsel
a document by which he surrendered his commission and pay.
This paper was as follows:

I, Hugh Davids, the subscriber,
having for some years past held a commission as cornet
of horse under the king of Great Britain,
and being now favored, through the Lord`'s mercy,
to see the inconsistency of war with the Christian religion,
have believed it to be required of me, as a religious duty,
to give up and surrender the commission I received of the king unto him again;
and also all the arrearages of my pay which may remain
due to me at the war office in London;
and likewise some money which I have heretofore received on account of my pay,
which I now have in hand, finding I cannot make use of it with peace in my own mind.
I do, therefore, by these presents, after due consideration, voluntarily,
and from conscientious motives,
freely give up and surrender to the king of Great Britain all my
right and interest in the said commission above mentioned,
and likewise all my claim or right in the arrearages
of wages which may appear due to me thereon.
And I have also paid into the hands of Phineas Bond, the king`'s consul in this city,
one hundred and sixty-five Spanish dollars,
which I heretofore received on account of my pay,
to be remitted to the proper office from which I received it.
I may further certify that I have not acted in this
matter from political or disrespectful motives,
but from those of a religious and conscientious nature only.

[.asterism]
'''

The following extracts from the diary of John Pemberton,
one of the Friends who was arbitrarily sent into exile in Virginia, are interesting,
as showing the Christian spirit which animated the sufferers:

On the Second-day of Ninth Month, 1777, about two o`'clock p.m.,
three persons came to my house,
and informed me they had orders from the Supreme Executive Council to take me as a prisoner.
I inquired, for what?--and demanded their authority.
One of them pulled a packet out of his pocket, and read a few lines of a long writing,
the amount of which was, that I was suspected of being inimical to the cause of America.
I pleaded with them for a considerable time,
on the injustice and oppression of imprisoning a man,
unless some crime was alleged against him.
They replied, they had orders, and must obey them.
I represented that I was an innocent man, and had not done anything I was ashamed of,
or to the injury of America.
They pretended that it was very disagreeable to them to execute such orders;
whereupon my dear wife told them, that Pilate washed his hands and said he was clear;
yet he was not so in the Divine sight.
Many serious remarks were made, but without effect,
though there appeared some tenderness in one of them.
Another said I should have a hearing when I came to the lodge,
where they had orders to take me.

They presented to me a paper, called a parole, and urged me to sign it,
to make my own house my prison, and be ready at the call of the council;
not to correspond with the enemy, as it was expressed; nor to do any act or thing,
by word or writing, prejudicial to the cause of America.
Knowing my innocence,
and that my religious principles would restrain me
from doing anything to promote the shedding of blood,
or to injure my country, I told them I could not sign such a paper,
as it would imply guilt, which I was free from.
They still urged my going with them; but I told them,
that as they had nothing justly to lay to my charge, and as my house was my own,
and I was a free man, I could not consent to comply with their unreasonable demand,
and could not leave my house without being forced.

When they saw I was resolute,
endeavors were used to prevail on my wife to urge my going quietly with them;
but she was staunch and upright.
One of them then went and brought a guard of about ten men,
whom they had left in the street; and again urged my going with them.
But I still maintained my right as a free man and a Christian.
He then took me by the arm, and said he would force me to go;
but I would not move from my seat.
The men he had brought into the house seemed averse to meddling with me;
but this man insisted that they should do their duty;
so I was lifted by two of them off my seat and led to the door.
My wife insisted on going with me; so my friend John Parrish, taking her by one arm,
and myself by the other, we supported her;
and with these soldiers we were conducted to the mason`'s lodge.
Though I believe she had not walked so far, at once, for two years, and was very poorly,
yet she was sustained, both in mind and body.

The people seemed generally serious, and many affected,
when we came to the lodge and were conducted up stairs.
Before we were put into a room, the person who brought the guard into my house,
demanded the keys of my desk.
I told him I thought he had no right to make such a demand, and I would give him none.
He then asked my wife, and she also denied him.
He then said he would break the desk open; and so returned to my house,
guarded by the same men; they broke open my desk,
and took out the rough minutes of the Meeting for
Sufferings for seven or eight months past;
and in other places which they searched, they found some other meeting papers,
and two bundles of manumissions for the freedom of slaves, which they took away.
But in all their searching, they could not find anything to their purpose;
and though they condemned Friends for publishing epistles,
especially the last Christian exhortation from the Meeting for Sufferings,
yet they now republished it themselves, at a time more critical than any heretofore.

On my coming to the lodge, I met there my brother James, and various other Friends.
We were favored with support in our persecution;
though that evening and night was to me a season of trial of spirit,
and I had little sleep.
Yet in the morning my heart was tendered,
and from that time to the time when we were removed from the city,
I was preserved in a steady resigned state of mind.

Fifth-day, 4th.--Brother Israel, John Hunt and Samuel Pleasants,
were brought as prisoners, so that our number was twenty-three.
Previous to brother Israel`'s coming,
he and John Hunt and Samuel Pleasants had presented a remonstrance to the council,
and demanded a hearing as their right, but they were not admitted,
and informed that they could have no hearing,
and so were conveyed to the place of confinement.
Afterward we also prepared and sent remonstrances to the council and Congress,
but could not obtain a hearing.

First-day, 7th.--Having had much company for several days past,
the inhabitants being affected with the unjust conduct pursued towards us,
we requested that we might be more retired;
and had a favored opportunity in humbly waiting upon Almighty God,
so that the hearts of many were tendered,
especially in time of solemn prayer and supplication,
for the support and preservation of ourselves and our families.

On Third-day, we sent for some of the persons who were instrumental in our being taken,
and demanded of them whose prisoners we were?
One of them said that none of us were his prisoners;
and the other did not own any except my brother Israel, John Hunt,
Samuel Pleasants and Phineas Bond.
In the afternoon an order from council appeared, for our removal to Staunton,
in Virginia; upon which we wrote another remonstrance against their proceedings.
Next day we were permitted to go home to prepare for our journey,
and on the following morning I had a solid opportunity in quiet retirement with my family,
and parted with my beloved wife in tender affection.
We were supported in this close trial beyond expectation,
the saying of the apostle being verified in my mind,
"`None of these things moved me;`" being enabled to resign
my life and my all to the disposal of Divine Providence.
About eight o`'clock I returned to my prison and continued until afternoon,
when two men came and informed us they were appointed to conduct us to Reading.
We demanded a sight of their orders, which they refused.
At length, after much altercation, one of them read a paper,
but another paper containing further orders, he absolutely refused to read,
or to give us a copy of it.
We entered a protest, and called in several inhabitants to witness it:
they were also informed that messengers were dispatched to the chief justice,
for writs of _habeas corpus_; but they paid no regard to that.
The wagons, etc., being before our prison, we were at length forced out.
Many hundreds of people were ranged along the alley, some of them much affected;
and many poor blacks, as well as others, after I was in the wagon, shook me by the hand,
being affected with our hard treatment.

=== How Friends in France Became Known to Their English Brethren

Joseph Fox, of Falmouth,
(the first who became a surgeon) had a share in two cutters with other owners, who,
outvoting his objection, at the commencement of hostilities with France in 1778,
armed these vessels as letters of marque in order to capture French merchantmen.
The enterprise (adds Burke in his [.book-title]#History of the Commoners#) was successful,
and some valuable ships were taken.
His partners then endeavored to keep him from his share in the profits;
but he insisted upon it and lodged the amounts in the British funds,
keeping the circumstance an entire secret even from his family,
and in fact dealing with the treasure like one who felt it was not his own.
His object was to restore it as soon as possible to those whom he considered to be,
and who really were, the rightful owners.

In 1783, on the restoration of peace, the opportunity occurred,
and he then commissioned his son, Dr. E. L. Fox (afterwards of Brislington),
to proceed to Paris, where he first communicated the matter to him by letter.
Much difficulty and delay intervened, trying faith and principle,
and giving a good excuse had he desired one, to abandon the attempt as hopeless.
While it was yet in progress, Joseph Fox died.
But his son had received the duty as a solemn trust and charge
which he was not to quit until the restitution was made.
He had a notice printed in the _Gazette de France_ of Second Month, 1785,
in consequence whereof applications were quickly made which led
to about fourteen hundred and seventy pounds being restored.
The sufferers thus reimbursed, made an acknowledgment in the Eighth Month _Gazette_,
which need not be quoted.
A small sum still remained in Dr. Fox`'s hands which he could not assign,
especially as the Revolutionary war broke out.
In 1818, when it had reached six hundred pounds, he could venture abroad once more,
and going again to Paris enquired how he could best appropriate it,
and ultimately placed it in the treasury of the "`Invalid Seamen of France`"
for the relief of the non-combatants of the merchant service.
The advertisement above noticed drew forth an address from a body of Protestants
whom we have since been glad to own in fellowship and belief,
for they were rejoiced to learn that anyone was in existence
who like them testified against iniquity and war;
and thus they came to the knowledge of the Society.
