== Chapter XIV. Divine Protection

In an account of the experiences of their family in the Irish Rebellion of 1798,
written by Dinah Goff, a member of the Society of Friends, she says:

[.embedded-content-document.letter]
--

It was about the middle of the Fifth Month, 1798, that the county of Wexford, in Ireland,
became a scene of open rebellion, headed by B+++_______+++ H+++_______+++, a Protestant,
and two Roman Catholic priests, John Murphy and Philip Roche.
The aims of the insurgents were various; some were more cruelly disposed than others;
all determined to liberate themselves by force of arms from the unequal yoke,
as they believed it, of the British government, and to become a free people;
some to bring all Ireland to Catholicism, etc.

About ten days before the rebellion broke out, a Roman Catholic, who resided near,
called on my father, and desired to speak to him in private,
He then informed him that the county would, in the course of a few days,
be in a state of general insurrection.
My father replied that he could not credit it, for he had frequently heard such rumors.
The person assured him that he knew certainly it would be so,
and that he had procured a vessel, now lying at Duncannon,
to convey himself and family to Wales, and that as a friend,
he gladly offered accommodation to our household.
My father thanked him for this act of friendship,
but said that it felt to him a matter of great importance
to remove from the position allotted him by Providence,
yet that he would consider of it, and consult his wife.
After having endeavored to seek best wisdom,
my dear parents concluded that it was right for them to remain at home,
placing their dependence and confidence in Him who alone can protect,
and who has promised to preserve those that put their trust in Him.

The estate and spacious mansion, called Horetown, occupied by my parents,
Jacob and Elizabeth Goff, and the family,
were situated about ten miles from each of the towns of Wexford and New Ross.
The rebels formed two camps, at Carrickburn and Corbett Hill,
one on each side of the house, at distances of two and five miles from it.
This central position caused a constant demand on us for provisions,
with which the insurgents were daily supplied,
and they often said that they spared the lives of the family for that purpose.

A day or two after the commencement of the rebellion, two carts were brought to our door,
and the cellars emptied of all the salt provisions, beer, cider, etc.,
which were taken off to the camp.
Fourteen beautiful horses were turned out of my father`'s stables,
and mounted in the yard by two or more of the rebels on each.
Some, which had not been trained, resisted by plunging;
but their riders soon subdued them, running their pikes into them,
and otherwise using great cruelty.
Much of our cattle they also took off,
and orders were sent each week from the camp at Carrickburn,
to have a cow and some sheep killed, which were sent for at stated times.

A party, who assumed the rank of officers in the rebel army, came to our house one day,
and directed to have dinner prepared immediately.
On my mother`'s requesting the servant to lay the tables in the hall,
they indignantly asked: "`Is it there you are going to give us our dinner?
Show us into the best parlor in the house.`"
But on my mother assuring them that she had seen noblemen sitting in that hall,
they became calm and satisfied.
They then asked for spirits and wine, saying they would have some;
and when my mother told them that there were none in the house,
they were greatly irritated, still saying they must have some.
On being spoken to by my mother in the singular number,
they desired her not to say "`thee`" and "`thou`" to them,
as if she were speaking to a dog; and on her again saying "`thou`" to one of them,
he flourished his sword over her head, and said, haughtily:
"`No more of your '`theeing`' and '`thouing`' to me.`"
They ate their dinner, however, and went off peaceably.

We were now informed that orders had been given to take my dear father`'s life,
and my mother was most particular in keeping us all close together around him,
saying that if it were permitted that our lives should be taken,
we might be enabled to support and encourage each other, or else all go together.

One day, about noon, a large company appeared on the lawn, carrying a black flag,
which we well knew to be the signal for death.
My dear father advanced to meet them as usual, with his open, benevolent countenance,
and my mother, turning to me, said, with her sweet, placid smile:
"`Perhaps my stiff stays may prevent my dying easily.`"
On which the Roman Catholic who had taken refuge with us, said: "`Have faith in God,
madam; I hope they will not hurt you.`"
She quickly pushed forward and joined my dear father, who was surrounded by a large party.
He observed to them, he feared they might injure each other,
as their muskets were prepared for firing; when one of them replied:
"`Let those who are afraid keep out of the way.`"
My mother distinctly heard one of them say:
"`Why don`'t you begin?`"--and each seemed looking
to the other to commence the work of death.
Some of them presently muttered: "`We cannot.`"
At this critical moment, some women came in great agitation through the crowd,
clinging to their husbands, and dragging them away.
Thus a higher Power evidently appeared to frustrate the intentions of the murderers,
and my beloved father was again graciously delivered.
One man said there was "`No use in taking Mr. Goff`'s life,`" but his two sons, if there,
should soon be killed, and then the estate would be theirs.

One morning a most outrageous party advanced towards the house,
yelling and roaring like savages, evidently with some wicked design;
but two young men who looked serious again interposed in our behalf,
and would not allow them to enter.
Thus were the words of David fulfilled: "`The wrath of man shall praise you;
the remainder of wrath you will restrain.`"

A young man who, with his mother, kept a neighboring public-house,
used at that time often to walk into our drawing-room, lay his sword on the table,
and amuse me and my young cousin by giving us his finely-decorated hat to admire.
One afternoon he tried to prevail on us two to go with him to the camp,
saying it was an interesting sight,
such as we might never have an opportunity again to see.
We were then sixteen and fourteen years of age,
and on my saying I did not think my mother would permit us to go,
he desired us not to tell her, and promised to bring us safely back.
My mother, ever watchful, was at this moment crossing the hall, and seeing us together,
she came forward and inquired what he was saying.
When we told her,
she asked him how he dared to request the children to go to such a place?
She then reasoned with us on the impropriety of listening to such invitations,
saying she should never have expected to see us again if we had once gone.

Three or four hundred English troops, accompanied by Hompesch`'s German hussars,
at length landed at Duncannon Fort.
This was announced by the firing of cannon early in the morning,
On my mother`'s entering my room, I expressed much pleasure at the intelligence,
when she replied: "`My dear, we must rejoice with trembling,
having much to dread from their being strangers, and we know not what may be permitted.
We have only to place our trust and confidence in Him who has hitherto preserved us!`"
// lint-disable invalid-characters
This little army formed an encampment on my late uncle Cæsar Sutton`'s lawn at Longgrague,
about two miles from us.
The next day, while we were sitting at dinner,
one of the servants said the rebel forces were coming from Wexford in thousands,
intending to surround the English encampment.
The royal troops, commanded by general Moore, having had previous information, were,
however, on the alert, and met them on the road, near our house.
We counted twenty-four pieces of cannon, belonging to the rebels,
which passed our entrance.
A dreadful scene, partly in our view, was now enacted, and lasted for three hours.
The firing was awful!
Having closed the doors and windows in the lower part of the house as much as possible,
we all retired to an upper room, and there remained in a state of fearful suspense.
It was a terrible sight, and deeply affected us,
the cannon-balls falling thickly about the house.
On one of my sisters raising the window to look out, a ball whizzed by her head,
and this, with many others, we afterwards found.
At length, seeing the poor, deluded people running in all directions,
we learned that they were routed.

Two soon came to the house to have their wounds dressed,
which my sister Arabella did as well as she could; one had a ball in the cap of his knee,
and both bled profusely; they expressed much thankfulness,
and hoped they might soon be able again to fight for their freedom.
A fine young man coming, who had received a severe wound in his side and shoulder,
my dear mother used means to relieve him, and dressed him comfortably in clean linen,
while he frequently exclaimed: "`Do, ma`'am, try to stop the blood.
I don`'t mind the pain, so that I may but fight for my liberty.`"
Observing him in danger from the great injury, she spoke to him in a very serious strain,
and also recommended his going to the Wexford Infirmary.
We heard afterwards that he died on the way, a few hours after he left us.
This battle was at Goff`'s Bridge, on the twentieth of Sixth Month.
Several hundreds of the insurgents were killed, but not many of the military.

Soon after the firing had ceased,
we observed two of the cavalry moving slowly and suspiciously up our avenue;
on which my father went down to the hall door,
and advanced with a smiling countenance and extended arms to meet them.
One, who was a German, at once embraced him, saying, in broken English:
"`You be Friend--no enemy, no enemy;`" and gave him the kiss of peace, adding:
"`We have Friends in Germany.`"
We got them eggs, milk, bread, etc., to refresh them,
after the excessive fatigue and excitement which it was obvious they had suffered.

The evening before this engagement, one of my sisters,
passing through the servants`' hall, observed the coachman leaning on his arm,
apparently much distressed.
When she requested to know the cause, he hesitated and said he could not tell her;
but on her entreating him, and adding that she should like to know the worst,
he said that he had heard it planned at the camp that, if they conquered the royalists,
we were all to be murdered, and the generals were to take possession of our house.
He then added, weeping: "`Oh, our plans are too wicked for the Lord to prosper them!`"
My sister remarked that we trusted in a Power stronger than man,
and able to protect us in the midst of danger; or to that effect.

During the night following this battle, our house was surrounded by Hompesch`'s cavalry,
who slept on the lawn, wrapped up in their grey coats.
The next morning twenty or thirty of the officers breakfasted with us,
and told us that we had had a marvellous escape on the previous day,
the cannon having been placed on the bridge,
and pointed against the house to batter it down; even the match was lighted,
when a gentleman who knew my father and us,
came forward and told them the house was "`inhabited by a loyal Quaker and his family.`"
They had previously supposed it must be a rendezvous of rebels, and feared,
from its commanding position, that they themselves might have been fired upon from it.
Some of the officers, being refreshed by their meal,
even shed tears when they reflected on the danger we had been in.

My cousins, Richard and Ann Goff, of Hopefield, near Horetown,
had been observed by "`the United Men`" to persevere in walking
to Forrest meeting while the country was in a state of rebellion,
and were apprised that, if they continued this practice,
and refused to unite in the Roman Catholic forms of worship, they should be put to death,
and their house burned.
This threat brought them under deep mental exercise,
accompanied with fervent prayers that they might be enabled to come to a right decision;
and collecting their large family together,
in humble confidence that best direction might be mercifully afforded,
after a season of solemn retirement, they laid the matter before their children.
On this memorable occasion, the noble and intrepid language of Fade Goff,
their eldest son, then about seventeen years of age, is worthy of being recorded.
"`Father,`" said he, "`rejoice that we are found worthy to suffer.`"
His parents were deeply affected, and their minds became so much strengthened that,
next morning, rising before daybreak, they all proceeded to the meeting,
and were enabled to continue to attend Divine worship without molestation,
expressing thankfulness in thus being permitted to
accomplish what they considered their religious duty.

David Sands and his companion attended that meeting, and returning to Horetown,
were joyfully received by us,
my dear mother saying that his visit reminded her of the
good Samaritan pouring oil into our wounded minds.
The three families now occupying our house all assembled with him on this solemn occasion,
and his communication was truly impressive and consoling,
inducing tenderness in all present.
He first alluded to the deep trials we had suffered;
then to the infinite mercy which had brought the family through them;
and afterwards offered a solemn tribute of thanksgiving
and praise to the great Preserver of men,
whose power had been so remarkably displayed for our protection,
when surrounded by danger on every hand.
It was indeed a memorable visit,
for which thankfulness prevailed to Him from whom all consolation is derived.
The Roman Catholic family had never before heard these plain truths so declared,
nor witnessed anything of the kind; but they all united in prayer on their knees,
and the mother said: "`I never heard such a minister as that gentleman;
he must be an angel from heaven sent to you!`"

--

During the dreadful scenes that were enacted in Ireland during the rebellion of 1798,
the members of the Society of Friends, who refused military protection,
and relied on the protecting care of the Almighty,
were remarkably preserved amid surrounding dangers,
and had their lives given to them for a prey.
After the main strength of the rebels was broken, many of their number,
who were outlawed, found places of concealment in woods and caves,
and issued forth by night to plunder those within their reach.
Dinah Goff describes two such visits paid to her father`'s house,
who had been urged to accept the nightly services of a guard, but had positively refused.
She says:

[.embedded-content-document]
--

On the first night, having all retired to rest,
we were aroused by the terrific knocking with muskets at the hall door.
My dear father raised his chamber window, and requested them to wait a few minutes,
and he would open the door; but they continued knocking still louder,
and swearing most awfully until he went down.
On his opening the door, they seized him, and instantly rushed up to his room,
breaking a mahogany desk and book-case to pieces with their muskets, and demanding money.
My father handed them twenty guineas, which was all he had in the house;
but they persisted in asking for more, and swore, in a most profane manner,
that if he did not give them more they would take his life.
I slept with a little niece, in a room inside his,
and we were entreated by my sister A+++_______+++ not to rise, as we should be of no use.
I endeavored to comply with her request, and remain quiet,
till I heard a dreadful scuffle, and my father`'s voice, exclaiming:
"`Don`'t murder me!`"
I could then no longer keep still, but opened the door, and saw one of the men,
dressed in scarlet regimentals, with full uniform, epaulettes, etc.,
rushing towards my father with a drawn sword in his hand.
My sister intercepted it by throwing her arms round my father`'s neck,
when the point of the sword touched her side, but not so as to injure her.
In the struggle the candle went out, and they called most violently for light.

The horror which I felt at this awful moment can scarcely be expressed.
My sister went down towards the kitchen,
and found a man standing at the foot of the first flight of stairs;
she asked him to light the candle, when he said she might go down,
and he would stand guard and not allow anyone to pass.
This he performed faithfully, and she returned in safety.
I could not, after this, leave the party, but followed them through the house.
The dreadful language they used, some of which was addressed to my sisters,
impresses me with horror to this day.
Money seemed the sole object of their visit that night, as they repeatedly said:
"`Give me more money, I tell you;`" assuring my father that,
if he did not give them more, they would murder him.
They even said, from minute to minute, while they held a pistol to his forehead:
"`Now you`'re just gone.`"
They then forced him to kneel down, repeating the same words, and presenting the pistol.
Seeing his situation, I threw myself on my knees on the floor,
and clung with my arms round him, when the ruffians pushed me away, saying:
"`You`'ll be killed if you stop there.`"
But my father drew me towards him more closely, saying:
"`She would rather be hurt if I am.`"
They snapped the pistol several times, which, perhaps, was not charged,
as it did not go off.
When they found there was no more money they desisted, asking for watches,
which were given them, and at length they went away,
after eating and drinking all they could obtain,
and charging my father to have more money for them the next time,
or they declared they would have his life.
So saying, one of them, who appeared in a great rage,
and had a cavalry sword in his hand, cut at the hand-rail of the hall stairs,
the mark of which still remains.

About a fortnight afterwards, before the family withdrew to rest,
my father had a presentiment that the robbers might come again that night,
and sat up later than usual.
About midnight they arrived, knocking furiously, as before,
and fully prepared to plunder the house.
They soon emptied the drawers,
and took all the wearing apparel they could get that did not betray the costume of Friends,
so that we were deprived of nearly all our clothes.
On perceiving that they were taking all,
my mother begged one shirt and one pair of stockings for my father,
which they threw at her face in the rudest manner, using dreadful language.
They behaved most violently; and, spreading quilts and sheets on the floor,
filled them with all sorts of clothing they could get;
they then called for a meal to eat and drink, desiring my sister to drink their health;
putting the cup of small beer to her lips,
and bidding her "`Wish long life and success to the
babes of the wood,`" as they called themselves.
This she steadfastly refused.
They then declared they would come again in two weeks,
and take us all to live with them in the wood,
"`and to cut bread and butter for the babes.`"
Their behavior was so insulting,
and my dear parents were so fearful of these threats being realized,
that they determined on sending us young females to my cousins, Goff and Neville,
who were then merchants in Ross; and there we remained for some weeks,
until tranquillity was restored to the county.

After the robbers had finished their repast, they threatened to take my father`'s life,
behaving very outrageously, and saying they must take him to their main guard,
at a little distance, and murder him there,
as they did not like to do it in his own house.
They then led him out, and we all attempted to follow; but they pushed my mother back,
saying that she should not come--it would be too
painful a sight for her to see her husband murdered,
which they certainly would do.
It was very dark; but my sister Arabella positively refused to leave her father,
and they allowed her to accompany him.
While crossing the lawn,
the root of a beech tree projecting above the path caused him to stumble;
he then sat down and said, if they were determined to take his life,
they might as well do it there.
My dear sister stood by in a state of awful suspense.
They rudely asked him if he had anything to say, telling him his time was come.
On hearing this, he remained quite silent, and they, not understanding it,
hurried him to speak; when he said he prayed that the Almighty might be merciful to him,
and be pleased to forgive him his trespasses and sins, and also to forgive them,
as he did sincerely.
They said that was a good wish, and inquired if he had anything more to say.
He requested them to be tender towards his wife and children; on which they said:
"`Good-night, Mr. Goff;
we only wanted to rattle the mocuses out of you`"--meaning guineas.

When they took my father forcibly out of the house, my mother, though much distressed,
was favored with her usual quietude and composure of mind, trusting in the Lord,
who had been pleased to support her through many deep trials, and then forsook her not.
So strong was her confidence,
that she even called to the servant for some warm water to prepare
a little negus for my dear father in preparation for his return;
when I said: "`It is not likely we shall ever see my father again alive,
for they are going to murder him;`" on which she replied, with firmness:
"`I have faith to believe they will never be permitted to take his life.`"
In about a quarter of an hour my valued and tender parent returned, pale and exhausted;
and, throwing himself on the sofa, said: "`This work will finish me;
I cannot hold out much longer;`" which proved to be the case.

--

Remarkable also was the protecting care vouchsafed
to my uncle Joshua Wilson (my mother`'s brother),
whose residence at Mount Prospect, near Rathangan,
was forcibly entered by a party of rebels.
One night, after the family had retired to rest,
they were aroused by a tremendous volley of musketry,
which at once shattered the hall door; and a loud cry was raised of "`Arms, money,
or life!`"--with most awful swearing.
My uncle went hastily down in his dressing-gown, followed by his wife,
who heard them exclaim:
"`You are a dead man;`" and seeing one of the men present a pistol at my uncle`'s head,
she rushed between him and the ruffian, exclaiming: "`You shall not, and dare not,
take my husband`'s life, or touch him;
for the arm of the Almighty is stronger than you are.`"
The man appeared confounded, and let the pistol drop from his powerless hand;
it was very remarkable that the whole party left the house soon after,
without doing any further injury.

When George Dillwyn was in England, he related an interesting incident,
illustrating the safety of depending on the Lord for protection.

It occurred in one of the back settlements,
when the Indians had been employed to burn the dwellings of the settlers,
and cruelly to murder the people.

[.embedded-content-document]
--

One of those solitary habitations was in the possession of a Friend`'s family.
They lived in such secure simplicity,
that they had hitherto had no apprehension of danger,
and used neither bar nor bolt to their door,
having no other means of securing their dwelling from intruders than by drawing
in the leather thong by which the wooden latch inside was lifted from without.
The Indians had committed frightful ravages all around,
burning and murdering without mercy.
Every evening brought forth tidings of horror,
and every night the unhappy settlers surrounded themselves
with such defences as they could muster--even then,
for dread, scarcely being able to sleep.
The Friend and his family who had hitherto put no trust in the arm of flesh,
but had left all in the keeping of God,
believing that man often ran in his own strength to his own injury,
had used so little precaution, that they slept without even withdrawing the string,
and were as yet uninjured.
Alarmed however, at length by the fears of others,
and by the dreadful rumors that surrounded them,
they yielded to their fears on one particular night,
and before retiring to rest drew in the string,
and thus secured themselves as well as they were able.
In the dead of the night, the Friend who had not been able to sleep,
asked his wife if she slept, and she replied that she could not, for her mind was uneasy.
Upon this he confessed that the same was his case,
and that he believed that it would be the safest for him
to rise and put out the string of the latch as usual.

On her approving of this, it was done, and the two lay down again,
commending themselves to the keeping of God.
This had not occurred above ten minutes,
when the dismal sound of the war-whoop echoed through the forest,
filling every heart with dread, and almost immediately afterward,
they counted the footsteps of seven men pass the window of their chamber,
which was on the ground floor, and the next moment the door string was pulled,
the latch lifted, and the door opened.
A debate of a few minutes took place, the purport of which,
as it was spoken in the Indian language, was unintelligible to the inhabitants;
but that it was favorable to them, was proved by the door being again closed,
and the Indians retiring without having crossed the threshold.
The next morning they saw the smoke rising from burning habitations all around them;
parents were weeping for their children who were carried off,
and children lamenting over their parents who had been cruelly slain.

Some years afterward, when peace was restored,
and the colonists had occasion to hold conferences with the Indians,
this Friend was appointed as one for that purpose, and speaking in favor of the Indians,
he related the above incident; in reply to which, an Indian observed,
that by the simple circumstance of putting out the latch string,
which proved confidence rather than fear,
their lives and their property had been saved--for
he himself was one of that marauding party,
and that on finding the door open, it was said: "`These people shall live.
They will do us no harm, for they put their trust in the Great Spirit.`"
During the whole American revolution, indeed, the Indians,
though incited by the whites to kill and scalp the enemy, never molested the Friends,
as the people of Father Onas, or William Penn,
and as the avowed opponents of all violence.

--

During the war between the Northern and Southern States, from 1861 to 1865,
many of the members of the Society of Friends were exposed to much
suffering on account of their testimony against war;
one, who resided in Ohio,
relates the following experiences of being drafted
for military service in the United States army:

[.embedded-content-document]
--

In the year 1864 I was drafted, according to the laws of the land, and one day,
while pleasantly enjoying the company of some intimate friends at my house,
also surrounded by my own dear family, a stranger abruptly entered,
inquiring if I lived here.
I replied.
Then he, without further ceremony,
drew from his pocket an order from the provost marshal of that district,
and read nearly as follows:
"`You are legally drafted into the militia of the
United States for the term of three years,
and you are required to present yourself at my office, at Alliance,
+++_______+++ day of +++_______+++, in order to be mustered into service.
Failing to comply with this, you will be treated as a deserter,
and subject to be punished to the utmost extent of the law.
Given forth under my hand.
J+++.+++ F. Oliver, provost marshal.`"

I repaired at an early date, or previous to the time specified,
and had an opportunity to lay before the officers assembled
there the reasons why I could not comply with the order;
that I was conscientious against taking the life of my fellowmen,
or in any way taking part in the war spirit,
believing it to be in direct opposition to the command of our Lord,
"`You shall not kill,`" and therefore I did not expect
to report myself at the time proposed.
I returned to my home; but in a few days an officer or deputy called at my shop,
and commanded me to get ready in a few minutes,
as he desired to return by train time to Columbiana station,
in order to go to Alliance immediately.

Thus, in a few minutes I had to part with my family,
not knowing how long I should be detained from home,
or whether I should ever be permitted to see them again.
On nearing the station,
he asked me what he should do with me while he drove
out nearly a mile to bring in William Nicholas.
I told him I should not put him to any trouble; that wherever he left me,
there he would find me.
He soon returned, and in a short time we were pushing on to Alliance.
After arriving, and being conducted to the marshal`'s office, they took our height,
complexion, etc., so that we could be easily identified, or picked up if we ran away.
They then wanted us to dress in soldiers`' clothes; this we could not do,
therefore they took my friend into another room.

Notwithstanding my dismal forebodings of the future,
I could not avoid smiling when my friend came out and told
me that when he was being dressed he said to the officer:
"`This is the first time I have been dressed since my mother dressed me,
having had uninterrupted good health.`"
Then came my turn, and I discovered the officer found it a heavy job,
for he often sighed deeply,
and I was handled as carefully as if I had just recovered from a spell of sickness.
He was about adding a haversack, canteen, etc.
I told him I did not expect to use them, so he let me go without.
Through their persuasion, I so far consented as to take pen in hand,
and was just in the act of signing my name to what proved to be the muster roll,
thinking that, notwithstanding these clothes were forced on us against our will,
it would thus do to sign my name to certify I had received them.
While reflecting, William came (he having been in another part of town,
and felt an impression to come immediately to the office), and accosted me thus:
"`What are you doing?`"

[.offset]
I replied: "`I have just been considering whether I should sign my name to this.`"

[.offset]
He answered: "`I would do no such thing.`"

I requested an hour to consider it.
Having privilege to walk about town, we retired to a wood nearby; endeavoring,
in silent retirement, to draw near unto the Lord,
that we might be kept from doing wrong by attending to that
which He might instruct us to do or leave undone.

We soon returned, and as I entered the office strength seemed given me to stand firm.
The language ran through my mind: "`Let them do their worst.`"
I told them I could not sign it.
They still urged, by persuasion and threats, but without avail.
Some of the officers spoke in an undertone to each other, in an adjoining room, saying:
"`We will send them to the rendezvous, at Columbus, then they will make them squirm.`"

We were consigned to the care of a young man to guard us over night,
who took us to a large warehouse where many of his comrades, with himself,
were making merry over what seemed to them our calamity.
When they ceased their loud talking, I fell asleep and slept sweetly,
but aroused up in the night, at first somewhat tried with my situation.
I was, nevertheless, favored with a precious covering of Divine regard,
and refreshed in having brought to my remembrance, as though spoken to me:
"`Be of good cheer, Paul; you have testified of me at Jerusalem;
you shall also bear witness of me at Rome.`"
(The names of Alliance and Columbus standing for Jerusalem and Rome.) I soon fell asleep,
and when I awoke the sun was breaking forth in the east,
and in a few minutes we were hurried out to take the earliest train to Columbus;
the young man taking the precaution to buckle on a belt in which he thrust a horse-pistol.
I told him he need not carry this on our account,
as we would not run away or put him to trouble.
Still he sat close by us in the car,
and in changing cars seemed to urge us to get quickly on the train leading to Columbus.
On nearing this place,
being seated in the smoking-car--as it would not do for such persons as
us to occupy or sit in a first-class car among the finely-dressed and
travelling public--I was favored with such a tide of the water of life
flowing into my soul that there was not room to receive it;
and it flowed back to our ever-present and glorious Shepherd in a song of praise;
and as the whistle blew and the cars came to a stand, words ceased to flow,
and I was ushered into a tranquil, quiet,
trusting adoration of Him to whom alone praise is due.

When nearing the barracks, the sight of the guards,
with their bayonets glistening in the morning sunlight, produced no fear,
the fear of man being taken away.
Being handed over to the officer in charge, we were soon inside,
the massive doors shutting out the world of beauty;
but in fond memory I was back again mingling with dear friends and loved ones at home.

After our names were taken, we were consigned to certain quarters.
I soon found that we were in the hands of unprincipled men,
with a board fence twelve feet high, encircling, perhaps, eight acres,
with sentinels but a few rods apart, inside and outside, walking their beats.
Inside this fence were many large, two-story buildings,
all fronting a tall flag-staff in the center.

Soon after rising in the morning, we were called into line by the tap of the drum,
and were expected to answer to our names,
and march in with ten or twelve hundred men to breakfast;
this we did not feel free to do, nor to join in the ranks to drill,
so we were reported by the officer of our barracks up to the major general.
When we came before him, we found a man tremulous with rage.
After he had spent himself in railing out against us, my friend was about to reply,
when he forbade him, saying: "`Not a word out of your mouth!
Your stubbornness may even be the means of causing a mutiny among my men;
but you are not to have your way;`" and closing with "`Now go back to your quarters,
and when you are commanded to drill, drill!
You will have to do it, even if we have to place two bayonets before and two behind you,
or if we have to run them into you.`"
Then we returned to our quarters,
and that afternoon all were desired to come out and
range themselves in front of the barracks;
this we could not do,
feeling that it was contrary to the commands and precepts of our Saviour,
and especially we feared to do despite to the spirit of grace made manifest in the heart.

In the afternoon we were nearly alone, while almost agonizing I was made willing,
or drawn to bow in great prostration of soul,
to put up my cries and tears to Israel`'s unslumbering Shepherd,
craving with much earnest entreaty that He, who preserved Daniel in the lion`'s den,
and the three Hebrew children in the midst of the burning fiery furnace,
would arise for our deliverance;
for I felt as though I would rather lay down my life than dishonor his name.
I then experienced a calm in the midst of seeming danger.
That evening we were conducted to the guard-house as a punishment,
and as the officer handed us over to the corporal of the guard-house, he said:
"`These are Quakers, whose principles do not allow them to attend roll-call, or to drill,
but not sent on account of any misdemeanor.`"
This prison was a foul place, near the stabling--a place to be dreaded.
Here we were confined with about fifteen persons, some of whom were the most depraved,
I think, I ever saw.
Our guard said to us: "`Men, I do pity you, as it is such a filthy place,
and such hard cases to be your company;
but I do like to see men live up to their principles.`"
I said: "`Perhaps you have felt condemnation for wrong-doing;
or a glow of satisfaction when you do well.`"
He replied he had.
"`Well, now,`" said I, "`live up to this,
and you may be brought into as tight a place as we are.`"
He said: "`I want to do so;`" and, giving us a cordial shake of the hand, bid us farewell.

Our new abode consisted of a building some thirty by sixty feet, with an open partition,
so that the guards, sitting or lying in the other end of the building,
could prevent the escape of any of its inmates.
There was a padlock on the door, with iron gratings to the windows,
and lamps were kept burning all night.
Notwithstanding these circumstances, I trust I shall remember, until my dying day,
the happy night my friend and I passed,
with nothing but a blanket between us and the plank floor.
Soon after being thus incarcerated, a tall man, with sword dangling by his side,
and epaulets on his shoulders, calling us by name, commanded us to come out there.
The large door was unlocked and we led out, where were gathered a few soldiers,
and an under officer, who was disposed to terrify us to drill, ordered us to stand erect,
with the heels close together.

My friend rehearsed the Scripture: "`You shall not kill.`"
"`Now whether it is right to obey God rather than man, you judge.`"
I also replied to them that, "`If you force us along, we will have to go; but,
as I do not expect to kill anyone, I do not wish to learn the trade.`"
Then we were conducted back to prison.
We were soon visited by some of our friends,
who took us before an officer to get us to accept positions as nurses, urging "`That,
although we were conscientious against fighting,
it was acting the part of the Samaritan to nurse or heal.`"
I believe words were given me to reply that "`This
is only a part and parcel of the dreadful demon,
war.`"

We were repeatedly visited by a cousin of the secretary of war, Stanton.
He, being a wise and humane man, took us before a notary public,
and had me give my views as to my conscientious scruples against war,
signing his name as a witness, then allowed me to write, which I did,
stating that I would endeavor to bear whatever sufferings were permitted to befall me,
until Providence made way for my deliverance.
This instrument of writing was sent to Washington, and probably occasioned my discharge.

About this time William Nicholas was taken to camp Chase,
he needing the aid of a physician; this deprived me of his company.

The corporal, finding the Quakers were to be trusted,
said to us one day he would like us to help him remove
some wood and pile it up in another place.
I had noticed a large amount of filth and offal there.
I told him I would help him if he would allow me to clean up this,
so as to make it more healthy in our prison, which he did.
I was also allowed to go to the postoffice, nearby, without being guarded.

Soon a demand came from the war department for more men in Shenandoah Valley,
as it was in a defenceless condition, and I was told my name was taken to go.
One day, as I was pacing the room with my mind much turned to the Lord,
all at once I seemed to see a helpless infant lying on the floor.
My heart seemed drawn out in sympathy for the child,
lest it should be crushed under the feet of the guards.
Just then some hand seemed to snatch it up.
This assured me, beyond a doubt, that I was under the care of Providence,
therefore I need fear no evil.
I wrote to my wife that "`The day of my deliverance draws near.`"
On inquiry, the officer said my name was not taken,
and I beheld many hundreds provided with all the implements of war;
drilled and marched out at the large gates, and sent away to Virginia.
Poor fellows; my heart yearned for them,
as it seemed doubtful whether they would ever see their families again; and,
more than all, if they were launched into a never-ending eternity,
could I hope their end would be peace!

In a few days an order came from the secretary of war,
ordering the officer to release me from the prison,
and from being confined at Todd barracks.
Thus was I relieved from the hands of unprincipled men,
and restored to the bosom of my family, with a reward of peace.
All praise to Him that enabled me to endure the cross and despise the shame, to his glory.

--

The sufferings of Friends in the Southern States, especially in North Carolina,
during the war brought on by the slaveholders,
far exceeded those of their fellow professors in the North.
The officers of the Confederate government were less favorably disposed to them,
and were more determined and unrelenting in their purpose to force
those who were conscripted into the ranks of the army.
The experiences of Friends in those trying times,
in supporting their testimony against war,
furnish interesting illustrations of the conscientious faithfulness of the sufferers,
and of the preserving power of the Lord extended for the help of his obedient followers.
Friends of North Carolina published an account of the suffering inflicted on their members,
from which the following narratives are extracted:

[.embedded-content-document]
--

S+++.+++ F., who had become a member with us after the passage of the exemption act,
and could not avail himself of it, was arrested in the Twelfth Month, 1864,
and taken to Salisbury.
On refusing to take a gun,
he was subjected for two hours to the brutal punishment known as bucking;
in which the person is placed in a stooping position,
the wrists firmly tied and brought in front of the knees,
with a pole thrust between the elbows and the knees,
thus keeping the body in a painful and totally helpless position.
After this he was made to carry a pole for two or three hours,
and then tied during the night.
The next morning he was tied up by the hands for two hours.
The same afternoon a gun was tied to his right arm and a piece of timber to his neck.
Unable longer to endure the weight of it,
he sat down in order to support the end of it upon
the ground when he was pierced by a bayonet.
They then bucked him down again,
and gagged him with a bayonet for the remainder of the day.
Enraged at the meekness with which these cruelties and indignities were borne,
the captain began to swear at him, telling him it was useless to contend further,
he must now take a gun or die.
As the captain proceeded to tie the gun upon his arm, S. F. answered quietly:
"`If it is your duty to inflict this punishment upon me,
do it cheerfully--don`'t get angry about it.`"
The captain then left him, saying to his men: "`If any of you can make him fight,
do it--I cannot.`"
Two young men now appeared with their guns,
telling him they were going to take him off and shoot him.
They, however, took him to the colonel of the regiment, who, more inclined to mercy,
advised him to consult a lawyer and procure exemption, if possible,
but assured him that if not so released he must take his gun or die.
Two days after his gun was tied to his arm with great severity,
and a strap passed around his neck, by which he was dragged around nearly the entire day.
The next day the bucking was resorted to.
A Friend, who visited the camp at this time, remonstrating against such cruelty,
it was given up;
though he was still retained as a prisoner till the surrender
of Salisbury not long after restored him to his family.

J+++.+++ B., of Chatham County, N. C., was, at the commencement of the war,
a Baptist and colonel of the militia.
He threw himself eagerly into the southern cause and began to raise volunteer companies.
The refusal of some Friends to join in a parade,
led him to examine the ground which they held.
The result was,
that he first hesitated to order the captains of
the different companies to enroll the Friends,
and soon after, in the fall of 1861, he resigned his own commission,
under a full persuasion that "`It was not right to slay his fellow-men.`"
Starting on a dark night not long after to attend a political meeting,
to be held near him, he lost his way, and wandering in no small distress of mind,
he reached at last the public road,
and the steps of a building which proved to be the Friends`' meetinghouse.
While seated there alone, in solemn meditation,
he became satisfied that it was his duty to unite
himself with the people who worshipped there.

Delaying a little to perform the vow which he had at that time made,
on the sixth of Third Month, 1862, he was drafted.
He evaded the search made for him by escaping into another county.
Venturing to return in the Eighth Month he was for some time unmolested.
He was received into membership with Friends in the First Month, 1863.
He soon after paid the exemption tax.
But the enmity which followed his decided course, and hitherto singularly held in check,
now had its way.
Early in the next year his exemption was revoked by a sub-officer,
and he was sent under guard to Camp Holmes, near Raleigh, and then to Wilmington,
where for four weeks he suffered much abuse.
But his spirit was so far changed that he was able to endure it meekly,
and even literally when smitten on the one cheek turned the other also.
A petition for his release from his friends, proving ineffectual, he resolved to escape.
After a perilous journey, on foot, of two hundred miles,
he reached his home only to be recaptured the next morning,
and was soon again at Wilmington under still more cruel treatment.
Believing he had erred in his hasty escape,
he now became resigned to whatever they might be able to inflict.
An alarming illness, which brought him to the brink of the grave, led to his discharge.
Upon his recovery he was again ordered to camp, and put in jail for a week.
Passed on again as a prisoner from camp to camp,
he had in each place to bear his testimony amid sneers and taunts and cruel threats.
He was finally released by the surrender of Johnston`'s army.

E+++.+++ P. H., who has since become a member of our Society,
became strongly convinced of the principles of peace.
He was ordered to Salisbury to guard government stores,
but refusing to participate in any way in the work of war,
a gun was fastened to his back, and he was tied to a guard-post.
In writing of this to a friend,
he spoke of it as "`The first punishment he had had the
blessed privilege of enduring for Christ`'s sake.`"
Often the curious crowds gathered around him to witness what in their eyes,
as naturally in his own, stamped him as a coward and despicable.
But instead of yielding to such an imputation,
he fearlessly explained the conviction that led to his singular position;
thus sometimes opening the eyes of others,
and compelling the respect of nearly all to a courage far beyond their own.
Strikingly were the words of the Apostle Peter verified in his experience:
"`If you be reproached for the name of Christ,
happy are you;`" and "`If any man suffer as a Christian, let him not be ashamed,
but let him glorify God on this behalf.`"

The surrender restored him to his family,
and the life thus ennobled by patient endurance,
has since been earnestly devoted to the relief of the suffering
around him and the highest welfare of his fellow-men.

G+++.+++ M. was arrested and removed from one guard-house to another, till reaching Richmond,
he was sent on to join the army of general Lee, then in the valley of Virginia.
Refusing to fight, he was ordered to the rear to cook.
He explained that while willing to do his own cooking,
he could take no part in any of a soldier`'s duties.
For this refusal he was bucked down for some hours.
The next day the army was obliged to retreat, and on the way he was offered a gun.
He replied that he had no use for it, as he could not fight.
The general in command of his division then threatened him with immediate hanging,
and he was marched towards some trees selected for the purpose.
But arriving there he was allowed to go on with the retreating army.
Refusing to accept any occupation that was military,
even to carrying the baggage of the officers,
after varied abuses (among which were much knocking and kicking),
he was put in close custody at Petersburg, where his hardships were great;
water to wash with being refused him for three weeks.
But the surrender of Lee`'s army at Appomattox Courthouse followed,
and he was discharged, after bearing his testimony, for conscience`' sake,
through seven months of great trial and suffering.

Other members of this same family were called upon
to lay down even their lives for a testimony.

J+++.+++ M., who had recently become a member, and had obtained employment in some iron works,
in order, if possible, to keep from the army, was arrested and hurried away,
without being permitted to see his wife and family--first to Raleigh,
and then in a few days to the army in the valley of Virginia.
He was forced into the battle at Winchester, and in the retreat,
finding the balls flying thick about him, he lay down upon the ground for safety.
Being taken prisoner, he was carried to Point Lookout, where, in a few days, he died.
It was believed by his family that his death was
hastened by the mental suffering which he endured,
both in his separation from them and in witnessing such scenes of carnage,
in which he could take no part,
and from which the natural tenderness of his soul recoiled.

A+++.+++ M., another brother of this family, had received a Christian training,
and being fully convinced, both from the Scriptures and his own experience,
that he should not resist evil, and that he was bound, so far as possible,
to live peaceably with all men, he sought admission to the Society of Friends.
He had obtained a discharge from the army, which was disregarded.
The sergeant who was ordered to arrest him was an old schoolmate, who,
while endeavoring to procure his release, also protected him from abuse.
From the first he had a strong impression that his days were now numbered,
and while still in health he wrote to his father,
giving his last messages to his brothers and sisters,
and also his wishes respecting his own burial.
He was taken to Richmond, refused to fight, and was put under guard.
The rations given him consisted only of meal made from cane-seed.
This unwholesome diet led quickly to severe illness,
and in one of the hospitals at Richmond, he laid down his life for the Gospel of Peace,
a good soldier of Jesus Christ,
and earlier permitted a happier discharge and a more
glorious reward than any of earthly giving.

S+++.+++ W. L., of Randolph County, N. C.,
was another of the number who proved faithful unto death.
He had been a member of our religious Society but a few months,
when he was arrested as a conscript and sent to the camp near Petersburg,
Va. Upon his arrival he was ordered to take up arms.
This he refused to do, and as a punishment was kept from sleep for thirty-six hours.
As this did not move him,
for about a week after he was daily bucked down for some length of time,
and then suspended by the thumbs for an hour and a half.
Being still firm in his refusal to fight, he was court-martialed and ordered to be shot.
A little scaffold was prepared, on which he was placed,
and the men were drawn up in line ready to execute the sentence, when he prayed:
"`Father, forgive them; for they know not what they do.`"
Upon hearing this, they lowered their guns, and he was thrust into prison.
Not long after he was sent to Winder Hospital, at Richmond, Va+++.+++, where,
after a long and suffering illness,
the end came in his peaceful release for a mansion in heaven.
A few lines from an officer in the regiment to which he
had been assigned closed the suspense of an afflicted family,
when his widow and his seven children were left with
little other legacy than the like precious faith.
"`It is my painful duty to inform you that S. W. L. died in Winder Hospital, at Richmond,
on the eighth of December, 1864.
He died as he had lived, a true, humble and devoted Christian,
true to his faith and religion&hellip; We pitied him and sympathized
with him&hellip; but he is rewarded for his fidelity and is at rest.`"

J+++.+++ M. J.,
A+++.+++ J. and D. J. were three brothers who joined Friends
after the passage of the Exemption Act.
After their names were placed upon the list of conscripts in 1863,
they still remained quietly at home, not even hiding in the woods.
Their protest against bearing arms was unheeded,
and they were sent on to the army at Orange Courthouse,
Va. There they were ordered into the ranks, but on refusing to obey,
J+++.+++ M. J. was knocked down with a gun, and a long gash cut in his head.
On attempting to rise, the blow was repeated,
this time nearly cutting off a portion of his ear.
This was done a third time, and he was sent to prison.
His brother A. was at the same time undergoing his trial,
being pierced with a bayonet to the depth of nearly an inch.
The third brother, though severely tried, suffered less in person.

They were soon after sent to the Rapidan, to general Scale`'s command,
where new trials awaited them.
The American officers, finding all their efforts to fail in subduing them,
turned them over to a German officer, who boasted that he could make soldiers of them.
Various punishments and abusive, threatening language were used in vain.
He then ordered them to be kept in close confinement for three days and nights,
without food or drink, making it a court-martial offence for anyone to relieve them.
A Kentucky soldier, in the darkness of the night, nobly risked his safety,
and passed in to them a little water, to their great relief.
The end of this trial found them still unwavering.
They were then all bucked down for three or four hours.
This cruel punishment, following so closely upon the others,
proved too much for the mind of the youngest, which became, for a time, deranged.
He was allowed medical treatment in a hospital until his recovery,
when he was again sent back to camp.
This severe treatment had now been continued for four or five weeks, when a Friend,
who was searching for them, obtained first, the suspension of this cruelty,
and soon after, by application to Richmond, their release.

--

In the Spring of 1862, two brothers, H. M. H. and J. D. H. were drafted,
arrested and taken to Raleigh.
Being allowed to return home for ten days they faithfully reappeared.
They were soon sent to Weldon, where they were required to drill,
and were warned of their liability to be shot if they proved refractory.
They were, however, only kept in close custody in the guard-house,
and the next month were discharged and sent home.
About a year after this, they were included in the conscription.
They were assigned to an artillery company at Kinston, and after various threats,
were sent to general R+++_______+++,
who declared that his orders should be carried out at all hazards.
They were now confined in an upper room without food or drink.
Various persons were allowed to converse with them, and, as day after day passed on,
so far from sinking under the suffering,
they used their little remaining strength gladly in explaining their testimony,
and telling of their inward consolation.
They felt that, in this time of fiery trial,
this did indeed turn to them for a testimony, and that they knew the promise fulfilled,
"`It shall be given you in that same hour what you shall speak.`"
Their sufferings from thirst were the most acute.
On the third night the brothers were awakened from a peaceful sleep by the sound of rain.
A little cup had been left in the room,
and from the open window they could soon have refreshed themselves.
The first thought of each was to do so.
They were in nowise bound to concur in this inhuman punishment.
Yet an impression was clearly made upon their minds, before consulting each other,
that they must withhold, and they scarcely felt the copious showers tempt them.

The next morning several officers entered the room and questioned them closely.
They claimed it to be impossible for them to retain so much strength without any food,
and charged them with having secretly obtained it.
They then, in much simplicity,
told them of their not feeling easy to take even the rain that fell.
This evidently touched the hearts of the officers.
Soon after the end of four and a half day`'s abstinence, a little water was allowed,
and about the end of five days their rations were furnished again.
This remarkable circumstance was widely spread,
and they had constant opportunities of bearing an open testimony to Christ,
and not a few of those who crowded around,
appeared to be persuaded of the truth which they held.
Even ministers of different denominations came and encouraged them to be faithful.

J+++.+++ D. H. was next taken before general D+++_______+++,
who said he would not require him to bear arms,
but would set him in the front of the battle, and use him to stop bullets.
On declining to work on the streets as a part of the soldier`'s duty,
he had a log of wood tied on his shoulders and was marched around until quite exhausted.
He was next sent to a guard-house,
then placed in a dungeon for a day--then in a prison cell.
His persecutors seemed at their wits`' end,
but they finally devised a rude and barbarous punishment.
A forked pole was thrust round his neck, and upon the prongs,
as they projected behind it, a heavy block of wood was fastened.
This they blasphemously called the Cross of Christ.
The soldiers and town`'s people were looking on,
while he was thus "`made a gazing stock by reproaches and afflictions.`"
No sooner had the captain fairly completed this work
than in a rage he pulled it off again,
and tied another log upon his shoulder, and marched him about till exhausted,
when he was sent back to jail.

Meantime his brother H. had been enduring a different punishment.
At three different times he was suspended by his thumbs,
with his feet barely touching the ground upon the toes,
and kept in this excruciating position for nearly two hours each time.
They next tried the bayonet.
Their orders were, they said, to thrust them in four inches deep; but,
though much scarred and pierced, it was not so severely done as they had threatened.
One of the men, after thus wounding him, came back to entreat his forgiveness.
In the various changes of the next four months,
some kindness was occasionally shown to them, but mingled with much cruelty.
It was not till seven months had been passed in these fiery ordeals,
that their release was obtained--another Friend thinking
it right to pay their exemption money for them.
The value of this tax, at that time,
was only equal to a little more than a barrel of flour--a small sum indeed,
could they have felt themselves easy to avail themselves of this provision.
It was no small addition to their sufferings that
their families at home were sharing in it.
In the extreme scarcity of labor,
their wives were compelled to toil hard in the fields
to raise the food for the coming winter,
and this proved not merely a passing hardship,
but left one of them in greatly enfeebled health.

Another brother of the same family, W. B. H., was arrested on the eighth of Sixth Month,
1863.
The officers to whose division he was assigned, were unusually rough and severe.
Finally,
after a full explanation of his views and the necessity
he was under of refusing all military duties whatsoever,
the colonel said he should be shot,
and the only favor allowed should be the choice of time--that night or the next morning.
After a little pause, W. H. replied,
that if it was his Heavenly Father`'s will that he should lay down his life,
he would far rather do it than disobey one of his commands.
But if it was not his will, none of them could take his life from him;
however they might give the order to do so.
He then spoke of the three men who were cast into the burning fiery furnace,
and of Daniel in the lions`' den, who all trusted in God, and He delivered them.
As to the time of his death, he could make no choice.
The officer seemed greatly at a loss, and sent him to the wagon yard for the night.

The next morning he was ordered out with a foraging party.
He explained that he had two objections to this.
It was, in the first place, military work, and besides,
it was taking the property of others.
The colonel, now greatly excited, came forward and had him laid on the ground,
while a gun was tied to his back.
He refused to rise with it on.
The men were then ordered to run their bayonets into him,
but they continued only to pierce his clothes.
A squad of men was then drawn up in readiness to fire;
but as the order was about being given W. H. raised his arms and said:
"`Father forgive them, for they know not what they do.`"
Not a gun was fired, and some of the men were heard saying,
"`They could not shoot such a man.`"
The enraged officer struck at his head, but missed his aim.
He then spurred his horse repeatedly to ride over him,
but the horse sprang aside at each attempt, and he remained unharmed.
The officer then left, saying,
he was not yet done with him--but was himself killed
the same or next day in the battle of Gettysburg.
As W. H. was sick at the time of this battle, no attempt was made to force him into it.
He found in the retreat, with which he was unable to keep up,
a shelter and kind care at a farm house,
but was soon taken prisoner by the Union cavalry and sent to fort Delaware,
as a rebel prisoner.
He had been ill there a week before a message could reach Philadelphia.

Application was at once made at Washington,
and a telegram was promptly dispatched from the war office,
ordering his release upon taking an affirmation of allegiance to the United States.
But loyal as he had ever been, he could not promise "`to support,
protect and defend`" the constitution and government.
He had already suffered too much and been too marvellously preserved
to flinch now from bearing any portion of his testimony.
He was told while thus apparently upon the eve of his release,
that there were two alternatives--this affirmation
or imprisonment until the close of the war.
But upon a fuller explanation of the nature of his scruples,
an alteration was promptly made in the form of an affirmation.
He was released, and like many others,
found a home in the West till the close of the war
allowed him to return to his beloved family.
The God whom he served had indeed been able to deliver him.

At the same time that W. B. H. was arrested, four others,
having a birth-right membership with us, and opposed to the payment of the tax,
were taken by force from their homes in Randolph County, C. and A. B., brothers,
and T. and J. H., also brothers, and cousins of the former.
Although detained in the army for nine months,
they suffered comparatively little from the cruelty of officers;
yet the uncertainty of their lot,
and the painful surroundings of camp life kept them in constant
dependence upon the care and lovingkindness of their Lord.
On their passage from Weldon to Camp French, near Blackwater, Va+++.+++,
the conscripts were packed standing so closely in a car,
that they could only rest themselves by leaning on each other`'s knees,
and were kept in this way, without water,
and with only the little food a few chanced to have with them,
for nearly twenty-four hours.
They were assigned to the fifty-second North Carolina regiment.
On declining to drill, they were entreated to pay the commutation tax,
and were assured that their money should be only used for civil purposes.
They steadily urged that liberty of conscience ought not to be purchased in any way.
The colonel then assigned them to captain K+++_______+++,
and from him and his company their quiet and consistent course won unexpected favor.
The lieutenant, however, for a time was very harsh,
and ordered his men to compel them with guns and
bayonets to aid in clearing ground for a camp.
He was just ordering two men to press steadily upon them with their bayonets,
until they moved, an order which they contrived to evade for a few moments,
injuring them but slightly--when captain K. appeared, and reproving the lieutenant,
told them they might remain quiet for that time.
As they trusted in the Lord, He often turned the hearts of their commanders,
so that even this same lieutenant became kind and considerate.

All sorts of work were offered to them, cooking, waiting on the sick, etc.
But though willing to do the work itself,
they could not accept such labor as military service.
At one time they were ordered to help bring in some fodder.
On refusing, they were first fastened together and then tied behind a cart,
so as to force them to run or be dragged three or four miles and back,
through mud and water, upon a very cold day.
If they still refused to load the fodder,
the order was to pitch them into the river--but such
orders were more easily given than executed.
Even the wagon master, who at first seemed fierce, relented,
and after watching them pass through this humiliating trial,
declared he could not help respecting men who stood up to their principles in that way.
Their presence in the army became more and more perplexing.
The wish was expressed that they would run away, but this they would not do.
Furloughs were often given,
and a written endorsement on one of these assigned as a reason for it,
that "`They were of no manner of use in the army.`"
At the battle of Gettysburg, their prayers were heard,
and though often ordered to the front, they were never forced to go.
They shared the same lot as their friend W. B. H.,
and were released from Fort Delaware by the same order.

Among all those who steadily refused to bear arms, and of whom many were imprisoned,
not one suffered a violent death,
which must surely be traced to the overruling providence of Him
by whom "`Even the very hairs of our head are all numbered.`"

The pecuniary loss sustained by Friends of North Carolina was not small.
As they could not fight, and as they were charged with favoring the cause of the Union,
they were frequently marked out for special plunder.
In the few small meetings in Tennessee, included in the limits of this Yearly Meeting,
the loss (in gold) was thirty-five thousand dollars.
In the vicinity of Goldsboro`', in a Quarterly Meeting of about forty families,
the whole loss of property was estimated in official returns at ninety-eight
thousand two hundred and twenty dollars (in gold.) This resulted,
in part,
from the army being quartered upon them at various times during the four years`' struggle,
but chiefly from the desolating march of general Sherman in the spring of 1865.
In not a few cases Friends were pointed out as very
obstinate secessionists and deserving no mercy.
Their homes were stripped of almost every comfort.
Much of the bedding and clothing, furniture and food, which they could not carry off,
was carelessly destroyed.
Their stock was generally swept away, and scarcely a living animal, even to a chicken,
remained.
The sick were taken from their beds, that the soldiers might search for gold.
So extreme was the destitution that followed,
that those who had lived in plenty were now seen upon the track
of the army--searching for fragments of food to sustain life.
A few old bones were counted a welcome treasure, and when this resource failed,
and rations were distributed in Goldsboro`',
delicate women and children had often to walk ten
or fifteen miles to procure a few days`' scanty food.
The seed placed in the ground had been mostly destroyed and they could obtain no more.

The fellowship between members of other Christian
denominations had been sundered by the war,
while Friends had maintained their Christian love and brotherly
confidence unbroken during these years of separation and trial.
And no sooner had the tidings of this great suffering reached Friends of Baltimore,
than the most prompt and generous measures were taken for their relief.
Funds were also freely contributed by Friends elsewhere;
clothing and various little comforts, such as love only could suggest, were prepared,
and shipments of food went forward immediately;
the secretary of war promptly giving passes to those who were the bearers of this relief,
the first we believe sent after the surrender.
Though personally strangers,
they were welcomed with tears of joy and gratitude by Friends;
and even others who still felt alienated from fellow professors,
and even kindred at the North, looked on in wonder at this exhibition of love unfeigned.

Meantime the Friends living in the counties of Alamance, Chatham, Randolph and Guilford,
and comprising by far the largest portion of those in the State,
were placed in most imminent peril.
After the fall of Richmond and the surrender of general Lee,
the army of general Johnston was still near Greensboro,
while the army of general Sherman moved on from Goldsboro`' to the other side of Raleigh,
and with a day or two`'s march between, demanded the surrender of the Confederate forces.
While awaiting the answer, President Lincoln was assassinated.
Roused by this to a still more determined spirit,
the army of Sherman seemed prepared for the most utter devastation.
Between the two opposing forces, and indeed partially surrounded by them,
lay their peaceful homes,
with an apparently almost certain destruction hanging over them.
They had neither weapon nor shield,
save their prayers and their trust in the arm of the Lord.
But these were all that were needed.
The threatening cloud of battle rolled away and the surrender of the last
of the southern armies was effected without bloodshed in their very midst.
Through four years of danger and distress on every hand,
the Lord had been increasing the faith of his people,
and now they were left to rejoice in safety over their last,
crowning and eminent deliverance.

Joshua Evans, a minister in the Society of Friends, mentions that,
about the year 1706 war was being waged between the English and French.
He says:

[.embedded-content-document]
--

On a certain occasion a number of our young men were
drafted to go as soldiers on an expedition,
but some of the inhabitants concluded on opening
a subscription to hire volunteers in their stead.
This seeming plausible, even to some under our profession, a number were taken therewith;
but when it was proposed or demanded of me, I felt a scruple, and told them if,
on considering the matter, I could be free to pay money for such a purpose,
I could hand it forward.
I had none to confer with on this occasion, but it was opened clear to me that,
to hire men to do what, for conscience`' sake, I could not do myself,
would be very inconsistent.
This led me in deep humility to seek for wisdom to guide me rightly,
whereupon I found it best for me to refuse paying demands laid on my estate,
which went to pay the expenses of war;
and although my part might appear but as a drop in the ocean, yet the ocean,
I considered, was made up of many drops.
Thus I had to pass through reproach because I had enlisted under
his banner who declared his kingdom was not of this world,
or else his servants would fight.

When my goods were taken to answer demands of a military
nature (which I was not free to pay voluntarily),
and sold, perhaps, much under their value, some would pity me,
supposing it likely that I should be ruined; others would term it stubbornness in me,
// lint-disable invalid-characters
or contrary to the doctrine of Christ concerning that of rendering to Cæsar his due.
But endeavoring to keep my mind in a state of humble quietude,
I was favored to see through such groundless arguments;
as there is not anything on the subject of war to be found in that text;
and I have been willing to pay my money for the use
of civil government when legally called for,
though restrained by a conscientious motive from paying towards the killing of men,
women and children, or laying towns and countries waste.
Through each of my trials in these cases, my wife encouraged me to be faithful, saying:
"`If we suffer in a right spirit,
we shall obtain that peace which the world can neither give nor take away.`"
I found when closely attentive to the pointings of the true light,
I was at times enabled to pray for my opposers and persecutors,
and to magnify the name and power of my God.
So let all be encouraged to hold on their way who are given up to serve Him in sincerity.
In this situation, no weapon formed against you shall prosper.

After the tribulations I have last mentioned,
some of my greatest opposers came to own my testimony,
and great was my peace in attending to my tender scruples.
I passed through many baptizing seasons, and have not seen how to reconcile war,
in any shape or color, with the mild spirit of Christianity,
nor that devouring disposition with the peaceable,
lamb-like nature of our blessed Saviour.
It seems to me we might as well suppose that theft
and murder do not contradict his royal law,
which enjoins the doing unto others as we would have them do unto us.

--

[.blurb]
=== Faithful Testimony Against War

During the war of the American Revolution, a young man named Moses Sleeper,
who resided in Maine, was ordered to join a militia company on a certain day.
He believed that war was wrong, and on this account refused to obey the order.
For so doing, he says:

[.embedded-content-document]
--

I was taken by an officer and file of men to fort Halifax, eighteen miles up the river,
and there shut up in a loathsome fish-room in an old block-house,
with a bunch of straw thrown on the floor to sleep on, the room being entirely dark,
except what light shone through a chink of the door and window-shutters.
After lying there a few days, I was taken to the headquarters in that section.
Here a court-martial was called, consisting of six or seven officers, and I was examined.
At the end of the trial, I was delivered to the care of a sentinel,
who placed me a few rods under the side of a barn,
within a few paces of the skirt of a wood.
The court were not long in making up their judgment--when they
went to the commander`'s quarters for him to approve the sentence.
Soon after, I being under the care of the same sentinel,
and in view of every part of the encampment, one of the captains came up to me,
and the following interview took place aside from the sentinel:

[.discourse-part]
__Captain__--Moses,
I can inform you that the court have made up their minds
upon the several charges exhibited against you,
and though it is against martial rules for a court
to divulge their verdict until it is declared publicly,
yet I can inform you that they have found you guilty of several crimes;
such as non-compliance with orders, absenting yourself at roll-call,
which is termed desertion, and for which they have pronounced sentence of punishment;
and I have been soliciting the commander to have the punishment taken off,
knowing it is in his power so to do, but cannot prevail;
but if you will take my advice you may evade punishment.

[.discourse-part]
__Prisoner__--Captain, you tell me that I am to receive a punishment,
and that you can put me in a way to evade it.
You will be so good as to point out a way by which I can escape a punishment,
though justifiable by martial law, yet unjust in the sight of God.
If I can with peace of mind, I will naturally accept your proposal.

[.discourse-part]
__Captain__--The way I propose is this: The wood you see is but a few paces off.
Step out into those woods, which are very thick, continue there hidden until dark.
You may then retire to the barn, if you please, till tomorrow morning,
then your time is out and they cannot touch you.

[.offset]
(It was then about three o`'clock p.m.)

[.discourse-part]
__Prisoner__--It is with feelings of gratitude, captain,
that I have noticed your kindness to me during my confinement,
and more especially in these your efforts to get me released
from punishment to be inflicted by martial law,
but how am I to get to these woods?

[.discourse-part]
__Captain__--I will call off the sentinel.

[.discourse-part]
__Prisoner__--You can not do that without yourself becoming responsible.

[.discourse-part]
__Captain__--Moses, if you will consult your own safety, you will take my advice.
I will call off the sentinel, and risk the consequences.

[.discourse-part]
__Prisoner__--Captain, I thank you heartily for your kindness to me in this affair,
but cannot with clearness accept your proposal.

[.offset]
(Upon which he shook his head, turned and went direct to the colonel`'s quarters,
and in about twenty minutes came back to me again.)

In the second interview, Moses told the captain:
"`It is from the pure conviction that war and bloodshed are contrary to the Gospel dispensation,
that I have thus far encountered the privations and sufferings
attendant through my present state of confinement.
But through the mercy and goodness of Him who has called me thus to suffer,
I have been preserved in an unshaken faith that the
cause for which I had contended was his;
that the testimonies for which I suffer are testimonies of Jesus.
And now, captain, you propose making my escape easy; but only consider for a moment,
my so escaping would by the public be considered desertion and fleeing from justice;
and though I am not a member of the Society of Friends,
yet I am one with them in profession,
and by my acquaintances am considered as one of their number,
that in so escaping I should bring disgrace upon that body, a stigma upon my relations,
and everlasting infamy on myself--I should act that
for which I should never expect to be forgiven.
But as I have now acted my part conformably to the
dictates of conscience and the law of my God,
my mind is perfectly tranquil.
Therefore, as I have not the least doubt of the purity of your motives,
yet let the sentence of the court be what it may, whether the severest punishment,
or even death, I most cheerfully submit, not without a hope and belief that you,
my dear captain, will have your reward for your kind interference.`"

With a tear of regret, he again turned from me, saying; "`Moses,
you wound me to the heart--farewell!`"
He went directly to the commander`'s quarters, and in less than an hour after,
the drums beat, the regiment formed a semi-circle on the green,
and the sentinel was ordered to bring me into the circle--when
one of the clerks read the doings of the court,
with the sentence to receive forty-five lashes on the naked back.
And after a pause read--"`and the above punishment is taken off,
and the said Moses Sleeper is therefore discharged.`"

I have, since the above transaction,
been informed that when the president of the court-martial
presented their verdict to the commander,
he confirmed the sentence, refused to grant a pardon,
and ordered the adjutant (then present) to see that the punishment was inflicted;
but that the adjutant utterly refused,
telling the commander it was his opinion the young man acted from real scruples of conscience;
and rather than be accessory in inflicting a punishment in such a case,
he should give up his commission.
Upon which the commander and the other officers present formed the plan
of sending the captain to use his influence to get me to absent myself,
and not prevailing, the commander thought best to take the punishment off as related.

--

In the early part of last century, some Friends,
bound on a religious visit to the West India Islands,
were captured by a French privateer.
The boarding party having made the crew and all the passengers, except the two Friends,
go on board the privateer, they, expecting to be sent also,
went to the side of the vessel, but were turned back.
It was then the dusk of the evening,
and the Friends felt comforted under a sense of the notice of Providence,
which they did believe was manifested in their being kept together on board the vessel.
Had they been carried on board the privateer, with the rest, they would,
in great probability, have been separated from each other.
Having secured the captured vessel, the privateer sailed for Martinico, a French island,
and their prize slowly followed.
The voyage was long, and the master of the captured vessel found the time so tedious,
and their progress so slow, that he declared the hand of the great God was against them.
He sometimes threatened--his unreasonable impatience with
the elements spreading to all around him--to throw the Bibles
overboard which he found the Friends often engaged in reading.
He probably thought that the baffling winds and little headway
of the vessel were somehow or other connected with those Bibles,
and, perhaps, was affronted at the quiet resignation of the prisoners,
who could enjoy their reading at such a time.

At the end of a fifteen days`' run, they found themselves at Martinico.
An officer of the port came on board and showed a
singular trust and confidence in the prisoners,
leaving all in the vessel under their care that day and the night following.
On the next day the officer returned,
with several persons who appeared to be people of consequence on the island.
On examining the Friends, they looked at their certificates, which one of the company,
who understood English, translated to the rest.
Of the testimony to their good lives and godly conduct given in the certificates,
they do not appear to have taken any notice;
but when they came to the passage in which the meeting expressed
its desire that Richard Gove might be preserved "`from the
hands of unreasonable men,`" one of the company cried out:
"`See, now, the Spirit has deceived you;
for you are not preserved as they would have it!`"
To this one of the Friends answered: "`The Spirit has not deceived us.
That mentioned is only the desire of our friends;
and it is possible that there may be some service for us here also.`"
Upon this the islanders, who were all Roman Catholics, cried out: "`See, now,
they are come to convert the fathers!
We will have you together, and you shall dispute it out.`"

None of the Popish ecclesiastics, however, came near them, except an Irish priest,
who had previously visited the Protestant prisoners
often to endeavor to "`bring them over`" to his faith.
He was allowed, it was said, forty shillings for every convert,
and he found little difficulty in inducing some of the sailors to conform
through the convincing argument of good food to hungry stomachs.
He knew how potent this kind of reasoning was to unsanctified men,
who held religion only in profession,
and therefore seldom came without bringing food with him.
Although the other prisoners wished him to dispute on religious subjects with the Quakers,
he manifested no disposition to engage them.
At last, however, urged on by the continued entreaties of the other prisoners,
he determined to try them.
He commenced with John Estaugh, and finding that he could make no headway with him,
he closed the argument with him by calling him a heretic.
He then turned to Richard Gove, who stood by with his Bible in his hand.
It would appear that Richard did not wait for him to say anything,
but read out of his Bible the passage in Matthew: "`Beware of false prophets,
which come to you in sheeps`' clothing, but inwardly they are ravening wolves,`" etc.
Not relishing the pointed application of the text,
the priest seized hold of the Bible and endeavored
to take it by force out of the prisoner`'s hands.
Richard, however, did not yield it up,
but it long bore the marks of the violence used in the attempt to force it away.
The other prisoners, seeing he had left off attempting to reason,
and was using physical arguments, told him, with a shout,
that he was not able to dispute with the Quakers.

Among the prisoners were some who had long been in captivity.
One of them was a major of the English army, who, although not a strictly religious man,
yet had been in the habit of reading prayers two
or three times a week for the benefit of those confined.
After Richard and John came, they were in the habit of holding meetings in the prison,
sitting down in silence, and ministering, as ability was, from time to time, received.
The prisoners soon began to attend their meetings,
while the prayer readings of the major grew smaller and smaller.
At this he grew angry,
and undertook to reprimand some of them sharply for going to Quaker meetings.
He was told by some of the most sober of them, "`They had heard prayers long,
and swearing and other ill conduct followed after they were over,
which was very disagreeable, and rather worse than if there had been none.`"

The major`'s audience continuing to decrease,
he made a violent attack on Richard and John, with high charges against the Quakers.
John was the principal spokesman in reply, and he managed his cause so unanswerably,
and spoke with such firmness and freedom, that his antagonist was enraged, and told him,
if he spoke another word, he would dash his teeth down his throat.
John was not dismayed at the threatened outrage,
but feeling a concern for the benefit of those who were by, he continued his argument.
As he proceeded, he was so cool and calm that at length the major was ashamed,
and endeavored to moderate his passion, and to pursue the argument in a proper temper.
The quotations from the Bible adduced by John were so contrary to the major`'s
mind that he declared the Quaker`'s Bible was not the same as his.
Yet, after persuasion, being induced to look in his own, and finding the passages alike,
he said: "`I profess, I did not think there had been such a place.`"
Finding all the places he examined similar in both, he became more friendly,
and the disputants parted in mutual good will.
From that he was kind and loving to the Friends.

A cartel for the exchange of prisoners having been
agreed on between the English and French,
it was found that the French had excepted from its benefit
all the prisoners who were either bound to or from Barbados.
This would have continued our Friends`' imprisonment; but Providence,
who had a labor for them to perform for his service in Barbados,
made a way for their release.
Colonel Byham,
who was going as English commissioner from Antigua
to Martinico to superintend the exchange of prisoners,
was desired by Jonas Langford, a valuable Friend,
and influential citizen of the former island,
to inquire if there were any Friends there among the prisoners not included in the cartel,
and if so, to use his influence to get them released.
He promised to do so, and on inquiry found Richard and John.
On this he went to the governor of Martinico,
and asked him as a private favor that the two Quakers, although bound to Barbados,
might be liberated, and go with him to Antigua.
The governor said: "`What!
The two apostles?`"--for such was the name they bore
on the island--and forthwith gave his consent.
They had been two months on the island, and although brought there without their will,
yet in the ordering of Providence so many openings for religious services had occurred,
that they thought in no part of their travels had there
been more evidence of their being in their proper allotment,
although at the island of Antigua, where they were next carried,
two persons were "`thoroughly convinced`" by their labors.
So not only were they preserved from unreasonable men,
but through the wicked acts of fierce privateersmen they were carried
to perform their Master`'s service in a place which would have
been closed to them if they had not come as prisoners.

It sometimes pleases the Lord to bring his servants into situations
where they may bear a testimony to his name and cause,
although it was not in their own planning.
William Reckitt, a minister in the Society of Friends,
felt a concern to pay a religious visit in America,
but in a few days after leaving England, the vessel was taken by a French privateer.
Although his original purpose seemed to be thus frustrated,
yet from his narrative of his experiences it is evident that he was made instrumental
in proclaiming the Truth to many persons who had no other opportunity of hearing it.

The disappointment of our friend in not being permitted
to reach the place of his religious service,
being thrown among blood-thirsty men,
and the probable confinement and suffering he would undergo,
must have been very trying to him.
He says, respecting it:

[.embedded-content-document.letter]
--

When I looked at my present situation, and what was likely to be the consequence,
fearing I might be a stumbling-block in the way of many, and bring dishonor to Truth,
I was much cast down, and did often cry, "`Lord, if I had been worthy,
you would have preserved me out of the hands of such unreasonable men.`"
But the good Shepherd of Israel did cast his mantle of love over me, and still my crying,
so that I was in a good degree made willing to submit to
what he should see fitting to allow to come upon me.

--

He was favored with stillness and sweet composure,
which fortified him against the assaults of the enemy.
He ate little food for several days, till he could take it with freedom of mind,
and a good appetite, which had been quite gone.
The men grew milder towards him, and except in one instance did not offer him any harm,
and that man was prevented from hurting him.
One of them, inquiring of a man-of-war`'s captain they had taken in a vessel,
respecting his religious principles, he told him Friends were a strange people,
denying baptism and the supper.
This gave him the opportunity of explaining the doctrine of Friends on those points,
which they heard patiently, and made no objections.
As they came near the shore, they were chased by an English man-of-war,
who came so fast upon them,
the men expected they should be released from their captivity;
and everyone prepared for removing, but they were so near the rocks,
the ship dared not follow them, and firing a shot which went over them, sheered off,
much to the disappointment of the prisoners.
In a few hours, having been on board eleven days,
they came into a small harbor near a town called Roscoff.
While they lay on board the last night,
William Reckitt underwent much distress on account of a project which
three of the Englishmen entertained of cutting the vessel out of the harbor.
He remonstrated earnestly against it.
He thought it could not be done without bloodshedding, if at all,
and though his liberty was dear to him as anyone`'s was,
he should be very sorry to see anything of that kind.

About midnight the men came up on deck, thinking it time to go to work,
and seemed in high spirits to make the attempt.
William was in a great strait how to act, but thought it best to keep peace, if he could.
He sat down by the principal,
intending to lay hold of him if he offered to take up a weapon which was at hand.
Great struggles were in the man`'s mind, as he afterwards confessed,
and he was often upon the point of carrying out his design;
but the Lord in great mercy interposed.
William became calm, all fear was taken away, and looking at him,
he saw the man`'s countenance was more composed; and asking him if he would go to bed,
he said he would; and the men who had been walking the deck,
perceiving that nothing would be done, also went to their beds.
Seeing them retired for sleep, William lay down on a bulkhead,
there being nothing better in the cabin, and his mind being released from the exercise,
he fell asleep also, and though stiff when he awoke, did not take cold.
He says:

[.embedded-content-document.letter]
--

The Lord was pleased to preserve me, though I often said in my mind,
I did not think myself worthy,
especially because he had permitted this great exercise to come upon me,
which I was several times sensible it would have been a light matter with him to hinder,
if he had seen fitting.
I often cried to Him in the secret of my heart, that if there was iniquity lodging in me,
He would be pleased to take it away; and if my going was not consistent with his will,
that He would be pleased to show me wherein I had missed my way,
that I might not bring a reproach upon the Truth, and trouble upon his people.

--

When breakfast was over,
they searched the prisoners to see what they could get from them;
and took what they found, yet giving William Reckitt his clothes.
Many people came to them on entering Roscoff--two of them priests,
who wished to know his religion, but he did not choose to converse with them.
A person of note said he was sorry to see him there,
and wished him safe again in England,
and procured an eating place for him and three others.
A woman in the house showed much concern about their walking to Morlaix that night,
and desired the soldiers to procure horses for them to ride,
and she would pay the charge.
They were brought before the commissary at Morlaix,
and such as could not give bail must go to prison.
The thoughts of a prison did not terrify him,
and he did not ask anyone to be bail for him, but a person volunteered,
who in a little time showed his deceit in declining it.
A merchant hearing of this,
said he would be bound for him as freely as he would for his own brother.
He was examined in the admiralty office, and something being said about an oath,
he told them he could not take it, being against his principles.
Finding him scrupulous on this point,
they put many questions touching his condition at home; whether he was a minister;
what he was intending to do in Pennsylvania--whether sent by the Quakers;
whether they would fight, etc., to which he made reply or not, as he thought proper.

"`About this time,`" he says: "`I suffered much in spirit;
the reason is best known to the Lord.
I was much afraid lest I should bring dishonor to Truth through unfaithfulness,
or some slip I might make, for lack of care in that strange land,
separated from my brethren, and deprived of all outward comfort and help.
But this to me was a profitable season; for I found the fear of the Lord,
which was in my heart, did preserve me from evil, and from falling into temptation.`"
Though such company was unpleasant, and he thought himself unfit for conversation,
yet when honest persons asked questions concerning our faith,
he was helped in the openings of Truth,
to give them an answer concerning the hope that was in him.

Charles Sermanson, who often invited him to his house,
asked why he went abroad in such troublous times; to which he replied:
"`I believed it to be my duty;
nothing else would have induced me to leave all that were near to me in this world,
as wife and children, but a sense of duty to God,
and obedience to what I believed He required of me; for as to outward gain or advantage,
I had nothing of that in my view; for such as have freely received must freely give.`"
When his wife understood I had left wife and children at home,
she said that could not be consistent with the will of God.
William reminded her that Christ says, "`He that loves father or mother,
wife or children, houses or lands, more than me, is not worthy of me.`"
He took the liberty of reproving her husband for taking the sacred Name in vain; which,
he supposed made an alteration in his countenance, as she asked what he said.
When Charles told her, she said he had done well, for that was his great weakness,
and she hoped he would take notice of it.
William remarked: "`By turning our minds to the light of Christ in our hearts,
which reproves for sin, as we came to yield obedience to it,
we should be helped to overcome our weaknesses.`"

[.embedded-content-document.letter]
--

She said I was a saint, and had overcome the temptations of the world.
I said, what I am, it is by grace.
I have nothing to boast of, and by grace I am saved out of many temptations of the world;
yet was a man of like passions, and liable to many weaknesses, as they were;
and was no longer safe than while I kept upon my watch.
My mind was opened to point out to them the way of salvation;
Scripture being brought to confirm the sufficiency,
work and operation of the grace of God upon the hearts of the children of men,
with the saving help there is in it, as obedience is yielded, unto it.

--

He had his quarters in a tavern at Morlaix in France for several days,
subjected to much company of various sorts.
Appearing singular to them, they wished to know what he was,
and those who could speak English, would ask questions,
to which he gave answers as he found freedom.
As he was sitting in a room, one of the company asked why Quakers would not fight?
"`I told him,`" said William, "`the weapons of the primitive believers were not carnal,
but spiritual, and mighty through God,
to the pulling down of sin and the strongholds of Satan;
and such as now come under the peaceable government of the great King of kings,
who said if his kingdom had been of this world, then his servants would have fought,
cannot fight with carnal weapons,
though there should seem as great a necessity as there was
when our Lord was likely to be delivered to the Jews.
I had to open several passages of Scripture,
which set forth the peaceable government of Christ, who came not to destroy men`'s lives,
but to save them; and that it was not the lamb`'s nature to tear and devour,
but the wolf`'s. This opportunity was seasonable;
the people were very still and attentive.
He that asked this question, had often been with me, and had asked many questions,
but was now silent, and seemed to go away satisfied;
for the power of God was over them at that time.`"

W+++.+++ Reckitt was ordered with other prisoners into the country, about thirty miles,
to a town called Carhaix.
Charles Sermanson supplied him with money, and recommended him to a friend of his there,
John Grace, a counsellor at law, who, during his stay,
showed several tokens of his regard and hearty friendship, after they became acquainted.

The counsellor became very loving, and frequently had our Friend at his house,
with whom he conversed on religious subjects.
He said he understood Friends did not baptize with water.
William replied:

[.embedded-content-document.letter]
--

The apostle says: "`There is one Lord, one faith and one baptism;`" and water, how,
or by whomsoever administered, is only sufficient to put away the filth of the flesh,
but not able to wash away the sin of the soul.
The same apostle also said, he was not sent to baptize,
(he there must be understood with water,) but to preach the Gospel,
which is the power that baptizes into the one spirit.
He was not a whit behind the chiefest of the apostles,
yet he thanks God he had baptized no more than the few he recites,
which he would not have done,
if baptism with water had been the one baptism essential to salvation.

He said he thought there ought to be something done to children
by the minister to initiate them into the church.
I said as to our not being in the practice of sprinkling children with water,
or signing them with the sign of the cross, as it was not scriptural,
we could not be justly blamed for the disuse of it.
He then said, if he at first had put on the priest`'s gown instead of that he then wore,
he should have thought it his business to search more into the Scriptures.
I told him I took him to be a man of such understanding,
as very well to know it ought to be everyone`'s business
to search into the things that belong to their own peace.
He said it was true, but they had men who were learned, whom they paid,
and he looked upon these to be his teachers; as for him, he was but a hearer,
and if they deceived him,
it would be the worse for themselves--they could not deceive God.
I said it was true, they could not;
but as the salvation of the soul is a thing of great importance,
we should not place our dependence upon others; and as to teachers,
we might know them by their fruits; for, according to Christ`'s own words,
"`Men do not gather grapes of thorns, or figs of thistles.`"
He further says to his ministers: "`Freely you have received, freely give.`"

--

Hearing that the commissary had uttered some bitter expressions against the Quakers,
and him in particular, for not putting off his hat when they met in the street,
he inclined to visit him, and took with him a young man to interpret for him.
The commissary took them into a room, and before William could say anything to him,
asked why he did not put off his hat.
He replied,
uncovering our heads was what we did when we prayed and addressed the Almighty;
but to do it to our fellow creatures was against our consciences.
The answer, though short, appeared to satisfy him, for his haughty countenance fell,
and he then spoke mildly, and said he had heard we did not baptize our children.

[.embedded-content-document.letter]
--

I said we did not use water baptism.
"`What do you then,`" said he "`instead of water?`"
I said the one baptism, which we believe to be essential to salvation,
is spiritual that of fire and the Holy Spirit; and as to little children,
they are heirs of the kingdom of heaven without water, or the help of any mortal man.
I told him I had heard he said something against me,
but I came in good will to pay him a friendly visit,
for I had a mind to speak with him by myself.
He then took me by the hand, saying he would not do me any hurt,
but all the service that lay in his power.
I took my leave of him with thankfulness that Truth had thus far prevailed;
and ever after when I met him, he looked pleasantly,
and I believe never any more took offence at my hat.

--

About the middle of the eighteenth century,
Friends of Pennsylvania were brought into much difficulty and mental
distress by the breaking up of the peaceful relations that had
always before existed between that colony and the Indian natives.

The visit of Samuel Fothergill to Friends in Pennsylvania,
occurred at a time when his fervent labors and weighty counsels
were peculiarly acceptable and serviceable to the right-minded.
Although he was in America but about twenty months, yet,
during this comparatively short period,
a series of events occurred which produced a crisis in the affairs of this province,
followed by an entire change in its administration and policy.
Soon after his arrival, in 1754, as stated by Ellen Evans in a letter to his sister,
Samuel Fothergill was led to deliver to a large auditory in Philadelphia,
a "`close prophetic warning of approaching trials,`" at a time "`when
not so much as a handbreadth of cloud appeared over our land.`"
These trials soon appeared in the outbreak of a protracted war with the French,
in which the martial spirit was fanned into a blaze throughout the community;
the maintenance of the testimony of the Society against all wars was brought
into great jeopardy through the unfaithfulness of many of its members;
destruction and bloodshed spread upon the frontier of the province,
and the powers of the government passed under the control of men and measures
totally at variance with those pacific principles and that trust in the
protecting Arm upon which it had been originally settled.

The same Almighty power which, in great mercy, had condescended to warn the people,
and prepare his servants for approaching trials,
did not forsake them in the time of danger and of conflict.
Though through much open opposition and reproach,
both from within and without the professing church,
a body of true Friends was preserved faithful to their religious principles and testimonies.
The writings of many of the Friends of that period which have been preserved to us,
bear ample evidences of the exercises which befell them and the Society in this storm,
which threatened to unsettle the foundations of the government itself.

The public affairs which led to this change in the condition of the province,
may be briefly stated: Shortly after the treaty of Aix-la-Chapelle,
in which the boundaries of the British and French possessions in America were left unsettled,
the French began to erect a chain of forts along the western limits of the colonies,
with the intention of connecting Canada with their settlements on the Mississippi.
Fort du Quesne, on the present site of Pittsburg,
and other military posts in Western Pennsylvania, were established in 1753 and 1754,
in pursuance of this policy, and under a claim made by the French to that region.
This claim was disputed by Virginia in the interest of her Ohio Land Company,
and in 1754 an engagement took place, near the Monongahela,
between the French and a body of provincial soldiers under Washington,
in which the latter were obliged to withdraw.

The British government, upon learning of these movements,
entered into negotiations with the court of Versailles,
meanwhile secretly dispatching an armed force, consisting of several thousand men,
under general Braddock, to Virginia.
The appointment of Braddock as generalissimo of the British forces
in North America was made on the twenty-fourth of Ninth Month,
1754, the day upon which Samuel Fothergill arrived in Philadelphia.

The main body of Braddock`'s forces landed in Virginia in the Third Month, 1755,
and were joined by others from different parts of the colonies.
The first foreign military that ever entered Philadelphia were connected with this expedition.
Catherine Payton, who was then in that city, remarks in her Journal,
in reference to the entry of these soldiers: "`I said a cloud of darkness came with them.
The Lord had settled this colony by peaceable means;
He has hitherto protected it by his own Almighty arm, and it prospered greatly,
but henceforward disunion and disturbance prevailed and increased in it.
Our friend Samuel Fothergill, as well as we,
were strongly and affectionately engaged to promote peace,
and guard them against the event which he feared would ensue, and which, in time,
followed.`"

The alarm produced by the unexpected defeat of Braddock`'s army, in the Seventh Month,
1755, was extreme;
and upon its retreat the country was left open to the incursions of an enraged enemy.
The general alarm was increased by the defection, at this time,
of many of the Shawnees and Delaware Indians,
whose early feelings of friendship towards the inhabitants
of Pennsylvania had become alienated by acts of injustice,
and who were now induced by the French to take up arms against the English.

Although open hostility had thus been shown by bands of the Shawnees and Delawares,
it was yet hoped that,
through the well-known influence of the Six Nations with these Indians,
a stop might be put to their devastations, and their friendship regained.
With a view of promoting such a reconciliation,
Friends addressed an earnest remonstrance to the governor
to withhold a formal declaration of war against them,
until "`Whatever remains possible to be done to prevent so fatal and lamentable an extremity,
may be strictly and impartially reviewed and considered,`" and "`that
the governor`'s care to guard against involving the innocent with the
guilty may carry so clear a demonstration of Christian tenderness,
and aversion to shedding blood,
that an evidence may be given to the minds of the other neighboring Indians,
which may engage them heartily and sincerely to assist in
the desirable work of restoring peace and tranquillity,
towards which all the measures hitherto taken seem to have contributed little good effect.`"

This appeal, however, was unavailing.
In the spring of 1756 governor Morris, with the advice of his council,
issued his proclamation,
coupled with the inhuman promise of reward for the scalps of the enemy.

Friends were earnest in their efforts to effect a restoration of peace,
and to put a stop to the war and bloodshed.
To promote these objects,
many of their prominent members joined in organizing "`The Friendly Association
for Regaining and Preserving Peace with the Indians by Pacific Measures.`"
They raised large sums of money,
which were expended principally in the purchase of clothing,
given as presents to the Indians.
They early took measures to examine into the justice of the claims of the Indians,
and attended the different conferences held with them by the government.
Difficulties were put in their way,
owing to the jealousy with which their proceedings were viewed by the government,
but the confidence placed in them by the Indians,
rendered their labors very serviceable in the restoration
of peace at the treaty held at Easton,
in 1756, with Tedyuscung, king of the Delawares.

The influence of Divine Grace upon some of the Indians present at the
treaty is referred to in an interesting manner by the committee,
in a report made on their return to Philadelphia.
Under date of Eleventh Month 17th, they say:

[.embedded-content-document.letter]
--

Tedyuscung and most of his people came down to the ferry-house and dined with us;
before parting with I. Zane and I. Pemberton, he took them aside and told them +++[+++that]
in conversation after dinner, a few days before,
he found what was said to him went to his heart,
and that he now found his heart affected; and,
his speaking being interrupted by a flood of tears, after retiring a little,
he told them that, in the course of this business, he had endeavored to +++[+++be]
turned in his mind, and look up to God for direction;
that when he was alone in the woods, and destitute of any other counsellor,
he found by doing so he had the best direction;
that he hoped God would bless our endeavors, and desired to be remembered by his friends.
He followed to the boat,
and was so much affected he could only by tears express his respect, which,
as it appeared to be the effect of a Divine visitation to a savage barbarian,
was a humbling scene,
and excited reverent and thankful sentiments in the minds of those directly observing it.

--
