== Chapter XVIII. Biographical

The early members of the Society of Friends were very jealous for the honor of Truth,
and not only by word of mouth,
but with the pen "`Contended earnestly for the faith`" they had received.
The literature they have left is very voluminous.
Among the works they produced,
perhaps none have been more valued and been more effective
than [.book-title]#The Apology for the True Christian Divinity,
As the Same is Held Forth and Preached by the People, in Scorn, Called Quakers.
Being a Full Explanation and Vindication of Their Principles and Doctrines,
by Many Arguments Deduced From Scripture and Right Reason,
and the Testimonies of Famous Authors, Both Ancient and Modern.
With a Full Answer to the Strongest Objections Usually Made Against Them.#
By Robert Barclay.

Almost from its first publication,
this book has been received by Friends as an authoritative
statement of the doctrines most surely believed among them,
and has been reprinted and distributed from time to time,
so that if any of their number should now reject its authority,
it would be no breach of charity to say that they
themselves had ceased to hold the doctrines of Friends.

A writer in the _Westminster Review_ speaks of it as a "`master-piece,
both in style and manner, among the richest gems of our language.`"
One of the most learned bishops,
when asked by a foreigner to recommend to him a systematic
work in the English language on Protestant Theology,
told him that he knew of none, unless it were [.book-title]#Barclay`'s Apology for Quakerism#.
"`And truly, to anyone wandering in the dreary waste of polemics of this age or that,
it would be a pleasant place to alight upon.
A complete proficient in the learning of the school-men,
he wields their weapons with wondrous skill,
to destroy the empire which they had so long held over men`'s souls,
and he defends the Truth with a chivalrous devotion, and courtesy to his opponents,
reminding us of the Norman knights from whom he was descended; and,
mingling with his eloquence and skillful logic,
we ever hear a strain of such pure and heartfelt piety as touches
our hearts fully as much as it pleases our fancy and our reason.`"

The Journal of Joseph Wood mentions the convincement
of several persons through the agency of [.book-title]#The Apology#.
It says:

The day after the Quarterly Meeting held at Leeds, Joshua Priestman, of Pickering,
breakfasted at the same Friend`'s house as myself.
On inquiring of him concerning a certain young man
I had particularly noticed in the meeting,
he told me he was a member of their Monthly Meeting,
and that his name was Richard Finnies Foster; that he came out of the south,
and had settled at Scarbro; that he had joined Friends by convincement,
and had appeared acceptably in the ministry, and related the following occurrence,
which I have put down as nearly as I can remember, namely: That Dr. Southam,
of Buckingham, a man eminent in his profession,
by which he had acquired considerable property, took a journey for pleasure,
with his wife, to London.
During their stay there they attended a play,
in which was acted "`The Quaker,`" with which the doctor was much affected.
At the close of the performance the principal manager observed to the company that,
if anyone was desirous to know more of this singular body of people,
he would recommend them to read [.book-title]#Barclay`'s Apology#.

Accordingly, before he left London, the doctor privately purchased that work,
and when he got home hid it in his study,
where he employed his leisure time in diligently perusing it.
His wife, very soon perceiving a visible alteration in him,
and having taken notice that he spent more time than usual in his study,
wondered what was the cause.
Whereupon, taking the opportunity when he was from home, she carefully examined the room,
and found the [.book-title]#Apology# therein, which she began to read,
and continued to do so at such times as her husband was absent.
The consequence of which was that,
by turning their minds to that Divine principle of
light and life which comes by Jesus Christ,
and is placed in the secret of every heart,
they were both convinced of the truth as professed by the Society of Friends,
and in time they found strength to make public profession of the same.

About the same period, Richard F. Foster`'s brother Oswald,
who was an apprentice with Dr. Southam, had finished his time,
and went to London for further instruction.
The doctor, having a great deal of business,
had proposed at Oswald`'s return to take him into partnership.
Before the latter reached home he heard of the doctor and his wife having become Friends,
at which he was very much surprised:
but being determined to let them know that he was not one,
when he entered the house he began to whistle and sing,
and passing through the lobby by the sitting-room door,
he went directly into the kitchen,
where he was very much struck with the visible alteration
he observed in the countenance of the maid-servant,
and thus accosted her: "`What, Betty, are you all turned Quakers?
But I will not be one, however.`"
But in a short time he was also favored with a precious visitation of Divine grace,
and became clearly convinced of the Truth as professed by Friends.

The said Richard F. Foster, hearing that his brother Oswald was turned Quaker,
lightly said: "`I shall quake also when cold weather comes.`"
The same Divine power however soon after reached unto him, and caused him to bow thereto,
bringing him into a state of willingness to confess
Christ before men (after the manner of Friends);
and about the same time his brother John, resident at some distance,
was convinced of the truth of Friends`' principles,
without having any previous conversation one with another.
Thus were six persons in rather a remarkable manner convinced
and brought to the acknowledgment of the Truth,
as laid down in [.book-title]#Barclay`'s Apology#,
and became valuable members of the Society of Friends.

The following testimony to the efficacy of the Holy Spirit,
and also to the value of [.book-title]#Barclay`'s Apology#,
is extracted from a letter dated Twelfth Month 24th, 1834, from Deborah Cope,
then travelling with Dugan and Asenath Clark, in New York and New England meetings,
and addressed to Sarah Emlen:

We paid Moses Brown a visit, who enquired affectionately for you, and desired his love;
he says you may come back to N. E., and he, for one, will be glad to see you.
It was really a feast to be in his company;
he still seems green in his ninety-seventh year.
He had just received a letter from a young man, with whom we afterward were in company,
one in and for whom we feel a deep and sincere interest.
He belonged to the Baptists,
and had spent three years at college preparing to be a missionary;
got through his studies with good reputation,
and was considered of much more than ordinary capacity by the professors in the Institution:
is said to be master of eleven languages.
He returned home to his father;
but no call offering which they considered equal to his talents,
his father prevailed on him to return to the college for six months more, which he did;
and while ransacking the library one day, in quest of something to amuse,
he lighted on [.book-title]#Barclay`'s Apology#, an old, dusty volume, in French.
He bore it off to his study and read it attentively, and was met in a narrow place.
He became very thoughtful,
and asked one of the professors one day if there were any people now living,
holding the faith of Robert Barclay, and was answered, "`No;
that was only an old controversial book,
which they kept to show the reasoning and arguments which could
be advanced by those who once professed such principles.`"
"`Well,`" said G+++_______+++, "`it is such reasoning and arguments as I never met with before;
I must set out and see if I can find any such people; and if not I must sit down alone.`"
Accordingly he went to S+++_______+++ and made inquiry, and was directed to H. C.,
a very suitable Friend.
He knocked at the door, and H+++_______+++ opened it;
whereupon G+++_______+++ inquired if there were any now living,
professing the faith of Robert Barclay.
H+++_______+++ smiled and said he hoped so, and invited him in.
They had much conversation, and G+++_______+++ repeated his visits.
His father was now displeased, and his friends disappointed,
and they reported that he was deranged; but G+++_______+++ persevered until he became a member;
attended last Yearly Meeting, and promises to be a consistent one.
The following is an extract from his letter to Moses Brown,
and will speak his own language:

This is a letter wiuthin a block quotation, so mark up differently in Jones:
"`At last my mind became so exercised that I was constrained to leave
the Institution in quest of a people who believed in [.book-title]#Barclay`'s Apology#,
and if I could not find such a people I determined to worship the Lord alone;
but blessed be God,
the Lord has still a remnant who are not conformed
to the vain and wicked fashions of this world.
To this people I desire to join myself, though I feel most unworthy to come among them.
Yes, I can say with the pious Barclay,
that having for a long time been seeking after human learning,
I have found that Heavenly learning which gives content to the soul;
after this learning may I seek forever.
I now believe that though a person may read the Bible ever
so carefully and critically in the original languages,
yet, the most unlettered person under the teachings of the Spirit of God,
is more able to have a true understanding of it,
than the learned man with all his critical care and study;
and though I myself have read the whole Bible in Hebrew (except the book of Daniel);
although I have read the New Testament critically in Greek and Syriac,
and have studied the Bible in several other languages; yet the most ignorant man,
who is really taught of the Spirit, can understand the Bible better than I can,
unless taught of the same Spirit.
And oh!--that all who may read this letter might
feel the necessity of being taught of God,
of sitting as little children at the Saviour`'s feet,
and learning of him who was meek and low of heart.

Farewell,

G+++.+++ W. R.

Sir James Mackintosh, in his [.book-title]#Revolution in England#,
designates [.book-title]#Barclay`'s Apology# "`a master-piece of ingenious reasoning,
and a model of argumentative composition, which extorted praise from Bayle,
one of the most acute and least fanatical of men.`"

The secretary to count D`'Estaing,
the French admiral on the American coast in the Revolutionary war,
after reading [.book-title]#Barclay`'s Apology#, returned it to the owner,
thanked him for the loan of "`that good book,`" and said: "`It is an excellent book;
it is all very true, but it is too tight.`"

On the above testimony, William T. Robinson, of New York, remarks:
"`And here lies the difficulty,
the rock on which most of those who are awakened
to a concern for their everlasting welfare,
split and are irrecoverably lost--as Christ, when on earth, said,
'`Many are called but few chosen`' and the reason is, the cross stands in the way,
which very few are willing to take up and endure--preferring the gratification
of their propensities in following after the beauty and pleasures of this world,
and so waste their time and talents in unproductive idleness.`"

The writer of the life of Robert Barclay, in the [.book-title]#Biographia Brittanica#,
makes the following observation respecting his celebrated Apology
on behalf of the Quakers.--"`A very curious and instructive work,
in which he with much solidity and perspicuity lays open the causes,
and displays the consequences, of superstition, on the one hand,
and fanaticism on the other, clearing the Quakers from both.`"

John Norris, M. A., of Oxford,
a minister and esteemed writer of the "`Church of England,`" who died in 1771,
and who is described in the [.book-title]#Biographical Dictionary# as "`a very pious, learned,
and ingenious man`" (and therefore his opinion respecting the views of Friends,
ought to have weight with their opponents,
and offer an inducement to honest inquirers to read their Apology),
in his treatise "`on Divine Light,`" makes this acknowledgment.--"`I
cannot think Quakerism inconsiderable,
as the principles of it are laid down and managed by Barclay.
That great and general contempt they lie under,
does not hinder me from thinking the sect of Quakers to be far the most considerable
(in the weight of their arguments) of any that divide from the church,
if the Quakerism that is generally held be the same
with that which Barclay has delivered to the world,
as such; whom I take to be so great a man, that I profess freely,
I had rather engage against a hundred Bellarmines, Hardings, and Stapletons,
+++[+++learned men and controversial writers], than with one Barclay.`"
Norris further declared of Barclay,
that he knew of no religion so rich in reputation for great men,
but might be glad of the accession of such a writer.

In truth, to adopt nearly the words of a candid writer,
"`Robert Barclay`'s qualifications for controversial labor were unusually eminent;
being not only master of useful literature, but of a clear comprehension,
a capacious reach of thought, a close and convincing manner of reasoning,
delivered in a forcible style, though plain and unaffected.
The excellency of his temper, heightened by the influence of religion,
preserved him in coolness, that his judgment was not blinded by any degree of passion;
while his regard to undisguised truth prevented him
from flattering error or excusing calumny.
His enlightened mind penetrated to the bottom of his subject,
and this imparted a clearness of method which, with the weight of his arguments,
proved him an over-match for his antagonists.`"

A writer in an early periodical of the last century ([.book-title]#Cato`'s Letters,
or Essays on Liberty, Civil and Religious#, 1720) observes:
"`I am not ashamed to own that I have, with great pleasure,
read over [.book-title]#Barclay`'s Apology for Quakerism#,
and do really think it to be the most masterly, charitable,
and reasonable system that I have ever seen.
It solves the numerous difficulties raised by other sects,
and by turns thrown at one another;
it shows all parts of Scripture to be uniform and consistent.
If we allow Barclay those operations of the Spirit, which the Quakers +++[+++testify of],
and which, he says,
every man in the world has and may feel if he watches
its motions and does not suppress them,
then, I think, all the janglings, vain questions, numerous superstitions,
and various oppressions, which have plagued the world from the beginning,
would cease and be at an end.`"

The following lines were addressed, by Richard Peters,
a clergyman of the Protestant Episcopal Church in Pennsylvania, to Anthony Benezet,
who had loaned him [.book-title]#Barclay`'s Apology#.
It was understood that R. Peters, previously to his perusal of Barclay,
had entertained and expressed unfavorable opinions of the Quakers and their principles:

For Barclay`'s learned Apology, is due
My hearty thanks and gratitude to you.
The more I read, the more my wonder`'s raised,
I viewed him often, and as often praised.
Commanding reason through the whole design,
And thoughts sublime appear in every line.
Sure some diviner spirit did inspire
His pregnant genius with celestial fire.
Long had I censured with stupendous rage,
And cursed your tenets with the foolish age,
Thought nothing could appear in your defence,
Till Barclay shined with all the rays of sense.
His works, at least shall make me moderate prove,
And those who practise what he writes I`'ll love.
With the censorious world, no more I`'ll sin
In damning those who own the light within.
If they can see with Barclay`'s piercing eyes,
The world may deem them fools, but I shall think them wise.

The esteem in which the author of this valuable treatise was held by his friends
is shown by the testimonies respecting him left by George Fox and William Penn.

George Fox bears the following short but comprehensive
testimony respecting his "`dear brother in the Lord,
Robert Barclay:`" "`He was a wise and faithful minister of Christ,
and wrote many precious books in defence of the Truth, in English and Latin.
He was a scholar and a man of great parts, and underwent many calumnies,
slanders and reproaches, and sufferings for the name of Christ;
but the Lord gave him power over them all.
He travelled, often, up and down Scotland, and in England, and in Holland and Germany,
and did good service for the Lord; was a man of repute among men,
and preached the everlasting Gospel of Christ freely,
turning people from darkness to light, and from the power of Satan unto God.
Much more,`" he adds,
"`might be written concerning this faithful brother
in the Lord and pillar in the church of Christ,
who was a man I very much loved for his labor in the Truth.
The Lord raise up many more faithful laborers to stand in his place.`"

The sterling quality of Robert Barclay is, perhaps,
best delineated by his contemporary and faithful friend, William Penn,
who thus describes him:

He was distinguished by strong mental powers, particularly by great penetration,
and a sound and accurate judgment.
His talents were much improved by a regular classical education.
It does not, however,
appear that his superior qualifications produced
that elation of mind which is too often their attendant.
He was meek, humble, and ready to allow others the merit they possessed.
All his passions were under the most excellent government.
Two of his intimate friends, in their character of him,
declare that they never knew him to be angry.
He had the happiness of early perceiving the infinite
superiority of religion to every other attainment;
and Divine Grace enabled him to dedicate his life and all that he possessed,
to promote the cause of piety and virtue.
For the welfare of his friends, he was sincerely and warmly concerned;
and he travelled and wrote much, as well as suffered cheerfully,
in support of the Society and principles to which he had conscientiously attached himself.

But this was not a blind and bigoted attachment.
His zeal was tempered with charity,
and he loved and respected goodness wherever he found it.
His uncorrupted integrity and liberality of sentiment,
his great abilities and the suavity of his disposition,
gave him much interest with persons of rank and influence;
and he employed it in a manner that marked the benevolence of his heart.
He loved peace, and was often instrumental in settling disputes,
and in producing reconciliation between contending parties.
In private life he was equally amiable.
His conversation was cheerful, guarded and instructive.
He was a dutiful son, an affectionate and faithful husband, a tender and careful father,
a kind and considerate master.
Without exaggeration,
it may be said that piety and virtue were recommended by his example; and that,
though the period of his life was short, he had, by the aid of Divine Grace,
most wisely and happily improved it.

The death of this worthy man was a fitting close to his life.
In the year 1690 he was seized with a violent fever.
On his deathbed he was in a truly peaceful, resigned and Christian frame of mind.
He expressed his love to all faithful Friends in England,
and to all the faithful everywhere, particularly to Friends in Cumberland,
and to George Fox, for whom he had a special regard;
and concluded with these memorable expressions: "`God is good to all;
and though I am under a great weight of sickness and weakness, yet my peace flows.
This I know, that whatever exercises may be permitted to come upon me,
they shall turn to God`'s glory and my salvation, and in that I rest.`"

Samuel Fothergill, the third son of John Fothergill,
was endowed with a strong understanding, and with an active and lively disposition.
He was apprenticed to a shopkeeper in Stockport,
at which place he fell in with evil and dissolute companions,
who enticed him into a course of folly and dissipation.
He had pursued this wicked life till he was now near the twentieth year of his age,
in despite of the counsel and warning of his excellent father, who,
when about to embark on his third visit to North America,
took leave of him in this solemn and awful language: "`And now, son Samuel, farewell!
Farewell!
And, unless it be as a changed man,
I cannot say that I have any wish ever to see you again.`"
Samuel Fothergill had not pursued his downward course without strong compunctions
and frequent resolutions to forsake his evil ways--and now,
loaded with the heavy rebuke of his venerable father--to whom his revolt from the Divine
law had been a source of the keenest anguish--he once more resolved on a change of life,
and, through Divine mercy, was happily enabled to effect it.

How strong were his compunctions,
how deep his contrition and how great his change of heart,
may be learned from a letter he addressed to the Monthly Meeting:

Dear Friends:--It has lain heavy upon me for some time to
write a few lines to you upon the following subject:

The Lord Jesus Christ, in his everlasting kindness, that has long strove with my soul,
has been pleased to unstop my deaf ear, that I might hear Him, the Shepherd of his flock,
and to open my blind eyes, and let me see my state as it really was,
very desperate and very lamentable.
He has shown me the dreadful precipice I was at the brink of,
and breathed into me the breath of life,
in order that I might arise from the dead and live.
He has set my sins in order before me, and shown me how I had estranged myself from Him,
raising strong desires in me to return to Him, the Redeemer of my soul.
The consideration of which has raised in my heart a just abhorrence of my former practices,
that induces me to make this public declaration of them,
which I desire to do in a few words.

When Rebecca Hubbs, of New Jersey, had come under the government of Christ,
she felt a call to declare unto others what the Lord had done for her soul.
Being among the poor of this world, and very illiterate,
she felt much discouragement at the prospect.
While these struggles were going on in her mind,
she went one day into the village of Woodstown, with her husband,
and was sitting alone in the carriage at a store-door,
when a man looked into the front of the carriage, saying.
"`I do not know what your name is; but I must speak a little to you.
The Master has a work for you to do, if you are faithful to it.
I want to tell you not to plead, as Gideon did, '`My family is poor in Manasseh,
and I am the least in my father`'s house.`' This
was Gideon`'s excuse--don`'t let it be yours;
I want you to be faithful--be obedient.`"

This unexpected salutation from an entire stranger,
one who could not know her secret plunges and discouragements, had an animating effect,
and quickened her diligence.
The individual who thus unexpectedly spoke so suitably to her case,
was that worthy minister, the late Arthur Howell, of Philadelphia,
who had been attending the Quarterly Meeting of Salem.
In the Journal of William Williams, the following interesting incidents are entered.

Now I think proper to relate a circumstance which took place as I was travelling,
which was as follows:

I was alone, and put up at a professor`'s house, to lodge.
After I had been in the hall a little while, the landlord asked to be excused,
and walked out to order his evening business, so that I was left alone,
which gave me a better opportunity to hear what passed in an adjoining room,
where one of the company raised her voice in singing
praises to her Maker (as she called it),
and after a very short line it broke off into very loud laughter.
The singing then commenced again, and then the laughter, and so on for four times;
so that I thought that I should be under the necessity of telling them my thoughts,
if I should get an opportunity.
Supper was soon set in the hall, and they were invited to sup,
whereupon the landlady and five young women came in, and we sat down and supped.
After we were done, before we left the table, I brought on the discourse I wished,
by observing to the landlady that I hardly thought these were all her daughters.
She answered that two of them were her daughters, and the other three were neighbors,
who had come on a visit.
I thought I could mark out the singer; so I spoke and said,
"`It is likely I may give you reason to think that I am a meddling traveller,
for I have some remarks to make to you, from what I have heard since I came here.`"
I then told them what I had heard as above related.
I told them not to misunderstand me, for I was not speaking against praising their Maker,
if it was done with the Spirit, but against its being interrupted by loud,
unbecoming laughter;
a thing that ought to be beneath the dignity of so noble beings as they were,
at any time, much more when engaged in that exercise.

I told them, it brought to my remembrance the words of the apostle,
where he was speaking of the unruliness of the tongue, with which, says he,
"`We bless God and curse men;`" "`these things ought not to be so,`" said I,
"`these things ought not to be mixed together.`"
When I was done, the noble young woman whom I had marked out in my mind, spoke and said,
"`I thank you kindly, sir, for your rebuke.
I am the very one, and I knew I was doing wrong when I did it; yes,`" said she,
"`there was something here`" (clapping her hand on
her breast) "`which told me that it was wrong.`"

The landlord then took up the subject, and said something on the imperfection of man,
but I do not recollect what he said, nor what I answered;
but my answer was such that he said no more.
The young woman then observed that the leprosy was out of the power of man to cure.
I said it was;
but did she not think that Christ was as able to
heal the leprosy now as He was when here on the earth?
She said He was.
"`But,`" continued she, "`we read that it gets into the wall;
then the wall has to be taken down and rebuilt before it can be cleansed,`" and this,
she said, was a great work.
To which I agreed, and asked if it was not a necessary work to salvation.
She said it was.
I asked if she did not think it was a possible work
through the assistance of the spirit of Christ.
After a solemn pause, she said it was.
So I told her, if we have a great work to do, and a necessary work,
it is never too soon to begin, in faith, to do it.
To which she acknowledged, and was silent.

Then I took the opportunity, in a few words, to open to her and the rest,
that to do this work, was to attend to that in the breast,
which tells us when we do wrong.
"`For instance,
if you`" (directing my discourse to the young woman)
"`had attended to that within at the first,
perhaps you would not have been overtaken in the first breach of good order,
much less to have repeated it.
For that which spoke in your breast and told you that you were doing wrong,
was Christ within, the saints`' hope of glory,
who has descended into the hearts of the children of men,
in order to heal them and cleanse them from all sin and leprosy,
and make them a pure people,
and enable them to praise God in humility of spirit and purity of mind.
Then this degrading thing of loud laughter would be far from our minds,
and we should be preserved from being overtaken by that fault,
as well as by all others.`"

We then rose from the table, and it was taken into the other room.
As soon as this was done, the landlord spoke to me and said,
"`I perceive that you are a minister,
and we perform what we believe to be our family duty, and do much desire you,
if you please, to go forward in it.`"
I said I did not think it would be right for him to give
such liberty to strangers who put up at his house,
although they might appear with fine words; for, if he did,
he would lay himself liable to be imposed upon.
More than that, I told him that we, as a people,
did not believe that we could perform such things at our own stated times.
At the same time,
I did not wish to put them out from what they did believe to be their duty,
and was willing to be with them, and hoped I should join in anything that was good.
So they went through their performances,
after which the women withdrew to the other room,
and the landlord pretty soon spoke of going to rest.
I said I was ready to lie down,
so he stepped to the door and called for a candle to light me to bed.

When these young women heard this, they all came in again,
and the young woman whom I have mentioned before, spoke as for all, and said,
"`You are a traveller, and will, likely,
be up and gone in the morning before we shall come down from our chamber;
and we thought we could do no less than to come in and take our solemn leave of you,
and once more thank you for your advice and counsel,
hoping we may never forget it nor you.`"
So said they all, as they bid me farewell, with tears flowing from their eyes,
which they did not try to hide, for the Truth had tendered their hearts.
So we parted in great tenderness and love.
Oh, that people would attend to that which teaches within,
so that they might become the children of light, and dwell no longer in darkness;
for as many as are led by the Spirit of God are sons of God; and God is light,
from whom comes that which teaches within,
being the true light that gives light to everyone that comes into the world,
which is the Spirit of God, which leads up to Him, and enables us to become his children.

William Williams, of Tennessee, says in his Journal:

I think proper to relate here, a singular circumstance concerning a little girl,
whose father rode sometime with me, when I was first in the State of New Jersey,
and at whose house I lodged the night before I left that State to go to New York.
The child was then under eight years of age.
I had a sitting in the family, which was a watering time,
for the presence of the Master was to be felt,
and the dear little daughter (as well as I remember,
the youngest of a large family) was tendered,
and felt her mind much attached to me in tender love,
which I was sensible of at that time.
This was in the Fifth Month, 1811,
and as I returned from the eastward in the Sixth Month,
I sent for some linens which I had left there, and when I opened them,
I found a small present, from this child to my little daughter at home,
whom I had told her of.
On the eighth day of the Second Month, 1813, I left home again,
and in the course of this visit also, I got to her father`'s house; and when I got there,
I soon looked for the little daughter, but saw her not.
I then asked for her,
and saw the tears start in the eyes of her mother at the hearing of her name.
We sat awhile in solemn silence, and I spoke and said: "`Is the child gone to rest?`"
She said: "`She has;`" and then told me about her latter end,
which I thought I would then write; but I put it off at that time,
yet it made so deep impressions on my mind, that it could not be erased.

The child was taken sick,
and in a little time afterwards she told her mother
that she should not live to get well again,
but should die; and her mother asked her if she was willing to die.
She said there was but one thing that she wanted;
that was to see that Friend who was from Tennessee; "`If I could only see him once more,
and hear him, I should be willing then to go to my heavenly Father,
and leave all my dear friends behind;`" and thus she continued for many days,
often saying: "`O heavenly Father, I am willing to die, and come to you,
yet I wish to see that endeared Friend and hear him preach to my father and mother,
and to my brothers and sisters, if it be your holy will, O Lord!
But not my will be done.`"
And one day as her mother was sitting by her bed with another friend, Mary lay still,
as though she was asleep or in a doze, for an hour or more; then she stirred,
and her mother asked her if she wanted anything (meaning drink or any refreshment),
she said: "`No, she wanted nothing but to die,`" and added:
"`I have wanted to see dear William Williams, but I shall not see him, but shall die;
you will see him.`"
"`O, no, Mary,`" her mother said, "`he lives a great ways from here.`"
"`That matters not, he is on his way now, and in time he will be here in this land,
and you will see him and hear him; and then give my love to him, and tell him,
I go to my Father and his Father, there to wait for his coming.`"
So, on the next day she quietly departed this life, when I was in Virginia,
on my way to these parts.

=== Copy of a Testimony of William Williams, Who Departed This Life About the First of the Ninth Month, 1824, Delivered About a Week Before His Death

It is well known to many on our continent that I have lived an active life,
in which I have not believed in,
neither followed cunningly devised fables or the rudiments of men,
neither human reason alone;
but I have believed in the doctrines of the glorious
Gospel of our blessed Lord and Saviour Jesus Christ,
as they stand recorded in the Scriptures of Truth,
and not because they stand there alone,
but the spirit of God bears witness with my spirit, that these things are true.

This doctrine have I believed from a child,
and when I became obedient to the manifestations of Divine grace in my own heart,
given to me and to all men to profit withal,
I was called upon to publish the same to the sons and daughters of men,
to which call I became obedient, conferring not with flesh and blood,
but trusting to his Divine promise,
that He would be with his followers to the end of the world;
which promise I found to be fulfilled,
so that through his aid and assistance I have been
enabled to go forth among all sorts of people,
and to publish his Gospel in large and mixed assemblies,
where there were many and various minds; the power accompanying the Word,
so that the mouths of gainsayers were stopped,
and the minds of the unbelievers were shaken, so that none dare oppose me openly.
Yet the unbelievers in Christ often talked behind my back, calling me a liar,
a fool and many other things, and that I would alter my mind before I died;
and as I have now been confined to my chamber and bed fifteen months,
wherein I have had great opportunities to consider and reconsider,
and now feeling that my close is drawing near,
for the comfort of my well-wishers everywhere,
and for the stopping of the mouths of the gainsayers;
I give this forth as my last testimony to the glorious Gospel of Christ,
that my mind has become in my silent meditations more and
more strengthened in faith to believe in God,
in his dear Son Jesus Christ, and in his glorious Gospel.
I have become deeply exercised from day to day on account of the disobedient and unbelieving,
seeing the awful situation that they are in, and will unavoidably centre in,
if they do not come to return, repent and live.
"`Verily there is a reward for the righteous;
verily there is a God that judges in the earth.`"
Now to the glory, to the honor and to the dignity of that God in whom I have believed,
be it ascribed, that I feel no condemnation, but that my soul is enabled to sing:
"`O death!
Where is your sting?
O grave!
Where is your victory;`" and this not in the dark,
but under the influence of the inshining light of the ever blessed Gospel,
wherein I may say, that I feel many who have seen and heard me very near to my best life,
hoping before long we shall meet in the mansions of eternal peace.

=== Mildred Ratcliff

The following tribute to the memory of a beloved minister of the Gospel,
has for many years been circulating in manuscript.

Her residence was in Western Pennsylvania, where she had removed from Virginia,
her native State.
During a religious visit which she paid in the latter
years of her life to Philadelphia Yearly Meeting,
she made a strong impression on the minds of many,
not only by her services in our meetings, but by her remarkable powers of conversation,
which were directed to the promotion of the kingdom of the Redeemer; so that,
like the late Christopher Healy,
her familiar conversation in the parlor was like preaching.

Her health was very frail,
and she was frequently disabled from journeying by attacks of disease.
On one such occasion she found a quiet resting place
at the house of the late William Kinsey,
of Frankford, Philadelphia.
His wife, Phebe, a sweet-spirited and valuable elder,
years after related to me an incident which occurred at that time.
As day after day passed away, while Mildred was still lying on her sick bed,
the young man, who waited on her and her female companion, became very uneasy.
Harvest time was approaching,
and he had left no one at home who could properly attend to the gathering of his crops,
and so he feared that they would be allowed to go to waste.
Mildred felt sympathy for him--and one day was favored
with a revival of faith on his account,
and told him she believed his crops would be safely housed.
He could scarcely accept the encouragement offered,
and replied that he did not see how it was to be done.
Yet so it turned out.
His grain ripened sooner than that of his neighbors and they went into his fields,
and gathered it;
so that on his return home he found Mildred`'s prediction had been fulfilled.

There is an eagle brightness in that eye,
Whence radiant sparks of inspiration fly;
There is a witchery in that fluent tongue,
Whence rich instruction every breath is flung.

The mute, the eloquent, the weak, the sage,
The wise, the simple, infancy and age,
As thou departed scenes called into view,
Hung on thy lips; for, ancient things and new

From thy exhaustless treasury are brought;
In all the dishabille of native thought.
As erst the prophet`'s vine, thy branches shoot
Over the wall, rich with luxuriant fruit.

Though still thy Master`'s pruning knife was known,
The native vigor in new shoots was shown.
Oft have the archers shot, but still thy bow
Abode in strength; thou quailed not at the foe.

Strengthened by Jacob`'s God, thy hands were strong
To stand the combat, tho`' the strife was long;
Yet, with thy mental strength, thy spirit`'s force,
Guiding our hearts, in a mysterious course;

Holding in leading strings, the strongest mind
A willing captive, curiously entwined
In some unearthly gossamer, whose strength
It cannot sever, nor define its length.

Thou art thyself a prisoner; a poor frame,
Shattered and weak, bears Mildred Ratcliff`'s name.
A spirit of gigantic powers is pent
In a frail body, by each light wind rent.

A mind, expanded as cerulean dome,
Is girt with pains and weaknesses at home.
The glories of the coming world are thine,
But this world`'s splendors never, for thee, shine.

Thou see`'st the gems and jewels of the throne,
But, gems and jewels here, wilt never own.
In thy log-cabin, by the mountain`'s side,
The Christian traveller loveth to abide.

Springs of refreshment there are bubbling up;
There the dear Master fills the sparkling cup;
And, as in Cana, still his power Divine
Turns living water to refreshing wine.

Though small thy oil, thy wheaten measure scant,
Thy King`'s own promise is, Thou shalt not want.
This was his language, when the bond went free,
And thy slaves rose to men, to liberty.
Glorious that day to thee, when comes the cry,
Thy Father`'s chariot waits! Home to the sky!
Then, may the church wear sackcloth; then, the bride,
In secret chambers, seek her grief to hide.
Then, may the priests before the altar fall;
Young men and maidens tell the mournful tale;
Then, may the plaintive cry from all proceed,--
Israel doth mourn a prophetess indeed.
But oh! to thee how glorious! Stripped of all
Earth`'s woes and weaknesses, heir-looms of the fall,
The buoyant spirit, like a bird let fly,
Shall join the church triumphant, in the sky.
Father of mercies, from this harvest home,
May seed be scattered and fresh verdure come!

=== A Weak-Minded Christian

He was the son of pious parents, who had, as the Lord opened the way for it,
instructed him in the knowledge of the Truth,
and the dear Saviour had condescended to his weak intellect,
so that the words of wisdom fell not into barren ground.
He was a great sufferer, and through strengthening grace,
was enabled to bear his physical anguish with exemplary patience.
Yet in the weakness of his mental constitution, he was fearful to be left alone.
Disease wore away his strength and the boy who could
not bear to be parted from his mother,
came to his dying day.
But the merciful condescension of his dear Saviour was manifested towards him,
in that he knew not that he was about to leave her.
He felt no additional pain, only the things around his bed seemed strangely to change.
But his mother was near, and so in quiet he gently breathed his last,
and was gathered by the blessed Saviour without a pang or struggle.
There was an additional weakness, a sinking of the pulse, until its motion ceased,
and then all pain and fear were over,
and the feeble-minded one found the Saviour`'s arms of strength around him,
and needed no earthly one to guide and guard.
In a sweet assurance of the extension of the gathering
arm of mercy towards this weak child,
his Christian parents rejoiced even in tribulation.
In respect to him the following lines were written:

We had a weak and tender one,
Unfitted for the storms of life;
With him the work of death begun,
And he was safely housed from strife.
A timid child, and wont to cling,
For safely to his mother`'s side,--
He needed her protecting wing,--
He needed her to cheer and guide.
Of feeble mind,--yet firm to bear
In patient grief,--as day by day,
Strong agony `'twas his to share,
Till all life`'s vigor wore away.
He could suppress each pain-stirred groan
Yet feared he to be left alone:
He would have viewed with thought of dread
Heaven`'s open gates before him spread,--
Since in that holy happy place
Maternal care he feared to miss,
And not a dear familiar face,
Would welcome to its bowers of bliss.
But Heavenly love was round his bed
To soothe all fears that might annoy,
And death laid off all looks of dread,
Before he touched the timid boy.
He knew not `'twas his time to die,
Without a groan, without a sigh,--
He left his crippled form, to spring,
A babe of grace on cherub wing:
To feel adoring praises move,
Amid the white robed ransomed host,--
And in the flow of Heavenly Love,
To find all fears and weakness lost.

The following lines were suggested by a re-perusal of the _Testimony
of Tottenham Monthly Meeting concerning Thomas Shillitoe_,
who deceased Sixth Month, 1836, aged eighty-two years.
(See _Friends`' Library_, vol.
3.)

And now beneath the weight of fourscore years,
Not rusted, or in self-indulgence spent,
Thy path of faithful dedication nears
The goal, yet on thy Master`'s work intent,
Freely renouncing earthly gain and ease,
Not thy own will to do, but Him to serve and please.

Oh! faithful one, how oft at duty`'s call,
Midst ocean`'s perils--perils of the land--
Thou the dark dungeon and the prison wall
Explored, and at his bidding oft did stand
Before the kings and princes of the earth,
Clothed in his armour who had sent thee forth.

And in that panoply of love Divine,
Emperors and kings to thee have bowed the ear,
And even the low debased, the libertine
Repentant, shed the penitential tear;
While to the sorrowing thou didst oft impart
Sweet words of cheer, and Gospel light to the benighted heart.

And now "`at evening time, behold `'tis light,`"
The goodly land, the crystal gates I see,
A glorious prospect greets my raptured sight,
Thus thou exclaim`'st in joyful ecstacy:
Yet works or merits, have I none to plead
At the pearl gates, or on that road so fair;
No claims to offer for that glorious meed,
On Jesus I rely for entrance there.
Clothed in his righteousness, all works of mine
Renounced, I trust in that bright robe to shine.

The love of my Redeemer sweetly flows,
Even his whose precious blood was shed for me;
And through that love my heart expanding glows,
Embracing all men universally.
// lint-disable scan-errors
Thus closed, illumined with a glorious ray,
Triumphantly, thy arduous well-spent day.

But who, blest one! thy falling mantle caught?
On what Elishas did thy spirit rest?
Who, with a faith and love like thine, have sought
The pearl of price, earth`'s treasures vain, confessed
That they esteemed, compared with this, as dross,
And '`midst temptations bear the daily cross.

Oh! Thou, whose voice omnific pierced the ear
Of buried Lazarus, awake we pray
Our earth-encumbered spirits, make them hear
Thy word, "`come forth,`" arise, that thus there may
A living army instrumental be
In bringing sons from far, and daughters as from earth`'s remotest sea.

Peter Gardiner, a Friend who lived in Essex, had a concern to visit Friends in Scotland,
but being in low circumstances, and having a wife and several children,
was under discouragement about it.
The Lord in mercy condescended to remove his doubts
by letting him know that he would be with him,
and though he was but a weakly man, having no horse to ride,
yet strength would be given him to perform the journey,
and he would be sustained so that he would not lack what was needful.
He, having faith, with innocent weight,
laid his concern before the Monthly Meeting to which he belonged;
and Friends concurring with him therein,
he took his journey along the east side of the nation, through Norfolk,
Lincolnshire and Yorkshire; and coming to a week-day meeting at Bridlington,
where John Richardson then dwelt, he lodged at his house.
In the evening, the doors being closed, Peter asked him if any Friend lived that way;
(pointing with his finger), John told him that he pointed towards the sea,
which was not far off.
He said he believed that he must go that way in the morning, and see somebody.
John asked if he should go with him; he said he believed it would not be best,
and so went to bed.

In the morning, when breakfast was prepared,
John thought he would see if the Friend was well, but he found the bed empty,
and that the Friend was gone, whereat he wondered.
Soon after, Peter came in, to whom John said:
"`You have taken a morning walk--come to breakfast.`"
They sat down, but before they were done eating,
a Friend from the quay or harbor (in the direction Peter had pointed) came in and said:
"`John 1 wonder at you to send this man to my house with such a message.`"
He then related:--That in the early twilight of the morning, Peter came to him,
as he was standing in the fish market-place, looking out on the sea, to observe the wind;
that he asked him if he would walk into his house--Peter
answered that he came for that purpose;
that when they went into the house, Peter enquired whether his wife was well,
and it was answered that she was sick in bed, and he was invited in to see her;
Peter said he came so to do.
Then being conducted into the chamber where the sick woman was, he sat down by her,
and after a short time,
told her the will and resignation of her mind were accepted instead of the deed;
and that she was excused from the journey which had been before her,
and should die in peace with God and man.
Then turning to her husband,
he said:--"`Your wife had a concern to visit the
churches in another country beyond the sea,
but you would not give her leave; so she shall be taken from you;
and behold the Lord`'s hand is against you,
and you shall be blasted in whatsoever you do, and reduced to lacking bread.`"
The man seemed angry with John, who bid him be still and weigh the matter;
for "`I knew not of the Friend`'s going to your house, but thought he was in bed,
and did not inform him about you nor your wife,`" at which he went away.

Peter continued his journey towards Scotland,
and John Richardson and another Friend went with him to Scarborough
on horseback (for he would not let them go on foot),
and he kept before them just as fast as they chose to ride.
When they had gone about half-way,
he gained ground on them and John said he was filled with admiration,
for he thought that he seemed to go with more slight
and ease than he had ever before seen any man travel,
John riding fast.
When he overtook him, he said: "`You do travel very fast.`"
Peter replied, "`My Master told me, before I left home,
that he would give me hind`'s feet, and He has performed his promise to me.`"

When they came in sight of Scarborough, Peter said: "`Take me to a Friend`'s house,
if there is any there.`"
John replied, "`I will take you to the place where I lodge,
and if you are not easy there, I will go until we find a place, if that may be.`"
So John Richardson took him to his lodgings, and just as they entered the door,
they heard someone go up stairs, and soon after the woman Friend of the house,
coming down with a neighbor, invited them to sit down.
In a short time Peter said: "`Here is light and darkness, good and bad in this house.`"
After the woman had got them some refreshment, she asked John,
"`Who have you brought here?`"
"`A man of God,`" he replied.
Having a meeting next day at Scarborough, John stayed with him,
and said he had good service.
He also went with him to several Friends`' houses there,
and he frequently spoke his sense of the state of the families.
But as they were near entering one house, Peter stopped and said:
"`My Master is not there--I will not go in;`" so they turned away.
Next morning, at parting, John Richardson asked him how he was prepared with money,
telling him his journey was long.
Peter answered: "`I have enough; my Master told me that I would not lack,
and now a bit of bread and some water from a brook
refreshes me as much as a set meal at a table.`"
But John insisted to see how much money he had, which was but two half-crowns;
on which John took a handful of small pieces from his pocket,
and forced Peter to take them, telling him it was as free to him as his own;
for so the Lord had put it into his heart.
Here they parted--John and the other Friend returned home.

In about two weeks afterwards the man`'s wife (before mentioned) died,
as Peter had foretold.
At that time the same man had ships at sea; his son was master of one;
a second son was on board another;
and in their voyages they were all wrecked or foundered, and their cargoes chiefly lost.
His two sons and several of the servants were drowned.
The man soon after broke, and could not pay his debts;
and though he had been in good circumstances, if not very rich,
he came to lack bread before he died.

The following notice of Anthony Purver and his translation
of the Bible is attributed to Hartley Coleridge.

Anthony Purver was a Quaker, poorer and less educated than most of his brethren;
by trade a shoemaker.
Can anyone assign a reason why so many shoemakers
have become eminent for their genius or their enthusiasm?
The employment is still, often solitary, and allows a man to be meditative.
Anthony Purver, as he worked with his awl,
was overmastered with an idea that he was called and commanded to translate the Scriptures.
His faith attributed the impulse,
whose origin he could not trace in his own will or
in the concatenation of his human thoughts,
to the Divine Spirit.
But, if he was an enthusiast, he was an enthusiast of much sanity;
for he sought the accomplishment of his end by the necessary means,
and he did not begin to translate till he had mastered the original tongues.
We know not what assistance he received in this great undertaking,
which was commenced when he had long outlived the years of physical docility;
but if it be true, as stated, that he began with the Hebrew first,
(and it was the natural course to occur to his mind), he must have had some,
for there was then no Hebrew and English lexicon or grammar.
However, he did acquire a competent knowledge of the Hebrew, Chaldee, and Syriac.
He afterwards learned Greek, and Latin last of all.
But still he could not have accomplished his purpose without pecuniary aid,
and that aid was liberally afforded by Dr. Fothergill,
at whose sole expense Purver`'s translation of the Old and New Testament,
with notes critical and explanatory, in two volumes folio, was printed,
and appeared in 1765.
A short account of this extraordinary effort of faith
and perseverance may be found in Southey`'s [.book-title]#Omniana#.
It is said to be remarkable for a close adherence to the Hebrew idiom.
It has not apparently attracted as much notice among biblical scholars as the curiosity,
to say no more, of its production would seem to challenge.
We never saw it but once, and that was in the library of a Friend.
We doubt, indeed, whether any new translation, however learned, exact, or truly orthodox,
will ever appear to English Christians to be the real Bible.
The language of the authorized version is the perfection of English,
and it can never be written again,
for the language of prose is one of the few things
in which the English have really degenerated.

=== To the Memory of George Dillwyn

Fully ripe, like the ear for the reaper,
He met the pale messenger`'s word;
Oh! sweet is the sleep of the sleeper
That rests in the name of the Lord.

He slumbers at length with his fathers
Secure from the tempests of time:
For the storm that on earth often gathers,
Is unknown in the heavenly clime.

They have placed the cold earth on his ashes;
They have given him up to the tomb;
But the light of his virtues still flashes,
The pathway of Truth to illume.

He is dead--but his _memory_ still liveth;
He is gone--his _example_ is here;
And the lustre and fragrance it giveth
Shall linger for many a year.

He stood in the might of his weakness,
With the snows of long years on his head;
And sublime with a patriarch`'s meekness
The Gospel of Jesus he spread.

The pathway of the faithful he noted--
In the way of the humble he trod--
And his life was with ardor devoted
To the cause of religion and God.

Like the sun of a midsummer even,
When unclouded it sinks in the west,
His departure was brightened from heaven,
With a cheering assurance of rest.

Calm and soft and serene was the slumber,
Preceding his glorious rise,
And free from all cares that encumber
The moment he winged to the skies.

Oh! there`'s joy in the grief of the weeper,
Whose loss may above be restored;
And sweet is the sleep of the sleeper
That rests in the name of the Lord.

"`Servant of God! _well_ done!
Rest from thy loved employ--
Thy walk of glory done--
Enter thy Master`'s joy.`"

=== Samuel Fothergill, William Hunt and John Woolman

Lines written to the memory of Samuel Fothergill,
William Hunt and John Woolman.--Written 1772.

Whence, oh, my friend, that sadly pensive sigh?
Whence those descending sympathetic tears?
Has thy firm bosom met some adverse shock?
Or dost thou feel another`'s secret woe?
--No: `'tis a general, universal grief
That swells thy bosom with augmenting pangs!
Thou mourn`'st for Zion, mourns the church`'s loss,
By the removal of her valiant sons--
For who can view her stately pillars gone,
Those firm supports of virtue`'s weighty dome,
And not unite in tributary tears?
No more a Fothergill with Truth`'s bright shield
Maintains the dignity of Christian zeal;
No more he shines the mirror of the good,
The noble standard of accomplished man!
Whate`'er of great the moralist can boast,
Whate`'er superior grace religion gives,
In him portrayed a finished character.
With what persuasive, nervous eloquence
His lips have uttered this endearing call:
"`Ye rising youth, the hope of future years,
You who have felt the cords of heavenly love
To draw and disengage you from the world,
Keep near that quick`'ning, vivifying power
Which freed from bondage Israel`'s favored sons!
So shall you grow to glad parental love,
And stand as warriors in defence of Truth!
On you the important cause must soon devolve,
Oh, be ye faithful, upright and sincere.`"
No more he he speaks; his flowing periods cease!
No more he lights devotion`'s sacred flame!
No longer warms and aids the ascending soul
To scale the altar whence his virtues flowed;
For all proceeded from the throne of grace;
His light, his love, his ardent charity,
Were but the emanations of that Sun
Whose rays diffusive are the Christian`'s strength,
His bow, his battle-axe, his only hope.

Nor less revered the memory of Hunt,
That noble veteran in his Master`'s cause,
Who greatly left his wife, his native land,
With every pledge that renders life most dear,
To purchase that best gift--a peaceful mind.
You, who with him have oft retired to sit
In inward silence, awful and profound,
Beneath the shades of Sinai`'s cloudy top,
To wait the unfoldings of mysterious love,
You only know the deep and ardent travail
Of his mind; his sympathetic mind,
In fellow-laboring lent a secret strength
With yours uniting, raising light and life.

And thou, oh, Woolman, venerable seer,
Art highly worthy of the plaintive lay;
In thee the astonished, gazing world admir`'d
What this degenerate age can rarely boast--
__A faithful follower of a suffering Lord!__
`'Twas thine the painful, thorny path to tread;
`'Twas thine to bear a Saviour`'s dying cross!
Redeemed from earth and earth`'s perplexing cares,
Redeemed from lawful and unlawful self,
Thy mind was tutored, fitted and prepared
To enjoy the highest privilege of man;
A near companion with Eternal Good--
A fellowship celestial while below--
The certain earnest of immortal bliss!
Thy only wish, to hear and to obey
The sacred mandate, and supreme decree
Of Him who calls for purity and peace.
Here stop my pen-This fainter sketch forbear
Of what their retrospective virtues teach--
Their bright _examples_ thus address mankind:
"`Our painful, arduous warfare now is past--
Our souls released from earth`'s penurious soil,
Are gone to enjoy the liberty they loved;
That full fruition of triumphant joy
For which we labored in our militant state.
Mourn not for us--the living claim your tears!
Weep for those dead in trespass and in sin!
Tread the same steps which centered us in rest.
By good example call to the supine;
The young encourage, animate the weak;
Comfort the mourners, strengthen those who faint,
That Zion thus may shake herself, and shine
With the bright lustre of her ancient days.`"

=== To Daniel Wheeler

On hearing him say,
in answer to a friend who queried respecting his home,--"`I have no home.`"

Pilgrim and stranger as thou art on embassy of love,
The messenger of Gospel Truth, an heir of rest above,
Well mayst thou say there is no spot from which thou shalt not roam,
That nook thy spirit knoweth not, nor asks on earth a home.

Afar from scenes most fondly prized; from friends in life most dear;
Duty has marked thy footsteps out, a way than none more clear;
But peace, sweet peace, hath followed thee, thy spirit`'s favored dome,
For every man thy brother seems, and every land thy home.

And whether moored on England`'s coast, or yet on Russia`'s plain,
Or on the mountain billow tost, while ploughing on the main,
Jesus has been thy guiding star, and thou couldst safely roam.
While riding on the swelling serge, the Freeling was thy home.

God`'s Holy Spirit beaming there (thy passport o`'er the deep),
When danger`'s darkest hour was near, lulled the rough winds to sleep.
In perils, oft thy soul was stayed where evil could not come;
Christ was thy anchor in the storm, thy port, thy spirit`'s home.

He bade thee go to distant lands, to seas and isles afar;
Nor didst thou doubt his torch of love would be thy guiding star.
Benighted sons there gathered round, rejoiced to see thee come;
And, in God`'s hand an instrument, e`'en there thou wast at home.

From snow-crowned heights, where love grew strong, faith led thy steps away
To tropic suns and genial climes, where earth`'s rich garden lay.
From north to south, from east to west, gray-headed thou hast come,
And, while we hail thy spirit here, oh! be our hearts thy home.

Yes, let thy precepts be impressed upon the softened clay,
Not merely as the morning dew that passeth soon away,
But as the shower that resteth long; that thus in years to come
Remembrance of the faithful past may cheer thy evening home.

As Christians, we can greet thy soul on Truth`'s exalted ground;
As children, come with listening ears to catch love`'s welcome sound;
For thou hast trod youth`'s slippery morn; noon past, and twilight come;
Experience speaks, come, follow me, as I am travelling home.

Loved ones thou hast; for life to thee has been one favored chain
Whose golden links, tho`' severed now, will re-unite again,
Where faith shall end in glorious sight, where partings never come,
And prayer be turned to endless praise in thy eternal home.

Susan H. Loyd

=== Addenda to Susan Loyd`'s Lines to Daniel Wheeler

In frost-bound Russia, she who shared thy bosom`'s joy and care,
Laid down in peace her weary head, her Master`'s joy to share;
From sea-girt isles, against whose base old ocean`'s surges come,
Thy William bowed to God`'s decree, and sought a heavenly home.

In giddy France the lovely one, who with affection true
Had followed thee to southern climes, and all thy combats knew,
Waited thy coming from the west, across the Atlantic`'s foam:
Saw thy dear face again in love, then hasted to his home.

Perhaps in mercy, He who gave, may every green bough take,
And thou, a tree late flourishing, a branchless trunk mayst make;
Then oh! how joyous will it be--no longer doomed to roam--
To hear the mandate from above that calls thy spirit home.

`'Tis done! the chariot wheels have passed along the parted air;
The victory won, the soldier leaves the field of toil and care.
The house eternal of our God, the everlasting dome
Is now the resting-place of him who had on earth no home.

Joseph Kite

=== Our Gallery--Northern District Meeting

The following lines,
descriptive of some of the worthies who belonged to the
Northern District meeting of Friends in Philadelphia,
fifty or sixty years ago, were found after his decease,
among the papers of the late Joseph Kite, author of [.book-title]#The Arm Chair#.

Gone are our princes! and the common lot
Records their lives--they were and they are not!
Man bows submissive as death`'s shaft is hurled,
Unbending conqueror of an humbled world!
Dust seeks its dust! then the freed spirits know
A union with their Head, commenced below.
Here of the well of life they joyful sang,
There they partake the fount from whence it sprang!
The worthies of an earlier day had fled
To join the mighty army of the dead:
Emlen and Savery, Scattergood and Jones,
Whose trumpets filled the ear with Gospel tones,
No more were here beside the altar found,
Nor to the people gave a certain sound
When first amid the gathered flock I came
To the North Meeting; still a living flame
Burned on the altar; still a chosen few
Could the remembrance of past days renew;
Though glorious lights had passed the heavenward track,
Their beams, reflected, came in glory back!
Though oft we mourn for better days gone by,
When our forefathers, of stern probity,
Stood as a rampart, throwing back the tide
Of coming billows, threatening dangers wide,
Yet deem not all is lost. Are there not now
Here many hearts no Baal learns to bow;
Souls firmly wedded to a suffering Lord,
And gifted servants to proclaim his word!
We may not name them, though we fain would name--
"`Well done!`" at last will be their well-earned fame!
They stand as watchers still upon the wall,
Their warning voices to the careless call;
Haply the children of our time will tell
To their descendants, while their bosoms swell,
How nobly stood the worthies of this day,
With armor burnished, fitted for the fray;
How battled they with an unshrinking front,
Bearing the conflict`'s most appalling brunt.
Here they may mourn--our worthies are laid low--
And fear that Israel no more such shall know;
But He who holds creative power can still
Call into being servants of his will.
In every age a remnant will be found
To do his bidding, in his grace abound;
Go in and out before the people, clad
In that bright armor that makes Israel glad.

=== Jerusha Curtis

`'Mid briars and thorns a gaudy flower-bush grew;
Bowed bruised to earth, abroad its odors threw;
For soon a storm swept through the bright parterre,
And tempest darkness filled the troubled air;
Its painted leaves then lay upon the ground,
Buds of its being strewed the earth around;
Proudly awhile it fluttered in its pride,
With its gay branches growing at its side;
The Gardener laid the fairest scions low,
And left the poor stripped bush few shoots to show;
But a sweet fragrance, all unknown before,
Did from its wounded side rich balsam pour.
Jerusha Curtis, in her hour of joy,

Lived to the world, scarce tasting of alloy.
Her children held her with a powerful tie,
While earth`'s loved objects hid her from the sky.
Mercy removed her idols, stained the view
Of worldly pleasures, as it gently drew
Towards the Saviour--till she humbly stood
A living witness of his cleansing blood.
Then for his cause she raised her voice of praise,
And died in hope--rejoicing in his ways.

Jerusha Curtis died on Third-day, the eighteenth of Fifth Month, 1830,
aged about fifty-one years, after a long and suffering illness.
She had many domestic afflictions, which tended to her purification.
She was an honest minister of the Gospel,
who bought the Truth for a price and sold it not.

=== Leonard Snowden

Thy meek, kind look--thy penetrating eye--
Thy earth-bowed form--thy thought ascending high--
Thy steady gathering to the house of prayer--
Thy reverend waiting on the Master there--
Thy honest dealing--sympathetic press,--
That sends the mourner help in deep distress--
Thy quiet movement through the crowded mart,
That shared thy presence, but held not thy heart--
The half-subdued, yet ever-present smile,
That o`'er thy features played and lit the while,
Lives in remembrance--though no more we dwell
On that dear countenance we loved so well.
Cast on a sea of trouble, when the fight
Of angry elements in struggling might,
Brought secret disaffections into view,
Calmly thou didst thy troubled path pursue.
So firm, yet gentle, in thy Master`'s cause,
Kind, yet unbending, steadfast to his laws--
The very men who did their Lord reject
Scarce knew to treat thee with marked disrespect.
Still Leonard Snowden held a certain place
With men far entered in the sceptic race.
In placid eve his sun went down in peace,
And he was gathered where all conflicts cease.

This beloved elder died the twentieth of Sixth Month, 1832,
aged about eighty-one years and three months.

=== Edward Randolph

Strong in thy will and purpose, earlier life
Saw thee a combatant in martial strife,
Where drums and trumpets fired the angry mood
With honors rife, and garments rolled in blood!
Another warfare it was thine to know--
A strife more arduous, with an inward foe--
To know a victory over wrong desire,
In warfare marked by a consuming fire.
May we not hope a conqueror in this field,
Did Edward Randolph know his foes to yield;
O`'er the last enemy victorious prove,
Through Him who lent the armory of love?
The final combat ended, loosed amain,
The passport gained through struggling and through pain,
Safely, we trust, thy weary feet have pressed
Through swelling Jordan, to the land of rest!

=== Ann Maule, Martha Rose, Sarah Smith and Israel Maule

Others through quiet seas have laid their prow,
Where scarce a ripple could their courses show;
Yet they as safely in the haven rest,
As whom waves followed and the spray caressed.
The quiet Mary knew the Gospel springs,
As much as Martha chafed with many things.

Such was Ann Maule,--such Martha Rose, if they
But passed through life in the appointed way;
Such Sarah Smith, if studious to fulfill
The known requirings of the Master`'s will.
Such Israel Maule, clean-handed, and with heart
Ready to suffer his allotted part.

Ann Maule, an overseer, died Third Month 13th, 1833, in her forty-ninth year.

Martha Rose was an overseer, Sarah Smith a minister.

Israel Maule, an elder, died Eleventh Month 25th, 1828, in his fiftieth year.

=== Mary Taylor

Faithful amid contumely and broil,
Gainst adverse billows with her friends to toil,
Bearing her cross where rose derisions wild,
And scoffs and jests were cast at Bethlehem`'s child,
Was Mary Taylor steadfast for the Truth,
Her age`'s stay, the promise of her youth.

Mary Taylor, an elder.
During the Separation, being faithful to the ancient principles of the Society,
she was a mark for the arrows of the enemies at Green Street Meeting.

=== Jane Snowden

When by the resurrection of thy Lord,
Quickened to preach the everlasting Word,
Awe-struck and trembling:--with each period`'s swell,
Hearts sympathetic answering, rose and fell:
No idle prating for the talking`'s sake,
Nor balanced words a cadenced point to make,
Fresh gushed thy offerings from the Fountain Head;
And He that opened guided as they sped;
Sent its appropriate streams where e`'er He chose,
As Shiloh`'s waves to these--as Marah`'s those;
The swell of Jordan to the stiff and proud,
Bethsaida`'s healing to the lame and bowed.
Long "`tarrying by the stuff,`" thy wearied frame,
Not oft the public altar could attain,
Where others ministered; but Grace had given
To thee a ladder reaching up to heaven:
Like Obededom`'s there the ark was bound--
A little Bethel at thy hearth-stone found.
Absent in person from the worshippers
Jane Snowden knew their spirits joined to her`'s.
As life was ebbing flowed the Gospel strain:--
The two disciples that to Emmaus came,
As day was sinking in the reddened West,
And recent scenes bewildered and distressed--
Whom the dear Master joined upon the road,
Opening the Scriptures till their spirits glowed,
Her dying tongue brought solemnly to view,
And from the passage sweet instruction drew.
Thus in her gift she labored to the last,
Till time was finished and probation past!

This beloved minister died Fourth Month 18th, 1837, in her eighty-third year.

=== Othniel Alsop

When the disciples faint, mid gloom and doubt,
Scarce in the battle held the combat out,
A living faith upheld thee, in the hour
Of infidelity`'s dark reign and power;
Brighter and brighter in that hour of night,
Thy steady confidence diffused its light;
And oft the cheering cup thou didst afford
To those who battled for their sovereign Lord.
When dashing billows beat against thy barque,
When death`'s bleak shore rose o`'er time`'s boundary dark,
Thou couldst proclaim, thy Captain walked the deck,
And the tossed vessel would not all be wreck!
"`Instant in season`" with thy gift, and true
To public service as it rose to view.
Beside thy grave the tribute just was paid,
As Othniel Alsop in the grave was laid,
That faithful in his ministry, he proved
A zealous servant to a cause he loved.

He died Twelfth Month 8th, 1836, in his sixty-sixth year.

=== Thomas Bacon

In golden harvest; when thy sun was high,
E`'er Autumn left thy branches seared and dry,
A burden-bearer, with bowed neck to feel
Allotted suffering for the body`'s weal;
A tender husband, and a father loved,
The Christian armor who so lately proved,
We fondly hoped thy promise would produce,
A plenteous harvest for the Master`'s use;
But mortal blindness cannot judge aright,
And thou wert taken from our hopes and sight,
Mysterious Wisdom planned--the contrite heart,
Bows to the fiat, though it weeps apart.
We fain had kept thee till mature in years,
Our hopes to cherish and partake our fears.
True to thy principles, in virtue bold,
Thou told the stranger who despoiled the fold,
How e`'er wrapt up in learning`'s close disguise,
That he was naked to discerning eyes.
Ah, blight and sear, and discord fell were found,
Where e`'er this stranger prest upon our ground;
Seeds of his sowing towering weeds have grown,
And all the fruits the parent stock have shown.
Bacon, we love thy memory!--we deem
The church`'s loss thy passage from this scene;
We deem the cause that made thy true heart break,
A wound received for thy dear Master`'s sake!

Thomas Bacon, an overseer, died on Seventh-day evening, the twenty-third of Tenth Month,
1838, in the forty-ninth year of his age.

=== Timothy Paxson

All native talent never yet sufficed,
The strong man bowed, must be a babe in Christ:
Thou mayst have deemed thy wisdom but as dross,
And laid thy treasures humbly at the cross.
The world, that claimed thee much, well didst thou know,
Oft robbed of joys it never could bestow.
There is a leprosy that closely cleaves,
To him who daily amid money lives;
It is a leaven that will work unseen,
Till captive man learns mammon`'s rites unclean;
Earth`'s honor as a covert poison flows,
Till all the system its dread influence knows;
Like some fair tree the sight with pleasure fills,
While prussic acid from its leaf distills!
Grace may in thee have conquered; we may hope
In age thy virtues had full room and scope;
That all the powers of thy lofty mind,
Gathered from earth were to the skies inclined;
That human wisdom in submission laid,
A new creation was in mercy made;
That e`'er the world receded from thy view,
Old things discarded, all things became new,
That Paxson found, his earthly covering riven,
A robe of righteousness through faith was given!

Timothy Paxson, an elder, died Fourth Month 21st, 1839, in his seventy-fifth year.

=== Rebecca Richardson

Rebecca Richardson, a few short years,
Sat here amid our prophets and our seers.
Steadfast to ancient principles, she ran
Her quiet course--pursued the Gospel plan;
Employed her talent till the Master came,
Nor sought the plaudits of an empty name,
Her`'s the reward of faithfulness. We trust
That though the body turned again to dust,
She knew the Power that triumphs over strife,
Who is the "`Resurrection and the Life.`"
As time was ebbing, thou couldst calmly say,
To a dear friend who watched thy closing day:
"`In the dark valley lie the shades of night,
But all beyond are glorious beams of light.`"

Rebecca Richardson, a minister, died Tenth Month 16th, 1840, in her sixty-fourth year.
During the early period of the Separation, she resided in Bucks Co.,
and heartily joined with her friends in opposition to the unsound
sentiments then promulgated by some bearing the name of Quakers.

=== Rachel Bartram

Caught in the Gospel net, thy trappings gay,
Ribbons and flounces, all were torn away!
Self-will that stooped not to the Christian yoke,
Under the Gospel hammer crumbling broke,
The wandering spirit that went forth to feed,
Beyond the covert, in the flowery mead,
Where no enclosure kept the foe at bay,
But secret enemies in ambush lay
The Shepherd`'s crook caught e`'er the wolf had slain,
And safely gave thee to the fold again!
// lint-disable modernize-words `imprest`
The dangers of that hour had deep imprest
A solemn warning in thy anxious breast;
The very day that closed thy pilgrimage,
To one^
footnote:[William Smith.]
so tempted thou gave counsel sage,
Told how thy startled heart heard the decree,
Mid thine own people must thy portion be;
And little deemed so soon before the throne
You both should answer for the deeds here done!
Love to the Saviour in thy tendered heart,
In gentle shootings soon began to start;
The bursting seed,--the tender blade,--the ear,--
In due progression at his call appear:
The ripened harvest did the toil repay,
When Death`'s keen sickle cut in haste away;
But in the garner, where the wheat is stored,
Has Rachel Bartram entered to her Lord!

Rachel Bartram, an overseer was suddenly called hence on Third-day, Twelfth Month 7th,
1841, in her fifty-second year.

=== Catharine Sheppard

Without a thought that needed art`'s disguise,
Open and obvious to the gazer`'s eyes,
Did Catharine Sheppard undissembling stand,
Bearing her open heart within her hand.
No shy reserve--no double minded way--
// lint-disable scan-errors
No shadowy covering to shut out Truth`'s ray;
Loving the ancient path her fathers trod,
Though by the cross and underneath the rod,--
Modern inventions for the ease of man,
To slip to heaven upon some other plan,
Her honest nature threw indignant by,
Choosing the path Fox trod to victory!

Catharine Sheppard, a beloved elder, died Twelfth Month 15th, 1842, aged eighty years.

=== William Hallowell

Of modest worth, of unpresuming merit,
With the meek covering of a quiet spirit,
Did William Hallowell his portion share,
And unrepining a long sickness bear.
Looking for mercy to a Saviour slain,
Who rose victorious from the grave again.

William Hallowell had been an overseer till released on account of infirm health.
He died Second Month 24th, 1843, in his seventy-first year.

=== Lydia Dean

Thy weary pilgrimage at length is done!
Through sore affliction was the victory won.
No flowery way towards Zion didst thou trace,
Through smiling gardens or through bowers of grace,
Thy rugged path in the cloud`'s shadow lay,
Little to make thee idle on the way.
And this was merciful! Thy vision clear
Saw joys beyond, felt briars and brambles here.
Thy very trials urged thee on the road
To where the weary rest, and lose their load.
As did the ancient servants of thy Lord
Where mockers would not listen to the Word,
Thou shook the dust from off thy feet, to make
A true memorial for the Gospel`'s sake,
Left blind professors firm to earth allied,
And sought congenial spirits here--and died!
Earth was receding from thy failing sight,
When o`'er thy features shone a heavenly light,
"`Sweet Jesus now has come`" thou joyful cried--
And Lydia Dean was by her Saviour`'s side.

Her certificate was received by the meeting in the Third Mo., 1844.
She never attended the Select Preparative Meeting.
Her mother said of her: "`She lived like a lamb, and she died like a lamb.`"

An interesting obituary notice was published in vol.
17 page 367 of _The Friend_.

Lydia Dean, a minister, died in 1844, in her fiftieth year.

[.asterism]
'''

Jacob Lindley, in the days of his early labors in the ministry,
passed through a period of trial and perplexity.
Being one day at work by himself, this question seemed to arise with him:
"`Have you a soul?`"
His inward answer was: "`Yes, certainly I have.`"
To this a second question arose: "`How do you know you have a soul?`"
He called to remembrance all the evidences in favor
of the immortality of the soul he had read,
but it was immediately suggested within him: All this may be priest-craft.
Then there arose before the view of his mind the
resemblance between the various races of animals;
and he saw that in form the monkey was a close approximation to man.
Man seemed to him but a link in the great chain of animal life,
and why should he be immortal, and the rest not so?
He was perplexed, though not at all satisfied with this reasoning,
yet felt as if he was doubtful whether he had anything to hope,
or any cause for fear beyond the confines of time.
This was during the Revolutionary war, and the thought arose that if he had no soul,
he might take part in the contest,
and if he should be killed in it there would be the end of him.
If there was no after scene--if death ended man`'s
existence--life could be of little consequence.

At last, leaving off his reasoning, he sat down, and his mind was drawn into quietude.
After a time thus spent, a query arose within him to this import:
"`Can you look forward a thousand years?`"
His inward answer was in the affirmative.
The query again arose, with an increase of the length of time.
This he knew he could do.
Then the query was further extended,
embracing in its scope existence which should have no end.
This idea, also, he felt that his mind could grasp.
The inward question then suggested that this power was not possessed by the animal creation,
and also that the mind which could grasp futurity would
exist through that eternity it could meditate on.

Jacob Lindley felt his doubts at once removed.
He believed that these suggestions were from a higher source
than the mere cogitations of his own reason and intellect,
and he doubtless was thereby more effectually fitted to meet and confute the deistical,
would-be reasoner, when his Divine Master laid it upon him.

William Penn made not only a beautiful piece of alliteration, but a full sermon,
when he wrote: "`No pain, no palm; no thorns, no throne; no gall, no glory; no cross,
no crown.`"

Respecting a visit to the Catholic bishop of Kilkenny, Thomas Shillitoe says:

On our arrival at the house we were ordered up-stairs,
where the bishop received us with great civility; ushered us into a room;
brought me a chair, placing it opposite to a sofa, on which he took his seat.
My companions taking seats, also, we dropped into silence,
which I broke by saying a visit had been paid to the drinking houses in Kilkenny,
which I supposed he had been acquainted with, to which he replied: "`Well.`"
I observed that in performing this visit,
my fears and the various reports I had heard were fully confirmed;
that the laity profess to believe the clergy have full power to forgive their sins;
adding, the people may be so deceived as to believe the priest has this power,
but that I did not believe it possible the clergy could believe it themselves.
Therefore, as their superior, to whom the people were taught to look up for counsel,
I desired he would seek to the Almighty for help, and as he valued his own precious soul,
as ability was afforded him,
endeavor to turn the minds of the people from man unto God and Christ Jesus,
who only can forgive sins;
otherwise he would incur a load of condemnation too
heavy for him to bear in the great day of account,
when the deceiver and deceived would be all one in the sight of God,
whether actively or passively deceiving the people.
That at times, when considering the subject,
it was my belief that if the Almighty had one vial of wrath more powerful than another,
it would be poured out upon those who thus deceived the people.

Here I closed for the present.
He manifested great confusion; shutting his eyes,
as not being able to look me in the face.
A pause ensued, and after a while he requested leave to say something,
to which I replied, he had heard me without interruption,
and I was willing to hear him in like manner.
He began by saying it was very indecorous and unchristian in me to come to his house,
a stranger to him, and from another land, and address him in such a manner, charging him,
who was a man of so much experience in the church of God, with being a deceiver;
saying surely, I must be mistaken.
I told him it was in love to his soul, and under an apprehension of religious duty.
He called upon me to produce my authority for my mission.
I told him my authority was in my own heart.
He said conversion was a great work, and he was not to be converted all at once.
I queried with him: "`Are not the people thus deceived?
Do they not believe the clergy have power to forgive their sins?
Are you endeavoring to undeceive them?`"--exhorting him
to be willing to cooperate with that Divine help which,
if rightly sought after by him, would be extended,
whereby ability would be received to undeceive the people;
again reminding him that the deceiver and deceived were all one in the sight of God;
and that it continued my firm belief,
if the Almighty had one vial of his wrath more powerful than another,
it would be poured out on those who thus deceived the people,
whether actively or passively engaged therein.

He said he believed I meant well, and that he commended my principles,
but he could not say he thanked me for my visit.
I expected, at times, he would have turned me out of the room.
We rose from our seats to take our leave, when the bishop clasped my hand,
and holding it, paused, saying:
"`I believe I may say I feel thankful for it;`" doubtless meaning the visit.
Requesting us to take some refreshment, he kindly conducted us to the stairs again,
and we parted, never more to meet on this side eternity; for I received an account,
about twelve months after this visit, of his removal by death.
We returned to our inn rejoicing; I,
under a sense of faithfulness in cooperating with the help mercifully vouchsafed
to deliver what to me appeared to be the whole counsel of my Divine Master,
and my companions, that I was helped to get through to my own relief.

There can be no doubt that much mischief attends the false
belief that the priests can absolve their hearers of sin.
Instead of lessening crime, it must encourage it,
and remove the belief of future punishment,
and induce a total disrespect for the truth of religion--especially
if they think they can be released from sin by paying for it.

Some interesting incidents are related of Jacob Lindley, a warm-hearted,
impulsive minister, who resided in Chester County, Pa.

As Jacob Lindley was riding on horseback, one day, not far from his own residence,
he was overtaken by a shower,
and took shelter under the sheds belonging to the New Garden meetinghouse.
Here the graveyard was open before him,
and his mind soon became busy in recalling to recollection the many worthy
Friends and faithful ministers of the Gospel buried there who,
having served the Lord in their generation, had died in peace.
His feelings became warm,
and at the top of his powerful voice he broke out in the words of Addison:

"`How are thy servants blest, O Lord!
How sure is their defence!
Eternal Wisdom is their guide,
Their help Omnipotence.`"

Such a voice as his echoed far and wide.
A neighbor, who was passing along the road at the time,
hearing the words uttered in such a tone, proceeding, apparently, from the graveyard,
and perceiving no one, he deemed it was something unearthly, and,
putting spurs to his horse, fled from the place with fear and precipitation.
Jacob, hearing the clatter of the horse`'s hoofs as the man galloped off,
immediately comprehended the cause, and, to appease the man`'s alarm,
he shouted after him.
In his earnestness he did not let his voice fall,
and the man`'s fears were aggravated by hearing himself called by that voice.
His spurs did not cease their office until he had placed a considerable
distance between himself and the spot from which such awful sounds proceeded.

On one occasion Jacob`'s warm heart was sorely tried, and his zeal was in great dominion.
He had given employment, in his family, to a colored person, who, it afterwards appeared,
was one held as a slave; who,
without having been manumitted by those claiming him as their property,
had attempted to secure his natural right to liberty by running away.
The person who was the reputed owner of this black man obtained
information--probably from a drunken neighbor of Jacob Lindley`'s,
named John Brown--where his human chattel could be found.
Taking a company of people with him, among whom was this John Brown,
the Southerner proceeded to the house of Jacob Lindley, and, by force, seized the slave.
Jacob, who warmly felt the oppression of the poor, afflicted negroes,
was deeply affected at seeing this man carried off into bondage.
He did not--he could not,
as a true-hearted follower of our Lord Jesus Christ--offer any physical resistance,
but he could plead the cause of Truth, mercy and righteousness,
with a voice of persuasion, of compassion, of warm-hearted feeling,
of terror-awakening zeal.
What he said to the slaveholder has not been preserved; but,
seeing his drunken neighbor, he turned to him and sharply demanded who he was.
The man no doubt quailed before the earnest manner
of this afflicted lover of the human race,
and answered that he was John Brown, one of his neighbors.
"`Yes,`" said Jacob, as if suddenly remembering him, "`I went by your house the other day.
The fences were down; the pigs were squealing;
the dog stood leaning against the side of the house, too lean to bark!
And I said to myself: '`John Brown!
John Brown!
Cursed within and without!`'`"

In speaking of the trials of faith into which Friends are sometimes brought,
Christopher Healy said he was once travelling, on the fourth of the Seventh Month,
and the time had fully come for feeding his horse.
It was a few miles from Albany,
and he stopped at a tavern kept by two brothers whom he knew very well,
and put his horse under the shed.
The hostler came and gave the horse his oats.
Presently the sound of a fiddle was heard in the house,
and Christopher knew there must be a dance going forward.
He became a good deal disturbed under the thought
of what people would say if he should be found,
on such a day, at a tavern where a dance was going on.
It would bring discredit, he thought, on his profession.
He quickly decided to proceed, and was about mounting his horse,
when he heard the language: "`You must go into the dance-room!`"
This, he thought, was out of the question, and a delusion, and he`'d do no such thing.
So he rode off slowly, but with a heavy mind.
Feeling so uncomfortable riding, he dismounted and tried walking; but it was no better;
the exercise continued.
Again he heard the voice, and again strove to put it away as a delusion.
The third time the admonition was:
"`Perhaps you will never have another opportunity to warn these people.`"
"`If it comes to that,`" said Christopher, "`I must go back.`"

Mounting his horse, he returned to the tavern, put it under the shed to finish the oats,
and proceeded into the house.
The senior of the young men who kept the house he found in the bar-room,
and inquired of him if he might go into the dancers`' room.
Though doubtless astonished, the landlord said: "`You may, Mr. Healy, if you desire it.`"
On being requested to do so,
he also went with Christopher upstairs and opened the ball-room door.
The floor was occupied by the dancers, and the fiddler was engaged in his vocation,
when the unexpected appearance of the plain Quaker burst upon their astonished vision.
Instantly the tones of the fiddle ceased,
and the dancers slunk away to the seats placed around the room.
The junior landlord came forward instantly, seeing his gain was likely to be disturbed,
and said: "`Oh, Mr. Healy, you can`'t preach here!`" "`But,`" said Christopher,
"`only let me ask the young people a question.
Would you be willing to get into the quiet a little time?`"
The company very generally gave assent; but the young landlord again interposed and said:
"`Any other time, Mr. Healy, we shall be glad to hear you, but positively not now.`"
Well,`" continued our friend, "`if you will not allow it, I shall be clear,
and must leave it on you.`"
He then departed, and went with a light and cheerful heart on his road.

Some time after, Christopher met with the young landlord,
who told him that he had felt very much troubled whenever he had
thought of having stopped him from speaking to the dancers,
and desired him to have a meeting appointed in that dance-room,
and he would take care to have all the company that were then present, invited.
The proposal took hold of Christopher`'s mind, and,
after consulting with the select members of his Monthly Meeting,
he felt easy to appoint a meeting in this large room of the tavern.
Very especial care was taken by the young landlord
to have all the company of "`the Fourth`" present,
and Christopher added:
"`That he never remembered to have had a more satisfactory meeting;
the floor being a good deal wet with the tears of his auditors.`"
After the meeting was over,
the young landlord told Christopher Healy that his object in going into the room at
the first was so far accomplished that there was not another sound of the fiddle,
or a single dance after he went into the room that day;
but that they all departed to their respective homes
as though they had been at a Quaker meeting.

=== The Last Interview Between Christopher Healy and Ruth Ely

At the close of Bucks Quarterly Meeting, held the twenty-sixth of Second Month, 1851,
Christopher Healy went to see his old friend and faithful
fellow-travailler for the prosperity of Zion,
Ruth Ely.
She had long been confined to the house,
but though absent in body from the assemblies of the Lord`'s people,
and debarred by situation from much of the company of her valued friends,
she was present in spirit with them,
and partook in her measure of their earnest concern
that the testimony of Truth might be supported,
and primitive practices maintained in all their purity and brightness.

The visit was one very satisfactory to the two aged Friends, who,
standing on the borders of the grave, into which they were about to descend,
could commemorate the Lord`'s mercies in times past,
and could rejoice in feeling and knowing that they
had not been following cunningly-devised fables,
but living and eternal Truth.

They felt that their own work was nearly accomplished,
and they were permitted to rejoice in seeing and
feeling the spiritual greenness of each other.
When the time of parting came, Christopher took hold of Ruth`'s hand, shook it cordially,
and looking at her very pleasantly, said: "`Farewell, Ruth!
Farewell!
We may meet again in mutability, and we may not.`"
Ruth then, in answer, said:
"`I feel it upon me to tell you what passed between two dear Friends at their last interview.
One said: '`We may meet again in mutability!`' The other answered: '`No!
When you come this way again, I shall be in heaven!`'`" Ruth added:
"`I thought I must get out again--but I am waiting;`"
evidently meaning she had gone through her labor,
and was only waiting for her release.
Christopher then said:
"`I must say what I once heard passed between a Presbyterian
minister and one of his hearers,
who told him she was in a waiting state:
'`There is no waiting state till the work is done.`'`"
Ruth received the admonition couched in the anecdote,
and sweetly, yet solemnly said, while her countenance was thoughtfully serious:
"`I must see what remains for me to do.`"

Christopher`'s wife coming into the room, Ruth said:
"`This has been a very satisfactory visit to me;
the unity that has been between us is not to be broken.
Neither heights nor depths,
nor anything in this world can break the unity that is between us.`"
Thus these two aged friends parted in the overflowing of Gospel love and fellowship.
Ruth soon found herself a little stronger than she had been for some time previously,
and she ventured out a short distance from home,
as she felt her mind drawn to visit some of her friends; and she was once at meeting.
Several of her visits are said to have been very remarkable
seasons--satisfactory to the visited and relieving to herself.
On returning home from the last of these visits,
she said she believed her work was now done.

A few days afterwards, just twenty days from her parting with Christopher,
she was suddenly and quietly released from the body, and gathered, we humbly believe,
to the just of all generations who have finished their allotted
portion of service and of suffering on earth.
Her decease took place Third Month 18th,
and the next time Christopher came that way was to attend her funeral.

It is said that while Christopher stood by the body,
once animated by the pure spirit of his friend, he said: "`Dear Ruth is gone,
and I shall not be long behind her.`"

Neither was his tarriance long; in less than two months he also was permitted, we trust,
to enter into the joy of his Lord.
Divine mercy sustained him in his sickness, and at his close,
so that "`Death had no sting, and the grave no victory.`"
Peace was his daily portion while treading the dark valley.
The tempter, the accuser of the brethren, stood rebuked.
Thanks be to God who gives (his saints) the victory, through our Lord Jesus Christ.

The following incidents were related by Christopher Healy,
at different times in companies where he was:

Upon Christopher Healy`'s visit to the Southern States, in the year 1824,
at one place he attended a small Select meeting.
There were not more than about ten present.
Christopher said something came over him that he could not get rid of,
and so he quoted the expression of the prophet, "`'`Shut the door,
and hold him fast at the door;
is not the sound of his master`'s feet behind him?`'
When anyone believes that there is no devil,
no evil spirit other than the natural inclinations of the human heart,
whether he is a Friend or belongs to another denomination,
he is ready to deny the divinity of our Saviour.
Christ was tempted of the devil, and He could not have been tempted by his own nature;
it must have been by an evil spirit.
Through this door +++[+++of denying the existence of a devil]
all infidel principles can come in, even till a man comes, with the fool,
to say in his heart, '`There is no God.`'`"

After the meeting had dispersed,
his companion told him that he had heard one of the Friends present
state his opinion in these very words--that there was no devil
other than the natural inclinations of the heart.
Nothing had been said to Christopher about it, and at the time he felt the impression,
he was not aware that any present held such views.`"

Fourth Month 15th, 1849.
At the house of a friend, Christopher said:

I suppose that there are few members of our religious Society now
living who have passed through sorer trials of their faith,
or have been plunged into deeper baptisms of sufferings than I have been;
but I can now see that it has all been for the best, and that they have been permitted,
or perhaps I may say appointed, to purify me more effectually from defilement,
and to wean me from the perishing things of this world,
and to induce me to seek for consolation where alone it can be truly found.
And lastly, that I may sympathize with, and comfort those who are under suffering,
with a little of that comfort wherewith I myself have been comforted of God.
And I do believe that it is not only my privilege, but my duty also,
to do what I can to comfort and encourage my friends who are under trials and afflictions,
by telling them how good the Master has been to me,
not only in sustaining and supporting me under my many and varied provings and besetments,
but in bringing me out from under them in his own appointed time;
and when He has seen that it was enough,
permitting me and enabling me to sing his praises on the banks of deliverance.
Glory be to his ever worthy Name therefor!

I just now remember a time when I was plunged into
as deep distress as perhaps I was ever in;
and I am willing to tell you of it +++[+++addressing an individual present],
for your consolation and encouragement.
I had been speaking a little in meetings from time to time, as you have been,
and not without doubts and reasonings from within, and opposing spirits from without,
as I suppose you have had to encounter.
But the cause of my then great trouble was on account
of some debts which I had left behind me unpaid,
in Rhode Island.
I knew that they ought to have been paid long before, but I had never been able to do it,
though I had worked early and late,
and denied myself almost the necessaries of life in order to do so;
yet I had not been able to procure the means.
The consideration of these things troubled me very much,
for I feared that my creditors would believe that I was dishonest,
and that I intended to cheat them out of their just dues, by refusing to pay what I owed.
Indeed I was so much troubled about it, and got so worked up in my mind,
that I felt almost confident that a complaint would
be sent to our Monthly Meeting against me,
and I was really afraid to go to Monthly Meeting,
lest I should there hear myself charged with being a dishonest man.

One evening in particular I was brought very low in my mind.
I seemed to have got to the very lowest spot that a poor mortal could be plunged into.
My wife had gone to bed, and was asleep, but I was afraid to go to bed, and there I sat,
or walked about, reduced almost to despair.
After a while I thought I would get my Bible,
and see if I could not find some comfort in it;
or at least if I could not divert my mind from its very distressing thoughts,
by reading in that good book.
The first passage I read did but increase my distress.
I have forgotten what it was, but it plunged me still deeper into misery;
and the further I read on, the worse I got,
so that I thought I would go distracted if I did not shut up the book.
It was then after midnight.
I put my Bible away, and concluded to go to bed,
expecting nothing else than I would toss and tumble about without sleep till morning.
But I think I was not in bed five minutes before I fell asleep;
and I seemed to awake as suddenly.
I stared around me, and it was broad day, and the sun was shining full in my face.
We lived then in a log cabin, at the east end of which there was a window of six lights,
through which the sun was shining bright and clear as I had ever beheld it.
I looked around the room.
There lay my wife sleeping sweetly by my side, and I could see everything in the room,
looking as natural and in its place as usual.
I looked out of the window, and everything there seemed bright and beautiful;
the glorious sun seemed to be half-way up the sky, shining with its accustomed splendor;
and there I lay in bed, debating with myself whether it was really day,
with the sun half-way up to the meridian,
or whether it was a vision of light that encompassed me.
But while I was considering this question, the light faded from my view,
and I found myself lying in my bed, with the darkness of midnight around me.

I then knew that it was either a dream,
or else a vision of light from the Lord to comfort my heart,
and to bring me out of my sore distress.
And blessed be his holy Name, who thus did comfort me,
and gave me at once faith to believe that He would make bare his holy arm for my help,
and bring me out of my great and sore troubles.
Indeed, the Sun of righteousness did already shine into my heart,
as the sun in this vision of light shone into my face, and lighted up the flame of hope,
giving me to believe that He would enlighten my path,
and enable me to see of the travail of my soul, and be satisfied therewith.
Being thus refreshed and comforted, I fell asleep, and slept soundly till morning.

Next day I wrote to a Friend in Rhode Island,
and told him how distressed I had been about my debts,
assuring him that I was desirous and anxious to pay them,
but that hitherto I had been unable to do so,
and I requested him to inform my creditors that I
was striving to earn the means of paying them,
and I would send it to them as soon as I could get it, which I hoped to do before long.
I soon received an answer, saying that I might make myself easy about my debts,
as all my creditors knew that I was an honest man,
and they were willing to wait for the money,
until I was able to pay it without distressing myself.

Times soon changed for the better with me.
I had a pretty good crop of wheat, which I sold, and I parted with some other things;
so that I collected a pretty considerable sum of money for me,
though not quite enough to pay all I owed; but I sent it to my friend C.,
desiring him to divide it among my creditors.
I soon after received a letter from him, enclosing receipts in full from all my creditors.
So the Lord helped me out of that difficulty, as I trust He will help you out of yours,
for I know that He will help all his poor distressed children
and servants out of their difficulties and trials,
if they will but trust in Him, and not cast themselves down as I did,
and as the devil tried to tempt the blessed Jesus to do,
when the old deceiver quoted Scripture to accomplish his wicked purposes.
It is wrong to cast ourselves down,
and it is nearly as bad to stay down in the cellar a moment longer than we can help it.
A cellar is a cold, damp and sickly place, and it is equally unwholesome for body or mind.
Come up out of it as soon as you can, and hold fast the shield of faith.
Don`'t cast it away, as though it had never been anointed with oil; for if you hold on,
the Master will bring you up out of the horrible pit, and out of the miry clay,
and set your feet upon a rock, and establish your goings; yes,
He will put a new song into your mouth, even praises to our God; yes,
He will enable you to sing a song of deliverance, even one of the holy songs of Zion,
to his praise.

In one of his instructive conversations, Christopher said:

I remember when I was in England,
I had one day eaten something which gave me severe pain;
and while I was suffering therefrom I was betrayed into irritability of temper,
by not keeping so close a watch over my spirit as I ought to have done;
and in consequence I said two or three words, for which my conscience smote me.
I do not remember what I said,
but I recollect very well that I soon found the sting
in my conscience harder to bear than my bodily pain.
I think there were twenty or more Friends in the room, eating dinner;
but as I could not eat, I sat in my rocking chair, rocking backwards and forwards,
as long as I could; and then I spoke right out and said: "`Friends,
I cannot bear this any longer,
for I feel that I did very wrong in saying those few words just now;
but I hope I shall be forgiven for it, for I am truly sorry for having said them,
and I cannot hope to have my peace of mind restored,
until I acknowledge my fault and express my sorrow for it,
which I now do in the presence of all of you who heard me.`"

One of the company immediately said,
he did not see that I had said anything out of the way,
that I need express or feel any sorrow for; and so several others expressed themselves.
But there was a plain and simple-looking woman Friend present,
who I think was a minister, who said: "`I am truly glad that our dear friend,
Christopher Healy, has been made willing to own his fault thus publicly,
and that he has been strengthened to condemn it at once, in so decided a manner.
I, like other Friends, did not at the time perceive any evil in the words he uttered,
but I now see that he has taught us a lesson, and given us an example,
which I hope we shall all try to profit by;
for I see we are not so watchful over our spirits, and over our words, as we ought to be,
and I hope we will all endeavor to get low and humble
enough to imitate our tender-spirited friend,
in acknowledging and condemning our faults,
whenever we are betrayed through unwatchfulness, into the commission of them.
It has been, I must say, a very instructive lesson to me,
and I hope it will be so to all of us.`"

The Friend`'s remarks had a very reaching effect upon the whole company,
and I felt myself healed at once;
so that I was enabled to go that afternoon to an appointed meeting,
which proved indeed a very satisfactory one, and the Gospel message flowed through me,
as I scarcely remember it to have done before.
And I do believe that I should not have been able to have
opened my mouth that day in the way of the ministry,
if I had not been faithful in condemning my fault before all the company,
who had heard me commit it.
I know that I lost nothing in the estimation of these Friends by doing so,
but on the contrary, I am fully persuaded that they thought all the better of me.
And my heavenly Father was also well pleased with the sacrifice
which I made of self on the altar of humility and Truth.
Indeed there is no other way to true honor but by the road of humility and self abasement.

I once had an appointed meeting at +++_______+++, in the State of New York,
in which I was led to speak of the pernicious doctrine of election and reprobation,
as many persons believe in it, and are thereby led to take up a false rest,
very far from the true rest which remains for the people of God;
and which has a tendency to foster in them,
that pharisaical spirit which can thank God that they are not like other men are,
and make them look down upon those whom they in their spiritual pride,
call publicans and sinners.

There was one of the great men of this world, at meeting that day, who was a judge, and,
as I understood, a brigadier-general also.
This man did not relish the doctrine I had to deliver;
and at last he stood up and interrupted me in my discourse: and I in my freedom,
answered him as well as I was able.
After meeting he kindly invited me--indeed he did more than that,
for he pressed me very earnestly--to go home with him to dine.
I felt something more than a mere willingness to go with the man,
and told my companion that if he was free to go along,
that I thought it might be right for me to go.
As my companion was willing to bear me company, I went,
and was very kindly treated and hospitably entertained.
After dinner he said, "`I desire to have some conversation with you, sir,
in relation to the doctrine you preached this morning.`"
I told him that I was at present not very well in health,
and that I was at best but a poor weak man, and no great hand at an argument,
as I could not say anything of myself, and if Master would not help me,
I could do nothing.

But as he insisted that I should defend the doctrine I had delivered,
I consented to hear him, but told him that there were a few preliminaries,
which I would like to have settled before he began his argument.
"`As I cannot give flattering titles to men, +++[+++see Job 32:21-22],
I want to know your name and to have full liberty to call you by it,
desiring that you will take no offence by my so doing, for it is not out of disrespect,
but as a matter of conscience that I so speak.
My name is Christopher Healy, and I would much prefer you would call me by my name.`"
"`And my name`" said he, "`is Paul Todd,
and I have no objection to be called by my name.`"

"`There is another proposition +++[+++said Christopher], which I wish to make, and that is,
if I should say anything, which you should think to be too hard,
about principles and doctrines, I hope you will not take it to yourself,
so as to make a personal matter of it, and get offended with me;
for it is principles and not persons, I trust, that we are going to discourse about.
And I consent to let you say as hard things about my doctrines and principles,
as you may see fit, promising you not to be offended thereat.`"
To all which he gave his assent,
saying it would be very weak in either of us to get affronted.

After the judge had stated a few of his objections against Friends`' doctrines,
Christopher said:

"`Now, Paul Todd, from what you said in meeting this morning, and from what you say now,
I think I understand precisely where you are; I presume that you are a Presbyterian.`"
To this he assented.
"`I suppose too, that you have '`got religion,`' as your people express it.`"
"`Yes,`" he said, "`I got religion thirty years ago; and when our minister is absent,
I sometime exhort the brethren myself.`"
"`No doubt then, you are fully persuaded in your own mind that everything which happens,
past, present and to come, does so in accordance with, and in conformity to,
the fixed and unalterable decree of God; and that nothing ever did,
or ever can come to pass,
but in exact conformity with his will foreordained and determined
before the foundations of the world were laid.`"
"`Yes,`" he said, "`these are my views and belief, and they are, in my apprehension,
in strict accordance with the Bible.`"

"`Now +++[+++continued Christopher], let me put one simple case to you.
You are a judge, and as such, you have, no doubt tried many criminals.
We will suppose that some wicked man--and the wickeder he is,
the better for my purpose--comes, and, in the secrecy and darkness of midnight,
murders your innocent neighbor, or your dearest friend; and he is tried before you,
and his guilt proved in the most positive and unquestionable manner:
what would you do with him?
Condemn him to be hanged, most certainly.
But you have said that there is no act done,
but in strict conformity with the will of God.
Therefore if God fore-ordained this man to commit this very murder, who are you,
that dare to punish him for doing the will of his great Creator?
According to your belief, he could not in any way, or by any possible means,
escape from the necessity of killing this man; and must he be punished for it?
Why, this horrible doctrine makes God himself the author
of all the wickedness that is in the world!
Is it not blasphemy?
Now, Paul Todd, I want you seriously, to consider this matter,
and decide what you ought to do with criminals,
if the truth be as you have believed it to be.`"

The judge said, "`This subject has been placed before my mind in a new light.
I never so contemplated it before.
I do not know what I ought to do.`"
"`But I +++[+++said Christopher]
do know what you ought to do; and that is, give up, renounce, and utterly forsake,
all such false doctrines, which are derogatory to the character of our Heavenly Father,
who wills all men to be saved, and to come to the knowledge of the Truth.
But they limit the offices of Christ,
and detract from the merits of that most holy sacrifice,
which the dear Son of God made of Himself,
when He shed his blood on the cross for all men;
and they quench the Holy Spirit in the hearts of many;
for a manifestation thereof is given to every man to profit withal.
Our Heavenly Father long ago declared,
'`For I have no pleasure in the death of him that dies, says the Lord God,
wherefore turn yourselves and live.`' And shall we, worms of the dust,
limit the Holy One of Israel, either in his power, or his mercy,
or his lovingkindness to the children of men;
who sent not his Son into the world to condemn the world, but that the world,
through Him, might be saved?
And my advice to you, Paul Todd, is,
that you should not trust to anything which you may have received thirty years ago;
for unless you receive a renewal of the Holy Spirit from day to day,
and have fresh and heavenly nourishment ministered,
more often than the returning morning, to enable you to resist temptations,
you will die in your sins,
notwithstanding all the experiences in which you have entrenched yourself.
Yes, destruction shall suddenly come upon you, and you shall be cut asunder,
and have your portion in that eternal misery into which, as a judge,
you would send the poor wretches who have committed what are called capital crimes.`"

The judge received my close dealing without offence.
He appeared somewhat affected, and we parted friendly.
But before my return home from that journey, Paul Todd was no more.
While walking in his garden one day, he fell down and expired.

The late Christopher Healy was not only an eminently favored minister of the Gospel,
but in private conversation was unusually interesting and instructive,
so that there often seemed a measure of the same holy anointing
that was present in his ministerial communications.

On one such occasion Christopher Healy had been speaking of a Friend,
poor as to this world, in whom he felt much interested, and who had lately,
in the usual course been acknowledged a minister in our Society, when he thus continued:

As poor as +++_______+++ may be, if he will but keep his place, keep low,
and look to the Master, I have no fear for him.
The good Master will make a way for him.
Haven`'t I abundant cause to bless his holy name?
Was there ever a poorer Quaker than I was?
And hasn`'t the Lord cared for me through many long years,
and hasn`'t He now fixed me in my old age in as comfortable
a situation as my heart can wish?
Why yes!
I have a comfortable home at which I can welcome and entertain all my friends.
Ah!--this was the height of my worldly ambition,
that I should be able to accommodate my friends;
and the Lord has fulfilled the desire of my heart.
In my first wife`'s time I had hard work to keep my head above water;
but the Lord strengthened me.
My wife was very weakly, and at least half her time so sick she couldn`'t help:
so that with doctor`'s bills and other expenses,
I had to struggle with many difficulties,
having no other way to earn a living but by going out to my day`'s work.
Many a time after working hard all day at hoeing corn, or other farm labor,
I have received my half bushel of corn for my day`'s
work (for the farmers didn`'t pay us in money),
and then after sundown had to carry it on my back a mile or more to mill to get it ground.
So I couldn`'t get it home until long after I ought to have been in bed and asleep,
to prepare me for another day`'s hard work.
I remember that at one time my doctor`'s bill was so large,
that I had to hire myself out for eighteen months to get money enough to pay it.

This reminds me of a circumstance which shows how poor and weak I was,
and how easily I was discouraged.
I was indeed both outside and in, one of the poorest Quakers that ever was;
at least I thought so.
My eighteen months was out at Quarterly Meeting time,
and my father-in-law brought my wife and two of my
children down to the Quarterly Meeting to meet me.
When we were going home, father took my wife behind him on horseback,
and carried one of my children in his arms, while my wife carried the other in her lap.
Of course I had to go afoot, and I had to carry my clothes and some other little matters.
We were thirty miles from home.
Still I didn`'t mind the distance,
but there was one of the bundles which I couldn`'t contrive to carry on my back;
it wouldn`'t stay fixed: so I spoke to a Friend in company,
who was one of the overseers of our meeting,
and who had a good strong horse under him and no baggage,
to know if he wouldn`'t let me tie that little bundle behind his saddle,
telling him I did not like to be a trouble or burden to my friends,
but I did not see how I could get it along myself.
He looked anything but encouraging and said:
"`If this was all the trouble and burden you were giving Friends,
we could more easily put up with it.`"
Well, I was poor enough in spirit before, but this overset me.
I had been bleating out a few words in meeting for some time,
and now I thought surely it is all over with me.

But the Lord who knew the sincerity of my heart did not allow me to perish,
but has preserved me, and blessed me even unto this day.
That rich overseer came to poverty, and made a bad end;
but the Lord has watched over me for good, given me my life for a prey, and bid me live.
It is wonderful how little money we can get along with.
When I had concluded to move into New York State,
we gathered together all the little property we had in the world and started.
We had a wagon and that was paid for, and in it there was my wife and six children,
and all the rest of our worldly goods.
We had a horse but it wasn`'t paid for,
and when we landed on the west side of the North River,
I had just one piece of money left, and that was a half dollar.
But I soon got into a school and began to earn something;
and am preserved unto this day to praise the Lord, and to tell of his wondrous works,
and of his goodness to the children of men.

These remarks of Christopher, writes the Friend who heard and who penned this account,
are very striking in themselves,
but they had an additional force to those who heard them, from the animation of manner,
and lively energy in the delivery.
He sat and rocked on his chair as he spoke,
and at times his voice would mellow away to a solemn melody,
especially when he was speaking of the Lord`'s mercies to him.
A feeling of thankfulness seemed very much the constant clothing of his mind,
and he loved to tell others of the riches of the
mercy and providential care of the Lord Jesus,
towards and over his dependent little ones.
A very short time before he was taken sick with his last illness, coming to his own home,
perhaps after a chilly ride,
and finding everything comfortably prepared for him in his little sitting-room,
and a good fire blazing on the hearth,
he sat down and seemed overcome by the thankful emotions of his heart.
He could not forbear to speak of the Lord`'s mercies to him,
of the promise made him in early life of future earthly things, if he would be faithful,
and of the fulfilment he then experienced.

At the Yearly Meeting in New York, in 1828,
after the Hicksite separation had been effected,
Friends of that meeting appointed a Committee to visit the subordinate meetings,
to strengthen the hands of the faithful few who remained in them.
Christopher Healy was soon afterwards attending meetings
within the limits of that Yearly Meeting,
and reached the house of a Friend at Bridgewater the day
before that on which the Monthly Meeting was held there.
He found the Friend very much cast down in mind, his faith being at a low ebb.
He told Christopher that the Yearly Meeting`'s Committee would be at the Monthly Meeting,
and that, of course, a separation must take place, when he expected only Zeno Carpenter,
himself and two others would remain with Friends,
and then the Hicksites would take up their cases and disown them directly.
Christopher knew that to look on the dark side of
things was a constitutional failing in his friend,
so he answered to this effect: "`I knew you of old in Connecticut,
and you were always living in the cellar.
It is a cold, damp, nasty place,
and will give you your death of cold if you don`'t get out of it.
I don`'t want you to get into the garret, either, but to live in the house.`"

At this meeting the body of the members were sadly unacquainted
with the causes which had led to the separation,
which was then spreading throughout most of the Yearly Meetings on the continent.
They had been informed that no doctrinal difference was at the bottom of it,
but only some personal dispute between the elders of Philadelphia and Elias Hicks.
As the account of the dispute was given to them by the friends of Elias,
they were disposed to think wrong had been done him,
and were prepared to give their strength to his cause.
Such appeared to be their situation when they went to meeting the next day.

When Christopher entered the meetinghouse,
he saw H. J. (an aged and noted advocate of Elias Hicks),
sitting at the head of the gallery, and he took his seat below him.
Several members of the Yearly Meeting`'s Committee were also there, and one of them,
a female, was soon on her feet.
Christopher was somewhat startled and distressed at this, thinking,
as he said when he related it, "`that it was not day yet.`"
However, as she proceeded,
he found that a good measure of life and light attended the communication,
and he had to acknowledge she "`had seen the sun`" before him.
After a time he "`saw the sun,
too,`" and he was brought under the necessary exercise
which prepared him to stand on his feet.
Soon after she sat down,
Christopher believed it right for him to lay open the faith of the Society of Friends,
and to contrast it with that publicly preached by Elias Hicks and his followers.
The letter of George Fox to the governor of Barbados being brought to his mind,
he repeated it, and then observed that this contained the doctrine of Friends,
but that the Hicksites did not believe that their
Saviour was crucified outside the gates of Jerusalem.

The meetinghouse was very much thronged,
for throughout the whole neighborhood it was known that
a separation would be likely to take place that day,
and people of all persuasions came to see what would take place,
and appeared to listen with interest to what was delivered.
When Christopher sat down, his next neighbor, H. J., arose.
He was very deaf,
and commenced by saying that he had not heard one word that had been said,
but that he had felt a weight of darkness,
and he wished all present to know that his Saviour
was never crucified outside the gates of Jerusalem.
In this part of his discourse he repeated nearly the very words which
had been used in describing the faith of the party he was there to support.
// lint-disable invalid-characters
The exposé by Christopher,
and its confirmation by one of the leaders among the Hicksites,
produced a powerful effect upon the members of that meeting.

When they were ready to proceed to business,
the minute of the appointment of the Yearly Meeting`'s
Committee was presented to the meeting.
The question was thus raised: "`Shall the Committee be recognized?`"
If this were done,
it would at once show that the Monthly Meeting intended to continue a meeting of Friends,
and to reject the Hicksites.
When the question came before them,
there was so great an expression of unity with this course, that the clerk,
who was himself a Hicksite,
said it was obviously the judgment of the meeting to recognize them,
but that he could not make a minute to that effect, for he did not approve of it.
He, however, on being requested to leave the table, quietly did so,
and the meeting appointed Zeno Carpenter clerk.
During the discussion of the matter, some of those who had been prepared,
before the meeting, to acknowledge the supporters of Elias Hicks,
publicly accused some of the leaders of that class with having deceived them.
They said: "`You told us there was no difference between the two parties,
except a matter with Elias Hicks and the Philadelphia elders;
but now one of your own preachers publicly avows his infidelity.`"
The result of the development in this meeting was,
that nearly all the members remained with Friends.
