== Chapter I

The history of the Society of Friends is necessarily
connected with the political history of Great Britain;
and especially with the religious controversies which agitated that nation.

The Reformation on the Continent of Europe of which
Martin Luther was the most prominent instrument,
was an effort to change certain corrupt doctrines and practices
which had become established in the church of Rome.
But that in England, in the time of Henry VIII,
was more in the nature of a political movement;
and consisted principally in rejecting the claims of the Pope to supremacy.
Henry quarrelled with the Pope,
because the latter would not grant a divorce from his wife Katharine of Arragon,
whom he wished to put away, so that he might marry Ann Boleyn.
So he determined to suppress the papal authority in England,
and induced the Parliament in 1532-1533,
to pass an act prohibiting the payment to the Pope of certain moneys which had
originally been granted as an aid in maintaining forces against the infidels.
Another act prohibited any appeals to Rome,
and directed that all causes of a religious nature, as well as civil,
should be determined within the kingdom.
This was followed the next year +++[+++1534]
by another act,
which declared the king to be the supreme head on earth of the church of England,
and that he was clothed with full power to exercise spiritual authority and jurisdiction.

This transference of spiritual allegiance from the Pope
to the crown was acquiesced in by the clergy generally,
but the monks were not so yielding.
The king soon after appointed a commission to examine into the condition of the monasteries,
which were eventually suppressed and their endowments confiscated.
The colleges, chapels and hospitals, consisting of secular priests,
experienced the same treatment.
The number of monasteries dissolved is computed at six hundred and forty-five,
of colleges ninety, of chapels twenty-three hundred,
and of hospitals one hundred and ten.

Henry, in accordance with his despotic character,
did not hesitate to put to death those who refused compliance.
The laws at that time were very cruel and cruelly executed; so that during his reign,
seventy-two thousand persons are said to have died by the hand of the executioner.

One of the royal "`injunctions`" was,
that a Bible in English should be placed in every one of the regular places of worship,
so that the parishioners might conveniently resort to and read it.
A+++.+++ W. Hone, of the Trinity College, Oxford,
in his work on the history of the English church says:
"`This translation of the Bible was received with the greatest delight; people,
instead of, as formerly,
being obliged to read it secretly in woods and retired
places were now permitted to read it openly;
those who could afford it, bought the book;
sometimes several neighbors clubbed together and bought it in common;
many aged people learned to read, in order that they might be able to read their Bible;
the Bible became the great topic of the day.`"

Although the tendency of this study of the Scriptures was to undermine
the authority of those false doctrines which had been held in the Church,
and to pave the way for further reformation,
yet many of the old Romish errors were retained by Henry VIII and his advisors,
such as the presence of images in the places of worship, praying to saints and angels,
the observance of holy days, and of many rites and ceremonies, a belief in purgatory,
the necessity of confession, and the benefit of absolution,
the forbidding of priests to marry, and the unreasonable doctrine,
that in what is called the sacrament, there is present under the forms of bread and wine,
"`verily, substantially and really combined and comprehended,
the very self-same body and blood of our Saviour Jesus Christ,
who was born of the Virgin Mary, and suffered upon the cross for our redemption.`"
Henry`'s belief in purgatory is shown by the fact, that in his will,
he left a considerable sum of money to the monks
of Windsor to be spent in masses for his soul.
"`His great object was to free England from the dominion of the Pope,
and to establish his own supremacy; any one who opposed him must suffer for it.
He would burn, and he actually did burn, on the same day (Seventh Month 30th, 1540),
six people, three for holding the doctrines of the Reformers; and three others,
priests and doctors of divinity, for upholding the supremacy of the Pope.`"

Historians state that the persecution under Queen Mary was one
of the chief causes which made England a Protestant nation.
Hone, who is strongly high church in his sentiments, remarks:
"`The folly of religious persecution cannot be better exemplified
than in the history of the English church at this period.
Henry persecuted Romanists and Protestants alike; Edward persecuted Romanists;
Mary persecuted those whom Edward favored;
and we shall soon find Elizabeth persecuting Romanists again.
We nowadays talk about the '`bloody reign of Queen Mary,`' and so it was;
so also were the reigns of her father, her brother and her sister.
It was a period when little notion of religious toleration existed;
yet the reaction of the public mind against the barbarity of burning goodly
people for their opinions was one of the causes which made England anti-Roman.`"

When Elizabeth ascended the throne,
Parliament passed an act restoring to the crown jurisdiction over the State Ecclesiastical--thus
linking the church and the State--an act which R. Barclay in his recent work
on the [.book-title]#Inner Life of the Religious Societies of the Commonwealth#,
says:
"`has entailed on our country greater evils than either
pen or tongue will ever be able adequately to tell.`"
By the act of uniformity passed at the same time,
"`He who ventured to address his Maker publicly in
other language than that of the [.book-title]#Book of Common Prayer#,
was liable to severe penalties.`"

The new order of things was willingly submitted to by most of the laity,
and of the ninety-four hundred clergy there were very few who refused to conform,
and so loose their livings.
William Penn, in his preface to the [.book-title]#Journal of George Fox#,
after speaking of several stages in the great reformation in the Christian church
from the darkness and corruption which at one time had overspread it,
says:

The eternal,
wise and good God was pleased in his infinite love to honor
and visit this benighted and bewildered nation +++[+++England]
with his glorious day-spring from on high;
yea with a most sure and certain sound of the word of life and light,
through the testimony of a chosen vessel.
People were directed to the light of Jesus Christ within them,
as the seed and leaven of the kingdom of God; near all, because in all,
and God`'s talent to all:
The gift and grace of God to life and salvation that appears to all,
though few regard it.
God owned his own work, and this testimony did effectually reach, gather,
comfort and establish the weary and heavy laden.
They no sooner felt his power and efficacy upon their souls,
but they gave up to obey Him in a testimony to his power,
and with resigned wills and faithful hearts, through all mockings, contradictions,
beatings, prisons,
and many other jeopardies that attended them for his blessed name`'s sake.

The more that which God required seemed to cross man`'s wisdom,
and expose them to man`'s wrath,
the more God appeared to help and carry them through all to his glory.
As God had delivered their souls of the wearisome burdens of sin and vanity,
and filled them with the good things of his house,
they went forth to all quarters of these nations to declare to the inhabitants thereof,
what God had done for them.
Their testimony was to the principle of God in man,
the precious pearl and leaven of the kingdom,
as the only blessed means appointed of God to quicken, convince and sanctify man.
They waxed strong and bold through faithfulness;
and by the power and spirit of the Lord Jesus became very fruitful;
thousands in a short time being turned to the truth
through their testimony in ministry and sufferings.
For they were diligent to plant and to water,
and the Lord blessed their labors with an exceeding great increase,
notwithstanding all the opposition made to their blessed progress, by false rumors,
calumnies, and bitter persecutions;
so that they seemed indeed to be as poor sheep appointed to the slaughter.

The rapid growth of the Society of Friends was due mainly to the secret,
Divine power of Jesus Christ,
without which there is no quickening and regenerating of dead souls.
So thoroughly convinced of this were those early ministers of glad tidings,
that they did not dare to pray or preach when they pleased,
but as Christ their Redeemer prepared and moved them by his own blessed spirit,
"`for which they waited in their services and meetings,
and spoke as that gave them utterance.`"
Their fundamental principle was the light of Christ within,
as God`'s gift for man`'s salvation.
"`This,`" says William Penn,
"`Is as the root of the goodly tree of doctrines that grew and branched out from it.`"

George Fox has left the following testimony:

When the Lord God and his Son Jesus Christ sent me forth
into the world to preach his everlasting Gospel and kingdom,
I was glad that I was commanded to turn people to that inward light, spirit and grace,
by which all might know their salvation and their way to God;
even that Divine spirit which would lead them into all Truth,
and which I infallibly knew would never deceive any.

In harmony with these declarations is that of Francis Howgill,
an eminent minister among our early Friends, who says:

God hath brought us forth in our age, to bear witness unto Him, and unto that life,
power and light, by which we are quickened and raised out of the grave of sin and death,
to live unto Him, and serve Him in newness of life;
and to confess unto his holy name and power by which we are saved,
illuminated and directed.

While our primitive Friends were thus careful to call the attention of the people
to the transforming and regenerating work of the spirit of Christ,
yet they by no means ignored the blessed effects
of the coming and sufferings of the Son of God,
his Divine character and the atonement for the sins of mankind wrought by Him.
This is clearly shown by the following extracts from the writings of William Penn.

In an epistle to John Collenges, he says:
"`I do heartily believe that Jesus Christ is the only true and everlasting God,
by whom all things are made that are made in the heavens above, or in the earth beneath,
or the waters under the earth; that He is as omnipotent, so omniscient and omnipresent,
therefore God.`"

In the invalidity of John Faldo`'s vindication, William Penn says:
"`We are led by the light and spirit of Christ with holy
reverence to confess unto the blood of Christ shed at Jerusalem,
as that by which a propitiation was held forth to the remission
of sins that were past through the forbearance of God,
unto all that believed.`"

John Banks, another valuable minister among our early Friends, bears a similar testimony:
"`We as truly believe in that same Christ who laid down his body, and took it up again,
as in his light within, and we have benefit to salvation by the one as well as the other,
and of both, they being one.`"

The most conspicuous of the instruments raised up by God to afresh proclaim
the spiritual nature of true religion and to call the attention of the
people to the internal workings of the spirit of Christ,
as the means by which they were to be regenerated and made fit for the kingdom of heaven,
was George Fox, a native of Leicestershire, who was born in 1624.
In his childhood he was more religious, inward,
solid and observing than was usual for persons of his age.
Continuing in this retired frame of mind,
and frequent communion with his Father in heaven he was gradually
prepared for the work to which the Lord had appointed him.
In the year 1652, when upon a high mountain in Yorkshire, waiting upon the Lord,
he had a vision in which his eye was directed northward,
beholding a great people which should receive him and his message in those parts.
Upon this mountain he was moved of the Lord, to sound out his great and notable day,
as if he had been in a great auditory, and from thence he went north,
as the Lord had shown him.
Many were convinced by his ministry, who,
after the knowledge of God`'s purging judgments in themselves,
and sometime in waiting in silence upon Him,
felt the Divine motions to speak in his name, and were led to exhort the people,
and to call them to repentance, and to turn to the light of Christ within them.
They suffered great hardships for this their love and good will, being often stoned,
beaten, whipped and imprisoned, though honest men and of good report where they lived.
And though the priests generally set themselves to oppose them,
and insinuated most false and scandalous stories to defame them,
yet God was pleased so to fill them with his living power,
that there was a mighty convincement over those parts.

The seed sown by these faithful laborers in God`'s vineyard,
in many cases fell on good ground,
on hearts which had been prepared for its reception by the operation of God`'s grace.
Of this, the biographies of our early Friends furnish many instances.
It is related of Thomas Wilson, who became an eminent minister,
that in his youth he had hungerings after righteousness,
and the true knowledge of the living God.
Being convinced that God is a spirit, and that they that worship Him,
must worship Him in spirit and in truth; he greatly longed to know this worship.

About this time he went into an evening meeting of the people called Quakers,
with strong desires to the Lord,
that if it was the true way of salvation which this people preached,
he might have some inward feeling and testimony thereof in his own heart.
After sitting some time in silence, a Friend began to speak,
directing and exhorting to an inward waiting upon the Lord in faith,
to receive power from Him over every unclean thought, etc.,
by which heavenly power they might glorify and praise the name of the Lord,
through the ability of his own free gift.
Thomas understood this to be the holy Word of God which the apostle preached,
and to which he turned the minds of the people;
and he felt his soul much in love therewith, saying in his heart:
"`This is what I greatly wanted.`"
The Lord`'s power arose in the meeting to the breaking and tendering his heart,
and inward cries were raised in him to this effect: "`O Lord,
create in me a clean heart.`"

His heart was now opened to receive the Truth,
and he felt the Lord`'s anger because of sin,
and was made willing to love and dwell under his righteous judgments,
being truly convinced that this was the way to come unto the mercy-seat.
He saw that he was to cease from the doctrines of men,
and mind the gift which was in him, and sit down among Friends in their silent meetings,
to wait on the Lord in retiredness of mind, for his heavenly teachings and holy leadings.
In the performance of this inward, Divine and heavenly worship, he,
with many more young people, was convinced of the inward work of God,
and turned to the Lord with all their hearts.
Those who attended the meeting, became very tender and heavenly-minded,
and in great love towards each other,
the heart-tendering power of the Lord being renewedly felt, inwardly revealed,
when no words were spoken.
Under the sanctifying and forming hand of the Lord,
our friend was raised up and qualified to bear public testimony in his name.

Thomas Wilson grew in the gift of the ministry and his services in that
line were often attended with an unusual extension of Divine power.
Among the incidents illustrating this is one where two men of high rank attended a public
meeting in which some ministers of the Society of Friends were concerned to preach.
After a time Thomas arose, and being of rather mean appearance,
one of the strangers said to the other, Let us go,
that man cannot say anything worth listening to.
The other replied, No, that is the prophet Jeremiah, let us hear what he has to say.
Thomas spoke with so much Gospel authority that the men were greatly impressed,
and at the close one of them stood up,
and desired he might be forgiven for having despised
one of the greatest of the Lord`'s messengers.

In company with Thomas Story he attended a meeting at Oxford, of which Thomas Story says:
"`We had a comfortable, open meeting; for though many of the collegians were there,
who used to be rude in an extraordinary manner,
yet the power of the Word of life being over them at that
time they were quiet under the testimony thereof,
in the authoritative ministry of Thomas Wilson;
whose voice was as thunder from the clouds, with words penetrating as lightning.`"
He adds: "`Many of them were struck with amazement and surprise,
and their eyes were filled with tears.`"

His Journal mentions his having been at Oxford on a previous occasion.
He says:

I went into that city on a First-day morning, in great fear and humility,
being a stranger to all Friends there, and sat me down in a corner of the meetinghouse.
Friends sat by the sides of the house,
and left the middle empty for the rabble (as I thought).
We having sat a little time, a Friend began to speak,
and had spoken but a very few words before the scholars came in,
in such abundance that I supposed they filled the middle part of the house;
the Friend sat down as soon as they came in, and the meeting being in silence,
they began to talk one to another, and spy out who would preach;
and seeing me like a traveller, said, that in the corner, looking rudely upon me:
and thus talking one to another for some time,
the word of the Lord was strong in my heart to preach unto them; but I was first to say,
Sit down, young men, we shall be glad of your company so long as you are civil;
which done, they all sat down, and began to listen earnestly what I would say;
I preached the way to the kingdom of heaven, to be in Jesus Christ,
regeneration and to be born again;
and that blessed Jesus taught this doctrine to Nicodemus: "`Except a man be born again,
he cannot see the kingdom of God.`"
And though he was a master or teacher in Israel, yet, being carnally-minded,
he could not understand these things;
neither can any carnally-minded men now know the things of God,
for no man knoweth the Father but the Son, and he to whomsoever the Son will reveal Him.
So those that preach against revelation,
they preach against the true knowledge of the living God, and life eternal.
And so went on preaching as it opened in me: the scholars went away quietly,
and the meeting ended in prayer to Almighty God.

When travelling in Ireland, Thomas Wilson attended the Province Meeting at Castle Dermot.
He says:

It was large, and divers able Friends in the ministry were there;
but I was very low in my mind, and did not go up into the gallery,
but sat down a little within the door, and many people came in,
so that the place about where I sat was much thronged,
it being a time that the rabble sort of people were very rude.
Several such were there that day, and I, being under great exercise of spirit,
the powerful word of the Lord filled my heart;
so I stood up and preached the Gospel in the demonstration
of the spirit and power that was upon me.
The rude rabble were astonished, and became very quiet,
and the Lord`'s heavenly power did shine forth gloriously,
under a weighty sense whereof the meeting held and concluded.

His dear friend and travelling companion, James Dickinson, relates that,
when they were journeying in Wales, an informer "`Came to Haverford West,
with a justice to assist him.
The power of the Lord was so eminently with Thomas in his testimony,
that the justice said: '`If these be the Quakers, I never heard the like.
Let them alone.`' In the time of this journey many
were convinced and turned to the Lord`'s teaching.`"

In the [.book-title]#Life of Jane Hoskins#, she mentions being at a meeting with Thomas Wilson in 1714,
at Plymouth, Pa. She says:

He spoke largely on the passage of the captive maid,
and her service to her Lord and Master,
and in a powerful manner set forth the privileges which the true
members of the church of Christ enjoy under his peaceable government.
This and divers other subjects which he mentioned,
greatly affected me and reached me in such a manner, that I was much broken,
and said in my heart:
"`Surely all here will be not only convinced but converted by the
Eternal Word of God unto the true faith of Christ our Lord,
who came to seek and to save all who should believe in his pure name.`"
I thought none could withstand the doctrine preached,
it being with great power and Divine authority,
not as that of the scribes or hireling priests.
What made it further remarkable to me was that the Friend
where they dined insisted on my going with them.
With fear and trembling I complied, and being sat down in the house,
Thomas Wilson fixed his eyes upon me,
which made me conclude he saw something in me that was wrong.
I arose and went out, being much affected, but heard him say: "`What young woman is that!
She is like the little captive maid I have been speaking of this day.
May the God of my life strengthen her.
She will meet with sore trials, but if she is faithful,
the Lord will fit her for his service.`"

The experience of George Fox was similar to that of Thomas Wilson.
He passed through many exercises and conflicts of spirit
preparatory to his coming forth as a minister of the Gospel,
some of which, as he afterwards saw,
were designed to give him a heartfelt experience that would better
fit him for declaring to others the mysteries of God`'s kingdom.
His Journal interestingly and instructively shows how one thing
after another was opened to his mind by the spirit of the Lord.

About the beginning of the year 1646, he says,
the Lord opened to him that none were true believers but
such as were born of God and passed from death to life.
At another time, he was made to see that to be educated at Oxford or Cambridge,
which were the great theological schools of England,
was not enough to qualify men to be ministers of Christ.
He adds: "`I wondered at it, because it was the common belief of people.
At another time it was opened in me '`That God, who made the world,
did not dwell in temples made with hands.`' This, at the first, seemed strange,
because both priests and people used to call their temples or churches, dreadful places,
holy ground, and the temples of God.
But the Lord showed me clearly that He did not dwell in these temples,
which men had commanded and set up, but in people`'s hearts.`"

His growth in Divine knowledge was attended with many trials and temptations,
which continued upon him for several years.
In 1647 there was a great meeting of Baptists in Leicestershire,
to which George Fox went, and where, he says: "`The Lord opened my mouth,
and his everlasting Truth was declared among them,
and the power of the Lord was over them all.`"

In looking back at the experiences through which he had passed,
this servant of Christ says he saw that he had been
brought through the very ocean of darkness and death.
"`The same eternal power of God,
which brought me through these things was that which afterwards shook the nations,
priests, professors and people.`"
In 1648 he appears to have entered more fully into his Gospel labors,
and mentions attending many large meetings,
in which "`several tender people were convinced.`"

At a great meeting at Leicester, held in a steeple-house,`" a woman asked a question,
out of Peter: "`What birth that was, '`A being born again of incorruptible seed,
by the word of God, that liveth and abideth forever?`'`" The priest said:
"`I permit not a woman to speak in the church,`"
though he had before given liberty for any to speak.
"`Whereupon,`" says George Fox, "`I stepped up and asked the priest:
'`Dost thou call this place (the steeple-house) a church?`' '`Or dost
thou call this mixed multitude a church?`' For the woman asking a question,
he ought to have answered it, having given liberty for any to speak.
But, instead of answering me, he asked me what a church was?
I told him, '`The church was the pillar and ground of Truth, made up of living stones,
living members, a spiritual household, which Christ was the head of;
but He was not the head of a mixed multitude,
or of an old house made up of lime, stones and wood.
This set them all on fire.`"

When in the vale of Beavor, one morning, as he was sitting by the fire,
a temptation beset him, which he thus narrates:

It was said, "`All things come by nature;`" and the elements and stars came over me,
so that I was in a manner quite clouded with it.
But as I sat still and said nothing, the people of the house perceived nothing.
And as I sat still under it and let it alone, a living hope and a true voice arose in me,
which said: "`There is a living God, which made all things.`"
Immediately the cloud and temptation vanished away, and life rose over it all;
my heart was glad, and I praised the living God.
After some time I met some people who had a notion that there was no God,
but that all things come by nature.
I had a great dispute with them, and overturned them, and made some of them confess,
that there is a living God.
Then I saw that it was good that I had gone through that exercise.

This incident suggests the following lines by J. G. Whittier:

Still, as of old in Beavor`'s Vale,
O man of God! our hope and faith
The elements and stars assail,
And the awed spirit holds its breath,
Blown over by a wind of death.

Takes nature thought for such as we,
What place her human atom fills,
The weed-drift of her careless sea,
The mist on her unheeding hills?
What recks she of our helpless wills?

Strange god of force, with fear, not love,
Its trembling worshipper! Can prayer
Reach the shut ear of fate, or move
Unpitying energy to spare?
What doth the cosmic vastness care?

In vain to this dread unconcern
For the All-Father`'s love we look;
In vain, in quest of it, we turn
The storied leaves of nature`'s book,
The prints her rocky tablets took.

I pray for faith, I long to trust;
I listen with my heart, and hear
A Voice without a sound: "`Be just,
Be true, be merciful, revere
The Word within thee: God is near!

"`A light to sky and earth unknown,
Pales all their lights: a mightier force
Than theirs the powers of nature own,
And, to its goal, as at its source,
His Spirit moves the universe.

"`Believe and trust. Through stars and suns,
Through all occasions and events,
His wise paternal purpose runs;
The darkness of his providence
Is star-lit with benign intents.`"

O joy supreme! I know the Voice
Like none besides on earth or sea;
Yeah, more, O soul of mine rejoice,
By all that He requires of me,
I know what God himself must be.

No picture to my aid I call,
I shape no image in my prayer;
I only know in Him is all
Of life, light, beauty, everywhere,
Eternal Goodness here and there!

I know He is, and what He is
Whose one great purpose is the good
Of all. I rest my soul on his
Immortal love and fatherhood;
And trust Him, as his children should.

Not less that his restraining hand
Is on our selfish seekings laid,
And, shorn of words and works, we stand
Of vain illusions disarrayed,
The richer for our losses made.

I fear no more. The clouded face
Of nature smiles; through all her things
Of time and space and sense I trace
The moving of the Spirit`'s wings,
And hear the song of hope she sings.

During the three years, 1646, 1647 and 1648, many were convinced,
and divers meetings of Friends were established.
George Fox`'s labors at that period appear to have been chiefly in Nottinghamshire,
Derbyshire and Leicestershire, in the central parts of England.
The message he was constrained to deliver he thus describes:

I was sent to turn people from darkness to the light,
that they might receive Christ Jesus; for to as many as should receive Him in his light,
I saw He would give power to become the sons of God.
I was to direct people to the Spirit that gave forth the Scriptures,
by which they might be led into all Truth and up to Christ and God,
as those had been who gave them forth.
I was to turn them to the grace of God and to the Truth in the heart,
which came by Jesus; that by this grace they might be taught,
which would bring them salvation, that their hearts might be established by it,
their words might be seasoned and all might come to know their salvation nigh.
I saw Christ died for all men, was a propitiation for all,
and enlightened all men and women with his Divine and saving light,
and that none could be true believers but those who believed therein.
I saw that the grace of God, which brings salvation, had appeared to all men,
and that the manifestation of the Spirit of God was given to every man to profit withal.

At Nottingham,
he attended a meeting in the "`steeple-house,`" when
the priest took for his text these words of Peter:
"`We have also a more sure word of prophecy, whereunto ye do well that ye take heed,
as unto a light that shineth in a dark place,
until the day dawn and the day-star arise in your hearts.`"
George Fox says: "`He told the people this was the Scriptures,
by which they were to try all doctrines, religions and opinions.
Now the Lord`'s power was so mighty upon me and so strong in me, that I could not hold,
but was made to cry out: '`Oh, no,
it is not the Scriptures,`' and told them it was the Holy
Spirit by which the holy men of God gave forth the Scriptures,
whereby opinions, religions and judgments were to be tried, for it led into all Truth,
and so gave the knowledge of all Truth.
The Jews had the Scriptures, and yet resisted the Holy Ghost and rejected Christ,
the bright morning star.`"

Although a prison was the result of this speech,
in which he remained a considerable time, yet some of the hearers were tenderly affected,
among them the High Sheriff, who sent for him from the prison,
and lodged him at his house, where he had "`great meetings.`"
The sheriff was so much brought under the influence of Divine grace
that he sent for a woman whom he had wronged in the way of trade,
and made restitution to her;
and on a market-day preached repentance to the people in the streets.

When at Derby, George Fox was arrested and taken before the magistrate, who, he says:
"`Ran into many words, but I told them they were not to dispute of God and Christ,
but to obey Him.
The power of God thundered among them, and they did fly like chaff before it.`"
He continued in prison here about a year, during which time he labored much with his pen,
warning evil-doers and strengthening the faith of those
who were convinced of the truths which he preached.

After his release from prison, and some further labor in the central part of England,
he went into Yorkshire.
At Beverly, in the "`steeple-house,`" when the preacher had finished, he says:
"`I was moved to speak to him and to the people, in the mighty power of God,
and turned them to their teacher, Christ Jesus.`"
The impression made upon the minds of some of his auditory may
be seen from the remark of a "`great woman`" who was present,
who afterwards told Justice Hotham that "`there was
an angel or spirit came into the church at Beverly,
and spoke the wonderful things of God to the astonishment of all that were there;
and when it had done, it passed away, and they did not know whence it came,
nor whither it went, but it astonished all present, professors and magistrates.`"

George Fox labored abundantly in the northern parts of England,
and very many were convinced of the truth of the doctrines proclaimed.
In the course of his visit he came to Fairbank Chapel, in Westmoreland,
where Francis Howgill and Edward Burrough had been preaching in the forenoon.
While the others were gone to dinner George came
and sat down on the top of a rock hard by the chapel.
About a thousand people gathered about him,
to whom he declared God`'s everlasting truth and
word of life for about the space of three hours,
directing all to the spirit of God in themselves,
that they might be turned from darkness to light,
and might come to know Christ to be their teacher to instruct them,
their bishop to oversee them, and their prophet to open Divine mysteries to them.
He says:
"`The Lord`'s convincing power accompanied my ministry
and reached home to the hearts of the people,
whereby many were convinced,
and all the teachers of that congregation (who were
many) were convinced of God`'s everlasting truth.`"

At Ulverston and Swarthmore, among those who were convinced, was the family of Judge Fell.
His wife, Margaret Fell, who, some years after her husband`'s death, married George Fox,
has left a graphic account of the first sermon he preached at Ulverston "`steeple-house.`"

When they were singing, before the sermon, he came in, and when they had done singing,
he stood upon a seat or form, and desired that he might have liberty to speak,
and he that was in the pulpit said he might.
And the first words that he spake were as followeth:
"`He is not a Jew that is one outward, neither is that circumcision which is outward;
but he is a Jew that is one inward, and that is circumcision which is of the heart.`"
And so he went on and said that "`Christ was the light of the world,
and lighteth every man that cometh into the world,
and that by this light they might be gathered to God,`" etc.
I stood up in my pew and wondered at his doctrine, for I had never heard such before.
And then he went on and opened the Scriptures and said:
"`The Scriptures were the prophets`' words and Christ`'s, and the apostle`'s words,
and what, as they spoke, they enjoyed and possessed,
and had it from the Lord,`" and said: "`Then, what had any to do with the Scriptures,
but as they came to the Spirit that gave them forth.
You will say: Christ saith this, and the apostles say this; but what canst thou say?
Art thou a child of light and hast walked in the light,
and what thou speakest is it inwardly from God?`"
etc.; this opened me so, that it cut me to the heart,
and then I saw clearly we were all wrong.
So I sat down in my pew again and cried bitterly.

She goes on to say that there was a great convincement in those parts,
meetings were settled, and during the year he continued to labor there alone,
twenty-four ministers were brought forth that were ready to go,
with their testimony of the eternal Truth, to the world.
This was in 1652.

It was not the natural eloquence of George Fox that produced such remarkable results,
but the extension of Divine power.
To this he alludes when speaking of a visit he paid to Kendal: "`So dreadful,`" he says,
"`was the power of God upon me, that people flew like chaff before me into their houses.
I warned them of the mighty day of the Lord,
and exhorted them to hearken to the voice of God in their own hearts,
who was now come to teach his people himself.
Several were convinced.`"

At a very large meeting near Cockermouth, many hundreds were convinced.
And so at Brigham, in that neighborhood,
where the multitude who had gathered were directed to the spirit of God in themselves,
by which they might come to have heavenly fellowship, "`many hundreds were convinced.`"
"`Near Langlands, in Cumberland,
we had a general meeting of thousands of people atop of a hill.
A glorious and heavenly meeting it was, for the glory of the Lord did shine over all.
Their eyes were turned to Christ, their Teacher.`"
In 1654,
it is stated that the Lord had raised up above sixty ministers in the north country,
and about that time sent many of them to labor in the southern parts of England.

George Fox`'s first visit to the south of England appears to have been as a prisoner.
As a measure of precaution, in the unsettled condition of things in England,
Oliver Cromwell, then at the head of the government,
had appointed certain military officers to watch over affairs in their respective districts.
One of these was Colonel Hacker, who resided at Leicester.
When George Fox went to that neighborhood,
he was arrested and brought before Colonel Hacker, who asked him to go home,
and not go to meeting.
This George refused to do, but said,
"`I must have my liberty to serve God and to go to meetings.`"
There was at that time some rumor of a plot against Oliver Cromwell,
which probably rendered the colonel more determined in his course,
and he told George that he would send him to the Lord Protector.
"`Whereupon,`" says the Journal, "`I kneeled on his bedside,
and besought the Lord to forgive him; for he was as Pilate,
though he would wash his hands;
and when the day of his misery and trial should come upon him,
I bid him then remember what I had said to him.`"
This Colonel Hacker had been one of the Judges of Charles the First,
and after the death of Cromwell, and the return to power of the Stuart family, he was,
with many others, put to death.
In the day of his misery and trial he remembered
the warning which he had received from his prisoner.

After George Fox`'s arrival in London, he wrote a paper to the Protector,
wherein he says: "`I did deny the wearing or drawing of a carnal sword,
or any other outward weapon against him or any man.
And that I was sent of God to stand a witness against all violence,
and against the works of darkness.`"
After some time he was sent for to Whitehall, the residence of Oliver Cromwell.
His account of the interview is interesting:

When I came in I was moved to say:
"`Peace be in this house;`" and I exhorted him to keep in the fear of God,
that he might receive wisdom from Him; that by it he might be ordered,
and with it might order all things under his hand unto God`'s glory.
I spoke much to him of Truth,
and a great deal of discourse I had with him about religion;
wherein he carried himself very moderately.
But, he said, we quarrelled with the priests, whom he called ministers.
I told him I did not quarrel with them, they quarrelled with me and my friends.
But, said I, if we own the prophets, Christ and the apostles,
we cannot hold up such teachers, prophets and shepherds as the prophets,
Christ and the apostles declared against;
but we must declare against them by the same power and spirit.
Then I showed him that the prophets, Christ and the apostles declared freely,
and declared against them that did not declare freely, such as preached for filthy lucre,
divined for money and preached for hire, and were covetous and greedy.
As I spoke, he several times said, it was very good, and it was truth.
As I was turning +++[+++to leave]
he caught me by the hand, and with tears in his eyes, said "`Come again to my house;
for if thou and I were but an hour a day together,
we should be nearer one to the other;`" adding that "`he
wished me no more ill than he did to his own soul.`"
I admonished him to hearken to God`'s voice,
that he might stand in his counsel and obey it; and if he did so,
that would keep him from hardness of heart.

Cromwell was convinced that he had nothing to fear
from any plots by George Fox and his friends,
and ordered him to be liberated.
Before he left the building, he was taken, by order of the Protector,
into the dining-hall.
But the sturdy Quaker bid them let the Protector know that
he would not eat of his bread nor drink of his drink.
When he heard this, he said: "`Now I see there is a people risen that I cannot win,
either with gifts, honors, offices or places.`"

Friends had "`great and powerful meetings`" in Leicester, to which many flocked,
and the Truth spread exceedingly.

Francis Howgill and Edward Burrough went to London
near the same time that George Fox was sent there.
In a letter to Margaret Fell they thus speak of their service:
"`We have three meetings or more every week, very large,
more than any place will contain and which we can conveniently meet in.
Many of all sorts come to us, and many of all sects are convinced; yea,
hundreds do believe,
and by the power of the Gospel declared amongst them is the witness of God raised.`"

The course they pursued is thus described in another
letter from the same Friends to Margaret Fell:
"`We get Friends on First-days to meet together in several places out of the rude multitude,
etc., and we two go to the great meeting-place which we have,
which will hold a thousand people, which is always nearly filled,
to thresh among the world, and we stay till twelve or one o`'clock,
and then pass away to where Friends are met in private.`"

Sewell, in his [.book-title]#History of the People called Quakers#, relates an incident,
which shows the zeal of Edward Burrough,
and his readiness to lay hold of all opportunities to preach the Gospel,
when called of the Lord so to do:

At London there is a custom, in summer time,
when the evening approaches and tradesmen leave off working,
that many lusty fellows meet in the fields to try their skill and strength in wrestling,
where generally a multitude of people stand gazing on around.
Now it so fell out that Edward Burrough passed by the place where they were wrestling,
and standing still among the spectators,
saw how a strong and dexterous fellow had already thrown three others,
and was waiting for a fourth champion, if any durst venture to enter the lists.
At length, none being bold enough to try,
Edward Burrough stepped into the ring (commonly made up of all sorts of people),
and having looked upon the wrestler with a serious countenance,
the man was not a little surprised, instead of an airy antagonist,
to meet with a grave and awful young man, and all stood, as it were,
amazed at this sight, eagerly expecting what would be the issue of this combat.
Edward Burrough began very seriously to speak to the standers-by,
and that with such a heart-piercing power that he was heard by
this mixed multitude with no less attention than admiration,
for his speech tended to turn them from darkness to the light,
and from the power of Satan to God.
To effect this he labored with convincing words,
showing how God had not left himself without a witness,
but had given to man a measure of his grace,
and enlightened every one with the light of Christ.
It was of such effect that some were convinced of the Truth.
For he was a breaker of stony hearts, though he omitted not, in due season,
to speak a word of consolation to those that were
of a broken heart and of a contrite spirit.

To thunder against sin and iniquity was his peculiar talent.
And, indeed,
he was one of those valiants whose bow never turned
back nor sword empty from the slaughter of the mighty;
for the Lord blessed his powerful ministry with very glorious success.

His bosom friend, Francis Howgill, after his decease, gave forth a testimony to him,
in which he speaks of him as one that had turned many to righteousness,
and made multitudes shake with the word of life,
and was very dreadful to the enemies of the Lord, yet, to the seed of God,
"`thy words dropped like oil, and thy lips as the honey-comb.
Many a rough stone hast thou polished and squared,
and made it fit for the buildings of God,
and much knotty wood hast thou hewed in thy day.`"

Edward Burrough was a remarkable man,
eminent for his natural energy and ability and for the measure
of Divine power and authority with which he was clothed.
Although he lived but about eight years after he went to London from the north of England,
yet the work he accomplished was great.
Persecution grew hot in London, and, being at Bristol, he said to some of his friends,
"`I am now going up to the city of London again, to lay down my life for the Gospel,
and suffer amongst Friends in that place.`"
Soon after his return to that city, as he was preaching in a meeting,
he was seized by some soldiers and committed to prison and fined.
Not being easy to pay the fine, he was kept in prison, with many more,
about eight months, and, owing to the over-crowding of the rooms, was taken sick.
He was led to pray for his persecutors, one of the most cruel of whom was Richard Brown,
an alderman of London, of whom he said, "`Lord, forgive Richard Brown,
if he may be forgiven.`"
And being sensible that death was approaching, he said:
"`Though this body of clay must turn to dust,
yet I have a testimony that I have served God in my generation;
and that spirit which hath lived, and acted, and ruled in me,
shall yet break forth in thousands.`"

Among the ministers who, in 1652, were sent out by the Lord from the North,
were John Camm and John Audland, who may be regarded as the special apostles to Bristol,
as Francis Howgill and Edward Burrough were to London.
Among those convinced by their labors was Charles Marshall,
who afterwards became a valuable minister of the Gospel.
From the narrative he has given, it is evident that, as we have already stated,
the spirit of the Lord had been working on the hearts of the people,
and thus preparing the ground for the reception of the seed of the kingdom.
He says that, about the year 1654, many were seeking after the Lord.
The account he gives of the visit of John Camm and John Audland to Bristol,
is interesting and instructive.
It is headed A Testimony to the Visitation of the Love of God to the City of Bristol,
and Adjacent Parts,
and to the Mighty Power of the Lord Appearing In and With His Two Precious Servants,
John Camm and John Audland, Who Came to that City in the Year 1654.

It commences in this manner:

After the long and tedious night of apostacy and dismal darkness spread over the people,
it pleased the Lord of heaven and earth to visit this island,
and first the northern part thereof, with the morning of his ever-blessed day.
From whence came the aforesaid servants of the Lord Jesus,
having received the everlasting Gospel to preach
in the demonstration of his mighty power,
with which, indeed, they were filled.
John Camm was an ancient man, full of zeal and fervency in the Gospel,
endued with the precious gift of discerning and sound
judgment--terrible to the man of sin,
full of tenderness to the travailing soul,
and friendly to the well-inclined to the way of righteousness, not sparing his weak body,
which he offered up even unto death,
to serve the Lord God in his blessed work of gathering,
which he saw in a plentiful manner, to his great satisfaction.

John Audland was a younger man,
of a sweet and ruddy countenance and of a cheerful spirit, one of the wise in heart,
filled with the excellent power of the Lord, in which he appeared many times,
and his voice was as thunder, dreadful in the strength of the Lord of Hosts,
against the man of sin and the workers of iniquity,
but livingly tender to the sensible travailers and poor in spirit.
He was a laborer night and day in the Gospel, in which he spent himself.

These two ministers of Christ Jesus came to the city of Bristol in the Fifth Month, 1654,
amongst a seeking people, who kept one day in the week in fasting and praying;
waiting for and breathing in spirit after the visitation of God and the day of redemption.
Amongst us they spoke the powerful word of life,
in the dread of his name that lives forever, and we were smitten even to the heart,
and that day overtook us which we had longed and waited for,
and we were turned from darkness to the marvellous light of the Lord.
We had some meetings, before the more general gathering, in and about the city,
which began on this wise:

On a First-day, in the morning,
I went with these two servants of God about a mile and a half from the city,
to a little spring of water, where I had spent many solitary hours in my tender years,
seeking the Lord, where we sat some time, and drank of the spring.
After some hours of the morning were spent, I saw in them a great travail in spirit.
John Audland said, trembling: "`Let us be going into the city.`"
So we came to the street called Broadmead,
to a house where were several people met together, inquiring after these two men of God.
John Audland was under a great exercise of spirit, and said:
"`Is here any one that has an interest in any field?`"
An ancient man said: "`I have a field pretty near.`"
Notice being given to the people in the house, they came forth, and as we went along,
people in the streets went also to the field called Earlsmeade,
so that we became a pretty number, where some seats or stools were brought.

Dear John Camm began to speak tenderly and in great zeal,
directing to the heavenly grace of God,
and testifying against sin and iniquity fervently, to which some were attentive.
I perceived a great exercise on my dear friend and father in Christ Jesus, John Audland,
who very much trembled.
After dear John Camm had done, he stood up, full of dread in his countenance,
lifted up his voice as a trumpet, and said:
"`I proclaim spiritual war with the inhabitants of the earth
who are in the fall and separation from God,
and prophesy to the four winds of heaven;`" and his words dropped among the seed,
and he went on in the mighty power of God, opening the way of life.
But, ah! the seizings of soul and prickings at heart which attended that season.
Some fell on the ground, others cried out under the sense of their states,
which gave experimental knowledge of what is recorded in Acts 2:
37+++.+++ It was a notable day, worthy to be left on record,
that our children may read and tell to their children, and theirs to another generation;
that the noble acts of God may be remembered through generations.

At this meeting many were effectually convinced and turned from darkness to light,
after which our meetings grew larger.
They visited the meetings of the Independents and Baptists, testifying amongst them,
in great power, the things given them of God, directing the poor and needy in spirit,
who saw their want of the Lord Jesus Christ, no longer to seek the living among the dead,
but look from the mountains and hills, dead ways and worships, unto Christ Jesus,
the fountain of life and salvation; and there was added unto the gathering daily,
and great dread was in our meetings, under the seasonings of the Holy Ghost.

Oh, the tears,
sighs and tremblings and mournings because of the middle wall of partition that we saw,
in our awakened state,
stood between us and the Lord in the sense of our spiritual wants and necessities!
Oh, the hungerings and thirstings of soul that attended
daily and great travail of spirit to obtain,
through the working of the mighty power of God,
dominion and spiritual victory over the enemy of our souls,
who had led us in the paths of death and darkness.
The visit of God`'s holy and ever-blessed day was signal, and, in his fear and dread,
we received the Gospel with a ready mind and with broken hearts,
and gave up to follow the Lord fully,
casting off the weights and the sin that easily besets,
and departed from the evil ways and vanities of this world;
stripping off all needless apparel and forsaking superfluities in meats and drinks,
walking in the plain, self-denying path, having the fear and dread of God on our souls,
whom we were afraid of offending in word or deed.
Our words were few and savory, our apparel and houses plain,
being stripped of superfluities,
our countenances grave and deportment weighty amongst those we had to do with.

Indeed, we were a plain, brokenhearted, contrite-spirited people;
our souls being in an inexpressible travail to do
all things well pleasing in the sight of God.
Our concern, night and day, was to obtain, through Jesus Christ,
the great work of salvation, and thereby,
an assurance of the everlasting rest and sabbath of our God.
Oh, the labor, travails and spending of strength of these servants of the Most High God,
in those days, in great assemblies in that city and counties around about.
Our meetings were so large that we were forced to meet out of doors,
and that in frost and snow;
and in those meetings the voices of these servants of God reached over
the multitudes when several thousands have been assembled together.

The sixty ministers who, as has been mentioned,
went forth from the north about this time, spread themselves over almost all England,
as well as in Scotland and Ireland,
and such was their zeal and the Divine power accompanying their ministry,
that it is no marvel that, as William Penn states,
thousands in a short time were turned to the Truth through their testimony.

Our early Friends were well aware that their success depended
on the Lord`'s blessing which accompanied their labors.
William Penn says: "`Without this secret Divine power,
there is no quickening and regenerating of dead souls.`"
And again, "`These experimental preachers of glad tidings of God`'s truth and kingdom,
could not run when they list, or pray or preach when they pleased, but as Christ,
their Redeemer, prepared and moved them by his own blessed Spirit,
for which they waited in their services and meetings,
and spoke as that gave them utterance.`"
It is evident, therefore, that no amount of preaching or other effort in a religious way,
that has its root in an imitation of the proceedings of our early members,
can be expected to produce similar results,
for it is the Lord alone who can change the heart of man,
and only those labors which flow from the movings of his
Spirit can we reasonably suppose will receive his blessing.
