== Chapter IX. Ministry

There have been preserved the outlines of several of the sermons preached by George Fox,
which show the general character of the doctrines
proclaimed by that devoted servant of the Lord.
When at Firbank-chapel, where a large audience had collected,
he directed all to the spirit of God in themselves,
so that they might be turned from darkness to light, and from the power of Satan,
which they had been under, unto God;
and come to know Christ to be their teacher to instruct them,
their counsellor to direct them, their shepherd to feed them,
their bishop to oversee them, and their prophet to open Divine mysteries to them.
He told them "`That the Lord God had sent him to preach
the everlasting Gospel and word of life amongst them;
and to bring them off from all those temples, tithes, priests and rudiments of the world,
which were gotten up since the apostles`' days.`"

In his preface to [.book-title]#George Fox`'s Journal#,
William Penn says that our early Friends directed
people "`To the Light of Jesus Christ within them,
as the seed and leaven of the kingdom of God; near all, because in all,
and God`'s talent to all.`"
They taught that without the secret Divine power of Christ
there is no quickening and regenerating of dead souls.
Such was their dependence on this power,
that they taught that in Him no true worship could be performed without its assistance;
hence,
in their assemblies they exhorted all to wait on
the Lord in silence for the experience of this power,
and without this arising they believed that no one
ought to attempt the exercise of Gospel ministry.

One of the early openings made on the mind of George Fox, he thus relates:
"`As I was walking in a field on a First-day morning,
the Lord opened unto me that being bred at Oxford or Cambridge was not enough
to fit and qualify men to be ministers of Christ--and I wondered at it,
because it was the common belief of people.`"
In another place he remarks that:

In the old covenant and testament there was but one
tribe of twelve that was made a priesthood,
and they were to have no lot or portion in the land,
but tithes and offerings were their portion and salary.
But Christ in his new covenant or testament makes all his believers priests,
as Peter saith, and to offer up spiritual sacrifices,
and in his general epistle he saith: Ye are a holy nation, a royal priesthood,
a peculiar people, offering up spiritual sacrifices, having one high priest,
Christ Jesus, that lives forever; who sanctifies his people, his church,
and washes and cleanses them with the heavenly water of his word.
So his people are a nation of priests, men and women;
for all must offer up to the Lord their spiritual sacrifices in his new covenant;
for both male and female are all one in Christ Jesus.
And so He ends the first priesthood, and abolishes it,
with all its outward water and washings, and ends all its offices,
and changes the law by which it was made,
and the commandment that gave it tithes and offerings.

The views which early Friends took of what the character of a true ministry should be,
are most easily seen from the expressions of those who were
most instrumental in spreading the Truth in their day.
Thus Edward Burrough remarks that:

The true ministry is sent of God, and is the gift of the Holy Ghost,
and it stands in the power of the Spirit of God, and not in the words of man`'s wisdom,
that wisdom which is from below.
It brings people to the knowledge of God, which is life eternal,
and it turns people from darkness to light,
and from the power of Satan to the power of God, and is freely given forth of us.
It proclaims peace on earth unto such as are of a broken and upright heart,
and it proclaims war against all the wicked upon earth.
It is a good savor unto God,
in setting the way of life and the way of death before all people.

When the English Government proposed sending out a commission
for the "`trial of ministers,`" Edward Burrough writes:

Whereas there is a great cry about ministry,
for sending forth and maintaining and encouraging a godly ministry, as you say.
Now to this I do answer on my Lord`'s behalf, and I must tell you plainly,
as for a true and godly ministry, truly called and sent of God, such a ministry,
and such ministers you can never be able to hinder.
The Lord will send them out, maintaining them and preserving them,
whether you will or no;
and while you are troubling yourselves about such a matter you are but
meddling with things above your line and out of your jurisdiction.

William Penn beautifully brings out this subject of clerical education,
and elucidates the true ground on which the true ministry of the Lord Jesus is built;
he says:

We are charged as to our want of learning and external accomplishments.
It is our joy and matter of rejoicing,
and many times with unutterable thanksgivings in sincerity I can say,
that the everlasting God should now, as frequently at other times,
display the riches of his love and grace to the mean and despised among men:
herein is it transcending in our eye, that He should obscure these things,
and leave them still as mysteries to the wise world,
whilst in extreme love He has so plentifully vouchsafed
the revelation of them unto babes;
and therein made good, in our times, that ancient observation of Paul: "`Not many wise,
not many noble,`" etc., not that we do thereby exclude any,
only we can affirm that the entrance of God`'s everlasting Gospel of salvation,
or whatever He has had to do among the sons of men,
has been with seemingly very despicable attendances.

Edward Burrough describes the labors of the early ministers among Friends, as follows:

Being prepared of the Lord, and having received power from on high,
we went forth as commanded of the Lord,
leaving all relations and all things of the world behind us,
that we might fulfill the work of the Lord, unto which He called us.
With flesh and blood, or any creature, we consulted not, nor took counsel of men,
but of the Lord alone, who lifted up our heads above the world,
and all fears and doubtings,
and was with us in power and dominion over all that opposed us,
which was great and mighty.
We sounded the word of the Lord and did not spare; and caused the deaf to hear,
and the blind to see, and the heart that was hardened to be awakened;
and the dread of the Lord went before us and behind us and took hold of our enemies.

Of Edward Burrough`'s own ministry, William Crouch has left the following testimony:

He was a man of undaunted courage; though but young,
the Lord set him above the fear of his enemies,
and I have beheld him filled with power by the spirit of the Lord.
For instance, at the Bull and Mouth, when the room, which was very large,
hath been filled with people, many of whom have been in uproars,
contending one with another, some exclaiming against the Quakers,
accusing and charging them with heresy, blasphemy, sedition and what not;
that they were deceivers, and deluded the people;
that they denied the Holy Scriptures and the resurrection;
others endeavoring to vindicate them,
and speaking of them more favorably--in the midst of all which noise and contention,
this servant of the Lord hath stood upon a bench with his
Bible in his hand (for he generally carried one about him),
speaking to the people with great authority from the words of John 7:12:
"`And there was much murmuring among the people concerning him (Jesus): for some said,
He is a good man: others said, nay, but he deceiveth the people.`"
And so suitably did he speak to the present debate amongst them,
that the whole multitude were thereby overcome,
and became exceedingly calm and attentive,
and departed peaceably and with seeming satisfaction.

The most highly favored of Gospel ministers are but poor suppliants
for help and strength at the Fountain of all spiritual blessings,
and can only hand forth to the audience that which is given them.
The same inexhaustible Fountain is open to all, and from it, in our religious meetings,
all should endeavor to obtain fresh supplies of heavenly food,
not depending on others to gather for us that manna
which we ought individually to labor after.

Many years ago, in the course of a religious visit in North Carolina,
Mildred Ratcliff attended a meeting of Friends, of which she says:

Soon after taking my seat in meeting, the old proverb revived:
"`They that beg of a beggar will never be rich,`" which I expressed; and I may remark,
that although there were some whose eyes were too much outward,
when the meeting first gathered, they seemed after a little time to get more inward,
turning their attention more to the Master.
This I rejoiced to feel, being sensible it was the surest way to meet with his blessing.
Indeed it turned out so.
For the love of the Good Shepherd and Caretaker of his flock seemed
to arise more and more to the praise of his own worthy name;
who often is pleased when there is looking to Him alone, to feed his flock,
both sheep and lambs, to the full.
In this meeting, and that unexpectedly,
my heart was much enlarged towards the dear youth in the arisings of the love of Christ,
that there might be amongst them an early submission to his cross,
and a willingness to wear his yoke in the bloom and prime of their day;
so that I think we were favored with a gladdening opportunity together.
I felt thankful we did not miss this meeting.
Oh, the desire I feel, that Friends everywhere,
when they meet together to worship that God who is a spirit,
might so abide in the spirit and in the truth as professed by them,
that their worship might be truly spiritual in the sight of Him who searcheth
the hearts and trieth the reins of the children of men;
that there might not be so much outward looking as to deprive
them of that inward food which is intended for them;
but alas! there is even among Friends an itching ear.

A sentiment similar to that contained in the above extract is expressed by Richard Shackleton,
in a letter to his son:

Clouds filled with Gospel rain, wafted along by the Divine spirit,
compressed by the Almighty hand, and discharging themselves on the people,
is the perfection of instrumental help; yet,
to be looking too earnestly at these clouds and watching which way the wind (the Spirit),
is driving them, is not the way for us to profit.
"`He that observeth the wind shall not sow,
and he that regardeth the clouds shall not reap.`"

Joseph Hoag mentions in his Journal the following incident,
which illustrates the nature of Gospel ministry:

When about thirteen years of age, I was sent to the mill,
and while the grain was grinding, the miller, who was an old man,
and two others (aged men),
fell into a discourse about a travelling minister that had been among them,
of the Methodist belief.
They all agreed that he was an able minister,
and that he had preached several very good sermons in that part of the country.
They believed that the Lord had sent him,
but that in their neighborhood he had said but little,
and informed the audience that he could not preach any more, and dismissed them,
which disappointed them very much, and they thought it was not right,
and that he ought to be talked to.
They agreed among themselves, which of them should talk with him.

As I sat listening in a deep muse, a solemn feeling came over my mind,
and I felt a forcible motion to go and speak to them in
the manner which I believed the Lord required of me.
I hesitated, but fearing to delay longer, I walked up to them,
and addressed them nearly in these words: "`You are old men,
and I have been hearing your talk about the minister
that you believe the Lord sent among you.`"
They replied that they did believe the Lord had sent him.
I said to them: "`Then I have something on my mind to say to you.
If the Lord sent him, the Lord knew best what He wanted him to preach,
and certain it was that He knew all the states of the people,
and knew what to give him to preach that would be suitable for the people, and how much,
and if he preached any more, it would only be man`'s preaching,
and might not be suitable to the states of any of the meeting;
and they ought to be careful how they meddled with the man,
seeing it was his duty to mind the Lord that sent him out;
and if by their talking to him he should preach more than the Lord gave him,
then he would turn from pleasing the Lord to please man; this might offend the Lord,
that He might take his gift from him.
What an evil that would be to the man, and an injury to the cause of God!
But if they saw anything in the minister`'s preaching or conduct that was not right,
then it was their duty to talk to him, and show him his error,
for in that way they might be a help to keep him right.
I thought they had better leave him to the Lord, who they believed had sent him,
than to meddle with him in any other way.`"

I stopped, and turned from them, feeling my mind relieved and filled with peace.
Not long after this, two of these men came to my father;
one of them related to my father the occurrence, with the remark,
that in all his life he never met with such a stroke;
to think that a child of my age and looks should be able to teach him,
and that it was the truth, that he never saw into before,
so that he had not dared to say to the minister what he intended.

In 1657, George Fox was in Wales, passing through Montgomeryshire into Radnorshire.
At a place in that county he held a meeting, of which he says:

There was a meeting like a leaguer, for multitudes.
I walked a little aside, whilst the people were gathering;
and there came to me John Ap John, whom I desired to go to the people;
and if he had anything upon him from the Lord to them, he might speak in Welsh,
and thereby gather more together.
Then came Morgan Watkins to me, who was become loving to Friends, and said:
"`The people lie like a leaguer, and the gentry of the country are come in.`"
I bade him go up also, and leave me;
for I had a great travail upon me for the salvation of the people.
When they were well gathered, I went into the meeting,
and stood upon a chair about three hours.
I stood a pretty while, before I began to speak.

After some time I felt the power of the Lord over the whole assembly:
and his everlasting life and Truth shined over all.
The Scriptures were opened to them, and the objections they had in their minds answered.
They were directed to the light of Christ, the heavenly man;
that by it they might see their sins, and Christ Jesus to be their Saviour,
their Redeemer, their Mediator, and come to feed upon him, the bread of life from heaven.
Many were turned to the Lord Jesus Christ, and to his free teaching that day;
and all were bowed down under the power of God;
so that though the multitude was so great that many sat on horseback to hear,
there was no opposition.
A priest sat with his wife on horseback, heard attentively, and made no objection.
The people parted peaceably, with great satisfaction; many of them saying,
they never heard such a sermon before, nor the Scriptures so opened.
For the new covenant was opened, and the old--the nature and terms of each,
and the parables were explained.
The state of the church in the apostles`' days was set forth,
the apostacy since laid open;
and the free teaching of Christ and the apostles was set atop of all the hireling teachers;
and the Lord had the praise of all, for many were turned to him that day.

When William Edmundson was in New England in 1675,
the people were greatly distressed by the Indians,
waylaying and killing many of the inhabitants.
He says:

I travelled in many places as with my life in my hand,
leaving all to the Lord that rules in heaven and in earth.
I heard of a tender people at a place called Reading,
and with five or six Friends I went there to an ancient man`'s house,
which was a garrison; for at that time most people, except Friends,
were in garrisons for fear of the Indians.
The gates being locked, we called, and the old man opened the gate;
one of the elders was at prayer; so we stopped until he had done,
and then went into the room where several were met to exercise religion,
but they seemed to be disturbed at our coming in.
I stood still and told them: "`We came not to disturb them, for I loved religion,
and was seeking religious people;`" the old man of the house bid us sit down,
and he sat by me.

As I sat, my heart being full of the power and spirit of the Lord,
the love of God ran through me to the people.
I told them I had something in my heart to declare among them,
if they would give me leave.
The master of the house bid me speak, and my heart being full of the word of life,
I spoke of the mysteries of God`'s kingdom; and as I was speaking,
I touched a little upon the priests.
The old man clapped me on the shoulder, and said, he must stop me,
for I had spoken against their ministers.
So I stopped, for I was tender of them, and felt they were a tender people,
yet my heart was full of heavenly matter.
After a little pause I told them,
I had many things to declare unto them of the things of God, but being in that house,
must have leave of the master of it.
He bid me speak on, which I did in the demonstration of the spirit and power of the Lord;
so that their consciences were awakened,
and the witness of God in them answered to the Truth of the testimony.
They were broken into many tears, and when I was clear in declaration,
I concluded the meeting with fervent prayer to the Lord.

The old man rising up, got me in his arms, and said he owned what I had spoken,
and thanked God that he could understand it,
and said he had heard that we denied the Scriptures, and denied Christ who died for us;
which was the cause of the great difference betwixt their ministers and us.
But he understood this day that we owned both Christ and the Scriptures,
therefore would know the difference betwixt their ministers and us.
I told him their ministers were satisfied with the talk of Christ and the Scriptures,
and we could not be satisfied without the sure, inward,
Divine knowledge of God and Christ,
and the enjoyment of those comforts the Scriptures declared of,
which true believers enjoyed in the primitive times.
The old man replied with tears, those were the things he wanted.
He would not let us go until we had eaten some victuals with them,
though at that time provisions were scarce, because of the great destruction by the wars.
Thus, leaving them loving and tender; when we parted the old man wept,
got me in his arms, and said he doubted he should ever see me again.

In a paper taken down shortly previous to his removal,
Andrew Jaffray thus alludes to the memorable outpourings of the Holy Spirit,
of which he and others were made partakers,
during the time of their long imprisonment at Aberdeen:

Oh, the unutterable glory that brake forth and spread, even in this country,
wherein God Almighty raised up some mean instruments, as well as some more honorable,
and myself among others, though very unworthy!
And when thirty or forty of our ancient Friends were shut up in prison,
I cannot but remember this particular instance;
that when we were all met in the low Tolbooth, and not a word had been spoken among us,
either in praying or preaching--we breathing in our hearts for power to do the
Lord`'s will--his power at last brake in among us in a wonderful manner,
to the melting and tendering our hearts.
And though I was kept very empty a long time,
yet at last the glorious power of God broke over the whole meeting, and upon me also,
and ravished my heart--yea, did appear as a ray of Divine glory,
to the ravishing of my soul and all the living ones in the meeting.
So that some of those that were in the town council above us,
confessed to some of our number, with tears, that the breaking in of that power,
even among them, made them say one to another: "`Oh,
how astonishing it is that our ministers should say:
'`The Quakers have no psalms in their meetings;`' for such
an heavenly sound we never heard in either old or new church.`"
After this, our meetings were often filled with heavenly, Divine comfort,
to the satisfaction of our souls, and we were often overcome with the love of our God,
and many innumerable instances of his miraculous power attended us;
many of which are recorded in a book for posterity to come.
And God will tread down Satan under the feet of his power in due time,
let him rage as he will.

When Samuel Bownas was paying a visit in Scotland in 1701, he went to Jedburgh.
He says:

We went to an inn, and the landlord took us in,
withal telling us how indecently the minister had
railed against the Quakers the day before,
asserting they were the devil`'s servants, and that, by his assistance,
they did in their preaching, what was done; with very many vile words;
but observing one of his hearers taking what he had said in short-hand, he called out,
charging him not to write what he spoke at random against the Quakers;
with much more to the same effect.
We called for some refreshment, but my mind was under so much concern,
I could neither eat nor drink.
We desired to pay for what we had, and gave the landlord charge of our horses and bags,
whereby he suspected that we were going to preach.

He took me by the hand, and begged that we would not go into the street,
but preach in his house, and he would have his family together, and they would hear us.
I looked steadily upon the poor man, who trembled very much, telling him:
"`We thought it our place and duty to preach to the inhabitants of the town;
and thinkest thou,`" said I to him, "`we shall be clear in the sight of God,
whom we both fear and serve,
by preaching to thee and thy family what we are required
to preach to the people in the town?`"
The poor man, I found, was smitten in himself, and his countenance altered greatly,
but he made this reply: "`Is this the case, sir?`"
I said it was.
"`Then,`" said he, "`go, and God preserve and bless you,
but I fear the mob will pull down my house for letting you have entertainment,
and kill you for your good will.`"
I bid him not fear, for He whom we served was above the devil,
and that not a hair of our heads should be hurt without his permission.
He then seemed willing to let us go, and followed at a distance to see our treatment.

The chief street was very broad, with a considerable ascent,
and near the top of the ascent was a place made to cry things on, to which we walked,
where we paused a little, but I had nothing to do there at that time.
Returning back to the market-cross, which was at the foot of the hill,
and had an ascent of three or four steps, and a place to sit on at the top, we sat down;
but we had not sat long before a man came to us, and took me by the hand, and said,
I must go into the Tolbooth, meaning the prison.
I asked him for what?
He said: "`For preaching:`" I told him we had not preached.
"`Aye! but`" quoth he, "`The provost,`" meaning the mayor,
"`hath ordered me to put you in the Tolbooth.`"
"`For what?`"
I again replied.
"`I tell you, for preaching.`"
I told him I did not know whether we should preach or not;
and it was soon enough to make prisoners of us when we did preach.
"`Ay,`" says he, "`I ken very weel that you will preach, by your looks.`"
Thus we argued the matter, he endeavoring to pull me up, and I to keep my place:
and when he found I was not easily moved, he turned to my companion,
who likewise was unwilling to be confined.
Then he went to Samuel Robinson, our guide, who was easily prevailed on to go,
and the easier, for that he had been there but the week before with two Friends, viz:
John Thompson and Thomas Braithwaite, both of our county of Westmoreland.

By this time we had a large assembly, and Samuel Robinson,
supposing we should have a better conveniency to preach to them in the prison,
as the Friends afore-named had the week before, we were conducted there,
just by the cross where we held the parley, and put in at the door.
But Samuel soon saw his mistake,
for the week before the windows of the prison were all open,
nothing but the iron grates in the way, the windows being very large for the sake of air,
but now all were made dark, and strongly fastened up with boards.
We had been but a short time there, before a messenger came to offer us liberty,
on condition we would depart the town without preaching;
but we could make no such agreement with them, and so we told the messenger.

The next day they were released, and after refreshing themselves at their inn,
went into the street, which was very full of people,
and spake to them in the power and spirit of grace, and they were quiet and civil.
Samuel Bownas adds:

By this time the day was much spent, and concluding to stay that night,
we ordered some refreshment to be got for us, for I found myself in want of it.
It was soon got ready, and we invited our host to share with us, who willingly did so,
showing his good liking to what had been said; adding,
he never saw the people so struck and give so good attention;
nor did ever he see so large a multitude who heard
so intelligibly down to the very foot of the hill,
which was, as he supposed, not much less than two hundred yards in length, and,
by computation, I took the street to be upwards of thirty yards wide,
and all that space much crowded.
I gave him a hint of his fear,
putting him in mind that our duty in preaching to that multitude,
could not possibly be discharged by preaching to him, and his family,
and he acknowledged it was right in us to do as we did.

There are not wanting instances,
in which Divine grace has more than supplied what to the
eye of human reason was utterly lacking by nature,
in his poor servants,
when they have learned to look with a single eye to the Lord and trust wholly in Him.
The following instructive account is taken from Joseph Oxley`'s Journal.
When at Ashwell, England, he says:

In this place lives Barbara Everard, a poor, honest, decrepit creature,
apparently convulsed all over, by which her speech is much affected,
and understanding also.
Yet the Lord has been pleased to make use of this young woman in an extraordinary manner,
having bestowed on her a gift in the ministry,
in which office she appears above many of far more natural talents.
In common conversation she is difficult to be understood, being of a stammering tongue,
but very clear in utterance in her ministry, her matter very correct and sound;
she opens the Scriptures very clearly,
and preaches the Gospel with great power and authority,
and is of singular service in this place; she had at this meeting good service.

The case of Thomas Brown is somewhat similar.
He was born in England and removed to Pennsylvania and settled in Philadelphia as a baker.
His Memorial says of him:

His gift in the ministry was living, deep, and very edifying,
and in the exercise thereof he was remarkable for an awful care not to appear without
clear and renewed evidence of the motion of life being upon him for that service.
Though a man of no literature, yet he was often led into sublime matter,
which was convincing and persuasive,
setting forth the dignity and excellence of the Christian religion.
Yet he was very attentive that those heights should
not detain him beyond his proper gift,
but that he should close in and with the life.
This made his ministry always acceptable to the living and judicious.
In discipline he was by no means forward,
but was watchful that the man`'s part might be kept subject to the power of Truth.

Although Thomas Brown was not without sufficient education
to enable him to transact the business affairs of life,
yet he often was led in his public communications to make use of language, and that too,
very appropriately, the meaning of which he did not know, or could not explain.^
footnote:[He was a man of great esteem among the citizens of Philadelphia generally,
as a public speaker.
The celebrated George Whitefield, when in this city,
hearing of his character in this respect, attended an evening meeting among Friends,
in the hope of hearing him.
In this he was not disappointed,
and afterwards in expressing his great admiration of the discourse,
he said he felt himself as a mere child to him.]

He left a few memoranda of visits to meetings, some of which follow:

1756+++.+++ Eighth Month 9th.--I went to Concord Quarterly Meeting,
but found no cause to espouse the cause of God in a public manner that day.
The next day went to the youth`'s meeting held at Kennett,
which was to great satisfaction.
My soul was so bended towards the people, I could scarcely leave them,
being engaged in a stream of the ministry to extol the Divinity
of that religion that is breathed from heaven,
and which arrays the soul of its possessor with degrees of the Divinity of Christ,
and entitles them to an eternal inheritance.
It also introduces a language intelligible only to the converted
souls who have access to the celestial fountain.
This is no less than a foretaste of eternal joy,
to support them in their journey towards the regions above,
where religion has room to breathe in its Divine excellencies in the soul.
Here it is instructed in the melody of that harmonious song of the redeemed,
where the morning stars sing together, and the sons of God shout for joy.

1756+++.+++ Eighth Month 29th.--I visited Gwynnedd Meeting,
where in waiting in nothingness before God,
without seeking or striving to awake my Beloved before the time,
by degrees my soul became invested with that concern that the Gospel introduces,
with an opening in these words:
"`I think it may conduce to my peace to stand up
and engage in a cause dignified with immortality,
and crowned with eternal life.`"
The subject raised higher and brighter,
until my soul was transported on the mount of God, in degree, and beheld his glory;
where I was favored to treat on the exalted station of the redeemed church,
which stands in the election of grace, where my soul rejoiced with transcendent joy,
and adored God.
Returned home in peace.

John Banks, in a letter to his wife,
thus alludes to the Yearly Meeting held in London in 1675:

For thy comfort I may tell thee, that since the time I parted from thee,
I have been made so much a witness of the enjoyment of the power and presence of God,
among my brethren, that I would not have missed it,
for all that can be mentioned to me in the world.
Oh, the in-breakings of the love and melting power of God,
and the shining of his glorious light amongst us, in this our Yearly Meeting,
where Friends in the ministry were from most parts through the nation!
How were our hearts broken, and our souls comforted and consoled!
The Lord did certainly evidence unto us, that our meetings,
and what we there offered to Him, were acceptable and well-pleasing before Him.
Oh, the sweet harmony of life that was amongst us! the streams whereof flowed,
and many living testimonies were borne to the greatness
and sufficiency of the power of God that overshadowed us!
And oh, the subjection, brotherly tenderness,
and godly care that were amongst us one over another, that we might speak, one by one,
as the Lord, by his spirit, moved and gave utterance!
How near were we to the Lord, and how dear one to another,
in the unity and fellowship of his blessed Spirit!
What a blessed communion was there held,
and how richly was the table of the Lord spread amongst us!
What thanksgivings, praises, honor and glory were many made to ascribe unto Him therefor!
And there was a godly care also for the prosperity of the Truth,
and spreading abroad thereof,
together with the establishing of Gospel order and discipline in the churches of Christ.

In Thomas Scattergood`'s Memoirs, there is the following entry:

At Augusta, in Georgia, I saw a pretty large number of people, both male and female,
carrying dirt on hand barrows to make a causeway.
At first sight of them, I felt pity flow in my heart towards them,
under a sense of their burdens--and after expressing my sympathy with them,
I found a necessity laid on me to pull off my hat
and preach to them the Gospel of Jesus Christ,
their suffering Lord and Saviour.
It was a solemn time; and when I took off my hat, they did so likewise,
and threw aside their tools; and there was loud weeping among them.
In thus unexpectedly laboring among this Ethiopian congregation,
(not having the least thought of such a thing five
minutes before) there was no want of words,
or of that seasoning sweetness which makes right words reach the heart,
and under this precious sense, it would have been as my meat and drink,
to have spent myself in labors of love,
if instead of twenty or thirty there had been as many hundreds:
great was the sweetness which attended on my mind after leaving them.

In William Penn`'s account of a visit paid to Princess Elizabeth,
of the Rhine--he describes in an interesting manner,
some of the religious opportunities with that estimable woman.
Of one meeting, he says:

There were several present besides the princess and countess.
It was at this meeting, that the Lord in a more eminent manner began to appear.
The eternal Word showed itself a hammer at this day, yea, sharper than a two-edged sword,
dividing asunder between the soul and the spirit, the joints and the marrow.
Yea, this day was all flesh humbled before the Lord! it amazed one, shook another,
broke another; the noble arm of the Lord was truly awakened,
and the weight and work thereof bowed and tendered us also,
after an unusual and extraordinary manner;
that the Lord might work an heavenly sign before them, and among them;
that the majesty of Him that is risen among the poor Quakers,
might in some measure be known unto them, what God it is we serve,
and what power it is we wait for and bow before.
They had a sense and a discovery that day, what would become of the glory of all flesh,
when God shall enter into judgment.
Well, let my right hand forget its cunning, and my tongue cleave to the roof of my mouth,
when I shall forget the lovingkindness of the Lord,
and the sure mercies of our God to us his travelling servants that day.
O Lord, send forth thy light and thy truth, that all nations may behold thy glory.

Thus continued the meeting till about the seventh hour; which done,
with hearts and souls filled with holy thanksgivings to
the Lord for his abundant mercy and goodness to us,
we departed to our lodging.

Samuel Bownas relates a somewhat singular experience
that happened to him in one of his religious journeys.
He says:

I went through part of Dorsetshire, and at Sherborne an old Friend was sick,
and not expected to get over that illness,
and it came into my mind he would die of that sickness,
and that I must be at his funeral, and preach with my Bible in my hand.
This made me shrink, fearing it was the fruit of imagination, but I kept it to myself,
and had many meetings about those parts.

I had not been many hours in Bristol before a messenger
came to desire Benjamin Coole to attend the funeral,
and Benjamin came to me to Brice Webb`'s, where I lodged, and told me how it was,
and desired me to go.
I pleaded many excuses; first, my horse was not fit, with other objections,
which were all removed.
I went to Bruton next day, being the Seventh day of the week,
and was at that small meeting on First-day.
The funeral was on Second-day, which was exceedingly large, John Beere from Weymouth,
being there, had something to say, but not much.
Then as it was with me, I pulled my Bible out of my pocket, and opened it;
upon which the people gave more attention than they had done before.
I had a very acceptable time,
often in the course of my matter referring to the text for proof,
and giving an ample testimony of the value we put upon the Scriptures;
earnestly pressing the careful reading of them, and advising to consider what they read,
and to seek the Lord by prayer, for assistance and power,
that they might practice what they read, which was the ultimate end of reading,
as well as of hearing preaching, for without practice, it would avail but little;
with other advice to the same effect.

There being sundry teachers of several societies, one of them, a Baptist,
took hold of me after meeting was ended, and desired some conversation with me.
I looked at him earnestly,
and desired to know if he had an objection against any part of what I had said?
"`If thou hast,`" said I, speaking with an audible voice,
that stopped many of the company, "`this is the most proper place,
the people being present;`" for they thronged about us very much.
This made him confess, that what he had heard was sound, and according to Scripture,
being very well proved from the text;
but he desired some private discourse between ourselves at my quarters,
if I would permit it.
I told him he might; I quartered at Richard Fry`'s; and Richard being present,
told him he should be welcome to come to his house, and so we parted.

When I came to Richard`'s, he said we should hear no more of him,
for that in his discourses amongst his hearers,
he had spoken many very unhandsome things against the Quakers,
endeavoring to unchristian them, and prove them heathens in denying the ordinances,
a common plea used by all our adversaries.
But this man carried the matter farther than some others, by adding,
that we denied the Scriptures,
and also would not allow of a Bible in any of our meetings,
nor did our preachers use a Bible to prove anything
therefrom that we preached to the people,
with more to the same purport; and as many of his hearers were there,
my appearing with a Bible, and referring to the text for proof, no doubt,
put him and them upon a thought what had been preached by him, amongst them,
concerning the Quakers,
which now appeared to be a manifest untruth by what
they had both seen and heard that day.
As Richard Fry thought, so it proved; he did not come near me,
and Truth was exalted above lies and falsehood.

The Society of Friends have always believed that
it is not consistent with the commands of our Saviour,
for his disciples to receive compensation for preaching the Gospel,
which as it has been freely given to those whom He appoints,
must be exercised without hope of pecuniary reward.

The labors of early Friends in the work of the ministry were astonishingly great,
and many could bear the same testimony as Thomas Chalkley when he says:
"`I have travelled many thousands of miles, and preached the Gospel many years,
as thousands of people can witness, and never received any consideration therefor,
neither directly or indirectly; neither do I reckon they are beholden to me for so doing,
for a necessity is laid upon me, and woe is me, if I preach not the Gospel.

In 1659, Richard Hubberthorn, addressing the council of state, thus speaks:

Let every one that will minister the Gospel,
do it freely according to the example of the apostles and the ministers of Christ.
And do not you go about to provide any maintenance
for any ministers of any sort in the nation;
for in that you will but lay a yoke upon the disciples`' necks,
and an imposition upon tender consciences,
which cannot do anything but what they do freely as unto the Lord,
and let every one that will preach the Gospel live of the Gospel,
and not upon any settled or state maintenance... For the
cry of the honest and godly people of this nation is,
to have a free ministry, a free maintenance,
and are willing freely to maintain those that minister unto them the word and doctrine.

The Quarterly Meeting of Cornwall, in one of its minutes, dated Second Month, 1671,
gives another instance of the way in which early Friends supported their ministers.
"`It is ordered,`" say they:

That John Trefry do deliver unto Thomas Salthouse £10,
which the Friends of this meeting desire him to accept from them, to buy him a horse,
he being at present destitute of one,
and having formerly had his horse killed whilst he was laboring
for the service and work of the Lord in this county.
His fallen lot being now amongst us,
and his labors and service in the work of the Lord being great here as in other places,
we have ordered the sum aforesaid to be paid him
as a demonstration of our love and care for him,
being desirous that he should reap of our carnal,
he having often sowed spiritual seed amongst us to the refreshing of our hearts.

Plainly as is here stated the grounds of the care
and consideration of the Friends of Cornwall,
more scrupulous, apparently, was Thomas Salthouse not to make the Gospel chargeable,
and there is added to the minute as the result of their offer,
"`Thomas Salthouse hath no freedom to receive the £10.`"

When Samuel Fisher had finished his studies, he was ordained a priest,
and was first a chaplain to a person of quality,
and afterwards presented with a living of two hundred pounds a year.
Being conscientiously engaged in seeking after Truth, he discovered,
before he knew Friends, that infant baptism was a human institution,
and preaching for a stipend was contrary to the command of Christ.

A young man, dissatisfied with singing David`'s psalms in the public worship,
gave his master so much uneasiness, that he applied to Samuel Fisher,
as a learned minister, to remove his scruples.
In the attempt,
the young man frankly gave these reasons for his apprehensions
of the impropriety of the practice--that God was a spirit,
and to be worshipped, not in other men`'s words,
but in spirit and in Truth--that it was a falsehood for
a proud man to sing that "`he was not puffed up in his mind;
he had no scornful eye,
and he did not exercise himself in things that were too high`"--that
it was absurd for one to sing "`Rivers of tears run down my eyes,
because other men keep not thy laws,`" whilst he never knew
a true sorrow and repentance for his own sins.
The result of this conference was, that instead of altering the young man`'s sentiments,
the reasons given for them had such a convincing effect on Samuel Fisher,
that he found himself restrained from giving out to his congregation,
David`'s conditions, to sing.
At length, preaching for wages, contrary to the convictions of his conscience,
became so great a burden, that he gave a rare instance of the honesty of his heart,
and the value he put upon the testimony of a good conscience, by resigning his living,
divesting himself of the sacerdotal office,
and placing his confidence in Divine providence for
the future support of himself and family.
He rented a farm and commenced grazier, by which he procured a decent competency,
accompanied by the solace of contentment, and the testimony of an approving heart.

As the minds of the ministers of the Gospel are kept
in communion with their Lord and Master,
He from time to time impresses upon them the belief
that certain duties are required of them.

Elizabeth Webb thus describes the arising in her mind of a concern to visit America:

In the year 1697, in the Sixth Month, as I was sitting in a meeting in Gloucester,
the place of my habitation, my mind was gathered into perfect stillness for some time,
and my spirit was as if it were carried away into America, and my heart was, as it were,
melted with the love of God.
It flowed and seemed to reach over the great ocean,
and I was constrained to kneel down and pray to the
Lord for the prosperity of his seed in America.
The concern never went out of my mind, day nor night,
until I went in the love of God to travel there.
So universal is the Divine love it reacheth over sea and land, and my soul can say:
"`Thy commandments, O Lord, are exceeding broad.`"

The Memoirs of Hannah Gibbons contain several references
to concerns to visit particular families or individuals.
Some of these were to persons under sentence of death.
In 1852 she records:

In the latter part of Eighth Month my mind was unexpectedly brought under exercise,
on reading an account of a poor colored man in prison
at Newcastle under sentence of death.
It seemed best to me that I should endeavor to see him; and after some time,
I was made willing to mention my exercise to some Friends (the elders),
who did not discourage me; and my dear friends, James Emlen and Martha Jefferis,
being willing to accompany me, we accordingly left home on First-day afternoon,
the fifth of Ninth Month, lodged at Wilmington, and next morning proceeded to Newcastle,
and were readily admitted into the apartment where the poor man was.
He appeared very uncomfortable as to the outward,
but we were united in believing that his mind was
turned to the right source for help and strength,
and that the work of repentance was in mercy going forward.
After endeavoring to relieve my mind, both in testimony and supplication, for the poor,
erring man, and dear Martha having also had something to communicate, we came homeward;
my mind being clothed with thankfulness for having
been enabled to yield to apprehended duty,
and for the reward of peace.

Ruth Anna Rutter, (afterwards Lindley), relates the following incident:

A Friend visiting Pottstown meeting about twelve months before I became plain,
and I being in a very low and discouraged state,
went to meeting greatly desiring he might be made an instrument of comfort to me.
He spoke for a considerable time,
but did not touch upon any thing relative to my condition;
and I returned home under many doubts and fears,
lest my Heavenly Father had cast me off forever.
My parents were in Philadelphia, and I being alone, sat down on the sofa,
with the Bible in my hand,
thinking to gain some instruction and comfort from its sacred contents.
I had given up the idea of seeing the Friend, (who was a true father in Israel),
or of having any opportunity with him, as not being worthy of it.
But he, having dined at my uncle`'s, not far distant, was,
after dinner walking in the piazza, and looking towards our house,
felt a draught in his mind to come over.
He knew nothing of the family, but yielding to the impulse he came; and,
passing through the outer room, where there was a young woman of the house,
without asking any questions, he walked into the parlor,
where I was sitting in the situation above described;
and without any further salutation than shaking hands, took a seat by me.
A considerable time elapsed in deep inward silence,
after which he mentioned how unexpectedly he was led to come over,
without knowing the cause; but then feeling his mind clothed with sympathy for me,
and believing it was for my sake, he imparted much counsel and advice,
with a great deal of encouragement to me.
Which singular favor did deeply humble my heart, and caused tears of gratitude,
contrition and tenderness to stream from my eyes.

Among the religious engagements into which the ministers and religiously
concerned members of the Society of Friends have often been led,
is that of visiting individuals and families from house to house.
There is this peculiar feature about it, that,
whilst in a public meeting a person may put aside the close preaching
of the minister with the plea that it was designed for others than himself,
in a family opportunity there is no room for such evasion,
but the message may come to him with the directness of Nathan`'s appeal to king David,
"`Thou art the man.`"
There are few, if any,
services in which a minister can be engaged that require greater watchfulness
and care to act under Divine guidance than such personal labors.

Ann Branson, of Ohio, under date of 1848, says:

I have felt it required of me in the late family visit in which I have been engaged,
not only to go to a number of families, who were not members of our religious Society,
but also to some houses, whose inhabitants were entire strangers to me,
and whose names were unknown, except by inquiry at the time,
feeling attracted to the houses as we passed them,
and feeling the woe if I did not give up to go in.
Trying as this service was to flesh and blood,
it is nothing to compare to a wounded conscience.
Previous to a late engagement in several families of this description,
I was near three days at a Friend`'s house, shut up, without any clear opening whatever.
But the command was, Be still.
What will my friends say of me?
was a query that often crossed my mind.
But the answer of my Heavenly Father was on this wise, "`Thy time,
thy health and thy faculties, are mine.
I have a right to do with them, and with thee, as seemeth unto me good.`"
Thus did I remain,
until a little opening appeared in a remote neighborhood where a few members were scattered.
After we arrived there, and had visited most of those who were members,
it came into my mind to inquire of the Friend at whose house we were,
concerning his children, who had married out of the Society, where they were settled,
and being informed that several of them were nearby,
I soon saw I must go to their houses.
This dedication, though greatly in the cross, yielded peace.

The same Friend mentions, in 1861, that, on one occasion, after making a family visit,
where she had delivered what appeared required of her, and had left the house,
she felt it required of her to go back.
Great fear possessed her heart lest she should be mistaken.
She had an interview with the parents,
and told them how it had been with her since being there before, telling them:
"`If I was mistaken in my feelings, I hoped they would pass it by,
and I would try to be more careful in future,`" at the same time
remarking that there was a secret language in my heart which said,
There is a secret hardness against some, which is not rooted out.
But it was in great fear and trembling, lest I should be mistaken.
When about to bid farewell,
the individual (where it seemed to me the testimony belonged), with tears,
and in much brokenness of spirit, said to me, "`I am glad thee came.`"

Henry Hull mentions in his Journal that, while at work in a mill,
word was sent to him that his father wished him to come to the house.
He says:

I immediately went, and found several Friends there,
who proposed a religious opportunity with the family.
When I found what I was wanted for,
I felt disturbed in my mind that my father should call me from
my work upon what I then thought such a trifling occasion,
and I could scarcely speak pleasantly to the Friends.
But, soon after we sat down together, the power of Truth spread over us,
and the Friends were enabled to speak so plainly to my situation,
that my spirit was broken into tenderness,
and when I left the house tears flowed from my eyes.
Reflecting on the solicitude of my dear father for my everlasting welfare,
and on the goodness of the Ancient of days,
in that He did not leave me in the hardened state
of mind I was in when I went into the room,
my heart was humbled, and I entered into solemn covenant with the Lord that,
if He would pass by my offences, I would endeavor to be mindful of his favors,
and walk more worthily.

In the earlier days of our Society greater attention was
paid to family visiting than has latterly been the case.
In the Queries adopted by Irish Friends, about the year 1737, one reads as follows,
"`Doth each Monthly Meeting take care that a visit to the families
of Friends be performed by well-qualified Friends once a year,
or oftener, as occasion requires?`"

The same subject is mentioned in the minutes of Philadelphia
Yearly Meeting as early as the year 1717.
They say, "`Considering the returns from the several meetings concerning visitors,
this meeting agrees that such Monthly Meetings as do see a service therein,
may appoint honest,
faithful and discreet Friends to visit families within
the compass of such meetings respectively.`"
In very many of the subsequent Yearly Meetings advices are sent down on this subject,
and subordinate meetings reported to the Yearly Meeting as to their care in this respect.
In 1747 the minutes say:
"`This meeting recommends it to the several Quarterly
and Monthly Meetings within the range of this meeting,
to revive and continue the practice of appointing solid and weighty Friends and elders,
together with some of their ministers,
to visit the particular families within their respective meetings,
the good effects of which wholesome and serviceable part of our ancient
practice and discipline hath been often attended with the Divine blessing,
to the great satisfaction of those concerned therein,
and hath been a means of preventing many growing inconveniences and customs amongst us,
which it may be difficult guarding against in a more public manner.`"

The practice of visiting each other`'s families and endeavoring to help
each other in a faithful support of our doctrines and testimonies,
did not originate in Yearly Meeting advices, but was practised from very early times,
and had its root in that love of the brethren and zeal for the
honor of the Lord`'s cause which marked our ancient worthies.

The practice of Friends not to enter upon vocal labor in meetings,
unless under the influence of a fresh call from the Head of the Church,
and their conviction that silence was better than forced sacrifices,
have frequently led to the holding of meetings in
which there was neither preaching nor praying.

When Joshua Brown was paying a religious visit in New England, at Leicester,
he lodged at the house of a widow Earle, whose son had married a Presbyterian woman,
who afterwards became a member among Friends.
Her father rode with Joshua on his way to Worcester.

As he rode along he spoke to Joshua, telling him he had a daughter joined to Friends.
Joshua queried, "`Is she any worse child or worse Christian than she was?`"
He said, "`He thought not.`"
Joshua said, "`That is well, so far.`"
The father then said he had a mind to converse, not for contention, but for information.
Joshua said he was willing, as far as he could, to satisfy him.
He then said: "`You profess not to study your sermons.`"
To this Joshua assented.
"`You mentioned many texts of Scripture, and I believe they were rightly quoted.
I wonder how you remember them.`"
Joshua, in reply, said: "`I spake as they were opened to me.`"
He then said: "`You always preach when you are at home, don`'t you?`"
Joshua, on this, said: "`There are several Friends belonging to the meeting I do,
who sometimes speak +++[+++in the ministry], and yet we have many silent meetings.`"
He said: "`I cannot reconcile that.`"
Joshua said: "`If thou wilt consider the nature of Gospel worship,
and that it is to be performed in spirit and in truth, thou need not wonder.`"
He then said: "`You always preach when you are abroad, and appoint meetings, don`'t you?`"
Joshua replied: "`I do not.`"
"`Do you not think that you impose upon the people?`"
Joshua said: "`I think not.
When we appoint meetings, we do not promise to preach;
but if we feel our minds engaged to speak, we do it as we find ability.
Your preachers preach for money, and are obliged to speak, but we do not.`"
He acknowledged that it was too true.
Much more conversation ensued, and when they reached his dwelling,
he kindly pressed Joshua to alight and refresh himself.
This Joshua was free to do.

John Griffith mentioned that, at Wigton, "`Friends having, without my knowledge,
given notice to their neighbors and to divers people of account in the world,
it is likely they expected great things from one who had come so far to visit them;
and some perhaps hoped to get credit by that day`'s work;
but we see sometimes when man appoints the Lord disappoints,
which in the issue seems to have been the case here.
I sat the meeting, which was very large, in silence,
to the great mortification of many present, some of whom,
one might have expected from their appearance and pretensions,
understood the nature of spiritual worship better
than to have been so anxious after words.
It proved, I think, as painful and exercising a meeting as ever I knew,
to which the expectations of Friends and others did not a little contribute.
At the conclusion I was fully satisfied that I had
discharged the service required of me that day,
in an example of silence, in which I had peace.`"

It is recorded of Peter Andrews, of New Jersey,
when travelling in England in the service of the Gospel,
that he visited many places in the county of York, visiting the churches,
which were greatly refreshed and edified by his labors of love.
+++[+++These meetings were sometimes held in silence], although appointed on his account,
generally large, and expectation high.
His eye being single to his great Master,
he often was led to famish the too eager desire after words.
For several public meetings he had nothing to say, which,
though a great disappointment for the present,
yet it afterwards appeared there was no small service in it.

The following incident was published in _The British Friend_:

On the first of Seventh Month, 1858,
a stranger from London attended our week-day meeting at
+++_______+++. It being the day after our Monthly Meeting,
the congregation was particularly small.
After two short communications, the individual above mentioned rose and said:
"`I have felt such a solemnity in this time of silence
that I could almost fancy I heard Jacob,
when he saw the ladder and the angels ascending and descending on it, exclaim,
'`How awful is this place; surely this is none other than the house of God,
and this is the gate of heaven;`' and I could almost fancy I heard the prophet say,
'`Then they that feared the Lord spake often one to another,
and the Lord hearkened and heard it,
and a book of remembrance was written before him for them
that feared the Lord and that thought upon his name;
and they shall be mine saith the Lord, in the day that I make up my jewels (or my crown),
and I will spare them,
as a man spareth his own son that serveth him.`' '`Then
shall ye return (when ye have ceased from your own actions,
reasonings and desires,) and discern between the righteous and the wicked,
between him that serveth God,
and him that serveth Him not.`' I hope I shall be excused speaking among you,
being a stranger, and not a member of your Society;
but I believe I shall feel remorse on leaving this place if I do
not acknowledge among you what God hath done for my soul.
It is now twelve months since I came to this place.
I had heard of your mode of worship,
but I wondered how the Lord`'s people could be profited by sitting in silence,
and sometimes not a word spoken among them.
I sat down in this house hoping and waiting to hear
something that might cheer and encourage my soul;
and as I sat in this expectant state, such an influence,
such a feeling of solemnity covered my mind as I
had never experienced before in all my life,
and which I shall never forget whilst memory holds her seat,
and which I believe to be from the Divine favor;
and I then understood what our Saviour says in John:
'`If any man love me he will keep my words, and my my Father will love him,
and we will come unto him, and make our abode with him.`' And in Rev. 3:20,
'`I will come in to him and will sup with him,
and he with me.`' And I felt that there is a communion
between God and the souls of his people;
and though I have felt reluctant to speak among you,
I could not leave this place with an easy mind without acknowledging
what I felt in this house twelve months ago,
and once since, when sitting in silence in my own house.`'`"

It has often been the experience of the Lord`'s servants,
that services were required of them that were more or less unusual.
This was frequently the case with Sarah Lynes (afterwards Grubb).
In 1798, she felt a concern to speak to the people at Wolverhampton Market.
The service is described by her companion John Burlingham:

She neither saw nor spoke to any Friend there, except those at our quarters.
On inquiry we were told the most suitable place to
speak would be from the upper window of the inn,
but that not feeling right to S. L., we left her to take the helm.
She said to A. Baker, "`Do thou take R. B`'s arm;
I will take J. B`'s,`" so she led the way into the market.
After making a short stand, she began to address those around her,
and had not spoken many sentences, when divers shed tears, struck dumb as it were,
with amazement; indeed the power was so great and so evidently felt,
that fear was taken from me.
After a very solemn, but short opportunity, having hold of my arm,
she went more into the centre of the market, which is a very large one,
and seeing a butcher`'s block, without asking any questions to whom it belonged,
she and Ann mounted it, my brother and self standing on each side.
A large audience collecting immediately, she addressed them for about an hour,
to the satisfaction, I believe, of most that could hear her.
When she got down, great was the anxiety of many to shake hands with her,
which numbers did, and also expressed their thankfulness.

By this time the farmers, many of them, were gone, and going to dinner;
we therefore went to the inn, the people making way for us to pass respectfully.
When there, S. L. did not seem quite easy in thus missing the farmers,
but understanding a number were dining at the ordinary,
she concluded to offer herself to them as soon as they had dined.
My brother went and asked them the question; the chairman immediately replied,
they or he had no objection.
My brother and myself accompanied S. L. and A. B. into the room.
We were asked to go up to the top, but S. L. declined, and sat down at the bottom.
During the space of about ten minutes`' silence,
divers interruptions took place by people coming in.
If I may give a description of S. L.`'s engagement at that time,
agreeably to my own feelings, I must say that her elegance of language, pertinent matter,
persuasive energy, and above all, the crowning authority and power,
I think I never witnessed exceeded, if equalled.
When she had done, she immediately began to withdraw, when the company, every man,
rose from his seat, though silently, yet most respectfully; they showed at the same time,
good manners, and also assent to what they had heard.

In 1809 Thomas Shillitoe felt a concern to visit the drinking
saloons in Dublin--a very exercising service,
as many of them were places of a very low character.
There were about six hundred visits paid.
Although they met with many trying things,
yet in a general way Divine help seemed to be near.
The following record of one day`'s proceedings will
show the nature of Thomas Shillitoe`'s experiences:

Fifth-day we proceeded to Barrack Street.
The first house we entered made a deplorable appearance;
it was very early in the morning, yet we found,
on descending the steps into the drinking-room, which much resembled a cellar,
the window-frames and glass broken, and several young women, without shoes,
stockings or caps, dancing to the fiddle.
We made towards the room set apart for the keepers of the house,
where we met with the mistress.
Requesting, if she had a husband to have his company, he soon made his appearance.
I endeavored to lay before them what arose,
although I found it difficult to get fully relieved.
The fiddle, and at times the screaming of the dancers, was a great interruption.
The man remained quiet for a short time and then left us,
the woman appearing to have the management of the house:
what I had to say brought her to tears.
On inquiry I found she had children,
I therefore requested her seriously to consider what would be her conclusion
respecting the conduct of any person who should harbor her children,
and suffer them to go on in such wicked practices as she
was now encouraging the young girls in under her roof,
who might be without parents or friends to take charge of them, saying,
I did not wish for a hasty reply; she confessed she should think they acted a cruel part.
I therefore entreated her to attend to that Divine monitor in her own breast,
which she confessed she at times witnessed to be near,
which would clearly make known to her the necessity
to rid her house of such company as she now harbored,
which would be one way whereby she might hope for the Divine blessing
on honest endeavors for the support of herself and family,
otherwise she must look for a blast following them every way.
She continued tender, and at our parting, in a feeling manner expressed her desire,
that what had been communicated might be profitably remembered by her.

After receiving her warm expressions of gratitude, we proceeded to leave the house,
but on reaching the top step of the entrance my attention was again arrested,
and I found I must be willing to return into the
apartment where the dancing was going forward,
and quietly submit to any insults that might be the
result of my being found in the way of my duty.
On my companion being informed hereof, he appeared tried as well as myself,
but I found it would not bring peace to our own minds to hesitate.
We therefore turned back, which the woman of the house observing, came and stood by us,
I supposed to prevent any rude behavior that might be offered.
I requested the man who had the fiddle to cease playing and take his seat,
which he complied with, and those who were dancing to do the like,
which each one yielded to.
The scene exhibited in different parts of this large room,
if it were possible fully to describe,
would produce a picture of as great human depravity and misery as well can be conceived.
On a bench near us lay young girls,
overcome with their night`'s revelling and drunkenness,
past being roused by anything that occurred round them; others, from the same cause,
reclining on the tables, barely able to raise their heads and open their eyes,
and altogether incapable of comprehending what was going forward:
companies of men and women in boxes in other parts of the room drinking.

On our standing silent amongst them a short time,
quietness prevailed over the whole company.
Strength was received to utter what was given me,
and after I had been some time engaged in addressing this band of human misery,
I think I shall not, whilst favored with my mental powers,
wholly lose sight of the distress and horror portrayed in the countenances
of those young women who had ceased their dancing.
Feeling my mind relieved and about to depart,
such of the company who were equal to it rose from their seats,
acknowledging their gratitude for the labor that had been extended,
and their desire that what had been said might not be lost upon them,
and that a blessing might attend us.
My back was towards the door,
and not hearing a footstep of those who came in while we were engaged,
when we turned to go out I was surprised at the addition made to our company:
my companion remarked,
it appeared as if something brought an awe over their minds on entering,
and they quietly took their seats, and when the seats were full others sat on the ground.

Isaac Penington says of those whom the Lord sent forth to proclaim
the glad tidings of salvation to the people of England in his time:

They were for the most part mean, as to the outward; young country lads,
of no deep understanding, or ready expression,
but very fit to be despised everywhere by the wisdom of man,
and only to be owned in the power of that life wherein they came forth.
How ridiculous was their manner of coming forth and appearance to the eye of man!
About what poor, trivial circumstances, habits, gestures, and things,
did they seem to lay great weight, and make great matters of moment!
How far did they seem from being acquainted with the mysteries and depths of religion!
But their chief preaching was repentance, and about a light within,
and of turning to that,
and proclaiming the great and terrible day of the Lord to be at hand;
wherein I confess my heart exceedingly despised them,
and cannot wonder that any wise man, or sort of professors, did or do yet, despise them.
Yea, they themselves were very sensible of their own weakness,
and unfitness for that great work and service wherewith the Lord had honored them,
and of their inability to reason with man;
and so (in the fear and in the watch of their spirits) kept close to their testimony,
and to the movings of his power,
not mattering to answer or satisfy the reasoning part of man,
but singly minding the reaching to, and raising of, that to which their testimony was.

Oh, how did the Lord prosper them in gathering his scattered,
wandering sheep into his fold of rest!
How did their words drop down like dew, and refresh the hungry, thirsty souls!
How did they reach to the life in those to whom they ministered,
raising up that which lay dead in the grave,
to give a living testimony to the living voice of God in them!
How did they batter the wisdom and reasonings of man,
making the loftiness thereof stoop and bow to the
weak and foolish babe of the begettings of life!
Eye hath not seen, ear hath not heard,
nor hath it entered into the heart of man to conceive,
what the power of life hath wrought, through them,
in the hearts and consciences of those who have longed after and waited for, the Lord.
Oh! the breathings and meltings of soul, the sense of the living presence of God,
the subjecting of the heart unto the Lord,
the awakening of and giving strength unto his witness,
the falling down and weakening of the powers of darkness,
the clear shining of the light of life in the heart,
and the sweet running of the pure streams thereof into the enlivened souls,
which hath often been known and sealed to from the
powerful appearance of God in their ministry!
Indeed, when I have considered these and such like things in my heart,
and narrowly marked them in my converse with them,
I have been often forced to cry out concerning them.
Truly here is man very weak and contemptible; but God very glorious and powerful.
And indeed, when at any time I looked on the man,
I was hardly able to forbear disdaining them; but, on the other hand,
when the eye of my spirit beheld the power and glory of the Lord in them,
I could hardly forbear over-esteeming and exalting them.

How hath the Lord enriched them with gifts and abilities,
and every way fitted them for the service and employment He hath had for them!
How hath He enlarged their ministry, that they who had very little to say,
either by way of declaration or disputation at first, now abound with strength,
and abundantly surpass the knowledge and wisdom both of the world,
and of other professors of religion!
The Lord indeed hath adorned them, putting his beauty upon them,
and causing them to grow up in his strength, and in his wisdom.
This mine eye hath seen, and often taken notice of, blessing the name of the Lord,
and praying to Him for their preservation.
And surely whoever he be, that hath either known himself,
or heard the relation of the poverty of these young striplings,
when they first came forth in the power of the Lord,
how empty in themselves they then were,
how sensibly they went up and down of their own weakness,
how little they had to say to people that came to observe them and inquire of them,
how afraid they were to be drawn from their watch,
at what a distance they stood from entering into reasoning about things--I say,
he that did know, and doth consider this,
and shall also behold how the Lord hath advanced them since,
making them mighty and honorable with his gifts and abilities (with the beauty whereof
the very man flourisheth to the sight of every eye that is in any measure truly open),
cannot but acknowledge the change to be wonderful.

William Dewsberry says:

I waited in the counsel of my God, in the calling where I was placed, until the year 1652.
And in the Eighth Month of the year, the word of the Lord came unto me saying:
"`The leaders of my people cause them to err,
in drawing them from the light in their consciences, the anointing within,
which the Father hath sent to be their teacher, and would lead them into all truth,
to seek the kingdom of God in observations where it is not to be found.
So, my people perish for want of bread: freely thou hast received,
freely give and minister:
and what I have made known unto thee in secret declare thou openly.`"
Which word constrained me, by the power of it,
to leave my wife and children and to run to and fro,
to declare to souls where their teacher is, the Light in their consciences,
of which the Lord hath given to every one a measure to profit withal,
for the exercise of the conscience towards God and man.
Waiting in the light for the power of Christ, he would lead them up,
to the living fountains of waters,
where their souls would find refreshment in the presence of the Lord;
and their bread would be sure,
and their water never fail--as the Lord has made manifest to my soul.

A writer who was contending for the principle,
that the gift of a ministry in the Gospel is bestowed upon women as well as men,
cites the case of Elizabeth Stirredge, of Gloucestershire (1634-1706),
the daughter of an honest, zealous, God-fearing Puritan, concerning whom she says:

My father being one of those called Puritans,
prophesied of Friends many years before they came.
He said: "`There is a day coming wherein Truth will gloriously break forth,
more gloriously than ever since the apostles`' days, but I shall not live to see it.`"
He died in the faith of it seven years before Friends came;
whose honest and chaste life is often in my remembrance,
and his fervent and zealous prayers amongst his family are not forgotten by me.

In the year 1670, at a time of great suffering amongst Friends,
because of the prevailing persecutions,
Elizabeth Stirredge feeling a drawing to the ministry, makes a record:

Thus the Lord gently led me towards the service and
testimony that He was pleased to lay upon me to bear;
which was the greatest trial that I ever met with.
My exercise increased, my inward pains grew stronger and stronger,
my heart was troubled within me, my eyes were as a fountain of tears, and I cried out:
"`Woe is me that ever I was born.
Lord, look thou upon my afflictions, and lay no more upon me than I am able to bear.
They will not hear me who am a contemptible instrument.
And seeing they despise the service of women so much,
make use of them that are more worthy.`"
The answer I received was, "`They shall be made worthy that dwell in my fear.`"

And further on she adds:
"`I can say to his praise I was so encouraged in all times of persecution,
wherein I might bear my testimony for the Lord who
had redeemed me out of the pit of misery,
that I rejoiced to do the will of the Lord,
for it was more to me than all that ever my eyes beheld,
and to stand a faithful witness for Him.`"

I will next speak of Susanna Hatton (afterward Lightfoot),
an account of whom is given in the Journal of James Gough, of Ireland,
a minister of excellent repute in the Society of Friends.
The narrative opens about 1737,
when Susanna Hatton at the age of eighteen came to this
country as a domestic in the service of Ruth Courtney,
a minister.
Young in years as she was, she began thus early to speak in meetings.
Returning in the course of a few months to Ireland, James Gough says of her:
"`I was very much affected with her inwardness,
fervency and tenderness of spirit out of meetings, as well as her awful +++[+++i. e.,
solemn and powerful], utterances in meetings.`"
At about twenty-three years of age she married a
linen-draper and lived in a very humble way,
her husband keeping two looms going, and she keeping two cows,
and carefully bringing up her family.
Her life was one of simple faith,
and though at times her outward condition was such that
she had not a morsel of food for herself and family,
yet when reduced to such extremities, and without making her case known,
sudden relief would come in from one quarter or another.
When settled in the province Ulster, her narrator, himself a true minister,
testified concerning the religious services of this
humble and devout handmaiden of the Lord:
"`Not one in those large meetings rose up with that
Divine authority and dignity that she did.`"
Removing to Waterford, and going soon afterward upon a religious visit to Carlow,
Mountmellick, etc., the following incident occurred as told by J. Gough:

A Friend put four guineas into my hand and desired me to present her with them,
which I did; but she refused to accept them,
telling me she had others offered before in that journey, but durst not receive them,
being under no present necessity.

Her confidence that the Lord would provide everything needful was not misplaced.
As her children grew up they found friends ready to aid them to good positions;
her own circumstances improved and, her husband dying,
she afterwards married an exemplary Friend from America,
with whom she returned to this country, and settled in Chester County, near Philadelphia.

Mary Dudley, of Bristol, England (1750-1810), was a Methodist,
held in much esteem by John Wesley and others, in that connection.
She was frequently urged to serve as a class-leader,
but becoming sensible that it was her religious duty to profess with Friends,
she united with them in 1773, and was recorded as a minister four years later.
She, however,
at first put aside the intimations of the holy command
publicly to declare the counsel of God,
until the sufferings she endured by her disobedience became great.
(Let it be remembered that in this, and the other instances cited, there was no priest,
committee, or other human intermediary required to be consulted.
The eyes of these women were to the Minister of ministers alone,
who hath the key of David, and "`openeth, and no man shutteth;
and shutteth and no man openeth.`") Upon yielding finally--not to any influence of man,
but through the constraining power of God--she says:

Oh! the rest I again felt,
the precious holy quiet! unequal in degree to what was my first portion,
but as though I was altogether a changed creature,
so that to me there was no condemnation.
Here was indeed a recompense even for years of suffering, but with this alloy,
that I had long deprived myself of the precious privilege by yielding
to those reasonings which held me in a state of painful captivity.

Another Mary of the same period, a true mother in Israel, was Mary Capper (1755-1845),
who was brought up in the established church of England,
having a brother who was a clergyman therein.
Having united in membership with Friends,
she was recorded as a minister at about the age of forty years.
In relation to the beginning of her ministry, which was at London, she says:

I have no distinct recollection as to any serious
thoughts of speaking in a religious meeting;
it sometimes arose to my view that possibly I might
have to tell unto others how I had been taught,
and kept from the broad way of destruction,
but a few words arising in my mind with something of unusual power,
I think at the Peel Meeting, I stood up and spoke them, and was very quiet,
nor did I anticipate or foresee that such a thing might ever be again.
And thus was I led on from time to time, not knowing but each time might be the last.

At eighty her language of encouragement to another was:
"`Everlasting mercy and help is on the side of the humble and devoted,
though they may have to pass through many tribulations,`" and,
as her spirit peacefully passed away, at ninety: "`O,
how beautiful! to go to a mansion prepared for us!`"
A devout, childlike, divinely-anointed minister of the Lord, fifty and five years,
shrinking utterly from anything like "`notoriety,`" who will say that
this Mary who loved so to sit at the feet of Jesus was misled or presumptuous,
or followed a false guide?

One of the most remarkable characters in modern Quaker annals is Stephen Grellet,
a French Romanist (1773-1855), who after becoming an infidel, if not an atheist,
came to this country at the time of the revolution in France,
and took up his abode on Long Island.
There his views, through the providence of God, underwent a radical change.
Being in a tender, seeking state,
he attended a meeting of Friends at which two women ministers from England,
Deborah Darby and Rebecca Young, were present.

After the meeting +++[+++he says in his personal narrative],
my brother and myself were invited to dine in the company of these Friends,
at colonel Corsa`'s. There was a religious opportunity after dinner,
in which several communications were made.
I could hardly understand a word of what was said,
but as Deborah Darby began to address my brother and myself,
it seemed as if the Lord opened my outward ear and my heart.
Her words partook of the efficacy of that "`Word`" which is "`quick and powerful,
and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart.`"
She seemed like one reading the pages of my heart,
with clearness describing how it had been, and how it was with me.
I was like Lydia; my heart was opened; I felt the power of Him who hath the key of David,
no strength to withstand the Divine wisdom was left in me.
O what sweetness did I then feel!
It was indeed a memorable day.
I was like one introduced into a new world; the creation,
and all things around me wore a different aspect--my heart glowed with love to all.
The awfulness of that day of God`'s visitation can never
cease to be remembered with peculiar interest and gratitude,
as long as I have the use of my mental faculties.
I have been as one plucked from the burning--rescued from the brink of a horrible pit.
O, how can the extent of the Lord`'s love, mercy, pity, and tender compassion be fathomed!

All this Stephen Grellet says for himself:
only the revelations of the last day may show the blessed result to others,
both of high and low degree,
which followed his religious labors and travels in
Gospel service in this and other lands.
I know of no more interesting and instructive biography,
and rejoice that its value has of late been extensively recognized,
and that various editions of his life have been issued.
Can any aver that Deborah Darby stood not in her appointed place,
in the Lord`'s ordering, when she delivered that searching, soul-reaching,
after-dinner discourse at the house of colonel Corsa?

Ann Mercy Bell, of York, England, was a valuable minister who died in the year 1776,
aged about sixty-nine years.
In the short account of her published in [.book-title]#Piety Promoted#, we are informed that--

While in a private capacity,
she was well esteemed as a Friend of circumspect life and conversation,
a pattern of plainness, and therein, as well as in other respects, a good example.
At length, steadily adhering to the Divine teacher in her heart,
and under the influence of the spirit of Truth, she had, from a well grounded experience,
to declare to others the way of life and salvation.
In this service she faithfully labored, according to ability received, at home,
and adjacent parts.

In the year 1753, she found a concern to visit Friends in London;
and during her stay in that city, under the influence of love to mankind,
had to exhort the inhabitants thereof, in the streets, markets,
and many places in and about London, Westminster, and Southwark,
calling them to repentance and amendment of life.
In this service she was signally furnished with ability to labor,
to the tendering of many minds, and acknowledgment of her goodwill to them;
and such was the ardor of her mind, and the flowing forth of love to them,
that she frequently preached three or four times a day, in different parts.
On her return home she had to acknowledge that she was favored with the reward of peace;
which she esteemed a sufficient reward for the various
exercises which attended that laborious service.

It may be premised that she had previously been engaged
in a religious visit to Devonshire and Cornwall,
in which, as related in a letter by Mary Weston to Israel Pemberton, of Philadelphia,
dated Third Month 8th, 1753:

She had uncommon service at public places of resort, markets, among stage players, etc.,
as also concerned to go through many of the streets of the city of Exeter,
preaching repentance to the people,
sometimes going to the magistrates and those in authority, with warnings, exhortations,
etc., and from what I learn had great place in the minds of many.
Indeed she seems gifted for such service; a courageous,
able minister in the judgment of most.

The account of her visit to London was drawn up by Joseph Phipps,
who accompanied her through the streets of the city.
He says:

Ann Mercy Bell, having acquainted the proper meeting,
with a concern which had long lain weightily upon her mind,
to visit the inhabitants in some of the public parts of this metropolis;
and that meeting after deliberation, having left her to her liberty;
on the fifth of Eighth Month, 1753, about ten o`'clock in the forenoon, she set out,
accompanied with several friends, and came into Rosemarylane,
at the end of Red Lion Street.
The lane was spread, up and down, with abundance of loitering people;
and upon our Friend`'s beginning to speak, many of them flocked up to us.
She preached the necessity of repentance and amendment, sometimes walking,
and sometimes standing a few minutes, in a most tender and engaging manner.
Opening the conditions of many, showing the danger of continuing in them,
and recommending the grace of God, in mercy extended, for their help;
which apparently was received with great openness of heart.

We proceeded gradually, till we came opposite to a public-house,
at the corner of a street: and a hasty shower coming on,
the people invited us in for shelter.
Many were sat drinking in the boxes, to whom Mercy gave a compassionate exhortation,
which was kindly accepted, both by the guests, and the woman who kept the house.

When the shower was over, we left the house,
being followed by a pretty many to the Ropewalks; where, stepping on a small rising bank,
she stood a while in silence, till the people gathered more generally,
which they presently did, from several parts, to a great number.
Here she had a fresh and open time, for about the space of twenty-five minutes.
A great solemnity came over them,
and the tears streamed plentifully from several of their eyes.
They gave various tokens of the reach they felt, by smiting their breasts,
and other sensible expressions of concern; and, when she closed her speech,
several cried out:
"`We never had such a visit as this! this is not such preaching as theirs,
that come with hell and damnation in their mouths.
She comes from God, to offer his grace and mercy to us.
It is a great mercy to us, poor miserable creatures, indeed!`"
One woman tenderly acknowledged, that she had originally descended from Friends,
but had left them when young, for the sake of a wider path, and made herself miserable.
She was thankful to find the Divine visitation renewed to her,
and that she was not finally forsaken.
In the afternoon Mercy attended Westminster meeting.

15th.--Leadenhall Market having laid before her with great weight, for some time,
in the afternoon, she gave up to go.
Entering in at the lower end of the Poulterer`'s Market, she went through,
calling to repentance, as she passed, with uncommon force and solemnity;
and coming to a convenient place in the Leather Market, after the people,
who poured in at every avenue, were gathered around her,
she had a large and favorable opportunity with them.
Their behavior was very commendable.
They attended with stillness, and afterwards expressed a general satisfaction,
wishing for more such opportunities.
An elderly woman, of good appearance, said "`She had the Gospel in her very soul,
and she believed many hearts were pierced.`"

16th.--In the morning she went through Long-alley, calling to repentance,
and then passed into the upper part of Moorfields,
where she preached to a large concourse of people,
and afterwards had something particular to the children,
several of whom stood dropping their tears before her.
Then coming to the bottom of the Middle-field, finding a renewal of her concern,
she appeared, a second time, to a great number.
Many expressed much satisfaction, and prayed success might attend her labors.

Returning into the city, soon after twelve o`'clock, she appeared by Wood Street end,
in Cheapside; afterwards at two different places in Paul`'s church-yard,
and again at Fleet-ditch; scarce less than half an hour at each of the six times,
and at some of them more.
At every place she was, generally, well received.
The strength and distinction she was furnished with, in this great day`'s work,
was matter of admiration to us who accompanied her.

Many of the people, who had followed from place to place,
observed with astonishment that she had not only held out,
but seemed to grow in strength to the last,
and concluded it must be owing to an immediate support from the Divine Power.
Some audibly confessed they had a feeling sense of it.

In bringing to a close his narrative of this remarkable visit, Joseph Phipps says:

In the prosecution of it she was generally attended with about half a dozen friends,
who were pretty constant, and occasionally, by above fifty others;
all of their own voluntary motion.
She was cautious of giving offence,
and therefore excused herself from accepting the attendance of such, when offered, as,
from their particular conduct or general character, might give any occasion of umbrage.
Though, in such a public way of appearing, a mixture of such could not be always avoided.

Her practice was, not to set out by the persuasion of others, nor merely at a venture;
but as she found her mind drawn to any part, then and there she went.
And though frequently in great weakness, and, as she sometimes said,
with so small a portion of faith it was but just perceivable; yet,
through the goodness of God, whose cause was her inducement,
it arose upon every engagement and increased to such a degree
of sufficiency that there was no want of anything;
it constantly ended in a never-failing supply, fully answerable to every exercise.
