== Chapter XI. Love of the Brethren

Our Saviour, when personally on earth, told his followers:
"`By this shall all men know that ye are my disciples, if ye have love one to another.`"
Living as our early members did,
in intimate communion with Him who is the fountain of Divine love,
it is not surprising that they imbibed this blessed principle in large measure.

William Penn declares that their love for each other was
one of the characters that distinguished the Society.
And not only so, but they manifested their love to those who had wronged them,
by relieving them when it was in their power so to do.

During the time of persecution, many Friends had been long in jail,
and there appeared to be no prospect of release,
when the following paper was presented to parliament:

Friends:--Who are called a Parliament of these nations:
we in love to our brethren that lie in prisons, and houses of correction and dungeons,
and many in fetters and irons, and have been cruelly beat by the cruel jailers,
and many have been persecuted to death, and have died in prison,
and many lie sick and weak in prison and on straw.
So, we in love to our brethren do offer up our bodies and selves to you, for to put us,
as lambs, into the same dungeons and houses of correction,
and their straw and nasty holes and prisons, and do stand ready,
a sacrifice to go into their places, in love to our brethren, that they may go forth,
and that they may not die in prison, as many of the brethren have already died.
For we are willing to lay down our lives for our brethren,
and to take the sufferings upon us that you would inflict upon them.
If our brethren suffer, we cannot but feel it; and Christ saith, it is He that suffereth,
and was not visited.
This is our love towards God and Christ, and our brethren, that we owe to them,
and to our enemies, being lovers of all your souls, and of your eternal good.

And if you will receive our bodies,
which we freely tender to you for our friends that are now in prison,
for speaking the truth in several places--for not paying tithes--for
meeting together in the fear of God--for not swearing--for wearing
their hats--for being accounted as vagrants--for visiting Friends--and
for things of a like nature&hellip; We whose names are hereunto subscribed,
(being a sufficient number to answer for the present sufferers,)
are waiting in Westminster Hall for an answer from you to our tender,
and to manifest our love to our friends,
and to stop the wrath and judgment from coming upon our enemies.

This was signed by one hundred and sixty-four Friends.

Parliament refused their request,
and indeed appeared to be offended at the exposure of the injustice of the magistrates;
but there is little doubt that this act was not without its influence.
The eloquent Henry Armitt Brown remarks respecting it:

I know of few things in the history of the English race more noble than this act.
No poet has made it the subject of his eulogy,
and even the historians of civil and religious liberty have passed it by.
But surely never did the groined arches of that ancient
hall look down upon a nobler spectacle.
They had seen many a more splendid and brilliant one, but none more honorable than this.
They had looked down on balls banquets and coronations, and the trial of a king,
but never, since they were hewn from their native oak,
did they behold a sight more honorable to human nature
than that of these humble Quakers grouped below.
They had rung with the most eloquent voices that ever spoke the English tongue,
but never heard before such words as these.

George Fox mentions in his Journal that when he was in prison at Lancaster:--

A Friend went to Oliver Cromwell, and offered himself, body for body,
to lie in Doomsdale in my stead; if he would take him and set me at liberty.
Which thing so struck him, that he said to his great men and council:
"`Which of you would do so much for me, if I were in the same condition?`"
And though he did not accept of the Friend`'s offer, but said, "`He could not do it,
for it was contrary to law;`" yet the Truth thereby came mightily over him.

In those days the Friends who were present at meetings for worship were
liable to be seized and thrust into prison with but little ceremony.
In their watchfulness over one another it soon became a practice
to select certain Friends who should care for those thus imprisoned.
Thomas Ellwood mentions that on one occasion thirty-two, of whom he was one,
were taken at a meeting in London and sent to Old Bridewell.
He says:

It was a general storm which fell that day,
but it lighted most heavily upon our meetings;
so that most of our men Friends were made prisoners and the prisons generally filled.
And great work had the women, to run about from prison to prison, to find their husbands,
their fathers, their brothers, or their servants;
for accordingly as they had disposed themselves to several meetings,
so were they dispersed to several prisons.
And no less care and pains had they, when they had found them,
to furnish them with provisions, and other necessary accommodations.
But an excellent order, even in those early days,
was practised among the Friends of that city,
by which there were certain Friends of either sex,
appointed to have the oversight of the prisons in every quarter,
and to take care of all Friends, the poor especially, that should be committed thither.
This prison of Bridewell was under the care of two honest, brave,
discreet and motherly women.
So soon as they understood that there were Friends brought into that prison,
they provided some hot victuals, meat and broth, for the weather was cold,
and ordering their servants to bring it with bread, cheese, etc.,
came themselves also with it, and having placed it on a table, gave notice to us,
that it was provided for all those that had not others to provide for them;
or were not able to provide for themselves.
And there wanted not among us a competent number of such guests.

Thomas Ellwood, though he had lived as frugally as he could,
had by this time reduced his little stock of money to ten pence, "`which,`" says he,
"`was all I had about me, or anywhere else at my command.`"
He was not discouraged at the prospect before him, nor did he indulge a murmuring thought.
"`I had lived,`" says he, "`by providence before,
when for a long time I had no money at all,
and I had always found the Lord a good provider.`"
Although from his account he had eaten little that morning,
and the sight and smell of hot food was sufficiently enticing to his empty stomach,
yet considering the terms of the invitation he questioned whether he was included in it,
and at length concluded that while he had ten pence in his pocket,
he would "`be but an intruder to that mess, which was provided for such as, perhaps,
had not two pence in theirs.`"

In the evening the porter coming up, he desired him to bring him a penny loaf only,
but not being able to do this, he brought him two half penny loaves,
which he says suited him better, as one loaf made him both dinner and supper,
the other being reserved for next day.
His lodging was under a table, the frame of which looked, he thought,
"`somewhat like a bedstead.`"
Making sure of that, he gathered up a good armful of the rushes,
wherewith the floor was covered, and spreading them under that table,
crept in upon them in his clothes, and keeping on his hat,
laid his head upon one end of the table`'s frame, instead of a bolster.
His example was followed by the rest,
beds being made with rushes in other parts of the room.
By the middle of the night they all found themselves cold,
but getting up and walking till they had pretty well warmed themselves,
lay down again and rested till morning.
Next day, those who had families or belonged to families,
had bedding of one sort or other brought in.

Thomas Ellwood did not fare so well, but kept to his rush pallet under the table,
for four nights together, "`in which time,`" he says, "`I did not put off my clothes;
yet through the merciful goodness of God to me, I rested and slept well,
and enjoyed health without taking cold.`"

Thomas Ellwood and other Friends, were continued prisoners by an arbitrary power,
from the twenty-sixth day of the Eighth Mo. 1662,
to the nineteenth of the Tenth Mo. following.
On that day they were had to the sessions at the Old Bailey.
But not being called there, they were brought back to Bridewell,
and were continued there to the twenty-ninth of the same month,
and then were carried to the sessions again,
and refusing to take the oath of allegiance which was tendered to them by the recorder,
inasmuch as their Lord and Master Christ Jesus had expressly
commanded his disciples not to swear at all,
they were all committed to Newgate, and thrust into the common side.
That side of the prison they found very full of Friends,
as were all the other parts of that prison, and their addition caused a great throng.
And though they had liberty of the hall, which in the daytime was common to all,
felons as well as others, yet in the night all lodged in one room: there were many sick,
and it was not long before one of their fellow prisoners,
who lay in one of those pallet beds, died.
"`This caused some bustle in the house,`" as it was requisite that
the coroner should enquire into the cause and manner of his death,
"`and the manner of doing it is thus: as soon as the coroner is come,
the turnkeys run out into the street under the gate,
and seize upon every man that passes by,
till they have got enough to make up the coroner`'s inquest.`"
If they resist they will drag them in by force,
and "`will not stick to stop a coach and pluck the men out of it.`"

It so happened that at this time they lighted on an ancient man, a grave citizen,
and laid hold on him, and although he was going on very urgent business,
they were deaf to all entreaties, and hurried him in,
the poor man chafing without remedy.
In this way they got their complement, and this ancient man, the oldest among them,
was made foreman.
He proved to be a man who was not to be trifled with,
but understood his place and their duty.
"`I require you,`" says he,
"`to conduct me and my brethren to the place where this man died; refuse at your peril.`"
They now wished they had let the old man go about his business, but it was too late,
and they were obliged to show him the place.
As soon as they were come to the door, the foreman, who led them, lifting up his hand,
said, "`Lord bless me, what a sight is here!
I did not think there had been so much cruelty in the hearts
of Englishmen to use Englishmen in this manner!
We need not now question,`" said he to the rest of the jury,
"`how this man came by his death;
we may rather wonder that they are not all dead,`" with other indignant remarks,
and an intimation that he would "`find means to let
the king know how his subjects are dealt with.`"
Whether he did so or no, I cannot tell,
but I am apt to think he applied himself to the mayor or sheriffs of London.
On the next day an arrangement was made by one of the sheriffs,
that all the prisoners who came from Bridewell should return thither again,
where they would find better accommodations,
and more room be given for those left behind, "`and here,`" said the sheriff,
"`is the porter of Bridewell, your old keeper, to attend you thither.`"

In the year 1678, George Fox writes thus:

Now it was a time of great suffering, and many Friends being in prison,
many other Friends were moved to go to the parliament,
to offer themselves up to lie in the same prisons where their friends lay,
that those in prison might go forth and not perish in the stinking gaols.
This we did in love to God and our brethren, that they might not die in prison;
and in love to those that cast them in,
that they might not bring innocent blood upon their own heads;
which we knew would cry to the Lord, and bring his wrath,
vengeance and plagues upon them.

At one time Friends in Wales suffered much,
largely through the efforts of an informer who sought
to enrich himself by the spoil of their estates,
but his efforts were much frustrated by the courage of John Thomas, a Welsh Friend,
who was willing to encounter personal risk for the sake of his brethren.

The chief informer,
through whose cupidity much of the suffering was brought upon Friends,
finding that the high constable and the subordinate officers of the law,
were loath to execute warrants upon their innocent and peaceable neighbors,
whose only offense was obedience to their religious principles,
determined to get an appointment of high constable for himself.
This he thought would enable him to take hold of the estates of the Quakers speedily,
and ensure the enriching himself by ruining them.
He had secured the good will of many or most of the great men of the county,
to assist him in obtaining the office.

John Thomas hearing of the man`'s design, set himself to frustrate it.
With this view, he called upon one of the justices, who was a moderate man,
and as such willing to alleviate the sufferings of the innocent,
and desired him to accept him as high constable.
This, it appears, was in his power as justice to do,
and he willingly granted the request,
not often having the opportunity to confer the office
on one of such standing in the community,
for property and respectability.
John was now high constable,
and all the warrants for distraint on Friends were brought to him to execute.
When the informer urged a speedy process, he told them that he was now responsible,
and quietly kept the warrant.
John did not doubt but that eventually he would be ruined in his estate by the informer;
for there was a clause in the act under which he held his commission,
that if a constable should refuse to execute the duties of the office,
he was liable to a heavy fine.
Yet in faith towards his Lord and out of love to the brethren,
he received the warrants as they came, until nine were in his hands.

At this period came forth very opportunely the king`'s "`declaration`"
for suspending the penal laws in matters ecclesiastical.
This "`declaration,`" after referring to his care
for the interest of the church of England,
by the various ways of coercion made use of under his authority,
to cause dissenting persons to return to its communion, states,
that it is "`evident by the sad experiences of twelve years,
that there is very little fruit of all these forcible methods.`"
It then goes on to "`declare our will and pleasure to be, that the execution of all,
and all manner of penal laws in matters ecclesiastical,
against whatever sort of Non-conformists or Recusants, be immediately suspended,
and they are hereby suspended, and all judges, sheriffs, justices of the peace, etc.,
are to take notice of it, and pay due obedience thereunto.`"
Thus John was released from all hazard,
and for a short period he and his Friends were allowed to meet together without molestation.
This faithful man afterwards removed to Pennsylvania.

Hugh Roberts had been intimate with him from his childhood,
and was with him at the closing scene.
A little before his departure, addressing those around his dying bed, he said: "`Friends,
wait upon the Lord, for He is near.`"
Shortly after, he added: "`Blessed be thy name, Lord God everlasting!
Thy will be done on earth, as it is in heaven!`"
Hugh says: "`With such expressions, magnifying and praising the name of the Lord,
he took his leave of us, giving his hand to every one of us; and in a sweet,
heavenly frame, he departed.`"

The love which prevailed among our early Friends,
often found occasions for its exercise in pleading with
those in authority for their brethren who were under suffering.

In the Memoirs of his Life,
George Whitehead frequently speaks of the labors which he
underwent for the relief of his suffering Friends.
Being a man of good ability, quick of perception, and undaunted spirit,
he had more influence with men in authority than many others;
and he was freely given up to spend his time in pleading
with such for those who were imprisoned or abused,
on account of their religious principles.
He says:

In the year 1670, in the Eighth Month, having been in the country,
and returning to London, I was taken with a great pain in my head, whereupon I grew sick,
which turned to an ague and fever.
I became very weak in body,
so that for some weeks there appeared little hope of recovery; this sickness continued,
and I remained in much weakness about six months,
until the beginning of the Second Month, 1671, and partly the beginning of that summer,
and then it pleased the Lord gradually to restore me to health and strength.

In that sickness, when most weak in body,
being well prepared and freely resigned in the will of the Lord to die,
that I might ever be with Him, I had an opening or apprehension,
that when I died my soul should be received into the bosom of my heavenly Father.

While I was in great weakness of body,
I was divers times told of the great and cruel sufferings of our friends in Southwark,
for meeting together at their usual meeting place at Horsleydown;
how barbarously and cruelly they were used, and grossly abused by soldiers and armed men,
both horse and foot, being not only kept out of their meetinghouse in the street,
but both men and women were violently pushed with muskets and other weapons--beaten,
bruised, hurt and wounded,
and much blood shed by the blows and wounds from
those inhuman persecutors and brutish persons.
The accounts of these and such barbarities against the innocent,
did very sorrowfully affect me;
and I deeply sympathized in spirit with the innocent sufferers,
earnestly praying to Almighty God for them that He would preserve and deliver them,
and rebuke that persecuting spirit by which they suffered;
earnest prayers with tears being then the church`'s very great concern,
which the Lord our God in his own time, graciously heard and answered,
blessed be his name.

The meetinghouse at Horsleydown was pulled down by order of the king and council,
because Friends persisted in holding their religious meetings in it.
George Whitehead says:

Our innocent Friends, as obliged in conscience toward Almighty God,
resolved to keep their solemn meetings in his dread and fear;
not being terrified therefrom by the rage and violence of their persecutors,
but constantly resorted to their said meetinghouse on First-days, while it was standing.
After it was pulled down,
they removed the rubbish that they might meet on the ground where their own house stood,
which they did until by force haled out, and barbarously used by the soldiers.

On the twenty-fifth of the Seventh Month, 1670,
Friends being peaceably assembled at their usual meeting place aforesaid,
there came some musketeers, and haled them forth into the street,
where the troopers came and rode in among them, in a violent, furious manner,
beating and abusing both men and women, punching them in the face and bodies,
with their carbines.
Soon after the foot soldiers came and fell upon them also,
and beat both men and women in a cruel and outrageous manner--punching
them on the feet with the butt-ends of their muskets,
till they broke some of them,
and running the muzzle of their muskets violently against the bodies of many.
Then a party of horse came desperately and strove to ride over them;
but the horses being more merciful, or naturally more gentle than the riders,
would not go forward to tread the people under foot; then the riders turning them,
curbed and reined them to do mischief.

The number of those that were wounded and sorely bruised this day,
was above twenty persons.

On the second day of the Eighth Month,
they being kept out of their meeting place aforesaid,
there came a party of foot and a party of horse,
and laid on Friends in a violent and cruel manner,
knocking them with their muskets and pikes, and the horsemen with their carbines,
until the blood lay in the streets; and so they continued for some time,
until they broke several pikes and muskets, and one carbine;
and several were so beaten and bruised that their lives were in danger.
They that were wounded and sorely bruised this day were above thirty persons.

Similar barbarities were practised at the meetings
held on the ninth and sixteenth of Eighth Month;
and in reference to them George Whitehead says:

I was the more willing to insert the foregoing relation in this place,
because I was very deeply and sorrowfully affected by the frequent
accounts which came to me of those barbarous and cruel persecutions,
in the time of my long sickness and great weakness of body.
The Lord my God having restored me to health,
enabled me again to labor and travel in his service,
in the Gospel of his dear Son Christ Jesus, and also to suffer with his people,
and to attend and solicit the king and government for their relief.
The hand of the Lord and his counsel were often with me, to help,
encourage and strengthen my heart in those services which many times had good effects,
the Lord`'s power going before and making way in the hearts of both king and council.

There was but little respite from persecution in twelve years`' time,
from the year 1660 unto 1672,
in which was the last war at sea between the English and Dutch.
One judgment and calamity followed another; plague,
fire and war unto great depopulation and devastation,
showing God`'s heavy displeasure against persecution and cruelty,
and that spirit which had been so highly at work against innocent,
conscientious and honest people, some whereof the Lord delivered by death;
yet many persecutors were so hardened, that they repented not of their cruelties,
and we have observed in our times, how suddenly the Lord swept away many of that sort.

Howbeit, by this time, A. D. 1671-2, the king seemed to bethink himself,
to take other measures than to continue persecution to destroy his own subjects,
not knowing what issue the Dutch war against him might come to;
insomuch that he published a declaration of indulgence to dissenters,
to suspend the execution of penal laws in matters ecclesiastical.

Soon after the declaration of indulgence was published in print,
as I was solitarily upon the road, returning toward London, out of the country,
a very weighty and tender concern fell upon my spirit,
with respect to our dear Friends then in prisons,
being above four hundred in and about England and Wales,
many of whom had been long straitly confined, under divers prosecutions,
sentences and judgments, as to imprisonments, fines, forfeitures and banishments,
for meeting, for not conforming, for not swearing allegiance,
and divers under sentence of premunire,
some having endured ten or eleven years`' imprisonment,
besides those who suffered long for non-payment of tithes.

Whereupon I was moved to write a few lines to the king, requesting their liberty,
which I intimated to our honest and loving friend, Thomas Moore,
who was often willing to move the king in behalf
of our suffering Friends for their liberty,
the king having some respect for him;
for he had an interest with the king and some of his council, more than many others,
and I desired him to present my few lines to the king, which he carefully did,
and a few days after, both he and myself had access into the king`'s presence,
and renewed our request which I had made to him in my letter before;
whereupon the king granted us liberty to be heard on Friday, as he said,
before the council, being the next council-day in the same week.

And then Thomas Moore, myself and our friend, Thomas Green,
attended at the council chamber at Whitehall,
and were all admitted before the king and a full council,
and being called to go up before the king, who was at the upper end of the council-board,
I had a fair opportunity to open the case of our
suffering Friends as a conscientious people,
chiefly to show the reason of our not swearing allegiance to the king;
that it was not in any contempt, or disrespect,
either to the king`'s person or government,
but singly as it is a matter of conscience to us, not to swear at all, in any case,
and that in sincere obedience to Christ`'s command and Gospel ministry.
When I had opened and more fully pleaded our suffering Friends`' case,
the king gave this answer, viz: I will pardon them.

Pursuant to the king`'s promise,
an order was given to the attorney general to draw up a pardon.

After we had taken out the foregoing order and warrant,
our friend Thomas Moore and I carried and delivered
the same to the king`'s attorney general,
sir Heneage Finch.
Thomas again scrupling the word pardon to him, as he had before to the king, etc.,
he took up Thomas somewhat short, telling him, "`Mr. Moore,
if you will not accept of his majesty`'s pardon,
I will tell him you will not accept thereof.`"
Then to pacify him I told him that it was not our business to question,
but accept what the king had granted for the relief of our suffering Friends,
that they might be released and discharged from their imprisonments and sufferings, etc.
Whereupon he seemed satisfied.

The attorney general ordered his principal clerk, +++_______+++ Nicolls,
to draw up the said bill, to contain the king`'s letters patent,
for a full discharge and release of our suffering Friends, from their imprisonments,
sentence of banishment, fines, forfeitures, premunire, etc., which, when he had done,
I got Ellis Hookes, our writer,
to draw out four or five fair copies thereof for expedition,
to be passed and entered and remain upon record in the several offices,
which the same was to pass through, as the Privy Seal, the Signet, the Patent,
the Hannaper offices, etc.

And understanding that because of the number of names in the patent,
great fees would be required in most of those offices, except the lord keeper`'s,
who had promised to remit his fee, and that he would ask none of us,
which was a kindness;
for there being above four hundred names of the sufferers
in one and the same instrument to be discharged,
we understood they would demand a great fee for each person, and, as we heard,
it would cost a single person twenty or thirty pounds charge
in fees to get a patent or pardon through all those offices,
to pass under the great seal of England,
so that we were constrained to make further application to the king,
to remit or abate the great fees.
Whereupon the king gave order, according to our request, as follows:

His majesty is pleased to command,
that it be signified as his pleasure to the respective offices and sealers,
where the pardon to the Quakers is to pass, that the pardon,
though comprehending a great number of persons, do yet pass as one pardon,
and pay but as one.

Arlington

At the Court at Whitehall, 13th of September, 1572.

But though we had this warrant from the king,
yet we had trouble from some of the covetous clerks, who strove hard to exact upon us.

When the instrument for the discharge of the prisoners was granted to our friends,
there being other dissenters besides Quakers in some prisons, as Baptists,
Presbyterians and Independents; some of their solicitors, especially one William Carter,
seeing what way we had made with the king for our friends`' release,
desired their friends in prison might be discharged with ours,
and have their names in the same instrument,
and earnestly requested my advice or assistance, which I was very willing to give,
in compassion to them.
Accordingly, I advised them to petition the king, with the names of the prisoners in it,
for his warrant, to have them inserted in the same patent with the Quakers,
which they petitioned for, and obtained.

Gilbert Latey, of London,
was a sympathizing friend and efficient helper of
those who were under suffering for conscience`' sake.
He was a man who was highly esteemed,
and had much influence with some prominent individuals.
In the year 1660, Catharine Evans and Sarah Cheevers, in the course of a religious visit,
were imprisoned at Malta.
Gilbert learned that one Lord D`'Aubigny, who came over to England with the queen-mother,
had interest and command in the island of Malta.
He soon obtained access to him,
and pleaded with him for the release of the two women from the cells of the Inquisition.
He was very kind and free to Gilbert, and reasoned with him like Felix with Paul,
about the principles of Truth and way of the Lord;
and being informed concerning the power of God and the manner of the Spirit`'s working,
answered that some of their people thought our friends were mad.
"`But,`" said he, "`I do not think so of them.`"

In discourse with him at another time, he said: "`Let me talk with you ever so long,
you will tell me of the spirit of God, and the grace of God,
and the work and operation thereof,
and the love of God you are made witnesses of through Jesus Christ, which, I believe,
may in a measure be true;
but do you not think it is well to have something
to represent that which you so much love?`"
To which Gilbert Latey answered that the substance of all things is come,
Christ in us the hope of glory, and all the outward types,
representations and shadows must come to an end and be swallowed up in one blessed Lord;
who told his disciples it was expedient for them He should go away; but, said He,
I will not leave you comfortless.
If I go not away, the Comforter will not come; but if I depart, I will send Him unto you,
even the spirit of Truth, which shall guide you into all truth;
and also that He who was with them should be in them.
This being witnessed, these needed nothing outwardly to represent or put them in mind,
for He being so near was himself the saints`' daily remembrancer.
Upon this they parted, but Gilbert Latey often visited him,
to desire and remind him to show kindness to the Friends
that were under confinement in a strange place,
and at so great a distance from their friends and their native country.

Some time after this,
through the kind interference of the lord D`'Aubigny on their behalf,
Catharine Evans and Sarah Cheevers were set at liberty.
They returned to England, and, accompanied by Gilbert Latey,
waited upon the lord D`'Aubigny, who, though a Romish ecclesiastic,
appears to have been a man of candor and liberality,
and received them with kindness and respect.
They expressed their acknowledgments, and as the Lord put it into their hearts,
spoke to him, adding that, were it in their power,
they should be as ready in all love to serve him; upon which he replied: "`Good women,
for what service or kindness I have done you,
all that I desire of you is that when you pray to God,
you will remember me in your prayers.`"

In the year 1665, London was visited with the plague,
which swept away about one hundred thousand of its inhabitants.
Gilbert Latey had taken lodgings in order to go into the country;
but as many Friends were under close confinement in the prisons at this time,
he could not find freedom to leave the city, to go and be at ease,
while his brethren were thus under sufferings, and therefore remained there,
and according to his wonted manner, visited them in the jails,
and endeavored that nothing should be wanting for their support, or,
according to his power, to procure their enlargement.
In this time of terror and sore distress,
he was also engaged in visiting Friends in their families.
He sought the sick, the poor and the convalescent,
to administer aid and comfort in their affliction.
"`The Lord inclined several Friends who were in the country
to consider the poor who were under this great calamity,
and accordingly they sent money to be distributed,
a part of which was allotted to the poor people who were ill with the sickness,
but more especially to those who were shut up in
their houses in the out-parishes without Temple Bar.
This service was committed to the care of Gilbert and one other Friend,
to visit the poor, particularly those who were confined to their own houses,
and as near as they could, they neglected none,
but went and administered the charity to them.`"

In the performance of this self-sacrificing duty he was much exposed to the contagion,
many of the families he visited having the disease in its most terrible forms.
The Lord, whom he was endeavoring to serve, was, however, with him,
and preserved him in health through all this exposure.

Soon after king James came to the crown,
Gilbert Latey was one who presented the king with a list of about fifteen hundred Friends,
prisoners for conscience`' sake,
about eight hundred of whom being "`escheated,`"
and writs about to go forth for seizing their estates,
he, with George Whitehead,
took great care and unwearied pains to have a stop put to these violent persecutions.
This service occupied much time and labor, but was eventually rewarded with success,
the prisoners released and relieved from the penalties which unrighteous laws had imposed.
Of another interview with king James the following account is given:

In the year 1688, Gilbert and two Friends, viz: George Whitehead and William Penn,
meeting at White-hall,
they asked him if he would go along with them to wait upon the king.
He made some little pause before he gave his answer, having nothing in his mind to say,
or to attend the king for; and as he thus stood silent,
it opened in his heart what he should say to the king,
whereupon he told the Friends he was ready to go with them.
Accordingly they went, and had admittance to the king`'s presence,
there being only one person present besides the king and the two Friends.
George Whitehead and William Penn having spoken what they had to say,
the king was pleased to ask Gilbert whether he had not something to say.
Upon which, in a great deal of humility, he spoke as follows: "`The mercy,
favor and kindness which the king hath extended to us a people,
in the time of our exercise and sore distress, we humbly acknowledge,
and I truly desire that God may show the king mercy and
favor in the time of his trouble and sore distress.`"
To which the king replied: "`I thank you;`" and so they parted.

What was then spoken by Gilbert Latey lived with the king; and a considerable time after,
when in Ireland, he desired a Friend to remember him to Gilbert,
and "`Tell him the words he spake to me I shall never
forget;`" adding that one part of them was come,
and he prayed to God the other might also come to pass.
Gilbert Latey desired the Friend, when he returned again to Ireland,
if he had opportunity to see king James,
to let him know that the second part of what he had said, in relation to the king,
was also in great measure come to pass, and that the Lord had given him his life.

There is reason to believe that this worthy man felt it a serious
thing thus to appear before the great of this world,
and was careful not to go in his own will.
With his mind humbly waiting upon the Lord for strength and wisdom,
he doubtless sought to be directed and guided in these movements
by the gentle influence of his pure Spirit.
The account from which we have quoted says:

It was his practice, in soliciting kings, princes, and great men,
to keep to the anointing and love of God; and, as that gave utterance, to speak;
in which he oft-times reached and had place in them,
and his solicitation was often answered, which made him say,
that as Friends feel and keep to this anointing in their solicitations,
they may expect a blessing and therein be serviceable to the Lord`'s people; but if,
on the contrary, any shall go in these services in their own will, wit and parts,
they may miss the desired end as some have done.

Gilbert Latey was blessed and prospered in his business,
so that he had plenty of this world`'s goods, to supply all his reasonable wants,
notwithstanding the continued exactions of heavy fines,
for attending meetings and on other accounts.
It was a great trouble to him that his friends should be
made to suffer on account of his being at their meetings,
or speaking in them,
and he sought as much as possible to screen Friends and bear the burden himself.
And it being known that he was a man of ability,
the justices and informers were usually willing, when they had an opportunity,
to fix what they were permitted to take upon him:--thus at one time there
were warrants against him to the amount of several hundred pounds.
So striking indeed was the protection and favor vouchsafed
to him that the enemies of Truth were ready to say,
as their master once did: "`Doth he serve God for nought,
hath He not set a hedge about him and all that he hath.`"

In married life also the Divine blessing attended this faithful man.
His wife, who survived and wrote a testimony respecting him, says in it:
"`He was to me a faithful, loving husband, and a dear and tender father to his children,
often admonishing, advising and instructing them to lowliness, humility,
and the fear of the Lord.
He was a good example to them,
being often concerned in the fear of the Lord to excite them to love God,
his Truth and people;
by which they would feel the power of the Most High to preserve them out of evil,
as he could truly say it had done for him, and preserved him to a good old age.`"

Toward the latter part of his life, Gilbert Latey delighted in quiet and retirement,
often mentioning that he waited the Lord`'s call, and time of being removed;
that he felt his peace to abound in him, and that there was no cloud in his way.

Though he was long weak and feeble as to the outward, yet he was fresh, strong,
and living in his inward man; and in the latter end of the Fifth Month, 1705,
was at the meeting at Hammersmith.
A large meeting being there assembled, the Lord moved him to stand up,
and so supported him by his Divine power,
as to enable him to sound forth the acceptable day of God,
and an invitation to all to come to Him, in and through the Lord Jesus Christ,
the alone mediator between God and man,
who is the way and only means to restore man again into the image and favor of God;
concerning which he there declared about an hour,
with a great deal of fervency and wonted zeal,
as if he had been under no infirmity of body,
even to the admiration of many of the hearers;
he being carried forth in a more than ordinary manner in this his last sermon.

The night before he departed he gave good counsel to them that were in the room,
to fear the Lord and not do evil for evil, but to do good for evil,
for that there was no overcoming of evil but in and by that which was good,
for in so doing, coals of fire would be heaped on their heads;
exhorting very much to love and tenderness,
for the Lord would bless such as were found therein.
He was much opened in exhortation and counsel at this time,
and uttered his words with great vigor, as if he ailed little and were in a meeting.
Next day he kept his chamber, being weak of body,
but preserved in the enjoyment of his reason to the last moment;
and a very few hours before his departure, spoke to some that were about him:
"`That there was no condemnation to them that were in Christ Jesus; for, said he,
He is the lifter up of my head, He is my strength and great salvation.`"

Thus trusting in,
and reverently reposing upon Him who is the strength and refuge of his redeemed children,
the aged Christian calmly met that solemn change which awaits all the living.
He peacefully departed on the fifteenth of Ninth Month, 1705,
aged about seventy-nine years.

The practice of benevolence, of that love to God which manifests itself in love to man,
was not confined to the early members of the Society of Friends.
It was exemplified in the life of that eminent physician, John Fothergill, of London,
who was a consistent Friend.
He was a coadjutor of Howard, in his efforts to reform the management of prisons.
Dr. Franklin once wrote of him: "`I can hardly conceive that a better man ever existed.`"
He died in 1780.
This worthy man was the son of John Fothergill, and brother of Samuel Fothergill,
both of whom were eminent ministers and diligent laborers in the Lord`'s service.

Dr. Fothergill acquired wealth by his profession, but seems to have valued money little,
except as a means of doing good, and relieving the distresses of his fellow creatures.
The following is one of many instances which are related of his generosity and benevolence.
A respectable man who had a large family to support
on a salary of fifty pounds per annum,
was brought into a great strait when epidemical disease
seized upon his wife and five of his children.
In this state of distress, he greatly desired to have the advice of Dr. Fothergill,
but dared not apply for it,
from a consciousness of being unable to reward him for his attendance.
A friend kindly offered to accompany him to the doctor`'s, and give him his fee.
They took advantage of his hour of audience,
and after a description of the several cases, the fee was offered and rejected,
but a note was taken of his place of residence.
The doctor assiduously called from day to day,
until his attendance was no longer necessary.
The grateful man,
anxious to return some evidence of the sense he entertained of his services,
strained every nerve to accomplish it; but his astonishment was great,
when Dr. Fothergill, instead of receiving the money he offered,
put ten guineas into his hands, desiring him to apply to him without hesitation,
in future difficulties.

A good many years ago, there lived in the town of Haverfordwest two maiden women,
members of the Society of Friends.
They were pious, godly women,
and devoted their whole lives to the service of their Divine Master.
This they were enabled to do the more easily,
as they were possessed of those two great talents, time and money;
and nobly they employed them.
They had their reward,
for their prayers and their alms went up for a memorial before the Lord.

The following is a narrative of a very remarkable
circumstance that occurred to the elder sister,
showing how God himself condescended, in a most direct manner,
to employ her as his instrument to minister to the need of one of his saints.

One bleak winter`'s morning, Friend Elizabeth Lewis awoke very early,
impressed in a strange manner.
She became perfectly convinced in her mind that a poor widow,
whom she sometimes relieved, was in great want,
and she ought not to delay one moment in sending to her aid.
Though it was still night, she rose immediately,
and called her maid--who much wondered what ailed her mistress,
that she should be disturbed at such an unseasonable hour--and
directed her to go at once and fetch Sally James,
who lived near, and whom she always employed on her errands of mercy.
While waiting the return of her messenger,
she busied herself in collecting together a goodly supply of food and other necessaries,
and packing them in a large basket.
When Sally James arrived, wondering, like the maid, at being sent for so early,
the worthy woman thus addressed her: "`Sally,
I have it on my mind that old Betty White is in great want.
I could not sleep for thinking about her.
Take her this basket and go to her at once.`"

Betty White was an aged widow,
who earned a scanty living by sorting rags at a neighboring paper mill.
Her daughter some time before had married; both she and her husband had died,
leaving two little children quite destitute.
The grandmother could not bear the thought of their going to the workhouse,
so she took them and managed somehow to support them,
till a fortnight previous to the time I am now writing of, when she was taken ill,
and not being able to follow her occupation, her little means were soon gone,
and starvation stared her in the face.
Now was her time of trial, but her faith did not fail her;
though she had no food in the house, and no visible means of obtaining any,
she trusted in the God of the widow and fatherless,
and having put the poor children supperless to bed,
she kneeled down and laid her case before the Almighty.
She must have passed the greater part of the night in prayer,
for when the messenger arrived at her door,
she heard the voice of the old woman inside talking very earnestly to some one,
as she thought.
Softly lifting the latch, she listened,
and very much astonished she was at what she heard.
To use her own words,
she said it seemed to her as if old Betty was holding
a conversation with a visible being,
and as if he was replying to her, for she was saying,
"`That she had worked for those children as long as she was able,
till sickness overtook her, and that He had sent that sickness;
that now she looked to Him to provide for them: the children were not hers,
but some He had sent to her to take care of.`"

Like the patriarch Jacob, she had remained all night in prayer, and when the day dawned,
the answer came.
No apparent miracle was wrought for her benefit,
only a poor old woman like herself stood at the door,
but as certainly sent direct by God as if He had
commanded an angel from heaven to fly to her aid.

When Sally opened the cottage-door,
she saw that poor old creature faint with hunger and cold, kneeling by the miserable bed,
where her two grandchildren lay huddled together for warmth.
She said nothing, but quickly emptied her basket, spreading the contents on the table.
There was abundance of food, enough to last many days, and better still,
a message from those good ladies to old Betty,
that they would care for her as long as she lived.

The preceding portions of this volume have furnished many illustrations
of the severity of the sufferings to which our early members were exposed,
because of their faithfulness to their religious principles.
It was not only their exposure to brutal treatment from the rough multitude,
which called for the sympathy and help of their friends,
but in many cases the victims who were imprisoned,
left their wives and families with little to support
them during the absence of their natural caretakers.
From very early times care was taken that these should not suffer;
and it has remained a regular part of the arrangements of the Society down to this day,
that the needs of the poorer members should be looked after,
and "`they relieved or assisted in such business as they are capable of.`"

Indeed,
the care of the suffering ones appears to have been one of the first motives
to the establishment of a system of discipline among Friends.
William Penn, in his preface to the [.book-title]#Journal of George Fox#, says:

This people increasing daily both in town and country,
an holy care fell upon some of the elders among them
for the benefit and service of the church.
And the first business in their view, after the example of the primitive saints,
was the exercise of charity; to supply the necessities of the poor,
and answer the like occasions.
Wherefore collections were early and liberally made
for that and divers other services in the church,
and entrusted with faithful men, fearing God, and of good report,
who were not weary in well doing, adding often of their own, in large proportions,
which they never brought to account, or desired should be known,
much less restored to them, that none might want,
nor any service be retarded or disappointed.

They were also very careful that every one that belonged to them
answered their profession in their behavior among men,
upon all occasions; that they lived peaceably, and were in all things good examples.
They found themselves engaged to record their sufferings and services;
and in case of marriage, which they could not perform in the usual methods of the nation,
but among themselves,
they took care that all things were clear between the parties and all others.
And it was then rare that any one entertained an inclination to a person on that account,
till he or she had communicated it secretly to some
very weighty and eminent Friends among them,
that they might have a sense of the matter;
looking to the counsel and unity of their brethren as of great moment to them.
But because the charge of the poor, the number of orphans, marriages,
sufferings and other matters multiplied,
and that it was good that the churches were in some way
and method of proceeding in such affairs among them,
to the end they might the better correspond upon occasion,
where a member of one meeting might have to do with one of another;
it pleased the Lord in his wisdom and goodness to open the understanding
of the first instrument of this dispensation of life,
about a good and orderly way of proceeding;
who felt an holy concern to visit the churches in person throughout this nation,
to begin and establish it among them.
And by his epistles, the like was done in other nations and provinces abroad,
which he also afterwards visited, and helped in that service.

Now the care, conduct and discipline, I have been speaking of,
and which are now practised among this people, is as followeth.

This godly elder, in every country where he travelled, exhorted them,
that some out of every meeting for worship, should meet together once in the month,
to confer about the wants and occasions of the church.
And as the case required,
so those Monthly Meetings were fewer or more in number in every respective county:
four or six meetings for worship, usually making one Monthly Meeting for business.
And accordingly the brethren met him from place to place, and began the said meetings,
viz: For the poor, orphans, orderly walking, integrity to their profession, marriages,
births, burials, sufferings, etc.
And that these Monthly Meetings should in each county, make up one Quarterly Meeting,
where the most zealous and eminent friends of the county should assemble to communicate,
advise and help one another, especially when any business seemed difficult,
or a Monthly Meeting was tender of determining a matter.

Also that these several Quarterly Meetings should
digest the reports of their Monthly Meetings,
and prepare one for each respective county against the Yearly Meeting,
in which all Quarterly Meetings resolve; which is held in London,
where the churches in this nation, and other nations and provinces,
meet by chosen members of their respective counties,
both mutually to communicate their church-affairs, and to advise, and be advised,
in any depending case, to edification; also,
to provide a requisite stock for the discharge of
general expenses for general services in the church,
not needful to be here particularized.

[.book-title]#The Journal of George Fox# shows how he was led to travel through England,
proclaiming the truths of the Gospel,
and calling upon his hearers to heed the discoveries
of the light of Christ on their consciences.
It was in the movings of the same Divine power which
had commissioned him to preach the way of salvation,
that he was led to establish meetings for discipline.
Under the date of 1666, he says:

I was moved of the Lord to recommend the setting
up five Monthly Meetings in the city of London,
besides the women`'s meetings and the Quarterly Meetings to take care of God`'s glory,
and to admonish and exhort such as walked disorderly or carelessly,
and not according to Truth.

From a document written in 1662, signed by Edward Burrough,
it appears that a similar meeting had been established in London some years before,
in which other Friends besides the ministers assembled to consult
about such things as did not properly belong to the ministry,
such as providing convenient meetinghouses, taking care of the poor,
visiting the sick and weak and impotent,
and finding employment for those who had lost their
situations for receiving the principles of Friends, etc.

After business meetings had been settled in London,
George Fox travelled through many parts of England,
establishing Monthly Meetings in the various counties.
And he sent papers to some places which he did not personally visit,
exhorting Friends to settle the Monthly Meetings in the Lord`'s power in those places.
So that those meetings soon came to be generally established among Friends.

Of the fruits of this righteous concern, George Fox says:

Since these meeting have been settled,
and all the faithful have met together in the power of God,
which is the authority of them, to perform service to the Lord therein,
many mouths have been opened in thanksgivings and praise,
and many have blessed the Lord God that ever He sent me forth in this service.

But although so much success attended these efforts
to introduce a settled order in the church,
yet there were a number of persons who objected to it,
arguing that every person ought to be left to the dictates of the light of Christ,
and that this movement was the substitution of a form for the liberty of the Gospel.
The most of those ministers, who had been instrumental in building up the new Society,
recognized the Divine authority which George Fox claimed as the foundation
of his scheme--but the Journals of some Friends who were contemporary,
show that there was enough dissent to cause serious concern
to the burden bearers in the church at that time.

Charles Marshall says the opposition was carried on under
a specious pretence of standing up against imposition,
calling the meetings forms and an idol;
when indeed it was the same Divine power and wisdom which gathered us to be a people,
that caused the setting and settling good order and discipline amongst us;
to take care of the poor, widows and fatherless,
and for due proceeding in that great concern of marriage,
and other things relating to the service of Truth and welfare of the church.

John Banks was one of our early Friends who was concerned to labor with
those members who had been entangled in the spirit of separation that
had arisen in some on the occasion of the establishment of the discipline.
He says:
"`The Lord laid a necessity upon me to go forth with
a testimony against that spirit of separation.`"
Before he went forth he was moved of the Lord to give forth a paper which
was sent to those places where this spirit had gotten the most entrance.
In this document he asserts that it was the work of the devil,
by his evil power and dark spirit and wicked instruments actuated thereby,
to divide and scatter us asunder.
"`This subtle spirit hath induced too many to slight
men`'s and women`'s meetings +++[+++Meetings for Discipline],
and the power of God by which they were set up.`"
"`The Lord in his love and by his light hath clearly given me to see its way,
that it leads to the chambers of death, and He hath delivered my soul from its snare,
who once was in danger to be taken by it,
when men`'s and women`'s meetings were first set up.`"

In a memorial respecting William Edmundson, issued by Friends of Leinster Province,
Ireland, it is said:
"`That when it pleased the Lord to concern his faithful servant George Fox,
to set up men`'s and women`'s meetings, our dear friend, William Edmundson,
rejoiced thereat, and gladly closed therewith.
He was a diligent attender of such meetings,
and was greatly concerned that none might be admitted members
thereof but such as were of clean and orderly conversations,
walking as examples to the flock.`"

John Gough, in his history of the people called Quakers,
relates the circumstances attending a separation in Westmoreland about 1675-6,
of which he says, the original cause was the establishing of the discipline.
The separatists urged against meetings for discipline,
that every man having received a measure of the Spirit of God,
ought to follow that as his leader, without regarding the prescriptions of men;
that meetings of discipline were therefore needless, etc.

In support of the discipline it was advanced that God,
who is a God of order and not of confusion,
doth not by his spirit lead any into confusion and disorder; that in society,
meetings for discipline are necessary and useful for looking after the poor,
sick and aged members, the widows and orphans;
that inasmuch as disorderly persons arise in all societies,
there should be power to establish such regulations as may prevent disorder and scandal;
that a similar care was exercised in the primitive church,
as is said in the Acts that Paul and Timothy, "`as they went through the cities,
delivered them the decrees for to keep,
that were ordained of the apostles and elders which were at Jerusalem.`"

The leaders in the opposition were John Story and John Wilkinson,
two north country Friends, both in the station of minister.
To prevent an open breach,
the Quarterly Meeting of Westmoreland referred the case to the judgment
of some of the most eminent Friends of the neighboring counties;
they came to the judgment that Story and Wilkinson and their
party had dissolved the bonds of unity with the Society,
by their public opposition to the good order established among them;
and issued a testimony against them and their spirit,
in the latter part of the year 1675.

The following year,
another effort was made to satisfy these opposers by a meeting held in Yorkshire,
which was attended by many Friends from other parts of the nation.
After four days, spent in a patient and full inquiry into the cause of the trouble,
this meeting confirmed the judgment of the former one,
which so disturbed the opponents of the discipline,
that they left the Society and set up separate meetings.
This continued but a few years.
The more sincere of its members came in time to perceive the causelessness
of their separation and reunited themselves to the body of the Society.
The rest soon fell to pieces and dwindled away.

It was probably in connection with one of these meetings,
that the following incident occurred:

John Steel, who, by relation, was a plain countryman,
of not much note or appearance in the Society, was following his plough,
when he found a constraint on his mind to leave home but knew not whither he was to go,
nor what service was for him to do;
but was commanded to travel toward a distant part of the nation (England),
which when he had so done, he heard that, at a particular place,
a meeting or conference was appointed to be held
between Friends and John Wilkinson and John Story,
on account of their separation.
Thither he found freedom to go, where William Penn,
Robert Barclay and other eminent Friends were met on the occasion.
In a little time John Steel had the following testimony to deliver:

"`The Lord our God, with whom the treasures of wisdom and knowledge are hid,
in an acceptable time, in this our age and generation,
had given his gifts unto his children for the gathering of people out of the world.
If any be unfaithful in the gift, He that gave it will take it away,
then nothing remains but the words which were learned
of the Lord while they had the gift;
and with these words they will war against the Truth
and against them who have the Gospel order;
for they are now bringing up new things, which was not in the beginning;
having the smooth words which man cannot see, but as their fruits make them manifest,
and an inward eye is opened.
The doctrine of this spirit is so smooth that many cannot see a hole in it;
but the nature of it is to divide Friends asunder like stray sheep:
but they go about to support this spirit,
although they have been engaged in many services for the Lord,
and He honored them and gave victory and clothed them with beautiful garments: yet,
if they go about to support this wrong spirit,
their garments shall be torn as the coat of a sheep amongst briars and thorns;
for if any who have received the gift, be not faithful unto it,
the Lord shall do as He hath done confound them out of the mouths of babes and sucklings;
for neither will nor wealth shall bear rule among the people of God;
but the power of the Lord must go over all, and in that must the rule be.

"`In the months that are past, and the years that are gone,
it could not be said '`we`' and '`they`'; but one God,
one people and one spirit was known;
but in process of time an evil spirit and power is entered as leaven whereby
it is said '`we`' and '`they`'. But the power of the Lord is to pass over,
and by it that is to be destroyed; and one power, one people and spirit is to be known,
if ever God`'s salvation be known;
by that one power of the one God all are made sensible members of that body,
of which Jesus Christ is head.
But in process of time, through the subtility of the devil,
some of these members have been benumbed and lost the sense of feeling;
and now several of the sensible members of which Christ is head,
have endeavored time after time, together with the help of the Head,
to seek the recovery of the benumbed members, but no recovery could be made.
What shall be done to these members?
Shall they be cut off?
Nay, the counsel of God is not so in my heart;
but let them be as near the body as may be; that if it may be,
they may receive again virtue from the Head, and come to the sense of feeling again.
They were seeing members, and did work for God when they did see; but being made numb,
they were also blind; and it is unto them as a continual night,
and being in the blindness they would be working for God,
being used to go abroad when they were sensible,
so they would be going abroad when they are blind.
But what shall be done to these members?
Let them be bound; but if it please God,
while they have a being in these tabernacles let them be loosed--if not,
let them be bound forever!
This is the judgment of God upon you, John Story and John Wilkinson.
If it be not just and equal, reject it if you can.`"
And to this they were silent.

The foregoing testimony came with such powerful weight and authority that, it is said,
William Penn afterwards remarked to Robert Barclay to this purpose:
"`This is neither the wisdom of the north, nor the eloquence of the south,
but the power of God through a poor ploughman.`"

The Journal of Charles Marshall, of Bristol,
gives a vivid picture of the exercise of spirit caused by
the opposition to a settled order and discipline among Friends.
He says:

Great was the travail of our ancient and honorable Friend, George Fox,
in this weighty concern, in the first breaking forth of Truth in this age.
Several other brethren were also deeply concerned
in settling meetings in the said good order,
and we found the Lord with us in our work and service.
The power of the Lord worked thus to settle us in a good order,
that we might appear to the world to be guided by his wisdom;
being found in the form of godliness,
as it arose from the power of it inwardly in the soul.
But the enemy that would have had us a people in confusion and a Babel instead of a Zion,
wrought in the earthly sensual wisdom of some loose-spirited
men who had lost their sense of the leadings of the Almighty,
and brought them into a false imagination that we
were going from the inward guidance of God`'s spirit,
to set up forms like other professions, thereby leaving the light of Jesus Christ,
which was to be every man`'s guide in faith and practice.
Hereupon they endeavored, with all their strength,
to lay waste the meetings before mentioned;
crying that imposition on conscience was the cause of their separation,
when in truth it was an opposition by the power of darkness working in themselves,
whereby they were quickly benighted; and many ran into their errors.

This spirit brought great affliction and travail upon some in the beginning of its workings.
Great were the disorders it made in Bristol and Wiltshire;
because of which the Lord concerned me, with other faithful brethren,
in his name and power, to make war against it, in great travail,
tears and distress of spirit, for several years together,
running in between the living and the dead for several years.
I can say, the Lord God that guided me to travel in his name and dread through the land,
was with me in this day of deep exercise; and I have cause, in great bowings of spirit,
to magnify his glorious name, who preserved me faithful over all discouragement.
My bow He made strong, and my quiver He daily replenished with arrows;
my soul He caused to be, as it were, baptized for the dead,
as one eating the bread of adversity and drinking the water of affliction,
sparing neither strength nor substance.
To a great height of opposition did this spirit of division rise in divers instruments.
The clouds were so thick and the mist of darkness so great,
that many poor sheep were in danger of becoming a prey to the wolf and devourer.
The honesthearted were grieved and bowed down,
and the rich in imagination exalted in rage;
so that this separation came quickly to be spread in the sight of the world,
and in several places they shut us out of our meetinghouses,
exposing us in the streets to the view of others.

I very well remember the day that I received instruction of the Lord in a vision,
concerning that people; wherein their work, end and downfall, was shown to me;
so that it became a concern on my soul to invite faithful Friends
of Wiltshire to have a meeting on purpose to wait upon the Lord,
in a deep exercise of soul,
and to cry to Him to appear for his name`'s sake and his people.
Friends did readily answer my desire, and we agreed upon such a meeting;
and the first was in the place where they designed to have
laid waste the Quarterly Meeting of that county.
When we were waiting upon the Lord,
this was the cry of my soul amongst Friends and brethren: Oh,
Lord! what wilt thou do for thy great name, that is dishonored?
For thy heritage, whom the enemy and destroyer would now scatter,
devour thy lambs and spoil and trample down thy vineyard?
Thus we cried in bowedness of spirit before the Lord,
who heard from heaven his holy habitation;
and his power broke forth in a wonderful manner, tendering his people before Him;
and his presence and heavenly wisdom comforted and confirmed his servants,
and Friends were opened to speak well of the name of the
Lord and the greatness of his power and appearance.

The watchful care of Friends over their members who were in distress,
extended to distant parts,
as shown by the efforts to obtain the release of
those who were held in captivity in the Barbary States.

The Barbary States, viz: Morocco, Algiers, Tunis, Tripoli and Barca,
though at one time the seat of learning and the arts, were, for many centuries later,
the abode of unprincipled barbarians, who, by piracy and pillage,
became the destroyers of commerce and the terror of navigators.
Their captives,
whether taken in war or from ships engaged in the peaceful pursuits of commerce,
were speedily sold into slavery of the most cruel and degrading character.
So early as the fifteenth century, it is said,
they numbered their Christian slaves by thousands, and in the years 1509,
1535 and 1541 many hundreds of their fellow-countrymen were liberated
by men-of-war sent out by the British Government for that purpose.

By these formidable expeditions of Great Britain, not only were the slaves liberated,
but treaties were made in which the people of Barbary pledged themselves
to refrain from such treatment of captives for the future.

With an insincerity which, centuries before,
had made "`Punic faith`" a synonym of treachery,
no sooner were the fleets gone and danger from them passed,
than the same illicit traffic was resumed and the same system of cruelty enacted.
So grievous to the English people had these outrages become, that Oliver Cromwell,
on assuming the protectorate, dispatched a fleet of thirty ships, under Admiral Blake,
who, in his turn, liberated all the English, and some Dutch captives,
the first of whom were numerous.

But none of these measures were permanently effective.
Emboldened by success, and encouraged by their skill as navigators,
they penetrated distant seas and brought their captives, it is said,
in some few instances, even from the English channel itself.

Towards the close of the seventeenth century,
though fewer in numbers and less skillfully organized,
these pirates still spread terror over the sea,
and did much towards increasing the perils of that current of travel
which was now setting so strongly in the direction of the new world.

Among other British subjects, who at this time were captured by these pirates,
were several members of the religious Society of Friends, who,
either in their religious services or in their secular pursuits,
were compelled to visit distant ports, and thus easily became their prey.
There is, indeed, little or no positive evidence that,
of those taken prisoners by the Turks,
any of the Friends were engaged in other than their ordinary business.
They are never referred to as Friends travelling in the ministry,
in the epistles hereafter quoted,
and this inference appears confirmed by the statement in the epistle of 1682,
that "`one of the prisoners at Algiers has a public testimony among them.`"
But they were earnest, devout, consistent Friends,
and their sad condition deeply affected their fellow-members,
who seem to have left nothing undone that could be done to effect their release.

Among those who were taken captive by corsairs,
and whose history has become well known to the Society, was Thomas Lurting,
then mate of a ship whose master was also a Friend, and who,
having been captured by the Algerines, so triumphed over their captors that, without,
on their part, shedding blood, they recaptured the vessel, and,
with a magnanimity unprecedented,
landed the Turks (as they were called) on their own shores, and then,
with continued safety, sailed away to their own homes.

Sewell, in his [.book-title]#History of the People called Quakers#,
states that several years after this occurrence:

George Fox wrote a book to the grand sultan, and the king at Algiers,
wherein he laid before them their indecent behavior and unreasonable dealings,
showing them from their Alcoran, that Mahomet had given them other directions.
To this he added a succinct narrative of what hath been related here (of Thomas
Lurting)...and how the Turks were set at liberty without being made slaves;
by which the Mahometans might see what kind of Christians the Quakers were, viz:
such as showed effectually that they loved their enemies,
according to the doctrine of their supreme lawgiver, Christ.

In the epistle of the Yearly Meeting begun and held in London, the fifth of Fourth Month,
1682 (the fifth epistle issued), appears the following:

Finally, dear Friends,
we have great cause to magnify the name of the
Lord our God for this blessed opportunity&hellip; being
greatly comforted and refreshed in the many good accounts and lively testimonies given
by Friends&hellip; As also of a new meeting even among the captives in Algiers,
where one Friend has a public testimony among them.
Again, in that of 1683, "`Here were some tender Friends from Dantzick, Frizeland,
Holland, Norway, Scotland and some from America.
And we understand that Friends keep up their meetings in Algiers and Turkey.`"

1684.--An account being given by a meeting here ordered to inspect
the accounts of Friends that are captives at Algiers,
etc.,
intimating that what was charitably contributed formerly
towards their redemption and left for that service,
is in a great measure expended for the redemption of many,
and the rest thereof is well nigh engaged for the redemption of several Friends more,
that have remained captives; some whereof have indeed been under extreme hardships,
as violent beating and other cruelties by their patroones.
These things tenderly considered, a collection for their redemption was proposed,
and unanimously agreed upon by this meeting,
that the same should be and hereby is recommended to the Quarterly Meetings
of Friends in their respective counties throughout England and Wales,
and that the same be and hereby is recommended to Friends in Ireland,
Scotland and Jamaica,
to afford their Christian and friendly assistance in contributing to the same service.

Epistle 1689.--Our Friends who are captives at Mequinez do remain as before;
only some are come down to Sally,
and have liberty to go about the town under security for their true imprisonment.
Great endeavors have been used for their redemption.

1690.--And as concerning our Friends at Mequinez and Sally,
endeavors have not been wanting to obtain their redemption;
but as yet it cannot be effected.
We hear from them that they are well,
and desire their love might be communicated to Friends in their native land.

1691.--Divers good epistles were read in this meeting from foreign parts--Ireland,
Scotland,&hellip;and two from Friends, captives at Mequinez, in Barbary,
under the emperor of Morocco.
There yet remain nine English Friends captives at Mequinez, and three at Murbray;
who received the Truth there (it being three or four days`' journey distant),
who correspond with each other by letters.
One Friend (to wit, Joseph Wasey), being lately redeemed and newly come over,
gave a large account to this meeting of their miserable hard usage in captivity;
having no lodging but under arches, in deep places on the cold ground, winter and summer;
only water for drink, and no bread allowed them by the king but of old rotten,
stinking barley; and no clothes but a frock once in two years; and forced to hard labor,
except three days in the year,
and more especially on the Sixth-day of the week (which is their day of
worship) they are compelled to carry heavy burdens on their heads,
running from sun-rising to sun-setting,
with brutish black boys following them with whips and stripes at their pleasure.

Many of the other captives perish and die through their
extreme hardships and want of food to sustain them;
as in all likelihood Friends there had,
if Friends and their relatives here had not sent them some relief;
seven pence a month formerly allowed them by the king being now taken from them.
Their sufferings are lamentable: yet the Lord`'s power has wonderfully preserved them,
and greatly restrained the fury and cruelty of that emperor towards poor Friends there;
in whose behalf the said Joseph Wasey did, by an interpreter, speak to the said emperor,
giving him an account of their innocent conversation and religion--which he heard
with moderation--though he often kills men in cold blood for his pleasure.
Joseph Wasey also signified that Friends`' daytime being taken up with hard servitude,
they are necessitated to keep their meetings in the night seasons to wait on God.
The aforesaid captive Friends were very thankful for the relief sent from hence,
which was very refreshing to them.

1692.--Several letters from Friends who still remain in their long captivity in Mequinez,
to divers Friends here, were read; intimating the state of things with them,
and that they received our epistles from our last Yearly Meeting;
and acknowledged Friends`' love and diligence here in laboring for their ransom.
And that since the last Yearly Meeting the Lord hath delivered three of them, by death,
out of their great misery and servitude, who ended their days in great content and peace.
Their names are John Bound, Richard Nevet and Thomas Harrall.
The distressed case of the remainder of them (as last year signified),
is still before Friends,
and divers are engaged in the love of God to use their endeavors for their ransom.

1693.--The Friends yet remaining captives at Mequinez are still held under
great severities and hardships by that cruel tyrannical task-master,
who is yet suffered cruelly to punish, wound and kill poor captives, at his pleasure.
And all possible care of their redemption and relief is by this meeting still recommended
to the Meeting for Sufferings to continue their endeavors for the effecting thereof.

1697.--At Barbary there remain several captives,
most of whom are such that received the Truth in the time of their captivity;
the ransom of whom could not hitherto be obtained,
although great endeavors have been used for it;
but further endeavors are intended to be used as opportunity presents.

1698.--We&hellip; understand that divers of our Friends who were captives at Mequinez,
and suffered great hardships there, are dead.
And there yet remain five, for whose ransom great endeavors have been used,
but it is not yet effected.

1699.--Earnest endeavors have again lately been used for the liberty of our Friends,
captives in Barbary, though not as yet obtained:
and there being at this time negotiations on foot
for the redemption of all the English there;
and though the persons in Barbary employed therein by Friends,
do wait sometime to see the effect of that,
yet we shall continue our farther endeavors for their discharge.
And in the meantime have and do take care to send them supplies for food;
they having little allowance in that country of anything
to support their bodies under the great severities of labor,
and undeserved stripes that captives often endure.
Also farther direction by this meeting is given in their behalf.

1700.--Friends`' care is also continued for the redemption
of our Friends that are captives in Barbary;
and (as was hoped),
the king has now agreed for the ransom of all the English captives there;
and agents are arrived from thence in order to receive the said ransom.
And although now as heretofore,
Friends have acquainted the Government that they
intend to redeem our Friends at our own charge,
nevertheless Friends are so far willing to encourage
a public collection for the said service that,
when the collectors shall come with the briefs to Friends`' houses,
we hope Friends will be inclined to extend their charity, in common with their neighbors,
toward the redemption of the other English captives.

1701.--The Friends that are in captivity in Barbary are duly taken care of by Friends.
And their ransom having been agreed for some time, it is hoped will be shortly effected.
One young man has been convinced there lately.

1702.--And whereas we formerly gave you some account of the hopes Friends had,
and endeavors used, for the redemption of Friends, captives in Barbary,
we now let you know that John King, Richard Robertson, Thomas Walkedon, Robert Finley,
James Burgoine,
Joseph Bigland (being all of our Friends who remained alive in that long and sore captivity),
have been this year redeemed;
whose ransom hath cost Friends upwards of four hundred and eighty pounds,
including one George Palmer, a Friend`'s son, of Pennsylvania, recommended from thence;
towards whose ransom they also did contribute.
Divers of which redeemed Friends have tenderly and gratefully
acknowledged Friends`' love and care of them.

Thus, after a care of more than twenty years,
the last of these poor people were restored to their homes,
and the tender concern of the Yearly Meeting was rewarded.

The case of Lucy Chopping is an interesting illustration of the manner
in which the Lord leads his devoted servants into services which,
however humble in themselves, if performed at his requiring, are accepted with Him.
She was born in the early part of the seventeenth century,
and became convinced of the Truth as held by the Society of Friends.
During the persecution of Friends,
Lucy Chopping found it her concern to visit them in prison,
and accordingly she went from jail to jail,
doing for them such service in mending and making their clothes, as they needed;
and many parents being shut up far from their homes,
she would also go and visit their families and children.
She spent many years in this line of service,
which was very acceptable to those who could not
obtain liberty to visit their families themselves.
Great was her labor of love, in that she did it freely, although she travelled on foot;
besides which she frequently attended the Yearly Meeting when it was established.

She was married to John Chopping, of Stebbing,
probably after reaching the meridian of life, with whom she lived but two years,
and survived him about twenty-eight years.
Through obedience and faithfulness to her Lord and Master, she grew in the Truth,
and was a mother in Israel, of a good understanding,
a visitor of those who were afflicted in body or mind,
to whom she often administered a word of comfort or advice.
Young convinced Friends, she exhorted earnestly to be faithful;
and when any grew careless,
her tender solicitude for their recovery led her to labor with them,
and often to so good effect, as to reach the witness of Truth in their hearts.
About two weeks before her death, she walked six miles to a meeting,
in order to visit a woman, who being overcome with the cares of the world,
neglected meetings; whom she warned of her danger,
and who became more careful afterwards in performing her duty.

The next day she was taken ill, and expressed herself thus:

I cannot say that what I feared, is come upon me; but that which I have long desired;
for I am very ill, and do think it will be my end.
But it will be well with me; I shall go to my mansion which is prepared for me,
and all the faithful followers of the Lamb; and I have nothing to do but to die.
The Lord has been with me even as with Jacob, and +++[+++when]
I knew it not; and blessed be his name,
He has been with me and made known the way of life and salvation to me,
and preserved me through many hard exercises, and deep afflictions,
and sorrowful travails in spirit.
He has been with me through my pilgrimage, and kept me safe through many long journeys,
in which I have walked many hundred miles, to serve my friends in the Truth,
and for the Truth`'s sake, and mostly alone; and the Lord has preserved me,
so that none were suffered to do me any harm;
for which I have often been humbly thankful; and now I feel peace,
and shall in a little time rest with Him in everlasting joy and peace.
