== Chapter XV. Slavery

The evil system of slavery was early introduced into the American colonies; and as,
at that time,
the public attention had not been awakened to its inherent injustice and iniquity,
and as the need for labor to bring the land into cultivation was much felt,
it spread rapidly.
One of the first legislative enactments opposed to
the system was passed by the legislature of Massachusetts,
in 1641, and similar acts were subsequently passed by other of the New England colonies.
While these enactments no doubt had an effect in discouraging the system,
yet it long continued in existence,
and it was only after much exercise and labor that a conviction that freedom
was the inalienable right of man until forfeited by his own wrongdoing,
so permeated the minds of the community as to erect
a substantial barrier to the spread of slavery.
The earliest and most interesting of the protests against the system
was that which originated with a colony of German Friends,
settled at Germantown, near Philadelphia, who formed a branch of Dublin Monthly Meeting,
and this document is still preserved among the papers of Philadelphia Yearly Meeting,
and is as follows:

=== Germantown Friends`' Protest Against Slavery, 1688

This is to the Monthly Meeting held at Richard Worrell`'s.

These are the reasons why we are against the traffic of men-body, as followeth.
Is there any that would be done or handled at this manner?
viz., to be sold or made a slave for all the time of his life?
How fearful and fainthearted are many on sea,
when they see a strange vessel,--being afraid it should be a Turk,
and they should be taken, and sold for slaves into Turkey.
Now, is this doing any better than the Turks do?
Yea, rather it is worse for them, which say they are Christians;
for we hear that the most part of such negroes are
brought hither against their will and consent,
and that many of them are stolen.
Now, though they are black,
we can not conceive there is more liberty to have them slaves,
as it is to have other white ones.
There is a saying that we should do unto all men as we would have them do to ourselves;
making no difference of what generation, descent or colour they are.
And those who steal or rob men, and those who buy or purchase them,
are they not all alike?
Here is liberty of conscience which is right and reasonable;
here ought to be likewise liberty of the body, except of evil-doers,
which is another case.
But to bring men hither, or to rob and sell them against their will, we stand against.
In Europe there are many oppressed for conscience sake;
and here there are those oppressed which are of a black colour.
And we who know that men must not commit adultery,--some do commit adultery, in others,
separating wives from their husbands and giving them to others;
and some sell the children of these poor creatures to other men.

Ah, do consider well this thing, you who do it,
if you would desire to be treated in this manner?
and if it is done according to Christianity?
You surpass Holland and Germany in this thing.
This makes an ill report in all those countries of Europe, where they hear of,
that the Quakers do here handle men as they handle there the cattle.
And for that reason some have no mind or inclination to come hither.
And who shall maintain this your cause, or plead for it.
Truly we can not do so, except you shall inform us better hereof, viz.,
that Christians have liberty to practise these things.
Pray, what thing in the world can be done worse towards us,
than if men should rob or steal us away, and sell us for slaves to strange countries;
separating husbands from their wives and children.
Seeing that this is not doing to others what we would want done to ourselves,
we therefore contradict and are against this traffic of men-body.
And we who profess that it is not lawful to steal, must, likewise,
avoid to purchase such things as are stolen,
but rather help to stop this robbing and stealing if possible.
And such men ought to be delivered out of the hands of the robbers,
and set free as well as in Europe.
Then is Pennsylvania to have a good report,
instead it hath now a bad one for this sake in other countries.
Especially whereas the Europeans are desirous to know in what manner the Quakers do
rule in their province;--and most of them do look upon us with an envious eye.
But if this is done well, what shall we say is done evil?

If once these slaves (which they say are so wicked and stubborn
men) should join themselves,--fight for their freedom,--and handle
their masters and mistresses as they did handle them before;
will these masters and mistresses take the sword
at hand and war against these poor slaves,
like, we are able to believe, some will not refuse to do;
or have these negroes not as much right to fight for their freedom,
as you have to keep them slaves?

Now consider well this thing, if it is good or bad?
And in case you find it to be good to handle these blacks at that manner,
we desire and require you hereby lovingly, that you may inform us herein,
which at this time never was done, viz., that Christians have such a liberty to do so.
To the end we shall be satisfied in this point,
and satisfy likewise our good friends and acquaintances in our native country,
to whom it is a terror, or fearful thing, that men should be handled so in Pennsylvania.

This is from our meeting at Germantown, held the 18 of the 2 month, 1688,
to be delivered to the Monthly Meeting at Richard Worrell`'s.

Garret henderich Derick up de graeff Francis daniell Pastorius Abraham up Den graef

At our Monthly Meeting at Dublin, the 30--2 mo., 1688, we have inspected the matter,
above mentioned, and considered of it,
we find it so weighty that we think it not expedient for us to meddle with it here,
but do rather commit it to the consideration of the Quarterly Meeting;
the tenor of it being nearly related to the Truth.
On behalf of the Monthly Meeting,

Signed,

P+++.+++ Jo. Hart

This, above mentioned, was read in our Quarterly Meeting at Philadelphia,
the 4 of the 4th mo.
`'88, and was from thence recommended to the Yearly Meeting, and the above said Derick,
and the other two mentioned therein, to present the same to the above said meeting,
it being a thing of too great a weight for this meeting to determine.

Signed by order of the meeting,

Anthony Morris

=== Yearly Meeting Minute on the Above Protest

At a Yearly Meeting held at Burlington the 5th day of the 7th month, 1688.

A paper being here presented by some German Friends concerning
the lawfulness and unlawfulness of buying and keeping negroes,
it was adjudged not to be so proper for this Meeting
to give a positive judgment in the case,
it having so general a relation to many other parts,
and therefore at present they forbear it.

Although this strong appeal failed to elicit immediate action from the Yearly Meeting,
yet there is reason to believe it was productive of good fruits;
and from this time onward,
testimonies against slavery continued to be borne by meetings and individuals.
One of the most effective of these laborers was John Woolman,
who labored in public and in private for the extinction of slavery,
but was favored to keep his zeal within the limitations of the spirit of Christ,
and thus to avoid much of the opposition which an intemperate zeal might have awakened.
He was a minister among Friends,
and for about twenty years from 1746 he travelled much in the Middle and Southern States.
In these journeys he bore a testimony against slavery, both by words and by practice.
In speaking of one of these journeys, he says:

Two things were remarkable to me in this journey--first in regard to my entertainment;
when I eat,
drank and lodged free cost with people who lived
in ease on the hard labor of their slaves,
I felt uneasy; and as my mind was inward to the Lord, I found, from place to place,
this uneasiness return upon me at times, through the whole visit.
Where the masters bore a good share of the burden, and lived frugally,
so that their servants were well provided for, and their labor moderate,
I felt more easy;
but where they lived in a costly way and laid heavy burdens on their slaves,
my exercise was often great,
and I frequently had conversation with them in private concerning it.
Secondly,
the trade of importing slaves from their native country
being much encouraged amongst them,
and the white people and their children so generally living without much labor,
were frequently the subject of my serious thoughts,
and I saw in these Southern provinces so many vices and corruptions,
increased by this trade and this way of life,
that it appeared to me as a dark gloominess hanging over the land;
and though now many willingly run into it,
yet in future the consequences will be grievous to posterity.
I express it as it hath appeared to me, not at once or twice,
but as a matter fixed on my mind.

The men of this generation who have seen the bitter calamities
brought on our country by the late civil war,
which was one of the fruits of the system of slavery, will be ready to believe,
that when John Woolman predicted that "`the consequences would be grievous to posterity,`"
he was a true prophet--one whose eyes had been anointed to see future events.

As the convictions of our members as to the sinfulness of slavery strengthened,
the advices and conclusions of the Yearly Meeting became more and more decided;
and in the year 1758, the Yearly Meeting was prepared to direct that,
if any one should vindicate slavery, or be concerned in importing,
selling or purchasing slaves, they should be considered no longer in unity,
and should be prevented from sitting in meetings for discipline,
and from subscribing to the funds of the Society.
After the Yearly Meeting, which took place in the Ninth Month, was over,
a friend of Benjamin Lay`'s visited him,
and told him of the conclusion Friends had came to.
On hearing it,
the heart of the weak and feeble old man was filled with pious gratitude and joy.
He rose from his chair, and exclaimed:

"`Thanksgiving and praise be rendered unto the Lord God!`"
He added, after a pause: "`I can now die in peace.`"

A number of Friends still held slaves,
and the Yearly Meeting encouraged those who felt concerned on this account,
to labor with such.
One who was engaged in this service says:

With other exercised brethren,
I became engaged to plead for liberty to the black
people who were held in the bonds of slavery,
amongst our fellow-members, and from house to house we visited those who held such,
particularly in the parts near us.
This business, at that time, went hard with some,
who thought it would cause uneasiness between them and their black servants,
so would scarcely permit us to perform the visit.
I saw it was the Lord`'s work,
and that in performing it we had need be as "`wise as serpents, and harmless as doves.`"
Truth opened our way to proceed much in this manner, viz:
To sit down in silence with the whole family;
not to let our communications give the blacks any
knowledge of our business with those who held them,
but when the other parts of a family withdrew, we pleaded with the master and mistress;
the Truth favoring us to do it in a way that gave general satisfaction.
I thought I never felt a greater reward than in pleading the cause of those poor,
injured, captive people.

This subject continued to claim the attention of Philadelphia Yearly Meeting until reports
were made from the subordinate meetings that they were all clear from this evil.
Having washed its own hands,
the Society was ready to appear before the world as advocates of liberty,
and it has now for a long time been known as an uncompromising enemy of slavery.
The strong language used in a minute of the Yearly Meeting in 1798,
shows the earnestness of the Friends of that day.
The minute speaks of "`The enormous iniquity of enslaving
and trading in the persons of men,
which crying abomination,
renewedly impressing the minds of many Friends with very painful sensations,
under the awful prospect of Divine judgments manifest in the earth,
it is desired we may individually labor for qualification to offer up effectual,
fervent prayers for the removal of this unspeakable wickedness from our land.`"

The description of slavery and its attendant evils given by that warm-hearted minister,
Jacob Lindley, of Chester County, Pa., is equally earnest:

When I view the dreadful scenes of barbarity attendant on the African slave trade,
and its train of concurrent circumstances,
my soul is almost overwhelmed with discouragement.
Judgment is the Lord`'s, and He will surely repay.
Have the Indians burned houses, murdered men, women and children, betrayed their friends,
carried away into captivity and bondage old and young, male and female,
and cruelly burned and tortured others, lurked privily for prey,
shot down men at their ploughs and travellers on the road?
Yea, they have, until the rehearsal of many of their horrid scenes of barbarity,
has agitated, shocked, and almost convulsed every nerve.
But what shall I say?
How are my feelings wounded on being constrained to compare these reproaches to humanity,
with the conduct of civilized, professing Christian nations!
In which I lament, our own government, in most respects superlatively excellent,
takes a share.
Vessels fitted out, commanded by men with hearts callous to the feelings of humanity,
and deaf to her cries, repair to the African coast, stir up a war, burn towns, kill,
catch and carry captive indiscriminately these poor,
and to them unoffending people--bring them to distant
and different cities and towns--ringing with +++[+++calls]
to worship, sounding with hymns and psalms from stately temples,
where they offer their devotion to the Universal Parent,
who hath revealed his will in the language: "`Do justly, love mercy,
and walk humbly with thy God,`" professing to believe in the Divine Lawgiver,
whose statute is: "`Whatsoever ye would that men should do unto you,
do ye even so unto them.`"
Instead of +++[+++doing this, these negroes]
are sold +++[+++by them]
like beasts at market; separated husband from wife, children from parents,
without regard to the tenderest ties of natural affection;
often put under unfeeling whippers, and cruel task-masters,
where they are frequently starved or whipped to death;
and if they run away and are caught, they have been hung without trial or jury.
Some who had +++[+++taken]
their liberty have been hunted with horses and dogs, and shot down.
While such enormities are in the land, and winked at by the rulers,
shall we not lay our mouths in the dust, with this language impressed on our minds:
"`O Lord! just and true, and righteous are thy judgments.`"
I cannot omit remarking the joy we feel,
at the escape of a captive white from among the Indians; yet,
what a stir when a negro attempts his liberty!
Advertisements printed, and rewards offered to take him alive or dead!

Henry Hull mentions in his Journal having a meeting at Crooked Run in Virginia, in 1799.
"`At this meeting,`" he

says:

I was led to expose the iniquity of the slave trade,
and the practice of holding the African race in bondage.
This was much to the relief of my own mind,
which was often deeply oppressed with grief at seeing
the sufferings endured by the poor slaves.
Their allowance was one peck of corn for a week,
and this they were sometimes necessitated to pound in the night,
when they should be asleep to refresh them for the next day`'s labor.
To this I have often been a witness,
when the noise of the pestle and mortar has aroused me;
and soon after I have been startled by the voice of the driver
and the snapping of his whip urging them to the toils of the day,
even before the light had fully appeared.
In addition to this, they had to endure the broiling heat of the sun, bareheaded,
both males and females; the latter with only one garment to cover them,
and the cruel drivers following them with a large
wagon whip in order to hasten their speed,
using it freely upon those who fell behind, when hoeing the corn or tobacco.

Similar cruelties I have seen exercised on the house slaves,
upon whom the lash was often freely laid,
while they were subject to the kicks and cuffs of the children of the family.
At one time, having laid my horsewhip on a table in the bar-room of a tavern,
I was suddenly raised from my seat by seeing the tavern
keeper using my whip upon the back of his negro boy.
I stepped to him as quickly as I could and got it from him,
assuring him it was not accustomed to such business,
and he should have known better than to take it for that purpose.
At another time my eye caught the sight of a poor negro`'s back,
who was rowing us over a ferry (his shirt being a mere bunch of rags),
and it appeared like a piece of raw flesh, from the severe flogging he had received.
It was a most pitiful, sickening sight, and affected me very much;
the more so as he was toiling for our accommodation, for which, however, we paid him,
in addition to what was demanded by his oppressor--a practice, I believe,
common with Friends, for a colored man who attended at another ferry,
told us he was always glad to see the Quakers come, for then he had something given him.

It was also our practice to pay those who took care of our horses, not always with money,
but sometimes with food, for which they appeared thankful.
But after all, I could do little for them.
I had to mourn for them and their oppressors also,
whose situation appeared far from a desirable one.
In many places they seemed to be under great fear,
being careful to secure their lodging-rooms with locks and
bolts and to have their weapons of defense at hand,
ready to be seized at the slightest alarm.
The influence of the parents`' example in exercising an
arbitrary and cruel power over the inmates of the house,
produced an evil effect on the children, whose countenances and conduct,
marked with rage and pride, presented a very different appearance from what they would,
had they been taught to view and to treat the colored people
as the workmanship of the same Almighty Hand as themselves
and equally the objects of the Redeemer`'s mercy and care,
instead of being made to consider them as little
or no better than the beasts of the field,
and not worthy of the notice their dogs received.
Many countenances which but for the passions depicted upon them,
would have been lovely and engaging, appeared spoiled and repulsive--many and great,
indeed, are the evil consequences of slavery, both to the oppressed and the oppressor.

My companion and I, in company with another Friend,
pursued our journey towards James River,
crossing the Blue Mountain at a place called Rock-fish Gap, where we lodged.
A number of travellers and other persons had put up here,
among whom were several rough and fierce-looking men, in pursuit of a runaway slave, who,
after being once taken by them, had again made his escape into the woods.

As we sat around the supper table,
they were relating the circumstances of his capture and escape,
loading the poor slave with hard names,
and drawing from their fellow slaveholders the conclusion that,
should they take him again,
the most cruel and severe punishment they could inflict would not be too bad for him.
I was grieved at such conversation, and, feeling my spirit stirred against their conduct,
could not forbear advocating the exertions of the poor runaway to obtain
his liberty--calling upon them to make his case their own,
and think whether there was any among them all who, if placed in his situation,
would not use the same means to escape slavery and punishment.
I was soon convinced of the propriety of the caution given by Christ:
"`Cast not your pearls before swine, lest they turn again and rend you.`"
Their anger was raised, and manifested toward me by furious and wrathful words,
and they were so unreasonable in their conduct that
I concluded it best to say nothing more to them.
The house was in a very solitary place,
and the inmates alike hostile to us--they being also slaveholders--and
from their conduct after we rose from the supper table,
we were not without apprehensions of personal danger.
+++[+++The next morning]
we did not feel quite released from apprehensions of danger,
until we had rode some miles from the place--remembering that William Savery
had been cautioned to beware lest he should be popped off his horse for having
interfered and cut the rope with which a poor colored boy was tied while receiving
a severe flogging for not having the cows in the yard at the usual time.

Towards the conclusion of this journey, Henry Hull had a meeting at Edisto,
of which place he says:

The crying injustice and cruelty of slavery had frequently
engaged my attention during the course of this journey,
but never more than while I was in this place,
where the oppressed race are very numerous, and are frequently sold at auction,
like cattle.
At one of these sales I was much affected in hearing
a young colored man pleading his cause.
His aged father and mother, and his wife and child were all mounted upon a stage,
so that they might be seen by the bidders; they being about to be sold.
The young man stepped up and stood by them, but was soon ordered down.
He said he wanted to be sold with them, but was told that he could not,
as it was a sale to satisfy a mortgage upon the others, in which he was not included.
He pleaded, with very affecting and moving language,
to show how hard it was to be separated from his family; but it was all to no purpose.
When he saw that his prayers were unheeded,
and that the others would be sold without him, he burst into a flood of tears,
and in the anguish of his feelings besought them rather to kill him; "`For,`" said he,
"`I had rather die than be separated from my family,`" upon
which he was dragged off the scaffold and driven away.
The company went on bidding,
apparently as unaffected as though the auctioneer had been selling sheep,
while the screams and prayers of the aged parents,
and the bereaved wife with her infant in her arms,
went up to heaven on behalf of themselves, and especially for the poor young man,
who had been so inhumanly torn away from them.

In these days, when slavery is no longer tolerated by the laws of our country,
it is interesting to observe the bold and honest
labors of faithful Friends in former days,
who were often compelled to cry aloud and spare not the iniquitous system,
even when in the midst of those by whom it was upheld.

Joseph Hoag travelled in the Southern States sixty or seventy years ago,
and was much distressed at the condition and sufferings of the black people,
and the want of humanity in their masters.
He says:

In musing on the situation of the country, sleep often left me, and my appetite failed;
I became feeble and feverish,
feeling a necessity laid upon me to be faithful in every place
where I felt anything in charge for the people from my Master;
and I felt a heavy woe if I gave back in the least,
so that my companion thought I often hazarded my life.
I have not language to set forth, so that another can realize,
what I passed through in those various exercises,
unless they were placed in a similar situation,
for I really feared I should lay my bones in this gloomy land;
and yet it was marvellous to reflect upon that I was never drawn into action,
either in public or private, but what the fear of man was taken from me.
They appeared no more to me than grasshoppers, in the time of action,
and no want was felt of language or matter to confute their
reasoning or confound their boasts in favor of slavery;
so much so, that though I was attacked, in all my travels in these slave States,
more than one hundred times by the learned and the great,
yet in all those disputes my great and good Master so furnished and helped me that,
with two exceptions,
they were always brought to acknowledge that it was
wrong to hold their fellow creatures in slavery,
and were convinced it was contrary to every attribute of the Divine Being.

He adds: "`They appeared to be standing against Divine justice and mercy,
with their eyes open.
But God will not be mocked forever, neither will his justice always slumber.`"
How fearfully was this prediction verified in our late calamitous war!

On one occasion he says:

I saw a master beat a black man wickedly, with a knotty cudgel;
it moved my feelings so much,
that when his anger had subsided I told him what I thought of such conduct.
He seemed to resent it, and rose three times from his seat,
either to frighten me or give me a stroke;
but this did not move my feelings with fear at all; I kept my eyes fixed on his,
and continued my speech until he sat down, kept quiet and hung his head.
He heard me through, and then acknowledged it was not right to hold them in slavery,
or treat them as they did.

William Savery mentions in his journal that,
when on a religious visit in the Southern States,
he stopped at the house of a hard-hearted slaveholder, near Savannah.
One of his lads, about fourteen, coming in from the field at dark,
was ordered to milk the cows, and falling asleep through weariness,
the master ordered him to be flogged.
William says: "`We went to supper, and this unfeeling wretch craved a blessing,
which I considered to be equally abhorrent to the Divine Being as his curses.`"

In the morning, whilst at the door musing, I heard some one begging for mercy,
and also the lashes of a whip.
Not knowing whence the sound came,
I ran and presently found the poor boy tied up to a post,
his toes scarcely touching the ground, and a negro whipper,
with five or six hazel rods lying by him.
He had already cut him in an unmerciful manner, and the blood ran to his heels.
I stepped in between them, and ordered him untied immediately,
which with some reluctance and astonishment was done.
Returning to the house, I saw the landlord, who then showed himself in his true colors,
the most abominably wicked man I ever met with,
full of horrid execrations and threatenings upon all the Northern people;
but I did not spare him.

It would be unjust to suppose that all those who held slaves treated them with cruelty,
but it was one of the bad features of the system of slavery,
that there was no adequate restraint on the cruelty and passion
of such masters as that with whom William Savery met.
A system which regarded human beings as property, to be used for the interests of others,
with but little regard to their own comfort, improvement or religious warfare,
was radically wrong.

During some journeys in the former slave States, since the war of the rebellion,
it was a matter of much interest to note how much the colored people
appreciated the blessing of freedom--even those who had been kindly
cared for and humanely treated while in slavery.
The old people would bless the Lord,
for having been permitted a few years of freedom before they were taken away.

=== Extracts From Thomas Shillitoe`'s Journal

When this devoted servant of Christ was engaged in ministerial labor in this country,
his feeling mind was often painfully affected by the wrongs inflicted
upon his fellow creatures who were held in cruel bondage.
Although slavery has now, as we hope, come to a final end,
it is well to revert occasionally to some of its incidents if only for the purpose
of enabling us rightly to estimate the evil which has been removed,
and to quicken emotions of gratitude for the great deliverance.
The following memorandums were made in the Tenth Month, 1827:

Fifth-day morning we again pursued our journey, crossed the Ohio river in a horse-boat,
and landed in Kentucky, a slave holding State;
on which my feelings were awakened to a thankful sense of being no man`'s slave.
On Second-day morning, about half a mile out of Mount Vernon,
we had a considerable mountain to ascend, and, to make it more easy of access,
bodies of trees were laid from the foot to the summit; a heavy fall of rain in the night,
and a very large drove of fat hogs which preceded us,
had occasioned the road to be very slippery; on reaching about half way up the mountain,
our carriage ran back, our horses turned round,
and turned the carriage off the road into a hole about three feet deep,
amongst the rocks; I was favored to escape unhurt, although in the carriage;
we managed to get it brought in the road again, and pursuing our journey,
reached the top of the mountain in safety.
This morning we were met by a company of slaves, some of them heavily loaded with irons,
singing as they passed along; this, we were informed,
was an effort to drown the suffering of mind they were brought into,
by leaving behind them wives, children, or other near connections,
and never likely to meet again in this world.

A short time after, we met another company; one respectable-looking,
rather well dressed slave, attracted my attention;
his hand was grasping the hand of a fine looking girl,
about fourteen years of age--his countenance appeared very dejected and melancholy.
I was led to conclude from the affection with which he appeared to treat the girl,
that she must be his child, whom in all probability,
he expected soon to be compelled to part with for life.
After this came two wagons, in which they were carrying some who were not able to walk,
also the children, all going to be sold at a market, like cattle.

It being time to bait our horses, while they were feeding,
I walked some distance from our tavern, and observed a handsome carriage standing,
which I supposed belonged to a peddler,
as it appeared to be loaded with coarse woolen goods.
I addressed myself to the owner of the carriage,
telling him he had a load of more bulk than weight; on which he replied,
his carriage contained the clothing of the company of slaves we had passed on the road,
of which he was the owner, saying,
he was seeking a market where he might dispose of them to the best advantage.
I told him his business was a very bad one,
and that a day of reckoning would come in which he would have to
account to his Maker for his conduct towards these poor creatures.
He replied, he believed so too, but said, I have them, and what am I to do with them?
I told him, I believed, were I in his situation,
my duty would point out to me the necessity of liberating them,
and if it were not in my power to do it in any other way,
to sell all my goods and chattels and part with the last
cent I had to assist them in getting to a free country.
To which he replied, it was a bad trade, and he wished it was wholly done away with.
I told him to consider, that same Almighty Power which created him,
created the colored people; and I asked him,
should his wife and children be torn from him,
as these poor creatures had been torn from their near connections,
how would he feel under the like circumstances?
He replied that he should feel it a hard case.
I told him he had better die poor than amass wealth
by such means as he was aiming to get it by.
I then made inquiry into the situation of the respectable
colored man I had seen with the other slaves;
he informed me that this man had left behind him a wife and children,
the property of another slaveholder.
When he took his leave of me he said,
he hoped he should remember the remarks I had made to him.

Next morning we again pursued our journey, and took up our abode at an inn for the night;
two men, who were strangers to us, formed a part of our company in the sitting room;
they inquired of us relative to the droves of fat hogs we had met on the road;
on our giving them such information as we were able, one of them observed,
he had taken a drove of six hundred to one of the markets,
and offered them at ten per cent.
discount, and to take the pay in negroes, but could not succeed.
On my companion remarking to him on his trading in his fellow creatures,
he excused himself by saying,
if he had made such an exchange it would not have been for his own private use;
but in the course of conversation he gave sufficient
proof that his motives for trying to make this purchase,
were not such as he would have had us to suppose;
for on our remarking we had met a wagon-load of negro children,
and men and women on foot,
he said he would have purchased the whole cargo if he could
have agreed with the owner of them about the price.
Although I felt much at the time he made these remarks,
yet silence appeared to be my proper place; but in the morning, before we parted,
I found it laid upon me to open my mind freely to him on the iniquitous
practice of dealing in or keeping in bondage our fellow creatures,
and to warn him against pursuing such evil courses.

=== Thomas Shillitoe and the Slave Trader

Previous to the downfall of slavery,
the iniquitous traffic in human beings formed a regular
branch of business in the city of Baltimore.
The hard-hearted men who conducted it were on several occasions
visited by Gospel messengers who endeavored in Christian love to
show them the wickedness and inhumanity of their calling,
and turn the attention of these guilty men to the requirements
of that holy religion of which they made profession.
A visit of this nature, paid by our Friend, Thomas Shillitoe, in the Eleventh Month,
1827, is thus related in his Journal:

My mind had been occupied with an apprehension of
religious duty to make a visit to a great slave-merchant,
who resided in this city, where the needy slaveholders,
and such as had slaves who were refractory and difficult to manage, were encouraged,
by his weekly advertisement, to come and find a ready market for them.
A large building is erected on his premises like a prison,
to secure them until he has obtained a suitable complement to send to different places,
where there is a demand for them.
I found he was considered, as a man, independent of his employment,
to be of a ferocious disposition, so that many, we were told, stood in dread of him;
notwithstanding which, this subject had taken such hold of my mind,
that I saw no way for my relief but to be willing to attempt an interview with him.

Seventh-day morning we called upon a Friend,
to whom I opened my situation relative to making a visit to this slave-merchant;
we found if we did make such a visit, it would be best for us to go alone;
and accordingly proceeded towards his residence.
On our way I felt much for my companion,
from what I had heard of the unsubdued will and wicked disposition of the slave-merchant,
and the danger we might be exposed to from the large dogs he kept loose about his premises,
to the terror of those who passed by.
But there was no way for me but to cast my care on Him who had so many times
preserved me as from the paw of the bear and the jaws of the devourer.
As we advanced towards the house, one of these fierce looking animals came out at us,
followed by another, as if they would have seized us.
Their noise soon brought out one of the house-slaves, and, as we supposed,
the slave merchant himself, whose countenance looked as fierce as his animals,
querying with us in a stern, commanding manner: "`What is your business?`"
I offered him my hand, feeling nothing in my heart but love towards him as a man;
saying I would be obliged to him to suffer me to have a little conversation with him.
He asked us into his house; on my requesting him to have the dogs taken care of, saying,
I was a nervous man, he attended to it; and in ascending the steps of his house,
we observed more of these large dogs chained about the yards.

He showed us into a very elegantly furnished parlor.
On the shelf of the chimney-piece was a pistol,
which appeared to be ready cocked for use should
he at any time be put to the test of defending himself;
he ordered us to take a seat on a sofa, and placed himself near us.
I gave him my certificate to read, which he appeared to do attentively;
this afforded us an opportunity of having our minds
brought into quiet after our besetment by the dogs,
and their master`'s angry countenance.
When he returned my certificates,
the reading of which appeared to have somewhat softened his mind, he said:
"`I suppose you are going about preaching the Gospel;`" to which I replied:
"`I profess to be so circumstanced.`"
I then endeavored, in a tender, feeling, but decided manner,
to open the subject that brought me to his house,
telling him I came on behalf of the poor colored people;
that I lived in a country where the inhabitants were all free,
but I found I was now in the slave-holding part of the United States of America;
and by an advertisement of his which I had in my possession,
it appeared he was a dealer in these colored people, who were kept in slavery.
I requested him to pause for a moment, and endeavor, as much as possible,
to place his own parents and nearest relatives in the very situation
of those poor creatures he had at times purchased and sold again,
thereby separating the nearest connections far from each other--husbands from wives,
and children from parents; and try how far such acts as he was in the practice of,
accorded with such feelings of humanity as he would wish
should be exercised towards his own parents and relatives;
with more to the same effect.

He appeared to hear me patiently, and tried to justify his conduct,
but with coolness and deliberation; saying,
he was educated in a slave-holding State--that his father was a slaveholder,
that his mother was a pious woman, in connection with the Methodists;
that she was in the practice of reading the Bible to her children,
and that her pious care for him he yet remembered,
and some of the good counsel that she gave him;
that through her influence his father manumitted about seventy slaves;
she died when he was young.
On his father marrying again, he found he must leave home,
or render it unpleasant to his parents, which he did not desire to do,
and therefore entered into the army, and was at the battle of New Orleans;
after the war was over the army was broken up; on quitting it he found himself in debt,
and not knowing what employment to take to, to extricate himself from his difficulties,
a relation encouraged him to become a slave merchant,
offering him funds to commence this trade, which he accepted; and yet said,
we thought feelingly so, it is a bad business, and that he had concluded to give it up,
and had been making arrangements for that purpose.
But some of his employers, in the first rank of slaveholders,
and even some who were making much profession of religion,
would not allow of his giving up his business, but urged him to go on with it.
He laid great stress on the encouragement he received
from this latter description of his customers,
from which I was led to fear,
that when he felt any qualms of conscience on account
of the manner in which he was getting his wealth,
for he was deemed wealthy, the entreaties of this class would be resorted to,
to salve over the wounds of conscience he at times experienced,
which I could not doubt had been the case at times with him.
He also pleaded having the laws of the State to sanction him in his traffic,
which opened the way for me to go further into the subject;
but in time it evidently was manifest, that the Divine witness was so reached in him,
as to compel him to cast away all his weapons of defence.
He gave it as his opinion,
that before twenty years were passed over slavery would be brought to a final close,
if the work was rightly gone about.

By this time we thought we never witnessed the declaration--that
the lion should lie down with the lamb,
more fully exemplified.
He assured us again of his determination to quit the business,
and acknowledged the gratitude he felt for the visit,
took his leave of us in an affectionate manner,
conducting us himself quite off his premises.
As we quitted him, his countenance, which on our first approach, appeared terrific,
was so changed that he was pleasant to look upon.
Everything about his elegant house and his yards,
told in plain terms that he considered himself living
in continual danger of losing his life.
