== Chapter XVI. Separation

Although our early Friends were richly endowed with the gifts and graces of the Spirit,
yet their history clearly enforces the truth that
they had their treasure in earthen vessels,
and that they were not safe any longer than they were preserved
in a state of humble watchfulness and dependence on Divine mercy.
The case of James Nayler is a memorable illustration of this.
He appears to have been eminently gifted as a minister,
and to have preached with an eloquence, energy and Divine authority,
which attracted the admiration and affection of his friends to a high degree.

Gough attributes the beginning of his downfall to the conduct of two women,
who had been reproved by Edward Burrough and Francis Howgill
for their impertinent opposition to their ministry.
They carried their complaints to James Nayler,
whom they were endeavoring to make the head of a party,
in the hope he would give his opinion in their favor.
He thought it his duty at first to discourage their
insinuations against those worthy men,
as tending to sow discord between brethren.
Disappointed in their expectation,
one of them vented her passion in weeping and expressions of regret,
which sunk James Nayler into depression of mind, in which he lost his judgment,
and became estranged from his best and most judicious friends,
and exposed to the pernicious flatteries of these unsettled spirits.
Some of his followers, in their letters to him,
addressed him with appellations not fit to be attributed to any mortal man.
Three of these silly women knelt before him and kissed his feet,
and after his release from prison spread their handkerchiefs
and scarfs before him as he rode into Bristol.
His case claimed the attention of parliament,
who judged these senseless enormities of a few deluded persons
of sufficient importance to engage their attention for ten days.

After undergoing the cruel torture of burning with hot irons,
and whipping till the blood flowed from his shoulders to his waist,
inflicted by order of Parliament on the charge of blasphemy,
all which he bore with quietude and patience, to the astonishment of the spectators,
he was put in prison, and kept there about two years.
This event was a severe trial to George Fox,
William Dewsbury and other substantial Friends, which,
with the opposition of John Perrot, John Wilkinson,
John Story and some others who fell away,
added to the afflictions of faithful Friends at that day.
George Fox remarks: "`So, after I had been warring with the world,
there was now a wicked spirit risen up amongst Friends to war against.`"

Through Divine mercy, James Nayler was favored, during his confinement,
with a clear sight of his lamentable fall, and with sincere repentance on account of it,
and was finally restored to a place in the Truth,
and to the unity of his exercised brethren, and continued therein to the end of his days.
He says:
"`Condemned forever be all those false worships with which any have idolized my person,
all their casting of their clothes in the way, their bowings and singings,
and all the rest of those wild actions which did any ways tend to dishonor the Lord,
etc., and all those ranting,
wild spirits which then gathered about me in that time of darkness;
and all their wild actions and wicked words against the honor of God,
and his pure spirit and people; I deny that bad spirit and the works thereof,`" etc.
"`And if the Lord of all mercies had not rescued me, I had perished,
for I was as one appointed to death and destruction, and there was none could deliver me.
This I confess,
that God may be justified in his judgment and magnified in his mercies without end,
who did not forsake his captive in the night,
even when his Spirit was daily provoked and grieved,
but hath brought me forth to give glory to his name forever.`"

The downfall of James Nayler was peculiarly affecting to William Dewsbury,
to whom he had been a brother beloved, and who labored with him for his restoration,
and afterwards for his reconciliation with his friends.
He says:

The Lord laid it upon me that George Fox and James Nayler might meet together.
My travail was great in spirit until the Lord answered, which, in the day He determined,
was done.
Mighty was his majesty amongst his people in the day he healed up the
breach which had been so long to the sadness of the hearts of many.
The Lord clothed my dear brethren, George Fox,
Edward Burrough and Francis Howgill with precious wisdom;
his healing Spirit did abound within them,
with the rest of the Lord`'s people there that day; according to their measure,
and the Lord was with James Nayler, and ordered him by his Spirit,
so that the measure of the Lord`'s spirit in all
reached to embrace it with gladness of heart.

James Nayler died about the Ninth Month, 1660, in the forty-fourth year of his age.
The following expressions, uttered about two hours before his death,
ought to be frequently brought into view and deeply pondered by his fellow-professors:

There is a spirit, which I feel, that delights to do no evil, nor to revenge any wrong,
but delights to endure all things, in hope to enjoy its own to the end.
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptation.
As it bears no evil in itself, so it conceives none in thought to any other.
If it be betrayed, it bears it;
for its ground and spring is the mercies and forgiveness of God.
Its crown is meekness, its life is everlasting love unfeigned.
It takes its kingdom with entreaty, and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regards or can own its life.
It is conceived in sorrow, and brought forth without any to pity it;
nor doth it murmur at grief and oppression.
It never rejoiceth but through sufferings, for with the world`'s joy it is murdered.
I found it alone, being forsaken;
I have fellowship therein with them who lived in dens and desolate places in the earth,
who through death obtained this resurrection and eternal holy life.

Another individual who made still greater trouble among Friends was John Perrot.
He early joined the Society, and entered into the ministry,
and being puffed up with a conceited estimate of his own abilities,
went to Rome about 1662 to convert the Pope.
There he was put into the hospital for madmen, and, when released, returned to England.
His imaginary consequence and exaltedness of mind so increased,
that he thought himself further enlightened than George Fox and other Friends,
and maintained that the custom of taking off the hat in
joining in public prayer was only a piece of formality.
The regard which was felt for him on account of his sufferings
at Rome procured him a considerable number of adherents.
He finally went over to America, and gave way more and more to whimsical ideas,
reckoning public worship a form to be avoided, putting on a sword and gaudy apparel,
and having obtained a post under government, rigorously exacting oaths.

Richard Davies mentions in his Journal, that:

About the year 1663 or 1664, I went to London,
and found some there separated from that love and unity, which I formerly saw them in;
joining in that spirit with John Perrot who was newly come from prison at Rome to London,
as it was said, with much seeming humiliation and lowliness of mind.
A considerable company joined together with him,
where they had me among them for a little time.
The tendency of that spirit was to speak evil of
Friends that bore the burden and heat of the day,
and so cry out against Friends as dead and formal.
They expected a more glorious dispensation than had been yet known among Friends;
and they kept on their hats in time of prayer.
I was but a little while among them when a veil of darkness came over me,
and under that veil, I came to have a light esteem for my dear and ancient friend,
George Fox, and some others, who had been near and dear to me.
But it pleased the Lord to rend that veil of darkness,
and cause the light of his countenance to shine again upon me;
whereby I came to see the doleful place I was led into,
by a spirit that tended to nothing else but self-exaltation,
and (under a pretence of humility and self-denial) breach of that unity, love,
and fellowship, that formerly we had together,
and the good esteem we had one of another in the Lord.
Children we are of one Father, esteeming one another above ourselves in the Lord.
There was no jar or contention among us then, but all dwelt together in love and unity,
and in the fellowship of that blessed Gospel of peace, life and salvation.

I was but a little time at home, ere John Whitehouse, a follower of John Perrot,
came and had a meeting at my house at Welch-Pool.
I happened not to be at the beginning of the meeting, but came before it was concluded,
and found that he had sown an evil seed, and that some of our Friends had received it;
who soon after joined with that corrupt spirit,
which led them to have a light esteem of their brethren,
which was a great exercise to many honest Friends, and especially to my wife and me;
and we were ready to say, hath the Lord sent us here,
to be instrumental for the gathering of a people in this country,
and hath he suffered the enemy to scatter them in their imaginations?
But some time after, the Lord satisfied me,
that those who were simple-hearted among them,
should be restored again into a more settled condition than they had formerly known;
and I believed in the word of the Lord.
And in time the Lord broke in among them, and opened the understandings of some of them,
and they began to reason among themselves, and saw that they were in darkness;
so that most of them were restored again into their first love,
and lived and died faithful to Truth.

The Christian spirit that moved Friends,
to labor with those who were drawn into separation from them,
is hinted at in the following short letter, written in 1669, by John Rouse to Sarah Fell:

Dear Sister:

We have had several precious meetings since the General Meeting,
for the gathering those who have gone astray;
in which the power and glory so irresistibly broke in upon them,
that many of them were very much broken,
and gave open testimonies against that spirit that
had seduced them from the unity of Friends,
very much to the satisfaction of the faithful.
The power wrought so effectually among them,
that Friends had little need to set forth the evil of the course they had followed;
for they themselves gave sufficient testimony of the evil thereof.
And the bowels of Friends were so enlarged towards them,
that I believe there will be meetings appointed for the gathering of them,
so long as any, that are honest among them, are left ungathered.

George Fox, in his Journal, writes:

We had great service in London this year, and the Lord`'s Truth came over all;
and many that had been out from Truth, came in again this year,
confessing and condemning their former outgoings.
Several meetings we had with them, and the Lord`'s everlasting power was over all,
and set judgment on that which had run out.
In these meetings, which lasted whole days,
several who had run out with John Perrot and others, came in again,
and condemned that spirit which led them +++[+++with him]
to keep on their hats when Friends prayed, and when they themselves prayed.
Some of them said, that if Friends had not stood, they had been gone,
and had fallen into perdition.

Thomas Ellwood also mentions the "`memorable meeting appointed to be holden in London,
through a Divine opening in the motion of life,
in that eminent servant and prophet of God, George Fox;
for the restoring and bringing in again those who had gone out from Truth,
and the holy unity of Friends therein, by the means and ministry of John Perrot.`"
"`When that solemn meeting was appointed at London,
for a travail of spirit on behalf of those who had thus gone out,
that they might rightly return,
and be sensibly received into the unity of the body again, my spirit rejoiced,
and with gladness of heart I went to it; as did many more of both city and country;
and with great simplicity and humility of mind,
did honestly and openly acknowledge our outgoings,
and take condemnation and shame to ourselves.`"
"`Thus, in the motion of life, were the healing waters stirred, and many,
through the virtuous power thereof, were restored to soundness;
and indeed not many were lost.
And though most of those who thus returned, were such, as with myself,
had before renounced the error and forsaken the practice; yet did we sensibly find,
that forsaking without confessing (in case of public scandal), was not sufficient;
but that an open acknowledgment (of open offences) as well as forsaking them,
was necessary to the obtaining complete remission.`"

In the latter part of the seventeenth century,
Friends in Pennsylvania were much troubled by the course pursued by George Keith.
He was a man of considerable abilities and learning, and in his native country, Scotland,
had preached,
written and suffered imprisonment and hardships for the principles of Friends.
He removed to Pennsylvania in 1689,
and was appointed teacher to a school set up by Friends.

With a high opinion of his own intellect and attainments,
he became dissatisfied if his own ideas were not received by his brethren,
and soon began to manifest a contentious spirit.
Friends appear to have exercised much patient forbearance,
but George became more and more violent and abusive until finally
the Monthly Meeting of Philadelphia proceeded to disown him,
and George Keith set up a separate meeting.

Thomas Wilson, in 1692,
visited Pennsylvania and had several meetings with George Keith and his party.
He told them that they were gone from the Lord in an airy flourish, and the wit of man,
and had set up a separate meeting,
but in a little time the sun of righteousness would shine among them,
and drive away the misty doctrines of men, and that they would dwindle and die away,
and come to nothing, except such as were most honest,
who should return to Truth and Friends.

In 1694 George Keith went over to England to argue his case before Friends there.
He attended London Yearly Meeting,
which spent ten days in listening to the statements laid before it,
and in endeavoring to restore unity,
and at last came to the judgment that George Keith was responsible for the separation,
and that he had done ill in printing and publishing those differences as he had done.
His rude and passionate behavior prevented his gaining many adherents.
He refused to take the advice of the Yearly Meeting,
but continued printing unsavory statements.
In 1695,
his case was again considered and the Yearly Meeting adopted a testimony against him,
in which they say that he had "`Separated himself from the holy fellowship of
the church of Christ,`" and "`ought not to be owned and received as one of us.`"

He set up a separate meeting, which continued for a few years.
But confusion soon began to prevail among his followers.
Some of them in Pennsylvania became reconciled to Friends,
others joined in membership with other societies.
In the Epistle from Philadelphia to London Yearly Meeting in 1697, they say:
"`Our exercises with the separatists is much over here.`"
Keith himself became an Episcopalian,
and was sent over to America by his bishop about the year 1702,
in the hope that he might win over to that sect, some of his former associates.
He appears to have spent his time principally in New England,
where he met with John Richardson, then on a religious visit to Friends in America.
John had gone to Lynn to attend the Monthly Meeting there,
and the evening before it was held, George Keith came to the house where he was staying,
and began railing against Friends, and said they pretended to be against all persecution,
but they were not clear,
for the Quakers in Pennsylvania and New Jersey had persecuted him,
and would have hanged him, but there was some alteration in the government.
John replied:

"`George this is not true.`"
I then demanded of him, What way our Friends proceeded against him,
and what measures they took, as he would insinuate, to bring him to the gallows.
But fear began to surprise the hypocrite,
and he would not meddle in the least with the particulars.
I then showed the people the falsity of his charge, and the wickedness of his spirit,
and the peaceableness of Friends`' behavior towards him.

At meeting the next day,
George stood up to tell us that he was come in the queen`'s name,
to gather Quakers from Quakerism to the good old mother church, the church of England,
as he called it, and that he could prove out of our own books, that we held errors,
heresies, damnable doctrines and blasphemies.
I stood up and signified to the people what manner of man George Keith was,
that he had been publicly disowned and testified against by us.
After a time it pleased the Lord to open my mouth, beginning with the words:
"`In that way you call heresy, do we worship the God of our fathers,
believing all things that are written concerning Jesus Christ,
both as to his Godhead and manhood,`" etc.
The people appeared very attentive, for the Lord`'s heavenly,
baptizing power was amongst us that day.

After John Richardson had ended, George began to exhibit his charges against Friends,
and said he could prove them out of our Friends`' books.

He was now crowded up into the gallery between me and the rail, with a paper in his hand;
and I standing over and being taller,
could see his quotations and his paraphrases upon them, on which I told him loudly,
that all the meeting might hear,
That he offered violence to that sense and understanding which God had given him,
and that he knew in his conscience we were not that people,
neither were our Friends`' writings either damnable or blasphemous,
as he through envy endeavored to make the world believe,
and that he would not have peace in so doing,
but trouble from the Lord in his conscience.
I spoke in the Lord`'s dreadful power,
and George trembled so much as I seldom ever saw any man do.
I pitied him in my heart, yet as Moses said once concerning Israel,
I felt the wrath of the Lord go forth against him.
George said, Do not judge me.
I replied, the Lord judges, and all who are truly one in spirit with the Lord,
cannot but judge thee.
So he gave over, and it appearing a suitable time to break up the meeting,
Friends parted in great love, tenderness and brokenness of heart.

George Keith remained in America about a year,
but not meeting with much success he returned to England,
when he obtained a benefice in Sussex.
Here he got into dispute with his parishioners,
being very exacting in the collection of tithes.
There is some reason to hope that he was re-visited by the long-suffering grace of God,
for about the year 1714, as he lay on his deathbed, he said to one who visited him,
that "`He did believe if God had taken him out the world
when he went among the Quakers and in that profession,
it had been well with him.`"

We have spoken elsewhere of the small secessions from the Society
of Friends which arose out of the military excitement which prevailed
in this country at the time of the Revolutionary war.
About the commencement of the present century a few members in Ireland left the Society;
the ground of this separation was doctrinal.
Hannah Barnard of New York,
being then in Great Britain on a religious visit appears
to have joined in feeling with these unsettled people.
Henry Hull, who had travelled with her in America,
says that she evinced much love and zeal for the cause of religion,
but afterwards imbibed and promulgated "`Principles inconsistent
with what she had once so zealously propagated,
denying the literal accuracy of some parts of the Holy Scriptures,
and rejecting the doctrines of the Divinity and atonement
of our Lord and Saviour Jesus Christ,
for which she was disowned from Society.`"

Some years after this fresh troubles arose in America springing
from the preaching of similar doctrines by Elias Hicks and others,
which led to the withdrawal, about the year 1827,
from communion with their former brethren, of many thousands of persons in Pennsylvania,
New York, Ohio, Maryland and other States,
and occasioned great distress to many who were concerned to uphold our original principles.
This breach has never been healed, but the two bodies, each claiming the name of Friends,
have continued to exist side by side.
