== Chapter XVII. Prayer, Meetings, Etc.

The late John Barclay says the essence of true prayer
is a reverential breathing unto the Lord,
and a longing of the soul after those things that we need;
and he thus relates his own experience:

I remember that after I refrained from repeating those forms of prayer,
which were taught me in my childhood,
I was much in the habit of kneeling down and repeating extempore prayers,
by dint of my natural abilities;
this I did for some little time with great fervor of youth and eloquence,
even sometimes aloud, both morning and evening,
until the Lord opened my eyes in this respect,
and gave me clearly to see that these attempts, in my own will, way and time,
were but sparks kindled about me,
and which availed nothing with Him whose own sacrifices
(of his own preparing and kindling) were alone acceptable.
Thus in obedience I was made willing to be silent and to seek the Lord,
who is nigh at hand, and dwells in the hearts of his people,
and is not far from any one of us, if we look for and unto Him.
This silence of all the creaturely reasoning powers was very hard to something in me,
which would be judging and questioning--very unmeaning did it appear;
yet durst I not forbear to meet with my Lord and Master, or to strive to meet with him,
day by day, and oftener than the day; and frequently crying,
in the depth and sincerity of my heart, unto Him,
that He would be pleased to show me the way to call upon Him aright,
and what to pray for.
I was often in tears, and lay down my head in grief upon my pillow,
fearing I should never be made sensible of true prayer,
and partake of the privilege of "`praying always.`"
The Lord did not long leave me without his blessing,
his blessed countenance and presence and comfort; no--He showered, at times,
of his merciful goodness into my poor heart, and kindled such love towards himself,
such earnest breathings after the further arising,
the glorious spreading and increasing exaltation of his name and power and truth,
as enabled me truly to praise and bless his holy name,
engaged me still more to cleave unto, obey and follow Him in whatsoever He might require.

His experience was similar to that of Isaac Penington, as recorded in one of his letters:

Because my not praying in my family, according to the custom of professors,
seemed to be such a great stumbling-block to thee,
it sprang up in my heart to render thee this account thereof.

I did formerly apply myself to pray to the Lord,
morning and evening (besides other times),
believing in my heart that it was the will of the Lord that I should so do.
And this was my condition then: Sometimes I felt the living spring open,
and the true child breathe towards the Father; at other times I felt a deadness,
a dryness, a barrenness, and only a speaking and striving of the natural part, which I,
even then, felt was not acceptable to the Lord, nor did profit my soul; but,
apprehending it to be a duty, I durst not but apply myself thereto.

Since that time--since the Lord hath again been pleased
to raise up what He had formerly begotten in me,
and began to feed it by the pure giving forth of that breath of life which
begat it (which is the bread that comes down from heaven daily to it,
as the Lord pleaseth freely to dispense it),
the Lord hath shown me that prayer is his gift to the child which He begets,
and that it stands not in the will, or time, or understanding,
or affectionate part of the creature, but in his own begetting,
which He first breathes upon, and then it breathes again towards Him;
and that He worketh this at his own pleasure,
and no time can be set Him when He shall breathe or when He shall not breathe;
and that when He breathes, then is the time of prayer,
then is the time of moving towards Him, and following Him who draws.
So that, all my times, and all my duties, and all my graces, and all my hopes,
and all my refreshments, and all my ordinances are in his hand,
who is the spring of my life, and conveys,
preserves and increases life of his own good pleasure.

I freely confess, all my religion stands in waiting on the Lord,
for the riches of his Spirit, and in returning back to the Lord (by his own Spirit,
and in the virtue of his own life) that which He pleaseth to bestow on me.
And I have no faith, no love, no hope, no peace, no joy, no ability to any thing,
no refreshment in any thing, but as I find his living breath beginning,
his living breath continuing,
his living breath answering and performing what it calls for.
So that I am become exceeding poor and miserable,
save in what the Lord pleaseth to be to me by his own free grace,
and for his own name`'s sake, and in rich mercy.

James Backhouse records, in his Memoirs,
an incident which shows his views in regard to prayer:

The evening was spent pleasantly in the family of a pious settler.
After the reading of the Scriptures, a long silence ensued,
which was concluded by my stating to the company
that I did not apprehend it was my place,
at that time, to express anything in the way of exhortation or prayer.
On my doing this, the master of the house knelt down with his family,
and uttered some petitions.
We thought it our place, on this occasion, to keep our seats,
and thus to bear a testimony against that disposition which determines,
on such occasions, to utter something in the way of prayer; and which has, by this means,
a strong tendency to draw the mind away from inward prayer,
and to cherish a feeling as if prayer must necessarily be vocal,
and might be performed by proxy.
We afterwards had some satisfactory conversation on this subject,
and on the advantage of cultivating, in silence, an individual inward exercise,
and of not engaging in vocal prayer,
except when the mind is brought under the feeling of duty in the matter.

When Jacob Lindley and other Friends were attending an Indian treaty,
they met with an instance which illustrated the uselessness of merely formal prayers.

Among the officers of the army was one much addicted to profane swearing,
and who was living a licentious life.
The Friends, in the freedom of the Truth, told him of his sins;
pointed out to him his degraded course of life,
and the danger he stood in of eternal punishment.
He said, in reply, that he thought no harm would ensue to him for his conduct,
for though they might "`think it very strange, he never lay down, drunk or sober,
without saying his prayers.`"

Our blessed Saviour had occasion to query, when personally upon earth:
"`Why call ye me Lord!
Lord! and do not the things which I say?`"
Such language might be addressed to many other professing
Christians as well as to the poor,
drunken, swearing, licentious, prayer-repeating officer mentioned above.
Little good will it do for us to acknowledge our sins in word,
and ask daily forgiveness for our trespasses, if we continue in them.
"`Not every one that sayeth unto me, Lord!
Lord! shall enter the kingdom,
but he that doeth the will of my Father which is in heaven.`"

=== Worship

James Backhouse, says:

In the evening we had a long conversation with a person of religious character,
who admits that silent retirement in private is a state most favorable to devotion,
but he does not seem to be able to enter into the
views of Friends in regard to public worship,
at least as respects the silent part of it,
and he cannot understand why meetings should sometimes be held wholly in silence.
I believe these things are a mystery to many other good men;
and unless the Lord open their understandings to see the
advantage of this united retirement of soul before Him,
I have no expectation that they will understand it by argument.
Nevertheless,
the matter is so plain to those who have felt the benefit of this mode of worship,
that we rarely find they can be satisfied with any other.
In dwelling under the baptizing influence of the Holy Spirit,
in reverent stillness before the Lord, a sense is given us of our unworthiness,
also of acceptance in the Beloved who died for us;
we feel that we become his adopted members, and are bowed in a reverent fear before Him;
so that we are brought to watch and wait before the Lord, in meetings and out of them,
and to revert to this state of expectation from Him alone,
whenever we find ourselves carried away from a sense of his presence being with us.

From Samuel Fothergill`'s sermon, delivered at Leeds, 1760:

It is a communion in spirit,
wherein the sanctified soul approaches the Author of spirits with a sacrifice in spirit,
when the sacrifice of words shall fail.
For there is a communion which language cannot express!
A worship that wants not the aid of words, nor is to be defined by a harmony of sounds,
in which we approach the sacred Author of unutterable love.

When there was "`silence in heaven for the space
of half an hour,`" when the vocal tribute of "`holy,
holy,
holy,`" and the hallelujahs of sanctified spirits in endless felicity were suspended,
their worship continued in awful, holy, solemn, inconceivable silence;
it was a rapturous adoration,
too copious for language to express! a cloud of incense
before the throne of immaculate purity and love;
may our minds be gathered to it, let our profession to religion be what it may;
and may we experience this Divine communion of saints,
and deeply ponder God`'s unbounded love in solemn silence.

Thus writes Robert Barclay:

As there can be nothing more opposite to the natural will
and wisdom of man than this silent waiting upon God,
so neither can it be obtained nor rightly comprehended by man,
but as he layeth down his own wisdom and will,
so as to be content to be thoroughly subject to God.
And therefore it was not preached nor can be so practised,
but by such as find no outward ceremony--no observations--no words--yea,
not the best and purest words, even the words of scripture,
are able to satisfy their weary and afflicted souls; because where all this may be,
the life, power, and virtue which make such things effectual, may be wanting.
Such I say were necessitated to cease from all externals,
and to be silent before the Lord;
and being directed in that inward principle of light and life in themselves,
as the most excellent teacher which can never be removed into a corner,
came thereby to be taught to wait upon God in the
measure of life and grace received from Him,
and to cease from their own forward words and actings,
in the natural willing and comprehension, and feel after this inward seed of life;
that as it moveth they may move with it, and be actuated by its power and influence,
whether to preach, pray, or sing.

And so from this principle of man`'s being silent
and not acting in the things of God in himself,
until thus actuated by God`'s light and grace in the heart,
did naturally spring that manner of sitting silent together,
and waiting together upon the Lord.
For many thus principled, meeting together in the pure fear of the Lord,
did not apply themselves presently to speak, sing, pray, etc.,
being afraid to be found acting forwardly in their own wills,
but each made it their own work to retire inwardly to the measure of grace in themselves,
not being only silent as to words, but even abstaining from all their own thoughts,
imaginations, and desires; so watching in a holy dependence on the Lord,
and meeting together not only outwardly in one place, but thus inwardly in one spirit,
and in the one name of Jesus, which is his power and virtue,
they come thereby to enjoy and feel the arisings of this life, which,
as it prevails in each particular, becomes as a flood of refreshment,
and overspreads the whole meeting.

It is a current opinion among some that silent meetings
did not much prevail in the early period of the Society,
but its records show that they did often exist.
Richard Davies, in 1657, mentions one in which he says:
"`Though it was silent from words, yet the Word of the Lord God was amongst us;
it was as a hammer and a fire; it was sharper than a two-edged sword;
it pierced through our inward parts; it melted and brought us unto tears,
so that there was scarcely a dry eye amongst us:
the Lord`'s blessed power overshadowed our meeting,
and I could have said that God alone was Master of that assembly.`"

When Joseph Oxley settled in the country, he says:

After a time, I got my little shop furnished, and myself agreeably settled.
I had now to consult with my grandmother how I should
conduct myself during the time of our week-day meetings,
my shop standing by itself; without hesitation, she soon advised me what I should do,
and that was, when meeting day came, to shut up my shop, "`for,`" says she:
"`thy grandfather and I did so, and when we returned from meeting,
generally found many customers waiting for us,`" and believed they never were
sufferers by shutting up their shop for the sake of going to a religious meeting.
I immediately joined in with my grandmother`'s advice, being of the same judgment,
and sweet, comfortable, edifying meetings we had,
such as I trust will make long and lasting impressions on my mind.

In the Journal of Christopher Story, it is related that:

Some years after our convincement,
being met in the house of Christopher Taylor to wait upon the Lord,
his power and presence in a wonderful manner overshadowed us in our sitting together;
and there was much brokenness and tenderness on the spirits of Friends,
which spread over the whole meeting except three or four persons who sat dry,
and they proved not well.
I being near the door,
saw many in the room filled before the power of the Lord reached me; yet the Lord,
in his free love and mercy, was pleased to give me such a share among my brethren,
that my heart is always glad when I remember that season of God`'s love,
though now upwards of twenty years ago.
And though we were at times plentifully fed with that bread which came down from heaven,
and sat together at the Lord`'s table,
where the wing of his power was known to overshadow us;
yet at other times the Lord tried us with want;
and at a certain time it entered my mind as a weighty
consideration why it should be thus,
we being the same people, and sometimes had very good and comfortable meetings,
and were sometimes very dry and barren in our meeting together.
As I was thus concerned in my mind,
it opened to me that there should be seed time and harvest, summer and winter,
unto the end of the world.
So I saw clearly there were times to abound and times to suffer want;
and I desired to rest satisfied in the will of God.

William Penn has left an interesting account of a visit,
which he in company with some other Friends paid to princess Elizabeth of Herwerden.
She was a religiously minded woman and received these
ministers of the Gospel with great cordiality.

The visitors were welcomed by the princess and her friend the day after their arrival,
and were invited to dine with them.
They held a religious meeting together,
which was so satisfactory that the princess desired another might be appointed,
at which several persons were present.
William Penn thus speaks of it:

The eternal Word showed itself as a hammer this day; yea, sharper than a two-edged sword,
dividing asunder between the soul and the spirit, between the joints and the marrow.
Let my right hand forget its cunning, and my tongue cleave to the roof of my mouth,
when I shall forget the lovingkindness of the Lord, and the sure mercies of our God,
to us that day.

The following day they paid two visits at this little court; and the day after,
which was the first day of the week, they held a meeting there,
appointed by the direction of the princess; at which several persons were present,
besides those of her household.
Among other things, Penn says of this meeting:
"`The quickening power and life of Jesus wrought and reached them;
and virtue from Him in whom dwelleth the Godhead bodily went forth.`"
After this meeting, which held till late in the evening, the visitors took their leave,
but not before they had been witnesses of the tender disposition of mind of the princess;
who,
attempting to set forth her sense of the power and presence of God prevalent among them,
could not proceed, but turned herself to the window, and said: "`My heart is full,
I cannot speak to you.`"

On the twenty-fifth of Tenth Month, 1834, G. W. Walker and I +++[+++James Backhouse]
went again to New Norfolk +++[+++Van Diemen`'s Land],
where on the following day we held two meetings.
In the one of them, a man who is attached to the principles of Friends,
reproved some persons for whispering; and afterwards remarked,
that our sitting in silence might appear strange to some,
who had not considered the matter, but that, for his own part,
he could bear testimony to the benefit of the practice;
that before leaving England he had for some time attended a little meeting of Friends,
in which, often, not a word was spoken;
that when these meetings had been held in silence, he had been more edified,
and his mind was turned to the light of Christ,
than ever he had been under the most learned, studied discourses;
and that he was convinced others would also be thus edified, even in silence,
if their minds were turned to the inward manifestations of that light, which is given us,
through Jesus Christ.

Joshua Evans found his mind engaged to draw the attention
of Friends to the class of bees called drones,
who did not work for themselves, but loved to live on the labors of others.
He exhorted them when they went to meeting to labor industriously in spirit,
that they might know the Lord himself to feed them,
and not to spend their time in looking to the servants,
and depending on them for spiritual instruction.
The servants can give only as it is furnished them,
but those who are industrious in waiting on the Lord renew their spiritual
strength whether there be any vocal utterance in the meeting or not.

John Parrett, was a resident of Birmingham, England, and died in the year 1840.
He had for many years been connected with the Methodists;
but not feeling satisfied either with his own spiritual attainments,
or with the people with whom he was connected,
he attended an afternoon meeting of Friends in Birmingham.
The meeting held somewhat longer than usual and was silent,
but was favored with a sensible experience of the Divine overshadowing.
At its close, John Parrett approached the writer of this article, with the query:
"`Do you not think, if these people had been waiting on the Lord, as they profess to do,
that some one would have had something to say all this time?`"
The answer to this query was:
That it was probable that if all had been sufficiently engaged,
there might have been some testimony;
but it seemed that he knew not that Friends believed they
could hear Christ by his spirit in their own hearts,
without a preacher.
After a pause, he said he believed they might,
and expressed his desire to know more about the belief of Friends.
When he became acquainted with the principles they held as to worship and ministry,
and their doctrine,
that the true ministers of the Gospel should speak only as they were moved of the Lord,
and deliver only that which had been immediately revealed to them,
he was concerned to visit several noted preachers among the Methodists,
to enquire of them concerning their ministry.

His first visit was to a very conspicuous and zealous man;
who went out afterwards as a missionary to New Zealand,
and was lost by the upsetting of a boat, while passing between the islands.
John Parrett conversed with this preacher,
saying he had been witness to his zeal and animation,
and desired to know whether what he delivered to the people,
was received by immediate revelation from the Lord.
The preacher replied, it was not; but that the Scriptures were a mine,
and he went to them and dug; but perceiving the importance of the query,
he declined any further answer.
From another who had been very successful, he received a similar reply to his question,
with the addition, that he found it written in the Scriptures of Truth:
"`Go ye into all the world and preach the Gospel to every creature.`"
This he said with very marked emphasis;
but when asked whether he considered those words
a standing commission to all who read them,
after a considerable pause he replied, they were written to characters,
and if he was one of those characters, they were written to him; adding,
he must decline any further conversation, or he could not preach that evening.
He then visited one who professed to live in a sanctified state,
and asked him whether he believed in the immediate direction of the Holy Spirit?
He replied, that some old people amongst them had thought they had come to such a state;
but added, "`we consider such childish.`"

=== Meetings

James Gough was a minister in the Society of Friends, residing in Ireland,
in the last century.
An instructive account of him is to be found in the ninth volume of _Friends`' Library_.
The following extract therefrom seems interesting and instructive:

From Dublin I proceeded towards Limerick, by Mountmellick, Mountrath, and Kilconnermore,
where John Ashton was then living; a valuable, good man,
little inferior to most I have known, in my estimation.
Although not eminent for great or shining parts,
yet he was a shining light in the county where he resided, in love and good works;
a man of great humility and fervor of soul for the promotion of piety;
much beloved and esteemed of his neighbors and friends.

When I came to the good old man`'s house, being now near eighty years of age,
he was very much indisposed; and,
it being about the middle of the Eighth Month (old style), or October,^
footnote:[Until 1752,
March was considered the first month of the year in all of England and its colonies.
O+++.+++ S. stands for Old Style,
referring to the former way of reckoning months according to the older Julian calendar.]
and the Friends in that part being late with some part of their harvest, he proposed,
notwithstanding his infirmity, to accompany me to Limerick,
a great day`'s journey for him when he was well, as the roads were then;
and his relations apprehending it too hazardous for
him to undertake under his present indisposition,
endeavored to dissuade him from it,
which made me desirous that he might not suffer in
his health or meet with any dissatisfaction of mind.

It proved a fine day; he grew much better, and his conversation was very edifying.
Our friends at Limerick rejoiced greatly to see him,
being the last time of his being there.
Next day being First-day, we had two comfortable meetings there.

On Second-day morning, at parting, he told me he was well paid for coming.
He was well and hearty the winter following,
and the next spring set forward towards the half-year`'s meeting at Dublin;
but having reached Birr, he found himself unable to go further, returned home, and,
after a short illness, departed this life,
leaving behind him a general testimony all round the country on his behalf,
as one who had eminently served God, loved mankind,
and was greatly beloved by almost every one who knew him.

He and his wife were both convinced at one meeting at Birr,
through the powerful ministry of that able and eminent minister of the Gospel,
Thomas Wilson.
Coming out of that meeting,
they said to each other the way of everlasting happiness
had been clearly laid down before them,
and they were resolved to walk in it, come life or come death.

Not long after,
John was thrown into prison for his Christian testimony
against the oppressive and anti-Christian yoke of tithes.
Being used to work without doors, he was at a loss how to employ his time,
but soon learned to make gartering and laces.

When at liberty, he, with his wife, constantly, twice a week,
attended the meeting at Birr, generally walking on foot thither,
being about seven English miles, and a very bad road, wading through a river in the way,
both going and returning.
In winter, in crossing this river, they sometimes had the ice to break,
and John said he had wept to see the blood on his wife`'s legs in coming through it.
In those days Truth was precious to its professors, who also possessed it,
and no difficulties or dangers could prevent them from getting to their religious
meetings to enjoy the renewings of Divine love and life with their brethren.

This good man also took great pains to get travelling
Friends to appoint meetings at his house,
and then to acquaint people thereof, several miles round,
travelling for that purpose by night as well as by day,
in the winter season and in severe weather,
and underwent much reproach for this labor and diligence.
Yet he was blest in it, both inwardly and outwardly;
many came to the meetings at his house, several were convinced of the Truth,
and in process of time a meeting was settled there, and grew larger than that of Birr,
out of which it had sprung.

At the time of his joining our Society he was in low circumstances;
but through industry and the blessing of heaven he grew rich, and did abundance of good,
being singularly hospitable, liberal and charitable.

At the above said meeting at Birr, through the ministry of Thomas Wilson,
there was also convinced his wife`'s daughter, Mary, the wife of James Sheppard.
This was a great mortification to her husband, who tried various means to reclaim her.
At length, a noted preacher being to preach at the worship house he frequented,
he proposed to his wife that, if she would go with him to hear him,
he would go with her next Sunday (as he called it) to the meeting at Birr,
to which proposal she assented.
She went accordingly, and heard fine words and eloquence;
but that was not what her soul wanted.

Next First-day, pursuant to his engagement, he went with her to Birr.
It proved to be a silent meeting there; yet,
through the reverent attendance of the souls of those present upon Christ,
the best Minister, they were favored together with his life-giving presence,
with the sense of which the said James was reached and tendered into contrition,
in the sight of the self-denying path cast up to peace with God.
Hereupon, what he little expected at his going to that meeting,
he immediately joined in society with Friends,
and became a serviceable man in his station.

A testimony of Stephen Grellet, recorded in 1805:

I have been very sensible, during these weeks past,
that the low state in which I find our Society, meeting after meeting,
is owing to their having departed from that retiredness of spirit, and lowliness of mind,
which characterized our former Friends and the primitive Christians.
They have retained, indeed, to a certain degree, the outward profession,
but too few continue in the life.
What a neglect is mournfully prevailing in many families
to train them up in a religious life and conversation,
consistently with our Christian profession; nevertheless,
the Lord has a precious remnant preserved in almost every place,
to whom I feel nearly united.
Through many baptisms He has brought them and preserved them,
and I have faith to believe that, though this people may be chastened to purify them,
they will not be forsaken; and from among the children--yea,
from generations yet unborn--will arise such as will magnify the name of the Lord,
their Redeemer.

=== Scriptures

Isaac Penington says:

We do, indeed, really, heartily, singly, as in God`'s sight,
own the Scriptures--the Scriptures written by the prophets and holy men of God,
under the law--the Scriptures written by the evangelists and apostles
in the time of the Gospel--and we read them with delight and joy,
and would draw no man from a right reading of them, to the benefit of his soul,
but only from giving their own judgment on them, without the Spirit of God,
lest in so doing they wrest them to their own destruction.
This is that which the Lord hath drawn us from,
and which we know it would also be profitable to others to be drawn from too; to wit:
from imagining and guessing the meaning of the Scriptures,
and interpreting them without the opening of that
Spirit from which they were given forth;
for they who do so feed that part with a gathered knowledge, which should be famished,
die and perish, that another thing might come to live in them and they in it.

George Whitehead says:

I always had a love to the Bible and to reading therein, from my childhood,
yet did not truly understand nor experience those doctrines essential to salvation,
nor the new covenant dispensation, until my mind was turned to the light of Christ,
the living, eternal Word,
the entrance whereof giveth light and understanding to the simple.
Yet I do confess it was some advantage to me frequently to read the Holy Scriptures,
when I was ignorant,
and did not understand the great and essential things therein testified of.
For when the Lord had, livingly,
in some measure opened my understanding in the Holy Scriptures,
by my often reading the same before, having the better remembrance thereof,
it was a help and advantage to my secret meditations when
a lively sense and comfort of the Scriptures was,
in measure, given me by the Spirit,
and thereby I was the more induced to the serious reading
and consideration of what I read in the Holy Scriptures,
and the comfort thereof made known by the Holy Spirit enlightening the understanding.
It is through faith which is in Christ that the Holy Scriptures
are said to make the man of God wise unto salvation,
and profitable to him for doctrine, reproof, admonition and instruction in righteousness,
that he may be perfect and thoroughly furnished in every good word and work.
Doubtless Paul esteemed Timothy`'s knowing the Holy Scriptures
from a child to be some advantage and help to him,
but it was principally through faith, which is in Christ Jesus.

These things considered,
I would not have Christian parents remiss in educating
and causing their children to read the Holy Scriptures,
but to induce them both to learn and frequently to read therein.
It may be of real advantage, and profitable to them,
when they come to have their understandings enlightened,
and to know the Truth as it is in Christ Jesus.
I have sometimes observed children, in reading the Bible,
have been affected with the good things they have read, from a secret belief of them,
which hath had such impression that they have been
induced to a more serious consideration thereof,
when the Lord has opened their understandings, in some measure,
by the light of his grace in them.

By what I have here declared in commendation of Holy Scripture,
and the advantage thereof,
I would not be understood to limit the gift of the Spirit of God, or ministry thereof,
or any of his Divine graces, from the illiterate, the unlearned,
or from persons of little education--as ploughmen, herdsmen, shepherds, fishermen, etc.
For God hath given of his good Spirit and spiritual gifts to such,
and hath promised "`to pour out of his Spirit upon all flesh;
and that sons and daughters should prophesy.`"
And Moses said: "`Would God that all the Lord`'s people were prophets,
and that He would put his Spirit upon them.`"
Among whom both men and women, learned and unlearned, are included.

When Samuel Bownas was travelling in New England, he had an appointed meeting at Newbury,
of which he says:

The priest came, and did all he could to hinder the people from coming in,
and made a great noise concerning the danger of our principles and doctrines.
I endeavored to press him to show wherein, but he evaded that as much as he could,
and charged in general.
Being closely pressed, at last he pitched upon our denying the Scriptures,
baptism and the supper, and the resurrection of the body.
I bid him hold, and first prove that we denied the Scriptures, and so the rest in order,
as they came in course.
I asserted that we owned the Scripture, and he said we did not; I demanded proof of him,
otherwise he must be concluded a false accuser.
He went about it, but could make nothing of it.
When he had said what he could,
I told him his accusation relating to the Scriptures must be false,
for it was publicly known that, both in our preaching, and also in our writings,
frequent recourse was had to the text to prove our doctrine,
and this must be a plain demonstration and proof that we owned the Scriptures.
The people allowed this to be right; and he, coming off so lame at first,
would proceed no further in that public manner,
but would have me go to his house and talk these matters over in his closet.
I told him his meetinghouse was more proper for such a conference than his closet,
and there I would meet him when he pleased.
I had heard he treated the doctrines held by us very unhandsomely in his pulpit,
where he knew none dared to oppose him; and if he would clear these things up,
I should be pleased with an opportunity to hear him
do it in as public a way as he had defamed us,
either to make proof of his charges or retract them;
but he would not permit any such thing.

The controversies into which Friends were sometimes drawn in defence of their doctrines,
are often instructive reading at this day; clearly showing the views they held,
and giving strong arguments in support of them.
Samuel Bownas describes an interview between himself and some other
Friends at Jedburgh and some of the people in that neighborhood,
who called upon them at the inn where Friends were tarrying.

The conversation was chiefly religious,
and one of the first topics discussed was the rule of faith and practice,
Samuel Robinson managing the argument on behalf of Friends.
After they had proceeded for some time,
Samuel Bownas desired liberty to ask a few questions, which was promptly granted.
He says:

I began to state the difference between us thus:
"`We all agree that the Scriptures are a rule of faith and practice; do we not?`"
This was granted.
"`The difference lies here, if I take it right: we say it is a rule;
you say it is the only rule; this is the point in dispute, is it not?`"
This was likewise granted.
Then I proceeded thus: "`Allowing what you say to be true,
it must be considered that all instrumental rules are made,
whether they relate to spiritual or temporal affairs,
and must be contrived and adapted to answer the end for which they are made.`"
This was allowed also.
"`And as the text is a rule made, contrived and adapted for spiritual affairs,
who made it so, since the text could not make itself?`"
Here was a long pause.
At last one replied: "`Holy men writ as they were moved by the Holy Ghost.`"
Here was a long pause again.
"`And,`" said I, "`is this your mind?`"
"`It is the plain words of the text,`" said another.
"`Granting this, then it must, by your concession,
be allowed that the Spirit gave forth or made the Scriptures, by the medium of holy men;
therefore the Spirit gave forth the text; now judge you whether a rule made,
or the author who made that rule, be subordinate.`"
There was a pause for a little while, and one of the company said:
"`You are done! you are done!`" meaning they had lost the victory;
"`the Scriptures must be subordinate to the Spirit that gave them forth.`"
I replied thus: "`We believe, concerning the text, that it is a rule,
and the best external rule we have: but that the Spirit,
which gave it us by the medium of holy men,
is the principal rule of faith and practice.`"
Thus this debate ended.

They then debated the subjects of water baptism, and taking the bread and wine,
which held not long,
Friends showing that there was no Scriptural obligation in these ceremonies; that,
at best, these were acknowledged to be only external symbols,
and that where the spiritual substance signified by them was enjoyed,
the type was unnecessary.
Their visitors soon gave up the point, and turned to Gospel ministry,
saying they knew how their preachers came by theirs, viz.,
by learning and the authority of the presbytery;
but they wanted to know how it was among Friends.
Samuel Robinson reasoned the matter with them for some time, and then observed that,
as he was not engaged in the ministry, he would refer them, for further information,
to his brethren, who were.
A pretty long silence ensued, and other subjects of discourse were introduced,
until S. Bownas says:
"`I could no longer withhold;`" feeling a pressure on his spirit to open
to them the nature and manner of his call to that solemn work.
He began with his childhood, as follows, viz:

My father was a cordwainer, who lived by his trade of making shoes,
and died before I was a month old,
leaving my mother a small patrimony of about four pounds a year to keep herself,
me and one son more, who was about seven years old when my father died.
My mother gave me a religious education in this same way.
When I was fit to go to school, I was sent there until I was ten or eleven years old,
and then was taken from school and put to keep sheep, my earnings, though very small,
giving some assistance to my mother, who had bound my brother an apprentice.
I was kept close to attend the flock when wanted,
and afterwards put an apprentice to a blacksmith, still going to our own meetings,
but did not understand the rudiments of the religion I was trained up in,
but was addicted to the pleasures of the times.
When I went to meeting, I knew not how to employ my thoughts; and often, yea, very often,
the greatest part of the meeting, for want of a proper employment of thought,
I spent in sleeping; for the preaching, which was pretty much, I did not understand.
Thus two or three years of my apprenticeship I spent
with very little sense of God or religion.

He then related the manner of his awakening, his inward exercises,
the teachings of the Holy Spirit in his heart, his call to the ministry by this Spirit,
his obedience thereto, and growth in his gift,
the constraining power of the Almighty leading him
forth in the service of the Gospel in different parts,
the good order settled among Friends in liberating
ministers to travel from home in that work;
and producing his certificates from his brethren at home, read them,
all which seemed greatly to the satisfaction of the visitors.
The narrative proceeds:

The night, by the time this was over, being far spent,
it being some time past the middle, a reckoning was called,
and they would not allow us to pay any part thereof,
but took leave of us with great affection; and the country gentleman,
who was assisting to our liberty, gave us a very kind invitation to his house,
which we received thankfully; but being engaged in our minds for England,
had not freedom to go with him; so we parted in a very loving and friendly manner.

We being now left to ourselves, I had an opportunity to reflect on what had passed,
and to examine my whole conduct all that day; a practice I frequently used,
after a more than common day`'s service;
and indeed after every opportunity of an enlargement in my gift,
by experience finding the best instructor in my own bosom,
to show where I hit the matter or missed it.
In considering why I began so low as my father,
setting forth my manner of education and trade,
which seemed to have no relation to my call to the ministry,
I saw the reason thereof to be, that they might not think my ministry to have,
in the least, any dependence upon literature;
a qualification much depended on for the work of the ministry amongst them,
and some of them will not take any notice of any other sort; if a man,
for they will not admit a woman to have any part in this work,
be never so divinely fitted by the Spirit, yet if he want human learning,
it is all nothing with them.
Thus the wisdom of Truth, which I did not see so plainly at first,
appeared to my understanding very clearly;
and on a close and narrow inspection into this day`'s work, I found inward peace,
a joy sprang in my heart that I could not set forth by words.

I have been more particular in the relation of this
day`'s work than I otherwise should have been,
as containing in it such signal marks of Providence; first,
that we should be detained in hold, just till the people from the country were come in;
and then set at liberty to say what the Lord gave us.
And thirdly,
that we had so seasonable an opportunity to explain our practice as to the ministry,
the conduct of the Society towards them,
and likewise the service of our Monthly Meetings respecting the poor, marriages,
admonishing offenders, making up differences,
granting of certificates to such as saw cause to
remove themselves from one Monthly Meeting to another,
as well as to ministers.
Their showing so much kindness, and raising no objection to anything said on these heads,
plainly demonstrated their good liking and satisfaction therewith.

When Joseph Glaister and Thomas Story were in Virginia, in 1705,
they were challenged to a dispute by a priest named Monro.
The first point was on water-baptism.
The second was on the possibility of being made free from sin in this life.
The third was,
whether Christ ever gave power to his apostles and ministers to force a maintenance.
In treating the first and second questions, Joseph was so enabled to uphold the Truth,
that Monro was foiled, and not willing to enter on the third.
He said: "`Mr. Glaister, you are a much younger man than I am, and stronger,
and can hold an argument longer.
I confess you have a close way of reasoning, though I think I have the truth on my side,
but can hold out no longer.`"
Thomas Story says: "`Being hot weather, and he, an elderly man, grew so weary,
weak and faint, that he could scarcely be heard.`"

In a dispute which Thomas Story had with another priest a few days after,
the priest commenced with asserting,
that the Quakers never used the Lord`'s prayer in their meetings,
although Christ had commanded his disciples that they should thus pray;
and finished by saying, the Quakers are no Christians.
Thomas, in reply,
stated that although the words of that prayer were
not often repeated entire in our meetings,
yet they were frequently referred to, and explained,
and that they were sometimes repeated verbatim.
The priest said: "`I never heard you, and who else here ever did.`"
Several of the audience said: "`I have,`" "`I have,`" and a lawyer said:
"`I have heard Joseph Glaister now present, in particular, use it, and others also.`"
The priest then dropped the charge.

When Samuel Bownas was at Newbury, Massachusetts, he says:

A man who lived in that place, being newly convinced,
was very desirous of a meeting at his house, which I consented to;
and when the time came, his wife not being pleased that we came to hold a meeting,
would not permit us to enter the house, but kept the doors locked against us, being,
as was said, advised to it by some of their teachers.
I took a turn round the house,
and happened to have some conference with her at the window, first assuring her,
that we had no design to put her husband to any charge,
but only to let us have house-room for about two hours to hold a meeting, adding,
that it illy became a wife to keep her husband out of his house at such a time.
By reasoning the case with her, after a little while she opened the door,
and would have us to go in, but I had not freedom.

A place to hold the meeting was then got ready, being a large building like a barn,
and we sat down, being a few Friends, and in a little time many people came,
amongst whom, as it was said, were six preachers.
After some time a young woman stood up who had a good gift,
but the people behaved very rudely, so that it put her out of countenance,
and she sat down.
Then stood up Lydia Norton, a famous minister, none more so of that country,
who had an excellent gift, and knew how to conduct herself in it;
but all this did not avail, the people grew worse and worse in their behavior.
Lydia having a strong voice, extended it very loud, but to no purpose,
for the people were as loud as she, calling for a dram,
and sporting themselves in their folly, so she sat down.
A young man, called Joshua Paddington, then stood up; and the people behaved worse,
raking up his former faults, and calling for a can of flip,
for he could drink as well as they; he having been a companion with them in fishing,
they made very free with him, so he shut up.

By this time the meeting was exceedingly numerous, and continued enlarging very much.
It came into my mind, to stand up and take out my Bible, which I did,
for I always travelled with one in those days,
finding a considerable service in it at times.
I opened it, and put my finger on it, as though I would take my text,
but I said nothing for some considerable time, till all was quiet.
The people continued in great confusion for a while, till some of them observed my book;
then they began to still one another, urging as a reason for it,
that I had the word of God in my hand, such a great regard they paid to my Bible.

In a little time all was quiet; then I opened my mouth, and said, I am an Englishman;
and enumerated the many lands and places I had travelled in,
but had never met with any people of such a behavior as these were;
referring to them to advise me what account I must give
of the people of Newbury at my return into England.
A comely gentleman-like man said, in excuse for the behavior of the people,
"`As for women`'s preaching we hold it unlawful, because St. Paul hath forbid it,
therefore we think it not proper to give them a hearing; and as for the man,
we know him perhaps better than you, and cannot think him qualified for that undertaking;
but you seem to be a gentleman of sense, and we will hear you.`"
I replied, that as for women`'s preaching, if any of you, after this meeting is over,
are willing to hear what I have to say in favor of it,
I shall be willing to give you the best account I can, why I think it is lawful;
and if any of you can show better reasons against it, I shall as willingly hear them.
And as for the young man, I grant you may, as he is a neighbor,
have had a better knowledge of his former conduct in life, than I can pretend to;
but allowing that he may, in time past, have been loose,
that argues not against giving him a hearing; for how know you, but that as Saul did,
he might condemn his past life and give you an example, by his present conduct,
to reform;
for which reasons you ought to have heard with patience what he had to say to you.

The same gentleman replied: "`I said very right, they ought to have heard him:
but I pray you speak what you have to say freely;
and I charge all present to make no disturbance or interruption; if they do,
in the queen`'s name, I will commit them.`"
By these words I found he was in the commission of the peace.
Then I began, with saying, that religion without righteousness was useless,
and could not profit those who possessed it.
And going on,
I came in the course of my service to recite the great improvement
true religion made in the minds of those who lived in it,
by giving them power over their lusts and passions; repeating that text in James 1:26:
"`If any man among you seem to be religious, and bridleth not his tongue,
but deceiveth his own heart, this man`'s religion is vain.`"
One of the throng said: "`Sir, you impose upon us, there is no such text.`"
I made a full stop, and turned to it; and many Bibles then appeared.
I repeated chapter and verse and they turned to it.
Then I asked them, if they had it?
They replied, they had.
Then I read both the twenty-sixth and twenty-seventh verses,
and asked if it was so in their Bibles, they answered, it was.
I then desired them to consider whether I that repeated the text,
or he that said there was no such text, was most in the right.

I went on with my opening, carefully minding my guide:
and in the course of the doctrine I had in my view, I came to treat of faith,
and distinguished between true and false faith, showing,
that notwithstanding we might give our assent to
the truth of what was called the apostles`' creed,
or any other made and drawn up by men,
and might be zealous to dispute and contend for the truth of these creeds;
yet if we did not lead Christian lives, we were but unbelievers;
"`For faith without works is dead,`" as the text tells us.
At these last words one cried out: "`You impose upon us, there is no such text.`"
I immediately stopped and turned to it, and quoted it, and all who had Bibles made search.
There being a profound silence, I read the text, asking if it was so in their books?
They all replied it was.

=== Marriage

Among a people who lived in such close communion
with their heavenly Father as did our early Friends,
it might reasonably be expected that in such an important matter as marriage,
they would be especially careful to seek for the Divine guidance and blessing.
Several of them have related their experience in this matter.
When Richard Davies was a young man he settled in London, but soon became uneasy,
remembering that his native country Wales was barren
and uninhabited with Friends and Truth.
He says:

I reasoned that I was alone, like a pelican in the wilderness,
or a sparrow on the house-top.
But the Lord still commanded me to go, showing that He would provide a helpmeet for me.
I prayed unto Him that she might be of his own providing,
for it was not yet manifest to me where she was, or who she was.
But one time as I was at Horsleydown meeting in Southwark,
I heard a woman Friend open her mouth by way of testimony against an evil ranting spirit,
that did oppose Friends much in those days.
It came to me from the Lord, that that woman was to be my wife,
and to go with me to the country, and to be an helpmeet for me.
After meeting I drew somewhat near to her but spoke nothing,
nor took any acquaintance with her, nor did I know when or where I should see her again.
I was very willing to let the Lord order it as it seemed best to himself,
and therein I was easy; and in time the Lord brought us acquainted one with another.
I told her, if the Lord did order her to be my wife,
she must come with me to a strange country, where there were no Friends,
but what God in time might call and gather to himself.
Upon a little consideration, she said: If the Lord should order it so,
she must go with her husband, though it were to the wilderness.
At one time as they were waiting upon the Lord together,
she arose and declared that in the name and power of God she consented to be my wife,
and to go along with me whither the Lord should order us; and I said,
in the fear of the Lord, I receive thee as the gift of God to me.

Soon after their marriage they went to Wales.

Robert Barclay, the author of the celebrated [.book-title]#Apology#, married Christian Molleson,
a worthy young woman of Aberdeen, Scotland.
The letter in which he avowed his attachment has been preserved,
and is a remarkable document.
It was dated the twenty-eighth of First Month, 1669,
and written when he was twenty-one years of age.
It is as follows:

Dear Friend:--

Having for some time past had it several times upon my mind,
to have saluted thee in this manner of writing,
and to have entered into a literal correspondence with thee,
so far as thy freedom could allow:
I am glad that this small occasion hath made way for the beginning of it.

The love of thy converse, the desire of thy friendship, the sympathy of thy way,
and meekness of thy spirit, has often, as thou may`'st have observed,
occasioned me to take frequent opportunity to have the benefit of thy company;
in which I can truly say, I have often been refreshed,
and the life in me touched with a sweet unity,
which flowed from the same in thee--tender flames of pure
love have been kindled in my bosom towards thee,
and praises have sprung up in me to the God of our salvation,
for what He hath done for thee!
Many things in the natural will concur to strengthen
and encourage my affection towards thee,
and make thee acceptable unto me; but that which is before all and beyond all, is,
that I can say in the fear of the Lord,
that I have received a charge from Him to love thee,
and for that I know his love is much towards thee;
and his blessing and goodness is and shall be unto
thee so long as thou abidest in a true sense of it.

John Croker mentions that when he began to think of a married state,
his thoughts were turned towards a virtuous young woman, in the county of Cornwall.
He says:

I was not hasty in proceeding, but well considered it,
and laid the thing before the Lord in my heart,
desiring that if it were not the Lord`'s pleasure it should be so,
He would remove it out of my mind, or else that He would increase my love towards her,
which I found still continued with me.
But when I was retired before the Lord,
I could think of her with an abundance of sweetness,
although I had not seen her for some time,
nor ever (that I remember) had been in her company above twice,
she living at about twenty-six miles distance from me,
and I had not been more than once at their house.
So in seasonable time we accomplished our intentions of marriage,
to the good liking and well wishes of our relatives and friends,
being satisfied the Lord sanctioned our affections,
and that by his spirit we were united.

=== Decline

The Society of Friends appears to have continued increasing in
numbers in England to the close of the reign of William III,
who died in 1702.
After that time,
it would seem that there were no such large accessions to its membership
as had marked the earlier periods of its history.
For this, several reasons may be assigned:
One was the lowered condition of vital religion in Great Britain,
of which historical writers speak as a marked feature
of the early and middle part of the eighteenth century.
Of this period Green, in his [.book-title]#History of the English People#, says:

In the middle class the old Puritan spirit lived on unchanged,
and it was from this class that a religious revival
burst forth at the close of Walpole`'s administration,
which changed, for a time, the whole tone of English society.
But during the fifty years which preceded this outburst,
we see little save a revolt against religion and against
churches in either the higher classes or the poor.
Among the wealthier and more educated Englishmen, the progress of free inquiry,
the aversion from theological strife, which had been left behind them by the civil wars,
the new political and material channels opened to human energy,
were producing a general indifference to all questions
of religious speculation or religious life.
In the higher circle "`every one laughs,`" said Montesquieu, on his visit to England,
"`if one talks of religion.`"
Of the prominent statesmen of the time,
the greater part were unbelievers in any form of Christianity,
and distinguished for the grossness and immorality of their lives.
Purity and fidelity to the marriage vows were sneered out of fashion.

The masses of the poor were ignorant and brutal to a degree which it is hard to conceive;
for the increase of population which had followed on the growth of towns,
and the development of commerce,
had been met by no effort for their religious or educational improvement.
The rural peasantry were left without much moral or religious training of any sort.
Much of this social degradation was due to the apathy and sloth of the priesthood.
Bishop Burnet brands the English clergy of his day as the most lifeless in Europe,
the most remiss of their labors in private, and the least severe of their lives.

It was but reasonable to expect that the Society of Friends would be, to some extent,
affected by the causes which operated on the other inhabitants of England.
In Abbey and Overton`'s [.book-title]#History of the English Church in the Eighteenth Century#,
it is said the "`Sect throve under persecution;`" and "`between the passing
of the Toleration Act and the end of William III`'s reign,
it made great progress.
After that it began gradually to decline.
This was owing to various causes.
Some share in it may, perhaps,
be attributed to the continued effects of the general
religious lethargy which had set in some years before,
but may now have begun to spread more visibly among the
classes from which Quakerism was chiefly recruited.`"
"`It may be added that, as the century advanced, there gradually came to be,
within the confines of the national church,
a little more room than had lately existed for the upholders of various mystical tenets.`"
Although the authors of the work from which I am quoting,
thus refer to the spiritual views of Friends as "`mystical,`" yet,
in the remarks which follow,
they show that they were not insensible to their truth and importance.
They speak of the faithful witness borne by the Quakers to the "`sense of a present
life-giving Spirit,`" when it was "`feeblest and most neglected elsewhere.`"
And they add:

If Quaker principles, instead of being embodied in a strongly antagonistic form,
as tenets of an exclusive and often persecuted sect,
had been transfused into the general current of the national religious life,
they would have contributed the very elements of which the
spiritual condition of the age stood most in need.
Not only in the moderate and constantly instructive
pages of [.book-title]#Barclay`'s Apology for the Quakers#,
but also in the hostile expositions of their views,
which we find in the works of their opponents,
there is frequent cause for regret that so much suggestive
thought should have become lost to the Church at large.
The Church would have gained in power, as well as in comprehension,
if their views on some points had been fully accepted
as legitimate modes of orthodox belief.
English Christianity would have been better prepared
for its formidable struggle with the Deists,
if it had freely allowed a wider margin for diversity of sentiment
in several questions on which the Quaker opinion almost universally
differed from that of the churchmen of the age.

They had been among the first to turn with horror from those
stern views of predestination and reprobation which,
until the middle of the seventeenth century,
had been accepted by the great majority of English Protestants without misgiving.
It was doctrine utterly repugnant to men whose cardinal
belief was in the light that lighteth every man.
The same principle kept even the most bigoted among them from falling
into the prevalent opinion which looked upon the heathen as altogether
without hope and without God in the world.
They, almost alone of all Christian missionaries of that age,
pointed their hearers to a light of God within them which should
guide them to the brighter radiance of a better revelation.
Nor did they scruple to assert that "`There be members of this Catholic Church,
both among heathens, Jews and Turks, men and women of integrity and simplicity of heart,
who, though blinded in some things of their understanding and burdened with superstition,
yet being upright in their hearts before the Lord&hellip; and loving to follow righteousness,
are by the secret touches of the holy light in their souls, enlivened and quickened,
thereby secretly united to God,
and thereby become true members of this Catholic Church.`"^
footnote:[[.book-title]#Barclay`'s Apology for the Quakers#.]
Such expressions would be generally assented to, in our day,
as embodying sound and valuable truths,
which cannot be rejected on account of errors which may sometimes chance to attend them.
At the beginning of the eighteenth century there were few, except Quakers,
who were willing to accept from a wholly Christian point of view the element of truth
contained in the Deistical argument of "`Christianity as old as the Creation.`"

When Quakers found that its more reasonable tenets could be held,
and find a certain amount of sympathy in the Church of England,
it quickly began to lose its strength.
A remark of Boswell`'s, in 1776, that many a man was a Quaker without his knowing it,
could scarcely have been made in the corresponding year of the previous century.
At the earlier date there was almost nothing in common
between the Church of England and a sect which,
both on its strongest and weakest side,
was marked by conspicuous antagonism to established opinions.
At the latter date Quakerism had, to a great extent,
lost both its mystic and emotional monopolies.
After a few years`' hesitation,
Southey concluded that he need not join the Quakers simply because
he disliked "`attempting to define what has been left indefinite.`"

The testimony borne in the preceding extracts to the spread in the community of some
of the principles advocated by the Society of Friends is interesting in itself,
as an illustration of the remark that has often been made--that
among professors of Christianity there has been a gradual approach
to the spiritual views of religion held by early Friends.
And it is very possible that it has been one of the causes
which have hindered the increase in the number of its members,
as suggested in the above extract from Abbey and Overton`'s work.

John Hunt, in his history of [.book-title]#Religious Thought in England#,
speaks of the rise of the Quakers as a recoil against mere ceremonial:

The steeple-houses against which George Fox cried out as temples of idol-worshippers,
were the churches of England when in possession of Presbyterians,
Independents and Baptists.
They had cast down Laud and his priests.
They had rejected them and their pretensions to be channels
of grace and conduit-pipes of the Divine favor,
but these sects were still clinging to the dead letter of a book.
They were still trusting in ordinances,
to some extent unconscious how much they were retaining of what
they really supposed they had rejected when they put down the bishops.
The church was their idol-temple, and the Bible the idol which they worshipped.
"`We have a sure word of prophecy,`" said the minister of the church at Nottingham;
"`it is the Scriptures by which all doctrines, religions and opinions, are to be tried.`"
George Fox was present.
He cried out: "`It was not the Scriptures,
but the Holy Spirit by which holy men of God gave forth the Scriptures, whereby opinions,
religions and judgments are to be tried.`"
That Spirit, he said, leads into all truth.
The Jews had these Scriptures, and yet resisted the Holy Ghost.
They rejected the "`Bright and Morning Star,`" and persecuted Him and his disciples.
They professed to try their doctrines by the Scriptures,
but they did not try them aright, because they did it without the spirit of God.

This error of trusting to the mere letter of the Bible,
Fox detected in every detail of belief and practice.
There might be external worship in the Church; there might be preaching, sacraments,
sacrifices, but what are these if there is no Spirit in them?
God dwells not in temples made with hands.
It is not the water baptism which saves, but the answer of a good conscience.
It is not ceremonies which justify, nor even belief in an external Christ.
It is Christ within who is to us both justification and sanctification.
The battle of the Quakers was for the reality against the shadow,
for the substance at the expense of the form,
for the law in its Spirit even at the risk of sacrificing the law in the letter.

The Journals and writings of faithful members of the Society of Friends,
in the early part of the eighteenth century,
show that they were very sensible of a falling away from the zeal
and earnestness which had previously been marks of Friends.
Deborah Bell, of London, in 1717, writes to Joseph Pike,
that a living ministry is almost lost amongst us.

In 1731, Thomas Story mentions being at Bristol, where he said:
"`There are two great meetings of Friends; but the greatest part being young,
many of them are hardly distinguishable from the world by any outward appearance,
either in speech or habit.`"

Some of the Lord`'s servants have been favored with a sense
that a renewed visitation of Divine Grace would be extended.
The following was expressed by Ann Jones in Stockport meeting,
the twenty-eighth of First Month, 1841:

A salutation of encouragement springs in my heart this morning to the mourners present,
the tried, the proved ones;
to some who may be said to be the Lord`'s poor and afflicted children,
for such there are in this company I do believe;
and although it is a day of discouragement and treading down in our poor, scattered,
backsliding and worldly-minded society, yet I would say to these,
Cast not away your confidence,
cast not away the shield as though it had not been anointed with oil,
for I have seen a brighter day that is about to dawn;
and though I may not see it with the natural eye,
yet I have seen it in this meeting in that which cannot deceive,
and never has deceived me.
And I do believe a brighter day is approaching;
for the Almighty will have a people professing as we do,
that will show forth his praise to the nations,
and He will yet overturn the wisdom of the wise,
and will bring to naught the counsel of the prudent, and show himself to be God over all,
blessed forever.
He will work, and who shall hinder?
bringing forth as He did our early predecessors and forefathers in the Truth,
from all the "`lo here`'s`" and "`lo there`'s`", out from amongst the world`'s people,
from the will and wisdom of man, living in the faith of the Gospel,
not in their own righteousness but in the righteousness of the saints.
And if some present who love the Lord Jesus Christ
in sincerity and are afraid to offend him,
are but willing to abide in the patience and the faith,
this language will assuredly be fulfilled in their experience, "`I have refined thee,
but not with silver;
I have chosen thee in the furnace`"--and if willing to abide therein,
they will come forth as fine gold, bearing the inscription of holiness to the Lord,
as prepared and qualified vessels sanctified and fitted for the Master`'s use,
sent to preach among the nations the unsearchable riches of Christ.
These will be permitted at times to sit under his shadow with great delight,
and his fruit will be pleasant to their taste;
you who are hungry and thirsty will have to come to the waters,
and he that hath no money may come and eat that which is good;
and let your souls delight in fatness, for his hand is full of blessings,
and in the Lord Jehovah is everlasting strength, for the Lord God Omnipotent, Omniscient,
Omnipresent, reigneth over all.

A letter from Oliver Paxson, of New Hope, Pennsylvania, dated Ninth Month, 1803,
contains some profitable remarks on a gradual declension
in the Society of Friends in this country.
It says:

Soon after the close of the French war,
there was a considerable advance in the price of country produce;
Friends began to add house to house, and field to field;
places of business were enlarged; to accommodate which,
recourse was had to hired or bought servants, often of bad characters,
and these mixed with Friends`' children; with which, other circumstances combined,
such as the keeping two fires in one family, perhaps two tables, etc.,
and thus eagerly pursuing the things of this life,
opportunities of solid retirement became less frequent,
and not so much zeal in getting young people to week-day meetings;
for we had not only First-day morning and weekday meetings, but in summer,
meetings in the afternoon of First-days; also, Quarterly, Monthly, General,
and Youth`'s meetings; all of these, since my time,
were strictly attended by faithful Friends.
But as the desire of outward gain increased, those meetings,
particularly in the afternoon, became burdensome;
and parents began to go themselves in the morning,
and send their young folks in the afternoon.
This gave rise to complaints of disorder among the youth; and, to remedy these,
the language was, among the active part of Society, "`lay them down;
for they are rather places of corruption than improvement.`"

On this occasion, my mouth was first opened in meetings of discipline,
in support of them; for I could recollect the sheds, the shades, the schoolhouses,
and other places, where my soul had very memorable baptisms.
But down they went, and in a while the Youths`' meetings,
and most of our General meetings, were also laid down.
"`The love of money`" is indeed "`the root of all
evil,`" when the gift is preferred to the Giver.
The wonderful lengths many of our Society have gone in commerce, some in land,
some in trade to sea; and, shall I say,
some in English horses;--too little of the "`yea`" and "`nay`" amongst us in our traffic,
and intercourse in the world.

=== Dreams

The importance of being preserved in a state of humility is shown by the following anecdote.
A ministering Friend residing in England,
under a religious concern paid a visit to the meetings
in Ireland in which service he was eminently favored.
In his meditation, after his return home,
on the evident Divine influence attending his ministry, spiritual pride crept in,
while in this critical condition he was instructed by a dream.
He thought he was walking on a plain,
reflecting on his late visit to Ireland--the wonderful service he had
had there--and exulting in his increase of spiritual experience.
As he was thus engaged, he perceived a person of lofty stature approaching him.
Full of presumption he advanced to meet the new-comer, and demanded his name:
"`My name is Self,`" said the giant.
"`Well,`" added the other, "`I will kill thee.`"
He thought in his dream that he immediately commenced the attack,
and after a sharp contest, succeeded in beating Self to death.
He then renewed his walk, and in addition to his former cause of inward gratulation,
he now with much satisfaction thought over his last valorous exploit.
Whilst thus engaged,
he beheld approaching a figure closely resembling the giant he had just killed,
but of more than twice the size.
As this majestic person drew near,
he was met with the same question which had greeted the other--"`Who art thou?`"
"`I am Self,`" was the answer.
"`I thought I had killed thee,`" said the puffed-up preacher, "`But I will do it again.`"
So saying, he vigorously assailed this formidable enemy,
and after a very severe and desperate struggle, succeeded in destroying him.
Now again he began to meditate on his great deeds; when he saw before him a person,
featured as the two others, but of immense stature, his head reaching to the clouds.
He approached, and to the demand of his name, was answered, "`I am Self.`"
Once more a combat commenced;
but it was soon apparent that this new giant was coming off victor.
The poor crest-fallen dreamer was brought to the ground, and perceived as he thought,
his death inevitable.
Then indeed, he thought of One,
whose arm of power could bring aid and safety in any difficulty.
His heart seemed humble, secret prayer was begotten to the Source of strength,
his faith was renewed, and Self vanished.
Then ended his dream.
As he pondered over its different parts, the delusion he had been previously under,
was made clearly manifest to his mind.
In tears and true contrition of heart he looked to
the Source of every good and perfect gift,
and received therefrom a renewal of that humility and fear,
which in the days of his youthful visitations were given to him.

Isaac Horner had been much troubled by the course of his son Samuel,
who had finally entered the army.
Yielding to these anxieties he became much depressed,
and his nervous condition awakened the anxieties of his friends.
One morning his daughter, Elizabeth Watson,
informed him she had on the previous night a remarkable dream, which she related to him.
The narrative has been preserved seemingly in the words of the dreamer:

Methought I was standing in a large and stately mansion,
amidst an immense throng of people moving about with noise and bustle,
and while gazing about me in wonder,
I was informed that this was the entrance to the infernal regions,
and that hell was beneath me.
I fled in terror, escaped from the building,
ran across a large field and halted for breath on
a style that crossed the fence on the farther side;
when a person approached and presented me with something in the shape of a cross,
bidding me calm my fears and assuring me that while
I preserved that cross no harm could befall me,
and that I might return in safety.
Prompted by curiosity I again entered the building,
and being invited to enter the lower regions, I proceeded, holding fast to my cross.
As I entered, Satan himself came forward, fawning and cringing,
paying the greatest attention, and escorting me through the place.
There, much to my horror, I saw many persons in torment, some of whom I recognized.
At one time, hearing a terrible noise, I inquired the occasion of it,
and was told that a very bad man was coming below, whose name was mentioned.
While terrified at these things I became less watchful and unfortunately lost my cross.
In a moment all was changed, Satan sprang at me with fiend-like fury, tore out my heart,
and held it quivering in his hand.
For a time I felt all the horrors of the damned.
Just then,
while the eyes of the devil were off me as he was placing my heart in safe keeping,
I gazed around me in despair,
and espied my cross lying unnoticed on the ground at some distance:
with a desperate effort I seized it, and in a moment was made whole as before,
with the fiend bowing and cringing at my side again.

Among other questions put to me by Satan, he inquired:
"`What sort of a man is your father?`"
I replied: "`He has been pious from his youth.`"
"`So I have heard,`" he replied, "`but I have hopes of him yet.`"
After the recovery of my cross I made my escape as soon as possible.

Isaac Horner listened with profound interest to this
narrative as it fell from the lips of his daughter,
and on hearing that Satan had hopes of him yet, he started up exclaiming:
"`Has he so! but I`'ll cheat him;`" and from that time he became
effectually roused and restored to his strength and energy of mind.
The record adds that the man whose name was mentioned as being
introduced to the abodes of darkness was a well-known neighbor,
who it was found had died that night.

Amongst those members of the Society of Friends in Ireland, who, about the year 1720,
had turned their minds to the consideration of removing to America, was Isaac Jackson.
He had a family of children growing up around him, and his thoughts were often upon them,
and their future settlement in life.
He did not wish to take them to a new country,
even though it offered many advantages over those they could hope for where they were,
unless it should be according to the will of his heavenly Father.
Both he and his wife had this subject much on their minds,
being deeply exercised that they might know what their duty in this manner was.
Whilst Isaac was still undecided, and his mind full of earnest thought,
he was favored with a remarkable dream, which he believed was providential,
and which had the effect of convincing him that his removal to America was in the ordering,
and would be with the approbation of Him,
who still leads his humble dependent children even in temporals,
in the paths wherein they should go.
The dream is thus described in the record made of
this circumstance by one of Isaac`'s descendants.

Whilst they +++[+++Isaac and his wife]
were under exercise and concern of mind, about so weighty an undertaking,
and desirous that best Wisdom should direct, Isaac had a dream or vision, to this import.
That having landed with his family in America,
he travelled a considerable distance back into the country,
until he came to a valley through which ran a pretty stream of water.
The prospect and situation of the place seemed pleasant; a hill rising on the north,
and a fine spring issuing near its foot;
and in his dream he thought that there he and his family must settle, though +++[+++it was]
then a wilderness and unimproved.

This dream seemed accompanied by a Divine unction which
satisfied him that it was right for him to remove to America;
and in 1725 he came over to Pennsylvania.
Soon after his arrival he went into the country,
to seek for a place wherein he and his family might settle.
In the course of his travels he came to the house of Jeremiah Starr, a Friend,
who in 1720 had settled in the wilderness in that part of
Chester County known now as Londongrove township.
During conversation at this Friend`'s house, Isaac related his dream;
and when he had described the beautiful spring, the up-rising hill behind it,
the lovely valley spreading out before it,
which even the forest which clothed it could not hide,
he was told that a spot just such as he described was nearby.
In the words of the account from which we have already quoted: "`He soon went to see it,
which to his admiration so closely resembled what he had a foresight of,
that it was cause of gratitude and humble thankfulness.`"

He purchased the spot,
and there in Harmony Valley his descendants reside at this present day.
The valley spreads out now in beautiful greenness,
and the pure water of that spring continues as refreshing as in
the day when it bubbled out in the shade of the primeval forest.

Samuel Fothergill, at a Quarterly Meeting in the North of England,
narrated the following anecdote:

He had called to visit an elder of the Society, on his deathbed,
and found him in great trouble and anguish of spirit.
He was a man who had borne a good character among men, and in the days of his youth,
had been zealous in the discharge of the duties devolving on those
who are rightly called to the station he held in the church.
As he grew older the ardor of his devotedness had declined, yet,
as he retained the form of godliness,
his estimation in the judgment of his fellow members was not materially affected;
but now, on his deathbed, the good opinion of others could not satisfy his soul,
on which a horror of great darkness rested.
He told Samuel that in the days of his youth he had a vision,
in which was represented a well-enclosed field of green pasture,
well watered and abounding in flocks of sheep.
They were in excellent condition,
and remarkable for the whiteness of their fleecy coverings.
This fold he was to watch over.
He was to care for the flock, see after the hedge,
and keep the fountain head of the water clean.
Now, in his old age, he had had the vision renewed.
He had again beheld the fold committed to his care; but oh! the awful change.
The hedge was broken down, the pasture was burnt up,
and the sheep and lambs who remained in the enclosure were poor, weak, and sickly,
and a venomous serpent lay in the fountain and poisoned the water.
While he considered the change, he heard a voice saying:
"`All this will I require at thy hand.`"

After narrating this,
he told Samuel that in looking to the future he could see nothing but gloom and darkness.

=== Power in Ministry

There are many references in the records of the Society of Friends to
the remarkable power that attended the ministry of some of its early members.
Richard Hubberthorn in writing to Margaret Fell from London in 1658, says:

The Lord is gathering in many in this city daily; there are many meetings full and large,
where there is any to declare the Truth amongst them;
and they that are great in the earth, the power of Truth shines through them,
and is drawing them in daily.
The priests confess that there is such a power amongst us,
that none who come to us can escape; and they exhort people not to come to us.

The ministers among Friends were conscious that their
success depended on the extension of this power,
and therefore were careful to move under its influence.
Of this Thomas Wilson gives an instructive example.
He was paying a religious visit in Ireland,
when he felt the motion of life in him for travelling to cease,
and he durst go no further,
but felt that he "`Must wait on the Lord to know his blessed will
and good time,`" so he employed himself in harvest work,
until the way again opened to go forward in his religious service.

The experience of all ages has shown that whatever strongly affects the mind,
often acts on the nerves and muscles of the body.
It was therefore a thing to be expected,
that outward trembling and nervous agitation should
accompany the convicting power of Divine grace,
which attended the ministrations of the early preachers among Friends.
John Banks says, that when he attended a meeting of Friends at Pardshaw,
"`The Lord`'s power so seized upon me in the meeting,
that I was made to cry out in the bitterness of my soul,
in a true sight and sense of my sins, which appeared exceeding sinful;
and the same day as I was going to an evening meeting,
I was smitten to the ground with the weight of God`'s judgment for sin and iniquity.`"

Thomas Wilson also relates, that, on one occasion:
"`The Lord`'s power arose in the meeting, and fell mightily upon me,
to the breaking and tendering of my heart, and a glorious time it was,
as the mighty day of the Lord; so that great fear and trembling seized me,
insomuch that the table whereon I leaned, was shaken.`"
Such experiences seem to have been very frequent;
and it was owing to these that Friends became known by the popular nick-name of Quakers.
In 1655 George Fox published a paper to those who made a scorn of quaking and trembling.
In this he shows by the testimony of the Scriptures that the prophets
and holy men of old trembled at the power of the Lord;
the apostle Paul, when he came among the Corinthians,
was with them "`In weakness and fear and much trembling
that their faith might not stand in the wisdom of men,
but in the power of God;`" in that power which made him to tremble.
This power, George Fox tells them,
it is that the world and all the scoffing teachers scoff at and scorn;
so that they that witness trembling and quaking wrought in them by the power of the Lord,
can scarce pass up and down the streets, but with stones and blows, fists and sticks,
or dogs set at them, or they are pursued with mockings and reproaches.

Similar results have generally been seen where any intense
and long continued feeling affected the public mind.
The Christian can rejoice at anything which shows
the operations of God`'s power on the heart of man;
but it must not be forgotten that such physical manifestations
are not a certain proof of the exercise of that power,
because they may be produced by anything which deeply affects the mind, or may be,
and often are, the effects of nervous sympathy,
and are symptoms of disease more than of grace.

Our Saviour gave us a test of the value of professed conversions when he told his disciples,
"`By their fruits shall ye know them.`"
Unless the converts manifest by their godly,
self-denying lives that they are really living under
the government of the spirit of Christ,
but little or no good will be accomplished by their
participating in the excitement of a revival.

Our early Friends did not build much upon these unusual outward phenomena,
but their writings abound in exhortations to a holy life and conversation.

A writer, commenting on such scenes, judiciously remarks:

The excitement that at times pervades great throngs of people and crowded meetings
is as merely physical as are the effects upon the muscles of the human body,
which have at times accompanied it.
The stimulation of religious emotion by arrangements of this kind is a
means to which religionists of all classes--pagans as well as Christians,
and Roman Catholics as well as Protestants--have had recourse.
But "`that which is born of the flesh is flesh;`" and the magnetic force
which pervades crowded assemblies is but a refined sort of intoxicant,
which no transmutation of forces will ever convert into spiritual energy.
Like all merely natural forces, and unlike those which are of the Spirit,
it is followed too often by a powerful reaction resulting in torpidity
and deadness as great as that out of which its subjects had been awakened.
An experience of this sort must be exceedingly injurious to the person who undergoes it.

The experience and observation of many have confirmed the truth that a deadening reaction
generally follows times of nervous excitement of those who partake of the emotions that
prevail in crowded revival meetings and are numbered among the converts.
It is often the case that a large proportion, as the excitement subsides,
fall back into their old ways, and show no real change of heart and life.
The whole process has a hardening effect upon them and renders
them less susceptible to the convictions of the Spirit.
It also has a hurtful influence on the community in which they live,
tending to produce the impression that religion is little more than a nervous excitement,
and its professors either weak-nerved or deluded people.
Nothing but the grace of God, the spirit of Christ operating on the heart,
can effectually change a man, redeem,
sanctify and make him a fit temple for the indwelling of Christ.
It is the continued extension of this Divine Grace
which keeps him from again falling into sin,
and finally establishes him as a pillar in the house of God, which shall go no more out.

It is good to be zealously affected in a good cause.
And there is no better cause than turning men from darkness to light,
from the power of Satan to God.
But in this work we should bear in mind that it is only as the Spirit impels,
leads and qualifies:
in other words--uses man as an instrument--that he can labor successfully.

A marked characteristic of the business meetings of the Society
of Friends has ever been their distinctively religious character.
The advice of George Fox:
"`Hold all your meetings in the power of God,`" applied
to these as well as to those designed only for worship.
In the establishment of these meetings,
he claimed to be influenced by the same Divine command which, at an earlier day,
had sent him forth to proclaim the doctrines of salvation.

The testimony of Robert Barclay is to the same import: "`We can boldly say,
with a good conscience in the sight of God,
that the same Spirit which leads us to believe the doctrines and principles of the Truth,
and to hold and maintain them again, after the apostacy,
in their primitive and ancient purity,
as they were delivered by the apostles of Christ in the Holy Scriptures; I say,
that the same Spirit does now lead us into the like holy order
and government to be exercised amongst us as it was among them.`"

From this view of the nature of meetings for discipline,
it was a natural consequence that,
in the management of the business which came before them,
the members were governed by the impressions on their minds,
which they believed to come from the Head of the Church,
and not by efforts of their own reasoning powers.
An illustration of this may be found in the Journal of Richard Davies,
who mentions that at a Quarterly Meeting where he
had exhorted Friends to the observance of the order,
then recently introduced,
of holding men`'s and women`'s meetings for the care of church matters, some one,
who was opposed to these meetings, opposed what he had said.

When he had done, our friend, Thomas Ellwood,
proposed to the meeting that all should sit down
and wait to feel the power of God among us,
and let that decide whether I did speak in the name and power of God among them this day;
to which the meeting agreed, and all were silent.
After which, several Friends, as they were moved by the Lord,
gave tenderly their testimony that what was delivered
that day was in the name and power of God.

There stood up a young man that I knew not, whose heart was affected,
and much broken in spirit, and said on this wise:
"`There is a man come this day amongst us,
I know not from whence he came nor where he goes; but this I am satisfied,
the Lord sent him here,
and his power and presence is with him and his testimony for the God of Truth.`"

In the early days of our Society the young and inexperienced were not expected
to attend meetings for business--but only those who were so far advanced in spiritual
growth as to be able to discern what was in accordance with the Divine will.
_A Testimony, or Epistle_, sent out by the brethren in London in 1666, says:
"`We advise that not any be admitted to order public business of the church
but such as are felt in a measure of the universal Spirit of Truth.`"
It appears to have been the practice for young Friends not
to attend such meetings until invited by the older members.
Joseph Pike mentions his own experience:"`When about twenty years of age,
I was invited by Friends to be a member of the men`'s meeting in Cork,
at which time I was under a religious exercise of mind.
My conversation was sober, and my exterior plain,
according to Truth--all which drew the love of Friends towards me.
I thought myself very unworthy, being low and weak in mind,
thinking I could do them no service; but hoping to receive some benefit myself,
I did with fear and caution accept their offer,
and sat among them some years before I presumed to speak much to what came before them.
Yet I joined in heart and soul with those who were exercised for the Truth;
and as I grew more and more concerned for its prosperity, when occasion offered,
I spake more to subjects in meetings.`"
After some further remarks on the subject, Joseph Pike expresses his judgment,
"`That the affairs of the Society cannot be conducted in the unity of
the Spirit without due care be taken in the admittance of qualified members.`"
In accordance with this view, in 1740, a query was adopted,
to be answered by inferior meetings:
"`Is care taken that no unfit persons sit in meetings for discipline?`"

William Edmundson, in an epistle _Concerning Men`'s and Women`'s Meetings_, says:
"`It is of absolute necessity for all the members to know in what
authority they sit in those meetings--for the service thereof must
be performed in the wisdom and counsel of the Lord Jesus Christ,
and in the authority of his blessed Spirit and power.`"
"`In all such meetings about the Lord`'s business, the Lord must be chairman,
ruler and judge--for it is in the gift of the Lord`'s good
Spirit that the ability stands to perform that service.`"

It would be easy to multiply similar testimonies.
Since the principles of our Society require the decisions of its
meetings to be based upon the judgment of the Spirit--this judgment,
whether it speaks through few or many, must be acquiesced in by the others.
Hence, as Robert Barclay states, Friends do not decide by pluralities or majorities.
The question as to deciding by votes,
was prominently brought forward in the course of
the trial of a cause in the New Jersey Court of Chancery,
involving the rights of Friends and of the Hicksites
to a school fund about the year 1830.
The first witness examined on behalf of Friends was Samuel Bettle, Sr.,
who made the following statement:

Our mode of deciding questions is peculiar.
It is intimately connected with our religious principles and doctrines;
when an individual or a religious assembly is gathered into a reverent, inward,
waiting state of mind,
we are sensible at times of the presence of the invisible and omnipresent
One--qualifying the heart for secret communion and approach unto God.
Hence, the Society believes,
and it is one of their peculiar and distinguishing doctrines,
that there may be secret approach to and worship of God,
without any ceremonial outward act or service; and in our meetings for business,
we also hold that it is needful to experience the same power to qualify
us for right discernment and to restrain our own spirit and will;
and we do believe that when our meetings have been thus in degree influenced,
there have been wisdom and judgment better than our own;
consistent with the prophetic declaration respecting the blessed Head of the Church,
that "`He should be a Spirit of judgment to those who sit in judgment.`"
With these views, and a corresponding practice,
our Society has been favored to come to its decisions
and conclusions at its various meetings,
with a remarkable degree of harmony and unity.
These conclusions, thus prevailing in a meeting, or, in other words,
this sense of the meeting, is often attained to with very little expression;
and the member acting in the capacity of clerk records this sense,
feeling or conclusion of the meeting.
And it has never been come to by a vote, or the opinion of the majority;
no question is ever taken by a reference to numbers, or votes, or a majority,
or anything like that.
It is obtained upon religious principles, which we understand very well,
but which it is difficult to explain.
We have got along in this way for near two centuries very well.

In reply to a query, whether, by the ancient practice of the Society,
the young and inexperienced are permitted to take
part in the transaction of the business of the meetings,
Samuel Bettle stated that in ancient times the young did not attend those meetings,
unless specially invited to do so;
but that the present practice is to admit all who choose to come.
This change of usage has been made with the hope that the attendance of these meetings,
and witnessing the religious exercise of those on whom the services of them rested,
might have a useful influence over the younger members,
and tend to prepare them for taking a part in the business of the Church.
This could scarcely fail to be the effect if, as Joseph Pike said was the case with him,
they "`joined heart and soul with those who were exercised for the Truth.`"
