== Chapter XIX. Letters

Among the letters preserved in the annals of the
Society of Friends are some so lively and interesting,
that it seems best to reproduce them here.

At the time Samuel Fothergill was preparing to sail for England,
having finished his religious service in this country,
Ellen Evans wrote the following letter to his sister Ann:

Sixth Month, 1756.

Though I am a stranger to thy person, yet not so to the good character thou bears,
therefore I find freedom to send thee a recital of
the prophetic warning of approaching trials,
which was delivered to a large auditory,
at the time of our Quarterly Meeting at Philadelphia,^
footnote:[Held Eleventh Month, 1754.]
by thy brother, soon after his arrival,
when not so much as a hand`'s breadth of cloud appeared over our land.
But in a short time a storm arose,^
footnote:[Indian massacres and the French war.]
and fell heavy on many within our borders.
As the subject was solemn, so was he quite great in the delivery of it,
which was to the following effect, viz: A holy commemoration of God`'s kind dealings,
formerly and latterly, to this our thriving colony; aptly comparing it to the vineyard,
the Lord thereof had in a very fruitful hill, which, after clearing and fencing,
he planted with the choicest vine;
such indeed were the first inhabitants of Pennsylvania, men of excellent talents,
both natural and Divine; when, looking for fruit, behold it brought forth wild grapes.
He then queried, what more could have been done for a people than had been done for us?
He besought us to consider what fruit we were bringing forth?--if sour grapes,
we might expect the fence should be taken down, and we trodden and laid waste;
signifying that such would be our case,
if not prevented by timely repentance and amendment of life.
Such, indeed, was the force of Divine evidence which attended him,
that Friends`' minds were seized with awful dread, and had to say to each other,
after meeting: Is this the last warning we are to receive?
It seems so like that of Jeremiah to the Jews, just before the destruction of Jerusalem.

The first time I had an opportunity to hear him, I thought he flew high,
even to the third heaven; when a pang of slavish fear took me,
and I had liked to have wished him there for good and all; that is,
safe in his heavenly mansion; but I was stopped,
and bidden not to pray that he should be taken out of the world,
but to breathe for his instruction in it; which I did, with all the little ability I had.
But when I had opportunity to observe his humble, watchful conduct,
like one always walking in fear, my fear, before mentioned, was entirely removed.

He is now going to leave us, who are so nearly united to him,
that bidding him farewell seems a heavy task to me and mine.
A sweet flow of Divine love which frequently passes through his heart to his auditory,
endears him to all, both saints and sinners.

There is a fine company of them going together.
Those precious ministers, Mary Peisley and Catherine Payton,
whose services were great in these parts of the world, and also our dear ancient Friends,
Abraham Farrington and Samuel Emlen, Jr.

As love for a long time hath been grown in my heart to thy worthy father, who,
of all men, struck the deepest impressions, in a religious sense, on my mind,
so it is matter of rejoicing to me to hear of the welfare of his family.
I often do believe God has a peculiar regard to the seed of the righteous; such,
dear friends, you are.
May the blessing of your father`'s God rest plentifully on all your heads.

Accept the love of one of thy father`'s old friends,

Ellen Evans

When information of the removal from the church militant
of John Evans reached Samuel Fothergill,
he felt bound in spirit to address an epistle of tender sympathy
and love to the bereaved Ellen (the author of the above letter),
and of exhortation and encouragement to her children.

Warrington, Second Month 4th, 1757.

That affectionate regard which Truth itself raised mutually in our hearts,
is by no means impaired.
Often, very often, since I left your land, has it been strongly revived,
and more especially so upon receiving the sorrowful
tidings of the removal of thy dear husband,
a circumstance in which the affliction is, like the loss, very extensively felt.
Thou mournest the loss of a tender husband; his children that of an affectionate father;
the church laments a pillar removed from the place it filled,
at a time when such are greatly wanted; a sorrow allowable,
for the perfect Example of every virtue, even Jesus, wept for Lazarus!
This nature demands, when its connections are broken,
and the endearing social ties dissolved.
But thou well knowest, and I hope it now stands thee instead,
that we are all pilgrims and strangers as our fathers were,
each journeying on through this region of distress,
towards that city which hath foundations.
Why should we grieve too much when a companion with whom we have travelled many dubious,
anxious steps, has an entrance granted him into the holy city, a few moments before us,
and enjoys consummate felicity,
whilst we stand at the door and wait for the same fruition,
of which at times we receive the earnest?

Upon all the glory of the earth, and all its enjoyments, upon every visible thing,
one inscription is written, as the immutable law and determination of Him,
whose name is the Most High; "`They shall perish.`"
Throughout all nature and natural connections, however endearing,
it has been and must be verified.
Equally fixed is the subsequent truth, the joy and song of many generations,
"`but thou remainest.`"
On this everlasting Husband, Father, Friend, and Succour, may thou and thine now lean,
and know this dispensation sanctified and blessed to all your help,
in renewing diligent care to live and move, that when the great Shepherd shall appear,
and all his faithful servants with Him, your portion may be among them forever.

The following letter was written by Samuel Fothergill,
to a young man who had gone astray, and for whose welfare he was deeply interested:

To Joseph Baker, Jr.

A degree of anxious concern for thee induces me thus to address thee;
and from the warmth of an affectionate heart, to open something for thy consideration,
to which thy temporal and eternal welfare require thy attention.
Notwithstanding many of our youth, and thyself among others,
have despised the simplicity of a plain appearance like Friends,
yet I am satisfied from the neglect of that distinction being maintained,
they and thou have been laid open to the seducements of that destroying enemy,
who hath great power over the inhabitants of the earth,
and then have leaned to an earthly spirit.
Thou hast fatally found the truth of this remark.
If thou hadst appeared like a religious, sober Friend,
those companions who have exceedingly wounded thee,
durst not have attempted to frequent thy company.
Thou seest H. F.; his conduct and appearance are consistent and sober;
none of those wicked young men dare approach him, such is the dignity of religion,
and its superiority over vice and folly.
I mention him, not from any partial regard for him as my kinsman,
but as a person I have had frequent opportunities to remark.
Thou knowest the esteem he has justly obtained, his usefulness in his father`'s family,
and that he is more justly honored than I think any young man in town.
I mention him, not to upbraid thee, but to instruct thee; his manners are virtuous,
his mind serene and peaceful; the contrary thy own experience will tell thee,
hath been thy lot, and it results from a conduct opposite to his;
nevertheless I am persuaded the regard of Divine
Providence is not totally withdrawn from thee;
His mercy is extended to recover thee, as from the gates of hell,
and pluck thee as a brand out of the fire.

My concern for thee, the kind reception thou hast met with at +++_______+++,
and the disposition of the worthy Friends there in receiving thee,
are to me proofs of the interposition of a Providential hand stretched out to save;
and these things ought to be humbly marvellous in thy eyes,
and induce thee to walk answerably to the favors received.
I earnestly wish thee to abstain from any company that may be improper;
thy resolutions are weak; the poison of evil company very ruinous;
if thou hast no other inducement to alter thy dress, I beseech thee to do it,
to keep the distinction our principles lead to, and to separate thee from fools and fops;
at the same time that, by a prudent distinction in thy appearance,
thou scatterest away those that are the bane of youth,
thou wilt engage the attention of those whose company
will be profitable and honorable to thee.

Thus, my friend, my heart longs for thee and for thy help,
that thou mayst improve the present Providential allotment to the best purpose,
that it may be of lasting benefit to thee.
It will be good for thee to bear the yoke in thy youth;
if thy mind be rightly subjected to it, thou mayst have cause to say:
"`It was good for me that I was troubled.`"
I beseech thee often to read the Holy Scriptures; remember the prodigal son,
and imitate his penitent example,
and the same gracious reception from the everlasting Father will be thy portion.
With what joy would thy anxious parent, thy affectionate sister, view thee reformed,
steady and prudent;
but if (which God forbid) thou shouldst slight this
Providential opportunity of retrieving thyself,
and relapse into those things which have hitherto ministered much to thy hurt, and,
if continued in, must effect thy total ruin,
how shall I meet those Friends to whose care I have been instrumental in committing thee?
And what will be the sentence from despised mercy?
I am shocked at the mere supposition; but what must be the suffering of such a state?
Dear Joseph, what shall I say?
What can I say that will tend to thy help,
but earnestly press thee to seek Him who is mighty to save,
and to whom Jonah cried out of the belly of hell?
Cherish every impression of good; place thyself frequently before that tremendous bar,
to which thou are hastening, and bring every thought and action to judgment;
be diligent and faithful in business, but above all,
be diligent in making provision for thy poor soul.

Farewell,

Samuel Fothergill

In the love which he felt for his brethren,
and for the great cause they were ordained to support and spread in the earth,
George Fox often addressed them in tender affection,
to strengthen and animate them to diligence.
In 1654, he says:

Oh, Friends! look not out, for he that doth is darkened.
And take heed of lightness; take heed of the world,
and of busying your minds with things not serviceable.
A wise man`'s eye is in his head, but a fool`'s is gazing up and down.
Be valiant for the Truth upon the earth, and tread upon the deceit.
Keep to yea and nay; for he that hath not power over his tongue, his religion is vain.
And take heed of knowledge, for it puffeth up; but dwell in the Truth,
and be what ye speak.
He that abideth not in the Truth, is led by the evil one.
Wait on the Lord, He will perfect his work amongst you.
He that hearkens diligently to the teacher within, denieth all outward hireling teachers.
He that is made the temple of the Holy Ghost, placeth no holiness in the world`'s temples.
The teachers without exalt the carnal mind, but the teacher within destroyeth it.
There is not a word in all the Scriptures to hold up the practice of sprinkling infants;
nor the word sacrament;
nor to hold up an hour-glass to preach by for an hour`'s time in a place;
but the vain mind doth hold up many things which Christ Jesus doth not command.

Earth makes masters amongst earthly men; but let him that ruleth rule in love,
for the earth is the Lord`'s, and the fulness thereof.
And he that laboreth, let him labor as to the Lord, in love.
So let love be the head in all things, and the Lord is exalted;
then there is no eye-service, but singleness of heart;
then all that is done is done as to the Lord.
So be faithful in all things, and keep from the world`'s vain customs.
Do not wear apparel to gratify the proud mind;
neither eat nor drink to make yourselves wanton; for it +++[+++food and drink]
was created for health, and not for the lusts--to be as servants to us,
and we servants to God; to use all those things to his glory; to whom be praises,
honor and glory forevermore; who hath created all things to his glory,
and so to be used and spent.

All Friends, be low, and in the life of God dwell to keep you low.
Ye are the salt of the earth, to make it savory unto God.
Ye are the light of the world.
Therefore walk in the light of Christ, whose light doth justify you;
who then shall condemn you?
Therefore in that dwell which doth condemn all the evil in the world.

Samuel Fothergill to Gilbert Thompson

Warrington, Sixth Month 29th, 1760.

Dear Cousin:--I believe I should be out of the way of my duty if I did not impart to
thee and thy sisters a dream or vision that was represented to me the last night,
and perhaps the interpretation of it may be brought home to your own hearts.

I thought the great day of account was come,
and all nations gathered to receive the irreversible sentence.
I beheld a variety of states, and many clothed in different colors; many in white, which,
nevertheless, was of different degrees of lustre and beauty.
I saw many whom I knew, and amongst others thyself and sisters;
I thought your garments appeared more white than many;
and whilst I mused on the tremendous, yet glorious day,
the trumpet sounded with a distinguishing energy, and seemed to say: "`Come,
ye blessed.`"
I beheld multitudes arise, as from the eminence of a mountain, and ascend triumphantly.
My eye descended to the mountain whence many had risen,
and in whose company I had seen thee and thy sisters.
I thought I clearly saw you remain on the earth, clothed in garments measurably white.
I queried in my heart: "`Alas! how happens it that these are left behind?`"
Immediately the white garments fell off,
and each of you appeared in the common dress in which you usually appear.
But I beheld chains, which seemed fastened about your necks,
and bound every limb and part of the body but the head;
and these chains were fastened to great rings in the earth,
and held you so fast as to prevent any of you ascending
to those who had taken wing and risen on high.
Here I awaked in great concern of mind,
and found an engagement to impart it immediately to thyself and sisters.
None other knows the least tittle of it, nor shall, from your most affectionate

Samuel Fothergill

Gilbert Thompson was greatly esteemed, in the station of elder,
and filled several other offices in the Society.
He died between seven and eight years after this letter was written.
The circumstances attending his closing scene are thus instructively
described in a letter from Samuel Fothergill to Samuel Emlen:

Our worthy friend and kinsman, Gilbert Thompson,
hath been in a declining state for some time,
and of late seemed to decay so very fast as to call
in question his surviving for one day.
He finished his course about midnight, last Sixth-day, and is to be interred tomorrow.
I have often been with him to my humbling instruction;
for some time his journeying was in the region of the shadow of death.
I have sat by him, accompanied his spirit under the load of death,
and the heavens as brass, sensible of deep distress but seemingly excluded from good.
This led to deep searching of heart, even, as he said,
of holes and of corners he had not suspected;
he saw that he had been short in the performance
of that service Truth would have led him into,
had he been fully dedicated in heart to know and to do his Master`'s will.
But adorable condescension visited afresh, revived a degree of hope,
fed him with a little bread when nigh to faint, and caused a part of that crystal stream,
which is the satisfaction and consolation of the whole city of God, to arise in his soul,
and it increased from time to time,
until it became like the water Ezekiel saw issuing from the threshold,
a river to swim in, a river that cannot be passed.
The holy canopy was often over our spirits when I visited him,
which I often did to my comfort.
I never, my dear friend, so fully understood the force of the expression:
"`If the righteous scarcely are saved:`"--the applause and esteem of judicious and injudicious,
regularity of conduct, his arrival at Bethel, the remembrance of many bedewing seasons,
all proved insufficient for his repose,
and were amongst the heavens that might be shaken, and must be removed,
that that which cannot be shaken may remain.

He languished long, in much pain;
great was the conflict previous to the separation of body and soul,
and it feelingly opened to my mind, with the conviction of an audible voice,
had his spirit been more disentangled from the love of lawful things,
his warfare would have been sooner accomplished,
the fetters of mortality more easily broken,
and his spirit would sooner have risen triumphant over death, hell, and the grave,
and on the wings of seraphic love ascended, with holy ease, to the realms of purity,
peace, and love.
But all is well--he is admitted to peace, and through his deep wadings,
instruction is given to us, with diligence, yea, with all diligence,
to fill up the measure of revealed duty,
and to stand on the watch for further discoveries,
what is the will of the Lord our God respecting us.

The following was written by Francis Howgill, for the encouragement of Friends,
in a time of close trial by persecution:

The cogitations of my heart have been many, deep and ponderous some months,
weeks and days,
concerning this people which the Lord hath raised to bear testimony unto his name,
in this day of his power; an intercession hath been made often for them to the Lord,
and a patient waiting to know his mind concerning them for the time to come;
which often I received satisfaction in as to myself;
but yet something I was drawn by the Lord to wait for,
that I might comfort and strengthen his flock by an assured testimony.
And while I was waiting out of all visible things,
and quite out of the world in my spirit, and my heart upon nothing but the living God,
the Lord opened the springs of the great deep,
and overflowed my whole heart with light and love; and my eyes were as a fountain,
because of tears of joy, because of his heritage, of whom he showed me,
and said unto me in a full, fresh, living power, and a holy, full testimony,
so that my heart was ravished there with joy unspeakable,
and I was out of the body with God in his heavenly paradise,
where I saw and felt things unutterable, and beyond all demonstration of speech.
At last the life closed with my understanding, and my spirit listened unto Him;
and the everlasting God said:
Shall I hide anything from them that seek my face in righteousness?
nay, I will manifest it to them that fear me; I will speak, do thou listen,
and publish it among all my people, that they may be comforted, and thou satisfied.

And thus said the living God of heaven and earth;
upon the twenty-eighth day of the Third Month, 1662:

Possibly format differently in Jones the below quotes from God:

"`The sun shall leave its shining brightness, and cease to give light to the world;
and the moon shall be altogether darkness, and give no light unto the night;
the stars shall cease to know their office, or place; my covenant with day, night,
times and seasons, shall sooner come to an end,
than the covenant I have made with this people, into which they have entered with me,
shall end or be broken.

"`Yea, though the powers of darkness and hell combine against them,
and the jaws of death open its mouth, yet will I deliver them, and lead them through all.

"`I will confound their enemies as I did in Jacob,
and scatter them as I did in Israel in the days of old.

"`I will take their enemies, I will hurl them hither and thither,
as stones hurled in a sling; and the memorial of this nation, which is holy unto me,
shall never be rooted out, but shall live through ages,
as a cloud of witnesses in generations to come.

"`I have brought them to the birth, yea, I have brought them forth; I have swaddled them,
and they are mine.
I will nourish them, and carry them as on eagle`'s wings;
and though clouds gather against them, I will make my way through them;
and nations shall know I am the living God,
who will plead their cause with all that rise up in opposition against them.

"`These words are holy, faithful, eternal, good and true:
blessed are they that hear and believe unto the end;
and because of them no strength was left in me for a while;
but at last my heart was filled with joy,
even as when the ark of God was brought from the house of Obed-Edom,
when David danced before it, and Israel shouted for joy.`"

Francis Howgill

An Epistle of William Leddra, to Friends,
Written by Him the Day Before He was Put to Death.

To the Society of the little flock of Christ, grace and peace be multiplied.

Most Dear and Inwardly Beloved!

The sweet influences of the morning star,
like a flood distilling into my innocent habitation,
hath so filled me with the joy of the Lord in the beauty of holiness,
that my spirit is as if it did not inhabit a tabernacle of clay,
but is wholly swallowed up in the bosom of eternity, from whence it had its being.

Alas! alas! what can the wrath and spirit of man that lusteth to envy,
aggravated by the heat and strength of the king of the locusts,
which came out of the pit, do unto one that is hid in the secret places of the Almighty;
or unto them that are gathered under the healing wings of the Prince of Peace;
under whose armor of light they shall be able to stand in the day of trial,
"`Having on the breastplate of righteousness,
and the sword of the Spirit,`" which is their weapon of war against wickedness,
principalities and powers, and the rulers of the darkness of this world,
both within and without?
O my beloved, I have waited like a dove at the windows of the ark,
and have stood still in that watch, which the Master, without whom I could do nothing,
did at his coming, reward with the fulness of his love; wherein my heart did rejoice,
that I might in the love and life of God speak a few words to you,
sealed with the spirit of promise,
that the taste thereof might be a savor of life to your life,
and a testimony in you of my innocent death.
And if I had been altogether silent, and the Lord had not opened my mouth unto you,
yet He would have opened your hearts,
and there have sealed my innocency with the streams of life,
by which we are all baptized into that body which is of God,
with whom and in whose presence there is life, in which, as you abide,
you stand upon the pillar and ground of Truth.
For the life being the truth and the way, go not one step without it,
lest you should compass a mountain in the wilderness;
for unto everything there is a season.
As the flowing of the ocean doth fill every creek and branch thereof,
and then retires again towards its own being and fulness, and leaves a savor behind it,
so doth the life and virtue of God flow into every one of your hearts,
whom He hath made partakers of his Divine nature; and when it withdraws but a little,
it leaves a sweet savor behind it, that many can say:
"`They are made clean through the word that He hath spoken to them.`"
In which innocent condition you may see what you are in the presence of God,
and what you are without Him.

Therefore, my dear hearts, let the enjoyment of the life alone be your hope,
your joy and consolation;
and let the man of God flee those things that would lead the mind out of the cross,
for then the savor of life will be buried;
and though some may speak of things that they have received in the life, as experiences,
yet the life being veiled,
and the savor that it left behind washed away by the fresh floods of temptation,
the condition that they did enjoy in the life boasted of by the
airy thing will be like the manna that was gathered yesterday,
without any good scent or savor.
For it was only well with the man while he was in the life of innocency,
but being driven from the presence of the Lord into the earth what can he boast of?
And although you know these things, and many of you much more than I can say,
yet for the love and zeal I bear to the Truth, and honor of God,
and tender desire of my soul to those that are young,
that they may read me in that from which I write,
to strengthen them against the wiles of the subtle serpent that beguiled Eve, I say,
stand in the watch within, in the fear of the Lord, which is the very entrance of wisdom,
and the state wherein you are ready to receive the secrets of the Lord.
Hunger and thirst patiently; be not weary, neither doubt; stand still,
and cease from thine own working, and in due time thou shalt enter into the rest,
and thy eyes shall behold his salvation whose testimonies are sure and righteous altogether.
Let them be as a seal upon thine arm, and as jewels about thy neck,
that others may see what the Lord has done for your souls.
Confess Him before men, yea, before his greatest enemies;
fear not what they can do unto you; greater is He that is in you,
than he that is in the world; for He will clothe you with humility,
and in the power of his meekness you shall reign over all the rage of your enemies,
in the favor of God; wherein, as you stand in faith, ye are "`the salt of the earth;
for many seeing your good works, may glorify God in the day of their visitation.`"

Take heed of receiving that which you saw not in the light,
lest you give ear to the enemy.
Bring all things to the light,
"`that they may be proved whether they are wrought in God.`"
The love of the world, the lust of the flesh and the lust of the eye,
are without the light in the world;
therefore possess your vessels in all sanctification and honor,
and let your eye look at the mark.
"`He that hath called you is holy;`" and if there be an eye that offends,
"`pluck it out and cast it from you.`"
Let not a temptation take hold, for if you do it will keep you from the favor of God,
and that will be a sad state,
for without grace possessed there is no assurance of salvation;
"`By grace ye are saved,`" and the witnessing of it is sufficient for you,
to which I commend you all, my dear friends, and in it remain your brother.

William Leddra

Boston Jail, the thirteenth of the First Month, 1660-61.

What a noble letter was that addressed by Sarah Grubb to her dear friend,
Richard Shackleton, when very ill of smallpox.
It was dictated four days before her death:

Thy salutation met me, though apparently out of course, in the right time,
being under impressions which make time and circumstances of little account,
compared with the unlimited consolations of the Spirit,
or a preparation to receive them at the Divine hand.
My soul, though encompassed with the manifold infirmities of a very afflicted tabernacle,
can feelingly worship and rejoice in nothing more than this,
that the Lamb Immaculate is still redeeming by his precious blood, out of every nation,
kindred, tongue and people; and making a glorious addition to the Church triumphant,
whose names will stand eternally recorded in the book of life.
I express not these things from a redundance of heavenly virtue,
but from the soul-sustaining evidence that,
amidst all our weakness and conflicts of flesh and spirit,
an interest is mercifully granted in Him who giveth victory over death,
hell and the grave.

Thomas Story relates that before he had joined the Society of Friends,
at the time of the assizes at Carlisle, he went to a meeting near that city.

During the time of the meeting I found an unusual load on my spirit,
and hardness in my heart; insomuch that I could hardly breathe under the oppression;
nor could I say I had any sense of the comforts of the Divine presence there,
but that the heavens were as thick brass, and the bars thereof as strong iron.
But though I had no enjoyment in myself,
yet I was sensible the presence and goodness of the Lord were there,
and many therein greatly comforted;
and therefore did conclude my condition of mind was from some other cause,
and not relating to the state of the meeting in general.
After the meeting was over, one of them asked me how I did; I answered: "`Indifferently.`"
Then he and some others perceived my spirit was oppressed,
and sympathized with me therein.
I could not, all this time,
perceive the particular matter which thus affected me--for I knew not
of anything I had said or done to bring it upon myself--till that evening,
being returned to my father`'s house, very solitary, silent and inward,
there came in one Thomas Tod, an acquaintance of mine, who,
after some compliments of civility--for at that time I had not quite declined
the common modes of salutation--desired to speak with me apart,
and then told me that he had a trial to come on next day
concerning certain houses of his in the town of Penrith,
being the greatest part of all he had in the world;
that one of the witnesses to his deeds of conveyance was dead;
another of them gone into Ireland, and could not be had; but I, being the third,
and having made the writings, he hoped, through my evidence and credit,
to gain his just point against his unfair adversary,
and desired me to be in readiness in the morning,
for the trial was likely to come on very early.

As soon as he began this relation,
the word of life began likewise to work in me in a very powerful manner;
and the hammer of the Lord I sensibly felt,
and saw to be lifted up upon that hardness of heart which, for some time,
had been my state; and it began to be broken, softened and dissolved,
and the sense of the love of God in some degree to be renewed.
Then I saw plainly that this was the hard thing I had to go through,
and that now was the time of trial wherein I must take up the cross of Christ,
acknowledge his doctrine in that point fully and openly,
according to the understanding given me,
and to despise the shame and reproach and other sufferings,
which I well knew would ensue quickly, or I must forsake the Lord forever.
For, denying his doctrine, in the sense I had now plainly seen it,
would be denying himself before men; and if I had then denied Him,
I could expect no less, but according to his word,
to have been immediately and forever denied of Him,
and left under that hardness of heart and want of the enjoyment
of his Divine presence wherewith I had been favored before,
and all the dreadful consequences of a beginning so woeful.

But, according to the advances of the word and work of the Lord in me at that time,
my heart inclined to him; as my acquaintance was speaking, and by the time he was done,
I was furnished with a full resolution to give him a plain and direct answer,
which was on this manner:
"`I am concerned it should fall out so`"--for I had a real respect for him,
and saw his case to be very hard--"`I will appear, if it please God,
and testify what I know in the matter, and do what I can for you that way,
but I cannot swear.`"

This was so great a surprise to him,
both from the nature of his case and confidence he had of my ready compliance--he having
had no suspicion of my present condition till that moment--that he broke into a passion,
and with an oath, or curse, said: "`What! you are not a Quaker, sure?`"
Though I had made confession in the truth so far, in that point,
and the Divine presence sensibly returned in me, yet, upon this I was again silent,
till clear in my understanding what to answer in sincerity and truth.
For as nobody before that time had called me a Quaker,
so I had not assumed the appellation, which, being given in reproach, was not grateful,
though the thing in its proper sense most delightful.

Nor did I then see whether I had so much unity with all their tenets as might justify
me in owning the name--for in the unity of Divine love and life only had I known them--till
the power of that life of Him who forbiddeth all oaths and swearing,
arising yet clearer and fuller in me, opened my understanding,
cleared my way and enabled me thereunto; and then I said:
"`I must confess the truth--I am a Quaker.`"

As this confession brought me still nearer to the Son of God,
his love increasing yet more sensibly in me,
so likewise it heightened the perplexity and disturbance of my friend,
whose case thereby became more desperate in his own opinion; upon which,
in an increase of heat, and expressions therefrom suiting so obvious a disappointment,
as it then appeared to him,
he threatened to have me fined by the court and proceeded
against with the utmost rigor of the law,
saying: "`What! must I lose my estate by your groundless notions and whims?`"

But the higher my enemy arose and raged in this well-meaning but mistaken man, who thus,
without design, became the instrument of my trial,
the fuller and more powerful still was the love of God,
whose cause I had now espoused through his own aid and the
power of an endless life from Him made manifest in me.
I replied, in that calm of mind and resignation to the will of God,
that the life of the Son of God enables to and teacheth:
"`You may do what you think proper that way,
but I cannot comply with your request in this matter, whatever be the issue of it.`"
And then he departed under great dissatisfaction,
with all the threats and reproaches his enraged passions could suggest,
under a view of so great a loss.

Immediately I retired to my chamber; for,
perceiving my grand enemy to be yet at work to introduce a slavish fear,
and by that means subject my mind and bring me again into captivity and bondage,
I was willing to be alone and free from all the interruptions of company,
that I might more fully experience the arm of the Lord,
and his Divine instructions and counsel in this great exercise.

The enemy, being a crafty and subtle spirit, wrought upon my passions,
not fully subjected, and artfully applied to my natural reason,
my understanding not being fully illuminated, as his most suitable instrument.
He urged the fine and imprisonment, and the hardships accompanying that condition,
and how little help I could expect from my father and friends,
who would be highly displeased with me for so foolish and unaccountable a resolution,
as they would think it; and, also, the scoffings, mockings, derisions, scorn, contempt,
loss of friends and friendship in the world, with such other inconveniences,
hardships and ill consequences as the enemy could invent and suggest.
During all this time, from about eight in the evening till midnight,
the eye of my mind was fixed on the love of God, which still remained sensibly in me,
and my soul cleaved thereto in great simplicity, humility and trust therein,
without any yielding to Satan and his reasonings on those subjects,
where flesh and blood in its own strength is easily overcome by him.

But about twelve at night the Lord put him to utter silence with all his temptations,
for that season, and the life of the Son of God alone remained in my soul; and then,
from a sense of his wonderful work and redeeming arm,
this saying of the apostle arose in me with power:
"`The law of the Spirit of life in Christ Jesus hath
made me free from the law of sin and death.`"
Then the teachings of the Lord were plentiful and glorious;
my understanding was further cleared, and his holy law of love and life settled in me;
and I admitted into sweet rest with the Lord my Saviour,
and given up in perfect resignation to his holy will,
in whatsoever might relate to this great trial of my faith and obedience to the Lord.
In the morning I went up toward the hall where the judges sat,
expecting to be called as a witness,
but found that the dispute had been settled by private agreement.

A Testimony of Friends in Pennsylvania Concerning their Deceased Friend and Governor,
William Penn.

We find ourselves under obligation and concern both in duty and affection,
to give this mark of our love and the honorable regard we bear
to the memory of our late worthy governor and well beloved friend,
William Penn,
though it may not be our part to attempt so ample
and general a testimony as seems justly called for.
By his early convincement of the blessed truth, his noble resignation thereunto,
his steadfastness therein, and great services to the church of Christ,
as well by incessant labors in word and doctrine (made more extensive by the many excellent
writings he hath published) as his valiant sufferings for purity of worship,
and the testimony he had received, which, to him,
might be the greater trial and conflict,
his birth and station in the world placing him more in the notice of those of high rank
amongst men than was commonly the lot of many others of our worthy elders.
Neither can it, we presume, be forgotten how,
when it pleased the Lord to give some ease to his people,
this our dear friend employed the interest he then had with success,
and devoted his time and purse to serve not only his friends in their religious liberties,
but them and others distressed,
or any wanting favor even to the neglect of his own just interest.
But these memorials we leave to be made by those of our worthy elders in Great Britain,
who have more instances and greater knowledge of those his traits, services and labors,
than many of us can be presumed to be so fully acquainted with.

Yet it becomes us particularly to say,
that as he was our governor he merited from us love and true honor;
and we cannot but have the same regard to his memory,
when we consider the blessings and ease we have enjoyed under his government,
and are rightly sensible of his care,
affection and regard always shown with anxious concern
for the safety and prosperity of the people,
who many of them, removed from comfortable livings to be adventurers with him,
not so much with views of better acquisitions or greater riches,
but with the laudable prospect of a retired quiet habitation for themselves and posterity,
and the promotion of truth and virtue in the earth.

And as his love was great, and endeavors constant for the happiness of his friends,
countrymen and fellow subjects, so was his great tenderness,
justice and love towards the Indians,
from first to last always conspicuous and remarkable.
Here we cannot but gratefully and humbly acknowledge
to the gracious God of all our mercies,
the wonderful preservation of this colony from such injuries
and barbarous depredations as have befallen most others;
and add,
that we believe the same love wherewith the Lord had so fully and effectually
operated on the heart of this our worthy friend was the chief and durable
motive of that his affection and kind behavior towards those people;
and was the cause, as he was made a means, of this our peace and preservation;
so that his name remains precious even amongst the heathens.

More might be truly said of him, as he was the proprietary and governor of this province,
and we now find it our duty (incited thereto by the
love of our Heavenly Father in our souls),
to add a few lines concerning him, as he was our worthy elder,
friend and brother in the blessed Truth; many of us having been often comforted,
edified and solaced with him in the enjoyment thereof.
As was his testimony, so was his conversation, edifying and lovely,
administering grace and knowledge.
His behavior was sweet and engaging, and his condescension great;
even to the weakest and meanest, affable and of easy access;
tender of every person and thing that had simplicity of truth or honesty for a foundation.

It was our comfort to understand that, after all his various troubles,
trials and afflictions, when in an advanced age, infirmity of body,
and a distemper which affected his memory in most other things which befell him,
yet the love of God remained with him,
and his sense thereof was frequently strong and evident, and, we doubt not,
the blessing of the Almighty was his Omega.

Elizabeth L. Redman, a minister of Haddonfield, N. J.,
in 1836 attended the Yearly Meeting of Virginia.
On her return from it the following incident occurred:

During the night, whilst lodging at the house of a friend in Baltimore,
her mind was introduced into much exercise on account of an individual, whom,
three years previously, she had observed at an inn a few miles from that city.
In the morning she felt that she could not with an easy
mind proceed homeward without endeavoring to see him.
She mentioned it to her companion, who inquired his name.
She replied: "`I know not his name, nor his home.
I can only say that I saw him not far from this place; but whether he was a traveller,
or a resident there, is unknown to me.
But I believe if we can see him, we shall find him in affliction.`"
It being thought right to make the effort to discover him, it was mentioned to a Friend,
with her description of the appearance of the individual,
which was so striking that it was immediately believed to be that of a
person well known as a slave-dealer noted for great inhumanity.

Inquiry was made for the man,
and after much search it was ascertained that he resided in that city,
near where she was then lodging.
She, with her companions, went to see him.
He was confined to his chamber by indisposition.
She at once recognized him, and taking a seat beside him,
sat for some time in profound stillness.
He also sat with his eyes fixed upon her in apparent amazement.
She then addressed him in close but kind language,
describing his condition as being desperate in the extreme,
but said she believed the door of mercy was now open for him,
if he would submit to the terms of salvation;
after which she knelt and supplicated in a remarkable manner,
interceding with the Father of mercies that, in the day of final retribution,
the blood of none might be found upon him unrepented of.
He was greatly broken by this appeal to the Throne of Grace,
and tears flowed down his face abundantly.
She then took kind leave of him, much to the relief of her own mind.
He did not recover from this indisposition,
but after this interview became greatly humbled and changed.

=== Reflections in a Storm

James Backhouse mentions the following incident:

1835, Fifth Month 6th.--A storm came on in the night, in which,
on reflecting upon the many snares that are in the world,
and the many persons that have fallen away from righteousness,
after having witnessed a precious state of Divine favor,
I felt willing to perish rather than that I should be permitted to falsify the
testimony which the Lord has given me to bear to the Truth as it is in Jesus.
Unworthy as I felt myself to be of the least of the Lord`'s mercies, I prayed to Him,
if He saw meet to continue my life,
to continue also the baptisms of his Holy Spirit until the very root of sin should perish;
and to enable me so to watch as that the seeds of sin might not be suffered to vegetate,
but their smallest buddings be destroyed by the power of the Spirit.

While thus meditating and praying in the storm,
with thanksgiving for the accommodation of a good berth and many other blessings,
I was preserved very peaceful under the sense of the Divine presence.
Thus, as in days of old, and as on many former occasions in my own experience,
the Lord proved himself to be "`A very present help
in time of trouble:`" and I could adopt the language,
Therefore we will not fear, though the waters roar and be troubled,
though the mountains shake with the swelling thereof; for the Lord of Hosts is with us,
the God of Jacob is our refuge, and blessed be his holy Name forever.

The following instructive incident, recorded by Thomas Scattergood,
during his journey in North Carolina in 1792, seems worthy of being revived at this time,
as an encouragement to individual faithfulness:

Eleventh Month 15th.--After a good opportunity in the family,
we set off before the sun was up, and rode to Spring meeting.
As our friend John Carter and I rode together, he informed me that, in his young years,
being visited by the Day-spring from on high,
he sought much to find a place of rest to his soul, and joined the Baptists.
After a time he grew dissatisfied with their mode of worship,
not feeling that peace which he was in pursuit of; and one day,
after seeking the Lord with great earnestness,
and begging of Him to show him whether that was the people he was to join himself to,
he went to their meeting with a determination that,
if he felt an evidence of the owning love of God to attend his mind,
he would submit to go into the water to be baptized, or anything for peace sake.
But on that day the preacher held forth such doctrine
that it turned him away from them in his mind,
and led him more and more into a lonely, seeking state.

At this time the little company of Friends in the neighborhood
had grown so weak as to neglect their meeting,
and had given consent to the Baptists to hold meetings in their meetinghouse.
For some time his mind was impressed with an apprehension that it was
required of him to go and sit down by himself in the meetinghouse;
but he put it off, being ashamed.
At length he went by a private way, and sat down alone, and was greatly refreshed;
but he could not do it privately long, feeling a necessity to travel the road openly,
for his friends and neighbors used to wonder where he went in private.
One day, in going to meeting, he met with one of them, who asked him where he was going,
and he told him honestly, "`I am going to meeting.`"
"`Strange,`" says the other, "`what will you go there for?`"
He left him, however, by the way, and had peace in the meeting.
Next time he went, seven of his neighbors, hearing of his going, joined him;
and in process of time he was united to the Society of Friends.
Zeal and religion revived amongst them, and there is now a large meeting,
called Spring meeting, which we were at today,
and this Friend is a valuable minister amongst them.
We had a favored meeting.

=== How John Parker was Made to Quake, and How He Became a Quaker

John Parker was born in Wilmington, in the State of Delaware, in the year 1748.
He was by birth a member of the Society of Friends,
and we may believe that he experienced some beneficial
restraints from his connection therewith.
But the loss of his father, while he was still young, was a serious disadvantage to him,
as he could no longer receive paternal admonition,
neither be subject to that watchful oversight and control
which a religiously-concerned father might have exercised.
Not submitting in early life to the cleansing and
heart-changing operations of the Holy Spirit,
he too much allowed his naturally lively imagination and strong will to rule his conduct.
It is believed that he was favored to witness preservation
from gross and reproachful vices,
though he deviated from the simplicity of the Truth,
and turned aside from the way of the cross.

He once in his earnest, animated manner,
gave a ministering Friend an account of the way in which he became a Quaker.
His narrative was to this effect.

At the time the English army early in the Ninth Month, 1777,
after having landed at the head of Elk, were approaching Philadelphia,
they passed near the place where he lived.
He was out of his house and a company of Hessians meeting him,
appeared disposed to rob him.
By some means they learned that he was a Quaker,
whereupon they desisted from all acts of violence towards him,
but carried him to the English officer in command.
Here too, probably,
the reputation of the Society of which he was then but an unworthy member,
cast a shield over him, and he was told that he should receive no harm.
He must, however, remain with them for a time,
as they were about to engage with the American army, and if he were released,
he might carry to their opponents the knowledge of their position and their intentions.
They treated him however, kindly,
and the head officer of that portion of the army kept him near his person.
As they were standing on the Brandywine hills,
surveying the beautiful country around--beautiful
although arrayed in the graver tints of early autumn,
the British officer made many remarks on the loveliness of the scene.
He also expressed his opinion that this was destined some future day to be a great country.
At last the firing commenced, and John who was still near the officer,
saw many fall around him.
The awfulness of his situation, in the consciousness that he was unprepared for death,
made him tremble.
The officer perceived the uneasiness of his companion, and smiling on him,
inquired if he was afraid?
To this John promptly replied, yes.
As no object was to be gained by detaining him any longer, he was told he might go.
He was not slow in understanding the import of this, but starting at a full run,
soon reached his home in safety.
As John in his old age related this circumstance, he added: "`That day made me a Quaker.
I never was one before.`"

It is probable that the view of death thus brought powerfully before him,
was of essential service,
and tended to drive him to seek for consolation where alone it could be found,
even in Him who, by taking away our sins, taketh away the sting of death.
He had been made to quake for fear of death;--he was now made a Quaker indeed,
in an awful sense of the power and presence of the Lord
God of Hosts visiting his soul as a refiner with fire,
and as a righteous judge with judgments.
Witnessing his own will brought into subjection, a new heart was given him,
and he no longer took delight in this world`'s pleasures.
He submitted to the cross of Christ,
and through the effectual working of the Lord`'s preparing Spirit,
and a gift in the ministry of the Gospel committed to him,
he was soon qualified for usefulness in the church of Christ.

=== A Brand Plucked From the Burning

James Backhouse thus describes the case of a prisoner
whom he met with in Van Diemen`'s Land,
whither he had been sent as a convict.
He lost an arm some time before, and, whilst in imminent danger from this accident,
was awakened to a sense of his sinful condition:

He said the Lord found him when he sought Him not,
yet so strongly did he feel his own desperate wickedness,
that he could entertain no hope, until he was reminded of the mercy extended to Manasseh,
Mary Magdalene, and others of similar character.
He told me he had been guilty of house-breaking, and many other crimes,
for which he said he had been three times sentenced to this settlement;
he said also that the gallows was no terror to him, and that he was so hardened,
that he did whatsoever he wished in defiance of the laws of God and man,
till the Lord visited him, and brought him low.
He afterwards ranked amongst those, who having been forgiven much, loved much.
The alteration in his conduct was noticed by all around him:
the commandant said his very voice was changed; formerly it was ferocious,
now it was mild; formerly he was contentious and addicted to fighting,
now he was gentle and peaceable; formerly he was so given to swearing,
and the habit of it had such power over him, that, after he had turned to the Lord,
if anything irritated him, he had to lay his hand upon his mouth that he might not swear;
now he was to be found warning others against this sin.

The men who had turned from their evil ways,
were allowed to sit in a room used for an adult-school,
in order that they might not be disturbed in reading
and meditation by those who still remained in folly,
and would be disposed to deride them; and this man, on account of his infirmity,
was allowed likewise to retire alone to one of the caves in the base of the island,
to meditate and pray.
Though he had lost an arm he was not idle,
but employed himself in carrying wood for fuel, after it was landed from the boat.
I invited him to show me his cave; he readily consented,
and led me down a steep and slippery path at the back of the island.
The cave was damp on one side, and had a honeycomb-like incrustation upon it:
its sloping roof was dry, a few old palings formed its loose floor,
and a cold wind blew through it from a small opening at its farther extremity.
I could not stand upright in it, but entered by stooping; he followed,
and we sat down upon its floor,
and conversed for a while on the mercy of God to sinners
in sending his Son into the world to save them,
and in calling them by his spirit to come unto Him.

This cold and forlorn place was much prized by its occupant, in it,
(to use his own words,) he contrasted his privilege,
in being allowed to meditate in quiet, and to wait for the Spirit`'s influence,
with the privations of those who in former ages wandered in sheepskins and goatskins,
in deserts and mountains, and in dens and caves of the earth, being destitute, afflicted,
tormented.
Before quitting the place we kneeled before the Lord,
and I prayed for this "`Brand plucked out of the burning,`" as well as for myself.
When I ceased, he prolonged the voice of supplication, ascribing, glory, honor,
and praise to Him that liveth forever and ever,
and who in the riches of his mercy had called him
out of darkness into his marvellous light,
and translated him from the kingdom of Satan, into the kingdom of his own dear Son.
In the course of conversation, this monument of Divine goodness,
desired that I would tell audacious sinners of the mercy that God had shown to him;
and assure them that he found such comfort and pleasure in righteousness,
as he never could have thought of whilst he remained in sin.
When he became awakened he found himself in ignorance also,
and since that time he had learned to read.

[.asterism]
'''

James Backhouse relates the following:

The superstition of sailors often leads them to attribute
a tedious voyage to having some unlucky person in the vessel.
On hearing one of them remark that we must have some Jonah on board,
I took occasion to observe, that it would be well if we had not many worse than Jonah;
for he was remarkable for disobedience to the Lord in one instance,
but I feared that in our company there were those who were disobedient in many.
There is little ear for religious instruction, but no profession to despise it.
I have been much restrained in mind in regard to expression on religious subjects,
and have felt the force of the declaration: "`Where the spirit of the Lord is,
there is liberty;`" the reverse of which is also true.
Here there is a want of regard for this Spirit, and little ear to hear.

=== Grace at Table

When taking a meal with pious persons, I was frequently requested to give thanks.
This being intended as a mark of Christian courtesy to a strange minister,
I received it as such; but we found it necessary to explain,
that it was our practice on such occasions to endeavor to feel thankful,
but not to give expression to +++[+++this]
feeling on behalf of ourselves and others,
unless under such a sense of Divine influence as warranted
the belief that it was done in spirit and in truth.

Though in the course of our travels,
we were sometimes present where thanksgiving was uttered in a formal way,
which left upon the mind the impression that God was drawn nigh unto with the lip,
while the heart was far from Him;
yet we were often sensible of a measure of the influence of the Holy Spirit,
when thanksgiving was devoutly uttered by those who were in the
constant practice of using expressions on such occasions.
Nevertheless, when we were present,
where the attention of the company was individually turned to the Lord,
in a short period of silence, in order to feel thankful,
and to acknowledge this feeling in the secret of the heart,
we were sensible of a greater measure of Divine influence, which comforted our minds,
under the belief that the Father of mercies condescended more decidedly,
to mark this homage with approbation.

=== The Way to Salvation

We left Launceston on the seventh, and reached Kelvedon again on the ninth,
having again visited some thoughtful families, with whom we were acquainted,
upon the way.
It was truly pleasant to see among them the tokens of advancing religious character,
yet I could not but lament that the immediate teaching
of the Holy Spirit seemed to be so little understood.
The consequence of this is that it is not waited for, and little, if any,
of its baptizing influence is to be felt in the generality
of the devotional exercises of many truly estimable characters.
These have witnessed so much of the work of the new birth,
as makes them very distinguishable from those whose minds
are not yet in any degree brought under Divine influence.
They have a religious understanding also, according to the measure of their faith;
but not having faith in the perceptible guidance of the Spirit,
they do not so walk as to perceive things clearly by its light,
and much of their religious exercise is, consequently,
the produce of their own natural powers, with little,
or often with nothing of the Spirit of Life.
In one family in which we again proclaimed the Gospel message,
I had to point out to the company,
that to the humble mind the way of salvation is opened,
not by deductions of the reasoning powers,
but by the light of Christ shining into the mind,
and giving a perception of the mercy of God in his beloved Son,
and of the state of the soul before Him, and of other truths progressively,
as there is a preparation of heart to receive them.

=== Fruits of Disobedience

In the afternoon we visited an ironed-gang +++[+++in New South Wales]
employed on the roads, under a military guard; we found them locked up in their caravans,
out of which only one-third were allowed to come at a time, for exercise.
When locked in, only half of them can sit up, on the ends of the platforms,
on which half of them sleep; the rest must sit back,
with their legs at a right angle with their bodies.
On our arrival, they were all turned out, counted,
and then marched to a place at a short distance, where they stood,
with a guard of soldiers under arms behind them.
After a pause we addressed them,
inviting their attention to the convictions of the Holy Spirit,
as the witness in their own minds against sin;
by neglecting which they had fallen into transgression before God and man,
until they had been permitted to commit the sins which had
brought them into grievous bondage among their fellow-men;
when, if they had attended to this warning voice of the Most High, they would,
on the other hand, have been led to repentance and faith in Christ, and, through him,
would have become of the number of his reconciled and obedient children,
free from the bondage of Satan.
They were invited to turn at the reproofs of instruction,
as at the voice of Him who desires not that any should perish.

In commenting on the passage: "`Eye hath not seen, nor ear heard,
neither have entered into the heart of man,
the things which God hath prepared for them that love Him;
but God hath revealed them unto us by his Spirit; for the Spirit searcheth all things,
yea, the deep things of God;`" it was mentioned, by way of illustration,
that our ideas of all things are liable to be very defective, till we see or feel them;
that thus, though themselves might have heard of the sufferings of prisoners,
they had had a very defective idea of them till they felt them;
and though they might have seen men in chains,
they had had a very imperfect notion of the suffering of this punishment,
till they felt it; and that so, likewise, though of an opposite nature,
the blessings of the Gospel required to be felt, to be understood.
These comments excited a significant assent in the
countenances and movements of the heads of the prisoners,
expressive of their sense of the suffering under which they have brought themselves,
by having multiplied their offences,
so as to incur the extra-coercive discipline of this part of our penal laws.

=== How a Drowsy Friend was Cured of Sleeping in Meetings

On one occasion, while in meeting, she fell asleep, and dreamed in substance as follows:
She thought she was occupying her usual seat in the meeting,
observing those who were assembled with her and who were sitting in profound silence,
when suddenly the door of the meetinghouse opened,
and a man dressed in a plain garb entered,
having a tightly-covered basket hanging on his arm.
His countenance was grave, but with an inexpressible sweetness.
His entrance did not appear to be noticed by the meeting generally,
and after looking over it with complacency, he walked up into the preacher`'s gallery,
carrying his basket with him.
He now began to observe each individual attentively as he passed along before them,
and ever and anon he put his hand into his basket,
and took out something which he put into the laps
of many of those who were quietly seated before him.
One thing was observable,
that those on whom he bestowed his gifts appeared to receive them with great delight,
while those to whom he gave nothing were apparently almost unconscious of his presence.
The Friend`'s curiosity being aroused,
she inquired of a worthy Friend who sat alongside of her, who the stranger was,
and what he was doing.
The reply was: "`It is the Saviour; his basket is filled with blessings,
and He is distributing them to those who are waiting to receive them.`"
As He was now approaching where they were seated,
the sleeping Friend`'s feelings were greatly excited.
He stood before her, and his hand was thrust in under the cover of his basket.
He regarded her for a moment, and then saying sadly,
"`She is asleep!`"--he passed her by,
and deposited a blessing in the lap of her next neighbor.
The shock completely aroused her,
and it was said she was ever after cured of sleeping in meeting.

=== Severe Reproof

When John Churchman, in ministering to the people at North Wales, had, as he tells us,
"`with a zeal that exceeded my childish knowledge,
laid on some strokes with the strength of the man`'s part,
more than with the humbling power of Truth,`" he
soon felt inward darkness and dejection of mind.
He was enabled to see his error, and makes this remark:
"`If we deliver hard things to the people,
we should ever remember that we are flesh and blood,
and by nature subject to the same frailties.
This would lead us closely to attend to the power
and to minister only in the ability of Truth,
in the meekness, gentleness and wisdom which it inspires.`"
This reflection did not make him lower the standard of Truth,
deliver its testimonies deceitfully,
or tend in any wise to make him one of those who sew pillows under armholes.
In a subsequent visit he thus wrote:

One meeting we were at was remarkably hard, and my companion was exceedingly exercised,
under a sense that the people were too rich, full and whole in their own eyes,
but he sat the meeting through, and suffered in silence.
I had something to say which was very close,
and felt a degree of the strength and power of Truth
to clear myself in an innocent and loving manner;
and remembering they were brethren, I did not preach myself out of charity towards them,
and so had peace.
We went home with an elderly Friend, who, in a stern manner asked me from whence I came,
and said I was a stranger to him.
I answered him with a cheerful boldness.
He asked me what my calling was; I told him husbandry.
He queried if I was used to splitting wood;
I let him know I had practiced it for many years.
He asked me if I knew the meaning of a common saying
among those who were used to that business,
"``'Tis soft knocks must enter hard blocks?`"
I told him I knew it well,
but that to strike with a soft or gentle blow at a wedge in blocks of old wood
that was rather decayed at heart would drive it to the head without rending them,
and the labor would be lost, when a few smart, lively strokes would burst them asunder.
Whereupon he laid his hand on my shoulder, saying, "`Well, my lad,
I perceive thou art born for a warrior, and I commend thee.`"
Thus we came off better than we expected, for I thought he pointed at my service that day.
He was ever afterward very loving to me, and I was thankful that the Lord was near to me,
for which I praise his sacred Name.
To be becomingly bold in the cause of Truth, at times is particularly necessary,
otherwise the weight of the testimony thereof would be lessened,
and a carping spirit be set over it.

Leonard Fell, a son of judge Fell, travelling one time, was attacked by a highwayman,
who demanded his money, which he gave him.
Then he desired to have his horse.
Leonard dismounted and let him take it.
Then, feeling the power of Truth to arise in his mind,
he turned to the robber and solemnly warned him of the evil of his ways.
The robber, flying into a passion, asked the Friend why he preached to him,
and threatened to blow out his brains.
But Leonard replied to this effect,
"`Though I would not give my life for my money or my horse,
I would give it to save thy soul.`"
The robber was so astonished that he declared, if he was such a man as that,
he would take neither his money nor his horse from him,
and returning both to the faithful Friend, went his way.

In the year 1682, Benjamin Bangs, visited Ireland, of which he says:

In this nation I travelled up and down in the work of the Gospel, and had good service,
many being convinced by means of my ministry.
At Antrim, a place of great profession, I had a meeting in the evening,
to which many came, and some with design to oppose me.
The place was not large enough to hold the people,
which occasioned those without to be very noisy and turbulent,
some of the ruder sort pelting them with bits of dirt and turf, whilst I was preaching.
I made a full stop, which occasioned a general silence; and after a little time I said,
I understand this is a place of great profession of religion;
I am sorry to see so much irreligion as appears amongst you at this time,
through your rude behavior.
It is not long since I came out of my native country,
and I think it will not be long ere I return again, and then what shall I say of you,
to your poor suffering brethren in England?
I advised them, if they had any regard to the reputation of religion,
to inquire after those that were the occasion of these disorders,
for such behavior was base and scandalous.
And I was moved to say, that the time draws nigh,
that you will be blown away like the chaff from the summer threshing floor,
and the place of your meeting will not be found.
At this meeting a young man, a papist, was convinced,
as were many more elsewhere in the north and other parts.

He continued his travels several months, in the course of which, he says:

As I was going from Antrim to the Grange, I saw ten or twelve men upon the road,
walking in a solitary manner, and it arose in my heart,
these are sheep having no shepherd.
When I came up to them I slackened my pace, and queried of them, what news?
The men were startled at the question, and answered,
"`we know of none;`" continuing to go softly, I said, are ye going to meeting?
They answered, "`Our minister is silenced; for orders are come down,
commanding all dissenters not to assemble; so now we have no teacher.`"
This brought to my remembrance what I had been concerned to deliver as above at Antrim,
where I met with so much rudeness.
I said, the hireling fleeth because he is an hireling, and careth not for the sheep,
referring them to the text;
further showing it is happy for those who are come to the knowledge of
that Teacher who cannot be removed into a corner--God said he would teach
his children himself--and the children of the Lord are taught of the Lord.
You may read in the first epistle of John,
"`The anointing which ye have received of him abideth in you,
and ye need not that any man teach you,
but as the same anointing teacheth you of all things.`"
And in Titus, "`The grace of God which bringeth salvation, hath appeared unto all men,
teaching us,`" etc.
Here I directed them to the great heavenly School-master, who said: "`Learn of me,
for I am meek and lowly in heart; follow me and ye shall find rest unto your souls.`"
Thus I labored to bring them from their hireling teachers,
to the teaching of God and Christ in themselves,
by which they might come to the knowledge of God, and walk in the ways of his salvation;
"`for a manifestation of the spirit is given to every man to profit withal.`"
I advised them to turn their minds inward, and mind the secret operation of it,
which checks and reproves for bad words and actions; and as they turned to it,
they would find it would lead them into all Truth, with many words to this effect.
They were well pleased, declaring at parting,
that they had never heard things so opened to them in their lives.

John Churchman relates an incident which shows the
importance of those who make a profession of religion,
living so on their guard, as not to stumble the young and inexperienced.
He says:

I remember a person was once at my father`'s,
who spoke about religious matters with an affected tone, as if he was a good man;
and when he mounted his horse to go away, taking a dislike to some of his motions,
he called him an ugly dumb beast, with an accent which bespoke great displeasure,
and grieved me much.
I believed that a man whose mind was sweetened with Divine love,
would not speak wrathfully or diminutively of the beasts of the field,
which were given to man for his use.

When William Jackson was in England on a religious visit his health seemed to fail,
which, he says:

It put me on thinking whether it could be required of me to travel so,
and I turned my mind a good deal homewards.
After being awake for several hours, I fell asleep and dreamed of being in America,
and that I could not feel myself satisfied.
I thought if I had but stayed in England, and attended the Yearly Meeting there,
I should have been better satisfied.
In my sleep I reflected on myself for coming away so precipitately,
and was much concerned how I should get back to the Yearly Meeting in London.
When I awoke I felt a degree of thankfulness that I was where I was.

It is a blessed experience in time of danger to have an unshaken
trust in the goodness and protecting care of the Almighty.

When Job Scott was on his way to England on a religious visit, in 1792,
he encountered a violent storm, which lasted for two nights and a day, and which,
he says, was "`truly terrible,`" reminding him of Addison`'s line: "`When wave on wave,
and gulf on gulf, o`'ercame the pilot`'s art.`"
He says, in a letter to his family:

It seemed, at times, as if the briny waves would soon swallow us up;
yet I never really lost my confidence,
for all this was no more than for months I had firmly expected to meet with.
You know it was sealed on my soul that the loud roar of wind,
and the dread rolling of the waves, would awfully attend my passage.
And now, indeed, it proved my hold on heaven.
I said in my heart: "`It is the Lord; let Him fulfill his purposes.
Let Him do just what He will with me in time and in eternity.
Naught else beside his holy will can ever be good for me;
and why should I wish even the most disagreeable parts of it averted,
mitigated or shortened?`"
I thought I had had his holy promise who cannot lie,
that I should live through these dreadful tossings on the bosom of the ocean,
and once more set my foot on firm ground; yea, bless his holy name,
in wonders yet to come on shore.
I cannot say I had no reasonings;
but I well remembered the clearness of prospect wherein
I had seen this dispensation on the ocean.
I also livingly remembered the holy warmth,
energy and assurance that attended the promise of safety through all;
and though it was now the Divine will that the evidence
of Divine things should be low in my mind,
yet I could not cast away my confidence.
My all I surrendered up to his disposal, not once wishing myself on shore,
nor in another vessel.

This devoted servant in this,
verified in measure the truth of the psalmist`'s declaration:
"`God is our refuge and strength; a very present help in trouble;
therefore will ye not fear, though the earth be removed,
and though the mountains be carried into the midst of the sea;
though the waters thereof roar and be troubled.`"

=== An Instructive Dream

Thomas Shillitoe, although a comparatively poor man,
felt it his duty to sacrifice part of his property,
that he might devote himself more fully to the service of his Divine Master.
While struggling with a sense of this requisition, he had the following dream:

I saw before me a straight but very narrow path, gradually rising,
at the foot of which stood a man very simply attired,
who offered to take the charge of safely guiding me up.
I followed him; when we had reached about two-thirds of the way up, my guide halted,
and turning himself round, requested me to do the same, which I accordingly did.
He then bid me take a view both on the right hand
and on the left of the road I had been ascending.
On my right hand the ground in the bottom appeared rocky and uncultivated,
covered with rubbish, grass, and trees that had been stunted in their growth; these,
I was told, were fit for nothing but the fire,
and that they were comparable to those whose hearts
continued to be like the stony and thorny ground.
I then turned to take a view on my left hand,
and shuddered in myself when my guide pointed out to me the dangerous
precipice close to the edge of which I had travelled.
The foundation of the path appeared as steep as a house side,
which led me to conclude the road on which my guide
had thus far conducted me must be founded on a rock,
otherwise, the path being so very narrow,
from the weight of my body I must have been precipitated
into the vast barren pace I beheld.
In this I observed a number of persons huddled together,
at times grubbing with their hands in the earth,
and at other times employing themselves in tossing the earth from one hand to the other,
every now and then looking one at the other,
with a sort of consciousness that they were employing their time in vain,
and saying one to another:
"`I am countenanced in spending my time in this manner by thee;`" and another:
"`I am countenanced by thee.`"
On which I queried with my guide: "`What does this all mean?
These men do not look like common laborers,
neither have they such tools as common day-laborers use; besides this,
they are all clad in very nice and costly apparel,
like men of the first rank in the world with respect to property.`"
My guide assured me that, although they were thus apparelled,
and were rich in worldly substance,
wanting nothing this world could bestow to make them as happy as it was capable of, yet,
having made riches their chief hope for happiness,
they had become so estranged in love and affection from
that Divine power which only can make truly happy,
that they were completely miserable.

My guide, turning round, bid me follow him; and, as we began again to ascend,
instructed me to keep very near to him, continually reminding me that,
although I had mercifully escaped the danger which those
I had observed in the barren space had fallen into,
yet I was not out of the way of danger,
and that my safety depended on my keeping continually near to him,
eyeing him in every step I took from day to day,
without which I should yet be precipitated into the same
barren space with those miserable persons I had beheld,
and become their doleful companion.
When I awoke, the danger which I seemed to have escaped on both hands,
but more especially that on my left, made such an impression on my mind that,
for several days afterwards, little besides it came before me.

=== Faithful Service

When Ebenezer Worth was living at Tunesassah among the Indians,
he had a severe attack of sickness.
His diary says, under date of Second Month, 1848:

While sick,
I was brought to feel a degree of love and concern
for a man who lived up Cold Spring Creek,
near the Reservation,
who had been charged (and I think likely justly so)
of letting the Indians have ardent spirits.
I heard reports of their drinking a good deal while I was sick,
and it was said they got much of it from that man.
I thought if I was spared to get well I would talk to him on the subject.
When I got able to go about, I remembered the feeling I had, but felt discouraged,
thinking I would be in danger of being insulted or abused by the rough,
intemperate people he kept about him.
Some weeks after, as I was passing by the place, I saw five Indians about leaving there,
all, I think, more or less intoxicated.
I then thought I ought to speak to him,
and requested a man who was going in to invite him out.
He came,
and I spoke to him on the subject of letting the Indians have intoxicating drink;
also expressed the concern I felt for him.
He seemed much tendered, I think to tears;
acknowledged it was wrong to sell or use the article.
He said when he disposed of what he had he would not keep the article in his house.
He also said he had prayed that if he drank any more ardent spirits,
it might make him sick; that he had once felt the love of God in his heart,
and thought he could feel something of it at times yet,
and that he was one of the greatest of sinners.
I told him I thought he had best get rid of what intoxicating drink he had,
and try to live up to his good resolution.
I first thought that he could wholesale it;
but afterwards concluded that it was not right to sell the article in any way.
I inquired how much he thought he had.
He said he thought about ten gallons of whiskey and no other ardent spirits in his house.
I proposed that he should throw it (the whiskey) on the ground.
He spoke of its being a loss.
I think I spoke in this way, that when we felt anything to be wrong,
that was the time to leave off and try to reform;
that the Lord`'s time was the best time,
that (it was) dangerous to put it off and to keep the temptation about him.

He seemed much broken down, and consented to throw it out if I thought best.
I told him he should not lose by it if he did.
He went into the house, took hold of the barrel, shook it,
and said he thought there was more in it than he had supposed.
There was a number sitting in the bar-room, who kept their eyes upon us,
as if their curiosity was much excited, not knowing what we were going to do.
The poor man acted with a good degree of firmness,
though no doubt it was a great cross to bear such a testimony
against an article he had dealt in and used so much himself.
I asked for a pail and a measure; he had it brought; we lifted the barrel on the counter;
those who sat looking on appeared struck with astonishment,
their countenances looked quite sober.
One man pleaded in favor of converting it into vinegar, so as not to waste it.
We measured out a pailful, I carried it (out) and threw it on the ground,
and so continued until we emptied the barrel.
While we were drawing it off, he sold some to two men,
who promised it should be used for medicinal purposes; to one to put on camphor;
the other man`'s wife was quite sick,
he said the doctor directed him to get some (I think) to rub her with.
There was another drinking man present,
who presented his jug and pleaded hard to have it filled, but he did not get any.
I do not recollect that there was an unkind or disrespectful
word spoken to me during the whole time.

After we had got done, I took the man aside who had pleaded so hard for liquor,
and talked with him of the great evil of making use of intoxicating drinks,
both as it regards our happiness in this world and our future prospects.
He first spoke strongly in favor of ardent spirits as a medicine,
said it had been recommended to him by a physician,
and that there did not appear to be any other medicine so well adapted to his disease,
which was something like an affection of the heart.
I told him the bad effects of the medicine were more to be dreaded than the disease.
He said before he got to using it as a medicine, he was opposed to using the article,
and before we parted he said he had thought, at times,
it would have been better for him to have died than got to using ardent spirits.
I parted with them both in kind, good feelings,
and had great reason to be thankful for the preservation and favors of that day.

=== John Evan`'s Suit Against Friends

This trial, which excited considerable interest in Philadelphia at the time,
grew out of the circumstance,
that the wife of John Evans was brought under the care of the Women`'s Monthly Meeting.
It is believed the occasion of this was her neglecting to assemble with her fellow-members
for the purpose of Divine worship-out of compliance with the wishes of her husband,
who had before been disunited from the Society of Friends,
of which at one time he was a member.

Mary Clark and another woman Friend called at the house, as a committee, to visit her;
John met them in the entry, told them that his wife was upstairs in her room,
and that they could not see her.
In her pleading with the husband to be allowed to go up to see the wife,
Mary laid her hand on John, either to soothe his ruffled temper,
or gently to remove him out of her way.
This act was so resented, that he brought a suit against her for assault and battery,
and employed two lawyers to plead his cause, one of these was Jared Ingersoll.
The course pursued by his counsel drew unusual attention to the case.
The whole course of procedure among Friends in cases of violation of the discipline,
was brought into court--the minute book of the Monthly Meeting was produced,
prominent members of the Society (among them the
// lint-disable invalid-characters
late Samuel Bettle) were subpœnaed as witnesses,
and copious extracts were read from the book of discipline, drawing from judge Tilghman,
who presided over the trial,
strong expression of admiration at the character of that code of regulations.
The decision was, that as Mary laid her hand on John Evans in his own house,
there was a technical breach of the peace, but not an actual one under the circumstances.
This trial has somewhat modified the practice of the Monthly Meeting of Friends of Philadelphia,
as to testimonies of disownment.
These are not now signed by the clerk,
but their authenticity rests on the testimony of
the committee who deliver them to the party concerned.

The verdict of the jury was one-half cent damages for John Evans, but no costs.

=== Anecdote Respecting John Crook

Our friend John Griffith informed Robert Dudley, that John Crook,
one of the earliest and most distinguished ministers among the people called Quakers,
was remarkable on many accounts,
especially during the violent persecution in the reign of Charles II,
a large participation whereof fell to this Friend.
It was observable that his gift in the ministry was such, that he frequently,
in those times of great affliction, whilst free from imprisonment,
continued his declaration in public meetings for upwards of three hours;
during the whole of which such an increasing degree of authority attended,
as to convince many of his auditory,
that nothing short of a Divine commission could produce
the baptizing effects of his ministry.
In consequence, many were joined to the Society of which he was a member,
through his labors, who became ornaments thereof.

He outlived those days of dark intolerance some years,
much beloved from the remembrance of his past services,
and sufferings for the noble cause of religion;
and he frequently appeared in the meetings of Friends,
in very long testimonies of sound doctrine and pleasing expressions.
But some deeply exercised minds among his friends, observed with concern,
that the energy of melting virtue, which had attended his Gospel labors in former times,
to their great consolation, was now very little, if at all,
felt to accompany his ministry.

Two of these Friends, who stood in the station of elders,
feeling their minds engaged to it, from a sense of duty, waited on him;
and with all the tenderness and deference due to his age, experience, and great worth,
communicated their fears to him on this head, and intimated their wish,
that he would look at this matter,
and seek to that gracious Being in whose service
he had been so successfully engaged for many years,
for his blessed counsel on the subject; desiring him at a suitable time,
to favor them with the result of his deliberations on what they had laid before him.

He received their communications with great meekness;
and after some weeks he waited on them, in a broken, tender frame of mind,
letting them know, with many tears, that their brotherly,
or rather fatherly conduct towards him, was a kindness that he should never forget;
and that on deep thoughtfulness respecting the matter referred to him,
he found there was ample cause for their fears;
and that he looked upon them as the messengers of love from his great Master,
to warn him of his dangerous situation.

He next related to them how he then found that in those times of public tranquillity,
he had gradually and imperceptibly slidden off from
receiving his ministry through that pure,
unmixed channel, by which he had formerly received it.
The spring of the ministry, he said, during the fiery trials of persecution,
flowed so copiously through him, that he felt but little labor to come at it;
but in these latter days of the church`'s tranquillity,
from the love he felt for the cause,
he delivered words as they occurred to him in the public assemblies, which,
till their kind intimations to him, he did not perceive,
proceeded only from his natural powers as a man, and did not, as formerly,
flow from the Divine spring and gift of Gospel ministry.
Of this, he said, he was now fully convinced,
and returned praises for his great deliverance where first due,
and gratitude to them as instruments thereof.

He continued for three years after this quite silent as a minister;
and about the expiration of that time, again appeared in the ministry in a few words,
as in his first beginning, and gradually experienced an enlargement in his gift.

=== Incident in the Ministry of Joseph Hoag

At Starksboro Monthly Meeting, Vermont, Joseph Hoag rose and repeated,
"`Ephraim is a cake not turned.`"
He then said, in substance,
that he had been reflecting upon the various necessary processes through which the flour,
which had first been rightly prepared, had to pass, before it became good,
wholesome bread, suitable for the nourishment and sustenance of the body.

It must first be properly moistened by either pure milk or water.
Then a little leaven must be added,
and the whole thoroughly worked together and incorporated.
Some time must then be given for the "`little leaven to leaven the whole lump.`"
After this it must be submitted to the action of fire, the most important of all.
Oftentimes it had to be turned to receive the full effect of the fire;
otherwise a part of it would, after all, be only raw dough and unfit entirely for food.
Like Ephraim of old, it would be a cake not turned.
Now he had been led greatly to fear there were some amongst
us who might have submitted to some of the various processes,
and a good beginning had been made in the right preparation.
But when they came to be tried so as by fire, they had shrunk from the needful trial,
they were not willing to be turned; and so were like Ephraim,
"`Cakes not turned,`" and could not be made useful
in the household and family of the Lord.

=== Resist Temptation

John Salkeld was in attendance at a meeting where,
after a time of silence and deep exercise, he struck his cane on the floor,
and exclaimed: "`Resist the devil this once, and he will not trouble thee again!`"
At the close of the meeting John was taken to task by some
of the Friends present for his disorderly act.
In reply, he said that if he had ever known the Divine commission to preach the Gospel,
he thought he had it for what he had done and said that day.
He thought he was acting in obedience to his Master`'s requiring,
and there he must leave it.
Although endeavoring to rest in the belief that he
had endeavored to do what he believed was his duty,
he no doubt felt, at times, the want of unity of his friends with his action that day,
and secret exercise and conflict of spirit concerning it.

About a year after the occurrence,
a man whom he met with inquired of him whether he
recollected being at the meeting where it took place.
John readily answered that he did, and that from the singularity of his service in it,
and the reproofs of his friends therefor, he had cause to remember it.
The man then told him that his service that day was in the
ordering of Divine Providence intended for him,
and that it had been the means of saving him from an awful death.
He had been for some time in a low, desponding state of mind,
and had fully intended to take his own life that day.
He had taken a rope to the woods to hang himself, when it was suggested to his mind,
no doubt by the Spirit of the Lord Jesus, the Saviour of men, to go to meeting,
which was held nearby.
With the rope in his pocket with which he intended to carry out his awful purpose,
he went to the meeting.
Whilst pondering over his miserable condition,
and the means of escape therefrom which Satan kept presenting to his mind,
the rap of the cane on the floor aroused his attention,
the exhortation to resist the old adversary that once,
and he should be free from his wicked temptation, took hold of his mind.
It was to him a saving visitation of Divine grace.
He resisted the temptation with success, turned from his purpose,
and found the truth of the promise verified.
He had not since been assailed by that temptation, and was,
through the mercy of the Lord,
enabled to rejoice in his happy deliverance from the dreadful
state of mind he had previously been in.
This declaration, from one who was a stranger to him, gave John, without doubt,
relief from all his misgivings,
and filled him with satisfaction in believing that his faithfulness in an apprehended
duty had been savingly blessed to a candidate for immortality and eternal life.

=== Settling a Difference

Joseph Carrington was a minister, residing in Pennsylvania.
He was not endowed with fine talents, but often showed great weakness.
Though in conversation he was below mediocrity,
yet in preaching the Gospel he was clear and powerful.
To him the Lord was strength in weakness, a present help in time of need.
When on a religious visit to England,
the Friend at whose house he lodged entered his room
one morning and excused himself for leaving home,
which he was obliged to do,
as he was on a committee appointed to endeavor to settle a difference between two Friends.
Joseph said: "`I will rise and go with thee.`"
His host, knowing Joseph was a weak man when left to his own resources,
was afraid to take him with him, lest he should prove a hindrance, and replied: "`No;
thou had best remain here,
and rest thyself;`" but Joseph persisted in getting up and dressing himself,
and they set off on horseback.

They soon had occasion to ford a small river,
when Joseph`'s horse stumbled and threw him into the mud.
"`Now,`" said his friend, "`thou wilt have to go back;
thou cannot continue on in this plight.`"
"`Oh, yes,`" said Joseph, "`I will go on; I cannot return now;
that was an effort of the devil to prevent me from going.`"

On arriving at the appointed place, they found the committee assembled,
and the differing Friends present.
Joseph requested the two Friends to be pointed out to him, and asked them to take a seat,
one on each side of him.
He then turned to one and said: "`Now, John,
let me hear thy story about this difficulty.`"
"`Thomas, thou must not say one word until he finishes.`"
John commenced relating the cause of dissension,
but had not proceeded far before Thomas interrupted with: "`No, that was not so.`"
"`Stop, Thomas,`" said Joseph; "`thou must wait for thy turn to tell it.`"
After a little while, Thomas again contradicted John`'s statement.
"`Hold thy tongue, Thomas,`" said our friend, laying his hand on his knee.
At length John finished his account,
when Joseph turned to the other and told him to begin.
He was soon interrupted by John, who was silenced by being told:
"`Thou hast had thy turn, and I have heard thee patiently;
now thou must let Thomas go on, and thou be silent.`"
When Thomas had proceeded a while, John again denied the statement,
and Joseph desired him to remain quiet.
When Thomas had no more to say, Joseph said: "`John, thou art to blame,
for thou began the difficulty;`" and then explained how all had originated,
and convinced John, who acknowledged he had done wrong, and that he regretted it.
Thomas immediately said: "`I, too, was to blame; if John began wrong,
I was to blame for taking offence at it.
I confess my error, and ask John to pass it by.`"
They both arose and shook hands, and remained good friends ever after.
Thus was settled a difficulty which had caused much
trouble to the meeting for several years.

=== Sermon by James Simpson,Delivered at Frankford, PA., a Few Months Before His Decease

What I am now going to relate is but a simple story,
and it is probable some of you have heard me tell it before;
but it has taken such possession of my mind that
I thought I would just drop it for your consideration.

When I was a young man, there lived in our neighborhood a Presbyterian,
who was universally reported to be a very liberal man,
and uncommonly upright in his dealings.
When he had any of the produce of his farm to dispose of,
he made it an invariable rule to give good measure, over good,
rather more than could be required of him.
One of his friends observing his frequently doing so, questioned him, why he did it?
He told him he gave too much, and said it could not be to his own advantage.
Now my friends, mark the answer of this Presbyterian:
"`God Almighty has permitted me but one journey through the world, and when gone,
I cannot return to rectify mistakes.`"
Think of this, Friends, but one journey through the world;
the hours that are passed are gone forever,
and the actions in those hours can never be recalled.

I do not throw it out as a charge, nor mean to imply that any of you are dishonest,
but the words of this good Presbyterian have often impressed my mind, and, I think,
in an instructive manner.

But one journey.
We are allowed but one journey through the world; therefore let none of us say:
"`My tongue is my own, I will talk what I please: my time is my own,
I will go where I please: I can go to meeting, or, if the world calls me,
I will stay at home; it is all my own.`"
Now this won`'t do, Friends; it is as impossible for us to live as we list,
and then come here and worship, as it is for a lamp to burn without oil.
It is utterly impossible.
And I was thinking what a droll composition man is; a compound of bank-notes, dollars,
cents, and newspapers, and bringing, as it were, the world on his back,
he comes here to perform worship; or, at least, he would have it so appear.
Now, Friends, I just drop this before we part, for your consideration:
let each one try himself, and see how it is with his own soul.

During a time when a pestilential sickness raged in Philadelphia, in the year 1692,
Roger Gill,
a ministering Friend from Great Britain was so dipped into sympathy with the sufferers,
that he had no rest in his mind until he reached that city on the tenth of Seventh Month,
where he entered upon the service of visiting the sick and dying,
and warning and comforting the living.

On the fifteenth, Thomas Story came to the city, who found Roger well, but he says:
"`many Friends on their sick and dying pillows;
and yet the settled presence of the Lord was with them at that time:
such is the goodness of God to his own people,
that in their bodily or any other afflictions,
his holy presence greatly abates the exercises of nature by its Divine consolation.
O,
the love that flowed in my soul to several in the times of my visits
to them! in which I was lifted over all fear of the contagion,
and yet not without an awful regard toward the Lord therein.`"

Roger, in one public meeting, told them that when one hundred miles from them,
his love in the Lord was so great, that had he wings, he would have flown to them.
In another meeting, during the time of the Yearly Meeting,
he was brought on his knees in fervent and devout
intercession with the Lord to stay His hand,
adding if He would please to accept his life for a sacrifice,
he did freely offer it up for the people.

His offer seemed accepted.
The general sickness abated, and he was soon taken down with the disease,
after which time very few died.
As he lay in great pain and affliction of body, he remembered his offering,
and said to Friends around him:
"`It is not in my heart to repent of the offer I have made.`"

He was preserved in cheerful resignation,
notwithstanding the great suffering he was enduring,
and he remained watchful to speak a word in season to those around.
He exhorted Friends to faithfulness, and said:
"`The Lord hath sanctified my afflictions to me,
and hath made my sickness as a bed of down.`"
Some at one time speaking of their hope of his recovery, he said:
"`Truly I have neither thoughts nor hope about being raised in this life;
but I know I shall rise sooner than many imagine,
and receive a reward according to my works.`"

His sickness continued seven days.
A few hours before his death, he took leave of his friends, and said: "`Farewell,
farewell, farewell, forever.`"
He in great peace and sweetness, departed this life, Eighth Month 2nd, 1699.
