== Chapter XX. Social and Conversational

Under date of 1653, Sewell says:

The number of the professors of the Light +++[+++Quakers]
increased greatly, and as it had been said, at first,
that they should be destroyed within a short time,
so now the priests began to say that they would eat out one another; for many of them,
after meetings, having a great way to go, stayed at their friends`' houses by the way,
and sometimes more than there were beds to lodge, so that some lay on the hay-mows.
This made some of the public church grow afraid that this hospitality would cause poverty,
and that when these Friends had eaten out one another,
they would come to be maintained by the parishes, and so be chargeable to them.
But it fell out quite otherwise, for these people were the more blessed and increased,
without falling into want.

This puts me in mind of what one of the daughters of judge Thomas Fell once told me, viz:
That her father having been abroad, and coming home with his servants,
found the shed so full of the horses of strange guests that he said to his wife,
this was the way to be eaten out,
and that thus they themselves should soon be in want of hay.
But to this Margaret said, in a friendly way, that she did not believe,
when the year was at an end, that they should have the less for that.
And it so fell out;
for this year their stock of hay was such that they
sold a great deal of what they had in abundance.
Thus the proverb was verified, That charity doth not impoverish.

The truth of this was also experienced by those called Quakers;
for though many people were shy at first,
and would not deal with them--because of their non-conformity with the vulgar salutation,
and their saying "`Thee`" and "`Thou`" to a single person, instead of "`You,`" etc.;
insomuch that some that were tradesmen lost their customers,
and could hardly get money enough to buy bread--yet this changed in time,
when people found by experience they could better trust to the
words of these than to that of those of their own persuasion.
Hence it was, that often, when any came into a town and wanted something, they would ask,
"`Where dwells a draper, or tailor, or shoemaker, or any other tradesman,
that is a Quaker?`"
Now, the cause of their trade so increasing was,
because they were found upright in their dealings.

In the early days of our Society,
when Friends were everywhere spoken against and persecuted,
a dance or play of some kind was introduced and acted on the stage in the city of London,
which, although almost blasphemous in its parts,
was one in which a striking soul-important truth was set forth.
A person was introduced, intended, with awful boldness,
to represent the Almighty Creator of the world; another was to personify the devil;
others were mortals, seeking to obtain, by petitioning the Dispenser of all benefits,
that which seemed most desirable to them.
Each one was allowed one request, and that one was always granted; one wished riches,
and obtained it: another honor; another revenge on his enemies; at last a poor,
persecuted Quaker was introduced, who asked for "`the kingdom of heaven.`"
When the others found he had obtained it,
with one consent they cried out that they had forgotten the kingdom of heaven,
and wanted that also.
They were told it was too late--their choice was made, and they must abide by it.
At this part of the play, he who represented the devil,
addressing the persecutors of the Quakers, said to this effect:
"`You are fools! you persecute the Quakers, and cast them into prison;
taking away their goods, and living from them,
so that they have no certainty of either liberty or estate;
and that tends to wean them from lower enjoyments, and to keep them low and humble,
which puts them out of my reach.
I will tell you what to do: Let them alone; and, as they are an honest,
industrious people, there will be a blessing on their labors,
and they will grow rich and proud; build them fine houses, and get fine furniture;
and they will lose their humility, and become like other people,
and then I shall have them.`"

During the difficulties prior to the Hicksite separation,
a simple-minded country Friend and a quick-witted infidel
neighbor were thrown together in company with others,
and the infidel was very full in his praise of Elias Hicks.
The Friend could not hear this without showing his dissent,
but he did not go into argument,
wherein he must needs have been worsted by his nimble-tongued opponent.
He did better.
"`Art thou not a believer in Tom Paine?`"
he asked.
"`Yes,`" returned the other, quickly and sharply,
as if he felt himself brought into an awkward position before his neighbors,
and was somewhat irritated.
"`What has that to do in the business?`"
"`Why,`" rejoined his slow-spoken antagonist, in his quiet, methodical manner,
"`if thou art a believer in Tom Paine,
thy praise of Elias Hicks is no great credit to him.`"
The infidel was completely foiled, and he felt it so.
He knew the remark of his antagonist would be deemed
a self-evident truth by those who heard it.
It was a realization of the declaration of the apostle,
that God "`hath chosen the foolish things of the world to confound the wise.`"

John Parker often expressed his opinion that much
of the success of the followers of Elias Hicks,
in spreading a partisan feeling in the Society in his favor,
sprang out of secret misrepresentation made use of by many of them.
On one occasion he said: "`This spirit was like a serpent in the grass,
biting our heels before we knew it.`"

He was led at times to exert himself against the spreading of this spirit,
and also against a spirit manifested by some, and advocated with great earnestness,
to keep quiet, and take no part.
This was then the cry of many who were departing or had departed from the truth of Jesus,
and who, to say the least against them,
were not amongst those who would "`contend earnestly for the faith.`"
On one occasion a person of this class, being at a meeting where John was,
undertook to preach against people being zealous
in the difficulties in which the Society was involved.
He urged his hearers to be quiet; to attend to their own business;
and finally warned them not to put to sea in a storm.
When he was done, John spoke out: "`But what if we are caught at sea in a storm!
No skulking below deck then, Friends.`"

It is stated that the parties to the following poetical
discussion felt a mutual attachment to each other,
and that the only obstacle to a union was a conscientious objection, on each side,
on account of religious sentiments.
One of the parties was a clergyman of the church of England,
and the other was a member of our Society, well known afterwards,
not only among her fellow-members, but in the literary circles of the day,
as Mary Knowles.

=== Clergyman

Hark! how the sacred thunder rends the skies!
"`Repent and be baptized,`" Christ`'s herald cries;
"`Repent and be baptized,`" consenting Heaven replies.
And can Lavinia unaffected hear
This awful message echoing in her ear?
Will my Lavinia unaffected prove
Rebel to God, and faithless unto love?
Say, shall a parent`'s absolute command
The mighty voice of God himself withstand?
Shall heavenly calls to earthly ties give place,
And filial fondness frustrate Christian grace?
Shall human wit Omniscience engage,
Shall Barclay endless war with Jesus wage?
Must each apostle waive his claim to merit;
That Fox may shine first martyr of the spirit?
Must common sense be banished from the soul,
Ere Gospel salve can make the sinner whole?
Must each adept in Calvary`'s great school
Be not in meekness but in fact a fool?
Must Paul at Corinth be a babbler too,
And Peter when a Baptist be a Jew?
Must Phillip`'s process be superfluous thought,
Because he washed the eunuch he had taught!
Must feudal rites be metaphored away,
And actual homage construed disobey?
Such juggling arts may change each part of speech,
Make water spirit, and baptize, to teach;
But if such jargon Jesus represents,
The light, indeed, is only lent to saints,
Then in the letter, double death we find;
And Christ in figure only saved mankind.

=== The Answer

Hark! how the sacred thunder rends the skies,
"`Repent and be baptized,`" Christ`'s herald cries!
"`Repent and be baptized,`" consenting Heaven replies.
The Christian`'s heart reveres the solemn sound;--
And deeply humbled treads the sacred ground;
Owns the injunction`'s undisputed claim,
Its awful import and its glorious aim!
But here a difference mutual zeal excites,
You plead for outward, we for inward rites.
We think the Gospel`'s hallowed page inspires
Superior efforts, nor one type requires;
Since no lavation can effectual prove,
The innate stain of nature to remove.
No mode of words can heavenly grace impart
To an infantile and unconscious heart;
Hence we, as vain and useless, disallow
The faithless surety, and unbinding vow,
As empty shadows, which men may observe,
Yet from the substance in their conduct swerve;
While superstitious rites their time divide,
They cease to follow their internal guide;
Enslaved by canons, and the various rules
Of councils, synods, colleges and schools,
Thus might mankind (for priests an ample field),
To circumcision`'s ancient custom yield;
And thus by like authority `'tis meet,
These holy fathers kneel to wash our feet,
`'Tis thus that holiness to form gives place,
And solemn triflings "`frustrate Christian grace.`"
In Jordan`'s pool well pleased the Almighty saw,
His Son beloved submitting to the law.
But his apostles through the world He sent,
With a baptising power beyond the element,
This power does all true ministry attend;
`'Twas promised, and will never have an end;
This mighty power his herald did proclaim,
"`He shall baptize you with an holy flame,`"
Yet water was in use an ancient rite,
Of old the common way to proselyte;
But no dependence placed thereon you`'ll see,
And Paul and Peter in this point agree.
The real Christians with illumined thought,
View Truth unbiased as its author taught,
No typic observations are revered,
Since their immortal antitype appeared,
Fox preached this doctrine to a seeking age,
It shines in Barclay`'s unrefuted page,
Simple their schemes, no mean self-love they knew,
But freely preached without a sordid view;
With hearts devoted, Gospel truths displayed,
And scorned to make divinity a trade;
No juggling arts e`'er used, no low disguise
O`'er obvious texts, and sense to tyrannize,
Discerning Truth by its own native light,
And by its guidance practised what was right,
This state attained, external rites no more
Demand observance as in days of yore--
`'Tis grace alone, we by experience find,
Imparts instruction to the attentive mind;
Convicts of error, and restrains from sin;
For what these are it manifests within;
Each wayward passion by its aid subdued,
The soul`'s enthroned in native rectitude;
Cleansed of its stains, and sprinkled from above,
With pure descendings of atoning love,
A baptism this, essential you will find,
Or, "`Christ in figure only saves mankind.`"
`'Tis this alone my suppliant spirit craves,
Since but one _Lord, one Faith, one Baptism_ saves.

In the Journal of John Churchman, the following anecdote is inserted:

Before going to Holland,
I was several times in the shop of a barber in this city (Norwich, England),
to be shaved.
The second time I was there I had to wait awhile for my turn, he having no assistant;
and when others were gone out, he told me he was very sorry I had to wait,
and hoped he should have my custom; and that if I would come on Saturdays and Wednesdays,
in the forenoon, I need not wait, but in the afternoon others came.
I asked him what days of the week those were which he called Saturdays and Wednesdays.
He seemed to wonder at my ignorance, but knew not how to tell me otherwise.
I said: "`I do not read in the Scriptures of any days so named.`"
He replied: "`That is true.`"
"`For what reason, then,`" said I, "`dost thou call them so?`"
"`Because it is a common custom,`" said he.
"`Suppose, then,`" said I, "`that we lived in a heathen country, among infidels,
who worshipped idols, should we follow their customs because common?`"
He replied: "`By no means.`"
I then said: "`If I have understood rightly,
the heathens gave the days of the week those names.`"
"`I never heard that before,`" said he; "`pray, for what reason?`"
I answered: "`They worshipped the sun on the first day of the week,
and named it after their idol, Sun-day; the moon on the second day of the week,
so came Monday; and the other days after other idols, for they had many gods;
Third-day they called Tuesday, after their idol tuisco;
and after the idol woden they called Fourth-day Wednesday; and Fifth-day,
after their idol thor, they called Thursday; from friga, Friday, and, after Saturn,
they called the seventh day Saturday.
As I believe in the only true God, and Jesus Christ, whom He hath sent,
and expect eternal life by no other name or power, I dare not, for conscience`' sake,
own the gods of the heathen, or name a day after them,
but choose the names which the days were called by
when the Most High performed his work of creation,
viz: first, second, third, and so on, which is Scriptural,
most plain and easily understood.`"
He seemed affected with the information,
and I desired him to inquire into the matter for himself,
and not to think that I designed to impose upon him.

On a subsequent visit, the conversation turning upon the study of algebra,
in which the barber was engaged,
John Churchman availed himself of the opportunity of turning the attention of
this inquiring man to the far greater moment of a more profitable and delightful
study--that of being quietly employed in learning the law of the Lord,
written in our own hearts, that we might be enabled to walk acceptably before Him.

He says:

On my return from Scotland to Norwich, a man ran to me in the street,
putting a paper in my hand, and immediately left me, whom I soon found to be this barber.
The letter contained an innocent,
childlike acknowledgment to me for my freedom with him, as is before mentioned,
in language rather too much showing his value for me as an instrument;
and believing him to be reached by the love of Truth, and in measure convinced thereof,
I thought it best to leave him in the Lord`'s hand for further instruction;
to learn by the immediate teachings of the Holy Spirit,
that his love might be centered on the true Beloved of souls;
for want whereof many are hurt looking outward and growing in head knowledge,
seeking the esteem and friendship of man.

=== The March of Refinement

Sons and daughters of Fox, from your slumbers awake ye,
No longer in listless indulgence recline!
From the fetters of sloth and luxury break ye,
And put on your beautiful garments and shine!

Time was when your fathers, in wisdom grown hoary,
In their doublet of leather, the pilgrim`'s rude guise,
Contemning the pride of this world and its glory,
Pursued their rough path of reproach to the skies.

Unletter`'d as they who on Judah`'s lone mountain,
By her wind-ruffled lake, in deep forest or den,--
Drawing waters of life from salvation`'s blest fountain,
Surrounded the houseless Redeemer of men.

Your sires, by his spirit`'s blest influence guided,
Regardless of dangers, of prisons, and death;
Alike by the sage, and the trifler derided,
Look`'d o`'er this vain world with the keen eye of faith.

From the lure of false glory, false happiness, turning,
With the courage of martyrs they follow`'d their Lord;
Their loins girded close, and their lamps brightly burning,
Unceasing they publish`'d his life-giving word.

Those days are long past, and new light rises o`'er us,
No longer we suffer such hardship and loss;
The "`March of Refinement`" now opens upon us,
And points other ways, than the way of the cross.

No longer we talk of meek, patient endurance,
Of low self-denial and watchful restraint:
But of confident hope, and exulting assurance,
And the triumphs that wait on the steps of the saint.

Knowledge waves her light wand, and poor wandering mortals,
No longer a rugged and thorny road trace;
The gate that was strait now unfolds its wide portals,
The way once so narrow, expands into space.

Religion has softened her features; around her
The attractions of taste and of fancy are shed;
The arts with their graceful adornments surround her,
And weave a rich veil for her delicate head.

Our maidens, no longer the homely task plying,
That once could engage the grave matrons of yore,
Are all in each liberal accomplishment vying,
And high on the pinions of sentiment soar.

`'T is true there are some who, these flow`'ry paths fearing,
Again and again tell us plainly we stray;
Who the standard of ancient simplicity rearing,
Exhort us to pause, and consider the way.

But many, tho`' granting their honest intentions,
Deem them rigid and narrow, of prejudic`'d mind,
And believe that `'midst thousands of modern inventions,
Some happy expedient yet we shall find,--

To reconcile things in their nature discordant,
Inclination and duty no longer at strife;
Religion with luxury kindly accordant,
The peace of the soul, with the pride of this life.

Vain hope of blind man! in his fond self deceiving,
Whilst immutably true stands the Saviour`'s own word;
Happy they, who, its sacred assurance receiving,
In lowliness follow their crucified Lord.

=== My Psalm

J+++.+++ G. Whittier

I mourn no more my vanished years:
Beneath a tender rain,
An April rain, of smiles and tears
My heart is young again.

The west winds blow, and singing low
I hear the glad streams run;
The windows of my soul I throw
Wide open to the sun.

No longer forward nor behind
I look in hope and fear,
But, grateful, take the good I find
The best of now, and here.

I plough no more a desert land,
To harvest weed and tare;
The manna, dropping from God`'s hand,
Rebukes my painful care.

$$.$$
I break my pilgrim staff;
I lay
Aside the toiling oar;
The angel sought so far away
I welcome at my door.

The airs of spring may never play
Among the ripening corn,
Nor freshness of the flowers of May
Blow through the autumn morn;

Yet shall the blue-eyed gentian look
Thro`' fringed lids to heaven;
And the pale aster, in the brook
Shall see its image given;

The woods shall wear their robes of praise,
The south wind softly sigh,
And sweet, calm days in golden haze
Melt down the amber sky.

Not less shall manly deed and word
Rebuke an age of wrong;
The graven flowers that wreath the sword
Make not the blade less strong.

But smiting hands shall learn to heal,
To build as to destroy;
Nor less my heart for others feel
That I the more enjoy.

All as God wills, who wisely heeds
To give, or to withhold,
And knoweth more of all my needs
Than all my prayers have told!

Enough that blessings undeserved
Have marked my erring track--
That whereso`'er my feet have swerved,
His chastening turned me back--

That more and more a Providence
Of love is understood,
Making the springs of time and sense
Sweet with eternal good--

That death seems but a covered way
Which opens into light,
Wherein no blinded child can stray
Beyond the Father`'s sight--

That care and trial seem at last
Through memory`'s sunset air,
Like mountain-ranges overpast,
In purple distance fair--

That all the jarring notes of life
Seem blending in a psalm,
And all the angles of its strife
Slow rounding into calm.

And so the shadows fall apart,
And so the west winds play;
And all the windows of my heart
I open to the day.

=== The Friend`'s Burial

J+++.+++ G. Whittier

My thoughts are all in yonder town,
Where, wept by many tears,
Today my mother`'s friend lays down
The burden of her years.

True as in life, no poor disguise
Of death with her is seen,
And on her simple casket lies
No wreath of bloom and green.

O not for her the florist`'s art
The mocking weeds of woe,
But blessings of the voiceless heart,
The love that passeth show!

Yet all about the softening air
Of new-born sweetness tells,
And the ungathered May-flowers wear
The tints of ocean shells.

The old, assuring miracle
Is fresh as heretofore;
And earth takes up its parable
Of life from death once more.

Here organ swell and church-bell toll
Methinks but discord were,
The prayerful silence of the soul
Is best befitting her.

No sound should break the quietude
Alike of earth and sky;
O wandering wind in Seabrook wood,
Breathe but a half-heard sigh!

Sing softly, spring-bird, for her sake,
And thou not distant sea,
Lapse lightly as if Jesus spake,
And thou wert Galilee!

For all her quiet life flowed on
As meadow streamlets flow,
Where fresher green reveals alone
The noiseless ways they go.

From her loved place of prayer I see
The plain-robed mourners pass,
With slow feet treading reverently
The graveyard`'s springing grass.

Make room, O mourning ones, for me,
Where, like the friends of Paul,
That you no more her face shall see
You sorrow most of all.

Her path shall brighten more and more
Unto the perfect day;
She cannot fail of peace who bore
Such peace with her away.

O sweet, calm face that seemed to wear
The look of sins forgiven!
O voice of prayer that seemed to bear
Our own needs up to heaven.

How reverent in our midst she stood,
Or knelt in grateful praise!
What grace of Christian womanhood.
Was in her household ways!

For still her holy living meant
No duty left undone;
The heavenly and the human blent
Their kindred love in one.

And if her life small leisure found
For feasting ear and eye,
And pleasure, on her daily round,
She passed unpausing by.

Yet with her went a secret sense
Of all things sweet and fair,
And beauty`'s gracious providence
Refreshed her unaware.

She kept her line of rectitude
With love`'s unconscious ease;
Her kindly instincts understood
All gentle courtesies.

An inborn charm of graciousness
Made sweet her smile and tone,
And glorified her farm wife dress
With beauty not its own.

The dear Lord`'s best interpreters
Are humble human souls;
The Gospel of a life like hers
Is more than books or scrolls.

From scheme and creed the light goes out,
The saintly fact survives;
The blessed Master none can doubt
Revealed in holy lives.

=== Anecdote of John Parker

One day,
having been favored to preach the Gospel with an unusual
degree of the demonstration of the Spirit and power,
on leaving the door of Kennet Meetinghouse, he,
as was frequently the case with him under such circumstances, appeared very cheerful,
shaking hands with,
and addressing some pleasant remark to each person as he passed along.
One of his sober neighbors, not a Friend, who had been at meeting that morning,
stood a little back from the crowd,
with much solemn gravity expressed in his countenance,
viewing John`'s cheerful progress among his friends.
When John reached the spot where he stood, the neighbor, taking his offered hand, said,
"`Mr. Parker, I do marvel how you can be so lively and pleasant,
immediately after having been so favored as you have been this morning,
whilst engaged in the solemn and awful work of the ministry.`"
After a short pause, John said, "`I find I can raise a variety of crops,
and keep different kinds of animals on my small farm, by keeping good,
strong fences between the different fields,
so as to confine everything to its proper place.`"
"`I see,`" answered his neighbor, "`that much depends upon good,
strong fences to keep everything in its proper place, and that there is, in fact,
but a step from one field of labor to another.`"

It is probable that neither John Parker nor his neighbor were hurt by this little colloquy.
The religion of our Lord and Saviour Jesus Christ is not a gloomy one,
and those who have felt their blessed Master`'s presence
crowning their labors in his cause,
have the privilege of feeling inward peace and manifesting outward cheerfulness.

=== Lines Composed on Travelling Through a Snow-Storm to Attend Caln Quarterly Meeting, in America, Second Month, 1817, by Mary Naftel

Through woods and wilds, o`'er hills and dales I stray,
From Albion`'s fertile valleys far away;
From Albion`'s Isle, the land that gave me birth,
Land most endeared of all the spacious earth,
That still contains what on it most I prize,
Joy of my heart, and pleasure of my eyes,
My loved companion and my children dear,
In climes remote but in remembrance near.
My spirit often seems with yours to greet,
And wafted home in retrospect we meet.
Your joys are mine, your cares are still my cares,
Your God is mine, to Him ascend my prayers,
As incense offered at his sacred throne,
That He might make and take us as his own,
Within his safe enclosure ever keep,
Lambs of his fold and of his flock the sheep;
That through all dangers we may fully prove
The sure protection of Almighty love,
The sure protection of that Arm Divine,
Which only, Oh Omnipotence, is thine!
That on the rock or on the boisterous deep,
On mountains high or hollow vales can keep,
Ride on the winds and make the clouds his way,
Give songs by night, turn darkness into day.
Cause these the dust but of his feet to prove,
His harbingers of mercy and of love.
Still to my feeble prayer, oh! Condescend,
Be thou my guide, my counsellor and friend,
And safe conduct me to the journey`'s end;
That praise and glory only may be Thine,
And peace and gladness be forever mine.

=== Sarah Cresson

Melodious singer of heart-thrilling songs,
Of Zion`'s injuries and Israel`'s wrongs,
Whose lonely harp still on the willow hung,
`'Till fresh-felt mercies every chord restrung;
Then touched to praise its tones in sweetness broke,
That in each heart responsive feelings woke!
Oh, I behold thee, as I last beheld,
When Gospel love thy grateful bosom swelled,--
When weeping listeners heard the tale of woe,
Of mental conflicts it was thine to know,--
When as a flood the enemy came in,
With doubts and reasonings, implements of sin,--
When from a pit of horror burst thy moan,
Illumined by no brightness from the throne,--
When sombre shadows compassed thee around,--
When Satan`'s legions pierced with many a wound,--
When the rank weeds were wrapped about thy head--
When boisterous billows over thee were spread,--
Then He who died and triumphed o`'er the grave,
Arose in might thy struggling soul to save;
Bade the waves sunder and temptations fly,
The scattering clouds haste from the brightening sky,
The sun of righteousness with cheering ray,
Shed the full radiance of perfected day.
Then from thy lips burst forth a joyful song
To thy Redeemer!--yea, it poured along
In most melodious energy of praise
To God, the Saviour, Him of ancient days,
The heart and language rising with the theme,
Till praise gushed forth one living, glowing stream!
Then from thy lips the thrilling language fell,
"`Glory to Him who raised my soul from hell!`"
Baptized in tears was many a cheek that day,
As Sarah Cresson told her chequered way,
`'Twas her last Gospel labor here of love,--
Mercy soon gathered her to praise above.

=== The Deserted Meetinghouse

This sketch refers to Upper Springfield Meetinghouse, Burlington County, N. J.,
and was written by Dr. Joseph Pancoast, a distinguished surgeon of Philadelphia, who,
when young, belonged to and attended that meeting.

"`How few the years that youth and age divide,
And yet of startling change how sadly rife!`"
Thus, o`'er a blighted shrine, a pilgrim sighed,
Where crowds had worshipped in his spring of life.

The ancient fane in Druid loneness stood,
Just as of yore, on gently rising ground,
Within the precincts of a sheltering wood,
Whose leafy limbs seemed still to clasp it `'round.

Forlorn it looked along the public way;
No wall begirt it, no protector nigh;
Its roofless sheds, fast tumbling to decay,
Matched well the tottering graveyard fence hard by.

The approaching paths, where busy feet once trod,
Uncalled by tolling bell at meeting-tide,
Still faintly ran beside the grass-grown road
Whence country grandeur came in Sabbath pride.

By none molested, visited by few,
With unresisting doors and crumbling wall,
The sacred awe its ancient memories threw,
Alone remained to shield it in its fall.

Yet still the oaks their wealth of leaves renewed,
Where "`early-comers`" once, within their shade,
With studied courtesy and voice subdued,
Their stores of knowledge modestly displayed.

The interest grew with each accession there,
Till entering, passed the Christian fathers by,
With looks ecstatic, as of coming prayer,
About to plead for mercies from on high.

Then, half-reluctant, though by duty led,
The young, in whispering converse, neared the door,
And soon each one stole in on tip-toe tread,
Afraid to wake an echo from the floor.

On either hand the dais-like galleries rise;
There were the elders of each sex arrayed,
With serious mien, but keen, observant eyes,
The youth surveying, and by them surveyed.

No vocal hymns, no organ, pealing loud,
No bustling verger, no robed priests were there,
No separate altar, veiled in incense cloud--
But all, as equals, joined in silent prayer.

A solemn hush o`'er all the assembly stole;
Each scanned the past, and sought, as guiding light,
The still small voice, that Mentor of the soul,
By great Elijah heard on Horeb`'s height.

Not that the stringent rules the old had made
Could always curb the errant thoughts of youth,
Or those of other sects, who came and prayed
With men they honored as the types of truth.

Oft must youth break the forms the old obey;
Slight causes there might serious thoughts restrain,
As bright eyes glancing o`'er the passage-way,
Or prisoned insects whirring `'gainst the pane.

Soon fled such lightness when the speaker rose,
Whose touching eloquence could quickly bring
All hearts to sorrow o`'er the Saviour`'s woes,
Or plead, self-humbled, with Judea`'s king.

The meeting closed, with mutual greetings shared,
The stately seniors, then emerging slow,
Paused oft to question how the absent fared,
And on the sick their sympathies bestow.

Not so the young, elastic as a spring
From strong constraint released, rebounds the more--
They gaily chat, or boldly venturing,
Accost the gentle maidens at the door.

So `'twas in old and better times: Alas!
That troublous themes, bewildering earnest men,
Should through that realm of peace resistless pass,
And break the bonds of brotherhood in twain.

Ah! happy days, thus sadly brought to mind;
Ah! hapless house, whose worshippers are fled,
Or of their jarring creeds oblivious, find
A quiet meeting-place among the dead.

For where are they, those seniors of old time?
Where--he of grave four-score, the first in place,
Whose froward youth in wildness spent, not crime,
Had ploughed deep furrows on his rugged face?

And he whose lofty faith and sombre mind
Awed all the weak, and oft repressed the bold,
Severely just, yet generously kind,
An ancient Cato, in a Christian mold?

And he, of massive form, and bearded face,
Who, like old Chronos, in grey marble wrought,
Sat, grim and still, in one unvaried place,
Yet revelled in fantastic fields of thought?

And they, most prized, whom gushing memory here
With many a sweet yet painful thought revives,
Whose loving hearts, in their parental sphere,
Poured floods of happiness on younger lives?

Yes, where are they? Where, too, their brethren, now?
Those plain exemplars of unconscious worth?
Move--scarce a bow-shot forth--and humbly bow,
For there they slumber in one common earth.

Few lettered stones, no mouldering vaults are there--
Round kindred groups of graves the pathways run--
No monumental marbles chill the air
Or check the radiant glories of the sun.

Hearts that ache most, grieve least to outward show,
And for the loved and lost, too deeply mourn,
To rear such pageant mimicries of woe,
As broken shaft, inverted torch or urn.

There, `'round each grave the sunbeams freely play,
The zephyrs softly waves its tufts of green,
And save the coy wood-robin`'s plaintive lay,
No sound disturbs the silence of the scene.

An hundred years had Death his harvest there,
Of those whose fame yet sanctifies his ground,
For gravesmen, with hereditary care,
Keep fresh the story of each cherished mound.

Seek ye their monuments? Look the country o`'er,
And know that all men called them wise and just;
Learn how in reverence held the names they bore,
In new lives spring, like blossoms from the dust.

What broad domains they tilled when strong and young--
What kindness showed to those of humbler state--
What maxims left couched in their dulcet tongue,
With fond remembrance many still relate.

See these poor graves! revered by all around
No mirth profanes, no reveller comes this way;
With bated breath each pilgrim treads the ground,
And sorrowing, views the ancient shrine`'s decay.

Deem we not well such memories of the dead,
May stone outweigh in tributary worth,
And o`'er their slumbers holier halos spread
Than towering pyramids or piles of earth?

At a social gathering of members of our Society, at Haddonfield, N. J.,
at the time of the Quarterly Meeting,
reference was made by one of the company to the honest boldness of John Roberts,
in his conversation with the bishop of Gloucester, as related in his Memoirs.
He had told the bishop that the religion of the Quakers
was of greater antiquity than that of the church of England,
for it was set up by Christ himself more than sixteen hundred years before,
when He taught the woman of Samaria that God is a Spirit,
and they that worship Him must worship him in spirit and in truth.

"`This,`" said John, "`is our religion,
and hath ever been the religion of all those who have worshipped
God acceptably through the several ages since,
down to this time,
and will be the religion of the true spiritual worshippers of God to the world`'s end;
a religion performed by the assistance of the spirit of God, because God is a Spirit;
a religion established by Christ himself, before the mass-book,
service-book or directory, or any of those inventions and traditions of men,
which in the night of apostacy were set up.`"

The bishop replied, "`Yours is the strangest of all persuasions,
for though there are many sects (which he named),
and though they and we differ in some circumstances, yet in fundamentals we agree as one.
But, I observe, you, of all others, strike at the very root and basis of our religion.`"

John Roberts.--Art thou sensible of that?

Bishop.--Yes, I am.

John Roberts.--I am glad of that, for the root is rottenness,
and Truth strikes at the very foundation thereof.

He further told the bishop that the clergy pretended to know more of light,
life and salvation, and things pertaining to the kingdom of heaven, than others;
"`But here you keep us always learning, that we may be always paying you.
Plainly it is a very cheat.
What! always learning, and never able to come to the knowledge of God!
Miserable sinners you found us, and miserable sinners you leave us.`"

The bishop, who seems to have been a man of considerable nobility of character,
did not take offence at John`'s plain dealing, but evidently respected his integrity.
Indeed it is probable he enjoyed the original and
straightforward way in which John expressed himself,
although he may have winced somewhat at the home-thrusts he received.

The relation of John Roberts`' experience was followed
by some incidents from the life of Thomas Story,
who sometimes found it to be his duty to administer reproof.
After he had become convinced of the truth as held by Friends, he says:
"`At one time there came a priest into the company where I was, and I, being silent,
and the rest cheerful in their way; he, being a wanton, airy man, and a little in drink,
observing me, cried out in a scoffing manner, '`What have we got here;
one of the holy brethren?`' I returned upon him,
'`What! art thou a teacher of the people, and scoffest at holiness?
What canst thou teach,
since thou art void of a qualification indispensably
necessary to that work?`' Upon which,`" says Thomas,
"`he became so uneasy and downcast that he could no longer stay in the room,
but went off troubled.`"

Thomas Story`'s father took in a poor priest to live in the family,
for his better accommodation; and one day, when there was a goose on the table at dinner,
the priest, intending to disappoint Thomas of a share of it,
whispered to him so loud that all about the table heard him,
"`This is a tithe goose,`" thinking that he would, for conscience,
abstain from touching it.
Thomas replied, "`Let him look to the evil of that to whom it is a tithe;
but to me it is no tithe, but a goose only; and with my father`'s leave,
I will take a share.`"

When in London, Thomas went with an older brother to call upon a near relative,
where he met with a priest, who was a stranger to him.
Thomas says:

This strange priest, not knowing the relation among us,
and looking upon me as a bird of a different feather,
began to peck at me by several sour hints, which showed his dislike of my company; which,
for conversation sake, I passed by.
But my forbearance and silence encouraging him to be a little bolder,
at length he moved a plain accusation, and said: "`You deny the ordinances of Christ,
water baptism and the Lord`'s supper.`"

I replied, "`Thou hast not heard me say anything on these subjects;
how dost thou therefore know what I deny or affirm?`"
Then said he, "`I perceive you are one of a sect that does deny them.`"
"`What authority hast thou,`" said I, "`for water baptism?`"
He was ready with that much mistaken text, "`Go ye, therefore, and teach all nations,
baptizing, etc.`"
"`This,`" said I, "`was a commandment given by Christ to his apostles;
but dost thou think this is a command to thee,
for thou seems to be a teacher of the people; hast thou any authority by this text?`"
Upon this he hesitated a little, and the justice began to smile.
The pause being over, the priest answered, "`Yes.`"
"`Then,`" said I, "`how many nations hast thou travelled through in this work,
how many taught and baptized?`"
His countenance began a little to alter, and then he replied,
"`I have never been out of England.`"
My next question was,
"`In how many counties of England hast thou travelled in this service?`"
He answered, he had not travelled any on that account.
"`Then,`" said I, "`Thou wicked and slothful servant,
out of thy own mouth shalt thou be judged.
Thou hast here affirmed before these witnesses that the Lord Jesus
Christ hath commanded and sent thee to teach and baptize all nations,
and thou art set down in a corner, and hast not baptized any one;
for thou must understand, friend, that sprinkling an infant is no baptism,
either in mode or subject.`"
Upon this the counsellor laughed outright and the other priests smiled.
Then said he, "`Sir, this gentleman is my near relation.
You will get nothing by meddling with him on these subjects.`"
So the matter dropped.

Still another incident in the experience of Thomas Story was revived,
in which he was led, in right authority,
closely to reprove an unfaithful professor of the same doctrines as himself.

At a meeting in the city of Bristol, where many people of other societies were present,
he says:

It became my concern, from the Spirit of Truth, to stand up therein,
with this prophecy of the apostle,
"`For the time will come when they will not endure sound doctrine;
but after their own lusts shall they heap to themselves teachers, having itching ears;
and they shall turn away their ears from the truth, and shall be turned unto fables.`"
I proceeded to observe to the auditory "`That this prophecy
is clearly fulfilled in this and other nations at this day,
all the several sects adopting to themselves certain notions,
principles and systems of religion, or what they call so,
make choice of such teachers as will teach and propagate these notions and no other,
and will pay such teachers; these at the same time are rejecting and despising the pure,
perfect and effectual teachings of the grace of God;
which have been publicly and freely preached in this
and some other nations now nearly a full century,
and still are unto this day;
contrary to the kind and merciful invitation and
expostulation of the Almighty where He saith,
by his evangelical prophet, Isaiah, '`Ho, every one that thirsteth,
come ye to the waters; and he that hath no money, come ye, buy and eat; yea, come,
buy wine and milk without money and without price.
Wherefore do ye spend money for that which is not bread,
and your labor for that which satisfieth not?
Hearken diligently unto me, and eat ye that which is good,
and let your soul delight itself in fatness.
Incline your ear and come unto me; hear and your soul shall live,
and I will make an everlasting covenant with you, even the sure mercies of David.
Behold, I have given him for a witness to the people,
a leader and commander to the people.`' It is to Him, the Lord Jesus Christ alone,
that we have ever directed mankind,
that they may be taught by his grace and Holy Spirit in their own hearts,
and redeemed from all the hireling teachers in the world.`"

Some days after this sermon was delivered, a man,
"`rich and high in the world,`" who professed to be a Friend,
yet secretly supported the priests by paying their demands,
told Thomas Story that he had done harm by his discourse, and that he had heard some say,
"`Thou deserved to be pelted for meddling with their religion,
which did not concern thee;`" with other matters of like import.
Thomas replied, that he and such violent persons as he spoke of,
had no true judgment as to the root or commandment from
which those matters had been uttered in the meeting;
and that their language showed that the Scriptures quoted were justly applicable to them,
"`and to thyself too, as of the same spirit and work with them.`"
And he added:

"`It is my work and business, as often as I have the same authority,
in the life of the Divine, eternal Truth, to expose all false teachers and hirelings,
as also all hypocrites, and covetous, presumptuous worldlings among ourselves,
who give their souls up, in a manner insatiable, to the gains of this world,
without any bounds, and then intrude themselves into the affairs of the church of God.
Such take upon them to act according to the weight of their worldly gains,
and not of the balance of the sanctuary; in which they are lighter than vanity,
or the small dust that weighs nothing.
And such an one art thou.`"
With more to the same effect; which was not pleasing, yet being his due,
I did not think proper to defraud him of it.

Though one illustration of the manner in which the servants
of Christ are sometimes led to reprove that which is evil,
naturally suggested other incidents of a similar character,
yet the reader must not suppose that no other topics of conversation were introduced
during the pleasant social intercourse connected with the Quarterly Meeting of Haddonfield.
Among other things that were related, was an anecdote of a ministering Friend in England,
who felt a concern some years ago to hold a public
meeting in the southwestern part of that country.
As the time drew nigh, he became much discouraged at the prospect,
and reasoned within himself, that the Methodists,
to which class most of the people who would assemble belonged,
were already a good kind of people; and that if the meeting were held,
although they might be satisfied with the opportunity,
yet in a few days the impression would all pass away;
so that no permanent good would be done.

While under these depressing feelings (probably a permitted baptism
to humble the creature and prepare it for the appointed service),
as he was passing along the public road, he saw a worthy Methodist, whom he knew,
breaking stones by the way-side.
On entering into conversation,
the laborer told the minister that he was then reading a book written by Samuel Rundell,
a member of our Society, which he had borrowed of an acquaintance.
When asked if he was acquainted with the author, he replied, that he knew him,
that Samuel Rundell had had a meeting about thirty-five
years before in his father`'s kitchen,
that on that occasion he had opened some passages of Scripture
in a manner that presented them to him in a new light,
and that something he then said had always remained with him.

This testimony to the permanent fruit of seed sown under Divine direction,
had a cheering effect on the mind of the minister,
who went on his way with faith revived.

Another pleasing anecdote was told of this same Methodist stone-breaker.
A clergyman had married a wealthy wife and became a landed proprietor in his neighborhood.
He had laid out a winding road of nearly a mile in length through his woodland and grounds,
and had bestowed uncommon pains in having it well graded, stoned and gravelled.
He was very proud of his road,
and called in his poor Methodist neighbor to see and admire it.
Richard, for that was the first name of the poor man, after examining the work,
said it was a good road.
This seemed very faint praise to the owner,
who expected a reply with stronger expressions of admiration.
So he dilated upon its merits, said it was a very fine road,
and queried whether his neighbor had ever seen one as good.
Richard replied that it was a very fine road,
but since he had been asked a direct question, he must say,
that he had seen a better one; and that was the road to the kingdom of heaven,
into which he had been favored to enter,
and in which he had been endeavoring to walk for many years!

This anecdote called up one somewhat similar,
in which "`Billy Bray,`" a somewhat famous local preacher among the Methodists of Cornwall,
in like manner took advantage of a simple incident to turn
the thoughts of those around him from earth to heaven.
Some of the family of one of the gentry of his neighborhood, were about to ride out,
and several of the poor people had collected to look at them and their equipage,
influenced by curiosity,
and that feeling of reverence for the aristocracy
prevalent among many of the lower classes in England.
Billy was passing by, and was asked if he would not like to ride in so fine a carriage.
He replied: "`No; he had no such desire.
That carriage would wear out; after awhile its wheels would give out,
the linings would become faded and torn, and it would all go to ruin.
But the carriage in which he was travelling to heaven, would never become old,
but would always remain as strong and good as it was now!`"

=== An Evening`'s Conversation

The opportunity for social converse among Friends from different neighborhoods,
who have been drawn to one spot to attend a Yearly Meeting of Friends,
is one of the pleasant features connected with such gatherings;
and it may be profitable also, if the exhortation of the apostle is heeded,
"`Let your speech be alway with grace, seasoned with salt.`"

During a late Yearly Meeting of Philadelphia, a number of Friends,
perhaps from fifteen to twenty, spent an evening together in that city.
They were of various ages, including both young and old.
The conversation was general in its character,
and the anecdotes and illustrations were largely of Friendly reminiscences.

The kind and restoring spirit in which reproof should be administered, was spoken of;
and,
in illustration of the different effects produced by harsh
and mild treatment of those who had gone astray,
one of the company gave an outline of an experience which he had heard the person concerned,
describe in a meeting.
He was a Friend who in early life had wandered far from the right path,
had gone to Iowa to reside, and there had kept on in the path to ruin,
both morally and financially.
Finally, he concluded to return to his former home,
and see whether he could there find any opening for business.
After his return, he was visited by one who told him,
he understood that he was a very bad man,
and that there seemed to be but little hope of his reformation.
The reproaches thus injudiciously heaped upon him, aroused an angry feeling,
and he retorted with much sharpness.
After this interview he determined to go to some strange locality.
But before leaving home, he was called upon by another person,
who addressed him in a very different spirit;
saying that he had been thinking much about him,
and he believed there was still hope for him, if he would strive against his temptations,
and walk in the right way.
This kind and encouraging visit was very helpful;
and he regarded it as the turning point in his life.

Another of the company described the effect produced by honest but tender labor,
with one who had fallen into the habit of using profane language.
The Christian interest for his best welfare, kindly conveyed,
had resulted in the reformation of the offender,
who had ceased from this offensive and evil practice.

Although plain dealing with offenders is often called for,
yet he who administers ought to be watchful that his own spirit is kept in subjection.
Of this need John Churchman had an instructive experience.
He mentions, in his Journal, being at a meeting where, he says:
"`With a zeal that exceeded my childish knowledge,
I laid on some strokes with the strength of the man`'s part,
more than with the humbling power of Truth.`"
When he sat down, he felt himself left in great darkness.
He saw that he had been too zealous and forward,
and had to wade through a sorrowful dispensation, which was very humbling,
yet profitable.
He makes the following comment on the occurrence:
"`If we deliver hard things to the people,
we should ever remember that we are flesh and blood,
and by nature subject to the same frailties;
this would lead us closely to attend to the power,
and to minister only in the ability of Truth, in the meekness,
gentleness and wisdom which it inspires.`"

The experience of John Churchman in this case no doubt prepared him to caution others;
for he had been on that sandbank himself.
The word "`sand-bank`" alludes to an anecdote, related by one of the company,
of a captain of a vessel who needed a pilot to guide
him in the navigation of the Delaware River and Bay.
Two persons applied for the position;
one of whom said he had been for years in the business,
and never yet had grounded on a bank.
The other said he had been on every bank and bar in the river.
"`You are the man for me,`" said the captain, "`for you must know where they all are.`"
This anecdote has an instructive application, if it is confined within just limits.
It would be a great mistake for any one to do wrong in order
to be prepared to caution others against the same evil course;
yet, where a wanderer in sinful ways has been brought back to the heavenly fold,
the sense of the loss he sustained, and the misery he endured,
may render him doubly cautious,
and give to his exhortations to other sinners a degree of tenderness,
earnestness and sympathy,
which could scarcely be felt by one who had not trodden in the same path.
Thus it sometimes pleases our Heavenly Father to overrule evil for good, and to make use,
in the accomplishment of his purposes, of those who, at one time,
were disobedient to his will.

In connection with the subject of discourse, an anecdote was told of Richard Jordan.
Two young men from Philadelphia came over to the meeting at Newtown, N. J.,
where Richard belonged, and behaved themselves quite indecorously;
so that Richard felt it needful to give them a hint.
Even this did not suffice to tame their unruly spirits,
for after a time they began to whisper, and even to eat.
This drew from Richard a very sharp rebuke,
in which he told them he would teach them better than to
come there and disturb a meeting in that way.
After the meeting, Richard conversed with Joseph Whitall, Jr., about what had occurred,
and asked whether he had gone too far.
Joseph answered somewhat cautiously,
yet holding up the view that mild reproof was better than sharp censure,
and that it might have been safer to speak to the offenders privately than publicly.
Richard became depressed in spirit,
and for six months did not open his mouth in the way of ministry.

About that time Joseph was in Philadelphia,
and learned that a great change had taken place in the two young men.
One of them had spoken acceptably in the meetings of Friends, and the other,
under the humbling operations of Grace, had changed his clothing, and put on plain dress.

When Joseph Whitall, Jr., returned home, he called on Richard,
and said he had something of interest to tell him, but he was afraid he would hurt him.
"`Oh, no,`" said Richard, "`I am too weak to lift a straw.`"
But when Joseph told the cheering news of which he was the bearer, Richard,
in his pleasurable excitement, brought his hand down on his knee with stinging force,
exclaiming, at the same time:
"`I will teach thee better than to interfere with my religious services in this way!`"
The cloud was now lifted,
and the next First-day Richard was again enabled
to exercise his remarkable ministerial gift.
The mention of Richard Jordan`'s name lifted the flood-gates of memory,
and quite a stream of incidents connected with him, flowed forth.
One of these showed that he knew how to administer a gentle caution, even if,
at other times, he followed the advice of the apostle to "`rebuke sharply.`"
A young man called upon him,
who thought he had been unfairly treated by the members
or officers of the meeting to which he belonged.
He poured his complaints into Richard`'s ear, who patiently heard the whole story,
and formed his judgment of the merits of the case.
He then told the young man that he was reminded of his own experience
when he landed in Liverpool after a rough voyage across the ocean.
His head was so unsteady that, as he passed up the street,
all the houses seemed to him to be vibrating as if shaken by an earthquake.
They were very high,
and the prospect was so dangerous that he sat down on a
step to consider what it was best for him to do.
Then he found that the motion was in himself.
What further advice, if any, he gave to the young man, was not mentioned;
but doubtless he felt that,
if the disturbance in his own mind was quieted by the influence of Grace,
the imagined harshness of his friends would disappear from view.

Benjamin Lay, who lived in Philadelphia in the early part of last century,
and was a noted opponent of slavery, was naturally a shrewd man, and was of a ready wit,
and thus those who disputed with him, were often more than matched.
When captain M`'Pherson, the privateersman,
undertook to make diversion for a company riding with him, at the expense of Lay,
who was walking into Philadelphia, he singularly failed.
"`Sir, your humble servant,`" cried M`'Pherson.
"`If thou art my servant, clean my shoes,`" retorted Lay.
Taken a little aback,
the captain then inquired if he could tell him the direct road to heaven.
"`Do justly, love mercy,
and walk humbly with thy God,`" was the prompt and appropriate answer.
Mortified, and doubtless conscience-stricken, the man of rapine and blood rode on,
feeling that he had met with a public rebuke which he dare not resent,
and that his attempt to raise a merriment at the expense of the humble philanthropist,
had but opened the way to his own mortification.

John Brown, of Barking, in Essex County, England, became involved in debt, and,
in a time of weakness, left his native place, without consulting his creditors,
and with his wife came over to Pennsylvania.
He took up his abode in Philadelphia,
where he exerted himself to earn an honest livelihood for the support of his family.
In the meantime Friends of Barking Monthly Meeting testified its disunity,
both with John and his wife, as having done that which the Truth did not allow of.
Years passed on,
John Brown maintained a fair and honorable character amongst his fellow-citizens,
and in the things of this world he was prosperous.
In the year 1717, when Thomas Chalkley was about making a voyage to England,
John Brown placed assets in his hands to meet all his indebtedness there,
which through the addition of seventeen years`' interest, had largely increased.
Friends of Barking having been informed of the circumstances,
issued a certificate to Philadelphia Monthly Meeting, dated Fifth Month 4th, 1718,
for the aforesaid John and his wife,
in which they say they "`find the creditors are now all paid to their satisfaction,
only four or five that we understood cannot be heard of,
the said Thomas Chalkley declaring he is ready to pay the rest as he can find them.
This we allow to be a noble act of honesty,
and by the said John Brown and his wife so doing,
hath gained reputation to themselves and our holy profession.
Being heartily glad of the good character we hear
of them since they came amongst you to settle,
we commend them unto you, desiring you tenderly to receive them,
and to watch over them in the Lord.
So with the salutations of dear love unto you,
we remain your friends and brethren in the precious Truth.`"

John Brown continued to reside in Philadelphia,
respected and esteemed amongst his fellow-professors and his neighbors, to his death,
which occurred about two years after the above certificate was issued.

=== The Neglected Call

When the field was white to harvest, and the laborers were few,
Heard I thus a voice within me, "`There is work for thee to do;
Come thou up and help the reapers; I will show thee now the way.
Come and help them bear the burden, and the toiling of the day.`"
For a more convenient season, thus I answered, will I wait,
And the voice, reproving, murmured, "`Hasten ere it be too late.`"

Yet I heeded not the witness, listening to "`Lo! here--lo! there,`"
Till I lost sight of the reapers in whose work I would not share;
Followed after strange devices--bowed my head to gods of stone,
Till like Ephraim, joined to idols, God had near left me alone.
But the angel of his presence followed on my erring track,
Setting here and there a landmark, if perchance to guide me back.

Onward yet I went, and onward, till there met me on the way,
A poor prodigal returning, who, like myself, had gone astray,
And his faith was strong and earnest that a Father`'s house would be
Safest shelter from temptation for such erring ones as he.
"`Read the lesson,`" said the angel, "`take the warning and repent.`"
But the wily tempter queried, "`Ere thy substance be unspent?`"

"`Hast thou need to toil and labor? Art thou fitted for the work?
Many a hidden stone to bruise thee in the harvest field doth lurk.
There are others called beside thee, and perchance the voice may be
But thy own delusive fancy which thou heard`'st calling thee;
There is time enough before thee all thy footsteps to retrace.`"
Then I yielded to the tempter, and the angel veiled his face.

Pleasure beckoned in the distance, and her siren voice was sweet,
"`Through a thornless path of flowers gently will I guide thy feet;
Youth is a rapid river, gliding noiselessly away,
Earth is but a pleasant garden, cull its roses whilst thou may;
Press the juice from purple clusters, fill life`'s chalice with the wine,
Taste the fairest fruits which tempt thee, all its richest gifts are thine.`"

Ah! the path was smooth and easy, but a snare was set therein,
And the feet were oft entangled in the fearful mesh of sin;
And the canker-worm was hidden in the rose-leaf folded up,
And the sparkling wine of pleasure was the fatal siren cup.
All its fruits were Dead Sea apples, tempting only to the sight;
Fair, yet filled with dust and ashes; beautiful, but touched with blight.

"`Oh! my Father,`" cried I inly, "`Thou hast striven, I have willed,
Now the mission of the angel of thy patience is fulfilled,
I have tasted earthly pleasures, yet my soul is craving food,
Let the summons thou hast given to thy harvest be renewed;
I am ready now to labor, wilt thou call me once again?
I will join the willing reapers as they garner up the grain.`"

But the still small voice within me, earnest in its truth and deep,
Answered my awakened conscience, "`As thou sowest thou shalt reap.
God is just, and retribution follows each neglected call,
Thou hadst thy appointed duty taught thee by the Lord of all;
Thou wast chosen, but another filled the place assigned to thee,
Henceforth in my field of labor thou mayest but a gleaner be.

"`But a work is still before thee--see thou linger not again,
Separate the chaff thou gleanest, bear it from among the grain;
Follow after these my reapers, let thine eyes be on the field,
Gather up the precious handfuls their abundant wheat-sheaves yield.
Go not hence to glean, but tarry, from the morning till the night,
Be thou faithful, thou mayest yet find favor in thy Master`'s sight.`"

Sarah Lynes +++[+++afterwards Grubb]
mentions in one of her letters, that when at Bath:
"`I was required to go into the pump-room,
amongst the giddy and the gay (a great number of
whom were there,) and stand as a sign for a while,
without saying a word; and then to declare, as the Lord by his Spirit gave utterance,
for about twenty minutes;
beginning with these words--'`I deem no further apology necessary for this conduct,
which may appear so strange to some of you,
than that I am here in pure obedience to my God.`'
Oh! the conflicts this sacrifice cost me,
were thoroughly equal to any capacity given me to endure.`"

Mary Ann Schimmelpennick describes the same scene with more details.
She says:

As my mother grew better, she frequently took me with her to the pump-room,
and she sometimes told me anecdotes of those she had seen there when a child.
On one occasion,
when the room was thronged with company--and at that time the visitors
of Bath were equally distinguished for rank and fashion--a simple,
humble woman, dressed in the severest garb of the Society of Friends,
walked into the midst of the assembly,
and began an address to them on the vanities and follies of the world,
and the insufficiency of dogmatic, without spiritual religion.
The company seemed taken by surprise, and their attention was arrested for a few moments:
as the speaker proceeded, and spoke more and more against the customs of the world,
signs of disapprobation appeared.
Amongst those present was one lady with a stern yet high-toned expression of countenance;
her air was distinguished: she sat erect, and listened intently to the speaker.
The impatience of the hearers soon became unrestrained:
as the Quaker spoke of giving up the world and its pleasures, hisses, groans,
beating of sticks, and cries of "`down, down,`" burst from every quarter.
The lady I have described arose with dignity, and slowly passing through the crowd,
where a passage was involuntarily opened to her, she went up to the speaker,
and thanked her, in her own name, and in that of all present,
for the faithfulness with which she had borne testimony to the Truth.
The lady added: "`I am not of your persuasion,
nor has it been my belief that our sex are generally deputed to be public teachers;
but God who gives the rule, can make the exception,
and He has indeed put it in the hearts of all his children
to honor and venerate fidelity to his commission.
Again, I gratefully thank you.`"
Side by side with the Quaker, she walked to the door of the pump-room,
and then resumed her seat.
This lady was the celebrated countess of Huntingdon.

The following experience of Thomas Ellwood, in 1660,
illustrates the position taken by Friends of that day on the first day of the week.
He says:

I had been at Reading, and set out from thence on the first day of the week,
in the morning,
intending to reach (as in point of time I well might) where a meeting was to be that day.
When I came to Maiden Head I was stopped by the watchman
laying hold on the horse`'s bridle,
and telling me I must go with him to the constable`'s, for travelling on Sunday.
Accordingly, I suffered him to lead my horse to the constable`'s door.
When we got there, the constable told me I must go before the warden,
who was the chief officer of the town; and he bid the watchman bring me on,
himself walking before.
Being come to the warden`'s door, the constable knocked,
and desired to speak with the warden.
He thereon quickly coming to the door, the constable said: "`Sir,
I have brought a man here to you, whom the watch took riding through the town.`"
The warden began to examine me, asking: Whence I came and whither I was going.
I told him I came from Reading, and was going to Chalfont.

He asked me why I travelled on that day.
I told him I did not know that it would give offence to ride or to walk on that day,
so long as I did not drive any carriage or horses laden with burdens.

"`Why,`" said he, "`if your business was urgent,
did you not take a pass from the mayor of Reading?`"

"`Because,`" I replied, "`I did not know or think I should need one.`"

"`Well,`" said he, "`I will not talk with you now,
it is time to go to church--but I will examine you
further anon;`" and turning to the constable:
"`Have him to the inn, and bring him before me after dinner.`"

The naming of an inn, put me in mind that such public houses were places of expense,
and I knew I had no money to defray it, wherefore, I said to the warden:
"`Before thou sendest me to an inn which may occasion some expense,
I think it needful to acquaint thee that I have no money.`"
At that the warden stared, and turning quickly upon me said:

"`How! no money?
How can that be?
You do not look like a man that has no money?`"

"`However I look, I tell thee the truth, that I have no money,
and I tell it to forewarn thee, that thou mayest bring no charge upon the town.`"

"`I wonder,`" said he, "`what art you have got, that you can travel without money,
you can do more, I assure you, than I can.`"

I making no answer, he went on and said: "`Well, well, but if you have no money,
you have a good horse under you, and we can distrain him for the charge.`"
"`But,`" said I, "`the horse is not mine.`"

"`Ho! but you have a good coat on your back, and I hope that is your own.`"

"`But it is not,`" said I, "`for I borrowed both the horse and great-coat.`"
With that the warden, holding up his hands, smiling, said:

"`Bless me!
I never met with such a man as you before!
What! are you sent out by the parish?`"
Then turning to the constable, he said: "`Have him to the Greyhound,
and bid the people be civil to him.`"

Accordingly, to the Greyhound I was led, my horse put up, and I put into a large room,
and some account given of me, I suppose, to the people of the house.

This was new work for me, and what the issue would be, I could not foresee;
but being left there alone, I sat down and retired in spirit to the Lord,
in whom alone was my strength and safety; and of Him I begged support,
even that He would be pleased to give me wisdom and right words to answer the warden,
when I should come to be examined before him again.

After some time, having pen, ink and paper about me,
I set myself to write what I thought would be proper if the occasion required,
to give to the warden.
While I was writing, the master of the house being come home from worship,
sent the tapster to me to invite me to dine with him.
I bid him tell his master that I had no money to pay for dinner.
He sent the man again to tell me I should be welcome
to dine with him though I had no money.
I desired him to tell his master that I was very sensible of his civility and kindness,
in so courteously inviting me to his table, but I had not the freedom to eat of his meat,
unless I could pay for it; so he went on with his dinner, and I with my writing.
But before I had finished what I had on my mind to write, the constable came again,
bringing with him his fellow constable.
This was a brisk genteel young man, a shop-keeper in the town, whose name was Cherry.
They saluted me very civilly, and told me they came to take me before the warden.
This put an end to my writing, which I put into my pocket, and went along with them.

Being come to the warden, he asked me the same questions he had asked before,
to which I gave him the like answers.
Then he told me the penalty I had incurred;
which he said was either to pay so much money or lie so many hours in the stocks,
and asked me which I would choose.
I replied: "`I shall not choose either, and I have already told thee I had no money;
though if I had money, I could not so far acknowledge myself an offender as to pay any.
But as to lying in the stocks,
I am in thy power to do unto me what it shall please the Lord to suffer thee.`"
When he heard that, he paused awhile,
and then told me he considered I was but a young man,
and might not perhaps understand the danger I had brought myself into,
and therefore he would not exercise the severity the law awarded me.
In hopes that I would be wiser hereafter, he would pass by this offence and discharge me.
Then putting on a countenance of the greatest gravity, he said: "`But young man,
I would have you to know, that you have not only broken the law of the land,
but also the law of God, and therefore you ought to ask Him forgiveness,
for you have highly offended Him.`"

"`That,`" said I, "`I would most willingly do,
if I were sensible I had offended Him by breaking any law of his.`"

"`Why!`" said he, "`do you question that?`"

"`Yes, truly,`" said I, "`for I do not know of any law of God,
that doth forbid me to ride on this day.`"

"`No, that is strange!
Where, I wonder, were you bred?
You can read can`'t you?`"

"`Yes,`" said I, "`that I can.`"

"`Don`'t you thus read,`" said he, "`the commandment;
'`Remember the Sabbath day to keep it holy,`' etc.?`"

"`Yes,`" I replied, "`I have read it often and remember it well.
But that command was given to the Jews, not to the Christians, and this is not that day,
their Sabbath was the seventh day, but this is the first day of the week.`"

"`How is it,`" said he, "`you know the days of the week no better.
You need to be better taught.`"

Here the young constable, whose name was Cherry, interposed, and said: "`Mr. Warden,
the gentleman is right as to that, for this is the first day of the week,
and not the seventh.`"

This the old warden took in dudgeon, and looking severely on the constable, said:
"`What! do you take upon you to teach me?
I`'ll have you know, I`'ll not be taught by you.`"

"`As you please, for that, sir,`" said the constable,
"`but I am sure you are mistaken on that point, for Saturday was the seventh day,
and you know yesterday was Saturday.`"
This made the warden hot and testy, and put him so much out of patience,
that I feared it would have come to a down-right quarrel betwixt them,
for both were confident, and neither would yield.
And so earnestly were they engaged in the contest,
that there was no room for me to put in a word between them.
At length, the old man having talked himself out of wind, stood still awhile,
as it were to take breath, and then bethinking of me, he turned, and said:
"`You are discharged, and may take your liberty.`"

"`But,`" said I, "`I desire my horse may be discharged, too, else I know not how to go.`"

"`Aye,`" said he, "`you shall have your horse,`" and turning to the other constable,
who had not offended him, he said, "`Go see that his horse is delivered to him.`"

Away thereupon, went I with the constable,
leaving the old warden and the young constable to compose their difference as they could.
Being come to the inn, the constable called for my horse to be brought, which done,
I immediately mounted and began to set forward.
But the hostler, not knowing the condition of my pocket, modestly said to me, "`Sir,
don`'t forget to pay for your horse`'s standing.`"
"`No, truly,`" said I, "`I don`'t forget it, but I have no money to pay it with,
and so I told the warden before.`"
"`Hold your tongue,`" said the constable, "`I will see you`'re paid.`"
Then opening the gate, they let me out, the constable wishing me a good journey,
and through the town I rode without further molestation,
though it was as much the Sabbath I thought, when I came out as when I went in.
A secret joy arose in me as I rode away,
that I had been preserved from doing or saying anything which might
have given the adversaries of Truth advantage against it,
and against the Friends, and praises sprang up in my thankful heart,
to the Lord my Preserver.
It added not a little to my joy,
that I felt the Lord near unto me by his witness in my heart to check and warn me,
and that my spirit was so far subjected to Him as readily to take warning.

With joy and thankful congratulations his friends at Chalfont, welcomed his return.
They had been anxious about him, knowing that he intended to be with them at meeting.

The manner in which the Head of the Church opens the way
before those whom He sends forth in his service,
is often cause of humble gratitude to those who are sensible of their
dependence on a higher power than their own efforts and abilities.
This is so frequent an experience,
that the following simple memorandum has nothing about it peculiarly striking;
yet it is a pleasant illustration of the manner in
which the obedient disciple is sometimes led.

In the Eleventh Month of 1849, Mary Davis, a minister of Dartmouth, Mass.,
received permission from her Monthly Meeting to visit in Gospel love, North Ashburnham,
Mass., a place where she was an entire stranger.
Sickness in her family and other difficulties,
delayed the accomplishment of the service until the Eighth Month of the following year,
when with suitable companions she left her home.
Leaving the cars at the nearest station,
they procured a carriage to convey them to the house of a person residing at North Ashburnham,
whose name had been furnished them.
On their way, they stopped for some purpose at a tavern;
and as they sat in the parlor felt depressed at the prospect.
The weight of the religious concern pressed upon them;
they were strangers in a strange place;
there was no member of their own Society to receive them at their journey`'s end;
and it was very trying to them to think of driving to the house
of a person whom they did not know and requesting to be taken in.
As Mary expressed it, "`they were very long-faced.`"
While thus communing together,
a young man came in who had ridden with their driver from the railroad depot.
He soon discovered somewhat of their uneasiness,
and let them know that he was a son of the man to whose house they wished to be taken,
and that he would drive them himself the remainder of the way.
On reaching their journey`'s end they were very kindly received and cared for.

The person to whose house they had come was the proprietor
of an establishment for making spools for cotton.
His factory buildings had recently been burned;
and several members of his family had gathered home to sympathize with him,
so that there was quite a company assembled in the evening.
Mary thought that a suitable time to make some explanations;
so she told them of the order pursued by Friends when their
ministers felt a concern to travel in the work of the Gospel;
and stated that they had with them the minutes of their Monthly Meetings,
which might be read if the company wished to hear them.
Their hosts expressed much admiration of the beautiful order observed by our Society;
and had not before known that any religious body exercised such a care over their ministers, etc.
They freely entered into Mary`'s concern, offered their meeting-place for her use,
and assumed all the care of making arrangements, giving notice, etc.

The meeting was held at two o`'clock the next afternoon.
The factory having been burned, all the operatives were at liberty to be present,
and the Friends all concluded that it was one of
the most satisfactory meetings they ever attended.
The congregation consisted of people who had been somewhat
dissatisfied with their former religious connections,
and had been drawn together from several different denominations.
They had joined in erecting a building which they called the "`Union Church.`"
Mary thought them a people who were seeking after the life of religion,
and who might do well if they did not take up a rest short of the true rest.

Some months afterwards,
the pastor and officers of the congregation drew
up a paper addressed to her Monthly Meeting,
in which they spoke of the good impression made upon
their people by the visit and labors of the Friends,
which they believed to have been performed under the influence of the Spirit of Truth;
and they intimated that they would be glad to receive a similar visit,
if any of the Friends should be moved to come that way.

In my note-book of 1848, I find the following anecdote of Richard Birdsall, a minister,
related by him to the Friend by whom it was communicated to me.
He married a gay girl who was not a member of our Society,
and was visited by a committee of the Monthly Meeting on account of this breach of discipline.
Though his own conduct was not consistent with the principles of Friends,
yet he felt in his heart that the members of the committee
were not under the influence of the Spirit of Truth,
so he did not manifest a humble disposition,
but could retort upon them in a saucy manner.
They came to him in the name of Jesus, but without his power,
and the evil spirit in him overcame them.

Those who are concerned to live in communion with their Heavenly
Father are often enabled to communicate instruction to others,
even in the course of their ordinary conversation.
The late Rachel Price mentions that:

In the year 1782, in the Fifth Month, I was in the city of Philadelphia.
In passing down Second Street, near Market,
by the gate which entered into the meetinghouse yard, I met a plain Friend,
of small stature.
He took me by the hand, saying, "`Whence comest thou?`"
I told him I was from Nantmeal, a small meeting about forty miles from that city,
and my name was Kirk.
He said he sometimes asked people whether they were Jews or of Ashdod,
when they gave him but one name.
I then told him mine was Rachel Kirk.
He said, "`Mine is Samuel Emlen.`"
He then inquired if I was a relative of Rebecca Kirk`'s. I told him she was my sister.
He desired his love to be given to her,
and said he had met with her at the funeral of Israel Jacobs, and felt that he loved her.
I told him I thought I should remember it when I saw her again,
but she had married and removed to some distance.
After inquiring whom she had married and where settled, he paused, then said, "`Rachel,
it will be thy turn next, and be careful that thou place thy affections upon virtue;
let nothing short of virtue sway thy mind.
If anything inferior gain preeminence in thy view, difficulties may ensue;
but if piety and virtue govern thy mind in making choice of a companion,
you may walk hand in hand through life happily together,
and be true helpmeets to each other.`"
He held me by the hand all the time he was speaking, then, bidding me farewell; added:
"`Now, mind what I have said to thee.`"
I thought it altogether a remarkable interview with
an entire stranger in a crowded market-place,
people passing and repassing all the time.
It was of great use in settling my mind to make a prudent choice,
which was soon after brought to the trial.
I had a few days previous become acquainted with Philip Price, who is now my husband,
with whom his prediction has been verified and as far realized as can
be expected in this probationary state of trial in order for our refinement
and preparation for a more perfect state of existence.

Many years ago, our worthy friend, John Simpson, lodged at our house,
on his way from Concord to Caln Quarterly Meeting.
He was in company with several other Friends.
He was very conversable, but the conversation was mostly upon worldly affairs,
on his getting along in the management of a large farm, etc.

I felt somewhat disappointed, expecting to be instructed and edified spiritually.
I never before had the opportunity of being in company with him,
but had previously the privilege of hearing him from the gallery,
in a very powerful manner,
declaring the truths of the Gospel with great weight and authority, once,
not a great while before, in a very particular manner, at Concord Quarterly Meeting.
I thought I had never before heard the great mysteries contained
in the Book of Revelations spoken of in such a manner;
the opening of the seals, the slaying of the witnesses,
their dead bodies lying in the streets of the great city, which, spiritually,
is called Sodom, or Egypt, where also our Lord was crucified,
as in the hearts of the wicked of all generations, the voices of the angels,
and the golden candlesticks, which represent the seven churches,
with the different messages to each of them.
I thought he was at that time favored to feel and
hear what the Spirit saith unto the churches,
and authorized to set forth,
in a clear point of view the spiritual and true meaning of those hidden mysteries,
which cannot be rightly understood but in the opening
of them by the Spirit of Truth in the heart,
as it is beyond human comprehension unaided by Divine revelation.

I had a desire to hear him converse on these sublime subjects,
that I might have the opportunity of querying of him in
a familiar manner something further of his views.
He, however, continuing his conversation on worldly affairs,
mentioned that he was in the habit of employing such hands
as offered particularly in harvest--temperate or intemperate.
He thought the latter must have employ,
and they knew he would not allow them any intoxicating drink.
He said he had at one time a large company of different characters,
some of them very indifferent.
They began to banter each other, to run on each other, pushing and making bad work,
destroying the wheat by tramping and slashing.
He was in the field at some distance gathering sheaves.
When he saw them he thought he would go immediately
and "`turn some of them out of the field in a hurry.`"
So he hastened towards them, when a voice intelligibly saluted his inward ear: "`John,
govern thyself before thou art rightly qualified to govern others.`"
He sat quietly down as soon as he could, desiring to be enabled to govern his own mind,
and prepared to instruct and reprove them in a proper manner.
After a while he went up to them and requested them all to stop;
as he had something to say; after which he addressed them, as nearly as I can recollect,
in substance as follows:
"`Do you not all think it is a great favor to have such a field of grain?
Is it not a favor from the all-bountiful Creator and Preserver of all things?
Do you not think it is very wrong to waste and destroy
what a kind Providence has bestowed for our benefit?`"
They were generally willing to allow it to be so.
He then desired all who were prepared to do so, to go quietly and steadily to work.
They all went; and he had no more difficulty with them.
He felt that if he had gone on in the disposition in which he started,
he would have made bad worse,
and brought condemnation over his own mind and reproach on the Truth.

Notwithstanding his conversation was on worldly concerns,
there was great instruction conveyed to my mind by it.
Situated (as we were) on a large farm,
with a family of different dispositions to be considered,
I felt the necessity of keeping self under proper control,
in order to a right regulation of those about me.
His remarks have been a watchword to me,
often recurred to in silence for my own improvement;
and I have recommended them to others as the experience of a valuable Friend.
Thus, He who knows what we stand in need of, even before we ask it,
grants that kind of instruction that we require.
No doubt I stood more in need of counsel at that time in the common walks of
domestic concerns than in the more sublime views of the mysteries of the kingdom,
which are hid from the wise and prudent of this world and revealed to babes.

=== John Richardson

When in America, he met with a remarkable deliverance from peril, in going from Salem,
Massachusetts, to Dover.
There was a river to cross.
He says:

A Friend took my horse, with two more, into the boat,
and by the time I came to the river side the boat was sinking,
and the ferrymen made a lamentable cry, saying:
"`The boat is sunk and we shall all be drowned.`"
There was but one Friend in the boat with the boatman.
Hearing the noise and floundering of the horses when tumbling into the water,
I called to the men to be sure to take care to free
themselves of all the tackling of the horses,
as bridles, stirrups, etc., and to catch hold of my horse`'s tail,
and he would bring them both on shore,
but if they trusted to the tackling when the horses swam they would fail them,
unless very strong, and to hold by the bridle was the way to drown both man and horse.
The boatman, being a lively youth, took my advice, caught hold of my horse`'s tail,
and calling to my horse, he came quickly, with the man, ashore,
but left the honest old Friend, Ezekiel Waring,
to whose house we intended to go that night, in the river, floating to the neck,
a hundred yards from the shore.
He missed taking my advice, and caught hold of the stirrup, and the girth broke,
which brought off the saddle and pillion, and the oar of the boat and his hat, which,
with the pillion-seat being on his arms, just bore up his head above water.
His poor wife, seeing the danger to which her husband was exposed,
fell into a fainting fit, there being neither house,
man or boat to be seen on this side of the river but ourselves.

The ferryman found a canoe, and coming to us, asked if Ezekiel was alive.
I told him he was, but very weak, for I had often heard him blubber in the water.
I encouraged him, that he might not faint in his mind.
I told him I yet believed his life would be preserved.
He would very faintly say, unless help came, he could not hold it long.
I went on by the water side, and laid me down often on the land,
not much regarding wet or dirt,
and I directed the man with his canoe where the poor Friend was,
and desired that he would turn the stern of his canoe to him,
as he could not lift him into the canoe,
neither to let him lay his hand on the broadside of it, lest he should overset it.
He did so, and brought him gently on shore,
to the great joy of his loving wife and of us all.
I bid the boatman fetch the boat on shore by the rope,
and then go and carry Ezekiel in the canoe to the inn on the other side of the water,
where he might dry, warm and refresh himself till we came.
In the meantime we cleared the boat of water, and got well over.
We found the good old Friend finely and well recruited,
and got to his house about midnight,
where we were glad and our hearts were full of praises to
the Lord for this great and eminent deliverance and preservation.

=== Anecdote of John Richardson

John Richardson says when in this land:

Having it on my mind to visit a meeting up the river called Perquimons,
west of the river Choptank, and being on the east side,
Henry Hosier and some more Friends set forward with me in a small boat,
not in good condition, with only one small sail.
We set out, as we thought, in good time to reach our desired port,
but when we were upon the great river--which is ten miles over the shortest way,
according to my recollection,
though the manner of our crossing it made it more--the wind veered much against us.
It rained hard, and was very dark, so that we could scarcely see one another,
and the water broke so much into the boat, that it was one man`'s work to heave it out,
and all our company were discouraged, and most very sea-sick.
Henry Hosier, of whom I had the most hope for help,
said that he could not steer any longer.
Notwithstanding the extreme darkness, the roughness of the waves,
boisterousness of the wind, and the hard rain, unwell as I was,
I was obliged to undertake the steering of the boat,
and not without some conflicts of mind, having no certainty from any outward rule,
what way we went.
Having no fire, and the boat open, we could not have any light to see our compass;
but my faith was in the Lord, that He would bring us to shore;
and I kept the boat as near the wind as she could sail, and told my poor, sick,
helpless company, I believed that we should not perish, although we might miss our port.
The like imminent danger I think I was never in before upon any water;
but renowned over all be the great name of the Lord forever,
we put into the mouth of our desired river, as though we had seen it in the day,
or steered by a compass, neither of which we had the benefit of for several hours.

Here we went on shore and made a great fire under the river`'s cliff,
and about midnight the moon rose, it cleared up and froze and was very cold.
My companions falling asleep, I turned them over,
pulled them from the fire as it increased, and put them nearer as it failed,
but could not keep them awake.
I sought logs of wood, and carried them to and mended the fire,
which was work enough for the remaining part of the night; but morning being come,
we got into our cold, icy boat, and sailed away towards the meeting.
When we were come among Friends, notice was given of a stranger being there,
and a heavenly and sweet meeting it was,
so that we thought we had a good reward for all our troubles;
blessed be the name of the Lord now and forever, for He is worthy;
although He may see good to try us, sometimes one way, sometime another.
How should we know that we have any faith, if it be not tried?
How shall we know that we have any true love to God, if it never be proved?
The trial of the true believer`'s faith is more precious than gold.
The excellent saying of Job came into my mind, "`Behold I go forward,
but He is not there, and backward, but I cannot perceive Him; on the left hand,
where he doth work, but I cannot behold Him; He hideth himself on the right hand,
but I cannot see Him.`"
And then like a man in the true faith he saith: "`But He knoweth the way that I take,
and when He hath tried me,
I shall come forth as gold;`" and the more vehement the fire is,
the more it destroys the dross, and the more pure and weighty the gold is.

=== A Tribute to Departed Worth

Thoughts during Philadelphia Yearly Meeting for 1862

Once more to the old gathering place we come,
A band of sisters, to our solemn feast;
Our swelling ranks in reverent silence wait
No pleasing ordinance, no rite of priest.

The Church and her best interests are the themes
That claim the outward ear; the inward eye
Of many a bowed and suppliant soul is turned,
For holy help to Him who ruleth them on high.

The mothers of our Israel, in their place,
Give us such counsel as pertaineth most
To our best interests; but one face is gone,
The dear, familiar face of her the loved and lost.

By the swift mandate of its God recalled,
The noble soul that labored for our weal,
No longer now for Zion pleads and prays;
That voice in its rich cadences is still.

Hers was no eloquent and rounded phrase;
No flowery language, pleasing to the ear;
But Truth`'s directness, glistening many an eye
Stony and cold, with fresh, unbidden tear.

So forcible that strong ones bowed and shook
Beneath the terrors of her Gospel hand,
So calm and deep and earnest in its strength,
Yet simple, that a child might understand.

And wielded by a woman`'s feeble arm,
The Spirit`'s sword cleft the abodes of sin;
Making an opening for the holy law
Of Truth and righteousness to enter in.

To many a darkened, hapless couch of pain
She was the instrument of hope and peace,
Sent by her Master, in his holy power,
To minister unto the mind`'s disease.

And there are those aroused to better things,
And rescued from their course in ruin`'s way,
Who, humbly waiting in the light of Christ,
Still live to bless that favored woman`'s day.

While to the timid, trembling child of hope,
Longing for way-marks on the desert drear,
Like the fresh breezes from a land of flowers,
A strength in weakness came her words of cheer.

She asked no blessing from those dying lips,
She shrank from praise that grateful hearts bestow,
But ever sought the glory of her Lord,
His call to answer, and his will to know.

So moved she in her true appointed sphere,
Erectly standing, like a tower of strength,
Bearing her burdens patiently and well--
The angel of deliverance came at length.

My mother! at the right hand of thy God,
Dying with hallelujahs to his praise,
The richest guerdon of thy labors won
Thy Saviour`'s blessing on thy latter days!

My mother! thou hast welcomed to thy home
Of the redeemed in Christ, the honored dead,
My second mother; on whose Gospel breast
I, childlike, oft refreshed my fainting head.

Aye, more, she was the first to wake my soul
From its deep slumbers in the courts of death,
Where in a false and treacherous ease it lay,
All idly wasting its immortal breath.

Oh mothers! in your holy home of light,
Where not the semblance of a shadow lives,
My errors and temptations cause no pang,
And the dear Saviour grace sufficient gives.

My heart rejoices in your high estate,
But mourns the loss of friends so good and true;
Its greenest memories of departed worth,
Its holiest aspirations live with you.

=== Samuel Fothergill`'s Acknowledgement

I know my sins are so many, and so obvious to every one,
that it is impossible and needless to recount and remark upon them;
for I was then in the bond of iniquity,
though it has pleased the Father of mercies to bring
me since into the very gall of bitterness,
and into anxiety of soul inexpressible; yea,
not to be apprehended by any but those who have trod
the same path and drank of the same cup;
yet blessed be the name of God, He who hath kindled breathings in my soul after Him,
would sometimes break in upon me, and though the waves of Jordan have gone over my head,
his supporting arm was underneath, that I should not be discouraged.
He, in his infinite love,
has given me to understand that the things which
belong to my peace were not utterly hid from my eyes;
that though I had drunk up iniquity as an ox drinketh up water,
although I had exceeded all others in sin, had long done despite to Him,
yet there was mercy with Him that He might be feared.

I can truly say that, during the time of my first conviction,
my lips quivered and my belly trembled, that my soul might rest in the day of trouble.
I choose not to write this,
but I cannot be easy unless I call others to the like enjoyment.
In bowels of tender love to you do I again salute you, and take my leave of you,
with strong desires that you who are advanced in years and favored in the Lord,
may remember me when it is well with you; and that I may be again preserved,
though beset with many temptations on every hand.
The Lord in mercy be near you, saith my soul.

His father remained in America two years.
He had parted from Samuel with feelings of intense anxiety and disapprobation,
even to sternness; and although he had received consoling accounts of his change,
first met him, after his return, under these memorable circumstances.
Soon after that return, John Fothergill went to the Quarterly Meeting at York,
which was large, and attended by many Friends from different parts of the nation.
His company was very acceptable, and the occasion was, in a peculiar degree,
solemn and instructive.

From some accidental circumstance,
he did not arrive in York until the morning of the day of the meeting,
which was gathered when he entered the house.
After a short period of silence, he stood up and appeared in testimony; but,
having proceeded a short time,
he stopped and informed the meeting that his way was closed;
that what he had before him was taken away and given, as he believed, to another.
He resumed his seat, and another Friend immediately rose, and, taking up the subject,
enlarged upon it in a weighty and impressive testimony, delivered with great power.
At the close of the meeting,
John Fothergill enquired who the Friend was that
had been so remarkably engaged amongst them,
and was told that it was his own son, Samuel!
After such a parting as had been between them, what a meeting was this!

The good old man wept and rejoiced over his son with no common joy,
receiving him as one restored to him from the dead.

=== Conversion of Samuel Neale

Samuel Neale inherited from his grandfather a good estate,
and as he was endowed with an excellent understanding, and a social, lively disposition,
his society was eagerly courted by fashionable, gay young men,
who led him into much dissipation.
Being apprenticed to a merchant in Dublin, he became intimate,
during his residence there, with several of the collegians,
and took liberties inconsistent with the principles in which he had been educated.
He says: "`We sometimes frequented the play-house, and after these amusements,
when on my return home, oh,
the anxiety and remorse that covered my mind and overwhelmed my spirit!
I was then willing to covenant to be more careful in future,
and avoid what now seemed so distressing; but when those seasons of diversion approached,
I felt my inclination to arise with redoubled strength, and my passion for gratifying it,
like an irresistible torrent, insurmountable;
so I went like a man bereft of understanding.`"

He was soon, however, effectually arrested in his wild career.

I remember being at a play one evening, up late that night,
and lying pretty long next morning, which was First-day.
An acquaintance asked me to go to meeting,
and at the same time informed me there were to be strangers there,
telling me who they were.
I said I would, for in my worst state, I generally attended meetings.
So to meeting I went, and it was a memorable one to me,
for my state was opened to that highly favored instrument in the Lord`'s hands,
Catherine Payton (who, with my beloved friend, Mary Peisley was visiting the churches),
so that all I had done seemed unfolded to her in a wonderful manner.
I was as one smitten to the ground, dissolved in tears, and without spirit.
This was a visitation from the Most High beyond all others I had as yet witnessed.
I was so wrought upon by the power and spirit of the holy Jesus that, like Saul,
I was ready to cry out, "`Lord, what wouldst thou have me to do?`"
I was almost ashamed to be seen so bedewed with tears,
and slunk away from the meeting to get into a private place.

I joined company with a religious young man,
and forsook my gay companions and associates, who beheld me with astonishment.
The change was very rapid, and my doubts and fears respecting myself were very great,
so that I could not trust myself in my former company,
lest my innumerable frailties should prove too powerful for all my good resolutions.
So I abode still, and kept near these messengers of glad tidings to me.
I went with them to Bandon and Kinsale,
and the same powerful dispensation of Divine virtue followed me; breaking in upon me,
and tendering my spirit in a wonderful manner,
in public meetings as well as in private opportunities;
which drew the attention and observation of many.
When I returned to Cork, I kept as private as I well could,
and resolved to quit all my worldly pursuits,
and follow the gentle leadings of that heavenly light
which showed me the vanity of worldly glory,
and that the pleasures of sin are but as for a moment.

Our beloved Friends intended for the province meeting at Limerick,
and took Kilcommon Meeting in their way, whither they went.
I also went; and a considerable degree of concern grew in my mind,
both by day and by night.
Their company was precious to me, their conduct and conversation strengthening,
and the inward manifestations of heavenly goodness vouchsafed,
were my crown and rejoicing.
My eyes were measurably opened to behold my insignificance, rebellion and backsliding.
I saw the perverseness of my nature, and that in me, as man, there dwelt no good thing.
I thought I saw that if I missed the present opportunity of coming as out of Babylon,
I was lost forever; I was come to the length of my chain, my measure was full,
and if I did not embrace the present offer, ruin and destruction would be my portion.
These sights of my condition stimulated me to exert myself in watchfulness and care,
to pursue with ardency the sense that opened in my own mind,
and to feel after the spring and virtue that I witnessed there,
which far exceeded every gratification that I knew before in this life.
My hunger and thirst after righteousness were great;
I delighted much in reading and retirement;
worldly things had no charms for me at this season, when the new creation began to dawn.
